### ISSUE TITLE
Upgrade SQLite to 3.8.9

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#1000]
There may be bugs: http://lcamtuf.blogspot.com/2015/04/finding-bugs-in-sqlite-easy-way.html

**Comment by marpaia** [comment]
Link to original ticket: https://www.sqlite.org/src/info/a59ae93ee990a55

**Comment by theopolis** [comment]
A dropin of the 3.8.9 amalgamation source compiles and passes our unit tests without modification. Not sure if any of these bugs come from the shell's query parsing workflows. Updating the shell will be a little more work.
