### ISSUE TITLE
Cannot create packages without git metadata

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1007]
The `make packages` command runs a `git describe --tags` within to determine the most recent version tag. If one downloads osquery from github's source tgz the metadata and version determination method is missing.

1. We can provide a make variable for the package builder to manually set the version.
2. We can touch a file when a tag is generated that includes the tagged version string.

Any other ideas?

**Comment by theopolis** [comment]
We might be able to fall back to `git describe --always` too.

**Comment by marpaia** [comment]
If you don't have git metadata, you won't be able to init submodules either, so build will fail also. This came up many moons ago and we decided to not support tar.gz downloads of the code for build. Do you think we should?

**Comment by theopolis** [comment]
We could fallback to a "unknown-version" string too!

**Comment by marpaia** [comment]
What if we published a tar.gz which had the version interpolated and third-party downloaded? We could put that somewhere, but I think the problem here stems from when people click the download buttons on the github release pages.

**Comment by theopolis** [comment]
[Fixed](https://github.com/facebook/osquery/blame/master/tools/deployment/make_linux_package.sh#L19)
