### ISSUE TITLE
Question: enrollment_tests failures

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1009]
I know we have some flaky tests, I'm responsible for most :'(

But I noticed [this](https://jenkins.osquery.io/job/osqueryPullRequestBuild/920/TargetSystem=centos7/console):
```
24/32 Test #24: enrollment_tests .................***Failed    0.01 sec
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from EnrollmentTests
[ RUN      ] EnrollmentTests.test_enroll
unknown file: Failure
C++ exception with description "Connection refused" thrown in the test body.
[  FAILED  ] EnrollmentTests.test_enroll (2 ms)
[----------] 1 test from EnrollmentTests (2 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (2 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] EnrollmentTests.test_enroll

 1 FAILED TEST

```

I'm wondering if there are any quick fixes to make this more reliable?

**Comment by marpaia** [comment]
I think this is the same thing as http_tests. The quick dirty fix is to sleep in between launching the thread and running the tests (give the http server a few milliseconds to start), unless you can think of something more crafty.

**Comment by theopolis** [comment]
Ideally we should std::promise over sleeping in tests. But a stop gap of micro sleeping is preferred to refactoring our tests. The tech debt is better crushed when we have time to refactor all our test sleeps.

**Comment by theopolis** [comment]
I *think* this was caused by not-properly torn down sockets. The OS is picky about hard-coded ports and inproper socket shutdowns. The new set of tests picks a port at random. There's still chance to intersect, but it's much lower and hopefully tolerable.
