### ISSUE TITLE
--database_cache_expire flag

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#1011]
Some people have asked for a way to expire the scheduled query cache after a certain amount of time.

**Comment by theopolis** [comment]
Suggested name: --database_expiry or --database_cache_expire. It'd be nice to have "database" in the front for easy grouping of feature-flag organization

**Comment by marpaia** [comment]
Good call, @theopolis.

**Comment by theopolis** [comment]
This is blocked from the modifications to `launchQuery` in snapshot query diffs.

**Comment by theopolis** [comment]
We'll land and document snapshot queries for the next release, a new type of scheduled query, that may achieve some of a cache expiry effect. I vote to table this expiration feature until post 1.4.5.

**Comment by theopolis** [comment]
@marpaia we can label this #wontfix and ask folks to use snapshot queries instead? Do you see a value in expiring non-snapshots?
