### ISSUE TITLE
Create documentation for file integrity monitoring

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#1014]
We don't have any docs for how to do FIM in osquery, even though we support the capability.

**Comment by arirubinstein** [comment]
Started some work on this here:
https://github.com/arirubinstein/osquery/blob/3bfd6890ecb91bf124845d92302f6ebe349b4c45/docs/wiki/deployment/file-integrity-monitoring.md

**Comment by marpaia** [comment]
![image](https://cloud.githubusercontent.com/assets/927168/7281757/631a1d06-e8e0-11e4-923c-c3021bf0f20a.png)

**Comment by arirubinstein** [comment]
re-working the pull request to reflect some of the binary changes and new config schema mentioned here https://github.com/facebook/osquery/pull/1029

**Comment by theopolis** [comment]
Merged: https://github.com/facebook/osquery/pull/1072#merged-event
