### ISSUE TITLE
[RFC] HTTP-based logger plugin

### ISSUE THREAD

**Issue by jedi22** [facebook/osquery#1015]
Abstract
=
Now that we have enrollment and configuration plugins done, we need to get logs from the client, to a central log aggregation point.

The logging plugin would be really slow, and create lots of network overhead if we made a request every time we wanted to log something, so we'll need a buffering mechanism and this should be controlled through options in the configuration.

Once the buffer is full, or a certain period of time has passed, the results will be packaged together in a JSON blob and sent to the logging endpoint. If the server responds that the records we received successfully, then the records are removed from the buffer, or if the buffer was full, it will be cleared entirely.

Possible Errors ➜ Possible Solutions
=
<b>The host is not on the network</b>
The logs will continue to buffer until it is.

<b>There are buffered logs and the process is killed</b>
Logs will be stored in RockDB persistently so process reboots shouldn't be a problem.

<b>The server responds that the client key is invalid</b>
Force a re-enroll and try again.

<b>There are more logs stored than can fit in a single post</b>
Add logs into request until it is too large, remove the last one and send. On success remove them from the database and loop.

<b>There is a single log of greater size than max post size</b>
Drop the log, this should not reasonably ever happen.

**Comment by marpaia** [comment]
some more failure cases to consider:

- What happens if the process is killed between log flushes?
- What happens if the host is not on the network?
  - What happens when the host isn't on the network and surpasses the max log size quota?
-

**Comment by jedi22** [comment]
Updated with some proposed solutions.

**Comment by marpaia** [comment]
Nice, @jedi22.

To spitball, I would think that this would be a logger plugin which started a service thread (the to-be-written LogForwarder) class. Maybe a `LogForwarder<HTTPTransport>`, so that we could hot swap out transports later on?

I feel like the logger plugin should be as simple as possible, so that we can easily add new plugins that use the same functionality using different transports.

Maybe something like:

```cpp
class AwesomeLoggerPlugin : public LoggerPlugin {
 public:
  osquery::Status logString(const std::string& s) {
    auto log_forwarder = LogForwarder<HTTPTransport>::getInstance();
    return log_forwarder->queueString(s);
  }
}
```

**Comment by jedi22** [comment]
So then should any responsibilities be handled by the plugin in your mind, or should they all be handled by the forwarder? Maybe database insertions could be handled by the plugin? Thoughts?

**Comment by marpaia** [comment]
Meh, I think that the config plugin should be a light wrapper around the functionality exposed the the `LogForwarder` class. Inserts into RocksDB should be handled by the implementation of `LogForwarder::queueString`.

IMO, anything that wouldn't change if you needed to write another plugin which used similar log forwarding logic should be encapsulated in the `LogForwarder` class.

**Comment by theopolis** [comment]
My immediate thought is `LogForwarder` and `LoggerPlugin` sound too similar. If you want to make a simple buffering logger why not write it as a plugin? If you want some extendable queue/sink then write a simple queue backed by RocksDB. Whatever the solution let's make sure the story/names/class facilities tell a clear tale. :)

**Comment by marpaia** [comment]
that's a fair point, yeah. i think that if the log forwarding functionality is significantly large, it should be broken out to a more significant area of the codebase (it's own set of classes in `osquery/remote` or something. if it's concise, I think that `LogForwarderPlugin : plugin LoggerPlugin` would tell a nice story. We could map out the parts of this and figure out class/directory structure?

**Comment by theopolis** [comment]
Agreed, a direct logger plugin implementing the buffering and forwarding concepts would be easiest and make most sense right now.

**Comment by marpaia** [comment]
Yeah, the more that I think about this, the more sense that it makes. 100%. Everything I said earlier was a lie.

**Comment by jedi22** [comment]
What do we want to do about Google Logging?

**Comment by marpaia** [comment]
maybe we can serialize them, via the `logString` method into some json like:

```json
{
  "action": "status_log",
  "content": "OMGWTFBBQ this is the status log content"
}
```

and then send them to the same endpoint.

What do you think, @theopolis?

**Comment by jedi22** [comment]
```
  google::SetLogDestination(google::INFO, (basename + ".INFO.").c_str());
  google::SetLogDestination(google::WARNING, (basename + ".WARNING.").c_str());
  google::SetLogDestination(google::ERROR, (basename + ".ERROR.").c_str());
```

These are the lines responsible for redirecting VLOG lines to files, we need a way to cause these to call our logger function instead.

**Comment by theopolis** [comment]
https://github.com/facebook/osquery/blob/master/include/osquery/logger.h#L119

**Comment by theopolis** [comment]
Merged: https://github.com/facebook/osquery/commit/da9bd5801b1a7ee09fb0b56b25aa04f3b4bea081
