### ISSUE TITLE
runtime flag for disabling tables

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#1016]
Let's add a flag `--disable_tables` or something (name is up for debate) that allows users to launch osquery without certain tables.

**Comment by marpaia** [comment]
This was a request from a user who doesn't want remote/scheduled queries to be able to query certain tables.

**Comment by theopolis** [comment]
Great suggestion

**Comment by marpaia** [comment]
For some additional context, we debated a compile time flag vs a command-line flag and ultimately decided on a runtime option so that they didn't have to compile and package osquery themselves.

**Comment by sharvilshah** [comment]
Thinking of taking a crack at this if no one minds.

I haven't dug into the code yet, but my approach would be something like:

* register a FLAG and split it by comma (assumption no `table_name` will have a comma) 
* for each part call detach in https://github.com/facebook/osquery/blob/master/osquery/sql/sqlite_util.cpp#L91
* And this should be called in `start()` after registry setup in https://github.com/facebook/osquery/blob/master/osquery/core/init.cpp#L262 

Thoughts?

**Comment by theopolis** [comment]
Right on with the comma-delimited set of table names. You could read, split, and store the result vector as a member variable of `SQLiteDBManager` (during construction) that will survive the life of the process. Then add some [similar static method](https://github.com/facebook/osquery/blob/master/osquery/sql/sqlite_util.cpp#L123) to retrieve this list or check if a table name is included. The best "funnel" for table attachments is [`attachTableInternal`](https://github.com/facebook/osquery/blob/master/osquery/sql/virtual_table.cpp#L239) if you check the disabled list using the table name there, like: `SQLiteDBManager::isDisabled(name);` you can prevent any internal table construction AND external table broadcasts.

**Comment by sharvilshah** [comment]
Perfect, thanks for the pointers ([obligatory xkcd](https://xkcd.com/138/)). I'll try and get a start on it later today.
