### ISSUE TITLE
Add support for new tables from external sources using JSON as a communication mechanism

### ISSUE THREAD

**Issue by jjulien** [facebook/osquery#1041]
This is a new feature suggestion designed to simplify the process of creating custom tables for users who lack experience working with c++.  The idea is taken from the Facter project https://github.com/puppetlabs/facter and employs a similar concept to what they call "external facts".  https://docs.puppetlabs.com/facter/2.4/custom_facts.html#external-facts

The idea is to provide a directory that osquery will source for user configured tables.  There would be 2 files per table, the schema file and the data file.  The purpose of these files would be to provide JSON output for both the schema definition and the table data.

These files could be either executable or static content.  In the event they are static content, the file itself contains the JSON.  In the event the file is executable, then execution of the file must return the proper JSON information.

File names would be formatted as `<tablename>-schema` and `<tablename>-data`

The schema file would provide a JSON dictionary that closely matches the current table spec files.  The data file would provide an Array of Arrays where the first Array represents rows of data and each inner array represents the column data for that row.

Here's an example of what the JSON output would look like for the time table

time-schema:
```
{ "table_name": "time",
 "description": "Returns the current hour, minutes, and seconds.",
      "schema": [{"name": "hour", "type": "INTEGER", "description": "The current hour"},
                 {"name": "minutes", "type": "INTEGER", "description": "The current minutes past the hour"},
                 {"name": "seconds", "type": "INTEGER", "description": "The current seconds past the minute"}]
}
```

time-data:
```
[[{"name": "hour", "value": 10},
 {"name": "minutes", "value": 5},
 {"name": "seconds", "value": 12}]]
```

**Comment by marpaia** [comment]
I like this for things like IOCs!

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by marpaia** [comment]
I'm going to put a wontfix on this, as I don't think this is a direction we plan on supporting anytime soon. This would take some pretty dramatic changes to the way our SQL engine works, so I'm uncertain if the juice is worth the squeeze on this one. If there's significant community desire, we can reconsider, but it's been pretty quiet.
