### ISSUE TITLE
Consider changing file_changes to file_events before FIM release

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1049]
Event-subscriber tables make sense to suffix with `_events`. Hardware and yara use this notation. File uses "changes", which makes sense but is not consistent. What are folks' thoughts on a rename and what precedent should we set before documenting this in the next release (currently the FIM features are undocumented)?

@marpaia, @wxsBSD, @jedi22 ?

**Comment by marpaia** [comment]
I dig it.

**Comment by wxsBSD** [comment]
I like consistency.

**Comment by theopolis** [comment]
Now documented as file_events.
