### ISSUE TITLE
Mac system symlinked directories don't work with file_changes

### ISSUE THREAD

**Issue by arirubinstein** [facebook/osquery#1063]
On a Mac, when subscribing to file_changes on a symlinked directory, (such as `/etc` which actually is `/private/etc` on osx), osquery appears to hook the directory but doesn't report any changes.  This functionality may also be the same in the linux version too - but I haven't tested it.  

### To reproduce:

1) Use a config like this:
```json
{
  "schedule": {
    "file_changes": {
      "query": "select * from file_changes;",
      "interval": 10
    }
  },
  "file_paths": {
    "users": [
      "/Users/me/Desktop/%%"
    ],
    "all_etc": [
      "/etc/%%"
    ],
    "tmp": [
      "/tmp/%%"
    ]
  }
}
```

2) and start `osqueryd` with that config.  Observe a successful listener addition in the osqueryd log: 
```
I0427 22:39:46.991005 1955668736 file_changes.cpp:59] Added listener to: /etc
I0427 22:39:46.991032 1955668736 file_changes.cpp:59] Added listener to: /tmp
I0427 22:39:46.991052 1955668736 file_changes.cpp:59] Added listener to: /Users/me/Desktop
```

3) See events in osqueryd.results.log for `/Users/me/Desktop` but not for `/etc/

4) Repeat with `/private/etc/%%` as the path to monitor instead of `/etc/%%`, and observe the file changes work.

### Possible fixes

If resolving symlinks is not an option, perhaps it would be useful to throw an error to the user indicating that a file_paths config is effectively disabled when pointed at a symlink.
 
Perhaps exposing a configurable "follow_symlinks" option may also be useful too.  Following symlinks has its own security implications too, so it may be useful to implement this to be configurable per-path in the config.

**Comment by theopolis** [comment]
We've encountered this before and have punted by suggesting to listen to the /private/etc,var directories instead. We should look at this more closely and see if we can detect the symlinks at start-time. On Linux it's a bit different since we match by inode. If an inode is swapped the inotify thread should replace the watch. @jedi22, if possible we should emulate watchman's functions.
