### ISSUE TITLE
Chrome extensions vtable doesn't include loaded unpacked extensions

### ISSUE THREAD

**Issue by arirubinstein** [facebook/osquery#1064]
By loading an unpacked extension in google chrome (not installed via chrome web store, but on disk somewhere else), the extension does not appear in the chrome_extensions table.  Is there a way to interface with chrome better or read an extensions manifest instead of dir enumeration to get this info?

**Comment by theopolis** [comment]
@arirubinstein we could, there should be a file or JSON somewhere that lists paths to unpacked/devmode extensions. Is this something hi-pri that I should take release-blocking? Release being us cutting a 1.4.5 :)

**Comment by arirubinstein** [comment]
Definitely low priority, just noticed this and figured I'd log a bug.

**Comment by theopolis** [comment]
Ok perfect, thanks!

**Comment by theopolis** [comment]
Added to #619
