### ISSUE TITLE
Less than ideal performance on joins in some cases

### ISSUE THREAD

**Issue by wxsBSD** [facebook/osquery#1068]
I've discussed this with @theopolis recently but I don't think an issue was ever made so I'm doing it just to make sure it isn't lost.

When issuing a query which does a join on a constraint performance can be sub-optimal in certain cases, depending upon what the table does. The only table I'm currently aware of with this problem is ```yara```, and it is best illustrated by an example.

```
select distinct count(*) from processes p, yara y where y.sigfile="/tmp/foo.sig" and y.path=p.path;
```

This will use ```/tmp/foo.sig``` and scan the path for every process currently running. Due to the way osquery works, the ```genYara()``` function is called once per path. The ```yara``` table does not keep state between calls (that would be a bad idea) so the net result is that every call causes the signature file to be recompiled which is sub-optimal to say the least.

Ideally the constraints would be collected up and passed in as a list so that I can compile once and iterate over the list of various constraints.

**Comment by marpaia** [comment]
If we wanted to handle this completely in the yara code, perhaps you could make a singleton YaraManager or something, which kept references to already compiled yara rule files? Then, before you compile a signature file, see if it's already been compiled and copy out a reference?

**Comment by wxsBSD** [comment]
I was thinking of something like that, but it seems like papering over the problem to be honest. In my eyes the root cause is in how osquery calls into the table generators in this case. If I were going to design this (without relying on sqlite) I would simply pass all path constraints in a list. I haven't looked at the sqlite code (which is where I assume this stems from) so there may very well be a good reason for this.

I'm more than willing to do as you suggest but when I talked with @theopolis about it, it sounded like he would look into it and come back with a suggestion. Given that the only one with this problem I'm aware of is YARA I'm inclined to take the performance hit until a rough consensus is reached. It's is, after all, a beta feature. :smiley:

**Comment by marpaia** [comment]
this will be bundled into some larger SQL engine improvements that we've been passively reasoning through. i'm going to close this for now, as it's not very actionable, but we should continue to have conversation on this specific topic on this issue.

**Comment by theopolis** [comment]
Also, check: https://github.com/facebook/osquery/blob/master/osquery/tables/other/yara.cpp#L89 that method is not returning `const` so the auto is invoking the map's copy constructor. You can speed that up and get the ondemand `siggroup` caching if you add a `&`.

**Comment by theopolis** [comment]
I think we've more or less solved this in the specific case of the yara table by compile each `sigfile` once and keeping the compiled data around for the life of the process. This is achieved by using the filename as an index and treating it as if it were defined as a `sig_group` in a config load. Take a look at the implementation change for details: https://github.com/facebook/osquery/pull/1448.
