### ISSUE TITLE
Core's event manager no longer digests call responses correctly

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#1069]
So, I haven't started exploring this in the code yet, but as I was working on Python API stuff, I noticed that core is no longer accepting valid responses from my extension's `ExtensionManager::call()` function. The error case exists for both the `api_example.py` extension (which is currently included with library code in #1020) as well as the crude extension using just the thrift API that I wrote last week (https://gist.github.com/marpaia/ddb09d4029a177850db3).

As of last week, the gisted extension worked with osqueryd, but not osqueryi. Now, neither extension works with either osqueryd or osqueryi. Specifically, what I mean by "doesn't work" is that, when querying the "foobar" table, osquery-core says no data was returned. This means that the extension successfully registers (it shows up in `osquery_extensions`), the table gets inserted into the registry (it shows up in `osquery_registry`), the table lists (`.tables`). Everything works, except for the data parsing bit.

Something like this happened last week during development as well, and it was because I wasn't formatting my QueryData response correctly (`list<map<string, string>>`), but I am formatting it correctly now (I believe).

**Comment by marpaia** [comment]
terminal output from osqueryi:

```
$ ./build/darwin/osquery/osqueryi
osquery> .tables
<<redacted>>
  => firefox_addons
  => foobar
  => groups
<<redacted>>
osquery> .mode line
osquery> select * from osquery_registry;
<<redacted>>
  registry = table
      name = foobar
owner_uuid = 8467
  internal = 0
    active = 1
osquery> select * from osquery_extensions;
       uuid = 0
       name = core
    version = 1.4.4-160-g0f9e31d
sdk_version = 1.4.4
       path = /Users/marpaia/.osquery/shell.em
       type = extension

       uuid = 8467
       name = XXX NAME
    version =
sdk_version =
       path = /Users/marpaia/.osquery/shell.em.8467
       type = extension
osquery> select * from osquery_extensions;
       uuid = 0
       name = core
    version = 1.4.4-160-g0f9e31d
sdk_version = 1.4.4
       path = /Users/marpaia/.osquery/shell.em
       type = extension

       uuid = 40785
       name = XXX NAME
    version =
sdk_version =
       path = /Users/marpaia/.osquery/shell.em.40785
       type = extension
osquery> select * from foobar;
osquery> 
```

**Comment by theopolis** [comment]
Does `make test` work? In the integrations tests for extensions (test_extensions) the entire workflow is exercised, including checking and extension table responses.

**Comment by theopolis** [comment]
```
[reed@reed-mbp] ~/git/github/osquery(branch:snapshots) » ./build/darwin/osquery/osqueryi --verbose                                                                                                                                                                      reed@reed-mbp
I0428 21:27:06.932824 2103894784 init.cpp:153] osquery initialized [version=1.4.4-151-g3398beb]
I0428 21:27:06.933106 2103894784 extensions.cpp:163] Modules autoload contains invalid paths: /etc/osquery/modules.load
I0428 21:27:06.934237 251457536 interface.cpp:249] Extension manager service starting: /Users/reed/.osquery/shell.em
I0428 21:27:06.937218 2103894784 config.cpp:68] Updating config with source: /var/osquery/osquery.conf
I0428 21:27:06.960316 256237568 events.cpp:422] Starting event publisher runloop: fsevents
I0428 21:27:06.960331 256774144 events.cpp:422] Starting event publisher runloop: iokit_hid
I0428 21:27:06.960388 257310720 events.cpp:422] Starting event publisher runloop: scnetwork
osquery - being built, with love, at Facebook
Using a virtual database. Need help, type '.help'
osquery> I0428 21:27:31.889986 254640128 interface.cpp:83] Registering extension (example, 21807, version=0.0.1, sdk=1.4.4)
I0428 21:27:31.890027 254640128 registry.cpp:240] Extension 21807 registered config plugin example
I0428 21:27:31.890470 254640128 registry.cpp:240] Extension 21807 registered table plugin example

osquery> select * from example;
+--------------+-----------------+
| example_text | example_integer |
+--------------+-----------------+
| example      | 1               |
+--------------+-----------------+
osquery> 
```

Using `/build/darwin/osquery/example_extension.ext --socket ~/.osquery/shell.em`

**Comment by marpaia** [comment]
The only test of mine that fails is:

```
[ RUN      ] FilesystemTests.test_safe_permissions
/Users/marpaia/git/osquery/osquery/filesystem/tests/filesystem_tests.cpp:251: Failure
Value of: safePermissions("/", kFakeDirectory + "/door.txt")
  Actual: false
Expected: true
/Users/marpaia/git/osquery/osquery/filesystem/tests/filesystem_tests.cpp:257: Failure
Value of: safePermissions("/", "/dev/zero")
  Actual: false
Expected: true
[  FAILED  ] FilesystemTests.test_safe_permissions (3 ms)
```

the extensions and modules tests both pass.

**Comment by marpaia** [comment]
example.ext works for me too, when ran with the shell

**Comment by marpaia** [comment]
@theopolis does the format of my ExtensionResponse look flawed? Printing `response` for the `foobar` table in the `api_example.py` example yields `[{'foo': 'bar', 'baz': 'baz'}, {'foo': 'bar', 'baz': 'baz'}, {'foo': 'bar', 'baz': 'baz'}, {'foo': 'bar', 'baz': 'baz'}, {'foo': 'bar', 'baz': 'baz'}]`

**Comment by theopolis** [comment]
Interesting, looks fine. Can you break/step: https://github.com/facebook/osquery/blob/master/osquery/extensions/extensions.cpp#L486

And see what happens to the data?

**Comment by marpaia** [comment]
I'm a tool, I was using `osquery.extensions.ttypes.Status` instead of `osquery.extensions.ttypes.ExtensionStatus`
