### ISSUE TITLE
how to connect with thrift client?

### ISSUE THREAD

**Issue by sidorares** [facebook/osquery#1075]
I'd like to make my own simple shell. Which port/socket daemon listens for thrift messages?

**Comment by theopolis** [comment]
Hey @sidorares, are you interesting in writing a shell to interact with a running daemon (osqueryd) process? If so it might be nice to extend the existing osqueryi (slim version of the SQLite shell) to include a `.connect` meta command.

If you're interesting in replacing the osqueryi shell completely that's a bit different. The two tools don't communicate at all right now. With some tricks you can use the shell to explore the daemon's cache but that requires proper permissions and will only let you interact with event-publisher/subscriber data, so not too useful either.

Aside from those goals, the osquery thrift interface exists for [two primary features](http://osquery.readthedocs.org/en/latest/development/osquery-sdk/): querying an already-running osquery process and exposing "plugins" that aren't included in master. At FB we use this thrift (extensions) interface to add tables, config, and logger plugins built with our internal GCC/C++ runtime. This involves starting a separate process from a binary compiled internally, which connects to the thrift interface (UNIX domain socket). But similarly, one could add tables and other plugins written in any language supported by thrift. @marpaia  is working on an example set of python binding right now. 

But to answer your question, the [default extensions socket](http://osquery.readthedocs.org/en/latest/installation/cli-flags/) location for the daemon is: `extensions_socket=/var/osquery/osquery.em` and for the shell it's `~/.osquery/shell.em`.

**Comment by sidorares** [comment]
Thanks @theopolis !
My goals are 1) build nice simple api to make extensions with node 2) make mysql protocol -> thrift api proxy ( similar to https://github.com/sidorares/mysql-pg-proxy but with osquery instead of pg ) so you can interact with osquery using mysql clients

**Comment by theopolis** [comment]
Nice! You'll want to track what @marpaia is working on for Python and use that as scaffolding for node: https://github.com/facebook/osquery/issues/876

To get an experience like:

```
>>> dbc = open("/var/osquery/osquery.em")
>>> dbc.query("select * from time")
```

You'll essentially be wrapping what the thrift interface expects as a [client wrapper](https://github.com/facebook/osquery/blob/master/tools/tests/test_extensions.py#L37) and interacting with that API similar to: https://github.com/facebook/osquery/blob/master/tools/tests/test_extensions.py#L93

Filling in that style of client to mimic some obdc driver might be fun too. :)

**Comment by sidorares** [comment]
Got it working, thanks!

```js
var thrift = require('thrift');
var ExtensionManager = require('./gen-nodejs/ExtensionManager.js');
var conn = thrift.createConnection(0, '/var/osquery/osquery.em');
var client = thrift.createClient(ExtensionManager, conn);
client.query('select * from time', function(err, res) {
  console.log(res.response);
});
```

prints `[ { hour: '11', minutes: '27', seconds: '5' } ]`

( gen-nodejs is result of `thrift --gen js:node osquery/osquery.thrift` )

**Comment by theopolis** [comment]
Anytime, we idle in #osquery on freenode if you want to chat about tools/integrations/etc. But GH issues work too!

Looking forward to some awesome node projects ;)

**Comment by sidorares** [comment]
first quick version - https://github.com/sidorares/mysql-osquery-proxy

**Comment by sidorares** [comment]
got node.js extension server running succesfully - happy to submit package similar to https://github.com/osquery/osquery-python/

**Comment by marpaia** [comment]
@sidorares whoa, that is AWESOME. and yes, an idiomatic JS would be amazing!

**Comment by sidorares** [comment]
took me a while to figure out what socket server is supposed to listen, your example was very helpful

**Comment by sidorares** [comment]
also it's a pity that extension has to start it's own server instead of using existing connection (its duplex anyway). Not sure if it's thrift or your api limitation

**Comment by marpaia** [comment]
I think the original logic was that you can have an arbitrarily large amount of active extensions and there was no way to have all of the services independently communicating using the same socket, but @theopolis would know more about the history there.

**Comment by sidorares** [comment]
should not be a limitation, dbus listens on unix socket and you create services by communicating to the same "client" connection

**Comment by theopolis** [comment]
Hey @sidorares the limitation is on the thrift interface mostly. At FB we use a fork of the Apache thrift which originally did not even include UNIX sockets as a transport. Mike and I ported the Apache thrift code to our thrift 2.0 codebase and did so in a half-duplex mode. This forced us to think about extensions as a local interaction API, so to speak, in that the core process could arbitrarily command any interface or API that "registered". Truth be told, interacting with extensions in a half-duplex mode was the path of last resistance and a minimum viable solution at the time.

I'd love to revisit an async extensions API but it would require more changes to both thrift-forks. In the mean time it's pretty simple to treat both the extension and core as a thrift service. Hope that helps! :D

**Comment by sidorares** [comment]
thanks for explanation!

**Comment by sidorares** [comment]
@marpaia have a look at client. API is different from python one, still not sure if I like it or not - https://github.com/sidorares/osquery-node
