### ISSUE TITLE
Add documentation for using and deploying extensions

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#1076]
We should talk through where to put them, what guarantees we make about starting and stopping them, etc.

**Comment by theopolis** [comment]
Sure! There are some hints in the CLI docs, and subtly in the chef cookbooks. We can outline how we use C++ extensions internally. I haven't heard of anyone wanting to use an extension dependency (aka config or logger plugin yet). Table plugins are more lax but still need autoloading documentation.

wrt the bro log parsing module, we could do a better job at lessening the onerous of CMake integration. A folder or simlink that built subdir-ed code as an extension or module based on a simple .txt arguments file would be perfect. That is of course for C++ extensions treated as "integrations" meaning they're not yet appropriate for master.
