### ISSUE TITLE
404s on osquery.io

### ISSUE THREAD

**Issue by sharvilshah** [facebook/osquery#1087]
Under the `Guides` section of the footer on osquery.io:

* Link to `Log Aggregation` should point to: https://osquery.readthedocs.org/latest/deployment/log-aggregation/ or https://osquery.readthedocs.org/en/latest/deployment/log-aggregation/
* Link to `Config Management` should point to: https://osquery.readthedocs.org/latest/introduction/using-osqueryd/ or https://osquery.readthedocs.org/en/latest/introduction/using-osqueryd/

**Comment by theopolis** [comment]
Nice, I'm trying to pull this repo into the osquery organization's control. Right now it's a private repo in my github. @marpaia can we turn the organization into a GH-bronze so we can store temporary private repos?

**Comment by marpaia** [comment]
I'll file an internal task for @jamesgpearce and see what we have to do to set that up.

**Comment by marpaia** [comment]
t6956995

**Comment by theopolis** [comment]
Merged! Thanks @sharvilshah!
