### ISSUE TITLE
Supporting 'legacy' Linux distributions without a C++11 runtime

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1090]
Thoughts on (1) if we should support legacy distributions that are very close to EOL or have been EOLed for the general non-enterprise user; and (2) how to deploy osquery without a system-provided C++11 runtime.

Operating systems in question: RHEL5.11, CentOS5 (max update), OEL5.11, Ubuntu10.X.
GCC runtimes: 4.1.Y (Y = max), and 4.4.Y (Y= max)

We can definitely build a GCC/C++11 runtime inline with our provision script/logic on a Jenkins build host for each "semi-"supported legacy distribution. Then tightly control and distribute this runtime along side the deployed osquery binaries in an RPM/DEB. 

osquery uses `/usr/lib/osquery` for modules (shared object-based extensions) and extensions proper. We can certainly deploy dependent dynamic libraries alongside. Then coerce the osqueryd/osqueryi executables use this path for their C++ runtime. RocksDB is the other inline-build project that would compile/runtime link specifically. We already build and link librocksdb statically so I don't perceive problems there.

I see 2 paths forward:
 - Write a different `/etc/init.d/osqueryd` that includes a LD_LIBRARY_PATH for osqueryd.
 - Compile each target binary, shipped with our RPM/DEB with an RPATH to `/usr/lib/osquery/`

Any other ideas?

**Comment by irctrakz** [comment]
I vote for option 2, but make it super clear this isn't a formally supported path.

**Comment by theopolis** [comment]
Right! I was thinking we could be absolutely clear by only writing an RPATH and including the libraries in a `osquery-legacy.rpm` or some similarly named package. This way you're making a massive and conscience decision that the normal packages and binaries are not supported.

With the separate package we can add lower **and upper** limits for the libstdc++ package/runtime. If you try to install `osquery-legacy.rpm` (with a package name: "osquery-latest") on a platform that has a supported runtime, the install will fail. Similarly, the `osquery.rpm` (with a package name: "osquery") includes only a minimum runtime requirement.

**Comment by theopolis** [comment]
I added a list of distro versions that should have side-by-side C++11 runtime included or statically linked: https://github.com/facebook/osquery/blob/master/CMakeLists.txt#L91

Let's try [statically linking](https://github.com/facebook/osquery/blob/master/osquery/CMakeLists.txt#L39) stdc++ option 3. The unit and integration tests don't complain and selecting from all the included tables works without ASAN barking.

**Comment by theopolis** [comment]
Considering this closed until the currently-implemented option 3 is no longer viable.
