### ISSUE TITLE
Upgrade RocksDB to 3.10.2 for Linux builds

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#1099]
Right now, we're compiling RocksDB 3.5 from source and statically linking it in Linux. We've drifted quite a bit, the current public stable release is 3.10.2, so let's update our provision scripts to reflect that.

**Comment by theopolis** [comment]
So far there are no "from-source" installs on OS X, (and FreeBSD to mention). We should ask the RocksDB dev team to push 3.10 into homebrew.

**Comment by marpaia** [comment]
@theopolis they are, there's an internal task cut for it.
