### ISSUE TITLE
Supporting more `disk_encryption` reporting options

### ISSUE THREAD

**Issue by sharvilshah** [facebook/osquery#1100]
@theopolis and I chatted, that it would be nice to support more non dm-crypt/LUKS disk encryption options. This issue is to track and discuss those. I'll add/update this as and when I take a crack at them.

* ecryptfs
* encfs
* truecrypt (newer libcryptsetup already has ability to read truecrypt headers)
* loop-aes

Also need to explore how to decouple `block_devices` and `disk_encryption` tables. Maybe the way forward here is adding data from the `mounts` table and checking if they are of type `ecryptfs` or `encfs`

**Comment by theopolis** [comment]
Right! We can group these into "categories" of disk encryption options, FS or Block. It'll be a challenge to represent them all in a single table. Loop-AES and eCryptFS might need a separate table that includes metadata about the configured FDE. I can't yet wrap my head around what details would be important. 

At the block level, a mounted/logical volume is easy to report on and makes sense when you ask "what mounts or devices are encrypted?"

**Comment by sharvilshah** [comment]
So I am not sure how disk encryption reporting can be accomplished for ecryptfs and EncFS without using information from `/proc/mounts` (or `mounts` table). 

As I understand it with both of those, there is a directory on local device/fs which serves as a backing store for encrypted data and a mount point to access them. Since one can choose arbitrary directories (the default on ecryptfs is `~/.private` but easy to override), I don't think it's feasible to scan the whole filesystem (this will be the same limitation on Mac OS X [1]).

I quickly setup ecryptfs and encfs on the vagrant image:

```bash
$ cat /proc/mounts

/home/vagrant/.Private /home/vagrant/Private ecryptfs rw,nosuid,nodev,relatime,ecryptfs_fnek_sig=6967d0c28476ffa1,ecryptfs_sig=253ca7e88811d184,ecryptfs_cipher=aes,ecryptfs_key_bytes=16,ecryptfs_unlink_sigs 0 0

encfs /home/vagrant/crypt fuse.encfs rw,nosuid,nodev,relatime,user_id=1000,group_id=1000,default_permissions 0 0
```

**ecryptfs:**

With ecryptfs there is there is FEKEK (File Encryption Key Encryption Key -- wow that's a mouthful) on the header (per mount) and FNEK (Filename Encryption Key) on per file. The cipher metadata is exposed as `mnt_opts` so we can grab it from the the `mounts` table.

**EncFS:**

Things are more difficult with EncFS. Just looking at the `/proc/mounts` there is no way to know where/which is the backing directory (can make an educated guess). The cipher data is stored in `.encfs6.xml` in the backing store directory. In addition to cipher details, that file also contains, password/passphrase wrapped keys. Even if we can find that directory, I am not sure it makes sense to parse `.encfs6.xml`, since securely opening and reading that file is a challenge in itself (making sure doesn't endup in swap).

Thoughts?

---

[1]:  Similar challenge on encrypted disk images (.`dmg` or `sparebundle`) created through `Disk Utility` (or `hditul` on CLI). There is no info on their mount points from a cursory look, and it seems the only way to report on them is find all `.dmg` and `sparsebundle` files and read their headers:

```bash
❯ xxd -g1 osquery_test.dmg | head -n 1
0000000: 65 6e 63 72 63 64 73 61 00 00 00 02 00 00 00 10  encrcdsa........
```

Though there maybe some more info in the `DiskImages` private framework (doesn't seem to have any symbols though). I think extra disk_encryption reporting on Mac is out of scope anyways.

**Comment by sharvilshah** [comment]
**truecrypt**

It seems truecrypt can do both block level and "virtual" filesystem level encryption (at least for windows, their old docs I found are more windows oriented). I think cryptesetup only deals with block level truecrypt containers (don't quote me on it, still digging). I don't know what truecrypt's mount table looks like for its filesystem encryption.

**Comment by theopolis** [comment]
Nice overview! If you think there's opportunity to report additional non-cryptsetup/LUKs FDE methods in disk_encryption we can add another column with the subsystem name (luks, truecrypt, loop, etc). And if there's no way to represent file system encryption subsystems, that's no problem, we can punt. 

For the OS X DA stuff there might be cool opportunity to use the Arbitration event notifier. Similar to IOKitHID and FSEvents, is it possible to hook and report on DMG mounts? Then we can limit the reporting to event time rather than searching for containers. That doesn't really accomplish the encrypted disk container need, but reporting on the current mounted volumns (what we have now) and mount events would be outstanding.

**Comment by sharvilshah** [comment]
> If you think there's opportunity to report additional non-cryptsetup/LUKs FDE methods in disk_encryption we can add another column with the subsystem name (luks, truecrypt, loop, etc).

I like the subsystem column. It's simple and get's us most of the way there.

> And if there's no way to represent file system encryption subsystems, that's no problem, we can punt.

We can grab metadata from the mount options/flags and use `mounts` and ForeignKey. ecryptfs by default exposes cipher details in the mount flags. So I think the options we have here are:

1. We can grab data from `mounts` table and populate what we can. So here ecryptfs will have full details (unless there is an option to hide them). EncFS and truecrypt (filesystem mode) we can report that they are encrypted (since the mount type is `fuse.encfs` and `fuse.truecrypt`) and leave cipher details blank. 

2. Just report on ecryptfs (above) and punt EncFS and truecrypt (filesystem mode).

3.  Punt all filesystem subsystems.

> For the OS X DA stuff there might be cool opportunity to use the Arbitration event notifier. Similar to IOKitHID and FSEvents, is it possible to hook and report on DMG mounts? Then we can limit the reporting to event time rather than searching for containers. That doesn't really accomplish the encrypted disk container need, but reporting on the current mounted volumns (what we have now) and mount events would be outstanding.

Excellent idea. And I think DA has mount notifications. Tracking this in #1103

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
