### ISSUE TITLE
how to use osquery public api in C++ program 

### ISSUE THREAD

**Issue by sami2316** [facebook/osquery#1112]
I tried to use osquery functionality in C++ progarm, but I'm failing to link osquery library with my program. 
I tried:
#include <osquery/sdk.h>
using namespace osquery;
 Both of these commands are not working. I think there is compiler linkages problem. Guide me how can i use osquery in a C++ program.
I am using netbeans.

**Comment by theopolis** [comment]
Hey @sami2316, what do you want to do with your app? Are you [building an osquery](http://osquery.readthedocs.org/en/latest/development/osquery-sdk/)?

**Comment by sami2316** [comment]
Actually I want to integrate osquery with another app. Using osquery functionality, raiseing osquery events that are compatible with another app and then sending it remotely using communication library specific to that app. 
But I am failing to include osquery in compiler. :-(
If there is some approach to do that task, please guide me.

**Comment by marpaia** [comment]
@sami2316 can you post more information about how you're trying to go about linking osquery into your program? You obviously need to link against osquery's dependent libraries if you want to link osquery; libosquery.a does not include them.

**Comment by sami2316** [comment]
@marpaia I need to link osquery libraries and use osquery functionally in my program. Initially my target is to use osquery in c++ program, get results there and use that data for another application.

I tried linking libosquery.a with compiler but it did't work for me. How can i link osquery libraries?

**Comment by theopolis** [comment]
@sami2316 we would love to help but we need a LOT more detail about the error, what steps you're taking, how we can try to reproduce, etc. Right now we know nothing about your setup or what error you're talking about.

Please read [this short guide](http://stackoverflow.com/help/how-to-ask) on some helpful question asking tips!

Let us know at a minimum, how you're trying to link (keep in mind "linking" means quite a few things), and be precise. Including errors, the error text, your command line output, will help us answer your question. Including your code or giving us a link to your github project that includes your code and your Makefile will be helpful too.

**Comment by sami2316** [comment]
I am linking against osquery library with compiler option "-L/path/to/broker/installation" and using C++11 standard. I am following: 
             http://osquery.readthedocs.org/en/latest/development/osquery-sdk/
documentation. When I compile the code, I get the following errors

"/usr/bin/gmake" -f nbproject/Makefile-Debug.mk QMAKE= SUBPROJECTS= .build-conf
gmake[1]: Entering directory '/home/sami.ullah/NetBeansProjects/Broker_test'
"/usr/bin/gmake"  -f nbproject/Makefile-Debug.mk dist/Debug/GNU-Linux-x86/broker_test
gmake[2]: Entering directory '/home/sami.ullah/NetBeansProjects/Broker_test'
mkdir -p build/Debug/GNU-Linux-x86
rm -f "build/Debug/GNU-Linux-x86/main.o.d"
g++  -L/usr/lib/osquery/   -c -g -std=c++11 -MMD -MP -MF "build/Debug/GNU-Linux-x86/main.o.d" -o build/Debug/GNU-Linux-x86/main.o main.cpp
main.cpp:8:25: fatal error: osquery/sdk.h: No such file or directory
 #include osquery/sdk.h
                         ^
     compilation terminated.
nbproject/Makefile-Debug.mk:66: recipe for target 'build/Debug/GNU-Linux-x86/main.o' failed
gmake[2]: *** [build/Debug/GNU-Linux-x86/main.o] Error 1
gmake[2]: Leaving directory '/home/sami.ullah/NetBeansProjects/Broker_test'
nbproject/Makefile-Debug.mk:59: recipe for target '.build-conf' failed
gmake[1]: *** [.build-conf] Error 2
gmake[1]: Leaving directory '/home/sami.ullah/NetBeansProjects/Broker_test'
nbproject/Makefile-impl.mk:39: recipe for target '.build-impl' failed
gmake: *** [.build-impl] Error 2

**Comment by marpaia** [comment]
@sami2316 as you can see from the output:

```
main.cpp:8:25: fatal error: osquery/sdk.h: No such file or directory
#include osquery/sdk.h
^
```

The compiler cannot find the needed header file. Where are the osquery headers on your system?

**Comment by sami2316** [comment]
@marpaia When I include the header folder in my project then that #include osquery/sdk.h command works.
but command
using namespace osquery
did't work. I need to link libosquery.so (dynamic library). How can i create libosquery.so? I tried making libosquery.so from libosquery.a but it did't work. 

if someone want to link osquery in one's application, what you guys propose? (dynamic library or dll).

**Comment by marpaia** [comment]
Did you get past the compiler error that you pasted above? If so, that's valuable context, you should follow up with what you did to fix the issue. If not, then that is clearly a headers not found error.

I copied the example module from the wiki above and, given the osquery headers on my system as well as the required libraries to link against, I was able to do the following:

```
$ clang++ -std=c++11 -I/usr/local/include/ -losquery -lthrift -lboost_system -lboost_thread-mt -lboost_filesystem -lglog -lrocksdb osquery_test.cpp -o mod
$ ./mod --help
osquery 1.4.5-31-g8235fd1, your OS as a high-performance relational database
Usage: mod [OPTION]...

osquery extension command line flags:

    --interval VALUE                Seconds delay between connectivity checks
    --socket VALUE                  Path to the extensions UNIX domain socket
    --timeout VALUE                 Seconds to wait for autoloaded extensions

osquery project page <https://osquery.io>.
```

This is clearly not an issue with osquery's ability to be linked into another application. I'm going to close this unless a further issue is found.

**Comment by sami2316** [comment]
What could be the possbile reason for error?

"/usr/bin/gmake" -f nbproject/Makefile-Debug.mk QMAKE= SUBPROJECTS= .build-conf
gmake[1]: Entering directory `/home/chenone2316/NetBeansProjects/osquery'
"/usr/bin/gmake"  -f nbproject/Makefile-Debug.mk dist/Debug/GNU-Linux-x86/osquery
gmake[2]: Entering directory `/home/chenone2316/NetBeansProjects/osquery'
mkdir -p build/Debug/GNU-Linux-x86
rm -f "build/Debug/GNU-Linux-x86/program.o.d"
g++ -I/usr/local/include/ -losquery -lthrift -lboost_system -lboost_filesystem -lglog -lrocksdb   -c -g -std=c++11 -MMD -MP -MF "build/Debug/GNU-Linux-x86/program.o.d" -o build/Debug/GNU-Linux-x86/program.o program.cpp
mkdir -p dist/Debug/GNU-Linux-x86
g++ -I/usr/local/include/ -losquery -lthrift -lboost_system -lboost_filesystem -lglog -lrocksdb    -o dist/Debug/GNU-Linux-x86/osquery build/Debug/GNU-Linux-x86/program.o 
build/Debug/GNU-Linux-x86/program.o: In function `osquery::RegistryHelperCore::RegistryHelperCore(bool)':
/usr/local/include/osquery/registry.h:188: undefined reference to `vtable for osquery::RegistryHelperCore'
build/Debug/GNU-Linux-x86/program.o: In function `osquery::RegistryHelperCore::~RegistryHelperCore()':
/usr/local/include/osquery/registry.h:189: undefined reference to `vtable for osquery::RegistryHelperCore'
build/Debug/GNU-Linux-x86/program.o: In function `osquery::ExternalSQLPlugin::query(std::string const&, std::vector<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >, std::allocator<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > >&) const':
/usr/local/include/osquery/extensions.h:62: undefined reference to `osquery::queryExternal(std::string const&, std::vector<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >, std::allocator<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > >&)'
build/Debug/GNU-Linux-x86/program.o: In function `osquery::ExternalSQLPlugin::getQueryColumns(std::string const&, std::vector<std::pair<std::string, std::string>, std::allocator<std::pair<std::string, std::string> > >&) const':
/usr/local/include/osquery/extensions.h:67: undefined reference to `osquery::getQueryColumnsExternal(std::string const&, std::vector<std::pair<std::string, std::string>, std::allocator<std::pair<std::string, std::string> > >&)'
build/Debug/GNU-Linux-x86/program.o: In function `int osquery::RegistryFactory::create<osquery::ConfigPlugin>(std::string const&, bool)':
/usr/local/include/osquery/registry.h:485: undefined reference to `osquery::RegistryHelperCore::setName(std::string const&)'
build/Debug/GNU-Linux-x86/program.o: In function `int osquery::RegistryFactory::create<osquery::ConfigParserPlugin>(std::string const&, bool)':
/usr/local/include/osquery/registry.h:485: undefined reference to `osquery::RegistryHelperCore::setName(std::string const&)'
build/Debug/GNU-Linux-x86/program.o: In function `int osquery::RegistryFactory::create<osquery::tables::TablePlugin>(std::string const&, bool)':
/usr/local/include/osquery/registry.h:485: undefined reference to `osquery::RegistryHelperCore::setName(std::string const&)'
build/Debug/GNU-Linux-x86/program.o: In function `int osquery::RegistryFactory::create<osquery::EventPublisherPlugin>(std::string const&, bool)':
/usr/local/include/osquery/registry.h:485: undefined reference to `osquery::RegistryHelperCore::setName(std::string const&)'
build/Debug/GNU-Linux-x86/program.o: In function `int osquery::RegistryFactory::create<osquery::EventSubscriberPlugin>(std::string const&, bool)':
/usr/local/include/osquery/registry.h:485: undefined reference to `osquery::RegistryHelperCore::setName(std::string const&)'
build/Debug/GNU-Linux-x86/program.o:/usr/local/include/osquery/registry.h:485: more undefined references to `osquery::RegistryHelperCore::setName(std::string const&)' follow
build/Debug/GNU-Linux-x86/program.o: In function `osquery::Status osquery::RegistryFactory::add<osquery::ExternalSQLPlugin>(std::string const&, std::string const&, bool)':
/usr/local/include/osquery/registry.h:513: undefined reference to `osquery::RegistryFactory::registry(std::string const&)'
build/Debug/GNU-Linux-x86/program.o: In function `osquery::RegistryHelper<osquery::tables::TablePlugin>::RegistryHelper(bool)':
/usr/local/include/osquery/registry.h:311: undefined reference to `osquery::tables::TablePlugin::addExternal(std::string const&, std::vector<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >, std::allocator<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > > const&)'
/usr/local/include/osquery/registry.h:311: undefined reference to `osquery::tables::TablePlugin::removeExternal(std::string const&)'
build/Debug/GNU-Linux-x86/program.o: In function `osquery::SQLPlugin::SQLPlugin()':
/usr/local/include/osquery/sql.h:153: undefined reference to `vtable for osquery::SQLPlugin'
build/Debug/GNU-Linux-x86/program.o: In function `osquery::SQLPlugin::~SQLPlugin()':
/usr/local/include/osquery/sql.h:153: undefined reference to `vtable for osquery::SQLPlugin'
build/Debug/GNU-Linux-x86/program.o: In function `osquery::Status osquery::RegistryHelper<osquery::Plugin>::add<osquery::ExternalSQLPlugin>(std::string const&, bool)':
/usr/local/include/osquery/registry.h:380: undefined reference to `osquery::RegistryHelperCore::add(std::string const&, bool)'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery14RegistryHelperINS_12LoggerPluginEEE[_ZTVN7osquery14RegistryHelperINS_12LoggerPluginEEE]+0x20): undefined reference to `osquery::RegistryHelperCore::call(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::vector<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >, std::allocator<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > >&)'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery14RegistryHelperINS_12LoggerPluginEEE[_ZTVN7osquery14RegistryHelperINS_12LoggerPluginEEE]+0x28): undefined reference to `osquery::RegistryHelperCore::setUp()'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery14RegistryHelperINS_9SQLPluginEEE[_ZTVN7osquery14RegistryHelperINS_9SQLPluginEEE]+0x20): undefined reference to `osquery::RegistryHelperCore::call(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::vector<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >, std::allocator<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > >&)'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery14RegistryHelperINS_9SQLPluginEEE[_ZTVN7osquery14RegistryHelperINS_9SQLPluginEEE]+0x28): undefined reference to `osquery::RegistryHelperCore::setUp()'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery14RegistryHelperINS_21EventSubscriberPluginEEE[_ZTVN7osquery14RegistryHelperINS_21EventSubscriberPluginEEE]+0x20): undefined reference to `osquery::RegistryHelperCore::call(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::vector<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >, std::allocator<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > >&)'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery14RegistryHelperINS_21EventSubscriberPluginEEE[_ZTVN7osquery14RegistryHelperINS_21EventSubscriberPluginEEE]+0x28): undefined reference to `osquery::RegistryHelperCore::setUp()'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery14RegistryHelperINS_20EventPublisherPluginEEE[_ZTVN7osquery14RegistryHelperINS_20EventPublisherPluginEEE]+0x20): undefined reference to `osquery::RegistryHelperCore::call(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::vector<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >, std::allocator<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > >&)'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery14RegistryHelperINS_20EventPublisherPluginEEE[_ZTVN7osquery14RegistryHelperINS_20EventPublisherPluginEEE]+0x28): undefined reference to `osquery::RegistryHelperCore::setUp()'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery14RegistryHelperINS_6tables11TablePluginEEE[_ZTVN7osquery14RegistryHelperINS_6tables11TablePluginEEE]+0x20): undefined reference to `osquery::RegistryHelperCore::call(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::vector<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >, std::allocator<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > >&)'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery14RegistryHelperINS_6tables11TablePluginEEE[_ZTVN7osquery14RegistryHelperINS_6tables11TablePluginEEE]+0x28): undefined reference to `osquery::RegistryHelperCore::setUp()'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery14RegistryHelperINS_18ConfigParserPluginEEE[_ZTVN7osquery14RegistryHelperINS_18ConfigParserPluginEEE]+0x20): undefined reference to `osquery::RegistryHelperCore::call(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::vector<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >, std::allocator<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > >&)'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery14RegistryHelperINS_18ConfigParserPluginEEE[_ZTVN7osquery14RegistryHelperINS_18ConfigParserPluginEEE]+0x28): undefined reference to `osquery::RegistryHelperCore::setUp()'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery14RegistryHelperINS_12ConfigPluginEEE[_ZTVN7osquery14RegistryHelperINS_12ConfigPluginEEE]+0x20): undefined reference to `osquery::RegistryHelperCore::call(std::string const&, std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::vector<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >, std::allocator<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > >&)'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery14RegistryHelperINS_12ConfigPluginEEE[_ZTVN7osquery14RegistryHelperINS_12ConfigPluginEEE]+0x28): undefined reference to `osquery::RegistryHelperCore::setUp()'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTVN7osquery17ExternalSQLPluginE[_ZTVN7osquery17ExternalSQLPluginE]+0x38): undefined reference to `osquery::SQLPlugin::call(std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > const&, std::vector<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > >, std::allocator<std::map<std::string, std::string, std::less<std::string>, std::allocator<std::pair<std::string const, std::string> > > > >&)'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTIN7osquery14RegistryHelperINS_12LoggerPluginEEE[_ZTIN7osquery14RegistryHelperINS_12LoggerPluginEEE]+0x10): undefined reference to `typeinfo for osquery::RegistryHelperCore'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTIN7osquery14RegistryHelperINS_9SQLPluginEEE[_ZTIN7osquery14RegistryHelperINS_9SQLPluginEEE]+0x10): undefined reference to `typeinfo for osquery::RegistryHelperCore'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTIN7osquery14RegistryHelperINS_21EventSubscriberPluginEEE[_ZTIN7osquery14RegistryHelperINS_21EventSubscriberPluginEEE]+0x10): undefined reference to `typeinfo for osquery::RegistryHelperCore'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTIN7osquery14RegistryHelperINS_20EventPublisherPluginEEE[_ZTIN7osquery14RegistryHelperINS_20EventPublisherPluginEEE]+0x10): undefined reference to `typeinfo for osquery::RegistryHelperCore'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTIN7osquery14RegistryHelperINS_6tables11TablePluginEEE[_ZTIN7osquery14RegistryHelperINS_6tables11TablePluginEEE]+0x10): undefined reference to `typeinfo for osquery::RegistryHelperCore'
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTIN7osquery14RegistryHelperINS_18ConfigParserPluginEEE[_ZTIN7osquery14RegistryHelperINS_18ConfigParserPluginEEE]+0x10): more undefined references to `typeinfo for osquery::RegistryHelperCore' follow
build/Debug/GNU-Linux-x86/program.o:(.rodata._ZTIN7osquery17ExternalSQLPluginE[_ZTIN7osquery17ExternalSQLPluginE]+0x18): undefined reference to `typeinfo for osquery::SQLPlugin'
collect2: error: ld returned 1 exit status
gmake[2]: *** [dist/Debug/GNU-Linux-x86/osquery] Error 1
gmake[2]: Leaving directory `/home/chenone2316/NetBeansProjects/osquery'
gmake[1]: *** [.build-conf] Error 2
gmake[1]: Leaving directory `/home/chenone2316/NetBeansProjects/osquery'
gmake: *** [.build-impl] Error 2

BUILD FAILED (exit value 2, total time: 4s)

**Comment by marpaia** [comment]
Where is your osquery library installed?

**Comment by sami2316** [comment]
@ "/usr/local/include"

**Comment by marpaia** [comment]
the headers should be installed to /usr/local/include, the library should be installed to /usr/local/lib/libosquery.a

**Comment by sami2316** [comment]
Another error :-( 

"/usr/bin/gmake" -f nbproject/Makefile-Debug.mk QMAKE= SUBPROJECTS= .build-conf
gmake[1]: Entering directory `/home/chenone2316/NetBeansProjects/osquery'
"/usr/bin/gmake"  -f nbproject/Makefile-Debug.mk dist/Debug/GNU-Linux-x86/osquery
gmake[2]: Entering directory `/home/chenone2316/NetBeansProjects/osquery'
mkdir -p dist/Debug/GNU-Linux-x86
g++ -I/usr/local/include/ -losquery -lthrift -lboost_system -lboost_filesystem -lglog -lrocksdb -L/usr/bin/    -o dist/Debug/GNU-Linux-x86/osquery build/Debug/GNU-Linux-x86/program.o -losquery
/usr/bin/ld: /usr/local/lib/libosquery.a(registry.cpp.o): undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
/usr/bin/ld: note: 'dlclose@@GLIBC_2.2.5' is defined in DSO /lib64/libdl.so.2 so try adding it to the linker command line
/lib64/libdl.so.2: could not read symbols: Invalid operation
collect2: error: ld returned 1 exit status
gmake[2]: *** [dist/Debug/GNU-Linux-x86/osquery] Error 1
gmake[2]: Leaving directory `/home/chenone2316/NetBeansProjects/osquery'
gmake[1]: *** [.build-conf] Error 2
gmake[1]: Leaving directory `/home/chenone2316/NetBeansProjects/osquery'
gmake: *** [.build-impl] Error 2

BUILD FAILED (exit value 2, total time: 111ms)

**Comment by theopolis** [comment]
Hi @sami2316, when you enounter undefined references (which is very common building new projects or adding drop-in code) you're most likely missing a link. You should look at the symbols you're missing:

```
undefined reference to symbol 'dlclose@@GLIBC_2.2.5'
```

And find out which libraries they come from, then if you have that library installed, in most cases you can add a `-lNAME` to your linking arguments. In this case `dlclose` comes from `libdl` so add `-ldl`.

**Comment by sami2316** [comment]
I'm trying to compile Eventing framework example, and getting the following error...


"/usr/bin/gmake" -f nbproject/Makefile-Debug.mk QMAKE= SUBPROJECTS= .build-conf
gmake[1]: Entering directory `/home/chenone2316/NetBeansProjects/osquery'
"/usr/bin/gmake"  -f nbproject/Makefile-Debug.mk dist/Debug/GNU-Linux-x86/osquery
gmake[2]: Entering directory `/home/chenone2316/NetBeansProjects/osquery'
mkdir -p build/Debug/GNU-Linux-x86
rm -f "build/Debug/GNU-Linux-x86/program.o.d"
g++ -I/usr/local/include/ -losquery -lthrift -lboost_system -lboost_filesystem -lglog -lrocksdb -L/usr/local/lib/ -I/home/chenone2316/osquery/   -c -g -std=c++11 -MMD -MP -MF "build/Debug/GNU-Linux-x86/program.o.d" -o build/Debug/GNU-Linux-x86/program.o program.cpp
In file included from program.cpp:5:0:
program.cpp:29:1: error: expected unqualified-id before string constant
 REGISTER(NewETCFilesEventSubscriber , "event_subscriber", "new_etc_files");
 ^
program.cpp: In member function ‘virtual osquery::Status osquery::tables::NewETCFilesEventSubscriber::init()’:
program.cpp:41:54: error: no matching function for call to ‘osquery::tables::NewETCFilesEventSubscriber::subscribe(osquery::Status (osquery::tables::NewETCFilesEventSubscriber::*)(const INotifyEventContextRef&), std::shared_ptr<osquery::INotifySubscriptionContext>&)’
   subscribe(&NewETCFilesEventSubscriber::Callback, sc);
                                                      ^
program.cpp:41:54: note: candidate is:
In file included from /home/chenone2316/osquery/osquery/events/linux/inotify.h:19:0,
                 from program.cpp:4:
/usr/local/include/osquery/events.h:797:8: note: template<class T, class C> void osquery::EventSubscriber<PUB>::subscribe(osquery::Status (T::*)(const std::shared_ptr<C>&, const void*), const SubscriptionContextRef&, void*) [with T = T; C = C; PUB = osquery::INotifyEventPublisher]
   void subscribe(Status (T::*entry)(const std::shared_ptr<C>&, const void*),
        ^
/usr/local/include/osquery/events.h:797:8: note:   template argument deduction/substitution failed:
program.cpp:41:54: note:   candidate expects 3 arguments, 2 provided
   subscribe(&NewETCFilesEventSubscriber::Callback, sc);
                                                      ^
gmake[2]: *** [build/Debug/GNU-Linux-x86/program.o] Error 1
gmake[2]: Leaving directory `/home/chenone2316/NetBeansProjects/osquery'
gmake[1]: *** [.build-conf] Error 2
gmake[1]: Leaving directory `/home/chenone2316/NetBeansProjects/osquery'
gmake: *** [.build-impl] Error 2

BUILD FAILED (exit value 2, total time: 2s)

**Comment by sami2316** [comment]
@theopolis @marpaia why there are errors relating to subscribe function? Errors are up above...

**Comment by sami2316** [comment]
Ok well, subscribe function error is solved, but error with Register function still exists. Please guide me with the possible solution.

 
In file included from program.cpp:4:0:
program.cpp:37:1: error: expected unqualified-id before string constant
 REGISTER(NewETCFilesEventSubscriber, "event_subscriber", "new_etc_files");
 ^
gmake[2]: *** [build/Debug/GNU-Linux-x86/program.o] Error 1
gmake[2]: Leaving directory `/home/chenone2316/NetBeansProjects/osquery'
gmake[1]: *** [.build-conf] Error 2
gmake[1]: Leaving directory `/home/chenone2316/NetBeansProjects/osquery'
gmake: *** [.build-impl] Error 2

BUILD FAILED (exit value 2, total time: 3s)

**Comment by sami2316** [comment]
I was able to solve above errors myself. But the following one is out of my approach. Please guide me

"/usr/bin/gmake" -f nbproject/Makefile-Debug.mk QMAKE= SUBPROJECTS= .build-conf
gmake[1]: Entering directory `/home/chenone2316/NetBeansProjects/osquery'
"/usr/bin/gmake"  -f nbproject/Makefile-Debug.mk dist/Debug/GNU-Linux-x86/osquery
gmake[2]: Entering directory `/home/chenone2316/NetBeansProjects/osquery'
mkdir -p build/Debug/GNU-Linux-x86
rm -f "build/Debug/GNU-Linux-x86/program.o.d"
g++ -I/usr/local/include/ -losquery -lthrift -lboost_system -lboost_filesystem -lglog -lrocksdb -L/usr/local/lib/   -c -g -std=c++11 -MMD -MP -MF "build/Debug/GNU-Linux-x86/program.o.d" -o build/Debug/GNU-Linux-x86/program.o program.cpp
mkdir -p dist/Debug/GNU-Linux-x86
g++ -I/usr/local/include/ -losquery -lthrift -lboost_system -lboost_filesystem -lglog -lrocksdb -L/usr/local/lib/    -o dist/Debug/GNU-Linux-x86/osquery build/Debug/GNU-Linux-x86/program.o -losquery -lboost_thread -lglog -lthrift -lrocksdb -lpthread -lz -lbz2 -lcrypt -ldl -s
build/Debug/GNU-Linux-x86/program.o: In function `osquery::INotifyEventPublisher::INotifyEventPublisher()':
/home/chenone2316/osquery/osquery/events/linux/inotify.h:113: undefined reference to `vtable for osquery::INotifyEventPublisher'
collect2: error: ld returned 1 exit status
gmake[2]: *** [dist/Debug/GNU-Linux-x86/osquery] Error 1
gmake[2]: Leaving directory `/home/chenone2316/NetBeansProjects/osquery'
gmake[1]: *** [.build-conf] Error 2
gmake[1]: Leaving directory `/home/chenone2316/NetBeansProjects/osquery'
gmake: *** [.build-impl] Error 2

**Comment by sami2316** [comment]
I have written code to use ```osquery``` api as extension. Source code is https://github.com/sami2316/random_osBro/blob/master/Client/main.cpp#L167-L174: my question is how to run ```brokerMessageQuery() ``` through/inside ```osquery::runner```. Till this point, I am calling it manually creating plugin class object and then calling it as you can see in code) and the code works. But I need to handover it to ```osqueryd```.  Is there some nicer way to do it?
