### ISSUE TITLE
Site osquery.io doesn't work under Chrome/Linux x64

### ISSUE THREAD

**Issue by hugoeld** [facebook/osquery#1115]
Request to https://osquery.io/ results in ERR_SSL_VERSION_OR_CIPHER_MISMATCH error in Chrome.

**Comment by marpaia** [comment]
We are irregularly restrictive on our cipher suite: 

- SSLCipherSuite HIGH:!aNULL:!MD5:!SSLv3:!SSLv2
- SSLProtocol all -SSLv2 -SSLv3

Can you confirm what ciphers that your browser is sending?

**Comment by sharvilshah** [comment]
@marpaia osquery.io's apache is [only configured for TLS 1.2] (https://www.ssllabs.com/ssltest/analyze.html?d=osquery.io). I am guessing chrome/chromium might be limited to TLS 1.1 on Linux. Comparing [this to my server](https://www.ssllabs.com/ssltest/analyze.html?d=sharvil.io), any reason not to support TLS 1.0 and TLS 1.1 (could be just misconfiguration)

**Comment by theopolis** [comment]
Not misconfigured, stepping up the Qualys report card game!

**Comment by sharvilshah** [comment]
> Not misconfigured, stepping up the Qualys report card game (A+)!

:+1:

**Comment by hugoeld** [comment]
@sharvilshah yes, seems like it's Chrome on Debian 7 is limited to TLS 1.1 on Linux.
What do you think about allowing TLS 1.1 in Apache?

**Comment by theopolis** [comment]
You twisted my arm and 1.1/1.0 are now enabled. :facepunch:

**Comment by sharvilshah** [comment]
Judging from this Debian bug report:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=771948 seems Chrome got
updated and is now fixed.

**Comment by hugoeld** [comment]
@theopolis Thanks from all chrome+debian folks!
