### ISSUE TITLE
config_md5 discrepancy

### ISSUE THREAD

**Issue by jacknagz** [facebook/osquery#1135]
On RHEL6.5+osquery-1.4.5, I'm running into an issue where the config_md5 field from osquery_info does not match the output of md5sum.  Confirmed this behavior on 3+ machines. 

"SELECT * FROM osquery_info"  output
```
{"name":"osquery_info","hostIdentifier":"","calendarTime":"Mon May 11 20:25:45 2015 UTC","unixTime":"1431375945","columns":{"build_distro":"rhel6","build_platform":"rhel","config_md5":"e67b4d35234ebdaf3bf228f3d6b4ea5a","config_path":"\/etc\/osquery\/osquery.conf","extensions":"active","pid":"30336","version":"v1.4.5"},"action":"added"}
```

md5sum: 
```
$ md5sum /etc/osquery/osquery.conf
9581d8c62506fb164a1f91cd0f6c9255  /etc/osquery/osquery.conf
```

**Comment by theopolis** [comment]
Right! We should rename the `config_md5` in `osquery_info` to `config_checksum`. Since there are arbitrary config plugins we calculate the md5 of the config based on the amalgamated/transformed JSON that is read, parsed, merged (from optional multiple sources), and optimized.

**Comment by marpaia** [comment]
@jacknagz is the content of `config_md5` consistent across the different machines?

**Comment by jacknagz** [comment]
@marpaia yep!  I was only concerned as the 'md5sum' of the actual file didn't match what osquery outputted.  Though it seems, that's by design.  There is definitely consistency across the machines in terms of md5sum and config_md5 output.

**Comment by marpaia** [comment]
Yeah, as @theopolis said, your config gets re-written a bit when read, so I don't think we can support config_md5 displaying the actual md5 of the file. I'm going to add a `wontfix` tag to this, I hope that the way it works now is sufficient.

**Comment by jacknagz** [comment]
@marpaia no issues! :+1:
