### ISSUE TITLE
Ubuntu Server 14.04: missing dependency

### ISSUE THREAD

**Issue by alexwoolford** [facebook/osquery#1140]
I tried installing osquery on Ubuntu Server 14.04 per the instructions in the docs.

The following error was returned when I tried to run `osqueryi`:

    osqueryi: error while loading shared libraries: libcryptsetup.so.4: cannot open shared object file: No such file or directory

It was necessary to install the following dependency in order to make it work:

    sudo apt-get install libcryptsetup-dev

Perhaps this dependency could be bundled so that it gets included when `sudo apt-get install osquery` is run, or include this step in the docs.

**Comment by theopolis** [comment]
Right! Ideally we should build this statically on our build hosts and ship without the -dev runtime dependency (see: https://github.com/facebook/osquery/pull/1131).

**Comment by theopolis** [comment]
If gcrypt is installed by default, I have a solution :)

**Comment by alexwoolford** [comment]
That sounds promising. I did a `dpkg-query -l '*gcrypt*'` on a virgin Ubuntu 14.04 server install and notice that `libgcrypt11` is available.

**Comment by theopolis** [comment]
This is my current attempt at a long-term fix (https://github.com/facebook/osquery/pull/1141). It will require some package removals if you're building at home. But when we "rebase" our Jenkins package builders they will build without the dynamic dependent libcryptsetup on all OSes.

**Comment by theopolis** [comment]
Should be fixed in future builds as of: https://github.com/facebook/osquery/blob/master/tools/provision/ubuntu.sh#L101

**Comment by theopolis** [comment]
Checked with: https://jenkins.osquery.io/userContent/build/trusty/osquery-latest-1.4.5-61-g525c584.deb, looks good!
