### ISSUE TITLE
osquery-1.4.5 RPM missing dependency on cryptsetup

### ISSUE THREAD

**Issue by adrianbn** [facebook/osquery#1149]
Hi,

The osquery-1.4.5 RPM from the dowloads page is not specifying any dependency on cryptsetup but when I try to run it in CentOS 6.5 it fails with:

`osqueryd: error while loading shared libraries: libcryptsetup.so.1: cannot open shared object file: No such file or directory`

After installing cryptsetup-luks-libs from the standard YUM repository it starts fine. I also checked with rpm -qpR and the dependency on cryptsetup-luks-libs is not listed there. 

Thanks!

**Comment by theopolis** [comment]
Thanks @adrianbn, we missed that dependency for 1.4.5. In master we first added it [here](https://github.com/facebook/osquery/pull/1131). And then removed the requirement for the system-provided cryptosetup libs [here](https://github.com/facebook/osquery/pull/1141). :)
