### ISSUE TITLE
Add QueryContext Constraint existence check by type

### ISSUE THREAD

**Issue by mofarrell** [facebook/osquery#1160]
When using the query context constraints to optimize table generation, a check for the existence of constraints is used.  This is to detect whether the table generation may be optimized.  In many cases the table generation should only be optimized when an `EQUALS` constraint is used.  Empty result sets may be obtained when using other constraint types as the table generation is optimized despite the fact that the code does not support it.

Example:
```
  if (context.constraints["pid"].exists()) {
    pids = context.constraints["pid"].getAll(EQUALS);
  } else {
    osquery::procProcesses(pids);
  } 
```
Here the optimized code path only supports `EQUALS` constraint types.
We should add the functionality to `exists` to detect for specific constraint types.

**Comment by theopolis** [comment]
I say we start by adding an optional parameter to `ConstraintList::exists()` => `ConstraintList::exists(ConstraintOperator op = ???)`. We then have two options, `???` can be set to `EQUALS` or a new `ANY_OP`. What is the assumption when you write `::exists()`?

1. `::exists()` asks if "any" constraint exists.
2. `::exists()` asks if a bound/specific enumeration should occur. 

I vote for 1 and we refactor the `::exists()` callsites to `::exists(EQUALS)`.
