### ISSUE TITLE
Some tables are missing on FreeBSD

### ISSUE THREAD

**Issue by wxsBSD** [facebook/osquery#1161]
While working on a processes table implementation for FreeBSD I noticed that processes tables which should be there is not. For example, this is on the latest master on a FreeBSD machine:

```
wxs@osquery osquery % build/debug_11.0/osquery/osqueryi "select * from processes;"
Error: no such table: processes
wxs@osquery osquery % 
```

Given the contents of processes.cpp (https://github.com/facebook/osquery/blob/master/osquery/tables/system/freebsd/processes.cpp) I would expect to see something besides that.

It seems like anything in that directory which is a symlink is a working (for various definitions of working) table, while processes is not. I suspect this is a problem somewhere in the build process but I'm unable to tease it out tonight. Hoping @theopolis can shed some light on things for me.

**Comment by theopolis** [comment]
Right, my fault, the spec files that build the callsites for the implementations (the classes that call those functions) are [blacklisted](https://github.com/facebook/osquery/blob/master/osquery/tables/specs/blacklist). :dancers: 

When you `make` you should see output like: [Blacklisting generated...](https://github.com/facebook/osquery/blob/master/tools/codegen/gentable.py#L211). If you remove the "freebsd:TABLE_NAME" lines from the blacklist file linked above those tables should become available.

**Comment by wxsBSD** [comment]
Perfect! I'll do so today and continue on my way. I knew it was an easy fix!

Nice side effect of this is that now I know that blacklisted tables are compiled but left out of the linking.
