### ISSUE TITLE
RHEL6.5 Dependency Version Checking

### ISSUE THREAD

**Issue by jacknagz** [facebook/osquery#1165]
I'm running into a build time dependency issue where `./tools/provision/lib.sh` is not checking versions of installed dependencies.  This becomes an issue for me as demonstrated below:

```
configure.ac:19: require Automake 1.12, but have 1.11.1
make: *** [deps] Error 1
```

Automake 1.11.1 comes installed on my system, however the provisioning is only checking that the binary (or library) exists before attempting to install.  If we can add in some version checking (on some of the deps) with `rpm -q` this would help.  

```
# rpm -q automake
automake-1.11.1-4.el6.noarch
```

OR even better: 

```
# rpm -qi automake | grep 'Version' | awk '{print $3;}'
1.11.1
```

**Comment by theopolis** [comment]
Sounds good! Would you mind sending a PR for the check? There should be install logic for automake already in lib.sh. If you can add the logic somehow to the `package` function maybe? And if you detect an out-of-date version then run `install_automake`.

Be warned that's a can of worms that requires a few other newer dependencies. You'll most likely need the whole autotools and friends suite. All of which are in lib. It might be easier to replace RHEL6.5 building with: https://github.com/facebook/osquery/blob/master/tools/provision/ubuntu.sh#L59 (this logic from ubuntu12).

**Comment by theopolis** [comment]
Hey @jacknagz, I've tested a few times from a base RHEL6.5 and I'm not encountering this. :(

**Comment by jacknagz** [comment]
Interesting, @theopolis it looks like the output of your [Jenkins](https://jenkins.osquery.io/job/osqueryMasterBuildRHEL6Package/51/console) server is showing the same thing:

```
configure.ac:34: the top level
configure.ac:19: require Automake 1.12, but have 1.11.1
make: *** [deps] Error 1
Build step 'Execute shell' marked build as failure
[copy-to-slave] Copying 'build/rhel6/osquery-*.rpm', excluding nothing, from 'file:/home/osquery/jenkins/workspace/osqueryMasterBuildRHEL6Package/' on 'org.jenkinsci.plugins.vSphereCloudSlave[RHEL6_ESX2]' to 'file:/var/lib/jenkins/userContent/' on the master.
Finished: FAILURE
```

**Comment by theopolis** [comment]
Good catch, looks like we need to improve the automake version discovery in provision. On new RHEL6.5 hosts there's no automake so it continues fine.
