### ISSUE TITLE
Process events

### ISSUE THREAD

**Issue by wxsBSD** [facebook/osquery#1169]
I'm reading up on the kevent interface on FreeBSD and realized it can be used to monitor events (fork, exec or exit) and signal delivery on processes. This could be really interesting to expose as a publisher. A quick google makes me believe you can do this with the netlink interface on Linux, and I have no clue about doing it on Darwin though I would be surprised if they didn't have a way to do it. Just curious if anyone thinks it's a good idea or not?

**Comment by mofarrell** [comment]
I think the kevent structure is also present on Darwin:
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man2/kevent.2.html

**Comment by theopolis** [comment]
@mofarrell and I had a short talk about this, @wxsBSD this is a good lead! The [`kqueue(2)`](https://www.freebsd.org/cgi/man.cgi?query=kqueue&sektion=2) API also exists in BSD/Darwin and allows a pid + set of actions to generate a call-in to the subscribing process. It's normally used to request actions on yourself or children, I wonder if it'll bark if your subscription set includes all PIDs. There might be a bit of a headache managing/tracking forks/execs and adding the resultant PIDs to your set. 

Are there any other applications that use kevent/kqueue to do this sort of process tracking?

**Comment by wxsBSD** [comment]
I don't know of any that use it like that off the top of my head. I opened this issue just to see what others thought and give a pointer to what I think is a good starting place in case anyone beats me to this.

I do agree that watching all pids can be cumbersome, but would have to experiment to see just how bad.

One thing probably worth thinking about here is that we probably want to support the notion of name as input here. Being able to say "all execs done by chrome" is much nicer than having to know the pid of chrome.

**Comment by theopolis** [comment]
Right, I could see having a KEventsPublisher with a subscription taking in a pid/names and then expressing the selections like:

```json
{
  "kevents": [
     {"name": "chrome"},
     {"pid": 9000}
  ]
}
```

Each dict in that list becomes a subscription. Then you'd get:

```sql
SELECT * FROM kevents_events;
```

**Comment by marpaia** [comment]
closing to keep the issue list clean, feel free to continue conversation on this topic in this issue.
