### ISSUE TITLE
Add ability to restrict file hashing to files less than a certain size

### ISSUE THREAD

**Issue by jesseendahl** [facebook/osquery#1171]
Hashing large files is expensive and when doing something like this https://twitter.com/mikearpaia/status/592494158608142336 you're probably looking for malware, so it would be great if you could do that same query but restrict the hashing to files under a few MB, so that you're not computing hashes for someone's 4GB .dmg downloads.

**Comment by jesseendahl** [comment]
So that you don't have to go check the tweet, the query is:

```
select f.path, h.md5, h.sha1 from file f, hash h where f.pattern='/Users/%/Downloads/%%' and f.path=h.path;
```

**Comment by theopolis** [comment]
Excellent idea!
