### ISSUE TITLE
documentation uses old added/removed format in using osqueryd docs

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#1175]
> https://github.com/facebook/osquery/blob/master/docs/wiki/introduction/using-osqueryd.md

Each query represents a monitored view of your operating system. The first time a scheduled query runs it logs every row in the resulting table with the "added" action. In this example, on an OS X laptop, after the first 60 seconds it would log:

```json
[
  {"model":"XHCI Root Hub SS Simulation","vendor":"Apple Inc."},
  {"model":"XHCI Root Hub USB 2.0 Simulation","vendor":"Apple Inc."},
  {"model":"BRCM20702 Hub","vendor":"Apple Inc."},
  {"model":"Internal Memory Card Reader","vendor":"Apple"},
  {"model":"Apple Internal Keyboard \/ Trackpad","vendor":"Apple Inc."},
  {"model":"Bluetooth USB Host Controller","vendor":"Apple Inc."}
]
```

If there are no USB devices added or removed to the laptop this query would never log a result again. The query would still run every 60 seconds but the results would match the previous run and thus no state change would be detected. If a USB memory stick was inserted and left in the laptop for 60 seconds the daemon would log:

```
[
  {"model":"U3 Cruzer Micro","vendor":"SanDisk Corporation"}
]
```

Each line in the results is decorated with a bit more information as described in the [logging](../deployment/logging.md) guide. This includes time, hostname, added or removed action, etc.

**Comment by marpaia** [comment]
this page should really just point to http://osquery.readthedocs.org/en/stable/deployment/logging/ and http://osquery.readthedocs.org/en/stable/deployment/configuration/ for more detailed information

**Comment by theopolis** [comment]
I think this 60k foot overview of configuration/logging for the daemon is ok. Both already point to the more detailed pages. The most important concepts when the reader is pursuing the introduction text is (1) there's a schedule, (2) it only logs differentials.
