### ISSUE TITLE
osquery relocation error on RHEL6.5 (dm_task_get_info_with_deferred_remove) libdevmapper.so.1.02

### ISSUE THREAD

**Issue by jacknagz** [facebook/osquery#1176]
On the most recent version of facebook/osquery#master, I'm running into the following error when trying to launch osqueryd/osqueryi on a RHEL 6.5 box. 

```
$ osqueryi
osqueryi: relocation error: osqueryi: symbol dm_task_get_info_with_deferred_remove, version Base not defined in file libdevmapper.so.1.02 with link time reference
$ ldd -v `which osqueryd` | grep not
$ ldd -v `which osqueryd` | grep libdev
	libdevmapper.so.1.02 => /lib64/libdevmapper.so.1.02 (0x00007ff1e10e1000)
		libdevmapper.so.1.02 (Base) => /lib64/libdevmapper.so.1.02
	/lib64/libdevmapper.so.1.02:
```

**Comment by theopolis** [comment]
Hey @jacknagz, perhaps we need to include a version-specific libdevmapper package in the RPM.

**Comment by theopolis** [comment]
Default version of device-mapper-libs: device-mapper-libs-1.02.79-8.el6.x86_64
Need version: 1.02.90-2.el6_6.3

**Comment by jacknagz** [comment]
@theopolis so this an additional dependency to be added in rhel.sh?

**Comment by jacknagz** [comment]
Just confirmed that yum updating `libdevmapper` allows osquery to run.
