### ISSUE TITLE
Darwin/OS X: make deps fails on rocksdb -- GFLAGS macro redefined error

### ISSUE THREAD

**Issue by sharvilshah** [facebook/osquery#1185]
Running `make deps` fails on:

```bash
[+] rocksdb is not installed/provisioned. installing...
[+] rocksdb is already downloaded. skipping download.
/tmp/osquery-provisioning/rocksdb-rocksdb-3.10.2 /tmp/osquery-provisioning
In file included from <built-in>:339:
<command line>:5:9: error: 'GFLAGS' macro redefined [-Werror,-Wmacro-redefined]
#define GFLAGS google
        ^
<command line>:4:9: In file included from <built-in>:note339: :
previous definition is <command line>here:5
:9: error: #define GFLAGS gflags'GFLAGS'
 macro        ^
redefined [-Werror,-Wmacro-redefined]
In file included from <built-in>:339:
In file included from <built-in><command line>::3395:
:9: <command line>:5:9: #define GFLAGS google
```

On both OS X 10.10 and 10.9.

Not entirely sure how to go about debugging this, since filenames/symbols seems to be missing.
Upstream issue perhaps? Could be user error too.

**Comment by theopolis** [comment]
We wont be building RocksDB from a tarball/source for much longer on OS X, waiting for: https://github.com/facebook/osquery/issues/1183. But maybe `GFLAGS` is being set in [lib.sh]( https://github.com/facebook/osquery/blob/master/tools/provision/lib.sh#L130)? That should come from `provision.sh` and should not include a GFLAGS define.

**Comment by sharvilshah** [comment]
Yeah that seems likely. 
FWIW If I manually `brew uninstall gflags` and then `make static_lib` in `/tmp/osquery-provisioning/rocksdb-rocksdb-3.10.2`, it works.

**Comment by theopolis** [comment]
When #1192 lands you will need to:
```sh
sudo chown -R $USER /usr/local/include/
brew link --overwrite rocksdb
```
