### ISSUE TITLE
Schedule queries could include a "removed": False to limit results to action=added

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1190]
This is an intermediate between scheduled queries and the normal event-style results logging. For informational or status queries such as osquery_info it's only important to see the added actions. A schedule like:

```json
{
  "schedule": {
    "osquery_info": {
      "query": "select * from osquery_info",
      "interval": 10,
      "removed": false
  }
}
```

Would only emit results logs where `"action":true`.

**Comment by marpaia** [comment]
This is neat, I could see this being useful, for sure.
