### ISSUE TITLE
Linking External Library with Osquery

### ISSUE THREAD

**Issue by sami2316** [facebook/osquery#1200]
I'm trying to implement the event framework with a communication library, but when I tried  make command; it is not able to link with that library.so. Outside the make command, cpp file compiles with gcc -llibrary... command.
How do i pass or link it with osquery code?

[root@localhost osquery]# make
cd build/centos7 && cmake ../../ && \
	CTEST_OUTPUT_ON_FAILURE=1 make --no-print-directory 
-- Building for CentOS
-- Found components for DL
-- Found readline library
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   unit_test_framework
--   system
--   regex
--   date_time
--   thread
--   filesystem
--   program_options
--   chrono
--   atomic
-- Found PythonInterp: /usr/bin/python (found version "2.7.5") 
-- Found RocksDB
-- Thrift version 0.9.1
-- Found PythonInterp: /usr/bin/python (found suitable version "2.7.5", minimum required is "2") 
-- Found library dependency /usr/local/lib/libboost_thread.a
-- Found library dependency /usr/lib64/librt.so
-- Found library dependency /usr/local/lib/libboost_system.a
-- Found library dependency /usr/local/lib/libboost_filesystem.a
-- Found library dependency /usr/local/lib/libboost_regex.a
-- Found library dependency /usr/local/lib/libyara.a
-- Found library dependency /usr/lib64/libudev.so
-- Found library dependency /usr/lib64/librpm.so
-- Found library dependency /usr/lib64/librpmio.so
-- Found library dependency /usr/lib64/libblkid.so
-- Found library dependency /usr/local/lib/libcryptsetup.a
-- Found library dependency /usr/lib64/libdevmapper.so
-- Found library dependency /usr/lib64/libgcrypt.so
-- Found library dependency /usr/lib64/libudev.so
-- Found library dependency /usr/lib64/libuuid.so
-- Found library dependency /usr/local/lib/libip4tc.a
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/osquery/build/centos7
[  3%] Built target libglog
[  3%] Built target cppnetlib-client-connections
[  3%] Built target cppnetlib-server-parsers
[  4%] Built target cppnetlib-uri
[  4%] Built target gtest
[  5%] Built target gtest_main
[  5%] Built target osquery_sqlite
[  8%] Built target osquery_extensions
[ 31%] Built target osquery_additional_amalgamation
[ 34%] Built target osquery_config_plugins
[ 35%] Built target osquery_devtools
[ 36%] Built target osquery_events_linux
[ 36%] Built target osquery_logger_plugins
[ 37%] Built target osquery_remote
[ 37%] Built target osquery_enrollment_plugins
[ 38%] Built target osquery_sql_internal
[ 46%] Built target osquery_tables
[ 46%] Built target osquery_tables_redhat
[ 59%] Built target osquery_tables_linux
[ 60%] Built target osquery_utils
[ 60%] Built target libosquery_additional
[ 65%] Built target osquery_amalgamation
[ 65%] Built target osquery_config
[ 70%] Built target osquery_core
[ 71%] Built target osquery_database
[ 71%] Built target osquery_dispatcher
[ 72%] Built target osquery_distributed
[ 73%] Built target osquery_events
[ 73%] Built target osquery_filesystem
[ 74%] Built target osquery_filesystem_linux
[ 75%] Built target osquery_logger
[ 76%] Built target osquery_registry
[ 77%] Built target osquery_sql
[ 79%] Built target osquery_tables_utility
[ 80%] Built target libosquery
Linking CXX executable osqueryd
libosquery_additional.a(new_etc_files.cpp.o): In function `global constructors keyed to a':
/home/user/osquery/osquery/tables/events/linux/new_etc_files.cpp:(.text.startup+0x159): undefined reference to `broker::endpoint::endpoint(std::string, int)'
/home/user/osquery/osquery/tables/events/linux/new_etc_files.cpp:(.text.startup+0x171): undefined reference to `broker::endpoint::~endpoint()'
libosquery_additional.a(new_etc_files.cpp.o): In function `osquery::tables::NewETCFilesEventSubscriber::init()':
/home/user/osquery/osquery/tables/events/linux/new_etc_files.cpp:(.text._ZN7osquery6tables26NewETCFilesEventSubscriber4initEv[_ZN7osquery6tables26NewETCFilesEventSubscriber4initEv]+0x2f): undefined reference to `broker::init(int)'
/home/user/osquery/osquery/tables/events/linux/new_etc_files.cpp:(.text._ZN7osquery6tables26NewETCFilesEventSubscriber4initEv[_ZN7osquery6tables26NewETCFilesEventSubscriber4initEv]+0x48): undefined reference to `broker::endpoint::listen(unsigned short, char const*, bool)'
/home/user/osquery/osquery/tables/events/linux/new_etc_files.cpp:(.text._ZN7osquery6tables26NewETCFilesEventSubscriber4initEv[_ZN7osquery6tables26NewETCFilesEventSubscriber4initEv]+0x52): undefined reference to `broker::endpoint::incoming_connection_status() const'
/home/user/osquery/osquery/tables/events/linux/new_etc_files.cpp:(.text._ZN7osquery6tables26NewETCFilesEventSubscriber4initEv[_ZN7osquery6tables26NewETCFilesEventSubscriber4initEv]+0x5f): undefined reference to `broker::queue<broker::incoming_connection_status>::need_pop() const'
libosquery_additional.a(new_etc_files.cpp.o): In function `osquery::tables::NewETCFilesEventSubscriber::Callback(std::shared_ptr<osquery::INotifyEventContext> const&, void const*)':
/home/user/osquery/osquery/tables/events/linux/new_etc_files.cpp:(.text._ZN7osquery6tables26NewETCFilesEventSubscriber8CallbackERKSt10shared_ptrINS_19INotifyEventContextEEPKv[_ZN7osquery6tables26NewETCFilesEventSubscriber8CallbackERKSt10shared_ptrINS_19INotifyEventContextEEPKv]+0x83): undefined reference to `broker::to_string(broker::data const&)'
/home/user/osquery/osquery/tables/events/linux/new_etc_files.cpp:(.text._ZN7osquery6tables26NewETCFilesEventSubscriber8CallbackERKSt10shared_ptrINS_19INotifyEventContextEEPKv[_ZN7osquery6tables26NewETCFilesEventSubscriber8CallbackERKSt10shared_ptrINS_19INotifyEventContextEEPKv]+0xeb): undefined reference to `broker::to_string(broker::data const&)'
/home/user/osquery/osquery/tables/events/linux/new_etc_files.cpp:(.text._ZN7osquery6tables26NewETCFilesEventSubscriber8CallbackERKSt10shared_ptrINS_19INotifyEventContextEEPKv[_ZN7osquery6tables26NewETCFilesEventSubscriber8CallbackERKSt10shared_ptrINS_19INotifyEventContextEEPKv]+0x186): undefined reference to `broker::endpoint::send(std::string, std::vector<broker::data, std::allocator<broker::data> >, int) const'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [osquery/osqueryd] Error 1
make[2]: *** [osquery/CMakeFiles/daemon.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2

**Comment by theopolis** [comment]
What is the name of the library you're trying to add? Take a look at how we link external libraries for the built-in tables: https://github.com/facebook/osquery/blob/master/osquery/tables/CMakeLists.txt#L62

**Comment by sami2316** [comment]
Thank you. It worked.

**Comment by sami2316** [comment]
I have read the whole documentation but i'm not getting; how to remotely query on demand. There is little clue in Extension manager but not clear to me. 
Is there a way to remotely query sql statement? If currently there is no support then any idea?

**Comment by marpaia** [comment]
using the python interface to thrift:

```
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import osquery
>>> client = osquery.ExtensionClient(path="/Users/marpaia/.osquery/shell.em")
>>> client.open()
>>> client.extension_client().query("select * from time")
ExtensionResponse(status=ExtensionStatus(message='OK', code=0, uuid=0), response=[{'seconds': '16', 'minutes': '9', 'hour': '15'}])
>>>
```

**Comment by marpaia** [comment]
it'll be pretty similar for C++, reading through that code path should be illustrative of the approach

**Comment by sami2316** [comment]
Is there reference example for writing shell.em
```client = osquery.ExtensionClient(path="/Users/marpaia/.osquery/shell.em")``` 
&
Is there any reference example for C++?

**Comment by marpaia** [comment]
Check out the extensions tests: https://github.com/facebook/osquery/blob/e57d15da86eef81f99431c53a26506647ce18a9f/osquery/extensions/tests/extensions_tests.cpp, grep for `EXManagerClient`, you'll see a ton of usage there. also look at https://github.com/facebook/osquery/blob/master/osquery/extensions/extensions.cpp and grep for `EXManagerClient`, you'll also see a lot of usage there too.

**Comment by sami2316** [comment]
Thanks @marpaia . One thing more.
What if I want to use my own connection library for remote host query, then where should I put that connection establish and break code like ```osqueryd``` connect with slave nodes?

**Comment by theopolis** [comment]
Hi @sami2316, I am not sure what you mean in your last two questions. Can you please elaborate?

**Comment by sami2316** [comment]
Actually, I want to remotely query ```osquery``` using ```broker``` library. Communication b/w endpoint will be established with ```broker``` and over that connection ```master broker``` point can send ```sql``` statement via its message function. Then the ```broker slave``` side should interpret that sql statement to query using ```osquery```. 
As per my knowledge, ```osquery``` provides extensions to query outside the ```osqueryi``` shell or ```osqueryd```. If I'm wrong do correct me. I need to build and manage ```borker``` connection inside ```osquery``` but I'm not getting where to put that part exactly for compatibility with ```osquery```. 

Is it clear to you?

**Comment by marpaia** [comment]
You can use the thrift interface to issue queries to osqueryd. Your code will have to implement all of the additional stuff you'd like to do around brokering and negotiation. The thrift signature for querying is here: https://github.com/facebook/osquery/blob/420b4edcefd6ba1beff729e2e6046d1d2d39e9d8/osquery.thrift#L86-L89

**Comment by sami2316** [comment]
@marpaia Please correct me where I'll be wrong: After analyzing ```interface.cpp & extension.cpp``` I came up with the thought that ```broker``` code will be in ```extension.cpp``` (broker functions) as additional functionality. I'm confused about calling these functions; 
_whether_ I need to call them in function like ```startExtension()``` and follow example in: https://osquery.readthedocs.org/en/stable/development/osquery-sdk/ 
_or_ there is some other way for auto calling my code with ```osqueryd```

**Comment by marpaia** [comment]
I don't know what a `broker` is in your context, so I can't comment on that. If you have external plugins and you want them to be actively available in osqueryd, you _must_ `startExtension`.

**Comment by sami2316** [comment]
I redefine my question: Is there a way to write internal plug-ins? and secondly if I'm writing external plug-in then do I have to use ```queryExternal()``` from ```extension.cpp``` instead of ```query``` as in ```thrift interface```?

**Comment by marpaia** [comment]
you can totally write internal plugins! in fact, all of the tables that come with osquery, the filesystem config plugin, the filesystem logger plugin, the tls plugins are all internal plugins. so if you're building osquery from source and you want to build your external plugins directly into the binary, that's totally possible.

**Comment by marpaia** [comment]
if you're writing an external plugin and want to query, getting an extension manager client instantiated and calling the query call on the extension manager's socket (via the thrift interface) would be how you want to go about it, which is exactly what `queryExternal` does :) it's just one of the niceties of writing your osquery plugins in C++

**Comment by marpaia** [comment]
As you can see, you can call any thrift call on the client:

```cpp
  ExtensionResponse response;
  try {
    auto client = EXManagerClient(manager_path);
    // this can be any thrift call
    client.get()->query(response, query);
  } catch (const std::exception& e) {
    return Status(1, "Extension call failed: " + std::string(e.what()));
  }
```

**Comment by sami2316** [comment]
Thanks ... now, it is more clear to me. Is Threading (for parallel tasks) supported in this framework?

**Comment by theopolis** [comment]
Concurrent requests are supported in Thrift! By default the daemon/shell will run 2 concurrent tasks based on the default vault of `--worker_threads=2`, which is passed to the Thrift service here: https://github.com/facebook/osquery/blob/master/osquery/extensions/interface.cpp#L190

**Comment by sami2316** [comment]
@theopolis I have written my class for ```brokering```;  I derived it from ```ConfigPlugin```. I am calling my broker connection functions in ```setUp()```. But when I run ```startExtension()```then nothing happens. I followed https://github.com/facebook/osquery/blob/master/osquery/examples/example_extension.cpp example program to run my extension. 
What am I not getting: how to handover my functions to osquery runner for automatic call. Please guide me.

**Comment by sami2316** [comment]
@marpaia 
You said we can compile extension code through ```osquery``` build system. but how can we: extension code contains ```main``` function and there can be only one``` main()``` in a program.
If it is possible to build extension code through ```osquery``` then where to place ```myExtensin.cpp``` file? 
Please guide me.

**Comment by marpaia** [comment]
@sami2316 if you wanted to define a new executable, you could use `add_executable` like such: https://github.com/facebook/osquery/blob/fa36a8918be5e0f38c546df3a70ac3d59adefc84/osquery/CMakeLists.txt#L248-L252

Although if you're just linking against the SDK for a private extension that you don't want to merge upstream, I would suggest using your own build tooling and just link against the osquery library.
