### ISSUE TITLE
Syslog Logger Plugin

### ISSUE THREAD

**Issue by jacknagz** [facebook/osquery#1207]
Enhancement: Creation of a logger plugin to write JSON osqueryd results via the syslog API into a configurable facility.  This would greatly facilitate the usage of rsyslog for central aggregation of osqueryd logs.  

Perhaps the INFO/FATAL/ERROR logs could also be written out to the same facility with each respective priority.

**Comment by theopolis** [comment]
Definitely, what type of control would you like over the pluign? What additional `--logger_syslog*` flags would be helpful when someone sets `--logger_plugin=syslog`

**Comment by jacknagz** [comment]
`--logger_syslog_facility` for facility option
`--logger_syslog_priority` for log level

**Comment by theopolis** [comment]
Perfect, thanks @jacknagz

**Comment by theopolis** [comment]
Setting a numerical facility override would be helpful/flexible, combined with us choosing a user-optional value (say LOCAL3, or USER) as default. The priority will be assigned by either the result or status log message. The caller/installer will not control levels.

Results: info
Informational status: notice
Warning status: warning
Error status: error

The only inconsistency is the info label applied to results logging, but those are more "informational" the what we call informational statuses, which indicate non-default but acceptable behavior.

**Comment by jacknagz** [comment]
sounds great @theopolis

**Comment by theopolis** [comment]
Suggested implementation: https://github.com/facebook/osquery/pull/1212
