### ISSUE TITLE
osquery_schedule: average cpu

### ISSUE THREAD

**Issue by jacknagz** [facebook/osquery#1242]
Enhancement: The addition of an `average_cpu` column in the `osquery_schedule` table would greatly help with judging continuous performance across a fleet of systems.   This value could be an average CPU load of `osqueryd` when each query executes.  If there's a way to already get this in the data, I'd love to hear :+1:

**Comment by marpaia** [comment]
Try launching osquery with the `enable_monitor` option. In your config:

```json
{
  "options": {
    "enable_monitor": "true"
  },
  "schedule": {
  }
}
```

**Comment by theopolis** [comment]
Right, we have two increasing counters representing user and system cycles. We can definitely add a third that represents an average of both, per query.

**Comment by theopolis** [comment]
Hey @jacknagz, instead of a new column let's just use: 

```sql
SELECT ((user_time + system_time) / (executions)) AS avg_cpu, name
  FROM osquery_schedule
  WHERE avg_cpu > 0;
```

Add the `WHERE` clause to only emit the rows that were not victim of a "divide by 0" fault, aka haven't yet run. Does this get the job done?
