### ISSUE TITLE
Prefer RocksDB LITE for distributions (smaller binary size, less features)

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1259]
In anecdotal tests I've seen better memory performance with the [LITE](https://github.com/facebook/rocksdb/blob/master/ROCKSDB_LITE.md) version of RocksDB. FreeBSD and OS X are the two platforms were we install RocksDB from a package. This means we'll need to configure via the respective package manager (brew/ports) to build a `librocksdb.a` with the `-DROCKSDB_LITE=1` define.

**Comment by theopolis** [comment]
We can detect if the build host has RocksDB LITE installed by checking for the absence of a link-time symbol.

```cmake
# Check for RocksDB LITE by detecting missing symbols at link-time.
# If the LITE version is installed, we must also define ROCKSDB_LITE=1.
include(CheckCXXSourceCompiles)
set(CMAKE_CXX_FLAGS ${CXX_COMPILE_FLAGS})
check_cxx_source_compiles("
  #include <rocksdb/db.h>
  using namespace rocksdb;
  // Check for symbol that does not exist with -DROCKSDB_LITE=1
  int main(int, char**) {
    Options options;
    auto status = RepairDB(\"test\", options);
    return 0;
  }" ROCKSDB_NON_LITE)

if(${ROCKSDB_NON_LITE})
  WARNING_LOG("RocksDB was not installed as RocksDB LITE")
else()
  add_definitions(-DROCKSDB_LITE=1)
endif()
```

Otherwise, if there is inconsistency with the defines (aka):
- If define `-DROCKSDB_LITE=1` at compile/link time, but rocksdb was compiled without--
- If we do NOT define `-DROCKSDB_LITE=1` at compile/link time, but rocksdb was compiled with--

We will abort at runtime.

**Comment by theopolis** [comment]
@igorcanadi, this is my best attempt at a "test-for-lite" macro (w.r.t. our previous discussion about requiring consistency for `-DROCKSDB_LITE=1` usage). I don't feel very good about it, since a failure-to-compile does NOT always indicate a non-LITE RocksDB. I should at least add a secondary macro that checks to see if a basic include + link works.

**Comment by igorcanadi** [comment]
@theopolis how about you have two static libraries: librocksdb.a and librocksdb_lite.a. You can prefer librocksdb_lite.a if present, and if not, compile with librocksdb.a?

**Comment by theopolis** [comment]
Right! That would work if the RocksDB compile/build logic could produce the `_lite.a` library (or symlink) when LITE was enabled.

**Comment by igorcanadi** [comment]
In the short-term, you should be able to do `OPT=-DROCKSDB_LITE=1 LIBNAME=librocksdb_lite make static_lib`, but maybe we should add a target `make lite` that will do all of this for you.

**Comment by theopolis** [comment]
We can control our build hosts completely, so we can default assume the RocksDB installed is the Lite version without needing to modify the library path. I can't figure out how we bootstrap the lite/non-lite assumption on an arbitrary developer's machine.

We could punt on that assumption, and only build for Lite if we find `_lite.a` and update our dependency build scripts to only install `_lite.a`. If we add a short configure notice if we cannot find the `_lite.a` path we should be gtg!

**Comment by theopolis** [comment]
Solved! Now using the dedicated libname to determine LITE in #1331.
