### ISSUE TITLE
Tcpflow functionality on top of event framework

### ISSUE THREAD

**Issue by astanway** [facebook/osquery#127]
Capture TCP headers, footers, and payloads (and demarcate them as such, printing the payload prettily in ASCII like tcpflow does) as part of the event framework.

The table would include:
```
header
footer
payload
source_ip
source_port
destination_ip
destination_port
```

The header and footer are less important for now than the payload, so if we can get that (essentially what tcpflow does), then that would be an excellent start.

**Comment by marpaia** [comment]
This is being tracked in #622.
