### ISSUE TITLE
New table idea: uptime

### ISSUE THREAD

**Issue by timzimmermann** [facebook/osquery#1273]
Add a table that provides information about the time passed since booting the system, similar to the tool `uptime`.
If there is a general interest in this information being part of `osquery`, I would be happy to take on the task.

**Comment by marpaia** [comment]
@timzimmermann sure, a simple `uptime` table would be neat. Were you thinking one row, like `osquery_info`?

**Comment by marpaia** [comment]
You've probably already come across the wiki, but in-case you haven't, the canonical instructions for creating a new table can be found here: http://osquery.readthedocs.org/en/stable/development/creating-tables/

**Comment by timzimmermann** [comment]
Yes, exactly. One row, similar to the `time` table, but with a `days` column in addition.
Thanks for the link, I already implemented it for OS X and Ubuntu. I have to test it on several other distributions and do automated tests though before I could publish it.

**Comment by marpaia** [comment]
@timzimmermann nice, like a boss. if you want, feel free to throw up a pull request. then, we (the osquery maintainers) can tell our friendly osquery bot, @osqueryer, to run all of the automated tests on all of the platforms that we support. it often makes the cross-platform development lifecycle a lot easier.

**Comment by theopolis** [comment]
I think @jacknagz had mentioned wanting uptime too. I'd recommend/request a column with `total_seconds` such that you don't have to do multiplication on minutes/hours/days during a select. ;)

**Comment by timzimmermann** [comment]
@theopolis Sure, `total_seconds` is a good idea. You mean in addition to the others, right?
Also, I searched for an `uptime` issue but haven't found one. Sorry for the duplicate, then. Maybe @jacknagz can let me know what his status on it is and we find a solution.
@marpaia Okay, great, I will open up a pull request soon.
Thanks for your help!

**Comment by marpaia** [comment]
I don't think @jacknagz ever wrote it, just noted that he wanted it. Feel free to move forward with your implementation :+1:
