### ISSUE TITLE
osqueryd goes zombie or dies on ubuntu12/ubuntu14 [osqueryd version 1.4.7]

### ISSUE THREAD

**Issue by liquid-sky** [facebook/osquery#1276]
Great tool and great functionality, however I cannot make it stay running for long either on Ubuntu 12 or Ubuntu 14. 

The process becomes `<defunct>` or dies without traces after running for a short while on both systems. Unfortunately, there are not clues in the log file, even when verbose debug is on.  

```
# ps -ef | grep os[q]
root     20807     1  0 09:03 ?        00:00:00 osqueryd --config_path=/etc/osquery/osquery.conf --pidfile=/var/run/osqueryd.pid --daemonize=true
root     22095 20807 10 09:08 ?        00:00:05 [osqueryd] <defunct>
```

Initially, I suspected that it might be related to the FIM, but I only added `/tmp` into file tracking and configured system limits as per [the guide](https://osquery.readthedocs.org/en/stable/deployment/file-integrity-monitoring/):

```
# sysctl -a | grep inotify
fs.inotify.max_user_instances = 256
fs.inotify.max_user_watches = 524288
fs.inotify.max_queued_events = 32768
```

...removing file paths from the configuration file _did not_ help. 

Last messages before it dies or restarts itself, before turning into a zombie, whether `file_paths` has been defined or not is: 
```
I0630 10:07:06.848131  8770 scheduler.cpp:83] Executing query: SELECT * FROM file_events;
```

Configuration file:
```
{
  "options": {
    "config_plugin": "filesystem",
    "logger_plugin": "filesystem",
    "logger_path": "/mnt/log/platform/osquery",
    "log_result_events": "true",
    "schedule_splay_percent": "10",
    "pidfile": "/var/run/osquery.pid",
    "event_pubsub_expiry": "86000",
    "database_path": "/var/osquery/osquery.db",
    "debug": "true",
    "verbose_debug": "true",
    "worker_threads": "1"
  },
  "schedule": {
    "listening_ports": {
      "query": "SELECT name, l.pid, port, uid FROM listening_ports l, processes p WHERE l.pid=p.pid;",
      "interval": 86400
    },
    "running_processes": {
      "query": "SELECT pid, name, path, cmdline, cwd, start_time, parent FROM processes;",
      "interval": 30
    },
    "crontab": {
      "query": "SELECT * FROM crontab;",
      "interval": 300
    },
    "suid_bin": {
      "query": "select * from suid_bin;",
      "interval": 300
    },
    "file_events": {
      "query": "SELECT * FROM file_events;",
      "interval": 300
    }
  },
  "file_paths": {
    "tmp": [
      "/tmp/%%"
    ]
  }
}
```

**Comment by liquid-sky** [comment]
Removing just this one stanza seemed to have kept the process stable: 

```
    "file_events": {
      "query": "SELECT * FROM file_events;",
      "interval": 300
    }
```

I tried adjusting interval to 420, but it did not help.

**Comment by marpaia** [comment]
@theopolis is actually currently working on improving `file_events`, so you should see improvements here soon. What version of osquery are you running?

**Comment by theopolis** [comment]
Hi @liquid-sky, thanks for those kind words! I'm sorry about the defuncting fiasco. In this case does a new daemon child (called worker) respawn? I realize the defunct is annoying and definitely a bug, but your schedule should continue to run after the parent respawns subsequent child workers. If that's not the case there's something more sinister going on here.

Your ps/grep should have identified a 3rd process, so I'm guessing the daemon DOES NOT create another worker process.

I'll try to replicate your setup and try to reproduce the worker deaths. I'm going to add --disable-watchdog such that the whole process group dies on an abort or except. Also, if you have apport running you should get a crash report in /var/crashes. I'll run my tests with a debug build in gdb.

Are there a particularly large number of files in /tmp on your system, and how long had osqueryd been running before you first noticed the defuncting?

**Comment by liquid-sky** [comment]
@marpaia, I deployed the latest binary version: 

```
# dpkg -s osquery | grep -i version
Version: 1.4.7-1.ubuntu14
```

**Comment by liquid-sky** [comment]
@theopolis, it does respawn a new worker, as can be seen from the log file (it logs that the listener has been added and even publisher loop has been started), but it does not survive for too long. I think it is safe to conclude that the process simply dies. 

There's a crash log for both types of systems, but with deployment time stamp. Not sure if it's related to this problem, because it hasn't left any other crash logs while I was experimenting. 

The easiest way to reproduce would be to set `file_event` query interval to the lowest value  (60 secs or so). 

There aren't many files in /tmp, but the files there are added and removed frequently. Just tried to reproduce that in Vagrant ubuntu VM, but wasn't able to. That's odd. The issue was observed in AWS. 

The run time is very random, which is also weird. If the query interval is set to 60, it dies pretty much after the first table scan. When it was set to 300s, I saw it running for a few hours even.

**Comment by liquid-sky** [comment]
This is how it looks like after a recent crash: 

```
# ps -ef | grep os[q]
root     29736     1  0 16:33 ?        00:00:00 osqueryd --config_path=/etc/osquery/osquery.conf --pidfile=/var/run/osqueryd.pid --daemonize=true
root     30081 29736  5 16:34 ?        00:00:03 [osqueryd] <defunct>
root     30472 29736  1 16:34 ?        00:00:00 osqueryd
```

There's nothing in `/var/crash`, unfortunately. 

Here's a snipped from the log. Workers PID was changing as it kept re-spawning and eventually died:

```
Log file created at: 2015/06/30 16:37:17
Running on machine: HOSTNAME
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0630 16:37:17.635630 31315 config.cpp:129] Verbose logging enabled by config option
I0630 16:37:17.635820 31315 config.cpp:129] Verbose logging enabled by config option
I0630 16:37:17.636009 31315 file_events.cpp:58] Added listener to: /tmp
I0630 16:37:17.637202 31323 events.cpp:429] Starting event publisher run loop: inotify
I0630 16:37:17.637442 31322 interface.cpp:220] Extension manager service starting: /var/osquery/osquery.em
I0630 16:37:17.639657 31324 events.cpp:429] Starting event publisher run loop: udev
I0630 16:37:19.364119 31323 db_handle.cpp:115] Opening RocksDB handle: /var/osquery/osquery.db
I0630 16:37:25.314219 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpSK4fK9
I0630 16:37:25.314291 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpSK4fK9
I0630 16:37:25.535138 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpSK4fK9
I0630 16:37:25.535214 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpSK4fK9
I0630 16:37:25.535254 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpSK4fK9
I0630 16:37:25.535919 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpSK4fK9
I0630 16:37:25.535964 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpSK4fK9
I0630 16:37:25.536000 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpSK4fK9
I0630 16:37:25.536551 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpjb4VX6
I0630 16:37:25.536595 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpjb4VX6
I0630 16:37:25.536633 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpjb4VX6
I0630 16:37:25.537212 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpjb4VX6
I0630 16:37:25.537261 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpjb4VX6
I0630 16:37:25.537298 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpjb4VX6
I0630 16:37:25.537808 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpjb4VX6
I0630 16:37:25.537854 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpjb4VX6
I0630 16:37:25.537889 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpjb4VX6
I0630 16:37:31.639324 31325 scheduler.cpp:83] Executing query: SELECT pid, name, path, cmdline, cwd, start_time, parent FROM processes;
I0630 16:37:31.834585 31325 scheduler.cpp:131] Found results for query (running_processes) for host: front-web03
I0630 16:37:45.033592 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpOoIJR1
I0630 16:37:45.033673 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpOoIJR1
I0630 16:37:45.033711 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpOoIJR1
I0630 16:37:45.034358 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpOoIJR1
I0630 16:37:45.034402 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpOoIJR1
I0630 16:37:45.034440 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpOoIJR1
I0630 16:37:45.034968 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpOoIJR1
I0630 16:37:45.035013 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpOoIJR1
I0630 16:37:45.035050 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpOoIJR1
I0630 16:37:45.035567 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpLBlYV9
I0630 16:37:45.035610 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpLBlYV9
I0630 16:37:45.035646 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpLBlYV9
I0630 16:37:45.036159 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpLBlYV9
I0630 16:37:45.036202 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpLBlYV9
I0630 16:37:45.036239 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpLBlYV9
I0630 16:37:45.036721 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpLBlYV9
I0630 16:37:45.036764 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpLBlYV9
I0630 16:37:45.036800 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpLBlYV9
I0630 16:38:02.839783 31325 scheduler.cpp:83] Executing query: SELECT pid, name, path, cmdline, cwd, start_time, parent FROM processes;
I0630 16:38:04.148555 31323 hash.cpp:98] Cannot hash/open file /tmp/tmp1lfi0t
I0630 16:38:04.148633 31323 hash.cpp:98] Cannot hash/open file /tmp/tmp1lfi0t
I0630 16:38:04.148671 31323 hash.cpp:98] Cannot hash/open file /tmp/tmp1lfi0t
I0630 16:38:04.150017 31323 hash.cpp:98] Cannot hash/open file /tmp/tmp1lfi0t
I0630 16:38:04.153216 31323 hash.cpp:98] Cannot hash/open file /tmp/tmp1lfi0t
I0630 16:38:04.153339 31323 hash.cpp:98] Cannot hash/open file /tmp/tmp1lfi0t
I0630 16:38:04.374166 31323 hash.cpp:98] Cannot hash/open file /tmp/tmp1lfi0t
I0630 16:38:04.374255 31323 hash.cpp:98] Cannot hash/open file /tmp/tmp1lfi0t
I0630 16:38:04.374301 31323 hash.cpp:98] Cannot hash/open file /tmp/tmp1lfi0t
I0630 16:38:04.374929 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpZjC7Cf
I0630 16:38:04.374986 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpZjC7Cf
I0630 16:38:04.375030 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpZjC7Cf
I0630 16:38:04.375609 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpZjC7Cf
I0630 16:38:04.375665 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpZjC7Cf
I0630 16:38:04.375710 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpZjC7Cf
I0630 16:38:04.376230 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpZjC7Cf
I0630 16:38:04.376283 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpZjC7Cf
I0630 16:38:04.376327 31323 hash.cpp:98] Cannot hash/open file /tmp/tmpZjC7Cf
I0630 16:38:04.994371 31325 scheduler.cpp:83] Executing query: SELECT * FROM file_events;
Log file created at: 2015/06/30 16:38:08
Running on machine: HOSTNAME
```

**Comment by theopolis** [comment]
Can you try dropping the `--daemonize=true` and instead using `--disable_watchdog` while a super low interval of file_events?

**Comment by theopolis** [comment]
I'd expect that instance to run without being forcefully killed by the watchdog daemon process. It will allocate memory beyond the "safe" limits though.

**Comment by theopolis** [comment]
Ok, I just ran a bit of tests and noticed a lack of warning log for forceful SIGKILLs of the worker processes notes here: #1277. I can fix this!

**Comment by liquid-sky** [comment]
@theopolis, running the process without the watchdog did help to keep the process running.

**Comment by liquid-sky** [comment]
Resource usage on 2x core, 7.5GB RAM VM, while scanning file_events every 10 seconds: 

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 5255 root      20   0  785560 364396   6192 S  98.6  4.7   1:22.84 osqueryd
```

**Comment by theopolis** [comment]
That's a bit high for `file_events` retrieval! Just curious, how many events are there: `select count(*) from file_events;`?

**Comment by liquid-sky** [comment]
not sure why, but I haven't seen any events there whatsoever: 

```
# osqueryi --database_path /var/osquery/
osquery - being built, with love, at Facebook

Using a virtual database. Need help, type '.help'
osquery> select * from file_events;
osquery> select count(*) from file_events;
+----------+
| count(*) |
+----------+
| 0        |
+----------+
```

**Comment by theopolis** [comment]
Try: `sudo osqueryi --database_path /var/osquery/osquery.db --verbose`, you need the full path to the database folder (usually ".db").

**Comment by liquid-sky** [comment]
Yeah, I already do that as `root`: 

```
# osqueryi --database_path /var/osquery/osquery.db --verbose
I0701 17:31:03.746578 32695 init.cpp:193] osquery initialized [version=1.4.7]
I0701 17:31:03.746776 32695 extensions.cpp:169] Could not autoload modules: Failed reading: /etc/osquery/modules.load
I0701 17:31:03.746999 32695 db_handle.cpp:115] Opening RocksDB handle: /var/osquery/osquery.db
E0701 17:31:03.747917 32695 init.cpp:330] osqueryi initialize failed: Could not open RocksDB
```

**Comment by theopolis** [comment]
Oh sorry, didn't notice your '#'. ;) The RocksDB database uses a process lock, a lock file in that directory. If there's another daemon/shell running it will fail additional accesses. If there's no other osquery[di] running then that's weird!

I'm working on the `file_events` logic now and I have some plans to make it much quicker and less taxing. It involves only emitting the "added" events when queried during the osquery schedule. Right now you'll get the whole lot for each SELECT and then use the differential logic, which is `O(n^2)`, to only emit the new events in the stream. That doesn't make sense for completely-additive tables aka those using our event publisher/subscribers. I hope to have that submitted as a PR by the EOD today!

**Comment by liquid-sky** [comment]
Ah, makes sense. That would explain why it was crashing then :-)

```
osquery> select count(*) from file_events;
+----------+
| count(*) |
+----------+
| 63831    |
+----------+

osquery> select time from file_events limit 1;
+------------+
| time       |
+------------+
| 1435585018 |
+------------+

$ date -d @1435585018
Mon Jun 29 13:36:58 UTC 2015

osquery> select time from file_events order by time desc limit 1;
+------------+
| time       |
+------------+
| 1435751749 |
+------------+

$ date -d @1435751749
Wed Jul  1 11:55:49 UTC 2015
```

**Comment by theopolis** [comment]
Hey @liquid-sky, I've landed a few changes to events monitoring that should greatly improve performance. If you don't mind trying an unstable build, it would be fantastic if you could give: https://jenkins.osquery.io/userContent/build/trusty/osquery-1.4.7-61-gba28b47.deb a run!

**Comment by liquid-sky** [comment]
Hi @theopolis, I've deployed it and will leave running for a while. Hopefully it'll stay up next time I check :-)

**Comment by liquid-sky** [comment]
Respawns (going zombie again) and throws `W0708 14:13:28.833719 23654 watcher.cpp:298] osqueryd worker (21041) memory limits exceeded: 67656000`. 
There're 82222 events in file_events table.

**Comment by theopolis** [comment]
Mind deleting your RocksDB store? By default the path is: /var/osquery/osquery.db

And then set the event expiration to a minute? Events are only expired after they are returned in result sets so you won't lose any events even if the expiration was a second. Add "--events_expiry=60" to the options in the config or via the CLI.

My guess is the previous set of file events is causing a massive differential after results are queried. Removing the old DB on disk will remove the differentials. Setting the expiration low will just guarantee a smaller max on disk DB.

**Comment by theopolis** [comment]
I thought about this a bit today and in #1312 there's some more attempts at reducing the instantaneous memory footprint which grows a bit out of control with a large set of `file_events` results. 

But! Looking at the watchdog limit code, I think we can solve this by relaxing the memory checking to mirror how process utilization limits are enforced. For utilization there's two input configurations: (1) a threshold for acceptable CPU utilization and (2) a maximum sustained number of seconds before the worker is considered in violation. This allows a worker to chew >70% CPU momentarily. We should do the same thing for memory: we'll count for the same number of seconds and if the private allocations continue to exceed the limit we will abort.

**Comment by liquid-sky** [comment]
@theopolis, followed your instructions and so far so good. Going to roll it out across a few more machines.

**Comment by theopolis** [comment]
Hey @liquid-sky, if everything seems solid I'll go ahead and close this issue. Feel free to reopen if you notice anything related again!
