### ISSUE TITLE
System calls on top of event framework

### ISSUE THREAD

**Issue by astanway** [facebook/osquery#128]
A table for monitoring all system calls. In its naive form, this would look like:
```
pid
syscall
```

Pragmatically, this would be a very large amount of data and we generally only care about syscalls from a select number of PIDs. Perhaps if there was a way to specify which syscalls get caught in the event framework by PID would be perfect, as opposed to chucking everything into the table and sorting it out afterwards.

**Comment by marpaia** [comment]
This is being tracked in #622.
