### ISSUE TITLE
Add date information

### ISSUE THREAD

**Issue by timzimmermann** [facebook/osquery#1297]
How about having information about the date in addition to the existing information in the time table?
I was thinking about extending the table with the columns `year`, `month`, `day` and `weekday` as well as `timestamp`.
We should also consider renaming the time table then, maybe to  `datetime` (like python).

**Comment by marpaia** [comment]
I think more columns would be cool, but renaming a table is an API change and I'd rather not embark down that road unless we really have to :)

**Comment by theopolis** [comment]
Agreed that date fields are needed. Are you thinking timestamp would be the **[ISO 8601](https://xkcd.com/1179/)** formatted string with time, such as **2015-07-02T14:47:47Z**?

It would be nice to have a **unix_time** column too.

@marpaia has a good point that **datetime** does seem more appropriate going forward but we should keep **time** for "*1.4.x*" releases, and when a "*1.5.0*" is released we'll consider making 1 easily trackable set of table API changes.

**Comment by timzimmermann** [comment]
I was actually thinking of `timestamp` as `unix_time`, but I can see how the ISO string might be helpful as well. So I can add both.

Concerning the renaming, I agree that it is better to wait for the next bigger release.
