### ISSUE TITLE
Duplicate UIDs are not preserved for users table

### ISSUE THREAD

**Issue by zi0r** [facebook/osquery#1301]
Under FreeBSD, we have two users that are uid 0:
root:*:0:0:root:/root:/bin/csh
toor:*:0:0:Bourne-again Superuser:/root:

However, you only see the 'toor' user in a 'select * from users;' query in osquery.  It looks like the addition of 'toor' overwrites the 'root' entry.

**Comment by zi0r** [comment]
osquery> select * from users;
+-------+-------+------------+------------+------------+--------------------------------+-------------------------+--------------------------------+
| uid   | gid   | uid_signed | gid_signed | username   | description                    | directory               | shell                          |
+-------+-------+------------+------------+------------+--------------------------------+-------------------------+--------------------------------+
| 0     | 0     | 0          | 0          | toor       | Bourne-again Superuser         | /root                   |                                |
| 1     | 1     | 1          | 1          | daemon     | Owner of many system processes | /root                   | /usr/sbin/nologin              |
| 2     | 5     | 2          | 5          | operator   | System &                       | /                       | /usr/sbin/nologin              |
| 3     | 7     | 3          | 7          | bin        | Binaries Commands and Source   | /                       | /usr/sbin/nologin              |


# cat /etc/passwd 
# $FreeBSD: release/10.0.0/etc/master.passwd 256366 2013-10-12 06:08:18Z rpaulo $
#
root:*:0:0:Charlie &:/root:/bin/csh
toor:*:0:0:Bourne-again Superuser:/root:

**Comment by theopolis** [comment]
Whyyyyyyy!? But yes, this is a problem that needs a fix!

**Comment by cdown** [comment]
I'm happy to take a look at this.

At first glance it looks like this used to be the default behaviour, but in 19a2d64959238 it was changed so that duplicate UIDs get dropped by checking for set membership.

@javuto, do you remember why that was necessary to implement?

**Comment by theopolis** [comment]
Hey @cdown, I'd say just remove that set/membership check. Let's use `getpwent` iteration as our source of truth.

**Comment by cdown** [comment]
I've just merged 260df0d6 into master, so this should be fixed. Feel free to ping this task if you find anything amiss. :-)
