### ISSUE TITLE
Automatic config-refresh interval setting for enrolled clients

### ISSUE THREAD

**Issue by arirubinstein** [facebook/osquery#1302]
Would it be possible to add an enrollment (or re-enrollment interval setting) so that the osquery clients can re-fetch the config from the enrollment server?  I'm looking to have my clients re-fetch the config every 30 minutes or so.

This could be implemented with a command-line argument, or as a response from the enrollment server possibly.  If "re-enrollment", or "re-check for config" is possible, perhaps the config checking interval can be returned in the response, and a `max_config_recheck_interval` command-line arg could set an upper limit to limit risk with tampering of the response from the server.  Having the server return the check interval in the response would be useful as one could use that potentially during an incident to remotely distribute rulesets quickly.

**Comment by theopolis** [comment]
Sure! The internal flag could be modifiable by the `"options": {}` dict returned in the configuration.

Proposal: `--config_refresh_interval=0` specified in seconds, a default of 0, meaning disabled.

I'd like to hear ideas around a sensible default. For most services where a file is the source of config, truth, a reload occurs via service restart/reload or SIGHUP. We'd follow suite with a "manual" reload or "manual" choice to poll for changes.

**Comment by arirubinstein** [comment]
For a remote deployment, I think a ~4 hour or so config refresh interval by default would be useful, then we could dial that down to 15 minutes or so on-demand with additional changes in the config.  As long as the cli arg is the upper bound, and the options dict in the config can override that to a lesser number (other than off), that would work well for us.

I think it's sane to not have this enabled by default though, since it goes against the SIGHUP model with the config on disk is totally repurposing the product a bit

**Comment by theopolis** [comment]
What are your concerns around the CLI-defined interval value being the upper bound?

Also, the `--config_plugin=tls` could implicitly set `--config_refresh_interval=4*60*60` if there was no explicit value set via a CLI flag. Effectively making 0 the default for everything, except tls, which will use 4Hr.

**Comment by arirubinstein** [comment]
In a disaster scenario, if the enrollment server were to be compromised, an attacker could theoretically "remotely disable" the new configs via an indefinite timeout / send out an empty config removing any reporting ability from the clients.  You would theoretically need to use another tool to kick all of the osquery installs to get them to report again.  Being able to set an upper bound would hopefully limit the scope of a compromised enrollment server.

The implicit timeout of 4 hours makes sense for tls.  It emulates functionality in other products re: interactive IR.  Given the reporting frequency, asking for the config every 4 hours shouldnt add too much burden

**Comment by theopolis** [comment]
Here's the simple implementation: #1352. I choose not to implement a max time = the initial time because the threat of a compromised enrollment/config server has much dire effects than neutering clients though an invalid refresh interval. Conversely, you can get benefit by updating to a more relaxed refresh, meaning longer interval. Let me know if this works. It would be simple to add the initial time as the max if you feel strongly about that feature. :)

**Comment by marpaia** [comment]
looks good to me! nice work

**Comment by arirubinstein** [comment]
Excellent, thanks!  This is great - I'll throw this in our testing environment :D
