### ISSUE TITLE
`processes` table pid constraint leads to non existent rows

### ISSUE THREAD

**Issue by mofarrell** [facebook/osquery#1303]
Querying the processes table with a query that generates a pid constraint gives interesting results for pid's of processes that are not running.  In the case of a process that isn't running we would expect no row to be generated.  Instead we see:

```
osquery> SELECT * FROM processes WHERE pid=123;
I0706 09:27:46.494313 1961374464 processes.cpp:175] An error occurred retrieving the env for pid: 123
           pid = 123
          name =
          path =
       cmdline =
           cwd =
          root =
           uid = -1
           gid = -1
          euid = -1
          egid = -1
       on_disk = -1
    wired_size = -1
 resident_size = -1
phys_footprint = -1
     user_time = -1
   system_time = -1
    start_time = -1
        parent = -1
```

This is the same for OS X and linux despite the separate implementations.  Thoughts?  This doesn't seem like a big deal.

**Comment by theopolis** [comment]
Right, the implementation as it exists today may lead to confusion. The implementations should NOT emit a row if the pid does not exist.

**Comment by wxsBSD** [comment]
When I'm back to normalcy in a week or so I can check this out on FreeBSD. I don't recall if it will exhibit the same bad behavior or not.

**Comment by mofarrell** [comment]
Thought I would tag on here that this is also true in the users and groups tables.  Seems like a rather systemic issue.
