### ISSUE TITLE
signed pkg

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#1316]
No osquery pkg I can find publicly available has a signature... e.g. `pkgutil --check-signature`

**Comment by mofarrell** [comment]
We should be getting to this as we work on signing the OS X kernel extension as well.  @theopolis

**Comment by theopolis** [comment]
We should be good to go now. Expect new packages, binaries, and bundles to be signed and distributed on S3. The intermediate/debug builds hosted by Jenkins will NOT be signed. 

We will test the entire signing/publishing workflow when the next tag is created.

**Comment by theopolis** [comment]
As of 1.5.0 packages distributed via S3 will be signed.

**Comment by marpaia** [comment]
```
$ pkgutil --check-signature osquery-1.5.0.pkg
Package "osquery-1.5.0.pkg":
   Status: signed by a certificate trusted by Mac OS X
   Certificate Chain:
    1. Developer ID Installer: Theodore Reed (B89LNTUADM)
       SHA1 fingerprint: 77 19 1E 49 10 ED 81 EC C1 80 52 D6 7E EB 3C 2E EF D6 72 7E
       -----------------------------------------------------------------------------
    2. Developer ID Certification Authority
       SHA1 fingerprint: 3B 16 6C 3B 7D C4 B7 51 C9 FE 2A FA B9 13 56 41 E3 88 E1 86
       -----------------------------------------------------------------------------
    3. Apple Root CA
       SHA1 fingerprint: 61 1E 5B 66 2C 59 3A 08 FF 58 D1 4A E2 24 52 D1 98 DF 6C 60

```

:dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer: :dancer:

**Comment by arubdesu** [comment]
🎺WOOOOOOOOOOOOOOOOOOT🎷 (olé!)
