### ISSUE TITLE
OS X EFI ROM metadata table

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#1317]
a.k.a. bootROM, I see stuff in the nvram table... but none of the values look like `Boot ROM Version:	MBA61.0099.B19`, as I'd get from `system_profiler SPHardwareDataType | awk '/ROM/{print $4}'`

**Comment by sharvilshah** [comment]
As far as I can tell, nvram table only looks for `options` object  (which is inherited from `AppleEFINVRAM`) under `IODeviceTree` plane.

Looking at IO Registry, `options` has following keys (values truncated):

```
❯ ioreg -d 3 -p IODeviceTree -n options
+-o Root  <class IORegistryEntry, ...>
    +-o options  <class AppleEFINVRAM, ...>
        {
          "efi-apple-payload2-data"
          "efi-apple-payload0-data"
          "gpu-policy"
          "fmm-mobileme-token-FMM"
          "efi-boot-device"
          "efi-apple-payload3"
          "prev-lang:kbd"
          "efi-apple-payload3-data"
          "SystemAudioVolumeDB"
          "BootCampProcessorPstates"
          "efi-apple-payload1-data"
          "efi-apple-recovery"
          "efi-apple-payload2"
          "fmm-computer-name"
          "backlight-level"
          "efi-apple-payload1"
          "SmcFlasherResult"
          "Test_ALS_Data"
          "bluetoothActiveControllerInfo"
          "efi-apple-payload0"
          "SystemAudioVolume"
          "efi-boot-device-data"
          "ALS_Data"
          "boot-gamma"
          "bluetoothInternalControllerInfo"
        }
```

The Boot ROM information is present in `rom` object (which is not derived from `AppleEFINVRAM`):

```
❯ ioreg -d 3 -p IODeviceTree -n rom
+-o Root  <class IORegistryEntry, ...>
  +-o /  <class IOPlatformExpertDevice, ...>
    +-o rom@0  <class IOService, ...>
    |   {
    |     "vendor",
    |     "fv-main-size",
    |     "release-date",
    |     "rom-size",
    |     "fv-main-address",
    |     "apple-rom-info",
    |     "version",
    |   }
```

It looks trivial (I think) to parse and add data from `rom`, but `nvram` might not be the right table for it.

**Comment by theopolis** [comment]
Right! The NVRAM data is a region within the SPI flash chip that is parsed / brokered by an Apple kernel extension and reported via IOKit at the /options device tree path.

The EFI platform information in "ROM" *might* be useful. I've been debating how to report info on the ROM and on the EFI bootloader(s) present on the partition and recovery partition. As well as searching for known bootloader paths for "additional" files, and parsing NVRAM variables incase those search paths are overridden.

The EFI platform data that is occasionally updated and written to SPI is much different than the bootloaders and much harder to read/hash. So maybe we could present these as two new tables? One "bootloaders" that reports info on the various files and another "efi_platform" that reported ROM metadata from IOKit on OS X. Later, if we can ever support reading SPI, we could add a hash to that table!

**Comment by arubdesu** [comment]
(Pardon the bump, but if someone would be kind enough to update the label to reflect this is a table request or something...😅)

**Comment by marpaia** [comment]
Are we in agreement that we should create a `bootloaders table and an `efi_platform` table? If so, we should close this and add it to #619

**Comment by theopolis** [comment]
Right, I captured this in the table requests. Seems easy enough to report the ROM information from IOKit. Discovering the list of bootloaders from the recovery/boot/actual disk as well as parsing paths from the GUID partition table metadata might be a little more involved. Like @marpaia mentioned, it's best to capture both the ROM platform metadata separately from the bootloader list since your system may (most likely does) include several potential bootloaders, but only one ROM platform.
