### ISSUE TITLE
Minor errors in the documentation

### ISSUE THREAD

**Issue by achmiel** [facebook/osquery#1322]
I noticed multiple minor errors in the documentation, for example:

* Incorrectly placed section headers ([cli-flags.md](https://github.com/facebook/osquery/blob/master/docs/wiki/installation/cli-flags.md))
* Misspelled words (for example, "explainations" instead of "explanations")
* Stylistic and grammatical errors (for example, using incorrect homonyms (you're/your, it's/its))
* Use of incorrect articles (a/an/the)
* Use of "etc" instead of "etc."
* Missing capitalizations (linux/Linux, darwin/Darwin, homebrew/Homebrew)
* Missing commas

**Comment by theopolis** [comment]
:sob:
