### ISSUE TITLE
Test brew-provided OpenSSL for OS X deployments

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1329]
We are using OpenSSL's x509/ASN.1 parsing for Keychain certificates since: #1321, to resolve the memory leak and speed issues from SecurityFoundation's API outlined in: #1032.

They system-provided OpenSSL is _rather old_ and should not be used in this capacity. If possible we should build in brew's OpenSSL. It's not the best plan but it's at least **much better** than the alternative. In 10.11 we may be able to again statically link with a system-provided crypto library.

OpenSSL vulnerabilities in the brew-provided distribution will warrant immediate releases with the announcements/fixes published in the change log.

**Comment by theopolis** [comment]
See #1331 for an example discovery of the latest OpenSSL provided by brew.

**Comment by sharvilshah** [comment]
Some updates:

In the latest beta of 10.11 El Capitan, there are no OpenSSL headers included from Apple. [Here's their official stance](https://lists.apple.com/archives/macnetworkprog/2015/Jun/msg00025.html): 

>With the latest OS X SDK we've removed the headers entirely, making it much harder to use the long-since-deprecated shared libraries.

> We recommend that developers who need OpenSSL build their own copy of it and include that copy in their app.  Alternatively you can use native OS X APIs, like Secure Transport.

I have finally made some progress, linking brew provided OpenSSL with osquery and cpp-netlib and I think I have almost all the niggles ironed out. 

However Apple also seems to have removed deprecated functions from Security framework and we make use `SecKeychainSearchCreateFromAttributes` (among others I think) in `keychain_acls`. Any particular reason to not use the newer equivalent ones (`SecItemCopyMatching`)? Maybe @marpaia knows the answer. If not I can update it to use newer ones (could also use a breather from the kernel-land).

**Comment by sharvilshah** [comment]
Okay, `SecKeychainSearchCreateFromAttributes` is still there in 10.11, the parameters changed a bit.

And success! Both building on 10.11 and linking with brew provided OpenSSL:

```
Mac:osquery vagrant$ sysctl kern.osrelease
kern.osrelease: 15.0.0

Mac:osquery vagrant$ sysctl kern.version
kern.version: Darwin Kernel Version 15.0.0: Tue Jul 21 21:47:25 PDT 2015; root:xnu-3247.1.68~32/RELEASE_X86_64

Mac:osquery vagrant$ uname -a
Darwin Mac.local 15.0.0 Darwin Kernel Version 15.0.0: Tue Jul 21 21:47:25 PDT 2015; root:xnu-3247.1.68~32/RELEASE_X86_64 x86_64

Mac:osquery vagrant$ which openssl
/usr/local/bin/openssl

Mac:osquery vagrant$ pkg-config --modversion openssl
1.0.2d

Mac:osquery vagrant$ ./build/darwin/osquery/osqueryi
osquery> select * from kernel_info;
+---------+-------------+-------------------------------------------------+--------------------------------------+-----+
| version | arguments   | path                                            | device                               | md5 |
+---------+-------------+-------------------------------------------------+--------------------------------------+-----+
| 15.0.0  | rootless=0  | System\Library\PrelinkedKernels\prelinkedkernel | 2A2B95F6-E11B-4D5E-8DB5-E6BE5D9877F5 |     |
+---------+-------------+-------------------------------------------------+--------------------------------------+-----+

osquery> select * from keychain_acls;
+------------------------------------+-----------------------------------------------------+-----------------------------------------------------------------+-------------+-------+
| keychain_path                      | authorizations                                      | path                                                            | description | label |
+------------------------------------+-----------------------------------------------------+-----------------------------------------------------------------+-------------+-------+
| /Library/Keychains/System.keychain | decrypt derive export_clear export_wrapped mac sign | /System/Library/PrivateFrameworks/Heimdal.framework/Helpers/kdc | lkdc-acl    |       |
+------------------------------------+-----------------------------------------------------+-----------------------------------------------------------------+-------------+-------+

osquery> select count(*) from keychain_items;
+----------+
| count(*) |
+----------+
| 424      |
+----------+

osquery> select count(*) from certificates;
+----------+
| count(*) |
+----------+
| 399      |
+----------+
```

There were a bunch of linker warnings about libs being built for 10.10. Will try to see if those can be muted/made less verbose.

And need to piece together my shell history and integrate them into our build scripts and test it out preferably on a clean 10.11 image.
