### ISSUE TITLE
The "read_user_links" CLI flag is broken

### ISSUE THREAD

**Issue by achmiel** [facebook/osquery#1332]
I noticed that the `--read_user_links=false` flag is not working as intended. With the flag set to `false`, both `osqueryi` and `osqueryd` treat all files as they were links. This breaks multiple tables (including `shell_history`, `crontab` and others).

Please take a closer look at the following commands:
```sh
$ whoami; osqueryi --version # running the latest version as non-root
artur
osqueryi version 1.4.7-104-g276891a

$ ls -al .zhistory # .zhistory is a regular file
-rw-r--r--  1 artur  staff  3 14 lip 19:08 .zhistory

$ osqueryi --read_user_links=true "select * from shell_history" # works fine
+----------+---------+------------------------+
| username | command | history_file           |
+----------+---------+------------------------+
| artur    | ls      | /Users/artur/.zhistory |
+----------+---------+------------------------+

$ osqueryi --read_user_links=false "select * from shell_history" # no output!
```
### The root cause
The bug is located in the following code ([filesystem.cpp](https://github.com/facebook/osquery/blob/master/osquery/filesystem/filesystem.cpp)):

```cpp
Status readFile(const fs::path& path, std::string& content) {
  struct stat file;
  if (lstat(path.string().c_str(), &file) == 0) {
    if (file.st_uid != 0 && !FLAGS_read_user_links) {
      return Status(1, "User link reads disabled");
    }
  } else if (stat(path.string().c_str(), &file) < 0) {
    return Status(1, "Cannot access path: " + path.string());
  }
...
```
According to the [documentation](http://pubs.opengroup.org/onlinepubs/9699919799/functions/lstat.html), the `lstat` function:
> (...) shall be equivalent to stat(), except when path refers to a symbolic link. In that case lstat() shall return information about the link, while stat() shall return information about the file the link references.

This means that the `lstat` function will also work with regular files and that it cannot be used to determine if a file is a symbolic link.

Interestingly, the `file.st_uid != 0` part makes this issue much harder to spot when running osquery as `root`.

**Comment by marpaia** [comment]
This is the best bug report ever. Thank you, @achmiel.
