### ISSUE TITLE
#1326 Produces a non release kernel build package.

### ISSUE THREAD

**Issue by mofarrell** [facebook/osquery#1339]
Because #1326 only tries to build a kernel package if the user has previously built the kernel, it no longer rebuilds it with release flags before packaging it.  This leads to versioning mismatches between the the kernel extension and the daemon, as one is built for release and one is built for debug.

**Comment by mofarrell** [comment]
We could fix this by always building the kernel when packaging, it seemed like you were against that earlier @theopolis.

**Comment by theopolis** [comment]
I haven't had a chance to dig into this yet, but do you mind elaborating on the expected outcome and the differences between the actual results? I'm guess the inconsistencies happen on a merge into master, right?

**Comment by mofarrell** [comment]
When the kernel extension is built as non release (ie. `kernel-build` make target), the `KERNEL_TEST` macro is defined.  Prior to #1326 the kernel was rebuilt during packaging but as a release version meaning the `KERNEL_TEST` macro was not defined.

Now, we end up with a userland daemon that was built without the `KERNEL_TEST` macro and a kernel extension built with it.  Because the kernel extension was built for testing and the daemon was not, the versioning check does not allow the daemon to connect to the kernel extension (this is good because a test build changes the communication system).

One solution would be to add the `kernel-build` target back as a dependency of the `packages` target.  In this case we would also always produce a kernel extension package.

**Comment by theopolis** [comment]
Perfect, great explanation @mofarrell! How do you feel about a `kernel-release` target?

I hesitate to have the `kernel-build` dependency in `packages` because developers may not have kernel SDKs/etc installed. They may also become confused as to why they are compiling kernel code implicitly when attempting to repackage their userland modifications.

**Comment by theopolis** [comment]
Then `kernel-release` would set the release macro/variable in CMake and essentially rerun the `kernel-build` dependency.

**Comment by mofarrell** [comment]
That sounds good, but it would be best then if the `packages` target only packaged the kernel if it was last built as a release version.

**Comment by marpaia** [comment]
Could you add a CMake dependency to make packages which is a script that checks to see if the kernel build is release and return !0 if so, thus causing the build to fail. We definitely want the build to fail if you're not about to package a release build, for sure.
