### ISSUE TITLE
Homebrew install of 1.4.7 doesn't include osqueryctl

### ISSUE THREAD

**Issue by sroberts** [facebook/osquery#1341]
It appears in the current (1.4.7) install of osquery from Homebrew. 

<img width="741" alt="screen_shot_2015-07-15_at_8_54_37_am" src="https://cloud.githubusercontent.com/assets/44774/8704658/305334da-2ad9-11e5-8cf7-48a13e78490f.png">

This was installed today (July 15) with ```brew install osquery```.

**Comment by theopolis** [comment]
Thanks for the heads up @sroberts, I'm taking a look right now! If I had to make a guess, I'd say the script is not included in the `make install` target within CMake; and the `osqueryctl` script is only bundled into the package payload layout with `make packages`. Whatever the problem, we'll make sure it's included in Homebrew going forward.

**Comment by marpaia** [comment]
Thank you for being a loyal, GitHub Issue submitting citizen, @sroberts :)

**Comment by sroberts** [comment]
@marpaia & @theopolis Thank you both for being awesome project owners!!
