### ISSUE TITLE
Process environment parsing on Linux

### ISSUE THREAD

**Issue by mcarpenter** [facebook/osquery#1356]
Hi,

Looking at the process environment on Linux:

osquery/tables/system/linux/processes.cpp:

    59 void genProcessEnvironment(const std::string& pid, QueryData& results) {
    60   auto attr = getProcAttr("environ", pid);
    61 
    62   std::string content;
    63   readFile(attr, content);
    64   for (const auto& buf : osquery::split(content, "\n")) {
    65     size_t idx = buf.find_first_of("=");

But `environ(5)` is zero-byte (not newline) delimited (line 64). (If `environ` really was newline delimited (was it ever?) naughty processes could deceive osquery...). Consequently, as it stands, osquery's output gets truncated at the end of the first variable.

    vagrant@vagrant-ubuntu-trusty-64:/vagrant$ uname -a 
    Linux vagrant-ubuntu-trusty-64 3.13.0-53-generic #89-Ubuntu SMP Wed May 20 10:34:39 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
    vagrant@vagrant-ubuntu-trusty-64:/vagrant$ git log -1 --oneline
    6bfe03f Merge pull request #1354 from theopolis/more_install
    vagrant@vagrant-ubuntu-trusty-64:/vagrant$ osqueryi --line "select key from process_envs where pid = $$"
      key = LANG
    vagrant@vagrant-ubuntu-trusty-64:/vagrant$ strings /proc/$$/environ | wc -l
    14
    vagrant@vagrant-ubuntu-trusty-64:/vagrant$ strings /proc/$$/environ
    LANG=en_US.UTF-8
    USER=vagrant
    LOGNAME=vagrant
    HOME=/home/vagrant
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
    MAIL=/var/mail/vagrant
    SHELL=/bin/bash
    SSH_CLIENT=10.0.2.2 60872 22
    SSH_CONNECTION=10.0.2.2 60872 10.0.2.15 22
    SSH_TTY=/dev/pts/0
    TERM=xterm
    DISPLAY=localhost:10.0
    XDG_SESSION_ID=2
    XDG_RUNTIME_DIR=/run/user/1000
    vagrant@vagrant-ubuntu-trusty-64:/vagrant$ 

(FreeBSD and Darwin do not use the same mechanism so are not affected).

**Comment by theopolis** [comment]
Great find! @mcarpenter, do you mind submitting a pull request to switch this back to `\0` delimiting?

**Comment by mcarpenter** [comment]
Sure, I can take a look at that evening of but (not before end of day Monday).

**Comment by mcarpenter** [comment]
You beat me to it! Thanks :)

**Comment by theopolis** [comment]
Sorry to steal your thunder! Wanted to get it in before 1.5.0. ;)
