### ISSUE TITLE
OS X: applications table misses many installed applications

### ISSUE THREAD

**Issue by gregneagle** [facebook/osquery#1357]
The current code to search for applications on OS X is quite naive.  Here's the output of a query on my machine:

```
osquery> select path from apps;
+-----------------------------------------------------+
| path                                                |
+-----------------------------------------------------+
| /Applications/Adium.app                             |
| /Applications/App Store.app                         |
| /Applications/Apple Configurator.app                |
| /Applications/Automator.app                         |
| /Applications/boot2docker.app                       |
| /Applications/Calculator.app                        |
| /Applications/Calendar.app                          |
| /Applications/Chess.app                             |
| /Applications/Contacts.app                          |
| /Applications/CrashPlan.app                         |
| /Applications/Dashboard.app                         |
| /Applications/Dictionary.app                        |
| /Applications/DVD Player.app                        |
| /Applications/Evernote.app                          |
| /Applications/FaceTime.app                          |
| /Applications/Firefox.app                           |
| /Applications/Font Book.app                         |
| /Applications/Game Center.app                       |
| /Applications/Google Chrome.app                     |
| /Applications/GPG Keychain.app                      |
| /Applications/iBooks.app                            |
| /Applications/Image Capture.app                     |
| /Applications/iMovie.app                            |
| /Applications/iPhoto.app                            |
| /Applications/iTunes.app                            |
| /Applications/Keynote.app                           |
| /Applications/Launchpad.app                         |
| /Applications/Mail.app                              |
| /Applications/Managed Software Center.app           |
| /Applications/Maps.app                              |
| /Applications/Messages.app                          |
| /Applications/Microsoft Communicator.app            |
| /Applications/Microsoft Messenger.app               |
| /Applications/Mission Control.app                   |
| /Applications/Notes.app                             |
| /Applications/Packages.app                          |
| /Applications/Photo Booth.app                       |
| /Applications/Photos.app                            |
| /Applications/Preview.app                           |
| /Applications/QuickTime Player.app                  |
| /Applications/QuickTimmy.app                        |
| /Applications/Reminders.app                         |
| /Applications/Remote Desktop Connection.app         |
| /Applications/Safari.app                            |
| /Applications/SecurID.app                           |
| /Applications/Skype.app                             |
| /Applications/Stickies.app                          |
| /Applications/System Preferences.app                |
| /Applications/TextEdit.app                          |
| /Applications/TextMate.app                          |
| /Applications/Textual 5.app                         |
| /Applications/Textual.app                           |
| /Applications/TextWrangler.app                      |
| /Applications/Thunderbird.app                       |
| /Applications/Time Machine.app                      |
| /Applications/VirtualBox.app                        |
| /Applications/VLC.app                               |
| /Applications/VMware Fusion.app                     |
| /Applications/Wireshark.app                         |
| /Applications/Workgroup Manager.app                 |
| /Applications/Xcode.app                             |
+-----------------------------------------------------+
```

Notice it returns only the applications found at the root level of the /Applications directory. It misses all the applications in /Applications/Utilities, but more importantly, it misses things like:

```
/Applications/Adobe Bridge CS6/Adobe Bridge CS6.app
/Applications/Adobe Photoshop CS6/Adobe Photoshop CS6.app
/Applications/Adobe Extension Manager CS6/Adobe Extension Manager CS6.app
```

and

```
/Applications/iWork '09/Keynote.app
/Applications/iWork '09/Numbers.app
/Applications/iWork '09/Pages.app
```

(These are all installed in their default locations.)

Results could be improved by simply doing a recursive directory walk, though you might choose to not descend into directories with names ending in ".app" so as not to clutter the results with helper apps contained inside other application bundles.

But even this approach would miss applications installed in other locations like /Users/Shared/. (I myself have more than one "interesting" application in that location) Looking at the code it looks like you are searching home directories, but you are only looking in the Applications, Desktop and Downloads directories. There is no guarantee users will copy applications only to those directories.

I'd suggest you consider using LaunchServices' _LSCopyAllApplicationURLs function to return all applications known to LaunchServices (and then filter as required) or use Spotlight (via NSMetadataQuery) to query for all items with kMDItemKind = "Application" (or do both and merge the lists, all depending on how exhaustive you want the application detection to be).

I can provide Python examples of both techniques that you could translate into C++/Objective-C, or you could just take a look at Munki's code here: https://github.com/munki/munki/blob/master/code/client/munkilib/munkicommon.py#L2168-L2220

I understand there may be performance-related reasons you've decided not to search exhaustively for installed apps, but missing a licensed commercial application like Photoshop CS6 in its default install location is probably indication that your current search strategy could use some tweaking.

**Comment by theopolis** [comment]
Awesome suggestions, thanks for the help @gregneagle!

**Comment by marpaia** [comment]
`NSMetadataQuery` seems like the way to go, good idea @gregneagle

**Comment by theopolis** [comment]
The only caveat is around the low fidelity of Spotlight. The database could be out of date, or have never been generated, when Spotlight is disabled. An amalgamation of the three methods would be ideal! I wonder if there are ways to disable the LS/CoreServices application cache? Hmmm
