### ISSUE TITLE
osqueryd safe permissions check

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1382]
The osquery daemon enforces several permissions checks:

1. The osquery daemon binary itself must.
2. Any autoloaded extension binaries.
3. Any autoloaded module shared libraries.

The permission checks include:

1. The path and leaf parent directory must be real.
2. The parent must not have sticky permissions.
3. The path must not be a directory.
4*. The path must be owned by root or the executor must match the path owner.

[*] There is an optional requirement that the path is executable.

With a homebrew install, the osqueryd binary is installed/owned by a user. If this binary is executed as root the permissions checks will fail. It is best to install osquery using the publicly provided [packages](https://osquery.io/downloads/).

There is a "workaround" that disables these checks. You can add `--allow-unsafe` to your flags or the command line arguments.

**Comment by msierchio** [comment]
Even publicly provided packages seem to present the same difficulty if Homebrew is installed – under certain conditions – it generally requires either sticky permissions or user ownership of ../bin – which cause the permissions check failure.
