### ISSUE TITLE
False positive for HackingTeam_Mac_RAT2 query pack?

### ISSUE THREAD

**Issue by lifeisfoo** [facebook/osquery#1385]
`osquery> select * from apps where bundle_identifier = 'com.ht.RCSMac' or bundle_identifier like 'com.yourcompany.%' or bundle_package_type like 'OSAX';`

| name           | path                                       | bundle_executable | bundle_identifier          | bundle_name | bundle_short_version | bundle_version | bundle_package_type | environment | element | compiler | development_region | display_name | info_string         | minimum_system_version | category | applescript_enabled | copyright |
|----------------|--------------------------------------------|-------------------|----------------------------|-------------|----------------------|----------------|---------------------|-------------|---------|----------|--------------------|--------------|---------------------|------------------------|----------|---------------------|-----------|
| unetbootin.app | /Users/alessandro/Downloads/unetbootin.app | unetbootin        | com.yourcompany.unetbootin |             |                      |                | APPL                |             |         |          |                    |              | Created by Qt/QMake |                        |          |                     |           |

[Unetbootin](http://unetbootin.sourceforge.net/) is a tool for creating bootable usb drives
Query pack doc: https://osquery.io/docs/packs/#osx-attacks_HackingTeam_Mac_RAT2

**Comment by theopolis** [comment]
Yeah, that's a known false positive.

I'll update the pack and remove the `bundle_identifier` match as it matches a few other applications, which did not update their project name/domain in Xcode.
