### ISSUE TITLE
document how to run osqueryd

### ISSUE THREAD

**Issue by runasand** [facebook/osquery#1395]
If I start osqueryd with *osqueryd --daemonize*, *ps aux | grep osqueryd* will list it as a running process. If I then run *osqueryctl status*, I get a response saying *osqueryd is not running. no pidfile found.* Note that I opted not to write the pid of the process to a pidfile/mutex.

**Comment by marpaia** [comment]
On OS X, osqueryctl looks to see if osqueryd is scheduled via launchd, by doing `sudo launchctl list | grep com.facebook.osqueryd`: https://github.com/facebook/osquery/blob/master/tools/deployment/osqueryctl#L98-L102

On linux, osqueryctl basically executes a `service osqueryd status`, which looks for the pidfile: https://github.com/facebook/osquery/blob/master/tools/deployment/osqueryd.initd#L102-L118

**Comment by marpaia** [comment]
I'm uncertain if we can have `osqueryctl` return reasonable information if you have opted to not create a pidfile. The pidfile, as it stands now, is the way that we represent an "instance" of osqueryd. There can be many instances of osqueryd running on a system and you can use native management options to allow a user to manage that instance (ie: --force on osqueryd), but they all need to have unique pidfiles.

**Comment by marpaia** [comment]
Are you launching osqueryd with `--pidfile=/dev/null` or something? If so, is there a particular reason why you don't want a pidfile? If your motivation is so that osqueryd doesn't write anything to disk, then that may be an effort in futility, as there is currently no way to manage rocksdb in memory given the current option set, although we've been talking about this, as we often run osqueryd on RO filesystems, so this would be a useful feature.

**Comment by runasand** [comment]
I launched osqueryd by running *osqueryd --daemonize* because I didn't realize there was a better way to do it (i.e. by using osqueryi and editing the config file to create a pidfile).

**Comment by marpaia** [comment]
@runasand do your questions pertain to OS X or Linux?

**Comment by runasand** [comment]
I'm running Ubuntu Trusty.

**Comment by marpaia** [comment]
If you've installed the deb, then you should have an init script (the source for which is https://github.com/facebook/osquery/blob/master/tools/deployment/osqueryd.initd), which you can `service osqueryd start`. An example Chef configuration for this is on the wiki: http://osquery.readthedocs.org/en/stable/deployment/configuration/#chef-linux

**Comment by marpaia** [comment]
After talking offline with @runasand we cam to the conclusion that the documentation about how to actually run osqueryd is kind of lacking. We have detailed config management docs, which are usually sufficient, but for a more casual user, we should outline some more detailed instructions.

**Comment by marpaia** [comment]
@runasand has volunteered to contribute some instructions to the docs based on her experiences, so looking forward to that.

**Comment by theopolis** [comment]
I captured a short blob in #1436, if anyone thinks that needs work or elaboration let me know ASAP! We could also think about a "getting started" guide on the https://osquery.io homepage or a short video tutorial.
