### ISSUE TITLE
Error executing query to retrieve list of currently logged in users

### ISSUE THREAD

**Issue by runasand** [facebook/osquery#1398]
The incident response pack contains the following query:

```
"logged_in_users": {
  "query" : "select liu.*, p.name, p.cmdline, p.cwd, p.root from logged_in_users liu, p where liu.pid = p.pid;",
  "interval" : "3600",
  "version" : "1.4.5",
  "description" : "Retrieves the list of all the currently logged in users in the target system.",
  "value" : "Useful for intrusion detection and incident response. Verify assumptions of what accounts should be accessing what systems and identify machines accessed during a compromise."
},
``` 

My Ubuntu Trusty system has been running osquery for ~12 hours and */var/log/osquery/osqueryd.ERROR* contains lines with the following error message:

```
E0727 10:18:25.022022  1710 scheduler.cpp:87] Error executing query (select liu.*, p.name, p.cmdline, p.cwd, p.root from logged_in_users liu, p where liu.pid = p.pid;): Error running query: no such table: p
```

**Comment by marpaia** [comment]
woops, that query should be `select liu.*, p.name, p.cmdline, p.cwd, p.root from logged_in_users liu, processes p where liu.pid = p.pid;`

**Comment by theopolis** [comment]
Totally my fault. :crying_cat_face:

**Comment by theopolis** [comment]
To prevent these typos going forward we should include executing all the pack queries alongside the [final integration python test](https://github.com/facebook/osquery/blob/master/tools/tests/test_example_queries.py#L77). Any failing query should cause `make test` to fail. I'm not sure if failing syntax does that now within `test_example_queries`, only implementation exceptions/missing virtual tables. So I'm up for suggestions on adding pack parsing/executing within the existing test or adding a new test called `test_query_packs` that executes each, checking for exceptions and syntax.

**Comment by theopolis** [comment]
I'm adding a new concept of release tests. These will be a bit "intense" and thus are gated from normal unit tests. Part of the new test suite will involve running all of the packs as well as benchmarking. Any syntax errors will cause the tests to fail and prevent package/binary release.

**Comment by theopolis** [comment]
With: https://github.com/facebook/osquery/pull/1401 we now have integration tests for query pack syntax!
