### ISSUE TITLE
Error parsing osquery_packs

### ISSUE THREAD

**Issue by PickmanSec** [facebook/osquery#1416]
After trying a fresh install of the latest version(.pkg) I ran into an issue involving osquery_packs not returning logs. I found this in the /var/log/osquery/osqueryd.INFO logs.

query_packs.cpp:139] Error parsing Query Pack incident-response: Could not read JSON from file
query_packs.cpp:139] Error parsing Query Pack it-compliance: Could not read JSON from file
query_packs.cpp:139] Error parsing Query Pack osx-attacks: Could not read JSON from file
query_packs.cpp:139] Error parsing Query Pack vuln-management: Could not read JSON from file

**Comment by PickmanSec** [comment]
This is OSX 10.10

**Comment by theopolis** [comment]
Hey @PickmanSec! Thanks for the note, we're tracking this in #1402. Essentially, the packs are not in the right/expected location set within the example config. We're trying to figure out if we should make them available by default (given a default install). Any ideas, guidance would be awesome!

Would one expect all the packs to be turned on by default?

**Comment by PickmanSec** [comment]
That bug was used for homebrew installed osquery. This was installed using the package download option.  I would expect any pack's *.confs in the config file to be enabled as log as they are not commented out. The big problem I have had is finding these logs in splunk which led me down this path of testing out the most updated version of osquery. Another thing that would be nice and something I will probably be looking into is the wether or not adding a "name" field in the packs adds the name field to the logs.

**Comment by theopolis** [comment]
Right, in the later parts of #1402, it turned out all paths are wrong on OS X regardless of how you do an external install. (The only way to get correct paths was via a `make install`.) 

I really like your, comment it in the example if it's not intended to load on default, recommendation.

**Comment by PickmanSec** [comment]
Alright, well I will join that task then. 
Thanks for the help I will look into #1402.
