### ISSUE TITLE
Using homebrew to build osquery on OS X 10.11

### ISSUE THREAD

**Issue by ghost** [facebook/osquery#1423]
We're having a few problems using homebrew to build osquery on systems running recent beta versions of OS X 10.11.

https://github.com/Homebrew/homebrew/issues/41862

**Comment by sharvilshah** [comment]
Yeah, osquery doesn't currently build on 10.11. 
I have been making some progress on that front.

**Comment by marpaia** [comment]
Is this fixed with https://github.com/Homebrew/homebrew/commit/0a203587a1bfe6251aba32f098559b7f0c0a00cf ?

**Comment by marpaia** [comment]
@sharvilshah ask and you shall receive :)

**Comment by sharvilshah** [comment]
@marpaia https://github.com/Homebrew/homebrew/commit/0a203587a1bfe6251aba32f098559b7f0c0a00cf is to detect thrift if homebrew is installed in a non-default location. 

I did successfully build osquery on 10.11 and updates are [here](https://github.com/facebook/osquery/issues/1329#issuecomment-127478210). Still need to clean it up before it's PR worthy.

**Comment by marpaia** [comment]
@sharvilshah nice! you're awesome.
