### ISSUE TITLE
osquery Truck Factor

### ISSUE THREAD

**Issue by gavelino** [facebook/osquery#1427]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **osquery** and obtained a value of **2**.

The developers responsible for this TF are:

Teddy Reed - author of 68% of the files
Mike Arpaia - author of 45% of the files

To validate our results, we would like to ask **osquery** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **osquery**?

(b) Do you agree that **osquery** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **osquery** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by marpaia** [comment]
Wow, pretty good. Yeah @theopolis and I constitute the osquery engineering team, with the help of @javuto who is our chief bit wrangler and @mofarrell who is our intern, although he's leaving the project tomorrow :cry:

For B, I think that if @theopolis and I both left completely, we'd be in trouble, but either one of us has a strong enough understanding of osquery that we could continue to carry the torch.

For C, yes, osquery has pretty good user docs and the whole codebase has doxygen comment blocks where appropriate. We use clang-format, etc. so the code is pretty easy to understand, if you're into C++, which much of Facebook is. We also have extensive internal documentation for how we manage our specific osquery deployment, which I think is a bigger concern, so all of the bits of that should be covered as well.

**Comment by marpaia** [comment]
I'm going to close this, but feel free to post any follow-ups and we'll do our best to answer quickly.

**Comment by gavelino** [comment]
Hi @marpaia,

thank you for your answer.
