### ISSUE TITLE
OS X/Darwin version-specific packaging coming soon

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1446]
We are now supporting a build for 10.10 and 10.9 as two different Jenkins builds, resulting in two different packages. These use the namespaces: `darwin` for 10.10 (the most current OS X version) and `darwin10.9` for Mavericks. I realize "darwin" is versioned differently than OS X, but it's an artifact of using the platform name then retroactively applying a distribution name too. 

Moving forward we will have a 10.10 and 10.11 that both use the `darwin` namespace purely because of an artificial circumstance of working around API differences. It is not possible to do the same acrobatics between 10.9 and 10.10 changes. Rather unfortunate.

This impacts deploys A LOT! At Facebook, with Chef, we can detect the platform/system version and choose a location to pull the package from. This works fine and allows us to deploy the different packages with the same name/version based on the OS version. However, when a machine upgrades the OS, the `osqueryd` will start failing. It will fail until there is a version update of the "osquery" package available.

We can avoid this by including the OS version in the package version similar to enterprise linux version or Ubuntu-based distros. Both RPM/DPKG allow "revisions/iterations" and it makes sense to embed the version of the build host within. If we choose to do this for OS X we will begin to muck with the versioning. It is definitely possible to support existing version semantics and move forward with something that defines the "revision" = OS version.

**Comment by sharvilshah** [comment]
10.9 builder builds packages to : `build/darwin10.9/osquery-x-x-x.pkg` and
10.10 builder builds it to: `build/darwin/osquery-x-x-x.pkg`

It's not too different on how it's done on centos:
centos7 gets packaged to: `build/centos7/osquery-x-x-x.rpm` and
centos6 is at `build/centos6/osquery-x-x-x.rpm`

(In all cases above 's/build_os/s3_key' is equivalent)

If I am grok-ing this correctly, when a user on 10.9 upgrades to 10.10, osquery will fail unless the package is updated. I think having package revision will solve the problem, and I don't see any downsides to it. Homebrew does formula revisions too when the underlying formula hasn't change but needs updating.

**Comment by theopolis** [comment]
We ended up not needing this right now. But if we do, we'll append a revision that includes the build host's OS version to the end of the package name/version string.
