### ISSUE TITLE
Collect hostname: system_info virtual table

### ISSUE THREAD

**Issue by 0xdabbad00** [facebook/osquery#1447]
osquery logging records a hostIdentifier, but additional info is needed to correlate this back to what system this is actually relevant to.  It'd be easiest for me to identify the system by hostname, but that can not be acquired by osquery.  It'd be easiest for me to take the hostidentifier of an event, and then search for that along with some sort of "host_info" table that I could have had osquery report.

**Comment by theopolis** [comment]
Definitely, and just to note: `hostname` could also change! Though not as often as `hostIdentifier`! The osquery default "hostIdentifier" is really the machine's domainname, which is the `gethostname` boost method-- the FQDN of the host/DHCP client. You can get something slightly more permanent using `--host_identifier=uuid`. On Linux this will generate a UUID, store it in RocksDB, and emit as `hostIdentifier`. On OS X this uses the `gethostuuid` library call to get the board/machine UUID.

But either way, the hostname is a good piece of information! We could make `--host_identifier` take `{host, domain, uuid}`, change the default to use `host` that emits JUST the hostname; and if you want the same data emitted today use `domain`. 

What do you think @0xdabbad00, sound like a plan?

**Comment by 0xdabbad00** [comment]
We are going to keep using the UUID for our hostIdentifier as this seems to be the easiest way to track an Apple system, since it seems this can not be changed (without removing physical components) and should survive through most any event that happens to a system (osquery get's removed and re-installed, OS get's wiped, etc.).  However, being able to correlate this to a hostname, and for those that use hostnames to correlate this to a UUID, seems like it would be very useful.

The basic problem is if we install osquery across a large number of systems, and then one reports info that makes us want to investigate it, we need a way to better track down that system.  One solution is to have a separate inventory tracking system which records things like the hardware UUID, so that you can just match up osquery data with that database, but that will be problematic for those that install osquery on non-Apple systems, since the UUID on non-Apple systems is simply a random number that osquery generates, and not an OS supported identifier. This is also useful for those without such an inventory system, or for those that may end up with systems that are not inventoried as precisely as would be hoped.

Many tools similar to osquery will provide an initial report of basic system information on the systems they install on such as that reported by the system_profiler command on Apple (or clicking "About this Mac" -> "System Report"), but that all is likely outside of the scope of what is necessary for osquery, and much of the more useful components of that data is accessible in osquery already.

I tried thinking of what else would be useful here, but all I can think of is to have a table (maybe called "system_info") with the host, domain, and UUID.

**Comment by marpaia** [comment]
@0xdabbad00 that sounds like a good idea, we should have that table. any interest in putting together a PR with such a table?

Would that be sufficient? we could potentially always include hostname in log results (in addition to hostIdentifier) although this seems wasteful if your host identifier is hostname.

**Comment by 0xdabbad00** [comment]
@marpaia Sure, we'll do a PR. It'll be a week or two before we get to this though.

**Comment by theopolis** [comment]
A bit more around the `system_info` idea: It would be awesome to know the `chipset` or some sort of hardware ID for the machine too! `cpu_type` and `memory_info` might be better as separate tables since there can be multiple/different CPUs on a board, same with memory, but "generally" there's 1 or a set of the same.

**Comment by marpaia** [comment]
Got an ask to also include the serial number: https://github.com/0infinity/IOPlatformSerialNumber/blob/master/cpuid.c

**Comment by marpaia** [comment]
Closing this and moving the tracking to #619 so that it doesn't show up in the "open issues", but let's keep discussion here. @0xdabbad00 any progress on this so far?

**Comment by 0xdabbad00** [comment]
Yes, I have it implemented. I'm waiting for someone on my team to review it before I submit a PR.

**Comment by marpaia** [comment]
@0xdabbad00 :dancer: :dancer:

**Comment by 0xdabbad00** [comment]
Created PR: https://github.com/facebook/osquery/pull/1490

**Comment by 0xdabbad00** [comment]
Updated the PR to address the comments
