### ISSUE TITLE
osquery won't start on Ubuntu 15.04: missing libgcrypt.so.11

### ISSUE THREAD

**Issue by jnbdz** [facebook/osquery#1455]
Ubuntu version:

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid

Error:

    ● osqueryd.service - LSB: run osqueryd daemon    Loaded: loaded
    (/etc/init.d/osqueryd)    Active: failed (Result: exit-code) since Tue
    2015-08-18 05:15:09 UTC; 8s ago
         Docs: man:systemd-sysv-generator(8)   Process: 27710 ExecStart=/etc/init.d/osqueryd start         (code=exited, status=127)

    Aug 18 05:15:09 public-server-01 systemd[1]: Starting LSB: run osqueryd daemon...

    Aug 18 05:15:09 public-server-01 osqueryd[27710]: osqueryd: error while loading shared libraries: libgcrypt.so.11: cannot open shared object file: No such file or directory

    Aug 18 05:15:09 public-server-01 systemd[1]: osqueryd.service: control process exited, code=exited status=127

    Aug 18 05:15:09 public-server-01 systemd[1]: Failed to start LSB: run osqueryd daemon.

    Aug 18 05:15:09 public-server-01 systemd[1]: Unit osqueryd.service entered failed state.

    Aug 18 05:15:09 public-server-01 systemd[1]: osqueryd.service failed.

This how I installed it:

    dpkg -i osquery-latest.deb

    apt-get install osquery

**Comment by marpaia** [comment]
Can you try running the binary itself with `--verbose --debug` and post error logs if available? If it crashes, supply a crash dump, etc.

We don't *technically* support ubuntu 15, we only support the operating systems that we have vagrant boxes for: https://github.com/facebook/osquery/blob/master/Vagrantfile

We could perhaps add the latest ubuntu to our build rotation as well, if we get a vagrant box, but I'm not sure if the juice is worth the squeeze there as most folks run the LTS.

**Comment by sharvilshah** [comment]
This is an upstream bug: [ubuntu 15.04 is missing libgcrypt](https://bugs.launchpad.net/ubuntu/+source/libgcrypt11/+bug/1452216)

**Comment by theopolis** [comment]
We can fix this by adding an explicit dependency for the "should-be-installed-by-default" `libgcrypt` package.
