### ISSUE TITLE
feature: enroll_secret_env

### ISSUE THREAD

**Issue by blackfist** [facebook/osquery#1460]
Right now if you're using TLS to send configurations to osquery you have the option of specifying an `enroll_secret_path` which will store the shared secret being used to authenticate hosts. That does encourage us to keep our secrets in a plain text file which isn't ideal and also makes us touch every machine if we want to do a cred roll.

It would make for happy fun times if we had a flag like `enroll_secret_env=OSQUERYENROLL` or something like that which would make osquery look in an environment variable for the shared secret rather than on the filesystem.

**Comment by marpaia** [comment]
What if we had a enrollment secret acquisition plugin interface? The default could be reading it from a file, but we could also support environment variables, encrypted magic, etc.

**Comment by theopolis** [comment]
I like the idea of a plugin type for this, the force factor would be one 1 more retrieval method. If someone needs a non-path, non-environment method I'll refactor this into another plugin type. Having it a non-plugin type means a minuscule lower RSS footprint as the plugins maintain state.
