### ISSUE TITLE
Kext table doesn't include if extension is actually loaded or signed(and by who)

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#1462]
Perhaps a rundown of the history behind the current state of osquery's `kernel_extensions` table may be helpful, I scratched my head about the discrepancies between it and 1. the cache compiled in `/System/Library/Caches/com.apple.kext.caches/Directories/`(System/Library)`/Extensions/KextIdentifiers.plist.gz` or 2. `system_profiler SPExtensionsDataType`'s output, which both number over 300 on my system, whereas osqueryi returns ~125.
Irregardless, knowing that the kext is loaded and if it's signed (and by whom) would help greatly. I could therefore say 'gimme all the non-apple's that are loaded' and zoom in on anything not in my whitelist (currently the following:
```
"/Library/Application Support/VirtualBox/VBoxDrv.kext",
"/Library/Application Support/VirtualBox/VBoxNetAdp.kext",
"/Library/Application Support/VirtualBox/VBoxNetFlt.kext",
"/System/Library/Extensions/dne.kext",
"/System/Library/Extensions/dniregistry.kext",
"/System/Library/Extensions/net6im.kext"
```
for virtualbox and citrix VPN, respectively). If I _can_ actually tell if it's loaded by interpreting the current output of this or another table I'm all for gettin' schooled, but it didn't jump out at me. Thanks!

**Comment by arubdesu** [comment]
And here's what I looked at when scratching my head about the osqueryi `kernel_extensions` output:
```
$ gzcat /System/Library/Caches/com.apple.kext.caches/Directories/Library/Extensions/KextIdentifiers.plist.gz | grep OSBundlePath | wc -l
      11
$ gzcat /System/Library/Caches/com.apple.kext.caches/Directories/System/Library/Extensions/KextIdentifiers.plist.gz | grep OSBundlePath | wc -l
     359
$ system_profiler SPExtensionsDataType | grep Location | wc -l
     372
$ /usr/local/bin/osqueryi --csv "select name, path from kernel_extensions" | wc -l
     127
$ system_profiler SPExtensionsDataType | grep "Loaded: Yes" | wc -l
     121
```
(As un-scientific/not-helpful as that may be)

**Comment by arubdesu** [comment]
Pardon that I now at least see the description of the table and it does say "both loaded and in the load search path", but that shouldn't have kexts intermittently dropping out, right? I have one in particular, `/System/Library/Extensions/Seagate Storage Driver.kext`, that doesn't get returned from the above command as frequently as my inventory client runs(every half hour or so), which makes for an unreliable binary yes/no check against inclusion in a whitelist...

**Comment by theopolis** [comment]
Hey @arubdesu, this is high-pri on my list! I'm doing some investigations now, expect an update sometime today. If you want to chat I'll be on IRC most of the day.

**Comment by theopolis** [comment]
The description for the `kernel_extensions` table is wrong. The table only includes *loaded* extensions, and uses KextManager: https://developer.apple.com/library/mac/documentation/IOKit/Reference/KextManager_header_reference/#//apple_ref/c/func/KextManagerCopyLoadedKextInfo to populate that list.

The table **should** include all loadable, or cached, extensions. If this is changed from loaded-> loadable then we can add a `loaded` column and get more useful information out of `added` and `removed` differential events.

**Comment by arubdesu** [comment]
But signature state/by whom could be considered part of this request as well?

**Comment by marpaia** [comment]
Closing this and tracking the request for a signature column in #619.
