### ISSUE TITLE
Slow performance on joining processes and listening_ports on OS X

### ISSUE THREAD

**Issue by sharvilshah** [facebook/osquery#1465]
I grabbed this example query to get processes, port and pid which are listening on all interfaces for a demo:

```sql
SELECT DISTINCT process.name, listening.port, process.pid
FROM processes AS process
JOIN listening_ports AS listening ON process.pid = listening.pid
WHERE listening.address = '0.0.0.0';
```
and noticed it took a bit (~8 seconds) on my system.

```
osquery> .timer on
osquery> SELECT DISTINCT process.name, listening.port, process.pid
    ...> FROM processes AS process
    ...> JOIN listening_ports AS listening ON process.pid = listening.pid
    ...> WHERE listening.address = '0.0.0.0';
+----------------------------------------------+-------+-------+
| name                                         | port  | pid   |
+----------------------------------------------+-------+-------+
| UserEventAgent                               | 0     | 239   |
| SystemUIServer                               | 63837 | 248   |
| Dropbox                                      | 17500 | 300   |
| 2BUA8C4S2C.com.agilebits.onepassword4-helper | 55141 | 320   |
+----------------------------------------------+-------+-------+
Run Time: real 7.248 user 2.972252 sys 4.256340
```

* This seems to be an issue on OS X only (I have only tested this on 10.10), and Ubuntu and CentOS are unaffected. 

* Queries to individual tables: `processes`, `listening_ports`, `process_open_sockets` are fast.

* More than half of the run time is sys time, so I checked that with Instruments.app. Here's the flame graph of the time profile:

![osquery_time_flame_graph](https://cloud.githubusercontent.com/assets/819943/9478230/57f3db76-4b2b-11e5-8c66-d6e5a27e9066.png)

* According to that, about ~86% of time is spent in `pid_procfdinfo`

Here's the system trace highlights from Instruments:

```
      1 Calls            Symbol Name
      2 3545687   99.8%               __proc_info
      3 3424416   96.4%                osquery::tables::genSocketDescriptor
      4 3424416   96.4%                 osquery::tables::genOpenDescriptors
      5 3424416   96.4%                  osquery::tables::genOpenSockets
      6 3424416   96.4%                   osquery::processOpenSocketsTablePlugin::generate
      7 3424416   96.4%                    osquery::TablePlugin::call
      8 3424416   96.4%                     osquery::RegistryHelperCore::call
      9 3424416   96.4%                      osquery::RegistryFactory::call
     10 3424416   96.4%                       osquery::SQL::selectAllFrom
     11 3424416   96.4%                        osquery::tables::genListeningPorts
     12 3424416   96.4%                         osquery::listeningPortsTablePlugin::generate
     13 3424416   96.4%                          osquery::TablePlugin::call
     14 3424416   96.4%                           osquery::RegistryHelperCore::call
     15 3424416   96.4%                            osquery::RegistryFactory::call
     16 3424416   96.4%                             osquery::tables::xFilter
     17 3424416   96.4%                              sqlite3VdbeExec
     18 3424416   96.4%                               sqlite3_step
     19 3424416   96.4%                                shell_exec
     20 3424416   96.4%                                 osquery::launchIntoShell
     21 3424416   96.4%                                  main
     22 3424416   96.4%                                   start
     23 119460    3.3%                 osquery::tables::genOpenDescriptors
     24 119460    3.3%                  osquery::tables::genOpenSockets
     25 119460    3.3%                   osquery::processOpenSocketsTablePlugin::generate
```

And the pretty graphs:

<img width="1174" alt="screen shot 2015-08-25 at 1 19 20 pm" src="https://cloud.githubusercontent.com/assets/819943/9478692/1da1c7c8-4b2e-11e5-851c-a5fc3ce1f401.png">

* I am not sure why so many calls to `proc_info` are being made and why `proc_info` takes so long. 

* This might be only something Apple can fix in its `libproc` implementation, in that case feel free to close this issue unless there are other `mach`/`CoreFoundation` APIs we could rely on, or if we can reduce the number of calls required to `proc_info`.

**Comment by sharvilshah** [comment]
This is done with LittleSnitch disabled, so I don't think there are external processes adding latency.

**Comment by marpaia** [comment]
Best report ever.

**Comment by sharvilshah** [comment]
This seems to be my system specific issue for now.

I stopped SystemUIServer (`launchctl stop com.apple.SystemUIServer.agent`) which launchctl will respawn and it seems to have worked:

```
osquery> SELECT DISTINCT process.name, listening.port, process.pid FROM processes AS process JOIN listening_ports AS listening ON process.pid = listening.pid WHERE listening.address = '0.0.0.0';
+----------------------------------------------+-------+------+
| name                                         | port  | pid  |
+----------------------------------------------+-------+------+
| UserEventAgent                               | 0     | 246  |
| Dropbox                                      | 17500 | 341  |
| 2BUA8C4S2C.com.agilebits.onepassword4-helper | 49263 | 600  |
| SystemUIServer                               | 51885 | 1077 |
+----------------------------------------------+-------+------+
Run Time: real 0.655 user 0.439811 sys 0.215417
```

Not quite sure why that is (purely coincidence that I picked SystemUIServer to kill first from the list), but the performance is much better now. 
I also tested this on 10.11 VM (although not much applications running on there) and it's pretty fast there.

Closing this for now. I'll reopen if this persists and I uncover more stuff.

**Comment by sharvilshah** [comment]
Interestingly with passage of time (and use), the query time has creeped up to ~4 seconds. Stopping SystemUIServer did nothing this time around, but a system restart brought the query down to sub 1 second again.

**Comment by theopolis** [comment]
Swap your join and you'll see massive performance gains. I think the intent is to join process details against each pid associated with a listening socket? Otherwise (the way you have it now) you're listing all process pids and for each: searching for a matching pid that is listening. ;)

**Comment by theopolis** [comment]
SELECT DISTINCT process.name, listening.port, process.pid
FROM listening_ports AS listening
JOIN processes AS process ON listening.pid = processes.pid
WHERE listening.address = '0.0.0.0';

Sorry for lack of markdown, on mobile!

**Comment by sharvilshah** [comment]
WHOA. Duh! 

I shouldn't have blindly copy pasta the query from README and should have given the query a second look before going on a wild goose chase. Thanks @theopolis

**Comment by sharvilshah** [comment]
![image](https://i.imgur.com/cXclkJJ.gif)

**Comment by sharvilshah** [comment]
From best -> worst report -- that (de) escalated quickly haha. Well, at least gained some more insight in profiling tools.

**Comment by theopolis** [comment]
The report is still fantastic! We should update the readme and do a quick search for example queries that could be optimized via SQL.
