### ISSUE TITLE
osqueryi generates error "dyld: Symbol not found: _kCFURLQuarantinePropertiesKey"

### ISSUE THREAD

**Issue by sboss** [facebook/osquery#1466]
without SUDO:
$ osqueryi
dyld: Symbol not found: _kCFURLQuarantinePropertiesKey
  Referenced from: /usr/local/bin/osqueryi
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /usr/local/bin/osqueryi
Trace/BPT trap: 5

with SUDO:
$ sudo osqueryi
dyld: Symbol not found: _kCFURLQuarantinePropertiesKey
  Referenced from: /usr/local/bin/osqueryi
  Expected in: /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
 in /usr/local/bin/osqueryi

osquery is from the .pkg downloaded 8/25.

**Comment by marpaia** [comment]
Can you post some details about your OS X install (version, etc)?

**Comment by marpaia** [comment]
Also can you run

```
otool -L /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
```

and

```
nm /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
```

**Comment by sboss** [comment]
I have a MBP (late 2011), running Mavericks (10.9.5) with 16Gig RAM, on a 1TB SSD.  My O/S is fully patched for being Mavericks.

**Comment by sboss** [comment]
otool:

/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation:
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 855.17.0)
	/usr/lib/libauto.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libDiagnosticMessagesClient.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libicucore.A.dylib (compatibility version 1.0.0, current version 51.1.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)

**Comment by sboss** [comment]
nm output it too long to post.  I have put it and the otool output in txt files inside the zip file.

https://www.dropbox.com/s/k4zogxzu6pv0vv5/osquery.zip?dl=0

**Comment by sboss** [comment]
let me know if the dropbox link doesn't work or is expired.

**Comment by sharvilshah** [comment]
@sboss Was that error with `osquery-latest.pkg`? Support for 10.9 got fixed in [1.5.2](https://github.com/facebook/osquery/releases/tag/1.5.2), but the links on the [download page](https://osquery.io/downloads/) haven't been updated yet and still point to 1.5.1

**Comment by sboss** [comment]
it was with ossuary-1.5.1.pkg let me try the -latest.pkg.

**Comment by sboss** [comment]
osquery-latest.pkg works as it should. so this is a bad bug report as it is fixed in the latest .pkg file.  Sorry about that.

**Comment by marpaia** [comment]
All good, thanks for pointing that out @sharvilshah
