### ISSUE TITLE
Query returns different column for alias

### ISSUE THREAD

**Issue by rafaelgarrido** [facebook/osquery#1482]
Column name from table processes is being replaced by etc_protocols.name:

```
osquery> select lp.pid, lp.port, lp.address, p.name, pr.name from listening_ports lp inner join processes p on lp.pid = p.pid inner join etc_protocols pr on lp.protocol = pr.number;
+-------+-------+--------------+------+------+
| pid   | port  | address      | name | name |
+-------+-------+--------------+------+------+
| 63    | 0     |              | ip   | ip   |
| 293   | 0     | 0.0.0.0      | udp  | udp  |
| 3138  | 0     | 0.0.0.0      | tcp  | tcp  |
| 6296  | 17500 | 0.0.0.0      | udp  | udp  |
+-------+-------+--------------+------+------+
```

**Comment by marpaia** [comment]
This is happening because, in your query, you're asking for two columns which are both called `name`. Call them something else more context specific and this works:

```
osquery> select lp.pid, lp.port, lp.address, p.name as pname, pr.name as prname from listening_ports lp inner join processe
+-------+-------+----------------+-------------------------------------------------+--------+
| pid   | port  | address        | pname                                           | prname |
+-------+-------+----------------+-------------------------------------------------+--------+
| 621   | 0     | 0.0.0.0        | UserEventAgent                                  | udp    |
| 621   | 0     |                | UserEventAgent                                  | ip     |
| 631   | 3283  | 0.0.0.0        | ARDAgent                                        | udp    |
| 631   | 3283  | 0.0.0.0        | ARDAgent                                        | udp    |
| 673   | 53482 | 0.0.0.0        | SystemUIServer                                  | udp    |
| 791   | 4500  | 127.0.0.1      | zixi_video_acceleration_proxy-16617             | tcp    |
| 799   | 6258  | 127.0.0.1      | 2BUA8C4S2C.com.agilebits.onepassword-osx-helper | tcp    |
| 799   | 6258  | ::1            | 2BUA8C4S2C.com.agilebits.onepassword-osx-helper | tcp    |
| 799   | 6263  | 127.0.0.1      | 2BUA8C4S2C.com.agilebits.onepassword-osx-helper | tcp    |
| 799   | 6263  | ::1            | 2BUA8C4S2C.com.agilebits.onepassword-osx-helper | tcp    |
| 813   | 4370  | 127.0.0.1      | SpotifyWebHelper                                | tcp    |
| 813   | 4380  | 127.0.0.1      | SpotifyWebHelper                                | tcp    |
| 848   | 17500 | 0.0.0.0        | Dropbox                                         | udp    |
| 848   | 17500 | 0.0.0.0        | Dropbox                                         | tcp    |
| 848   | 17600 | 127.0.0.1      | Dropbox                                         | tcp    |
| 848   | 17603 | 127.0.0.1      | Dropbox                                         | tcp    |
| 8825  | 17501 | 0.0.0.0        | Dropbox                                         | tcp    |
| 52122 | 2222  | 127.0.0.1      | VBoxHeadless                                    | tcp    |
| 52122 | 64599 | 0.0.0.0        | VBoxHeadless                                    | udp    |
| 60450 | 4381  | 127.0.0.1      | Spotify                                         | tcp    |
| 60450 | 4371  | 127.0.0.1      | Spotify                                         | tcp    |
| 60450 | 57621 | 0.0.0.0        | Spotify                                         | udp    |
| 60450 | 57621 | 0.0.0.0        | Spotify                                         | tcp    |
| 60450 | 59798 | 172.24.236.153 | Spotify                                         | udp    |
| 60450 | 63929 | 172.24.236.153 | Spotify                                         | udp    |
+-------+-------+----------------+-------------------------------------------------+--------+
```

**Comment by rafaelgarrido** [comment]
Hello @marpaia, thanks for following up and proposing a solution with field name aliasing.

Although that helps with the disambiguation of columns, I do believe there is a glitch that replaces the content of column processes.name with etc_protocols.name. Otherwise it wouldn't display two columns for "name".

I was expecting to receive the process names on either an ambiguous column name or on a automatic alias with a suffix or what not. Suppressing data due to query construction seems to be more than an user operational issue and should be investigated.

**Comment by marpaia** [comment]
I think this is one of those times where the simplest possible solution is to say "don't do that". Naming two columns the same thing is a configuration error. Don't do it and this problem won't exist.

**Comment by rafaelgarrido** [comment]
OK, fair enough. I can live with this. As long as we agree this is a legit bug that won't be addressed :+1:

**Comment by marpaia** [comment]
Personally, I think that, if you have ambiguous column names in your query, that's a legit bug in your query :) Anything that happens after that is, as far as I'm concerned, undefined behavior.

**Comment by marpaia** [comment]
That being said, in a perfect world, we would gracefully handle that error case, sure.

**Comment by theopolis** [comment]
Here's a comparison of the default print behavior and the expected:
```
osquery> select lp.pid, lp.port, lp.address, p.name, pr.name from listening_ports lp inner join processes p on lp.pid = p.pid inner join etc_protocols pr on lp.protocol = pr.number limit 1;
+-----+------+---------+------+------+
| pid | port | address | name | name |
+-----+------+---------+------+------+
| 522 | 0    | 0.0.0.0 | udp  | udp  |
+-----+------+---------+------+------+
osquery> .mode line
osquery> select lp.pid, lp.port, lp.address, p.name, pr.name from listening_ports lp inner join processes p on lp.pid = p.pid inner join etc_protocols pr on lp.protocol = pr.number limit 1;
    pid = 522
   port = 0
address = 0.0.0.0
   name = UserEventAgent
   name = udp
osquery> 
```

In both you have duplicate `name` columns but in the second you see the expected values for each. This is due to the undefined behavior of column conflicts. There is a fixable bug here in the default "pretty print" output but I think it should remain "wont fix". It is almost always recommended to avoid those column conflicts. 

Legit, but benign, bug, won't be addressed, for sure!

**Comment by rafaelgarrido** [comment]
@theopolis thanks for the insightful comment. I agree with you this is a benign bug and respect the decision of not prioritizing/addressing it.

@marpaia I also agree this is a bug on the query. I forced this situation to check how osquery would behave so I could plan how to better use my queries with some scripts. Some RDBMS duplicate column names on the tuple, some throws exceptions, some add a "_N" suffix for each ambiguous column. So what I learn out of this is that I can't run "SELECT * " statements with joins (which is a common mistake to do). Since I don't remember what is defined on ANSI SQL for this kind of situation, I also agree that the behavior is undefined and rather impossible to predict from the user standpoint.

Thank you both! I am very excited with this tool!

**Comment by theopolis** [comment]
No problem! It's good to have this documented as an issue too. 

If you find yourself with a few spare minutes and want to familiarize yourself with the codebase: adding a warning log for duplicate column names encountered in the daemon's query schedule would be neat. :)
