### ISSUE TITLE
Query Pack Returning Empty Results

### ISSUE THREAD

**Issue by Centurion89** [facebook/osquery#1483]
Steps to reproduce:

1. Create plist in /Library/LaunchDaemons called com.JavaW.plist (simulate the presence of malware)

2. launchctl load com.JavaW.plist

3. Ensure plist is loaded:
`$ launchctl list | grep JavaW`
`7125	0	copy com.JavaW.plist`

4. Ensure the plist is seen from osqueryi
`osquery> select path,name,label from launchd where name = 'com.JavaW.plist';`

5. Enable the osx-attacks (or malware) query pack with snapshots set to true and interval set to 30 seconds

6. tail /var/log/osquery/osqueryd.snapshots.log and wait for the osx-attacks query pack to run

7. Results show up empty
`{"snapshot":"","name":"osx_attacks","hostIdentifier":"myhostname.local","calendarTime":"Tue Sep  1 15:52:27 2015 UTC","unixTime":"1441122747"}`

**Comment by marpaia** [comment]
Oh hey, @Centurion89 :)

**Comment by marpaia** [comment]
What version of osquery are you running?

**Comment by Centurion89** [comment]
*waves* :)

Version is 1.5.0

**Comment by marpaia** [comment]
There was a bug with 1.5.0 which caused this, try upgrading to 1.5.2, which is the current stable latest.

**Comment by Centurion89** [comment]
Tried with 1.5.2-29-g7ac1b99 and still having the same problem :(

**Comment by marpaia** [comment]
Can you elaborate on "Enable the osx-attacks (or malware) query pack with snapshots set to true and interval set to 30 seconds"?

Also, can you post the actual reproduction config files as well as commands executed to launch osquery?

**Comment by Centurion89** [comment]
Sure, I think that's explained in my config. It's entirely possible I configured the packs incorrectly - I put it in a Gist here:

https://gist.github.com/Centurion89/b5d6f931156822ac798b

My snapshot logs display the following every 10 seconds (as expected):
`{"snapshot":"","name":"it_compliance","hostIdentifier":"myhostname.local","calendarTime":"Tue Sep  1 18:12:17 2015 UTC","unixTime":"1441131137"}`
`{"snapshot":"","name":"osx_attacks","hostIdentifier":"myhostname.local","calendarTime":"Tue Sep  1 18:12:17 2015 UTC","unixTime":"1441131137"}`

I'm launching just via "osqueryd" and have verified that it's using the correct config

**Comment by marpaia** [comment]
```
  "schedule": {
    "osx_attacks": {
      "interval": 10,
      "snapshot": true
    },
    "it_compliance": {
      "interval": 10,
      "snapshot": true
    }
  },
```

^^ this doesn't work, you can't override the packs like this. The reason why you're getting blank results is because the "osx_attacks" query (which you're defining in the schedule there) doesn't contain a query text, so there's no results for it to return.

**Comment by marpaia** [comment]
I like where your heads at though, that's a nice UX. We should think about supporting something like that.

**Comment by marpaia** [comment]
Right now, much to a lot of people's dissapointment, there's no way to override the interval (or other options, like snapshot) of queries that are included in packs. Fortunately though, packs are just JSON and it would be pretty easy to write a little python tool that re-wrote options/intervals.

**Comment by Centurion89** [comment]
OHHH now I understand. The code snippet on this page make it super vague how to actually configure them. Having the "schedule" block above gave me the impression that I could schedule my packs to run at a schedule that I defined. I think elaborating in that code example would help make this more obvious. 

https://osquery.readthedocs.org/en/stable/deployment/configuration/#query-packs

**Comment by Centurion89** [comment]
OK cool, just modified the actual pack and now I understand how this all fits together and it all works. I had a feeling this might be a bad case of PEBKAC. Thanks for the help!

**Comment by marpaia** [comment]
NP, let us know if you have any more questions. I'm making a bunch of changes to the way packs are managed internally in #1474, which includes a number of documentation changes as well.
