### ISSUE TITLE
Implement buffering and compression controls for TLS-based loggers

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1489]
It would be nice to include:
1. LZ4 stream compression on TLS POST body results.
2. Options for buffing logs based on time and size.

**Comment by defunctzombie** [comment]
On a related note. I am looking at the docs and trying to find any information about the size of the POST data when using the TLS logger. If I write an endpoint for a TLS logger, how large of a request size should it be able to ingest? Would it be reasonable to provide a config option to have TLS logging split the requests into smaller chunks if the individual request size exceeds the configured max.

**Comment by theopolis** [comment]
So as of 1.7.0 there is a `--logger_tls_max` that can limit the max number of bytes sent within a POST request. If this limit (default=1MB) is exceeded, a status line is generated with the associated details. Since status and results logs are sent independently, the chances of losing a status line due to an overflow of status data is very low. Thus violations of the 1MB limit should be observed. In my case I've noticed several hosts with ~2MB of results logs being denied had have changed the configuration option to 4MB (in this case I control the max request size so 4MB is confirmed+accepted).

1.7.0 also allows the non-default `--logger_tls_compress=True` which will apply gzip compression to the log data and set the appropriate content-type in the HTTPS request header.
