### ISSUE TITLE
osquery build system is forcefully changing external library links to librocksdb.so

### ISSUE THREAD

**Issue by sami2316** [facebook/osquery#1502]
I am trying to add external library with ```ADD_OSQUERY_LINK_ADDITIONAL("broker")``` that will be used in making executable file. but the linker is generating following error
```
[ 77%] Built target modexample
Linking CXX executable osquery_additional_tests
/usr/bin/ld: warning: librocksdb.so, needed by /usr/local/lib/libbroker.so, not found (try using -rpath or -rpath-link)
[ 85%] Built target osquery_additional_tests
Linking CXX executable osquery_benchmarks
/usr/bin/ld: warning: librocksdb.so, needed by /usr/local/lib/libbroker.so, not found (try using -rpath or -rpath-link)
[ 87%] Built target osquery_benchmarks
Linking CXX executable osquery_kernel_benchmarks
/usr/bin/ld: warning: librocksdb.so, needed by /usr/local/lib/libbroker.so, not found (try using -rpath or -rpath-link)
[ 88%] Built target osquery_kernel_benchmarks
Linking CXX executable osquery_kernel_tests
/usr/bin/ld: warning: librocksdb.so, needed by /usr/local/lib/libbroker.so, not found (try using -rpath or -rpath-link)
[ 89%] Built target osquery_kernel_tests
-- Built libosquery: /home/bproject/osquery/build/centos7/libosquery.a
[ 89%] Built target osquery_library
Linking CXX executable osquery_tables_tests
/usr/bin/ld: warning: librocksdb.so, needed by /usr/local/lib/libbroker.so, not found (try using -rpath or -rpath-link)
[ 91%] Built target osquery_tables_tests
Linking CXX executable osquery_tests
[ 98%] Built target osquery_tests
Linking CXX executable run
/usr/bin/ld: warning: librocksdb.so, needed by /usr/local/lib/libbroker.so, not found (try using -rpath or -rpath-link)
[ 98%] Built target run
Linking CXX executable osqueryi
/usr/bin/ld: warning: librocksdb.so, needed by /usr/local/lib/libbroker.so, not found (try using -rpath or -rpath-link)
[100%] Built target shell

```
```ldconfig -v``` shows true link in /usr/local/lib. What could be the possible reason and how can I solve it?
I am using ```CENTOS 7```

**Comment by marpaia** [comment]
We only install the static `librocsdb.a` in our provisioning tooling. What is broker? Is that a thing that you've created? If so, it shouldn't be linking against `librocksdb.so`, it should link against `librocksdb.a`.

**Comment by sami2316** [comment]
```broker``` is communication library. It's an external library (I am not building it) which i am using as libbroker.so. Broker does not provide ```libbroker.a``` 
so what's the solution then?

**Comment by marpaia** [comment]
`librocksdb.so` is needed by `libbroker.so`. We're not RocksDB or the creator's of this Broker library, so this doesn't seem like an osquery problem.

The solution, however, is that the build system is linking against `libbroker.so`, which requires `librocksdb.so` to exist. So you need to compile librocksdb.so and install it.
