### ISSUE TITLE
Logs Prepending Pack Name Into Name Key

### ISSUE THREAD

**Issue by jacknagz** [facebook/osquery#1505]
Per my conversation with @javuto , when I migrated a set of queries from normal `schedule` to `packs`, then the pack name became prepended to the query result 'name' key in the logs:

before:
`hostname osqueryd[pid]: result={"name":"processes" ... }`

after:
`hostname osqueryd[pid]: result={"name":"packname_processes" ... }`

This causes issues on the back-end log aggregation since `name` is used to identify historical data.

**Comment by marpaia** [comment]
This is how we express both the name of the pack and the name of the query in the log. Is updating your log searches to account for the new scheme possible?

**Comment by jacknagz** [comment]
@marpaia could it be expressed via a separate key? like `{"pack":"packname"}`?  

We could glob our Splunk searches, but if we have a similar query name between two packs it'll cause issues.

**Comment by theopolis** [comment]
We could include a flag: `--packs_prepend_name=true` that you can set to `false` and force all packs to use just the query name. Collisions of query names within packs will be undefined by most likely lead to weird differentials.

**Comment by marpaia** [comment]
Yeah, like @theopolis said, if we cut the pack name, weird things could happen in you have a query named the same thing in two packs. If you can change your splunk searches to glob, why don't you change them to use the new packs naming format, @jacknagz? The new format offers you more descriptive, informative names for your queries, it seems like a win/win for a little amount of effort.
