### ISSUE TITLE
HTTP 403 on centos7/osquery-1.5.2.rpm

### ISSUE THREAD

**Issue by sharvilshah** [facebook/osquery#1513]
The download link for CentOS 7 RPM package: https://osquery-packages.s3.amazonaws.com/centos7/osquery-1.5.2.rpm gives 403 Forbidden.

```bash
❯ curl -I https://osquery-packages.s3.amazonaws.com/centos7/osquery-1.5.2.rpm
HTTP/1.1 403 Forbidden
x-amz-request-id: 3CE10AC48A62E60B
x-amz-id-2: TVa+XLpwPw9LzrnbLkzHQB77c6AJRLqV0wMNSlyQduhpUH55tTkusf/lIis7FM5H12Jfmdt8/bE=
Content-Type: application/xml
Transfer-Encoding: chunked
Date: Fri, 18 Sep 2015 17:42:57 GMT
Server: AmazonS3
```

Rest of the links work great.

**Comment by sroberts** [comment]
I've been having issues with the apt repository for Debian as well:

![screen shot 2015-09-18 at 3 10 36 pm](https://cloud.githubusercontent.com/assets/44774/9968717/fab96bd8-5e17-11e5-8655-ab121b202ede.png)

**Comment by javuto** [comment]
For some reason some tagged versions did not get sync'd to s3, I am on it

**Comment by theopolis** [comment]
@sharvilshah, looks like CentOS7's 1.5.2 exists now! The Ubuntu 12.04 deb exists too, but I don't have a 12.04 install to check if apt can update correctly; if you have a chance @sroberts, do you mind checking if the update is resolved?

Thanks for jumping on this @javuto!

**Comment by sharvilshah** [comment]
Looks good, thanks @javuto!

**Comment by sroberts** [comment]
I double checked this finally, turns out `apt-get install osquery` still doesn't work.

**Comment by javuto** [comment]
Hey @sroberts, I have just fixed the trusty/precise repos and now you can apt-get install osquery again. Right now you will get the latest package generated (master build), so working on distributing with the repos the latest tagged release instead.

**Comment by theopolis** [comment]
The missing `main/source/Sources` problem is a known issue with 12.04.

When you add a "non-Sources" package source, using:
```
sudo add-apt-repository "deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/precise precise main"
```

It will automatically append a "Sources" entry (`/etc/apt/sources.list`):
```
deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/precise precise main
deb-src [arch=amd64] https://osquery-packages.s3.amazonaws.com/precise precise main
```

What you want is:
```
deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/precise precise main
# deb-src [arch=amd64] https://osquery-packages.s3.amazonaws.com/precise precise main
```

You'll have to manually edit your sources list and remove the `deb-src` target.

**Comment by sroberts** [comment]
@theopolis :metal: Thanks for running this down.
