### ISSUE TITLE
Add support for the DNF package manager

### ISSUE THREAD

**Issue by thedrow** [facebook/osquery#1515]
Fedora forked Yum and started a new project called [DNF](http://dnf.baseurl.org/). Since it has a different API, the CentOS queries for Yum probably won't work. If we decide to implement this feature it means that we'll have to add Fedora to our supported operating systems and test it in CI.

**Comment by theopolis** [comment]
Hey @thedrow, I'm definitely for supporting Fedora and FNF if there are some infrastructures using Fedora on their clients or servers.

Would you mind creating a diff for build and packing support for DNF? It's essentially creating a bash script: https://github.com/facebook/osquery/tree/master/tools/provision for Fedora that installs the needed packages for a `make` to work.

The package dependencies should then be expressed in [`Packages.cmake`](https://github.com/facebook/osquery/blob/master/CMake/Packages.cmake#L13) for Fedora systems. We try to support an install requiring NO additional packages, so this step isn't too important if we get dependency (from source) installs correct.

**Comment by thedrow** [comment]
I wasn't talking about deployment (at least not yet). I was talking about adding support for querying packages installed by DNF. I can give it a shot once I'll get back from vacation (4th of October). Feel free to beat me to it.

**Comment by theopolis** [comment]
Oh, gotya! Right on, can't wait to see some Fedora support! You might need to write a straw man dependency install script to get a build up and running on Fedora. Mind submitting the deps and DNF virtual table when you get back? :dancers:

**Comment by thedrow** [comment]
Sure, I'll try.

**Comment by theopolis** [comment]
Closing this issue and tracking the table request in #619. Let's continue to use this specific task for questions/updates.

**Comment by thedrow** [comment]
Sure. I'll let you know on IRC what I tried to do and where I'm stuck.
