### ISSUE TITLE
Add table for currently loaded pf firewall rules on Darwin

### ISSUE THREAD

**Issue by jesseendahl** [facebook/osquery#1521]
The existing application layer firewall table is awesome, but a table showing pf rules would be even better. I'd like osquery to have a table that displays each pf rule that's loaded, along with the name of the anchor it's loaded from. This would just be the output of `/sbin/pfctl -a '*' -sr`

**Comment by jesseendahl** [comment]
@arirubinstein pointed out that if you try this and don't have custom rules, you'll see see an error, which reminded me that Apple's pf has a bug when dealing with wildcards. Info is here: https://pleiades.ucsc.edu/hyades/PF_on_Mac_OS_X

Relevant bit pasted below for convenience:

Note there is a bug in Apple's implementation of PF! According to pfctl(8):

If the anchor name is terminated with a '*' character, the -s flag will recursively print all anchors in a brace delimited block.

but it produces an error instead:
>$ sudo pfctl -a 'com.apple/*' -sr
anchor "*" all {
pfctl: DIOCGETRULES: Invalid argument
}
anchor "*" all {
pfctl: DIOCGETRULES: Invalid argument
}

We have to use the full anchor path:

>$ sudo pfctl -v -s Anchors
 com.apple
 com.apple/200.AirDrop
 com.apple/200.AirDrop/Bonjour
 com.apple/250.ApplicationFirewall

> $ sudo pfctl -a "com.apple/200.AirDrop/Bonjour" -sr
pass in on p2p0 inet6 proto udp from any to any port = 5353 keep state
pass out on p2p0 proto tcp all flags any keep state

**Comment by theopolis** [comment]
Agreed! @jesseendahl, would you mind writing a `network_firewall` table that on OS X exposes the pf rules?

**Comment by jesseendahl** [comment]
@theopolis I'd love to give it a go, but I literally have no time to work on this, unfortunately =\ I guess it'll have to wait until either I'm less busy or you guys can get to it.

**Comment by theopolis** [comment]
Ok, no worries! We'll move this to an item within the [table request master task](https://github.com/facebook/osquery/issues/619), close this issue, and make a reference. If you have time or recommendations for the table please continue to update this issue!

Collecting these rules isn't high priority for us right now so expect some lag unless someone else is interested.

**Comment by darkk** [comment]
> Info is here: https://pleiades.ucsc.edu/hyades/PF_on_Mac_OS_X

The URL is unavailable as the host is down (and, maybe, gone), but luckily it was archived and the copy is available at https://web.archive.org/web/20190428120934/https://pleiades.ucsc.edu/hyades/PF_on_Mac_OS_X
