### ISSUE TITLE
Query planner output option for shell

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1527]
It would be excellent to have a `--planner` or turn on a verbose planner in the shell when using `--verbose`. This could be a SQLite++ version of the planner that described `QueryContext` decisions and what virtual tables were being used (and possibly if they are making optimization decisions).

**Comment by kcreyts** [comment]
add support for profiling in the release.pkg (and query planner)

**Comment by sharvilshah** [comment]
I am assuming that the scope for profiling is something like: 

sample given query `n` times and report and compute average `cpu_time` and related metrics and not something like providing stack traces (libunwind) and adding performance counters.

If so, there is already a `.timer` functionality built in the shell to get a rudimentary `time` like output for the query. Maybe we can expand on that.

**Comment by theopolis** [comment]
I'd like the same report that `./tools/tests/profile.py` gives using the slimmed `run` test binary. In the past the best datas/comparisons have been:

1. Does a single run leak memory?
2. Does a `n` number of runs leak more than `n-1`?
3. Are there more than `k` (where k is a more-or-less static 6, 7) file descriptors open after a query completes?
4. Does joining against this table using something that seems like a pkey take an *annoying* amount of resources/wall time?

That means:

1. Reporting on all of these measures, `.timer`++
2. A switch for running a given query consecutively `-n` times.
3. A switch for concating a query `-m` times for a single run.

Am I missing anything?

**Comment by theopolis** [comment]
Also for the actual SQLite virtual machine run you can prepend `explain` or `explain query plan` to any given query. That does not introspect into the osquery-specific logic of `additional` or `required` column types.

**Comment by theopolis** [comment]
So the functionality of the `run` binary is now built into `osqueryi` and it may be used with the `./tool/profile.py` script without having to build osquery from source. I'm not yet sure if we should be bundling the profile script alongside packages. This means to profile you will still need a checkout of the osquery source.

I'd like more guidance on the **planner** part. A few notes on the expected UI/UX would be awesome! 

Here is where my thoughts are now: given the query:
```sql
 SELECT count(*) FROM processes JOIN users USING (uid);
```

Shows something similar (`.timer on` within the shell):
```
+----------+
| count(*) |
+----------+
| 322      |
+----------+
Run Time: real 0.123 user 0.099983 sys 0.008706
```

Versus the query:
```sql
SELECT count(*) FROM users JOIN processes USING (uid);
```

And:
```
+----------+
| count(*) |
+----------+
| 330      |
+----------+
Run Time: real 1.126 user 0.645359 sys 0.437934
```

We can compare the two queries:
```
osquery> explain query plan SELECT count(*) FROM users JOIN processes USING (uid);
+----------+-------+------+---------------------------------------------+
| selectid | order | from | detail                                      |
+----------+-------+------+---------------------------------------------+
| 0        | 0     | 0    | SCAN TABLE users VIRTUAL TABLE INDEX 0:     |
| 0        | 1     | 1    | SCAN TABLE processes VIRTUAL TABLE INDEX 0: |
+----------+-------+------+---------------------------------------------+
Run Time: real 0.000 user 0.000102 sys 0.000016
osquery> explain query plan SELECT count(*) FROM processes JOIN users USING (uid);
+----------+-------+------+---------------------------------------------+
| selectid | order | from | detail                                      |
+----------+-------+------+---------------------------------------------+
| 0        | 0     | 0    | SCAN TABLE processes VIRTUAL TABLE INDEX 0: |
| 0        | 1     | 1    | SCAN TABLE users VIRTUAL TABLE INDEX 0:     |
+----------+-------+------+---------------------------------------------+
```

But it is not obvious that `processes` can use `pid` as a pkey and speed up JOINs or that, more importantly in this example, `users` can use `uid`, which is the pivot. 

I'm thinking we can add a `--trace` switch that tells the virtual table implementation to actually run the query, (1) log details about how it fills in the `QueryContext` from the predicate where clauses, (2) print results from each intermediate table generate/scan, and (3) embed the metadata about `additional` and `required`/`index` to also emit logs when the corresponding column name exists within a context provided to the table. This allows us to instrument solely within the virtual table implementation and not require refactors of table code.

**Comment by theopolis** [comment]
So with the merge of #1695, there is a basic `--planner` option that prints some constraint and cursor/scan decision to stderr. This will be improved over time as we get access to more SQLite virtual table features/APIs.

I played around with representing the planning/tracing logic as a separate table so it could be output in the various modes, but coercing this data into a "hidden" table such that it can go through the SQLite workflow is a bit more work than I imagined. So it's plainly written to stderr:

```
$ osqueryi --planner
[...]
osquery> select count(*) from (select * from file where directory = '/dev/' union select * from file where directory = '/tmp');
osquery planner: Opening cursor (4) for table: file
osquery planner: Adding constraint to cursor (4): directory = /dev/
osquery planner: Scanning rows for cursor (4)
osquery planner: Closing cursor (4)
osquery planner: Opening cursor (5) for table: file
osquery planner: Adding constraint to cursor (5): directory = /tmp
osquery planner: Scanning rows for cursor (5)
osquery planner: Closing cursor (5)
+----------+
| count(*) |
+----------+
| 241      |
+----------+
osquery> 
```
