### ISSUE TITLE
Docs are cut off on macbook pro screen

### ISSUE THREAD

**Issue by aj0strow** [facebook/osquery#1532]
On the [osquery website](https://osquery.io/docs/tables/#iokit_registry) the Darwin section is too long to fit on the screen, and can't be scrolled. 

![cut-off copy](https://cloud.githubusercontent.com/assets/1374327/10145779/2f7afe1c-65f3-11e5-97b5-d8e101b5b89a.jpg)

Thought you should know. Thanks for taking a look.

**Comment by theopolis** [comment]
Good to know! We definitely want those to scroll or display as a block type and push the height of the page down.

**Comment by theopolis** [comment]
I'm not sure what to do about this yet. We could find the folder that each spec is "organized" into, such as system/network/etc and make subsections and hope those don't exceed screen height? Or add some overflow scrolling to the sidebar ;)

**Comment by theopolis** [comment]
Should be fixed, the sidebar will now oddly scroll if the sub-elements go to far off the page. Let me know/re-open if you see and problems!

**Comment by aj0strow** [comment]
@theopolis looks great
