### ISSUE TITLE
Scripted Package Downloads Failing

### ISSUE THREAD

**Issue by sroberts** [facebook/osquery#1535]
I've got a script pulling osquery and as of today the downloads are failing from curl & wget (using linked url `https://osquery-packages.s3.amazonaws.com/darwin/osquery-1.5.2.pkg`). 

<img width="1156" alt="screen shot 2015-09-29 at 11 48 03 am" src="https://cloud.githubusercontent.com/assets/44774/10169633/fa076574-669f-11e5-917e-564e552a2874.png">

Downloading using the same URL with a browser works just fine.

**Comment by javuto** [comment]
Hey @sroberts, I just wget the pkg from s3 and no issues. Maybe was a temporary s3 hiccup?

**Comment by sroberts** [comment]
Perhaps it's a connectivity issue. Thanks for checking.
