### ISSUE TITLE
Insufficient enrollment documentation

### ISSUE THREAD

**Issue by zenfish** [facebook/osquery#1540]
Small typo for Ubuntu 14.04.3 LTS, at:

https://osquery.readthedocs.org/en/stable/installation/install-linux/

Near the bottom, in the "Running osquery" section, it says:

    sudo cp /usr/share/osquery/osquery.example.conf /etc/osquery/osquery.conf
    sudo service osquery start
    sudo service osquery status

The "osquery" should be "osqueryd" (added the letter "d")

I only have run it on Ubuntu so far, so I don't know if it's supposed to be this for other OS's.

Cheers!

**Comment by marpaia** [comment]
Nice catch, @zenfish! Do you mind submitting a PR which updates that file (https://github.com/facebook/osquery/blob/master/docs/wiki/installation/install-linux.md) with a more accurate representation of your experiences? :)

**Comment by zenfish** [comment]
The only issue I have is I don’t know if it’s true for anything but ubuntu (I suspect it’s more, but…)

I’ll give it a try, in any case.

But since I’m volunteering to do that little bit, I’ll give some unasked for critique - for the love of god, throw us a scrap of documentation about enrollment of remote systems! It’d be very helpful to have a sample test client like you have the test web server, if nothing else. A sample shell script. Something that writes to kernel memory directly. Punch cards that achieve this in BCPL on a PDP-10. Anything that actually does what you describe, but for now your remote dox just blow (https://osquery.readthedocs.org/en/latest/deployment/remote/ <https://osquery.readthedocs.org/en/latest/deployment/remote/>.) 

You have great documentation for doing things locally. I really don’t want to have to read code to know how it might work from a server.

— d

**Comment by marpaia** [comment]
@zenfish, are [the enrollment docs](http://osquery.readthedocs.org/en/stable/deployment/remote/#remote-server-api) not sufficient? Any suggestions on information that we're missing that we should be including?

**Comment by marpaia** [comment]
I'm not sure I follow the "something that writes to kernel memory directly" comment? Are you referring to https://github.com/facebook/osquery/tree/master/kernel?

**Comment by marpaia** [comment]
In general though, I think that the code is the best documentation there is for how osquery works. No matter how stale the documentation is (if it ever gets stale), the code will always be the source of truth. This is true for any open source project, of course.

**Comment by marpaia** [comment]
renaming the issue to refer to the current state of the conversation.

**Comment by marpaia** [comment]
perhaps we could link to open source examples? community members, such as @blackfist, have been creating backends for remote TLS enrollment/configuration/logging/etc: https://github.com/heroku/windmill

**Comment by zenfish** [comment]
RE: marpaia & windmill - yes, exactly. I'm simply speaking as a user, and I'd say I'm a pretty technical one who has contributed security software for a quarter century gratis; rightly or wrongly I feel like I understand systems pretty well, and have been doing system and monitoring for many, many years.

But whenever one hears "I think that the code is the best documentation there is for how osquery works" - let me assure you, that's spoken by someone who is a dev on the project, not a user. I - and just about no one else in the world - don't expect to have to read the source code of my email system, my DNS, my kernel, my file system, and the rest of my platform to use all the pieces. And if that's the case, why should I read 20k-ish+ lines of yours?

The problem is aggravated by the fact that much of your documentation is of high quality; I can do pretty much anything I want on a single machine, but that's pretty worthless to me if I can't roll it out to production.

Don't get me wrong - I'm not ungrateful for the large amounts of work that have obviously gone (and continue to go) into the project. But with great power comes great responsibility and all that, and having a really key feature lacking the same polish means less people will adopt it, which I'd surmise is counter to the goals of having it on git in the first place.

For instance, searching on google for "enroll_secret" and "osquery" and I get exactly 4 hits - 3 from your sites and one from the Windmill project above. I take that as an indicator that either (a) no one knows how to use that, or perhaps (b) there is a secret cabal that is preventing the information from spreading or something... and Occam suggest the former.

It's great that you have the JSON required to do various POSTs to achieve things, but while necessary, I'd argue it's not sufficient for many to bootstrap themselves to their first remote install (it's the kind of thing I'd personally go back to and use to write my own client after checking out yours, for instance.) It'd be seemingly very simple to have a small test client, just like your test server, and in a few paragraphs (or lines, depending how easy it is!), say start the server, then point the client at it, and bam, you're done, and now the spice will flow and all is good.

Anyway, I'd like to see more of osquery in the world, not less, and while yes, I'm selfishly writing because I don't want to go through your code and just sorta want it to work, I'm also writing because while I think it's really exciting in concept, I'm not convinced yet that it's what I need to really deploy it, and I don't want to have to put in what could be substantial effort (because... who knows? It could be trivial, but I don't know yet) to find out if it's worth it or not.

All said, just my 2 cents. (And my suggesting that a method to write to the kernel directly in the original post was a jest, as was the comment about the BCPL on a PDP-10!)

Viva osquery.

**Comment by theopolis** [comment]
I love this suggestion @zenfish! IMO we should have some example `Dockerfile`s that start the enrollment server and TLS config distributor/log aggregator. But, you're right, the remote documentation should include example code that implements the basic enrollment API.

I will assign this task to me and write (at least) the docs!

**Comment by theopolis** [comment]
Hey @zenfish, I went through the documentation this weekend and came up with: #1551 as a pretty basic content refresh.

I thought pretty hard about your comments here and I agree with @marpaia that the Remote Settings JSON request/response docs are sufficient for the wiki. The [`test_http_server.py`](https://github.com/facebook/osquery/blob/master/tools/tests/test_http_server.py) is the straw man implementation of all the documented Remote Settings and *should be* enough to get interested developers/integrators off the ground.

A more complete/robust enrollment server and config/logger set of endpoints is out of scope for now. I'm going to recommend we focus a bit more on highlighting community projects and integrations on the homepage-- and work towards having a simple blog to do setup walkthroughs. The rational is just a focus of priority, right now we're still very very focused on the client platform/agent, as that is our speciality! We cannot dedicate the time, love, and expertise to a full-fledged scalable web service that implements the Remote Settings. We CAN promote the community in any way possible to create an integration project that does!

**Comment by kdt-scc** [comment]
I agree with much of what @zenfish is saying, and when I wrote the readme for the Windmill project, part of my goal was to serve as the missing manual for how to do enrollment. I haven't looked at the PR yet to see what improvements have been suggested, but here is what I have in Windmill for configuring osquery https://github.com/heroku/windmill#configuring-osqueryd

It's a lot of little things, like that the tls_hostname shouldn't have the https on the front or that the endpoints should not be full URLs. A lot of the configuration that is listed there came from reading source code, or doing `select * from osquery_flags` in osqueryi.

**Comment by blackfist** [comment]
oh crud, the above comment was posted using the wrong github login. That was actually me that said that.

**Comment by theopolis** [comment]
@blackfist, that section is super valuable, I'll update #1551 with those notes. We can also link to Windmill as an example implementation from RTD, as we do with Kibana, ElasticSearch, Fluentd, and Splunk for logging/aggregating.

**Comment by theopolis** [comment]
Updated! Thanks all for the help!
