### ISSUE TITLE
Darwin naming: as per scutil terminology, LocalHostName and ComputerName

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#1546]
The `system_info`'s hostname entry is accurate in the traditional sense, but admins may want to know the other two pieces of naming criteria services may use (LocalHostName for bonjour/zeroIPconf discovery, and ComputerName for Apple Remote Desktop-style 'friendly' naming). This is usually retrieved with `scutil --get` and the other two name types, e.g.:  

```
odmit62:~ abanks$ scutil --get ComputerName
bar
odmit62:~ abanks$ scutil --get LocalHostName
foo
```

(And obviously I'm using the default prompt, which includes that distinct hostname)

**Comment by marpaia** [comment]
```
[marpaia-mbp] ~ osqueryi
osquery - being built, with love, at Facebook
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Using a virtual database. Need help, type '.help'
osquery> .mode line
osquery> .all system_info
          hostname = marpaia-mbp.dhcp.thefacebook.com
              uuid = XXXXX
        cpu_serial = XXXXXX
          cpu_type = x86_64h
       cpu_subtype = Intel x86-64h Haswell
         cpu_brand = Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
cpu_physical_cores = 4
 cpu_logical_cores = 8
   physical_memory = 17179869184
    hardware_model = MacBookPro11,2
osquery> .exit
[marpaia-mbp] ~ scutil --get LocalHostName
marpaia-mbp
[marpaia-mbp] ~ scutil --get ComputerName
marpaia-mbp
[marpaia-mbp] ~
```

It seems like both of those attributes can be extrapolated from the hostname column in system_info, no?

**Comment by arubdesu** [comment]
Nope, these are disparate values in the system - they just happen to be the same on your laptop.
You can verify, to see the results I have in clipping above, by overriding the different values with `scutil --set`or using the Sharing pane of sysprefs to override both Local- and  Computer- at once.

**Comment by theopolis** [comment]
Done! Now you have `computer_name` and `hostname` fields within `system_info`!

**Comment by arubdesu** [comment]
Er, so that's the Apple Remote Desktop 'friendly' name done... but the .local/zeroconfIP/MDNS/bonjour name is still enroute?
```
osquery> select * from system_info;
          hostname = odmit17
              uuid = xxxx
          cpu_type = x86_64h
       cpu_subtype = Intel x86-64h Haswell
         cpu_brand = Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
cpu_physical_cores = 2
 cpu_logical_cores = 4
   physical_memory = 17179869184
    hardware_model = MacBookPro11,1
   hardware_serial = xxxx
     computer_name = bar
```
```
$ sudo scutil --get LocalHostName
foo
```

**Comment by arubdesu** [comment]
Hey, doubling back to tidy this up. For Darwin, to get this value using system frameworks over the pyobjc bridge, it's super-straightforward:
```py
#!/usr/bin/python
from SystemConfiguration import SCDynamicStoreCreate, SCDynamicStoreCopyValue
net_config = SCDynamicStoreCreate(None, "net", None, None)
sysconfig = SCDynamicStoreCopyValue(net_config, "Setup:/System")
mutatable = dict(sysconfig)
print mutatable['ComputerName']
```

Please consider re-opening this issue/implementing this lookup so this value can be added to the `system_info` table on Darwin.
