### ISSUE TITLE
NTP server/timezone not included in time table

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#1547]
It's a big pain in the neck if the NTP service is off, or if for whatever reason it hasn't been updating, and when folks travel it's good to know what time zone the computer thinks its in.

**Comment by marpaia** [comment]
good call, tracking in #619.

**Comment by dernorberto** [comment]
Hello. I realised that the "NTP server" part is not included in the table. Would a new request be suitable or can this one be reopened?

**Comment by directionless** [comment]
Hi @dernorberto, I don't believe osquery has an NTP table at this time. Osquery is an volunteer project, and if that is work you're interested in contributing, I'd love to talk more. But simply reopening the ticket will not cause work to happen.

**Comment by dernorberto** [comment]
> Hi @dernorberto, I don't believe osquery has an NTP table at this time. Osquery is an volunteer project, and if that is work you're interested in contributing, I'd love to talk more. But simply reopening the ticket will not cause work to happen.

fair point! I'll have a look at osquery code to try to understand it, and if I feel I can help, i'll open a PR:)
