### ISSUE TITLE
Profiling without building from source?

### ISSUE THREAD

**Issue by PickmanSec** [facebook/osquery#1555]
I would like to do some profiling of some queries for speed. I noticed that if one of your queries fails to finish due to a timeout, it appears to stop running the rest of the queries as well(I will create a separate issue for this). I would like to be able to get some performance impacts out-of-band from the queries and not have to use profile.py since it expects to be used from a built-from-source osquery.

**Comment by marpaia** [comment]
The most effective way to test the performance of a schedule is via the profile tool which requires you to have built osquery: http://osquery.readthedocs.org/en/stable/deployment/performance-safety/#testing-query-performance

To test the execution performance of queries live, in production, you can set the "enable_monitor" flag. Then, when you query [osquery_schedule](https://osquery.io/docs/tables/#osquery_schedule), the table will be populated with performance metrics about each query.

I suggest doing both. Profile your config to make sure it's not going to blow things up, then persistently monitor your queries performance to ensure they perform as expected.
