### ISSUE TITLE
profile.py not working with config

### ISSUE THREAD

**Issue by PickmanSec** [facebook/osquery#1563]
If I run profile.py with the example config it throws an error.

./tools/profile.py --config /var/osquery/osquery.example.conf
Cannot open/parse config: Expecting property name: line 2 column 3 (char 4)

**Comment by PickmanSec** [comment]
Apparently profile.py can not handle comments. If you remove the comments it works.

**Comment by theopolis** [comment]
Yeah, the comments in the config are a liberal use of `boost::property_tree`'s acceptance of non-standard JSON. I think the comments are helpful, we could move all of them to sh-style comments and change the python script to strip them. Thoughts?

**Comment by PickmanSec** [comment]
Just parse out comments before json.loads.

**Comment by PickmanSec** [comment]
Also I have made a utils.py that can hand the comment type inside of the json config.
