### ISSUE TITLE
profile.py does not work with packs

### ISSUE THREAD

**Issue by PickmanSec** [facebook/osquery#1564]
./tools/profile.py --config /Users/pickman/Downloads/osquery.example2.conf
Profiling query: SELECT * FROM osquery_info
 D:0  C:0  M:0  F:0  U:0  info (1/1): duration: 0.516358852386 cpu_time: 0.023541636 memory: 6057984 fds: 5 utilization: 2.2

runs only the sample query.

**Comment by theopolis** [comment]
Yeap! It's not that robust of a script, would you mind updating it?

**Comment by PickmanSec** [comment]
Yep, almost done with a version that can handle comments.

**Comment by PickmanSec** [comment]
fine.
