### ISSUE TITLE
OS X's .bash_history may be a FIFO, reads are blocked

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1571]
User-controlled FIFO reads are blocked. This means that `shell_history` will not report data for OS X user's bash history. It possible to allow these reads via a non-default flag setting. It is also possible to whitelist locations expected to be FIFOs and rely on the existing user-control file read max safety controls.

**Comment by sharvilshah** [comment]
`s/linux/os x/` on the label

**Comment by theopolis** [comment]
This issue may just be an artifact of my system. But never-the-less we could do something like:
```cpp
  if (file_size == 0) {
    off_t total_bytes = 0;
    ssize_t part_bytes = 0;
    do {
      auto part = std::string(4096, '\0');
      part_bytes = read(handle.fd, &part[0], 4096);
      if (part_bytes > 0) {
        total_bytes += part_bytes;
        if (total_bytes >= read_max) {
          VLOG(1) << "FIFO file too large";
          return Status(1, "File exceeds read limits");
        }
        content += part.substr(0, part_bytes);
      }
    } while (part_bytes > 0);
  } else {
    content = std::string(file_size, '\0');
    read(handle.fd, &content[0], file_size);
  }
```

This is not tested, but could implement reads up to the read max for FIFOs.
