### ISSUE TITLE
Installed apps ospack  mislabeled

### ISSUE THREAD

**Issue by PickmanSec** [facebook/osquery#1595]
Installed apps table does not show installed apps but, apps that are located in several different locations. I would supposed changing the name for the osquery pack in incident response to "apps located in several different places". This was of course a joke but, this name does not accurately detail what the output of the query is.

**Comment by theopolis** [comment]
But it does! App bundles do not need to be in /Apps, this table is actually backed by OSX LaunchServices. So those bunch of locations is not our doing O.o, haha!
