### ISSUE TITLE
JSON Pack parsing error

### ISSUE THREAD

**Issue by raphdev** [facebook/osquery#1596]
When reading JSON packs, the `initialize` function expects the parsed JSON to contain the "query" key. If it doesn't exist, the uncaught exception will result in SIGABRT.

This can be fixed by simply moving the call to `initialize` inside the try/catch in the Pack constructor, and catching the specific exception and/or checking if this key exists first. The latter may be preferable in cases where you don't want an exception context, such as if Pack is intended to be reused to parse a set of incoming distributed queries, for example.

**Comment by theopolis** [comment]
@raphdev, if you have a change, please retest this, but #1599 should have fixed the uncaught exception. Thanks!
