### ISSUE TITLE
adding file_paths always results in file access monitoring

### ISSUE THREAD

**Issue by lexelby** [facebook/osquery#1600]
We're attempting to use the file_events table as a simple form of file integrity monitoring (FIM).  Here's a basic FIM config:

```json
{
  "schedule": {
    "file_events": {
      "query": "select * from file_events;",
      "interval": 900,
      "removed":false
    }
  },
  "file_paths": {
    "configuration": [
      "/etc/%%"
      ],
    "binaries": [
      "/usr/bin/%%",
      "/usr/sbin/%%",
      "/bin/%%",
      "/sbin/%%",
      "/usr/local/bin/%%",
      "/usr/local/sbin/%%",
      "/opt/bin/%%",
      "/opt/sbin/%%"
    ],
    "ssh_keys": [
        "/home/%/.ssh/authorized_keys"
      ]
  }
}
```

The goal here is to notice any changes/deletions/additions in these directories and calculate new hashes when they happen, which should at a baseline be quite rare.  However, when we run this config with version 1.5.3, we see far more CPU usage than expected, and it's very easy to DoS the kernel (high system time) by, for example, reading all files in /usr/bin.

Verbose logging gives a clue:

```
Oct 27 17:59:08.062702 osqueryd[31126]: severity=0 location=options.cpp:50 message=Verbose logging enabled by config option
Oct 27 17:59:08.062984 osqueryd[31126]: severity=0 location=db_handle.cpp:124 message=Opening RocksDB handle: /var/osquery/osquery.db
Oct 27 17:59:08.063162 osqueryd[31126]: severity=0 location=interface.cpp:220 message=Extension manager service starting: /var/osquery/osquery.em
Oct 27 17:59:08.063635 osqueryd[31126]: severity=0 location=events.cpp:564 message=Event publisher failed setup: kernel: Cannot access /dev/osquery
Oct 27 17:59:08.064101 osqueryd[31126]: severity=0 location=file_access_events.cpp:45 message=Added kernel listener to: /usr/bin/
Oct 27 17:59:08.064496 osqueryd[31126]: severity=0 location=file_access_events.cpp:45 message=Added kernel listener to: /usr/sbin/
Oct 27 17:59:08.064961 osqueryd[31126]: severity=0 location=file_access_events.cpp:45 message=Added kernel listener to: /bin/
Oct 27 17:59:08.065340 osqueryd[31126]: severity=0 location=file_access_events.cpp:45 message=Added kernel listener to: /sbin/
Oct 27 17:59:08.065754 osqueryd[31126]: severity=0 location=file_access_events.cpp:45 message=Added kernel listener to: /usr/local/bin/
Oct 27 17:59:08.066162 osqueryd[31126]: severity=0 location=file_access_events.cpp:45 message=Added kernel listener to: /usr/local/sbin/
Oct 27 17:59:08.066586 osqueryd[31126]: severity=0 location=file_access_events.cpp:45 message=Added kernel listener to: /opt/bin/
Oct 27 17:59:08.066979 osqueryd[31126]: severity=0 location=file_access_events.cpp:45 message=Added kernel listener to: /opt/sbin/
Oct 27 17:59:08.067417 osqueryd[31126]: severity=0 location=file_access_events.cpp:45 message=Added kernel listener to: /etc/
Oct 27 17:59:08.067800 osqueryd[31126]: severity=0 location=file_access_events.cpp:45 message=Added kernel listener to: /home/
Oct 27 17:59:08.068193 osqueryd[31126]: severity=0 location=file_events.cpp:58 message=Added listener to: /usr/bin/**
```

Any time you add file_paths to your config, inotify watchers will get set up not only for modification, but for access.  This is disastrous for performance when used on /usr/bin et al. because they're constantly being accessed.

The underlying reason is that inotify watcher setup is entirely separate in the code from use of the `file_events` or `file_access_events` tables.  There's no way to just watch for modifications.  This line registers the file access watcher plugin which is initialized at startup:

https://github.com/facebook/osquery/blob/master/osquery/tables/events/file_access_events.cpp#L28

Either these plugins should detect whether they're needed and only set up their watchers appropriately (perhaps by examining tables used in queries?) or there should be a method of disabling file access monitoring.  Without this we can't use osquery in production.

**Comment by theopolis** [comment]
Absolutely! We can modify `file_paths` to assume a default of just watching for modifications. Then for backwards compatibility we can add `file_path_accesses` as the sets of paths for watching for accesses.

**Comment by blackfist** [comment]
That would be sooooo helpful, @theopolis. If we could even get that change into master we could move forward with our deployment without having to wait for an official release. I'll volunteer to update the documentation on FIM if you get this code rolled out.

**Comment by theopolis** [comment]
You got it, on it right now!

**Comment by lexelby** [comment]
Awesome!! And argh, of course, why didn't I think of that solution? I was stuck trying to add a CLI_FLAG, but I think that doesn't work in tables or something.  

I'll be available first thing tomorrow morning to build and test.  Thanks for jumping in this!

**Comment by blackfist** [comment]
@theopolis I just sent you an email. I wanted to comment here so you would know that email is legit.

**Comment by theopolis** [comment]
Let me know if this is still kicking up too much CPU, if so we can further restrict what the default "file_paths" events actions are.
