### ISSUE TITLE
file_locations blows up on recursive symlinks

### ISSUE THREAD

**Issue by lexelby** [facebook/osquery#1611]
Apparently this is standard on debian, from the `x11-common` package:

```
# ls -l /usr/bin/X11
lrwxrwxrwx 1 root root 1 Dec 10  2014 /usr/bin/X11 -> .
```

Any configuration with `file_locations` containing `/usr/bin` goes into infinite recursion in `inotify.cpp:addMonitor()` and eventually blows the stack and segfaults.

**Comment by lexelby** [comment]
@theopolis apparently #1600 was a red herring.

I'm working on a fix, but my C++ is quite rusty, so any help would be appreciated.  This is currently blocking us from using osquery for FIM.

**Comment by sharvilshah** [comment]
So, there is a max recursive glob limit set here: https://github.com/facebook/osquery/blob/master/osquery/filesystem/filesystem.cpp#L39
I don't know if the [inotify event publisher](https://github.com/facebook/osquery/blob/master/osquery/events/linux/inotify.cpp) uses those filesystem.cpp APIs during path discovery.  

One quick test would be to lower that number to something like 2 or 3 on a local build and see if it blows the stack again.

**Comment by lexelby** [comment]
Oh!!  I hadn't even realized the real problem: the code is trying to do the recursion twice.  There's this:

https://github.com/facebook/osquery/blob/master/osquery/events/linux/inotify.cpp#L247

But `listDirectoriesInDirectory` can already do recursion, because it ultimately calls `genGlobs` in filesystem.cpp.

**Comment by lexelby** [comment]
Based on the logic here: https://github.com/facebook/osquery/blob/master/osquery/events/linux/inotify.cpp#L54

I think the solution is to rewrite `addMonitor` to add `/**` to the end of the path and use filesytem.cpp's `listInAbsoluteDirectory` with GLOB_FOLDERS.  We can't use `listDirectoriesInDirectory` because it explicitly breaks `**` recursive globbing by tacking on `/*` at the end of the path.  Once we do that, `addMonitor` shouldn't recurse.

**Comment by lexelby** [comment]
It's probably also worth running all paths through boost's `fs::canonical` because `genGlobs` will generate 64 entries like `/usr/bin/X11`, `/usr/bin/X11/X11`, `/usr/bin/X11/X11/X11`, etc, which will needlessly bloat the inotify watch list.
