### ISSUE TITLE
shell_history only shows user roots shell history

### ISSUE THREAD

**Issue by PickmanSec** [facebook/osquery#1615]
Shell_history has some code that limits is ability to gather histories from other users. I am not sure why that decision was made but I wanted to run it by people before I do a pull request. 

So the offending line has a where clause on where it only returns the user id of the user running osquery.

Shell_history.cpp in function genShellHistory:
```
QueryData users;
  if (!context.constraints["username"].exists(EQUALS)) {
    users =
```
:wink: SQL::selectAllFrom("users", "uid", EQUALS, std::to_string(getuid()));:wink:
```
  } else { 
...
```

My Fix:

```
QueryData genShellHistory(QueryContext& context) {
  QueryData results;

  // Select only the home directory for this user.
  QueryData users;
    users =
        SQL::selectAllFrom("users");
    auto usernames = context.constraints["username"].getAll(EQUALS);
    for (const auto& username : usernames) {
      // Use a predicated select all for each user.
      auto user = SQL::selectAllFrom("users", "username", EQUALS, username);
      users.insert(users.end(), user.begin(), user.end());
    }
```

**Comment by theopolis** [comment]
I need to review the table implementation to be sure, but IIRC, we wanted to be careful not to read several potentially large files from home directories that may or may not be NFS mounted. BUT, that "not-traversing-auto-mounts" problem should definitely be solved using a flag and some `readFile` or `path` logic more globally.

If you want to grab history from all users you can:
```sql
select username, count(*) from users join shell_history using (username) group by username;
```

NB: I have my history limit configured for 300,000 lines, so parsing the set of histories in for my user takes a bit of time and spikes the CPU momentarily. I'd expect a few users to do the same, so this query may fail to complete, I'm trying to figure out what to do in these cases.

**Comment by PickmanSec** [comment]
So, I can make add an extra config flag that says something like "--traverse" "traverse as all users" and add an extra check to affected tables, that checks if the flag is set.

**Comment by theopolis** [comment]
Hey @PickmanSec, the way 1.6.1 is implemented, no `--traverse` is used. The way it is now includes the related packs/docs that attempt to make it clear you need to add some `JOIN users`. Let me know if you're still working on a `--traverse` that simplifies that.

**Comment by PickmanSec** [comment]
Sorry, for the slow response, got busy :cry:  . I am working on a flag system that will trigger on a per table basis. I should be able to have this setup on trial for the shell_history table on Saturday. If you have any suggestions for implementation I would like to hear them.

**Comment by theopolis** [comment]
Cool, I'll take a look when you post a PR!

**Comment by PickmanSec** [comment]
`select username,key from users join known_hosts using (uid) group by username;`
Only returns one known_host key per user.

**Comment by theopolis** [comment]
What are you trying to achieve? A `group by` is an aggregation step. You should expect to have one result row given your column selection within the aggregation.

**Comment by PickmanSec** [comment]
Yep, my bad. I took you sql and didn't read it. It's all good now. `select username,key from users join known_hosts using (uid);`

**Comment by theopolis** [comment]
Any status on the `--traverse` feature :question:

**Comment by zwass** [comment]
@PickmanSec Do you still have plans to work on this?

**Comment by theopolis** [comment]
We now have warnings when using these tables as `root` without `JOIN`ing from `users`: https://github.com/facebook/osquery/blob/master/osquery/sql/virtual_table.cpp#L500
