### ISSUE TITLE
Broken link in Creating New Tables documentation page

### ISSUE THREAD

**Issue by thedrow** [facebook/osquery#1627]
The documentation [here](https://osquery.readthedocs.org/en/stable/development/creating-tables/#sql-data-types) links to https://github.com/facebook/osquery/blob/master/include/osquery/database/results.h which doesn't exist anymore.

**Comment by sharvilshah** [comment]
Thanks, the correct/updated link is: https://github.com/facebook/osquery/blob/master/include/osquery/database.h
