### ISSUE TITLE
RocksDB initialize failed: RW, RO, and no database access errors and logs

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1629]
RocksDB is the default (only) backing store for osquery. It does not support multiple processes opening handles to the on-disk database location. 

When an `osqueryi` process starts, it tries to open a RW handle to `~/.osquery/shell.db`, if another shell is running this will fail. The new (second) shell will continue without RocksDB support and thus disable publishers and persistent storage. This makes sense as in most cases, usually non-debug, publishers are not needed within the shell. Eventually they may be disabled completely on default.

When an `osqueryd` process starts it checks a process mutex, called `--pidfile` and if no file exists or the pid is "stale" it will run and attempt to open a RW handle to `--database_path`. If this RW handle fails, the daemon will stop. The daemon MUST have a RW handle.

You will see the following line in your error log:
```
osqueryd initialize failed: Could not open RocksDB
```

Possible reasons for a failed handle:
- There is another daemon running with the same `--database_path`.
- The `--database_path` (is a folder) was previously created and has restrictive ownership/mode such that the new process cannot create or write files.
- An intermediate directory does not exist.

**Comment by sharvilshah** [comment]
Thanks, this is helpful. Would also be cool to have `RLOG` reference in `db_handle`.

**Comment by theopolis** [comment]
That's why it exists. ;)
