### ISSUE TITLE
OS X: "homebrew_packages" fails with non-standard Homebrew location

### ISSUE THREAD

**Issue by the-real-tokai** [facebook/osquery#1653]
The `homebrew_packages` table is not populated with entries when *Homebrew* is not installed in the default location. E.g. I opted to separate my *Homebrew* installation into a dedicated subdirectory rather than placing it directly into the commonly recommended `/usr/local` location.

```
$ brew list | wc -l
     114
$ brew --cellar
/usr/local/homebrew/Cellar
```

```
osquery> .all homebrew_packages
osquery> 
```

It seems that osquery only checks the most common `Cellar` location (`/usr/local/Cellar`) rather than properly querying `brew` for the actual `Cellar` location (which might differ from `/usr/local/Cellar` depending on the user's installation/ environment). While osquery is running this can be verified with something like this:

```
$ sudo fs_usage | fgrep osquery
...
17:17:26  stat64            /usr/local/Cellar                                                                0.000007   osqueryi    
...
```

(That's not the path where my Homebrew `Cellar`is located, obviously. :smile: )

**Comment by theopolis** [comment]
Correct! @the-real-tokai, would you mind fixing the table implementation? I'm assuming brew is writing the location of the `Cellar` directory to a well-known file/plist? Can we discover and replace the static [`/usr/local/Cellar`](https://github.com/facebook/osquery/blob/master/osquery/tables/system/darwin/homebrew_packages.cpp#L26) with this method? Unfortunately we cannot shell out to run `brew --cellar`.

**Comment by the-real-tokai** [comment]
The `brew` command script self-discovers this basing on its own resolved script path, see the sh wrapper script: https://github.com/Homebrew/homebrew/blob/master/bin/brew

So there's no config file really. The first `brew` in the `$PATH` is called and resolves its own base location. This `brew` might only be available to a single user (e.g. with an installation of *Homebrew* in the user's home dir, f.ex.). I guess, this somewhat makes it tricky for osquery to fetch this information in a proper and reliable way?

Checking the target location of a possibly existing `brew` link in `/usr/local/bin` would make it a bit more reliable than it is currently. At least it could fix detecting the `Cellar` location of globally (for all user's of the system) available *Homebrew* installations.

**Comment by theopolis** [comment]
Thanks for the info and research! I agree, doing a `readlink` on `/usr/local/bin/brew` sounds much better than assuming `/usr/local/Cellar`. In most cases we want to know about the system-available brew installation (to check for out of date/vulnerable packages). So if folks have installed brew locally to their home directory and likewise installed brew into `~/bin/`, they are on their own for now.

Would you mind taking this @the-real-tokai?

**Comment by the-real-tokai** [comment]
@theopolis "Taking it" as "implementing it"? I have to admit I'm not very (as in not at all) acquainted with the `osquery` codebase (albeit it looks rather readable) and especially not `C++`. I rather like `C` (my favourite programming language), but I always dodged the `++` headache. :smile:

Another thing that scares me is the big disk space requirement (like 1 GiB?) for the `boost` stuff (one of those madness++ thingies? :sweat_smile: ). That's the reason I install osquery via the binary packages from the official website and not via Homebrew (albeit that takes a bit more effort to keep track of the updates.) :wink:

I'm just an interested `osquery` user, so to speak, not a developer. Sorry! :smiley:

**Comment by theopolis** [comment]
Ok no worries!

**Comment by the-real-tokai** [comment]
I can confirm that it now works properly (for me) as expected. :+1: :smile: 

```
$ osqueryi --version
osqueryi version 1.6.1
$ osqueryi
osquery - being built, with love, at Facebook
...
Using a virtual database. Need help, type '.help'
osquery> .all homebrew_packages
+-----------------------+---------------------------------------------------+--------------+
| name                  | path                                              | version      |
+-----------------------+---------------------------------------------------+--------------+
| autoconf              | /usr/local/homebrew/Cellar/autoconf/              | 2.69         |
| automake              | /usr/local/homebrew/Cellar/automake/              | 1.15         |
| cairo                 | /usr/local/homebrew/Cellar/cairo/                 | 1.14.4       |
| calc                  | /usr/local/homebrew/Cellar/calc/                  | 2.12.5.0     |

...

| openssl               | /usr/local/homebrew/Cellar/openssl/               | 1.0.2e       |
| optipng               | /usr/local/homebrew/Cellar/optipng/               | 0.7.5        |

...

| wget                  | /usr/local/homebrew/Cellar/wget/                  | 1.17         |
| xdelta                | /usr/local/homebrew/Cellar/xdelta/                | 3.0.10       |
| xz                    | /usr/local/homebrew/Cellar/xz/                    | 5.2.2        |
| zeromq                | /usr/local/homebrew/Cellar/zeromq/                | 4.1.3        |
+-----------------------+---------------------------------------------------+--------------+
```

Thanks for the bugfix!

**Comment by theopolis** [comment]
yay! :dancer: thanks for the update!
