### ISSUE TITLE
File Integrity Monitoring and Offline Attacks

### ISSUE THREAD

**Issue by eoinmiller-sfdc** [facebook/osquery#1656]
We noticed that if osquery is performing file integrity monitoring on a host that is attacked offline no logs are created when the victim host is brought back up. Would it be possible to keep the last accessed and last modified dates of all monitored files in a table that is checked against when osqueryd is started?

**Comment by theopolis** [comment]
This is a great suggestion. When the FIM-based tables are notified by inotify on Linux and fseventsd on OS X we can keep a lookup table in RocksDB of the path + mtimes (ctime, mtime, atime). When the osqueryd daemon is restarted, or after a machine reboot, that lookup table can be consulted by the `file_events` table subscriber and emit rows for any path that doesn't match.

**Comment by mmb** [comment]
We were wondering about this to see if an attacker could kill osquery, modify some files, and then restart osquery. Based on our understanding osquery wouldn't generate any alerts if this happened.

If there were a database that persisted when osquery was not running it could help but if an attacker can kill osquery they could probably also delete this database.

**Comment by theopolis** [comment]
Right, if the concern is missed events because the daemon was down because of updates or some sort of failure then a DB tracking hashes or mtimes would assist. If the goal is to add state to defend against malfeasance we'll be out of luck.

**Comment by theopolis** [comment]
We haven't had much discussion here, and fighting against disabling the daemon has become a non-goal for the project. If anyone has energy here and wants to add features please let us know!
