### ISSUE TITLE
on_disk should probably get renamed to file_exists

### ISSUE THREAD

**Issue by cdown** [facebook/osquery#1661]
on_disk just does `osquery::pathExists`, we should rename it to `file_exists` or `path_exists` or something.

**Comment by theopolis** [comment]
Ok, I've thought a bit about this and think that "for now" `on_disk` makes sense. If you consider "virtual" or "meta" disks as, disks, then it's not sooo bad. Even if there's no spinning or NAND cycling backing the bits, they are still organized by the OS into images, volumes, and file systems. The biggest reason for being contempt with this stretch of definition is the lack of ability to deprecate column names.

I'm going to add this change to our working set of requested API changes (the master task). We'll work a bit harder on getting aliases or deprecation-style capabilities for the virtual table implementations. This ability will eventually stem from within changes to the SQLite APIs. I'm pretty confident this is achievable within the next half.
