### ISSUE TITLE
FreeBSD euid is actually suid?

### ISSUE THREAD

**Issue by cdown** [facebook/osquery#1662]
I notice the following line in osquery/tables/system/freebsd/processes.cpp:

```
r["euid"] = INTEGER(proc->ki_svuid);
```

This seems wrong, since `ki_svuid` is actually the saved user ID, unless I'm missing something. It probably should be `proc->ki_uid`

**Comment by cdown** [comment]
Well, SIGAR has this line in some source code [here](https://github.com/hyperic/sigar/blob/18c2856f75ee7ed26e209b3820bc05913c88f4a7/src/os/darwin/darwin_sigar.c#L157), so maybe this somehow makes some sense?

```
#define KI_EUID kp_eproc.e_pcred.p_svuid
```

I'm not going to pretend I understand what's going on, though.

**Comment by theopolis** [comment]
@wxsBSD, ping!

**Comment by cdown** [comment]
talked to @wxsBSD in person and he thinks its just a typo. We looked at how procstat_cred (https://github.com/freebsd/freebsd/blob/0f2211c30ded7871b441bfaa1647843f1b4fd0c2/usr.bin/procstat/procstat_cred.c#L46-L67) does it, and it seems like they use kv_uid as EUID.

I'll put up a patch to fix it then. Thanks for your help Wes!
