### ISSUE TITLE
feature request: attempt re-enroll if node_invalid

### ISSUE THREAD

**Issue by blackfist** [facebook/osquery#1676]
If my understanding is correct, when an osquery endpoint receives a node_invalid message from an https server (perhaps running windmill) it will just go on with life and try again later. So if our database got nuked somehow then we would have thousands of servers that can't pull their config. There's also no easy migration path to go from one server to another.

It would be nice if there was a feature flag along the lines of --re-enroll-after-fails = n. If not set then the current behavior persists. But if set, then after receiving `node_invalid` n times the server will attempt to re-enroll. That way, migrating to a new server is as easy as a DNS change, and a puking database doesn't require me to have to log into thousands of machines and delete the rocksdb.

**Comment by lexelby** [comment]
My name is Lex and I support this issue.

**Comment by theopolis** [comment]
Are there any negative effects to making this the default behavior? And not requiring an additional flag?

**Comment by lexelby** [comment]
In practice, I think not.  The reason we might not want to make this the default is that if a node re-enrolls erroneously, there will then be a duplicate entry for that node in windmill (or whatever other server).  That may be undesirable to some users.

My opinion is that it makes sense to err on the side of re-establishing contact with the server whenever possible so as to avoid a situation where the administrator has to fix thousands of machines, even if that means possible cleanup in windmill.  Windmill's UI could be changed to make this kind of cleanup easy (automatic?) if this becomes an ongoing problem, but I doubt it will.

**Comment by blackfist** [comment]
I suppose if I were a super 1337 haxor I could poison DNS so that your endpoints start trying to enroll with a different server. After receiving some failures I could get the endpoint to re-enroll with my malicious host and steal the enroll_secret. I could also send malicious configs to the servers.

HOWEVER, if I can poison DNS then I already can send a malicious config. When the endpoint asks for a config my server doesn't have to verify anything and could just send it along. And stealing my enroll_secret isn't really a big deal unless I use that for other things too. So in practice, I don't know that there is a big security risk if this is the default behavior.

**Comment by adrianmacneil** [comment]
What about allowing the server to request this behavior? By returning
node_invalid, reenroll: true. This would mean you won't get any nodes
accidentally changing up their node key due to a temporary server-side
issue (e.g. node database offline).

**Comment by sroberts** [comment]
I've definitely run into similar situations as well. I'm sort of split on having this initiated via the server or the client, both have flaws and positives. My gut still says it should stay with the client, since a change is still going to need to be initiated on the client either way. Either way this would be really valuable as osquery endpoints start to have a lifecycle that needs managed.

**Comment by blackfist** [comment]
Also, all of the DNS poisoning stuff I talked about above can be prevented by using the tls certs features. So no, I can't think of anything bad that would come from having this be the default behavior.

**Comment by blackfist** [comment]
So did we decide that this is safe from a security perspective? I mostly just wanted to bump the thread.

**Comment by theopolis** [comment]
Here are some mostly unorganized thoughts, some of this is captured in the documentation on [Remote Settings](http://osquery.readthedocs.org/en/stable/deployment/remote/):

1. In all cases the remote server is authenticated.
 There is no way to "skip" the TLS server authentication with the distributed binary. Spoofing DNS, MITMing the network, etc, only affects reliability and potentially leads to DoSing your clients. Normal stuff, no practical or needed way around this. If you want to restrict (poor man's pin) the certificate store, the `--tls_server_certs` [option](http://osquery.readthedocs.org/en/stable/installation/cli-flags/#remote-settings-optional-for-configloggerdistributed-flags) is for you. 

2. The simple client-authentication method of a shared secret for enrollment has a bit of attack surface. 
 If your shared secret (enrollment secret) is leaked/compromised then an attacker can "spoof" new enrollments. This has two immediate negative implications: (A) your logging collector can be DoSed with tons of logs, (B) if you are not careful with aggregating/identifying nodes this can lead to confusion and logical masquerading if a duplicate hostname is spoofed.

 B can be avoided if you use the negotiated `node_key` as the host identifier. It can also be avoided if you use the UUID identifier approach with `--host_identifier=uuid`. On OS X this uses the hardware UUID (not guessable, but also not changeable), and on Linux a persistent randomly-generated UUID stored in RocksDB. Essentially, hostname is guessable, observable, and in this case spoofable, be careful if using it as a unique identifier.

 With the simple shared-secret model the important note is a compromise of your shared secret (enroll key) does NOT mean attackers can masquerade as existing hosts. They can only enroll new hosts. The "new enrollment" problem can be solved on the server implementation with an "enroll approval" process or something similar that puts a human or context/decoration factor into the loop.

 3. If you want to avoid a shared secret, TLS [client authentication](http://osquery.readthedocs.org/en/stable/installation/cli-flags/#remote-settings-optional-for-configloggerdistributed-flags) works too.

Ok, so now for **re-enrollment**!

The guarantee made in B w.r.t. not being able to masquerade as a client after compromising the infrastructure `enroll_key` *goes out the window* in some scenarios. I understand the need for re-enrollment and understand that the need does not change if we edit the logic for storing the node key.

Let's liken the `node_key` stored in RocksDB to the SSHd host private key. If you blow your host's SSHd keying material away, every existing cached known host's file is going to complain. You'll face the well known key distribution/rotation problem. Loosing a host's `node_key` is equivalent. And the proper solution is equally hard. What you observe in the land of osquery remote APIs is the node establishing a new `node_key` and the server having to implement some correlation to reasonably identify this is not a masquerade/spoofing attempt. I would love to do a deeper dive into how this is possible, but let's table that for a different issue or venue.

The issue at hand is the server losing the equivalent of an SSH client's `known_hosts` cache. In this case the client usually consults an OOB lookup or blindly accepts the advertised hash. The scenario here is inverted but the concept holds-- in that the server had unintentionally and 'unrecoverably' lost the set of node keys. I would propose to approaches, (1) the server includes some magic OOB lookup/verification of the assets it manages *or includes a human* or (2) accepts its fate and allows nodes to re-enroll with reckless abandon. In both cases this is a choice made by the server and the client should willingly accept.

Remember that the client has unconditionally authenticated the server, if the server says "bad node key" the client should willingly ask "what do" and obey. We can translate that into either proposed option of extending the remote APIs to include an optional `{"re-enroll": true}` that forces the client to re-enroll or have the client's default behavior when a `node_invalid` is received to retry the enrollment flow.

So, in any case (from what I can tell) the security/attack surface does not change by allowing nodes to re-enroll. Let's go with the option that makes the most sense and is easiest to grok. IMO that's modifying the client behavior to retry the enrollment process on failure.

**Comment by lexelby** [comment]
I'm +1 on having the client retry, perhaps with an option to disable that.

I would note that using enroll_key to reliably protect against masquerading isn't completely secure.  There's nothing to stop the masquerader from enrolling BEFORE the host they're masquerading, thus confusing matters even more.  IMO we gain more by re-enrollment than we lose in protection against masquerading.  If someone really cares about masquerading, they can use client certificates to positively identify nodes and perhaps even issue the same enrollment secret back to a re-enrolling node.

**Comment by theopolis** [comment]
Agreed 100%, so current plan is default re-enroll if an invalid response is received with a `--disable_reenroll=false` option that can be set to turn it off.

**Comment by adrianmacneil** [comment]
Perhaps this is what you meant, but I think it's important to distinguish between an invalid response, and a `node_invalid` response. I suggest only reenrolling if an HTTP 200 response is received with the body `{"node_invalid": true}`. Otherwise, it's possible that a temporary server-side error would lead to a whole bunch of nodes reenrolling and potentially losing their current state (if the node_key was being used as a primary identifier).
