### ISSUE TITLE
Remove comments in JSON files for boost 1.59 (ptree removed support)

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1689]
Comments in JSON is non-standard but were still parsed by boost's property tree library. In [boost 1.59](http://www.boost.org/users/history/version_1_59_0.html) this non-standard support is removed. Homebrew already includes 1.59, so there's a little haste around removing the comments we have.

**Comment by andrew-d** [comment]
I will note that having comments to explain what a query does, why it's there, etc. is super-useful.  My vote is actually for keeping these, possibly by including a preprocessor that strips them on load?  [This library](https://github.com/sindresorhus/strip-json-comments) does a cool thing which replaces comments with whitespace, so the error locations (if any) are still correct.

**Comment by andrew-d** [comment]
I ported over the code from the above library to C++ pretty quickly today - see it here: https://github.com/andrew-d/json-strip

I'm pretty busy for the rest of the week, though, so I'm not sure I'll have the time to get to actually putting this in a PR - if anyone else does before me, let me know.  It probably also needs tests - the code was written pretty quickly.

**Comment by marpaia** [comment]
https://xkcd.com/1172/

**Comment by theopolis** [comment]
Although we assume config instantiation and parsing is a rare and potentially expensive event-- if we "only support" hash-style comments then we can greatly simplify the comment stripping logic. It essentially becomes a strip + character compare.

**Comment by marpaia** [comment]
If we want comments for the sake of comments, sure, we can just support # comments.
