### ISSUE TITLE
Feature request: command to make osquery pull config from tls server now

### ISSUE THREAD

**Issue by blackfist** [facebook/osquery#1701]
When you're doing development it can be a pain in the butt to wait for the next pull. It would be cool if there was a command I could run that would make it grab from the tls_server now instead of waiting.

**Comment by lexelby** [comment]
👍

**Comment by theopolis** [comment]
Not sure I follow. :crying_cat_face:

If you have a testing `osqueryd` process, I understand it's tough to keep restarting the process-- but perhaps a lower `--config_tls_refresh` is a good happy medium? The default values is `10 * 60`.

Otherwise, do you mind describing what sort of command would be helpful? If you're HUPing the daemon, why not just start/stop it?

**Comment by blackfist** [comment]
Most of the time I would agree. There's really no command that is going to be more convenient than just restarting the service. But we're running into an issue where we know that restarting causes the osqueryd process to pull from the tls server but normal polling doesn't. At least that's how it appears right now. So we were looking for a troubleshooting tool in this case rather than something that would used regularly.

**Comment by theopolis** [comment]
@blackfist, gotya, so will the other feature request: #1702 + a short refresh time do the trick?

I'm hesitant to add a signals API for doing things like config refreshes (or anything else for that matter). Not that I think it wouldn't be helpful, but it's a bit of work to get correct.

I'm curious if the extensions API allows you to test the config updating. I'll debug the config+update a bit and see if there are any inconsistencies. Will report back about the API and debugging in a few.

**Comment by blackfist** [comment]
I think we can close this out. Now that we figured out what was going on (see #1704) I think that a short refresh time and the ability to dump config would meet our needs just fine.

**Comment by lexelby** [comment]
Yup, I agree.  I would note, though, that a faster refresh time might not suit all users as their windmill server (or equivalent) might not be able to handle the load.
