### ISSUE TITLE
Feature request: ability to dump the running config

### ISSUE THREAD

**Issue by blackfist** [facebook/osquery#1702]
When troubleshooting, it can be handy to know what the running config looks like. But if you're using the `config_plugin=tls` option then there really isn't a way to view that. It would be cool if there was a command I could run that would make osquery dump the running config so I could inspect it.

**Comment by lexelby** [comment]
# 👍

**Comment by lexelby** [comment]
This would help us debug issues with windmill, for example.  I assigned this config and the node pulled its config; did it get the new config?

**Comment by theopolis** [comment]
(possibly related) I use the "synthesized" `config_hash` in `osquery_info` to track the distribution of config updates when using the TLS config plugin.

I'm going to expand this feature request a bit:

- [ ] Provide a dump config option that retrieves the config once, writes to stderr, and exists with the status code similar to `--check_config`. This can be added to the `--check_config` feature, all we need to do is add output to stderr.
- [ ] Allow config plugins to optionally cache the retrieval of config content. This can be added to the API by having Config instances check if the active plugin wants to cache the config. That plugin can then use the cache if retrieval fails.
- [ ] Provide a database dumping option for debugging.

**Comment by blackfist** [comment]
Is the config stored anywhere in it's unaltered form?

**Comment by lexelby** [comment]
I think that's what the second item in the list is about.  It's not currently, but @theopolis would add that capability.

**Comment by blackfist** [comment]
Right. I was just trying to gauge if this might be within my capabilities. But maybe not.

**Comment by theopolis** [comment]
Actually, `--config_check` is going to write to `stdout` since logs and goodies are using up `stderr` already.
