### ISSUE TITLE
Possible Bug: inotify watchers only setup on restart

### ISSUE THREAD

**Issue by blackfist** [facebook/osquery#1704]
We discovered that if an osquery endpoint is pulling configuration from a tls server it will run new scheduled queries but will not set up inotify watchers. So we were sending out a config that would do file integrity monitoring and not seeing any results which resulted in a lot of troubleshooting (see #1701) and wondering if osqueryd even updates on a schedule.

We were able to confirm that it does update, and it will run new queries that it gets, but the inotify watcher stuff wont happen until a reboot occurs.

**Comment by theopolis** [comment]
Confirmed!

**Comment by lexelby** [comment]
Yay!

**Comment by lexelby** [comment]
Our workaround is to restart osqueryd everywhere to roll out this config, but that's obviously a pain and not what one would hope when using windmill :)

**Comment by theopolis** [comment]
Working on this now. It's going to take some time as we need to refactor the pubsub callback API somewhat. Right now there is an implicit assumption that the file categories in the config will never be removed.

**Comment by theopolis** [comment]
It's a bit of code, but this should be implemented in: #1710

**Comment by theopolis** [comment]
@lexelby, @blackfist, if you have an opportunity to test, the "latest" [packages](https://osquery.io/downloads/) should be working with #1710 and a few others. The expected version is 1.6.1-34-g96f5201 or greater.

Starting the daemon or shell with `--verbose` should output to stderr when paths/patterns are added to inotify's watch list.

The basic expectation is that every config update drops all of the watched paths then rebuilds the watch list and restarts the inotify socket. I'd call this a basic or poor-man's approach. Later we'll apply the set difference without affecting the socket select. If you can report this as working and expected I'd be happy to tag a 1.6.2!

**Comment by lexelby** [comment]
Victory!

```
Dec 10 20:01:09.628399 hermes.118211@staging.herokudev.com osqueryd[16069]: severity=0 location=tls.cpp:193 message=TLS/HTTPS POST request to URI: https://osq-staging.herokuapp.com/api/config
Dec 10 20:01:09.734275 hermes.118211@staging.herokudev.com osqueryd[16069]: severity=0 location=file_events.cpp:68 message=Added listener to: /usr/bin/**
```

**Comment by lexelby** [comment]
...and I do see that the next update again dropped and readded the config.  This isn't perfect, because it does allow a brief window of time during which a change could be missed, so we'll be looking forward to the set-difference approach.

**Comment by theopolis** [comment]
Nice! I'm tabling that implementation as a non-blocking like-to-have. As soon as I find some free time it should be a straightforward change.
