### ISSUE TITLE
FIM on linux misses file moves

### ISSUE THREAD

**Issue by lexelby** [facebook/osquery#1720]
We noticed that, e.g. in package installations, we see the CREATED and UPDATED events for, say, `/usr/bin/foo.dpkg-new`, but not the MOVED event for `/usr/bin/foo` when dpkg moves the new file into place.

I believe this is because, while the actual inotify code watches for IN_MOVE, the file_events table's subscriber does not subscribe to IN_MOVE.

**Comment by lexelby** [comment]
I believe this also affects the passwd_changes table.

**Comment by theopolis** [comment]
@lexelby, good find! Do you mind updating: https://github.com/facebook/osquery/blob/master/osquery/tables/events/linux/file_events.cpp#L73 to include `IN_MOVE`. 

Also, I've nixed the `passwd_changes` table(s) as it was mostly exemplary and duplicates what you'd want from managing a `file_paths` set yourself.

**Comment by lexelby** [comment]
yup, PR in progress!

**Comment by lexelby** [comment]
@theopolis any reason we shouldn't just use IN_ALL_EVENTS in file_events.cpp in order to avoid duplicating the list of events?
