### ISSUE TITLE
TLS client-auth enrollment

### ISSUE THREAD

**Issue by sleeper** [facebook/osquery#1733]
While using TLS client-auth enrollment, the documentation is stating that:

 > The TLS server may (...) return blank keys during enrollment and require TLS client authentication for every endpoint request.

However when doing so, `osqueryd` is complaining that [No enrollment key returned from TLS enroll plugin](https://github.com/facebook/osquery/blob/master/osquery/remote/enroll/plugins/tls.cpp#L110)

```
  if (node_secret_key_.size() == 0) {
    return Status(1, "No enrollment key returned from TLS enroll plugin");
  }
```

Anyway the logic of having both a TLS auth-client enrollment (e.g. the client already has a kind of - signed - identifier) and returning it back an identifier (`node_key`) seems redundant.

Would it be possible to have the following logic implemented:

 * if TLS auth-client is detected (e.g `--tls_client_cert` and `--tls_client_key` are part of the `osqueryd` parameters), then automatically disable enrollment (same logic as ```disable_enrollment`)
 * From this point the client cert's subject name can be considered as the `node_key` and then sent in any of the message sent by `osqueryd` (e.g. `config` and `logger`)

**Comment by theopolis** [comment]
Hey @sleeper, I've thought a bit about this and the enrollment phase may be wanted by deployments authenticating with client certificates. For example, the negotiated `node_key` could be a pseudo unique identifier (I use UUIDs actually). What do you think of documenting this a bit more in the remote settings and then asking/encouraging those who don't want to use enrollment to explicitly add `--disable_enrollment` to their config/flags.

**Comment by theopolis** [comment]
Closing this assuming the updated documentation notes are "good enough". The solution is essentially: disable enrollment with `--disable_enrollment` when using TLS client-auth for a simple/easy flow.
