### ISSUE TITLE
Package can't be built for Debian Jessie

### ISSUE THREAD

**Issue by mmichie** [facebook/osquery#1749]
After being able to successfully compile osquery 1.6.3, make packages fails at:

CMakeFiles/packages.dir/build.make:50: recipe for target 'CMakeFiles/packages' failed
make[4]: *** [CMakeFiles/packages] Error 1
CMakeFiles/Makefile2:189: recipe for target 'CMakeFiles/packages.dir/all' failed
make[3]: *** [CMakeFiles/packages.dir/all] Error 2
CMakeFiles/Makefile2:197: recipe for target 'CMakeFiles/packages.dir/rule' failed
make[2]: *** [CMakeFiles/packages.dir/rule] Error 2
Makefile:213: recipe for target 'packages' failed
make[1]: *** [packages] Error 2
Makefile:115: recipe for target 'packages' failed
make: *** [packages] Error 2

$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support/"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by sharvilshah** [comment]
Hi @mmichie,

Currently `make packages` is only supported for [platforms for which CI infra exists](https://github.com/facebook/osquery/blob/master/README.md).

In the meantime, you can use the [`make_linux_package.sh`](https://github.com/facebook/osquery/blob/master/tools/deployment/make_linux_package.sh) script after compiling osquery to manually create the deb package. 

```bash
# fpm ruby gem is needed to use the make package script
$ sudo apt-get install ruby-dev
$ sudo apt-get install rubygems
$ sudo gem install fpm

vagrant@jessie-amd64:/vagrant/tools/deployment$ ./make_linux_package.sh -t deb -i 1.ubuntu -d zlib1g libbz2-1.0 libreadline6 libgcrypt11
[+] copying osquery binaries
[+] copying osquery configurations
[+] creating package
Debian packaging tools generally labels all files in /etc as config files, as mandated by policy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag {:level=>:warn}
Created package {:path=>"/vagrant/tools/deployment/../../build/linux/osquery-1.6.1-85-g360ac54.deb"}
[+] package created at /vagrant/tools/deployment/../../build/linux/osquery-1.6.1-85-g360ac54.deb
```

Feel free to create a pull request for this change, the debian provision file is [`debian.sh`](https://github.com/facebook/osquery/blob/master/tools/provision/debian.sh) and the package dependencies are in [`Packages.cmake`](https://github.com/facebook/osquery/blob/master/CMake/Packages.cmake)

**Comment by theopolis** [comment]
We could support folks building Debian packages themselves with a few tweaks to CMake. Give me a few minutes to check this out.
