### ISSUE TITLE
log level for TLS endpoints

### ISSUE THREAD

**Issue by defunctzombie** [facebook/osquery#1750]
When using the TLS plugin to capture osquery events, I am seeing a lot of HTTP status events and other non-error items. While I could filter these out at the TLS endpoint, my goal is to reduce the amount of data sent over the wire and thus was looking for a way to just turn those off (or better yet just report critical errors). The closest information I could find was in this issue `https://github.com/facebook/osquery/pull/420 but it doesn't seem like this is true for the TLS endpoint. Basically a way to either turn off `info` logging or limit it greatly would help towards cutting down network load on a client.

**Comment by theopolis** [comment]
What log level are you using, there should be no `INFO` level events by default.

If you start your `osqueryi` binary with the flags/configuration equivalent of the daemon you can:
```
osqueryi
osquery> select name, type, default_value, value from osquery_flags where name LIKE 'log%' or name = 'verbose';
+------------------------+--------+-------------------+-------------------+
| name                   | type   | default_value     | value             |
+------------------------+--------+-------------------+-------------------+
| log_result_events      | bool   | true              | true              |
| logger_mode            | int32  | 416               | 416               |
| logger_path            | string | /var/log/osquery/ | /var/log/osquery/ |
| logger_plugin          | string | filesystem        | tls               |
| logger_syslog_facility | int32  | 19                | 19                |
| logger_tls_endpoint    | string |                   | /log_endpoint     |
| logger_tls_period      | int32  | 4                 | 300               |
| verbose                | bool   | false             | false             |
+------------------------+--------+-------------------+-------------------+
```

`verbose` should be false! Meaning you'll only receive [status logs](http://osquery.readthedocs.org/en/stable/deployment/logging/#status-logs) of level `WARN` or `ERROR`.

**Comment by defunctzombie** [comment]
@theopolis I ran that `osqueryi` command and indeed see false for verbose value. However, my TLS endpoint is seeing items with severity `0` and message `TLS/HTTPS POST request to URI: ...`.

**Comment by defunctzombie** [comment]
My bad, I realized I had a flags file that was set to verbose! womp womp!

**Comment by theopolis** [comment]
:dancers:, nice, good find!
