### ISSUE TITLE
wifi_networks table on OS X 10.9.5 (13F1507)

### ISSUE THREAD

**Issue by pathcl** [facebook/osquery#1760]
I've just cloned and installed osquery and then tried to do this:

lsanmartin ~/src/c++/osquery >  ./build/darwin10.9/osquery/osqueryi
osquery - being built, with love, at Facebook
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Using a virtual database. Need help, type '.help'
osquery> select * from wifi_networks;
2016-01-11 14:59:26.090 osqueryi[29498:507] -[__NSArrayM getObjects:andKeys:]: unrecognized selector sent to instance 0x7f9153c58740
E0111 14:59:26.091904 1905287952 registry.cpp:336] table registry wifi_networks plugin caused unknown exception

Am I missing something? couldnt find any open issue regarding this.

**Comment by sharvilshah** [comment]
Can you pass in the `--verbose` flag to `osqueryi` and see what it says?

**Comment by pathcl** [comment]
lsanmartin ~ > osqueryi --verbose
I0111 16:53:59.184216 1905287952 init.cpp:278] osquery initialized [version=1.6.3-17-g34d19a2]
I0111 16:53:59.184419 1905287952 extensions.cpp:177] Could not autoload modules: Failed reading: /etc/osquery/modules.load
I0111 16:53:59.184619 1905287952 db_handle.cpp:106] RocksDB: [WARN] RocksDB version: 3.13.0
I0111 16:53:59.184634 1905287952 db_handle.cpp:106] RocksDB: [WARN] Git sha rocksdb_build_git_sha:
I0111 16:53:59.184640 1905287952 db_handle.cpp:106] RocksDB: [WARN] Compile date Oct 16 2015
I0111 16:53:59.184646 1905287952 db_handle.cpp:106] RocksDB: [WARN] DB SUMMARY
I0111 16:53:59.184738 1905287952 db_handle.cpp:106] RocksDB: [WARN] CURRENT file:  CURRENT
I0111 16:53:59.184756 1905287952 db_handle.cpp:106] RocksDB: [WARN] IDENTITY file:  IDENTITY
I0111 16:53:59.184768 1905287952 db_handle.cpp:106] RocksDB: [WARN] MANIFEST file:  MANIFEST-000133 size: 937 Bytes
I0111 16:53:59.184777 1905287952 db_handle.cpp:106] RocksDB: [WARN] SST files in /Users/lsanmartin/.osquery/shell.db dir, Total Num: 8, files: 000109.sst 000111.sst 000112.sst 000115.sst 000121.sst 000124.sst 000136.sst 000138.sst
I0111 16:53:59.184784 1905287952 db_handle.cpp:106] RocksDB: [WARN] Write Ahead Log file in /Users/lsanmartin/.osquery/shell.db: 000137.log size: 198924 ;
I0111 16:53:59.184800 1905287952 db_handle.cpp:106] RocksDB: [WARN]          Options.error_if_exists: 0
I0111 16:53:59.184811 1905287952 db_handle.cpp:106] RocksDB: [WARN]        Options.create_if_missing: 1
I0111 16:53:59.184823 1905287952 db_handle.cpp:106] RocksDB: [WARN]          Options.paranoid_checks: 1
I0111 16:53:59.184834 1905287952 db_handle.cpp:106] RocksDB: [WARN]                      Options.env: 0x104f38188
I0111 16:53:59.184846 1905287952 db_handle.cpp:106] RocksDB: [WARN]                 Options.info_log: 0x7ff4a1601098
I0111 16:53:59.184859 1905287952 db_handle.cpp:106] RocksDB: [WARN]           Options.max_open_files: 5000
I0111 16:53:59.184870 1905287952 db_handle.cpp:106] RocksDB: [WARN]       Options.max_total_wal_size: 0
I0111 16:53:59.184881 1905287952 db_handle.cpp:106] RocksDB: [WARN]        Options.disableDataSync: 0
I0111 16:53:59.184893 1905287952 db_handle.cpp:106] RocksDB: [WARN]              Options.use_fsync: 0
I0111 16:53:59.184906 1905287952 db_handle.cpp:106] RocksDB: [WARN]      Options.max_log_file_size: 1048576
I0111 16:53:59.184917 1905287952 db_handle.cpp:106] RocksDB: [WARN] Options.max_manifest_file_size: 18446744073709551615
I0111 16:53:59.184929 1905287952 db_handle.cpp:106] RocksDB: [WARN]      Options.log_file_time_to_roll: 0
I0111 16:53:59.184942 1905287952 db_handle.cpp:106] RocksDB: [WARN]      Options.keep_log_file_num: 10
I0111 16:53:59.184952 1905287952 db_handle.cpp:106] RocksDB: [WARN]        Options.allow_os_buffer: 1
I0111 16:53:59.184964 1905287952 db_handle.cpp:106] RocksDB: [WARN]       Options.allow_mmap_reads: 0
I0111 16:53:59.184975 1905287952 db_handle.cpp:106] RocksDB: [WARN]      Options.allow_mmap_writes: 0
I0111 16:53:59.184988 1905287952 db_handle.cpp:106] RocksDB: [WARN]          Options.create_missing_column_families: 1
I0111 16:53:59.184999 1905287952 db_handle.cpp:106] RocksDB: [WARN]                              Options.db_log_dir:
I0111 16:53:59.185010 1905287952 db_handle.cpp:106] RocksDB: [WARN]                                 Options.wal_dir: /Users/lsanmartin/.osquery/shell.db
I0111 16:53:59.185022 1905287952 db_handle.cpp:106] RocksDB: [WARN]                Options.table_cache_numshardbits: 4
I0111 16:53:59.185034 1905287952 db_handle.cpp:106] RocksDB: [WARN]     Options.delete_obsolete_files_period_micros: 21600000000
I0111 16:53:59.185046 1905287952 db_handle.cpp:106] RocksDB: [WARN]              Options.max_background_compactions: 1
I0111 16:53:59.185058 1905287952 db_handle.cpp:106] RocksDB: [WARN]                  Options.max_background_flushes: 1
I0111 16:53:59.185070 1905287952 db_handle.cpp:106] RocksDB: [WARN]                         Options.WAL_ttl_seconds: 0
I0111 16:53:59.185082 1905287952 db_handle.cpp:106] RocksDB: [WARN]                       Options.WAL_size_limit_MB: 0
I0111 16:53:59.185094 1905287952 db_handle.cpp:106] RocksDB: [WARN]             Options.manifest_preallocation_size: 4194304
I0111 16:53:59.185106 1905287952 db_handle.cpp:106] RocksDB: [WARN]                          Options.allow_os_buffer: 1
I0111 16:53:59.185119 1905287952 db_handle.cpp:106] RocksDB: [WARN]                         Options.allow_mmap_reads: 0
I0111 16:53:59.185132 1905287952 db_handle.cpp:106] RocksDB: [WARN]                        Options.allow_mmap_writes: 0
I0111 16:53:59.185143 1905287952 db_handle.cpp:106] RocksDB: [WARN]                      Options.is_fd_close_on_exec: 1
I0111 16:53:59.185154 1905287952 db_handle.cpp:106] RocksDB: [WARN]                    Options.stats_dump_period_sec: 0
I0111 16:53:59.185174 1905287952 db_handle.cpp:106] RocksDB: [WARN]                    Options.advise_random_on_open: 1
I0111 16:53:59.185185 1905287952 db_handle.cpp:106] RocksDB: [WARN]                     Options.db_write_buffer_size: 0d
I0111 16:53:59.185195 1905287952 db_handle.cpp:106] RocksDB: [WARN]          Options.access_hint_on_compaction_start: NORMAL
I0111 16:53:59.185206 1905287952 db_handle.cpp:106] RocksDB: [WARN]                       Options.use_adaptive_mutex: 0
I0111 16:53:59.185214 1905287952 db_handle.cpp:106] RocksDB: [WARN]                             Options.rate_limiter: 0x0
I0111 16:53:59.185220 1905287952 db_handle.cpp:106] RocksDB: [WARN]      Options.delete_scheduler.rate_bytes_per_sec: 0
I0111 16:53:59.185226 1905287952 db_handle.cpp:106] RocksDB: [WARN]                           Options.bytes_per_sync: 0
I0111 16:53:59.185231 1905287952 db_handle.cpp:106] RocksDB: [WARN]                       Options.wal_bytes_per_sync: 0
I0111 16:53:59.185238 1905287952 db_handle.cpp:106] RocksDB: [WARN]                   Options.enable_thread_tracking: 0
I0111 16:53:59.185243 1905287952 db_handle.cpp:106] RocksDB: [WARN]                                Options.row_cache: None
I0111 16:53:59.185480 88100864 interface.cpp:246] Extension manager service starting: /Users/lsanmartin/.osquery/shell.em
I0111 16:53:59.185506 1905287952 db_handle.cpp:165] Opening RocksDB handle: /Users/lsanmartin/.osquery/shell.db
I0111 16:53:59.185544 1905287952 db_handle.cpp:106] RocksDB: [WARN] RocksDB version: 3.13.0
I0111 16:53:59.185551 1905287952 db_handle.cpp:106] RocksDB: [WARN] Git sha rocksdb_build_git_sha:
I0111 16:53:59.185557 1905287952 db_handle.cpp:106] RocksDB: [WARN] Compile date Oct 16 2015
I0111 16:53:59.185562 1905287952 db_handle.cpp:106] RocksDB: [WARN] DB SUMMARY
I0111 16:53:59.185662 1905287952 db_handle.cpp:106] RocksDB: [WARN] CURRENT file:  CURRENT
I0111 16:53:59.185708 1905287952 db_handle.cpp:106] RocksDB: [WARN] IDENTITY file:  IDENTITY
I0111 16:53:59.185782 1905287952 db_handle.cpp:106] RocksDB: [WARN] MANIFEST file:  MANIFEST-000133 size: 937 Bytes
I0111 16:53:59.185799 1905287952 db_handle.cpp:106] RocksDB: [WARN] SST files in /Users/lsanmartin/.osquery/shell.db dir, Total Num: 8, files: 000109.sst 000111.sst 000112.sst 000115.sst 000121.sst 000124.sst 000136.sst 000138.sst
I0111 16:53:59.185811 1905287952 db_handle.cpp:106] RocksDB: [WARN] Write Ahead Log file in /Users/lsanmartin/.osquery/shell.db: 000137.log size: 198924 ;
I0111 16:53:59.185825 1905287952 db_handle.cpp:106] RocksDB: [WARN]          Options.error_if_exists: 0
I0111 16:53:59.185835 1905287952 db_handle.cpp:106] RocksDB: [WARN]        Options.create_if_missing: 1
I0111 16:53:59.185845 1905287952 db_handle.cpp:106] RocksDB: [WARN]          Options.paranoid_checks: 1
I0111 16:53:59.185855 1905287952 db_handle.cpp:106] RocksDB: [WARN]                      Options.env: 0x104f38188
I0111 16:53:59.185865 1905287952 db_handle.cpp:106] RocksDB: [WARN]                 Options.info_log: 0x7ff4a1601cb8
I0111 16:53:59.185875 1905287952 db_handle.cpp:106] RocksDB: [WARN]           Options.max_open_files: 5000
I0111 16:53:59.185885 1905287952 db_handle.cpp:106] RocksDB: [WARN]       Options.max_total_wal_size: 0
I0111 16:53:59.185897 1905287952 db_handle.cpp:106] RocksDB: [WARN]        Options.disableDataSync: 0
I0111 16:53:59.185907 1905287952 db_handle.cpp:106] RocksDB: [WARN]              Options.use_fsync: 0
I0111 16:53:59.185919 1905287952 db_handle.cpp:106] RocksDB: [WARN]      Options.max_log_file_size: 1048576
I0111 16:53:59.185930 1905287952 db_handle.cpp:106] RocksDB: [WARN] Options.max_manifest_file_size: 18446744073709551615
I0111 16:53:59.185940 1905287952 db_handle.cpp:106] RocksDB: [WARN]      Options.log_file_time_to_roll: 0
I0111 16:53:59.185950 1905287952 db_handle.cpp:106] RocksDB: [WARN]      Options.keep_log_file_num: 10
I0111 16:53:59.185959 1905287952 db_handle.cpp:106] RocksDB: [WARN]        Options.allow_os_buffer: 1
I0111 16:53:59.185969 1905287952 db_handle.cpp:106] RocksDB: [WARN]       Options.allow_mmap_reads: 0
I0111 16:53:59.185979 1905287952 db_handle.cpp:106] RocksDB: [WARN]      Options.allow_mmap_writes: 0
I0111 16:53:59.185989 1905287952 db_handle.cpp:106] RocksDB: [WARN]          Options.create_missing_column_families: 1
I0111 16:53:59.185999 1905287952 db_handle.cpp:106] RocksDB: [WARN]                              Options.db_log_dir:
I0111 16:53:59.186009 1905287952 db_handle.cpp:106] RocksDB: [WARN]                                 Options.wal_dir: /Users/lsanmartin/.osquery/shell.db
I0111 16:53:59.186022 1905287952 db_handle.cpp:106] RocksDB: [WARN]                Options.table_cache_numshardbits: 4
I0111 16:53:59.186033 1905287952 db_handle.cpp:106] RocksDB: [WARN]     Options.delete_obsolete_files_period_micros: 21600000000
I0111 16:53:59.186044 1905287952 db_handle.cpp:106] RocksDB: [WARN]              Options.max_background_compactions: 1
I0111 16:53:59.186054 1905287952 db_handle.cpp:106] RocksDB: [WARN]                  Options.max_background_flushes: 1
I0111 16:53:59.186065 1905287952 db_handle.cpp:106] RocksDB: [WARN]                         Options.WAL_ttl_seconds: 0
I0111 16:53:59.186076 1905287952 db_handle.cpp:106] RocksDB: [WARN]                       Options.WAL_size_limit_MB: 0
I0111 16:53:59.186091 1905287952 db_handle.cpp:106] RocksDB: [WARN]             Options.manifest_preallocation_size: 4194304
I0111 16:53:59.186103 1905287952 db_handle.cpp:106] RocksDB: [WARN]                          Options.allow_os_buffer: 1
I0111 16:53:59.186113 1905287952 db_handle.cpp:106] RocksDB: [WARN]                         Options.allow_mmap_reads: 0
I0111 16:53:59.186125 1905287952 db_handle.cpp:106] RocksDB: [WARN]                        Options.allow_mmap_writes: 0
I0111 16:53:59.186136 1905287952 db_handle.cpp:106] RocksDB: [WARN]                      Options.is_fd_close_on_exec: 1
I0111 16:53:59.186146 1905287952 db_handle.cpp:106] RocksDB: [WARN]                    Options.stats_dump_period_sec: 0
I0111 16:53:59.186156 1905287952 db_handle.cpp:106] RocksDB: [WARN]                    Options.advise_random_on_open: 1
I0111 16:53:59.186167 1905287952 db_handle.cpp:106] RocksDB: [WARN]                     Options.db_write_buffer_size: 0d
I0111 16:53:59.186177 1905287952 db_handle.cpp:106] RocksDB: [WARN]          Options.access_hint_on_compaction_start: NORMAL
I0111 16:53:59.186187 1905287952 db_handle.cpp:106] RocksDB: [WARN]                       Options.use_adaptive_mutex: 0
I0111 16:53:59.186198 1905287952 db_handle.cpp:106] RocksDB: [WARN]                             Options.rate_limiter: 0x0
I0111 16:53:59.186209 1905287952 db_handle.cpp:106] RocksDB: [WARN]      Options.delete_scheduler.rate_bytes_per_sec: 0
I0111 16:53:59.186219 1905287952 db_handle.cpp:106] RocksDB: [WARN]                           Options.bytes_per_sync: 0
I0111 16:53:59.186230 1905287952 db_handle.cpp:106] RocksDB: [WARN]                       Options.wal_bytes_per_sync: 0
I0111 16:53:59.186240 1905287952 db_handle.cpp:106] RocksDB: [WARN]                   Options.enable_thread_tracking: 0
I0111 16:53:59.186251 1905287952 db_handle.cpp:106] RocksDB: [WARN]                                Options.row_cache: None
I0111 16:53:59.186343 1905287952 db_handle.cpp:177] Opening RocksDB failed: Continuing with read-only support
I0111 16:53:59.186399 1905287952 init.cpp:461] Error reading config: config file does not exist
osquery - being built, with love, at Facebook
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Using a virtual database. Need help, type '.help'
osquery> select * from wifi_networks;
2016-01-11 16:54:00.900 osqueryi[30421:507] -[__NSArrayM getObjects:andKeys:]: unrecognized selector sent to instance 0x7ff4a1620050
E0111 16:54:00.901618 1905287952 registry.cpp:336] table registry wifi_networks plugin caused unknown exception
osquery>

**Comment by sharvilshah** [comment]
Thanks. Nothing immediately jumps out.

Does the file `/Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist` exist on your system? If so, can you share the contents/structure of it (you can redact ssid, security type, timestamp and other data).

In the meantime, I will try to source a 10.9 box to test it out on.

**Comment by theopolis** [comment]
Also, what version of RocksDB do you have installed? Might want to `brew upgrade` on that build.

**Comment by pathcl** [comment]
@sharvilshah 

lsanmartin ~ > cat /Library/Preferences/SystemConfiguration/com.apple.airport.preferences.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>RememberedNetworks</key>
	<array>
		<dict>
			<key>AutoLogin</key>
			<false/>
			<key>Captive</key>
			<false/>
			<key>Closed</key>
			<true/>
			<key>Disabled</key>
			<false/>
			<key>LastConnected</key>
			<date>2016-01-12T12:10:30Z</date>
			<key>Passpoint</key>
			<false/>
			<key>PossiblyHiddenNetwork</key>
			<false/>
			<key>SPRoaming</key>
			<false/>
			<key>SSID</key>
			<data>
			qwerty
			</data>
			<key>SSIDString</key>
			<string>qwerty</string>
			<key>SecurityType</key>
			<string>WPA2 Personal</string>
			<key>SystemMode</key>
			<true/>
			<key>TemporarilyDisabled</key>
			<false/>
		</dict>
		<dict>
			<key>AutoLogin</key>
			<false/>
			<key>Captive</key>
			<false/>
			<key>Closed</key>
			<true/>
			<key>Disabled</key>
			<false/>
			<key>LastConnected</key>
			<date>2015-11-27T20:52:04Z</date>
			<key>Passpoint</key>
			<false/>
			<key>PossiblyHiddenNetwork</key>
			<false/>
			<key>SPRoaming</key>
			<false/>
			<key>SSID</key>
			<data>
			qwerty
			</data>
			<key>SSIDString</key>
			<string>Kenya</string>
			<key>SecurityType</key>
			<string>WPA Personal</string>
			<key>SystemMode</key>
			<true/>
			<key>TemporarilyDisabled</key>
			<false/>
		</dict>
	</array>
	<key>Version</key>
	<integer>14</integer>
</dict>
</plist>

@theopolis I'll try 'brew upgrade'

**Comment by pathcl** [comment]
@theopolis I upgraded to rocksdb 4.1 and recompiled osquery. Anyway same result.

**Comment by sharvilshah** [comment]
Thanks @pathcl. The problem is that on OS X 10.9 network list is an array of dictionaries and on OS X 10.10 and later it is dictionary of dictionaries. I will try to get a pull request out later tonight/tomorrow.

**Comment by sharvilshah** [comment]
Hey @pathcl, when #1766 lands, hopefully that should fix it. It would be great if you can build that branch and test it out -- while I was able to get a 10.9 VM going, I couldn't emulate the wifi hardware.
