### ISSUE TITLE
Missing issuer and self_signed column in certificates

### ISSUE THREAD

**Issue by joubin** [facebook/osquery#1765]
Here is what I see as available when doing 
```
select * from certificates limit 1;
````
in the header

<pre>
| common_name | subject | ca | not_valid_before | not_valid_after | signing_algorithm | key_algorithm | key_usage | subject_key_id | authority_key_id | sha1 | path|
</pre>
<pre>
OSX 10.11.4 Beta (15E27e)
osqueryi version 1.6.2

</pre>

**Comment by theopolis** [comment]
Hi @joubin, you'll need to upgrade to 1.6.3: https://github.com/facebook/osquery/releases/tag/1.6.3 for those columns.

**Comment by joubin** [comment]
@theopolis 

You are right. I thought that when I did `brew upgrade` and saw `osquery` on the list, that it was the 1.6.3 update. But it was only to 1.6.2. 

Thank you.
