### ISSUE TITLE
Docs mention passwd_changes table that does not exist

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#1769]
In https://osquery.readthedocs.org/en/latest/development/pubsub-framework/#example-inotify there is a link to a `passwd_changes.cpp` file that does not exist. I looked around the repo and couldn't immediately find which (if any) file this should be referencing.

**Comment by theopolis** [comment]
Yeah, that table is long gone, we should remove the references. It would be best to also include a way to get the `file_events` table to produce `passwd` change events. I'll look into the most appropriate place to describe this configuration.
