### ISSUE TITLE
Enable/disable packs based on the contents of /var/osquery/packs

### ISSUE THREAD

**Issue by sohailmamdani** [facebook/osquery#1773]
Right now, packs are enabled/disabled via this bit in osquery.conf

``` json
"packs": {
    "packname": "/var/osquery/packs/packname.conf"
  },
```

It would be easier to enable/disable packs if packs could be enabled/disabled based on the contents of `/var/osquery/packs`. So the relevant part of the config file would be:

``` json
"packs": {
    "/var/osquery/packs/*"
  }
```

**Comment by theopolis** [comment]
So, @sohailmamdani, right now packs cannot be "disabled" so to speak. If you have the contents on disk but do not explicitly "enable" them in the config they could be called disabled, but it's more like they aren't ever enabled. ;)

We could add support to the **filesystem** config plugin to accept filesystem-style globbing as pack targets but this would be very-specific to loading packs from the filesystem. And the allowed globbing would be restricted to `man 3 glob`, how does that sound?

**Comment by zwass** [comment]
@sohailmamdani Is this something you are still interested in?

**Comment by sohailmamdani** [comment]
Sorry for the delayed response, folks. @zwass I am indeed; @theopolis' explanation of adding support to the filesystem config plugin went a bit over my head, though. If I understand it right, Teddy, you're saying that this feature, if implemented, could only load packs from the filesystem - and that's totally fine. I can do a deploy/yank via JSS or Munki of the files in /var/osquery/packs/ and am comfortable doing that. 

Not sure what you mean by "the allowed globbing would be restricted to `man 3 glob` though...

**Comment by zwass** [comment]
I think @theopolis is just trying to say that we could add this functionality for loading packs using the (standard) filesystem config plugin, but that it wouldn't apply to other config plugins, nor other configuration settings besides packs. We would actually perform the globbing with `glob(3)` as described in `man 3 glob`, so it would use the semantics of that function.

More simply, though, I believe this would do what you want. At the least, the example you provided in your original post would work as you expect.

**Comment by theopolis** [comment]
If we ignore 'disabling' via the config, we could add a only-slightly-oddball:
```
"packs": {
    "*": "/var/osquery/packs/*"
}
```
Then each pack name is inherited from the *stem* portion of the filename.

**Comment by sohailmamdani** [comment]
@theopolis I like that! 

So to be clear - in this scenario, removing a pack from `/var/osquery/packs` and perhaps unloading/reloading the launchd for `osqueryd` would, in effect be disabling that pack?
