### ISSUE TITLE
Error parsing config, RocksDB initialize failed after upgrade from 1.5.1 to 1.6.3 (OS X)

### ISSUE THREAD

**Issue by runasand** [facebook/osquery#1779]
After updating osquery on OS X 10.11.2 directly from version 1.5.1 to version 1.6.3, I am running into issues with RocksDB and the config file:

1. The RocksDB issue is #1629 (RocksDB initialize failed). The issue has been closed, but I am not sure how to resolve it on my end. A reboot didn't do the trick. Thoughts?

2. The osquery logs show *"Error reading config: Error parsing the config JSON"* and *"Error registering subscriber: process_file_events: No kernel event publisher"*. I'm guessing these errors are related to the RocksDB issue.

**Comment by sharvilshah** [comment]
On 2:

Is the JSON in the config file valid? Since #1689 only lines starting with `//` or `#` are considered valid comments. And the error regarding `process_file_events` is a red herring, since it requires a kernel extension, which is not shipped by default.

**Comment by runasand** [comment]
It's a bit unclear from #1689 whether osquery supports # comments. I replaced all C-style comments with # comments, but still get the same error. I'm unable to run *config-check*, since I can't open RocksDB. Thoughts?

Also, do you know of a solution for the process_file_events error?

**Comment by sharvilshah** [comment]
Judging from the [code](https://github.com/facebook/osquery/blob/master/osquery/config/config.cpp#L315-L336) hash `#` comments are supported.

On RocksDB: 
* What version are you running (try upgrading to 4.1 if not already?)
* And the RocksDB path can be opened by a single `osqueryd` instance, is there any other process accessing the path?

And the unhelpful `process_file_events` error message is fixed in 31dfad2515e5399c9b48b89a97d68fd4a1b7292e

**Comment by runasand** [comment]
Thanks for confirming # comments! I went through the config file one more time, removed another instance of C-style comments and no longer see the config error.

I'm starting to wonder if I have RocksDB installed at all. I can't seem to find a mention of it on my system, and I know it's not something I have installed manually. Unless it came with osquery 1.5.1, I don't have it. Any idea when RocksDB was introduced? I could install it manually now, if you think it's likely to solve the problem I'm having.

**Comment by sharvilshah** [comment]
RocksDB has been a dependency and the backing store since the very beginning.
I am assuming you are downloading the pkg from https://osquery.io/downloads/. That package should not have any dependencies.

If you are compiling from source or installing it via `homebrew`, you can check if rocksdb exists by running `brew list rocksdb`

**Comment by runasand** [comment]
I installed both 1.5.1 and 1.6.3 by downloading the OS X package. 

The only `osqueryd` instance running is `/usr/local/bin/osqueryd  --flagfile="/var/osquery/osquery.flags"`

How do I check which version of RocksDB I have installed and what the path is?

**Comment by sharvilshah** [comment]
Ah, if you downloaded the OS X package, then the latest RocksDB is embedded (statically linked) inside the binary, and I do not know if there is a way to check the version.

I wonder if the database path (default is `/var/osquery/osquery.db`) has the right permissions.
On my box:
`drwx------   root  wheel  osquery.db` or if the pidfile is stale.

That's all I can think of now, but as a last ditch effort (I do not recommend this), you can:
* stop osqueryd (`sudo osqueryctl stop`)
* remove the `LOCK` file inside `osquery.db`
* remove `osqueryd.pidfile`

and then start osqueryd again and see if that helps.

**Comment by sharvilshah** [comment]
Also did you see the `RocksDB initialize failed` error in the shell or in osqueryd logs?

**Comment by runasand** [comment]
The database path on my system has the same permissions as on your box. The ``LOCK`` file was last touched on Aug 3 (guess this means it's stale).

The ``RocksDB initialize failed`` error only pops up when I try to run ``osqueryctl config-check``. I do not see the error in the logs or when I stop/start.

**Comment by sharvilshah** [comment]
Is `osqueryd` already running when you are doing the config-check? If so, it will throw up and error (as expected) since `osqueryd` has the RW lock.

```
❯ sudo osqueryctl config-check
E0118 17:10:09.520731 1913696256 init.cpp:421] [Ref #1629] osqueryd initialize failed: Could not open RocksDB
❯ sudo osqueryctl status
com.facebook.osqueryd is running. pid: 81943
❯ sudo osqueryctl stop
❯ sudo osqueryctl config-check
```

**Comment by runasand** [comment]
Hah, yep, that fixes it. To summarize for anyone else reading this issue:

1. The `RocksDB initialize failed` error only appears when `osqueryd` is running **and** I try to run `osqueryctl config-check`. The solution is to run `osqueryctl stop` first, followed by `osqueryctl config-check`.

2. The `Error parsing the config JSON` message appeared because support for C-style comments was dropped (#1689). The solution is to edit the config file and replace all C-style comments with # comments.

3. The `process_file_events error` message is fixed in 31dfad2.

Thanks for taking the time to debug this, @sharvilshah!

**Comment by theopolis** [comment]
Awesome! I'll work these notes into the ReadTheDocs guides and into the related issues.

**Comment by sharvilshah** [comment]
Cool! 

And just to be extra clear for the docs, both Hash style comments (lines starting with `#`) and C++ style comments (lines starting with `//`) are considered valid comments for the config file. 

C-style comments (lines starting with `/* ... */`) are invalid.

**Comment by theopolis** [comment]
Right, we added support for C++ `//` and hash-style comments directly in the osquery code. Comments in the config-as-JSON are very helpful!
