### ISSUE TITLE
Query System Integrity Protection

### ISSUE THREAD

**Issue by llauren** [facebook/osquery#1798]
Hi,

One thing that would be really nice to query is whether the El Capitan System Integrity Protection is in action. This is what's returned from the `csrutil` command. While not really feasible for a malware, anybody with physical access may boot a mac into rescue mode and issue the command `csrutil disable` from the terminal.

**Comment by llauren** [comment]
Oops. Uninformed user error. Sorry and thanks -- this was already implemented as sip_config :blush:

**Comment by theopolis** [comment]
Hey @llauren, the [`sip_config`](https://github.com/facebook/osquery/blob/master/specs/darwin/sip_config.table) table is in master right now! :dancer:

**Comment by llauren** [comment]
Masterful!
