### ISSUE TITLE
Query thermal and fans

### ISSUE THREAD

**Issue by llauren** [facebook/osquery#1799]
One reason i might still want to keep _collectd_ is that i can query the temperature of a device and know when it's starting to boil, or whether the fans are humming. If osquery provided this sensor data, i'd have one less tool to worry about.

**Comment by llauren** [comment]
Might i add that i'm not a coder, so i don't expect to add that functionality myself?

**Comment by guerrillera** [comment]
Si pero quería pedir permiso primero a github , estuve dudosa y prefiero consultar siempre. Un saludo

**Comment by guerrillera** [comment]
Muchísimas gracias,muy agradecida

**Comment by sharvilshah** [comment]
So at least on OS X, there is an `smc_keys` table that is now exposed. The data there is the raw sensor values, so will need processing.

For fans, the keys are:

F0Ac - Fan actual speed
F0Mn - Fan minimum speed
F0Mx - Fan maximum speed
F0Sf - Fan safe speed
F0Tg - Fan target speed

That's for the first fan. If there are multiple fans, the keys are F1Ac and so on. The data type for that is `fpe2` which I speculate is unsigned floating point.

There are similar keys for temperature sensors (I don't know which keys off the top of my head).

So the data is there, one just needs to clean it up.

**Comment by llauren** [comment]
Thanks, and i had no idea from looking at those key names!

**Comment by theopolis** [comment]
Hey @llauren and @sharvilshah, I'm curious to your opinions on a fan/thermal-dedicated table. Do you think we should expose those SMC keys in a specific table-- would there be any other data or formatting we could possibly add?

**Comment by theopolis** [comment]
So with the addition of the `temps` table in #1807, I think we can close this out. Also note that `temps` will most likely be renamed to `temperatures` before the next release.

**Comment by guerrillera** [comment]
A todos como ya dije no tengo palabras para expresaros mi gran gratitud por toda vuestra ayuda.Gracias

**Comment by llauren** [comment]
Hi and sorry for not reacting! I feel kind of rotten not having taken part
of the discussion.

But! Thanks for creating a table for temperatures. I'll take a look at it
as soon as possible! Mostly, what I'm looking for is some "health data"
from a laptop or a server, so I know if I should fetch out the canned air
and blast out the dust and car hair from the fan vent. I'm not so
interested in the temperature of given components, unless they are
critically hot and on the edge of disaster (or a little before, perhaps).

Best regards,
.. Robin Laurén

**Comment by llauren** [comment]
Back.

Looking at the `smc_keys` table makes my head spin and the values for `F0Ac` and `F1Ac` make no sense to me. My `F0Ac` stands at 1073741824.000000 and my `F0Mx` is zero, and i kind of feel that i should be getting nervous. `F1Ac` on the other hand is 0 and `F1Mx` is at -2147483648.000000 so yeah, i'm kind of weirded out. And by that, i please request some more sensible keys and values, if that wouldn't be too much to ask.

Further on, i don't have a `temps` table in my osquery (1.7.0), which i just downloaded from osquery.io. At least `select * from temps;` returns a frosty `Error: no such table: temps`. Not sure if it should be in the master already. Maybe i'm just impatient.

Oh, and using `brew install osquery` got me an older osqueryi 1.6.2, which crashed with a malloc error, but i suppose the brew stuff will update in due time.

~rL

**Comment by theopolis** [comment]
See #1781 and #1782 for the Boost and brew 1.6.2 breakage. Waiting to merge https://github.com/Homebrew/homebrew/pull/48992 for a fix.

If you take a peek at the changes since 1.7.0: https://github.com/facebook/osquery/compare/1.7.0...master the `temperatures` and `fan_speeds` tables were added afterward. I'm not 100% certain about the `F0Ac` and `F0Mx` values, but my guess is that https://github.com/facebook/osquery/commit/503ffb6e545921262db020d2a8329597b0912f96 should have fixed those values.

**Comment by llauren** [comment]
Sorry, i was being too clever for my own good. I meant to say that it's not in the _released version_ yet, not in the master. Anyways, i'll try to practice some patience for the next one ॐ
