### ISSUE TITLE
Reduce binary size or ship shared library (libosquery)

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1811]
The binary size is beginning to increase dramatically again. We should take steps to reduce the footprint via removing expressions, potentially cpp-netlib (using updated thrift + TLS additions).

**Comment by theopolis** [comment]
This may happen in the future as the recommended default but for now `OSQUERY_BUILD_SHARED` will produce a `libosquery.so` and link the resultant executables. Binary size is a non-goal with the new 1.8.0 build system.

**Comment by Sudexo** [comment]
> OSQUERY_BUILD_SHARED

Where to set value of OSQUERY_BUILD_SHARED ?
