### ISSUE TITLE
Force use `removed=false` for events-based queries

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1816]
We need a facility for communicating from within virtual table implementations to the callsites issuing queries. There are four scenarios where queries are used within the codebase:

1. The scheduler issues a query and constructs a `ScheduledQuery` structure that includes a differential.
2. The extensions API or distributed query API receives a request for a query and executes.
3. A virtual table's `xFilter`/scan implementation implicitly uses some SQL via `SQL::SQL`.
4. A 'service' such as the watchdog issues SQL similar to implicit scans.

We allow concurrent executions of SQL queries through the `SQL` class that maintains multiple databases. At all times there is a "master" to prevent module attaching for each executions. Additional databases are created ephemerally to service concurrent executions. These have considerable performance impact.

Since there is no explicit SQLite mechanism for communicating to `sqlite_exec` from within `xFilter` implementations we have two options:
- Use a global structure, potentially indexed by database container.
- Implement a hidden column for each table that is removed via the `SQL` abstraction.

**Comment by lexelby** [comment]
I could be totally off-base here, but do the description and the title refer to the same issue?

**Comment by theopolis** [comment]
Ah, they 'sort' of do! My want is to prevent events-based tables from eventually generating removed events in the log. To do this we must create a mechanism for table implementations to communicate to the schedule. Right now the code implementing the virtual tables, and the code implementing the filter/scan (aka the `genTableName`) calls is very much opaque to the rest of osquery.

I we can figure out a way to build communication from the table implementation into other parts of the codebase we can achieve the title!

**Comment by lexelby** [comment]
Oh, I see now.  Anyway, yes, I'm definitely in favor of this one.  It'd halve our log output :)

**Comment by theopolis** [comment]
See this PR and specifically the logic highlighted in the anchor: https://github.com/facebook/osquery/pull/2431/files#diff-888b4707cbdedc29bc1bdabf69949d1eR100

It's a set of new features that help solve this issue. From here on out there is no set-difference applied to results from events-based tables. :)
