### ISSUE TITLE
fpe2 values in smc_keys table seem off

### ISSUE THREAD

**Issue by kaizensoze** [facebook/osquery#1822]
I have a fan_speeds PR almost ready with the one thing remaining being converting the speed values. The only issue is the values from the smc_keys table for fpe2 types seem weird compared to the sp78 values. Both of which should be 2 bytes.

An sp78 value in the table looks something like 2b80 while a fpe2 value looks like -1073741824.000000. I'm not too familiar with smc. Is there an extra step I need to do for the fpe2 values?

ref: https://stackoverflow.com/questions/22160746/fpe2-and-sp78-data-types

**Comment by theopolis** [comment]
On my host both `fpe2
