### ISSUE TITLE
Request: Tab autocomplete in osqueryi

### ISSUE THREAD

**Issue by llauren** [facebook/osquery#1837]
Oh how i'd love to `select * from sip_<tab>`, not having to remember whether it's `sip_config`, `sip_status` or `sip_something_else`. Oh how i would _especially_ love if it's a sensible tab autocomplete which shows me the different choices i would have for, say, all those `process_` tables.

Thank you.

 ~rL

**Comment by zwass** [comment]
@llauren I'm implementing this in https://github.com/facebook/osquery/pull/2236
