### ISSUE TITLE
Hardware status, sensors, health related tables

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1854]
Hey @kaizensoze, interested in your ideas / insight here.

Your tables that utilize the `smc_keys` values are really helpful for diagnosing machine physical/hardware health. It would be nice to somehow namespace these tables, perhaps by simply adding `hardware_` to their names-- for no other reason but to make them appear in the listings together and organize the very-related data source.

We should also be looking towards how the Linux kernel reports this data, and extending the specs/implementation for cross-OS coverage. It might be worthwhile to investigate a bit now to get an understanding of (1) if the data is available, (2) what sort of diction is used.

**Comment by kaizensoze** [comment]
I need to double check, but I think getting the equivalent info in Linux would be a matter of iterating over the files in `/sys/class/hwmon/`. At least that seems to be what lm-sensors/sensors-detect does: https://www.kernel.org/doc/Documentation/hwmon/sysfs-interface

**Comment by theopolis** [comment]
What do you think about renaming the related tables to include `hardware_` as a prefix?

**Comment by kaizensoze** [comment]
That works. Add it to fan_speeds, currents, voltages, and temperatures? I still need to add a power table.

**Comment by theopolis** [comment]
Yeah, that should cover it! I like to shy away from abbreviations actually. :/

I'm working on an aliasing mechanic for table names, but that's a bit out-- and even then I'd prefer to have the most verbose alias be the default.

It's worth some consideration though, since the "hardware" namespace could be applicable in a few other places. We should be careful not to dilute or pidgeon hole its use. Maybe "sensors_"?

**Comment by kaizensoze** [comment]
`sensors_` might be a better option. Or `sensor_`. I guess it depends on which one makes more sense when querying a table:

`hardware_temperatures`
`sensors_temperatures`
`sensors_temperature`
`sensor_temperatures`

Most of the existing tables are plural so it might be awkward to go with a double plural in the name.

**Comment by theopolis** [comment]
You're right, although `hardware_` sounds the best, `sensor_` seems the most appropriate. And a double plural is all sorts of annoying, haha.

**Comment by sharvilshah** [comment]
Was thinking about for this a bit:

Thoughts on combining these tables and calling them `sensors` and adding a column `type` which could be `temperature` or `fan_speed`? 

So queries would look like: `select * from sensors` and to narrow it down: `select * from sensors where type = 'fan_speed'`.

My reasoning for this is:

* `sensors` is a common-ish binary on linux (part of libsensors I think) so it maps naturally to the table name
* It seems we can use `libsensors` for the Linux implementation (I haven't looked into super closely into it), and most of Linux VMs / cloud instances won't report on most sensor types as they are virtualized, so I think it's less of a clutter to have just a single table, that may have none, partial or all of the sensor types.

**Comment by kaizensoze** [comment]
The only issue with a single sensors table is if any of the sensor types would be better displayed in a different format, which is already the case for fan_speeds:

```bash
osquery> select * from sensor_fan_speeds;
+-----+--------+------+------+--------+
| fan | actual | min  | max  | target |
+-----+--------+------+------+--------+
| 0   | 4044   | 2000 | 6436 | 3985   |
+-----+--------+------+------+--------+
```

as opposed to the key-name-value format for the others:

```bash
osquery> select * from sensor_voltages;
+------+-------------------+-------+
| key  | name              | value |
+------+-------------------+-------+
| VC0C | CPU Core 1        | 0.78  |
| VD0R | Mainboard S0 Rail | 14.23 |
| VN0C | MCH               | 0.21  |
| VP0R | 12V Rail          | 8.55  |
+------+-------------------+-------+
```

**Comment by sharvilshah** [comment]
I think  `fan_speeds` can also be adapted to the key-name-value format since each of `actual`, `min`, `max`, `target` maps to distinct SMC key (at least on Darwin): `FiAc`, `FiMn`, `FiMx`, `FiTg` respectively (i ∈ {0,1,2,3,...}).

So the table might look something like:

```
+------+--------------------+-------+
| key  | name               | value |
+------+--------------------+-------+
| F0Ac | Fan 0 Actual Speed | 3000  |
| F0Tg | Fan 0 Target Speed | 4000  |
| F0Mn | Fan 0 Min Speed    | 2000  |
| F0Mx | Fan 0 Max Speed    | 6000  |
+------+--------------------+-------+
```

I haven't looked at the `fan_speeds` implementation, so I might be missing something but this seems that it could work.

**Comment by kaizensoze** [comment]
Yeah I was going to say changing fan_speeds to the key-name-value format wouldn't necessarily be a deal breaker and you could just search for attributes of a given fan with `where key like 'Fi%'`.

**Comment by theopolis** [comment]
Aw, I really liked the set of related speeds accessible as a single row!

**Comment by theopolis** [comment]
Would it make sense to converge on 3 tables: `sensor_fan_speeds`, `sensor_temperatures`, and `sensor_power`? With the most significant change being the consolidation of power, currents, voltage, etc (which are the key/value tables).

**Comment by sharvilshah** [comment]
Yeah, I think you hit the perfect middle ground.
Shoe-horning fan_speeds into key-name-value did seem a little backward.

**Comment by Shellcat-Zero** [comment]
Was this ever added for Linux? I cannot find anything regarding osquery for getting `sensors` data from Linux hosts despite issues/discussions that I've come across, and nothing that I've identified with `.tables` either. This is device fan speed and temperature data, specifically.
Related: 
https://github.com/osquery/osquery/issues/1807
https://github.com/osquery/osquery/issues/1799
