### ISSUE TITLE
osquery.example.conf has typo "log_results_events"

### ISSUE THREAD

**Issue by lexelby** [facebook/osquery#1865]
https://github.com/facebook/osquery/blob/master/tools/deployment/osquery.example.conf#L21

Should be "log_result_events".

**Comment by lexelby** [comment]
Found #1866 because of this.

**Comment by theopolis** [comment]
Nice find! Mind sending a PR with the quick fix?

**Comment by lexelby** [comment]
Sure!  I filed this earlier because I was busy and didn't have time to dash off a PR.
