### ISSUE TITLE
invalid flags in flag file don't cause an error or warning message

### ISSUE THREAD

**Issue by lexelby** [facebook/osquery#1866]
An invalid command line argument actually passed on the command line causes osquery to exit with an error message.  An invalid argument in the flag file is silently ignored.  For example, `--log_results_events` (see #1865).

**Comment by theopolis** [comment]
Right, at worst an invalid flag should create an error line. Since the config can be updated at a later time I don't want invalid flags causing the daemons to turn down.

We can also catch these when the daemon starts and fail initialization if there's an invalid flag.

**Comment by lexelby** [comment]
Yeah, that makes sense.  It's just interesting that we've had an osquery.flags config running in production for months that had an incorrect arg.

**Comment by theopolis** [comment]
We're you trying to turn result-events off? They default to on/true ;)

**Comment by lexelby** [comment]
We were trying to turn it on, thankfully :)
