### ISSUE TITLE
add "ignore_paths" option for FIM

### ISSUE THREAD

**Issue by lexelby** [facebook/osquery#1870]
We'd like to be able to monitor `/etc/**`, but a certain file is changed many times.  Our results are bloated with unimportant changes, and osquery's memory is bloated by buffering all of those changes.  It'd be useful if we could tell osquery to monitor everything under `/etc/` but ignore `/etc/foo`.

**Comment by theopolis** [comment]
The `file_paths` key should accept shell globbing expressions. So something like '/etc/[!t]*` I think the challenge is when we intersect globbing with our `**` 'feature' of recursive watching. This is not standard and is not handled from my tests.

**Comment by lexelby** [comment]
Hmm.  The problem is that as with regexes, `[abcd]` matches a single character.  So if I wanted everything (recursively) in /etc except /etc/foo, I'd have:

```
/etc/?
/etc/??
/etc/[!f]*
/etc/f[!o]*
/etc/fo[!o]*
/etc/foo?*
/etc/*/**
```

That's if `/etc/foo` is expected to be a file.  It gets even more insane if `/etc/foo` could be a directory.  I'm not sure this kind of solution is flexible enough.

**Comment by lexelby** [comment]
Fwiw, alternatively supporting a dialect of regex with lookahead/lookbehind assertions would neatly solve the problem.

**Comment by theopolis** [comment]
Right, it's a pain. We should jump into the #fim channel on the osquery Slack and talk about a more flexible path expression method, regexing + checking against a list of potential folder/file targets is intense-- not sure if it's possible.

**Comment by theopolis** [comment]
See #3530
