### ISSUE TITLE
Add table for core cpu info from /proc/stat on Linux

### ISSUE THREAD

**Issue by DaanDeMeyer** [facebook/osquery#1889]
I'm looking to use osquery to display general system information of a number of servers. Currently osquery does not have a table to query the cpu usage of a system. On Linux this information is easily accessible through the /proc/stat file, which displays how much time the cpu spent in various parts of the system. If a table for this information is implemented, users will be easily able to calculate where the cpu spent time since the last query by using the results log.

**Comment by xavinux** [comment]
@theopolis think that this table could have this columns:

+------+-----------+--------+-------------+----------+------------+--------+---------+----------+-------+---------------+
| cpu  | user      | nice    | system    | idle       | iowait     | irq      | softirq | steal    | guest | guest_nice |
+------+-----------+--------+-------------+----------+------------+--------+---------+----------+--------+---------------+
| cpu0 | 1737    | 3770  | 3417628  | 44816  | 25816     | 4968 | 4028    | 7192    |  0      |   0               |
+------+--------- -+--------+-------------+-----------+------------+--------+---------+----------+--------+---------------+

**Comment by xavinux** [comment]
@theopolis this is the idea of the columns for this table:

+------+------+------+----------+-----+---------+----+--------+--------+--------+---------------+
| cpu  | user | nice | system | idle | iowait | irq | softirq | steal | guest | guest_nice |
+------+------+------+----------+-----+---------+----+--------+--------+--------+---------------+
| cpu0 | 137 | 704 | 17628 | 448 | 28164 | 48 | 4024  | 71921  | 0000  |  000000000  |
+------+-------+-----+----------+-----+---------+----+--------+---------+--------+---------------+


And think that the spec file could be:

**table_name("cpu_usage")
description("Displays information about cpu cores usage.")
schema([
    Column("cpu", BIGINT, "Name of the CPU Cores"),
    Column("user", BIGINT, "Time spent in user mode"),
    Column("nice", BIGINT, "Time spent in user mode with low priority (nice)"),
    Column("system", BIGINT, "Time spent in system mode"),
    Column("idle", BIGINT, "Time spent in the idle task"),
    Column("iowait", BIGINT, "Since Linux 2.5.41 the time waiting for I/O to complete"),
    Column("irq", BIGINT, "Since Linux 2.6.0-test4 the time servicing interrupts"),
    Column("softirq", BIGINT, "Since Linux 2.6.0-test4 the time servicing softirqs"),
    Column("steal", BIGINT, "Since Linux 2.6.11 time spent in other operating systems when running in a virtualized environment"),
    Column("guest", BIGINT, "Since Linux 2.6.24 time spent running a virtual CPU for guest OS under the control of the Linux kernel"),
    Column("guest_nice", BIGINT, "Since Linux 2.6.33 the time spent running a niced guest "),
])
implementation("linux/cpu_usage@genCpuUsage")**



Thanks

**Comment by DaanDeMeyer** [comment]
The /proc/stat file also provides a row of information for the entire cpu (the sum of all the values of the cores). Do we include this row in the table or should users calculate it themselves by summing all the values?

**Comment by xavinux** [comment]
I think that would be useful to include it and have this data in the table so users don't have to calculate it by hemselves.

**Comment by DaanDeMeyer** [comment]
That's true, but I think it gives the table more than 1 responsibility. Having the primary key just be the number of a core makes things a lot more clear in my opinion. The sum of all cores should probably be in another table, but I'm not sure if it should be an existing table or a new table.
