### ISSUE TITLE
make sdk fails on ubuntu trusty

### ISSUE THREAD

**Issue by DaanDeMeyer** [facebook/osquery#1896]
when running make sdk on the ubuntu14 vagrant vm, the build fails with following error:

/usr/bin/ld: cannot find -llibosquery_additional

Steps to reproduce:

1. clone osquery
2. launch ubuntu14 vm with vagrant up ubuntu14
3. ssh into the vm and clone the osquery repository
4. cd into the osquery directory and run make deps
5. run make sdk

**Comment by theopolis** [comment]
Confirmed! There is a bit more work involved to restore the SDK build. I am working on the first part in #1897.
