### ISSUE TITLE
gflags dependency missing when installing on clean OS/X system

### ISSUE THREAD

**Issue by readshaw** [facebook/osquery#1909]
As part of deeper planning of an osquery rollout, I have noticed that on a clean OS/X system there is a single dependency missing that is not bundled or statically linked with osquery client - gflags.  Note that I am building osquery locally from the master branch.

```
$ osqueryd --help
dyld: Library not loaded: /usr/local/lib/libgflags.2.dylib
  Referenced from: /usr/local/bin/osqueryd
  Reason: image not found
Trace/BPT trap: 5`
```

If that dependency is pre-installed via either brew or simply copying the file over manually, then osquery client runs OK.

I think it would be preferred for the osquery client package to be fully self-contained wrt these types of dependencies.  Is there a way that this particular dependency could be statically linked or bundled another way?

Thanks in advance.

**Comment by sharvilshah** [comment]
Running `make deps` before building should pull in gflags via homebrew. See https://github.com/facebook/osquery/blob/master/tools/provision/darwin.sh#L26 and https://github.com/facebook/osquery/blob/master/tools/provision/lib.sh#L540-L541

Is that not the case?

**Comment by theopolis** [comment]
But it is! ...if you're using the packages we provide, we have a test to assure there's no locally linked dependencies. :D

If you're building packages yourself, you should consider @sharvilshah's note about make deps. Also check out: https://osquery.readthedocs.org/en/stable/development/building/

There're lots of notes about building / distributing / testing packages.

**Comment by readshaw** [comment]
Thanks for the suggestions.

My build process is:

$ make deps (I see the gflags brew package installed as part of this step)
$ make (compiles without error)
$ cd tools/deployment
$ make_osx_package.sh  (because I want to pass flags to this script for custom plist, conf, etc)

When I transfer the built package to a clean, fresh OS/X image on a different system, the osquery pkg installs OK but osqueryd fails to start with the error above:

```
$ osqueryd —-help
dyld: Library not loaded: /usr/local/lib/libgflags.2.dylib
  Referenced from: /usr/local/bin/osqueryd
  Reason: image not found
Trace/BPT trap: 5`
```

The tactical resolution was to manual copy that library from my build system, but that's not preferred, but confirmed this was the only shared library missing from the bistro.

On the Wiki I see reference to running “make package”, but that seems to build the package with default options, which is why I run make_ox_package.sh directly, which is also referenced the Wiki.  Did I misunderstand that choice?

**Comment by sharvilshah** [comment]
Does `brew info gflags` show it as installed, and what paths does `brew ls gflags` spit out?
Are there symlinks to the paths given by `brew ls gflags` in `/usr/local/lib`?

**Comment by readshaw** [comment]
On my build system:

```
$ brew info gflags
gflags: stable 2.1.2 (bottled)
Library for processing command-line flags
https://gflags.github.io/gflags/
/usr/local/Cellar/gflags/2.1.2 (16 files, 335.5K) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gflags.rb
==> Dependencies
Build: cmake ✘
==> Options
--with-debug
	Build debug version
--with-static
	Build gflags as a static (instead of shared) library.
```

and

```
$ brew ls gflags
/usr/local/Cellar/gflags/2.1.2/bin/gflags_completions.sh
/usr/local/Cellar/gflags/2.1.2/include/gflags/ (4 files)
/usr/local/Cellar/gflags/2.1.2/lib/libgflags.2.1.2.dylib
/usr/local/Cellar/gflags/2.1.2/lib/libgflags_nothreads.2.1.2.dylib
/usr/local/Cellar/gflags/2.1.2/lib/cmake/ (4 files)
/usr/local/Cellar/gflags/2.1.2/lib/ (4 other files)
```

**Comment by theopolis** [comment]
Try a: brew uninstall --force gflags
Then: make deps

**Comment by readshaw** [comment]
Thanks Teddy.  I performed these steps, and did see gflags get re-compiled as a static library:

```
Install the project...
/usr/local/Cellar/cmake/3.5.0/bin/cmake -P cmake_install.cmake
-- Install configuration: "Release"
-- Installing: /usr/local/Cellar/gflags/2.1.2/lib/libgflags.a
-- Installing: /usr/local/Cellar/gflags/2.1.2/lib/libgflags_nothreads.a
```

as well as the soft-linking into /usr/local/lib.

Installation on a clean laptop worked correctly this time, probably as y'all expected.  Not sure why gflags was built dynamically before.

Thanks again for your patience.

**Comment by theopolis** [comment]
No problem at all! We can modify the provision scripts to make sure this doesn't happen again. That means adding some logic to check how gflags was installed.

The make/CMake logic allows local dependent links to assist OS package managers and customized packaging. Only the "deps" provision step enforces environment changes as it mimics our build / package setups
