### ISSUE TITLE
JDBC driver for osquery

### ISSUE THREAD

**Issue by sumkincpp** [facebook/osquery#1927]
Hi all, 

Would be great to have a JDBC driver for osquery. 
As result it could be possible to smoothly integrate osquery to other solutions, as well as centralize data collection.

Or, maybe there should be a centralized "database" with jdbc accessor which will be a proxy to discovered cluster of osquery machines. 

Any thoughts?

**Comment by theopolis** [comment]
Hi @sumkincpp, there was some talk a while back in #764. I'm not sure if a JDBC connector/driver makes the most sense-- but it certainly depends on how you want to use or integrate osquery's table data. Do you have any use cases / projects in mind?

**Comment by sumkincpp** [comment]
osquery can be greatly be integrated to some of the Network Monitoring Systems which are using JDBC SQL Collector approach as the source for monitoring Data(I.e. I may provide example off-list). Thrift-based service query endpoint is good, but this is something that needs to have custom Collector specifically written for osquery Thrift interface.

What about idea of adding osquery service discovery mechanism, so it would be possible to proxy queries to exact devices in network through "management gateway"?

Also, there were some recent news about OCP initiative within Google&Facebook and where were mentioned a good idea for development of new transport mechanism for device inventory querying, in other words - [replacing legacy SNMP approach](http://www.pcworld.com/article/3042641/google-has-joined-facebooks-open-compute-project-and-submitted-a-48-volt-rack-design.html). I think osquery very nicely fits to this idea as all is left is a protocol development task . 

And finally, SNMP approach is still here, widely deployed and used. So, as osquery data lives in tables, it is also possible(and may be very useful) to extend net-snmp with dynamic MIB Model based on osquery tables currently used on host machine which is running osquery.

Sorry for many ideas, just wanted to share my thoughts about osquery.

**Comment by theopolis** [comment]
There hasn't been any movement on this for a while. I'm going to close the issue, feel free to reopen if anyone wants/needs these features.

**Comment by igor-suhorukov** [comment]
@sumkincpp I try solve jdbc access issue by leverage QuestDB as PostgreSQL protocol emulator and custom [osquery](https://github.com/igor-suhorukov/osquery-java) function for it

**Comment by C2BB** [comment]
> @sumkincpp I try solve jdbc access issue by leverage QuestDB as PostgreSQL protocol emulator and custom [osquery](https://github.com/igor-suhorukov/osquery-java) function for it

Did you have any success with this approach?
