### ISSUE TITLE
Adding event subscriber for Application Usage Times, looking for comments about NSWorkspace Observers

### ISSUE THREAD

**Issue by muffins** [facebook/osquery#1943]
I've been working with @theopolis on adding a subscriber to application event feed data in OS X, however we've been having trouble figuring out how to get observer methods subscribed to the NSWorkspace notification center in objective c++. I through this question out in the slack and  @arubdesu mentioned that @russellhancox may possibly have some ideas?

The initial commit of the [fork is here](https://github.com/PoppySeedPlehzr/osquery/commit/583251ce82f93e84b1d7e3638fb747b7eaf5f826) 

Another note, most of what we've currently got has been an attempt to mimic how the crankd script is registering observers for application events, but we can't seem to get it working as they did.

Any suggestions would be much appreciated :smile:

**Comment by russellhancox** [comment]
The problem is that NSWorkspace notifications need the _main_ runloop to be running. The `CFRunLoopRun()` run call inside `NSWorkspaceEventPublisher::run()` will return immediately because you aren't adding any sources to that thread's runloop.

The main runloop is created automatically on the main thread but something needs to tell it to run. I haven't looked at the event framework code closely but I assume all of this is running on background threads. Making the main runloop run would require moving whatever currently runs on the main thread onto a background thread and then calling `CFRunLoopRun()` on the main thread.

**Comment by theopolis** [comment]
Good info! If there's an implicit requirement to use main's runloop, this is definitely not going to work. Each of the `::run` methods are executing in dedicated threads.

Alternatively, is there a way to supply a runloop to the observer (guessing this is the thing attaching / adding to the runloop) such that a publisher thread's runloop can be used?

**Comment by russellhancox** [comment]
Unfortunately not, it's NSWorkspace itself that needs the main run loop.

Would moving all of the code in `main()` to a second thread be possible? Something like:

```cpp
int realMain(int argc, char* argv[]) {
  // stuff currently in main.
}

int main(int argc, char* argv[]) {
  std::thread osqueryMain(realMain, argc, argv);
#ifdef __APPLE__
  CFRunLoopRun();
#else
  osqueryMain.join();
#endif
}
```

**Comment by theopolis** [comment]
@PoppySeedPlehzr pointed me at http://stackoverflow.com/questions/6062299/how-to-add-an-observer-to-nsnotificationcenter-in-a-c-class-using-objective-c for a CF-based implementation.

Seems like there's a [lot of corroboration](https://developer.apple.com/library/prerelease/mac/documentation/CoreFoundation/Reference/CFNotificationCenterRef/index.html#//apple_ref/c/func/CFNotificationCenterAddObserver) with @russellhancox's note about `main`'s run loop being the only one the notification centers post updates into.

This means we'll have to refactor some of osquery's `Initializer` class to include platform-specific run handoffs. Right now they simply wait for a signal by joining on the set of services created via osquery's `Dispatcher` facilities. This will be somewhat OK to change, the logic will remain in that signals will be the primary tear-down mechanic. But we'll introduce overloadable `Initializer::run` and `Initializer::shutdown` (on OS X this will run-loop-stop) methods.

**Comment by fmanco** [comment]
Closing as this is stale. If anyone have interest on this please reopen.
