### ISSUE TITLE
Table(s) for guest virtual machine details and configuration

### ISSUE THREAD

**Issue by Happy-Dude** [facebook/osquery#1945]
In an incident response setting, I found it difficult to correlate guest virtual machine log entries (DHCP, IP, MAC, packet captures, etc.) to an actual host system and user.

Would it be possible for osquery to gather some of the basic system information for us? I'm not sure where the "library" listing of virtual machines are stored, but if possible, can osquery parse that information, and gather configuration information from the corresponding config files?

That would certainly make it easier to correlate which hosts these guests are being launched from and with what virtual hardware settings (MAC, virtual disk location + size, shared folders, etc.). Anything for VirtualBox, VMware, KVM, Xen, qemu would be awesome.

**Comment by Happy-Dude** [comment]
I am actually very interested in this feature, and if some guidance can be provided, I would love to research where to gather this information and see if I can contribute back to the project!

**Comment by zwass** [comment]
Hi there, @Happy-Dude. Sorry we missed this.

If you can identify where the data you'd like to collect is stored (which file, API, etc.), we can guide you through implementing a virtual table to make it available in osquery. See the [creating tables](http://osquery.readthedocs.io/en/stable/development/creating-tables/) documentation for an overview of how this is done.

**Comment by fmanco** [comment]
This is stale and not well defined so I'm going to close. If you still care about this please open a [Feature Request issue](https://github.com/facebook/osquery/issues/new?template=Feature_Request.md) with more details.
