### ISSUE TITLE
Dependent libraries build & installation for Windows

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1956]
**Ensure that all dependencies either build on Windows or have existing packages:**

* [x] Bzip2
- [x] Readline (or equiv for SQLite's shell)
- [x] RocksDB (optional)
- [x] Boost (filesystem, regex, system)
- [x] Thrift 0.9.3
- [x] Glog
- [x] Gflags
- [x] Gtest Gmock (should be inline with third-party repo)
- [ ] google bechmark (optional for now)

**Other dependency-related decisions:**
- [x] Select a compiler and build environment.
- [ ] Document prerequisites required for a Windows build, and create a provision script to install those that can be installed automatically.
- [x] Integrate Windows into the build system, but the build will fail with expected build errors (e.g. `fork()` not found).

**Comment by yying** [comment]
Possible alternative for readline: https://github.com/arangodb/linenoise-ng

**Comment by theopolis** [comment]
That looks great, I wonder if it could use a seed of all the SQL schema to do completion too.
