### ISSUE TITLE
Allow queries to define decorators or triggers

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1960]
A scheduled query definition could include:
```json
"tmp_process_signatures": {
  "query": "select * from processes where path LIKE '/tmp/.%';",
  "decorators": [
    {"query": "select * from signature", "join": "path"}
  ] 
}
```

This is a little strange when considering how to join programatically. SQL is a much more appropriate candidate.

For almost all tables, a `UNION`, `LEFT JOIN` or subselect is appropriate.

For event-based tables, this is a bit more tricky. If tables had a primary key defined we could determine which columns were used to join. Or a subscriber could explicitly define foreign keys. Since the feature we really want is:

1. Process **event** happens
2. Grab the binary details
3. Grab some signatures
4. Inspect the environment variables

And similar semi-abstract relations / actions.

**Comment by theopolis** [comment]
We now have "decorator" queries that emit "decorations" and run at configuration load, before every scheduled query, or on an interval. Check out the documentation here: http://osquery.readthedocs.io/en/stable/deployment/configuration/#decorator-queries

We still should solve for the "trigger" or query-specific decoration request.

**Comment by zwass** [comment]
Maybe I'm being misled by the example above, but how does this differ from just doing the join in the query (something like `select * from processes join signature using (path) where path LIKE '/tmp/.%';` for the example)? Is the idea that the decorator query being joined in is expensive and SQLite might not optimize it appropriately?

**Comment by theopolis** [comment]
I can't think of any reason to use a `JOIN` as a 'triggered' query. We can close this and wait for someone to raise a good use case worthy of re-opening.
