### ISSUE TITLE
Syslog table configuration errors

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#1964]
Placeholder, for now (just need an issue number to use with `RLOG`).

**Comment by my-janala** [comment]
I am struggling to fix syslog table, still nothing is being populated on _syslog_ table. The log shows 

> I0719 15:32:07.685186  5266 syslog.cpp:87] Successfully opened pipe for syslog ingestion

**Comment by jacknagz** [comment]
> Does rsyslogd report any errors in /etc/log/sysog?

shouldn't that be `/var/log/syslog`

**Comment by zwass** [comment]
@jacknagz Yes, will correct above.

**Comment by zwass** [comment]
@my-janala Come on over to the [osquery Slack](https://osquery-slack.herokuapp.com/) if you would like more help debugging. You can catch my attention by mentioning me with @zwass in there.

**Comment by DwijadasDey** [comment]
@zwass The steps for debugging syslog table is nice one. I am also facing the same issue but with syslog-ng. In my case syslogs do logged in the file /var/log/osquery/osqueryd.results.log as i can test and check the logs through $ tail -f /var/log/osquery/osqueryd.results.log | grep 'test log foo' if i issue $ logger "test log foo" from another terminal. 

But the syslogs does not appear in the table syslog. The name pipe has been created and syslog-ng is running as root:adm. Although i have checked with root:root as well.

> ls -l /var/osquery/syslog_pipe
> pr--rw---- 1 root adm 0 Apr 14 15:41 /var/osquery/syslog_pipe

There is no error in /var/log/syslog as well. I am using Ubuntu 16.10 and not firewall is running.

**Comment by zwass** [comment]
@DwijadasDey I don't understand the issue you are experiencing. Please join the [osquery Slack](https://osquery-slack.herokuapp.com/) if you would like more help debugging. You can catch my attention by mentioning me with @zwass in there.

**Comment by zwass** [comment]
If anyone is interested in in using the `syslog` table with `syslog-ng`, please take a look at [this discussion](http://lists.balabit.hu/pipermail/syslog-ng/2017-April/023679.html) for more information.
