### ISSUE TITLE
Potentially flaky OS X ASL table test

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#1975]
The ASL table test for OS X may be flaky:
```
[----------] 5 tests from AslTests
[ RUN      ] AslTests.test_add_query_op
[       OK ] AslTests.test_add_query_op (0 ms)
[ RUN      ] AslTests.test_create_asl_query
[       OK ] AslTests.test_create_asl_query (0 ms)
[ RUN      ] AslTests.test_read_asl_row
[       OK ] AslTests.test_read_asl_row (0 ms)
[ RUN      ] AslTests.test_convert_like_regex
[       OK ] AslTests.test_convert_like_regex (0 ms)
[ RUN      ] AslTests.test_actual_query
/Users/osquery/jenkins/workspace/osqueryPullRequestBuild/TargetSystem/osx11/osquery/tables/system/darwin/tests/asl_tests.cpp:174: Failure
Expected: (results.rows().size()) > ((size_t)0), actual: 0 vs 0
[  FAILED  ] AslTests.test_actual_query (16461 ms)
[----------] 5 tests from AslTests (16461 ms total)
```

From [build 2526](https://jenkins.osquery.io/job/osqueryPullRequestBuild/2526/TargetSystem=osx11/console), @zwass if you have a second, would you mind triaging this?

**Comment by theopolis** [comment]
Another failure: https://jenkins.osquery.io/job/osqueryPullRequestBuild/2528/TargetSystem=osx11/console this time the build infra was relatively quiet, all machines in the PR build should have had plenty of cycles.

**Comment by zwass** [comment]
Ah, yeah, this test checks that there are some messages in the Console log. Are these machines "reset" regularly? Would you object to the test throwing a message into ASL and then checking for it?
