### ISSUE TITLE
darwin - SIP table column output (esp. apple_internal) should match when not in transition

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#1978]
I currently have `apple_internal` and `dtrace` protections disabled via csrutil - my impression is that the nvram column could be out-of-sync with the current state of the config until a reboot, but if it hasn't been changed (via a blessed kext like [rootfool](https://reverse.put.as/2015/10/12/rootfool-a-small-tool-to-dynamically-disable-and-enable-sip-in-el-capitan/#more-2469) or a legit process while netbooted) I'd expect those values to match. Current output on my day-to-day machine, 10.11.4, osquery 1.7.2:
```
select * from sip_config;
+----------------------------+---------+---------------+
| config_flag                | enabled | enabled_nvram |
+----------------------------+---------+---------------+
| sip                        | 0       | 0             |
| allow_apple_internal       | 0       | 1             |
| allow_device_configuration | 0       | 0             |
| allow_kernel_debugger      | 0       | 0             |
| allow_task_for_pid         | 0       | 0             |
| allow_unrestricted_dtrace  | 1       | 1             |
| allow_unrestricted_fs      | 0       | 0             |
| allow_unrestricted_nvram   | 0       | 0             |
| allow_untrusted_kexts      | 0       | 0             |
+----------------------------+---------+---------------+
```  
Haven't iterated over all permutations to see if there are others who have output I don't expect from nvram, but can get a test system up if helpful to confirm. If there's something I'm not understanding about the nvram column please let me know.

**Comment by sharvilshah** [comment]
What does your `nvram -xp csr-active-config` output for your setup above?

**Comment by theopolis** [comment]
Here's mine (SIP disabled):
```
+----------------------------+---------+---------------+
| config_flag                | enabled | enabled_nvram |
+----------------------------+---------+---------------+
| sip                        | 0       | 0             |
| allow_apple_internal       | 0       | 1             |
| allow_device_configuration | 0       | 0             |
| allow_kernel_debugger      | 0       | 0             |
| allow_task_for_pid         | 1       | 1             |
| allow_unrestricted_dtrace  | 1       | 1             |
| allow_unrestricted_fs      | 1       | 1             |
| allow_unrestricted_nvram   | 1       | 1             |
| allow_untrusted_kexts      | 1       | 1             |
+----------------------------+---------+---------------+
```

And:
```
	<key>csr-active-config</key>
	<data>
	dwAAAA==
	</data>
```

**Comment by sharvilshah** [comment]
Thanks, the gist of this is that apple internal bit field is set anytime `csrutil enable` is invoked without `--no-internal`. 

But it seems `csrutil status` (and thus by extension the `csr_` syscalls) from non-recovery environment ignores the apple internal bit field, and hence there is a discrepancy between the active config read from nvram and from the syscall.

Found this while looking at dtrace source, which confirms that apple internal is for their internal development:

```c
/*
 * Check if DTrace is running on a machine currently configured for Apple Internal development
 */
boolean_t
dtrace_is_running_apple_internal(void)
{
...
	if (csr_check(CSR_ALLOW_APPLE_INTERNAL) == 0)
		return TRUE;
```

I guess we could update `enabled_nvram` column to ignore the internal flag so that it's more in line with what `csrutil status` from non-recovery environment reports. Thoughts @theopolis?

Needs a bit more testing and running through all permutations and combinations.

**Comment by theopolis** [comment]
Interesting, ideally we should report consistent values between the two columns, unless we determine there is non-expected results from the `csr_` API calls wrt the expected NVRAM settings.

**Comment by theopolis** [comment]
Unless someone throws up a pull request with good rational, I'm inclined to leave this as-is. The experience isn't nice, but we're consistent with what Apple tells us and if anything changes under their hood, it will be subsequently reflected in the table-- vs having to maintain an edge case.

**Comment by arubdesu** [comment]
Just want to chime in once more to call out that the edge-case-y-ness is, in specific, that apple_internal is the only value not reflected consistently. Totally fine with this being closed.
