### ISSUE TITLE
Build system detects Windows, fetches prereqs, and builds

### ISSUE THREAD

**Issue by dguido** [facebook/osquery#1985]
Part of #1956

**Comment by dguido** [comment]
We are currently testing a PowerShell provision script that ensures the proper development tools exist on the machine and acquires an archive of already compiled third party dependencies.

**Comment by yying** [comment]
So, I've been thinking about how to package the third-party dependencies better.

It seems like we can classify the third-party dependencies into three categories: buildable via CMake, compile+distribute as Chocolatey package, and pull pre-built binary from official source. 
 * **Buildable via CMake**
   * gflags
   * glog
   * gtest
   * rocksdb
   * thrift
   * zlib
 * **Compile+distribute as Chocolatey package**
   * bzip2
   * openssl
   * zlib
   * yara
   * snappy _<1>_
 * **Pull pre-built binary from official source**
   * boost
   * doxygen
   * snappy _<1>_
   * thrift compiler

_<1>_ - snappy can be obtained as a pre-built binary from a tangentially supported, third party(?) website.

For the packages that are buildable via CMake, we plan on `git clone`ing the package source in `third-party/` (alternatively, we can also follow how things are done now and use submodules) and building it.

For the compile+distribute packages, we plan on building the libraries once and distributing the result as a Chocolatey with the source to abide by whatever open source license is used.

For the pre-built binary packages, we plan on acquiring pre-built binaries from the official source and extracting them into `third-party/`.It might  be worth the effort to chocolatey-ify the pre-built binaries obtained from an official source for uniformity (assuming they don't already exist...).

**Comment by theopolis** [comment]
1. Why not Chocolatey everything?

2. If we choose to build from source during the `make deps` 'phase'. We should avoid overloading the use of our third-party submodule. I'd like to keep that to SQLite pre-releases and Gtest/Google benchmark/Gmock. Let's call extending third-party an anti-pattern.

 Instead let's define some sort of build macro for pulling/building these sources within powershell. Then choose some temporary directory to pull/build the sources, then install them as they are designed to be installed. Perhaps there's no `--prefix` equivalent?

 `./build` is designed to hold build artifacts, worst case let's generate the build outputs from third-party libraries there.

 Let's also avoid building anything that's not osquery in our CMake logic / `CMakeLists.txt`. `ExternalProject`s are cool, but we've refactored a few out and it's easier to run tests if we assume a resume from a previous `make deps` + snapshot phase.

**Comment by artemdinaburg** [comment]
It should be possible to Chocolately everything, with some caveats. All dependencies that build to shared libraries or are distributed as executables should be fine. Those that only build to static libraries may have problems. 

We suggested building from source for better compiler compatibility. Some of the dependencies (mainly thrift, can't recall right now if there were others) only build as static libraries on Windows. The official word from MS is to avoid statically linking libraries produced by different compiler versions (see: https://msdn.microsoft.com/en-us/library/bb531344.aspx)

For static libraries, there's a few possible solutions:

1. Fix the dependency to compile as a DLL.
2. Support only a specific Visual Studio version and package static libraries built with that version.
3. Git clone/submodule the dependency and build from source.
4. Package multiple versions of the library, each built with different Visual Studio releases.

**Comment by theopolis** [comment]
I don't like the concept of shipping DLLs for third-party libraries alongside our code. I like **installing** shared objects, and providing a shared object of our own if we plan on executing multiple processes concurrently.

The compiler variance issue is valid. Is there no way to ask Chocolately to build a 'local' version, such that you can provide a deterministic compiler? I guess it would also need a method for providing environment/build options too; such that the local build could produce non-default static libraries.

I'm assuming (4) means have Chocolately provide explicit COMPILER-LIB_VERSION-LIB named/tagged releases? That sounds wrong, let's avoid that unless there's some sort of native `:compiler_tag` supported in the package definitions. (I'm dog sciencing the diction here).

For (2) I think this gets closer to the appropriate approach, assuming Chocolately does not provide the nice feels to do what we need-- (2) can be modified to read: download tarballs of the version-bound source, compile, and 'install' the static libs into an expected subdirectory within `./build`.

**Comment by dguido** [comment]
Should have been closed with https://github.com/facebook/osquery/pull/2015, oops
