### ISSUE TITLE
Reproducible build environment

### ISSUE THREAD

**Issue by dguido** [facebook/osquery#1988]
Part of #1956 

This is a nice-to-have that would assist other developers helping out with the Windows build.

https://github.com/chocolatey/choco/wiki/DevelopmentEnvironmentSetup

**Comment by dguido** [comment]
We are currently testing a PowerShell provision script that ensures the proper development tools exist on the machine and acquires an archive of already compiled third party dependencies.

**Comment by yying** [comment]
I'm starting to chocolatey-ify some of the pre-build binary/library packages such as boost, snappy, and doxygen. Luckily, thrift-compiler is already represented in the chocolatey repository as "thrift". 

The current packages are maintained in another repository at the moment: https://github.com/trailofbits/osquery-chocolatey-packages

**Comment by dguido** [comment]
Should have been closed with https://github.com/facebook/osquery/pull/2015, oops
