### ISSUE TITLE
Verify all the prereqs link together on Windows

### ISSUE THREAD

**Issue by dguido** [facebook/osquery#1990]
Part of #1956

**Comment by yying** [comment]
We have a small tool to test this. Currently it is located here: https://github.com/trailofbits/osquery-windows-linking-test

Ideally, this is to be cloned within the oquery root directory.

**Comment by marpaia** [comment]
This is really neat. I've seen people do this directly in CMake via [`CHECK_CXX_SOURCE_COMPILES`](https://cmake.org/cmake/help/v3.0/module/CheckCXXSourceCompiles.html). For example, HHVM does this for dl: https://github.com/facebook/hhvm/blob/master/CMake/FindLibDL.cmake

**Comment by yying** [comment]
The tool verifies that everything links together without issue.
