### ISSUE TITLE
Tests for process abstraction

### ISSUE THREAD

**Issue by dguido** [facebook/osquery#1994]

**Comment by yying** [comment]
Running into some slight issues with the linker. However, got it down to just 6 errors:

<pre><code>
"C:\Users\user\work\osquery\build\windows10\OSQUERY.sln" (osquery_tests:Rebuild target) (1) ->
"C:\Users\user\work\osquery\build\windows10\osquery\osquery_tests.vcxproj.metaproj" (Rebuild target) (2) ->
"C:\Users\user\work\osquery\build\windows10\osquery\osquery_tests.vcxproj" (Rebuild target) (40) ->
(Link target) -> 
  filesystem_tests.obj : error LNK2019: unresolved external symbol "void __cdecl osquery::replaceGlobWildcards(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,enum osquery::GlobLimits)" (?replaceGlobWildcards@osquery@@YAXAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@W4GlobLimits@1@@Z) referenced in function "private: virtual void __cdecl osquery::FilesystemTests_test_canonicalization_Test::TestBody(void)" (?TestBody@FilesystemTests_test_canonicalization_Test@osquery@@EEAAXXZ) [C:\Users\user\work\osquery\build\windows10\osquery\osquery_tests.vcxproj]
  osquery.lib(init.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > & osquery::fLS::FLAGS_distributed_plugin" (__imp_?FLAGS_distributed_plugin@fLS@osquery@@3AEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@EA) referenced in function "public: void __cdecl osquery::Initializer::start(void)const " (?start@Initializer@osquery@@QEBAXXZ) [C:\Users\user\work\osquery\build\windows10\osquery\osquery_tests.vcxproj]
  osquery.lib(init.obj) : error LNK2019: unresolved external symbol "__declspec(dllimport) bool osquery::fLB::FLAGS_disable_distributed" (__imp_?FLAGS_disable_distributed@fLB@osquery@@3_NA) referenced in function "public: void __cdecl osquery::Initializer::start(void)const " (?start@Initializer@osquery@@QEBAXXZ) [C:\Users\user\work\osquery\build\windows10\osquery\osquery_tests.vcxproj]
  osquery.lib(interface.obj) : error LNK2019: unresolved external symbol "public: __cdecl apache::thrift::concurrency::StdThreadFactory::StdThreadFactory(bool)" (??0StdThreadFactory@concurrency@thrift@apache@@QEAA@_N@Z) referenced in function "public: void __cdecl osquery::ExtensionRunnerCore::startServer(class boost::shared_ptr<class apache::thrift::TProcessor>)" (?startServer@ExtensionRunnerCore@osquery@@QEAAXV?$shared_ptr@VTProcessor@thrift@apache@@@boost@@@Z) [C:\Users\user\work\osquery\build\windows10\osquery\osquery_tests.vcxproj]
  thriftmd.lib(BoostMonitor.obj) : error LNK2019: unresolved external symbol "bool __cdecl boost::this_thread::interruptible_wait(void *,struct boost::detail::timeout)" (?interruptible_wait@this_thread@boost@@YA_NPEAXUtimeout@detail@2@@Z) referenced in function "protected: bool __cdecl boost::detail::basic_condition_variable::do_wait<class boost::unique_lock<class boost::timed_mutex> >(class boost::unique_lock<class boost::timed_mutex> &,struct boost::detail::timeout)" (??$do_wait@V?$unique_lock@Vtimed_mutex@boost@@@boost@@@basic_condition_variable@detail@boost@@IEAA_NAEAV?$unique_lock@Vtimed_mutex@boost@@@2@Utimeout@12@@Z) [C:\Users\user\work\osquery\build\windows10\osquery\osquery_tests.vcxproj]
  C:\Users\user\work\osquery\build\windows10\osquery\Release\osquery_tests.exe : fatal error LNK1120: 5 unresolved externals [C:\Users\user\work\osquery\build\windows10\osquery\osquery_tests.vcxproj]

    110519 Warning(s)
    6 Error(s)
</code></pre>

**Comment by yying** [comment]
![osquery_test](https://cloud.githubusercontent.com/assets/4278185/14753690/e8c9fdb0-08a4-11e6-8c5c-76f005b2a798.png)

We can now generate an `osquery_tests.exe` executable on Win64. It can run but many tests fail.

**Comment by yying** [comment]
Closed with #2069
