### ISSUE TITLE
Reimplement SSL with SChannel

### ISSUE THREAD

**Issue by dguido** [facebook/osquery#2011]

**Comment by theopolis** [comment]
I thought we were preferring to stick with an OpenSSL API equivalent for our TLS implementation?

There are a few abstractions that assume OpenSSL: ASIO, and cpp-netlib.

**Comment by dguido** [comment]
We raised that as a potential course of action if removing the OpenSSL dependency for Windows became too difficult. I think there's a good shot we can ship osquery without OpenSSL. If we need, we can look into more maintainable libraries like LibreSSL, BoringSSL, or another compatible library if we discover the required modifications are untenable. Let's revisit this when we get to the Native SSL milestone and have a chance to look at ASIO and cpp-netlib in more detail.

**Comment by theopolis** [comment]
Let's stick with OpenSSL and we can tackle moving to another TLS implementation later.
