### ISSUE TITLE
Table for sudo users

### ISSUE THREAD

**Issue by FugiOnline** [facebook/osquery#2024]
I would like to see a table that lists user entries in the sudoers file. Could not find anything in the documentation related to this.

However, I'm not sure about all the requirements of sudo and potential security issues related to reading the sudoers file.

**Comment by marpaia** [comment]
I added this to #619, so I'll close this individual issue out.

**Comment by theopolis** [comment]
For the security concerns, this is appropriate. The sudoers file must be 600 or more restrictive. That works perfectly for osquery, as there's no privilege changes: if you run the daemon as root, you see things as root, if you run as a user you see them as that user.

The processes do drop privilege temporarily when acting on user data, or user controlled directories, but that's not an issue here.
