### ISSUE TITLE
minor error in parsing core column in cpu_time table

### ISSUE THREAD

**Issue by friedbutter** [facebook/osquery#2025]
` words[0].back()` only gives the last character of the string; if the number cpu > 10, then we will missing information. 

https://github.com/facebook/osquery/blob/6f034a71567ce237454943eb623e13eeafb4592a/osquery/tables/system/linux/cpu_time.cpp#L62

For example, I have 32 cores, and it only displays the last number of my core. 

> osquery> select * from cpu_time;
> +------+----------+---------+---------+-----------+---------+-----+---------+-------+-------+------------+
> | core | user     | nice    | system  | idle      | iowait  | irq | softirq | steal | guest | guest_nice |
> +------+----------+---------+---------+-----------+---------+-----+---------+-------+-------+------------+
> | 0    | 13262986 | 2302725 | 5915036 | 266422045 | 9540707 | 178 | 260569  | 0     | 0     | 0          |
> | 1    | 9460401  | 1087258 | 5422930 | 278348334 | 4309353 | 43  | 99041   | 0     | 0     | 0          |
> | 2    | 10331826 | 1065375 | 5452819 | 279481682 | 2643461 | 28  | 69357   | 0     | 0     | 0          |
> | 3    | 10161709 | 1052127 | 5416921 | 280451770 | 1984307 | 29  | 67741   | 0     | 0     | 0          |
> | 4    | 9117089  | 974625  | 5319659 | 282299951 | 1507869 | 0   | 34767   | 0     | 0     | 0          |
> | 5    | 8890770  | 956784  | 5281346 | 282779884 | 1297034 | 0   | 33622   | 0     | 0     | 0          |
> | 6    | 8790121  | 931163  | 5275847 | 283176547 | 1067825 | 0   | 33007   | 0     | 0     | 0          |
> | 7    | 8652040  | 917455  | 5228862 | 283456252 | 1003048 | 0   | 32282   | 0     | 0     | 0          |
> | 8    | 12517514 | 2482477 | 5310802 | 276488232 | 2141046 | 38  | 71376   | 0     | 0     | 0          |
> | 9    | 10092190 | 1285901 | 5136180 | 280302488 | 2134306 | 48  | 74618   | 0     | 0     | 0          |
> | 0    | 9863891  | 1058804 | 5106404 | 280736027 | 2280296 | 46  | 68738   | 0     | 0     | 0          |
> | 1    | 9809138  | 996382  | 5136410 | 280867174 | 2271246 | 43  | 70856   | 0     | 0     | 0          |
> | 2    | 9030617  | 900426  | 5095703 | 282166976 | 2058845 | 0   | 35800   | 0     | 0     | 0          |
> | 3    | 8924431  | 886594  | 5095861 | 282156103 | 2176308 | 0   | 35905   | 0     | 0     | 0          |
> | 4    | 8798556  | 876226  | 5105031 | 282742302 | 1735515 | 0   | 35444   | 0     | 0     | 0          |
> | 5    | 8739026  | 878004  | 5079751 | 282687966 | 1870318 | 0   | 34823   | 0     | 0     | 0          |
> | 6    | 3901073  | 470998  | 1947340 | 294308740 | 301490  | 0   | 2977    | 0     | 0     | 0          |
> | 7    | 3523798  | 363970  | 1929052 | 294742427 | 326114  | 0   | 2572    | 0     | 0     | 0          |
> | 8    | 2556860  | 233288  | 1809077 | 296225212 | 165684  | 0   | 2309    | 0     | 0     | 0          |
> | 9    | 2525109  | 219751  | 1773702 | 296141815 | 200400  | 0   | 2049    | 0     | 0     | 0          |
> | 0    | 2315183  | 225767  | 1736408 | 296514010 | 222545  | 0   | 1982    | 0     | 0     | 0          |
> | 1    | 2256934  | 226750  | 1707132 | 296621497 | 219334  | 0   | 1843    | 0     | 0     | 0          |
> | 2    | 2274732  | 217964  | 1714505 | 296673920 | 162208  | 0   | 1678    | 0     | 0     | 0          |
> | 3    | 2215102  | 212828  | 1692793 | 296725910 | 204677  | 0   | 1739    | 0     | 0     | 0          |
> | 4    | 2844270  | 329812  | 1862006 | 295619165 | 485157  | 0   | 2516    | 0     | 0     | 0          |
> | 5    | 2539868  | 256863  | 1786038 | 296350574 | 231631  | 0   | 2170    | 0     | 0     | 0          |
> | 6    | 2533179  | 226275  | 1768918 | 296420824 | 237222  | 0   | 2143    | 0     | 0     | 0          |
> | 7    | 2529305  | 222446  | 1755505 | 296522744 | 183965  | 0   | 2134    | 0     | 0     | 0          |
> | 8    | 2307415  | 210544  | 1732228 | 296720332 | 252798  | 0   | 1972    | 0     | 0     | 0          |
> | 9    | 2213447  | 202231  | 1628348 | 296611303 | 576932  | 0   | 2054    | 0     | 0     | 0          |
> | 0    | 2241225  | 201603  | 1676389 | 296812053 | 315319  | 0   | 2118    | 0     | 0     | 0          |
> | 1    | 2182951  | 198390  | 1676026 | 296672790 | 523997  | 0   | 1801    | 0     | 0     | 0          |
> +------+----------+---------+---------+-----------+---------+-----+---------+-------+-------+------------+

**Comment by friedbutter** [comment]
@theopolis please assign this to me. I seem to unable to assign this to myself....

**Comment by theopolis** [comment]
Try now :)

**Comment by friedbutter** [comment]
Still no  💔

**Comment by cwalkatron** [comment]
+1

**Comment by friedbutter** [comment]
merged.
