### ISSUE TITLE
add memory info table

### ISSUE THREAD

**Issue by friedbutter** [facebook/osquery#2028]
Parse out `/proc/meminfo`. For details, see https://www.centos.org/docs/5/html/5.2/Deployment_Guide/s2-proc-meminfo.html 

Fields we care about:

`MemTotal `
`MemFree `
`Buffers`
`Cached`
`SwapCached`
`Active`
`Inactive`
`SwapTotal`
`SwapFree`

**Comment by friedbutter** [comment]
@theopolis currently, the unit used in `/proc/meminfo` is in KB. Do you care if we keep it, or should we convert to Byte?

**Comment by theopolis** [comment]
Do you have an example for OS X?

**Comment by friedbutter** [comment]
I'm not sure about mac yet. With a quick research, I found that we can do something like this for mac to get basic information about the memory usage:
https://github.com/giampaolo/psutil/blob/1b71ca531ba377e8c71d2c581debfce7eae35a40/psutil/_psutil_osx.c

And vm_stat provides some basic information as well:
http://opensource.apple.com//source/system_cmds/system_cmds-550.10/vm_stat.tproj/vm_stat.c

I would have to do more research to see if we can get the same columns for osx as well. I added a tag Linux for now until we can find a way to do this for osx. 

@theopolis, should we implement some columns that we can with above code for now  and leave the rest of the columns empty until we find out more details?

**Comment by sharvilshah** [comment]
On OS X, since most of these are exposed via `sysctl`, one could probably just grab them via `system_controls` (in particular the `vm` and `hw` subsystem) table.

**Comment by theopolis** [comment]
Closed by #2282.

**Comment by rkgrep** [comment]
Hello! Is this going to be ported for OS X?
