### ISSUE TITLE
Allow adhoc `--pack` CLI runtime option for osqueryi for query pack(s)

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#2041]
For testing, demo, or other 'check everything NOW' purposes, having the ability to do an on-demand run of a query pack would be awsm. (Minus osqueryd-dependent behavior, of course).

**Comment by theopolis** [comment]
See the implementation here: https://github.com/facebook/osquery/commit/0ffe0c9d16726ef1e2a71163a771d623d6cd381f

That should allow pack testing. :)
