### ISSUE TITLE
Fails to build on Debian Jessie

### ISSUE THREAD

**Issue by mchugh19** [facebook/osquery#2055]
After commenting out osquery/tools/provision/debian.sh
```
  #package ruby1.8-dev
```

during the ```make deps``` step, I get the error 
```
[+] aws_sdk has not been extracted. extracting...
/tmp/osquery-provisioning/aws-sdk-cpp-0.10.6/build /tmp/osquery-provisioning
CMake Error at CMakeLists.txt:19 (cmake_minimum_required):
  CMake 3.1.2 or higher is required.  You are running version 3.0.2


-- Configuring incomplete, errors occurred!
Makefile:88: recipe for target 'deps' failed
make: *** [deps] Error 1
```

Looks like Jessie is only has a package for 3.0.2. Boohoo :(

**Comment by marpaia** [comment]
We (Facebook) don't maintain Debian build infrastructure on https://jenkins.osquery.io, so we can't prioritize fixing this at the moment. If you (or anyone else) regularly uses Debian and would like to augment the build/provision tooling to install a more modern version of CMake, we'd be happy to offer guidance and support!

**Comment by theopolis** [comment]
For Jessie (and other Debians for that matter):

Change: https://github.com/facebook/osquery/blob/master/tools/provision/debian.sh#L60
To call `install_cmake`: https://github.com/facebook/osquery/blob/master/tools/provision/lib.sh#L74

As it is doing for Wheezy and you'll be set.

**Comment by theopolis** [comment]
@mchugh19, any interest in submitting a patch to build CMake from source using the suggestions I posted a few days ago? :dancer:

**Comment by mchugh19** [comment]
Sorry for the delay, I just returned from traveling. The install_cmake step worked, but it also needed the ruby1.8-dev package assigned to wheezy. 

Thanks all!
