### ISSUE TITLE
OS/X: osqueryd worker respawning too quickly

### ISSUE THREAD

**Issue by readshaw** [facebook/osquery#2057]
I have rolled out the osquery 1.7.2 client to approx 20 OS/X systems with minimal issues so far.  We're using a remote enroll/config/log server.

On one system, a Mac Mini, I am getting crashes with the client respawing too quickly.  I can reproduce this with the client running from the command line as well, with a command line as follows:

/usr/local/bin/osqueryd --verbose --debug --force --pidfile /var/osquery/osqueryd.pidfile --database_path /var/osquery/osquery.db --tls_hostname <host> --tls_server_certs /var/osquery/tls-server-certs.pem --enroll_tls_endpoint /prod/endpoint-enrollment --config_tls_max_attempts 3 --config_tls_refresh 600 --config_plugin tls --config_tls_endpoint /prod/endpoint-config --logger_plugin filesystem --log_result_events --disable_distributed --disable_kernel --schedule_splay_percent 10 --disable_events

I've also tried with  --disable_watchdog and that didn't seem to make any difference.

A crash dump is attached.

[osqueryd_2016-04-30-133802_display1.crash.zip](https://github.com/facebook/osquery/files/243440/osqueryd_2016-04-30-133802_display1.crash.zip)

**Comment by theopolis** [comment]
The crash is a SIGILL, that usually means the binary was compiled with AVX instructions and you're deploying to a Core 2 processor, or earlier, which does not have Intel AVX.

Is this 1.7.2 downloaded from our packages at https://osquery.io/downloads? Or is it from brew or did you compile/distribute yourself?

If you're building packages yourself consider running:
```
export RUN_RELEASE_TESTS=1
./tools/build.sh
```

Or:
```
RUN_RELEASE_TESTS=1 make test
```

The details are somewhat described here: http://osquery.readthedocs.io/en/stable/development/building/

**Comment by readshaw** [comment]
That explanation makes a lot of sense. The system on which this issue is
occurring is a mac mini and our oldest one of those.  We build osquery
ourselves to bundle custom configurations.

Regards,
Neil.
