### ISSUE TITLE
MinorEnhancement: `--version` output shouldn't include name of binary

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#2075]
This is a small niggle, but running `--version` against osqueryd or osqueryi should only result in the version string, it currently returns e.g. `osqueryd version 1.7.3`.

**Comment by theopolis** [comment]
I'm torn, there's no hard and fast rule or standard for this. Thrift does it, clang does it, and since we've been doing it I hesitate to break any version-detection folks have already set up. If you want a super clean version without having to parse:
```
$ osqueryi --csv --header=no "select version from osquery_info"
1.7.4-10-g30df6ab
```

**Comment by theopolis** [comment]
Feel free to re-open if there's a lot of passion about remove the prefixed strings.

**Comment by arubdesu** [comment]
nah, I get it that it's been that way for a bit, thanks for the one-liner to get clean output
