### ISSUE TITLE
"WindowsError" thrown when unhandled exception raised in tools/get_platform.py

### ISSUE THREAD

**Issue by defaultnamehere** [facebook/osquery#2136]
This code is run when installing on Debian:
`result = commandOutput(["lsb_release", "-cs"])`
If lsb_release is not installed (which happens with the debian:8 base Docker image), then an error other than subprocess.CalledProcessError is thrown.
This is the error handling code:

  ```
          try:
              output = subprocess.check_output(cmd)
              return output
          except subprocess.CalledProcessError:
              return None
          except WindowsError:
              return None
```
WindowsError isn't defined in this file, so the error handling fails. This prevents CMake from finding the right directory, so `make` and `make packages` don't work.

**Comment by PoppySeedPlehzr** [comment]
Fixed with [7e80f7f517c35870ec3589c8c527d41e304fddd1](https://github.com/facebook/osquery/pull/2143/commits/7e80f7f517c35870ec3589c8c527d41e304fddd1)
