### ISSUE TITLE
osquery for SuSE SLES

### ISSUE THREAD

**Issue by tirili** [facebook/osquery#2138]
Hello all,

is there a possibity to run osquery in SuSE SLES?
Any help is appreciated.

Thomas

**Comment by theopolis** [comment]
Hi @tirili, have you tried compiling on the version of SUSE you're using?

**Comment by theopolis** [comment]
The new build system #2169 should make building on SuSE pretty easy. If the 5 dependencies are installed: http://osquery.readthedocs.io/en/latest/development/building/

**Comment by rahulkrvnit** [comment]
Hi theopolis

I have already installed all dependencies as mentioned above in Suse SLES and still "make deps" fails.
could you please help here?

RahulK

**Comment by spasam** [comment]
@rahulkrvnit Which version of SuSE? Am currently looking at Vagrantfile changes for build and I can add SuSE boxes and try it out if I know the version.

**Comment by rahulkrvnit** [comment]
Hi spasam
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 1


cud you pls let me know where to add such things in future

**Comment by theopolis** [comment]
You should be able to install the RPM from: https://osquery.io/downloads/ if you'd like to build-your-own osquery on SuSE then we'll have to wait for #3714.
