### ISSUE TITLE
Discussion on improving `make format`

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#2145]
In its current state, `make format` only runs on files that are _staged_ in git. This leads to confusion and missed opportunities to perform formatting.

I am interested in exploring how we can change the behavior to make it easier for contributors to provide properly formatted code.

Potential options:

1. Use the `-f` flag in [git-clang-format.py](https://github.com/facebook/osquery/blob/master/tools/formatting/git-clang-format.py#L99). This will run `clang-format` on all files that differ from HEAD, and not just staged files.
2. Set the commit to compare with to `master`. This will run `clang-format` on all files that have changed from master, which could catch files that were changed in one commit but not in the current state of the tree. Many folks are making multiple commits and then squashing them, and this could help with missing formatting in that workflow.
3. Both of the above.
4. The nuclear option. Run `clang-format` on every file, every time `make format` is run. We could do one commit fixing all the outstanding formatting, and then `clang-format` should only make changes to new files anyway.

Hoping we can have some discussion around these and other possibilities...

**Comment by theopolis** [comment]
I like option 4, which exists as `make format-all`. The biggest problem, which also exists for normal `make format`, is the differing versions of `clang-format`. This leads to a seesawing of style nitpicks from commit to commit as each version goes back and forth. IIRC there are still some things `clang-format` cannot parse so adding format guards is needed too.

2 also works + some documentation in CONTRIBUTING. That might do the trick for now.

**Comment by marpaia** [comment]
Yeah, as @theopolis said, the seesawing of people with different versions of clang-format installed has historically kept us from doing this. It seems like option 1 would be pretty rad though if the thing we were trying to solve for is that people are running `make format` before they run `git add`?

**Comment by zwass** [comment]
It sounds like 4 would be the most desirable option, but problems with `clang-format` versions differing prevent it.

What do you think of option 3? It seems like it will be the most straightforward for users. It should work in the following scenarios that are currently missed:
1. `make format` is run before `git add`
2. `make format` is run after committing
3. `make format` is run on a stack of commits

The assumptions here are (a) `clang-format` is non-destructive (eg. running it on unstaged files is okay) (b) comparing against `master` is reasonable in most scenarios.

**Comment by theopolis** [comment]
It is nice to see what `clang-format` changed. :)
1. Stage edits
2. `make format`
3. `git diff`

The tool is destructive with respect to several pre-processor control flow expressions.

But let's give it a shot and see how it works.

**Comment by zwass** [comment]
I'll take some time to play with option 3 and see how it works...

**Comment by theopolis** [comment]
Check out the new "audit" CI build job, which uses `make format_master` to implement 2, and the normal `make format` is modified to implement 1.
