### ISSUE TITLE
Database corruption/invalidation/scheduled query update leads to inability to diff results

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2162]
If a host's database is corrupted or removed the next time a scheduled query runs it will log ALL rows. If a scheduled query is updated to select different columns, the query results differential will produce undefined behavior.

Let's brainstorm ways to continue to yield expected results in these scenarios.

**Comment by fuzzball5000** [comment]
I may have seen this behaviour before... So just for clarity, a query ran after the local database is removed will return all rows as there is no longer a stored state of the previous queries?

**Comment by theopolis** [comment]
Correct!

**Comment by theopolis** [comment]
I don't think there's much we can do to prevent that. But we can identify when a query's results return "the whole table scan" using a new key in the log result.

**Comment by theopolis** [comment]
It may also help to "version" the queries in a schedule. This could happen transparently if you assume resilient state. The daemon write a query and the name into the persistent store and an initial version 0, if a different query with that same name is provided then the version is incremented. Then the log lines can again be extended to include the version if !0.

**Comment by fuzzball5000** [comment]
Versioning queries sounds like a reasonable approach, I had the thought of some kind of checksum in my head, but thinking through that idea it would probably be excessively complex.

**Comment by theopolis** [comment]
@mwielgoszewski  was experiencing something related, the daemon was running and logging `added` for a query, but the query's results were not available in the RocksDB backing storage-- only the `configurations[QUERY_NAME]` storage.

**Comment by fuzzball5000** [comment]
Not seen that myself from any of my fleet... Any more information on the context or events prior to it happening? Did the daemon quit and get a restart? Did the query get changed before this happened?

**Comment by fuzzball5000** [comment]
I should say for clarity, I have seen all rows returned unexpectedly before, just not what I presume is an added event with no data?

**Comment by theopolis** [comment]
Ah, what I meant was, `added` with the complete results too. And that event would be logged every time the query ran. Then inspecting the database on the machine's disk using `--database_dump` showed that there were no logged results. That corroborates the "seeing the same event twice" observation. If the DB does not have a record of previous results, there is nothing to diff against. To be clear though, I am not yet sure how to reproduce as this *should not* happen. If there are DB errors while inspecting/diffing the output of a scheduled query the daemon should log a DB status error and NOT log the results.

In all cases we need to be more aggressive and loud about DB errors during schedule execution.

**Comment by fuzzball5000** [comment]
Ok, shall spin up a test machine and kick it around a bit, see if I can get a failure in some kind of repeatable way. Annoyingly, I had an instance which may have duplicating events in a reliable way, but is now sadly trashed; I just blamed it on an unreliable Splunk indexer I was having problems with at the time :( 

Also, just to make sure I'm looking in the right place.... In rocksdb.cpp, we're parsing out the RocksDB logs for errors opening the DB connection, then on line 288 checking if Rocks is throwing an I/O error on write?

**Comment by theopolis** [comment]
I wrote some pretty basic logic:
```cpp
  for (size_t i = 0; i < 1000; i++) {
    auto actual = std::to_string(i);
    auto s = osquery::setDatabaseValue(osquery::kPersistentSettings, "test1", actual);
    if (!s.ok()) {
      std::cout << "Cannot set: " << s.getCode() << " " << s.getMessage() << std::endl;
    }
    std::string result;
    s = osquery::getDatabaseValue(osquery::kPersistentSettings, "test1", result);
    if (!s.ok()) {
      std::cout << "Cannot get: " << s.getCode() << " " << s.getMessage() << std::endl;
    }
    if (result != actual) {
      std::cout << "Result mismatch actual=" << result << " expected=" << actual << std::endl;
    }
    ::sleep(1);
  }
```

Then played around with corrupting the DB's disk contents.
```
/tmp/osquery.db  » ls -la
total 32
drwx------   7 reed  wheel   238 Jul  6 17:44 .
drwxrwxrwt  31 root  wheel  1054 Jul  6 17:44 ..
-rw-r--r--   1 reed  wheel   252 Jul  6 17:44 000003.log
-rw-r--r--   1 reed  wheel    16 Jul  6 17:44 CURRENT
-rw-r--r--   1 reed  wheel    33 Jul  6 17:44 IDENTITY
-rw-r--r--   1 reed  wheel     0 Jul  6 17:44 LOCK
-rw-r--r--   1 reed  wheel   266 Jul  6 17:44 MANIFEST-000004
/tmp/osquery.db  » chmod 000 000003.log 
/tmp/osquery.db  » ls -la
total 32
drwx------   7 reed  wheel   238 Jul  6 17:44 .
drwxrwxrwt  31 root  wheel  1054 Jul  6 17:44 ..
----------   1 reed  wheel   628 Jul  6 17:45 000003.log
-rw-r--r--   1 reed  wheel    16 Jul  6 17:44 CURRENT
-rw-r--r--   1 reed  wheel    33 Jul  6 17:44 IDENTITY
-rw-r--r--   1 reed  wheel     0 Jul  6 17:44 LOCK
-rw-r--r--   1 reed  wheel   266 Jul  6 17:44 MANIFEST-000004
/tmp/osquery.db  » ls -la
total 32
drwx------   7 reed  wheel   238 Jul  6 17:44 .
drwxrwxrwt  31 root  wheel  1054 Jul  6 17:44 ..
----------   1 reed  wheel   715 Jul  6 17:45 000003.log
-rw-r--r--   1 reed  wheel    16 Jul  6 17:44 CURRENT
-rw-r--r--   1 reed  wheel    33 Jul  6 17:44 IDENTITY
-rw-r--r--   1 reed  wheel     0 Jul  6 17:44 LOCK
-rw-r--r--   1 reed  wheel   266 Jul  6 17:44 MANIFEST-000004
```

I expected this to be the case since the DB "connection" is persistent and has already opened the file descriptor. However:
```
/tmp/osquery.db  » rm 000003.log 
override ---------  reed/wheel for 000003.log? yes
/tmp/osquery.db  » ls -la
total 24
drwx------   6 reed  wheel   204 Jul  6 17:46 .
drwxrwxrwt  31 root  wheel  1054 Jul  6 17:44 ..
-rw-r--r--   1 reed  wheel    16 Jul  6 17:44 CURRENT
-rw-r--r--   1 reed  wheel    33 Jul  6 17:44 IDENTITY
-rw-r--r--   1 reed  wheel     0 Jul  6 17:44 LOCK
-rw-r--r--   1 reed  wheel   266 Jul  6 17:44 MANIFEST-000004
```

And the application keeps going! This is writing to RocksDB's in-memory [memtables](https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide#flushing-options). Though it may be attempting to write to disk and still have the file descriptor open.

Before `rm`:
```
osquery> select * from process_open_files where pid = '37300';
+-------+----+-----------------------------------------+
| pid   | fd | path                                    |
+-------+----+-----------------------------------------+
| 37300 | 0  | /dev/ttys001                            |
| 37300 | 1  | /dev/ttys001                            |
| 37300 | 2  | /dev/ttys001                            |
| 37300 | 3  | /private/tmp/osquery.db                 |
| 37300 | 4  | /private/tmp/osquery.db/LOCK            |
| 37300 | 5  | /private/tmp/osquery.db/000003.log      |
| 37300 | 6  | /private/tmp/osquery.db/MANIFEST-000004 |
+-------+----+-----------------------------------------+
```

After:
```
osquery> select * from process_open_files where pid = '37300';
+-------+----+-----------------------------------------+
| pid   | fd | path                                    |
+-------+----+-----------------------------------------+
| 37300 | 0  | /dev/ttys001                            |
| 37300 | 1  | /dev/ttys001                            |
| 37300 | 2  | /dev/ttys001                            |
| 37300 | 3  | /private/tmp/osquery.db                 |
| 37300 | 4  | /private/tmp/osquery.db/LOCK            |
| 37300 | 5  | /private/tmp/osquery.db/000003.log      |
| 37300 | 6  | /private/tmp/osquery.db/MANIFEST-000004 |
+-------+----+-----------------------------------------+
```

We'd generally have to release the DB connection, then force a re-`open` of the FD. This does not work for machines using the `process_events` or other high-rate event publisher. :/

**Comment by fuzzball5000** [comment]
Heh, OK so it looks like we both spent our respective afternoons doing similar testing ;) This is good, as we both got the same results! 

I created a osquery.conf with a query against the process table scheduled every 60 seconds, then a bash script to spawn and kill a process with a similar delay. Results into Splunk. 

I then attached strace to the osquery daemon and it's worker PIDs, and began dd'ing some urandom bytes into Rock's .sst files. As you have seen, it keeps on flying regardless. Nothing in the strace output would have indicated that it had a problem. Killing it and restarting then resulted in an DB error, as expected. 

So yes, there's no error being emitted as the only opportunity for doing so is on the re-connection to the DB, which won't happen (and as you say, shouldn't be the way we solve this one for performance reasons) until osqueryd is restarted. 

What output did you get from your code during this test? I wasn't able to keep track of events being logged by osqueryd as I got distracted by an incident, so will pick this back up today. I did have one thought though, *if* damaging or removing the DB files will eventually result in either no data being returned on a get, or unpredictable results, could we write a little logic (probably very similar to what you wrote up there) to first set a random value to a known key on init, persist it in memory, then periodically read this value back and error if the returned value != the initially seeded one? It's a little hacky, but it would give us a way of detecting when the already open DB starts to misbehave.

**Comment by theopolis** [comment]
This PR (with a force sync for most data) forces the error to occur much faster! https://github.com/facebook/osquery/pull/2228

Bubbling up the error from RocksDB into osquery's database handling code is the first step. We can then force the daemon to take action based on runtime corruption.

**Comment by fuzzball5000** [comment]
Nice, didn't even know that was possible mid connection. Giving Rocks more opportunities to cough out an error is better than attempting to infer one in OSQ 👍

**Comment by theopolis** [comment]
@PickmanSec you mentioned seeing `IOError`s in your logs. I believe they come from this change (improvement) and result from something causing permissions in `/var/osquery/osquery.db` to change. We can work through some DB-auto-remediation options such as a very basic "re-open".

**Comment by theopolis** [comment]
Has anyone seen/encountered remaining issues here? I'd like to close this out.
