### ISSUE TITLE
Increase configurability around logging of distributed queries

### ISSUE THREAD

**Issue by mwielgoszewski** [facebook/osquery#2164]
For purposes of transparency and allowing end users to audit the distributed queries executed, I'd like to see a log statement emitted any time a distributed query is executed by a node. We can achieve this simply by adding an additional log statement to the `Distributed::runQueries` method, similar to the `Scheduler::launchQuery` method:

osquery/osquery/dispatcher/scheduler.cpp:
```
59:  VLOG(1) << "Executing query: " << query.query;
```

However, both `VLOG(1)` and `LOG(INFO)` are not emitted by default unless the `--verbose` cli flag is passed, which of course includes all other messages at this level.

In addition to `LOG` and `VLOG`, there are also `DLOG` and `TLOG` which adds additional confusion. I propose we consolidate the log utilities to just `VLOG`. With `VLOG`, we can avoid inundating logs with extraneous messages by finely tuning what messages get logged using V-style logging with the `-vmodule` flags.

Ideally, we should be able to just turn on logging of queries executed (regardless of their level), in addition to whatever is logged by default, so that other deployments don't all of a sudden start logging everything. For example, on servers I don't care to see this level of information, but on laptops, I'd prefer to be transparent with our employees what information is being collected, how often, etc, and provide them the capability to audit the logs themselves.

**Comment by theopolis** [comment]
Here's a potential solution: #2445

**Comment by theopolis** [comment]
Before we "re"-visit the logging configurability I think a simple:
1. Begin logging `LOG(INFO)` by default, aka without needing `--verbose`
2. Move schedule and distributed execution to `INFO`

...addresses the issues here.

Configurability about verbosity may be difficult to manage. I would love to reduce the `VLOG(1)` to `VLOG` and remove `TLOG` for clarity. `DLOG` for the debug build, for development help, where the messages/code is stripped for normal and release builds is OK too.
