### ISSUE TITLE
New test: PlatformFile operating on directory and file with restricted permisions

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2175]
The `PlatformFile` and other filesystem-based methods should include a test operating on files and directories with `0` permissions.

**Comment by theopolis** [comment]
We need a test mimicking: https://github.com/facebook/osquery/blob/master/osquery/filesystem/tests/filesystem_tests.cpp#L76

1. Open a file stream
2. Write content
3. Perform osquery filesystem API calls on the file

With an added: 2.5: change/restrict the permissions.

This test should perform as many methods from `PlatformFile` as possible: https://github.com/facebook/osquery/blob/master/osquery/filesystem/fileops.h

**Comment by vjon** [comment]
I've implemented this test as seen in this commit:
https://github.com/vjon/osquery/commit/cbb4d5f56a8704eac8513174d7e3823b40e145c4

I wanted to discuss this before submitting a Pull Request. At the moment, it performs pretty much all the functions defined in "fileops.h" for the sake of completion. However, some of these tests are of less relevance to the topic of a file with zero permissions, and it would be best to prune the list down to the essential tests before finalizing the commit.

**Comment by theopolis** [comment]
Do you want to open that commit as a PR?
