### ISSUE TITLE
Add augeas table

### ISSUE THREAD

**Issue by thedrow** [facebook/osquery#2179]
Augeas is a configuration editing tool and API. It parses the configuration of many known formats.
This would be a useful addition to OSQuery.
I tried doing this myself but I'm stuck on linking against Augeas on OSX.
Augeas depends on gnulib which I expect to find in Linux/Unix but it's not available in OSX.
In fact, when you build libaugeas they pull the source and compile it themselves.
gnulib is also GP2L/LGPL2, which may or may not be a problem.
See the [build output](https://gist.github.com/thedrow/ae3a6e8732c27d7b61c7a71c768b3053#file-gistfile1-txt-L63).

We can disable the table for OSX but it's a shame since augeas itself is available through homebrew and it works just fine.
The other option would be to use a subprocess in order to invoke `augtool dump-xml` and parse that whenever a configuration file change but I expect that it would be slower than using the C API.

The development branch for this feature is in https://github.com/thedrow/osquery/tree/augeas-table

**Comment by marpaia** [comment]
On the topic of subprocessing: https://github.com/facebook/osquery/blob/master/CONTRIBUTING.md#calling-systems-tools

**Comment by thedrow** [comment]
Turns out augeas has another dependency that isn't released separately called [libfa](http://augeas.net/libfa/) and in order to link with augeas we need to link with libfa as well.

**Comment by thedrow** [comment]
The table works but it doesn't filter when I use LIKE operations.
I'm assuming this is because I don't use the QueryContext right?

**Comment by zwass** [comment]
@thedrow The SQLite engine should be performing the LIKE after your virtual table returns the results. You don't need to use the `QueryContext` in order to get this behavior, but you can take advantage of it to optimize retrieving the results.

If you add a failing test case to your branch, I can try to help you understand what's going on.

**Comment by thedrow** [comment]
@zwass I figured it out myself.
Rigth now I'm trying to figure out how to integrate [augeas path expressions](https://github.com/hercules-team/augeas/wiki/Path-expressions) into the QueryContext.
I want users to be able to use both SQL and Path Expressions to query that table.
I know that I need to use QueryContext::expandConstraints() but I haven't got to doing it yet.

**Comment by zwass** [comment]
Sorry, didn't realize that discussion was taking place both in this thread and in the PR...

What if you add a column like `path_exp`, and then access it directly through the `QueryContext`? I'm not sure that you need to use `expandConstraints` in this case.

**Comment by theopolis** [comment]
Done! Let's open subsequent issues to further refine how `augeas` is used.
