### ISSUE TITLE
Method for purging buffered logs in buffered logger plugins

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#2206]
The current implementation of [BufferedLogForwarder](https://github.com/facebook/osquery/blob/master/osquery/logger/plugins/buffered.cpp) does not include any mechanism for purging old logs that have not been sent successfully. In a bad scenario -- in which the target of the logs goes down, or otherwise errors while consuming the logs -- the buffered logs in RocksDB could grow unboundedly. This could cause major memory and/or disk usage in osqueryd from the buffer.

The potential for this bad scenario to occur necessitates providing some mechanism to remove unsuccessfully sent logs from the buffer.

@mimeframe suggests that the optimal solution for his and @jacknagz use case would be a max percentage of disk/memory to be used by the buffer. From my reading of the docs, RocksDB does not provide a way for us to accurately determine this information. Is anyone aware of a reliable way to calculate this?

Would a flag setting the max number of stored logs (and dropping oldest unsuccessful logs first) be a workable solution? Other ideas?

Curious for comments from @hackgnar (since you are using `BufferedLogForwarder` in the Kinesis/Firehose plugins), @theopolis, @marpaia and anyone who uses the TLS logger plugin.

**Comment by theopolis** [comment]
This is an accepted risk of the TLS logger plugins right now.

A potential % disk/mem implementation: expand the `DatabasePlugin` API to provide a method for inspecting the disk and memory usage. For RocksDB this could be a stat/walk of the `--database_path`, then you can implement similar logic to check `mounts` / `system_info` and determine usage.

**Comment by zwass** [comment]
Thanks for your comments @theopolis. Do you know if folks are using that plugin right now at scale without problems?

It sounds like we could get the _total_ disk size of the DB using the described method (and estimate a max memory size from that), but would we be able to extract the size for just the buffer?

**Comment by zwass** [comment]
Does anyone have an objection to adding a flag to set a max number of buffered events? We could always add another method later, but I'd like to implement something to prevent the possibility of unbounded growth.

**Comment by theopolis** [comment]
In my data an upper bound for number of events received a day from a single host is around `300000` (300k). The max number of events with the same `unix_time` for a host is `140000` (140k). If this is set to 1M or 2M it should be OK.

**Comment by theopolis** [comment]
Examples of worst case:
1. A host has it's DB wiped.
2. A new host with years of usage is added to the fleet.

**Comment by zwass** [comment]
So we could default it to 1M and allow a flag to set it (or 0 for no purging).

**Comment by theopolis** [comment]
Sounds like a plan!
