### ISSUE TITLE
Update references to homebrew installation in docs

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#2208]
"Install with brew" still features very prominently on https://osquery.io/downloads/.
The wiki also says "The easiest way to install osquery on OS X is via Homebrew".

As of recently, our Homebrew support has been limited, so we should update this documentation.

**Comment by theopolis** [comment]
This recommendation is still true with version 1.7.4. AFAIK the brew package cannot be updated past 1.7.4. When a 1.7.7+ version is determined stable we will need to remove the brew documentation.

**Comment by theopolis** [comment]
Website updated, now we just need to update the wiki.

**Comment by theopolis** [comment]
We still need to update this: http://osquery.readthedocs.io/en/stable/installation/install-osx/#homebrew-installation
