### ISSUE TITLE
Documentation about enable filesystem access and file tables

### ISSUE THREAD

**Issue by ppKrauss** [facebook/osquery#2216]
Perhaps is an error, but using standard apt-get osquery installation at UBUNTU 14 LTS, the `file` table not retrive  information. Checking guide, etc. no indication about "enable filesystem access".

-----
`osqueryi --version` returns *osqueryi version 1.7.7*. Using `osqueryi`, empty queries:

* `select * from file limit 10;`
* `select * from device_file limit 10;`
* ... any kind of `ls` command? ...

**Comment by theopolis** [comment]
Ah, right. There's plans to build this into the client, but there are certain tables that need a `WHERE` clause: https://osquery.io/docs/tables/#file. Check out the example queries there, and I know those "pin" icons are more or less unhelpful.

The near-term plan is to add an error message in the client when you attempt:
```sql
SELECT * FROM file;
```
Something like:
```
Table 'file' requires a predicate for one of the columns: path, directory
```

**Comment by theopolis** [comment]
So try:
```sql
SELECT * FROM file WHERE path = '/etc/group';
```

**Comment by ppKrauss** [comment]
It is running, thanks!  And  +1 vote to the  "plan about error message"! 

----

About the documentation, now I see that something exists... is the section "Tables with arguments" at
https://osquery.readthedocs.io/en/stable/introduction/sql/#tables-with-arguments

> Several tables, `file` for example, represent concepts that require arguments. (...) These tables, and their columns, are flagged {{icon here?}} in the [table documentation](https://osquery.io/docs/tables/) as requiring a column or as using a column to generate additional information.


... but beginner will ask, Why not something like `SELECT * FROM file('/etc/group','path');` ? 

----

... so, to complement error messages, this is a **documentation suggestion**:

*  let's put a link at [`osquery.io/docs/tables`](https://osquery.io/docs/tables/) in the icon "*required in WHERE clause*" to the `introduction/sql/#tables-with-arguments`;  and in each table like `file`, at table description, an alert icon to say *"this table requires a predicate"*.

* and show that icon in the `introduction/sql`...

* and add some kind of "NOTICE!" box in both texts &ndash; something like *«hey, beginner! no need of enable config, its not an installation error, it is only a strange SQL feature to send arguments»*.


Beginners will thank you!

**Comment by theopolis** [comment]
Thanks for those notes @ppKrauss! Totally agree!

The docs are kept within our [`./docs`](https://github.com/facebook/osquery/tree/master/docs) folder here, feel free to edit and add all of those suggestions. :D

**Comment by ppKrauss** [comment]
Thanks @theopolis ! 

-----

About change docs, perhaps the best is the participation of experts, because it is not only a /docs change...

* At [/specs](https://github.com/facebook/osquery/tree/master/specs) need to add the  `additional=True` to `description()` not only at `Column()`... or change some logic to do this automatically when a column is flagged.
 
* The  [`osquery.io/docs/tables`](https://osquery.io/docs/tables/) page is not part of the `/doc`, is a site page, generated by some template or page-generator that I not see.

* the source of the cited Guide page, [introduction/sql/#tables-with-arguments](https://osquery.readthedocs.io/en/stable/introduction/sql/#tables-with-arguments),  is at [docs/wiki/introduction/sql.md](https://github.com/facebook/osquery/blob/master/docs/wiki/introduction/sql.md) .. I  can change (see request!), but not see how to show the icon in the text. 

... So, my main suggestions stay there as my  [first and second itens there](#issuecomment-230673550), with some clues for /specs here.

**Comment by ppKrauss** [comment]
... need something more to the first (only /doc) commit? It is stopped.

**Comment by theopolis** [comment]
Check out some new (hopefully helpful) warnings for these types of tables: https://github.com/facebook/osquery/pull/2432 I hope this helps reduce confusion. :)
