### ISSUE TITLE
Flaky tests: BufferedLogForwarderTests.test_async Unexpected mock function call

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2218]
We are seeing a few flaky tests:
```
[----------] 6 tests from BufferedLogForwarderTests
[ RUN      ] BufferedLogForwarderTests.test_index
[       OK ] BufferedLogForwarderTests.test_index (0 ms)
[ RUN      ] BufferedLogForwarderTests.test_basic
[       OK ] BufferedLogForwarderTests.test_basic (0 ms)
[ RUN      ] BufferedLogForwarderTests.test_retry
[       OK ] BufferedLogForwarderTests.test_retry (0 ms)
[ RUN      ] BufferedLogForwarderTests.test_multiple
[       OK ] BufferedLogForwarderTests.test_multiple (1 ms)
[ RUN      ] BufferedLogForwarderTests.test_async
terminate called after throwing an instance of 'std::runtime_error'
  what():  
Unexpected mock function call - returning default value.
    Function call: send(@0x2b8dce1a5ab0 { "foo", "bar" }, @0x2b8dce1a5a58 "result")
    The mock function has no default action set, and its return type has no default value set.
```

Example: https://jenkins.osquery.io/job/osqueryPullRequestBuild/2833/TargetSystem=ubuntu14/console

Any chance you have a moment to look into the test logic @zwass?

**Comment by zwass** [comment]
The offending test (https://github.com/facebook/osquery/blob/master/osquery/logger/plugins/tests/buffered_tests.cpp#L210) is checking that the actual timing on the dispatcher thread is correct. I see a couple of possibilities here:

1) Eliminate this test, as it depends on the actual execution timing. There is a possibility of it continuing to be flaky no matter what we do.

2) Increase [kLogPeriod](https://github.com/facebook/osquery/blob/master/osquery/logger/plugins/tests/buffered_tests.cpp#L48) to reduce the chance of the timing going wrong. Even if we increased it to 200ms, the test would still run in a few seconds.

**Comment by theopolis** [comment]
So you're racing against a `pthread` scheduling assumption, with the expectation that the OS schedules the "dispatched" thread before the return from the test unit (via the `EXPECT_CALL`'s except or asserts within destructors?). Right now the `1.5 * kLogPeriod` is guaranteed to block the test, right?

I'm partial to 1, but there's very little dispatcher test code coverage. If there were more then there'd most likely be more to the `InternalRunnable` and `Dispatcher` APIs that made testing easier. 

Instead of changing `kLogPeriod` could you increase the modifier within this test case, from `1.5`=>`3` or something? Then we can see how often, if at all, that fails?

**Comment by zwass** [comment]
Yes, your analysis is correct. We can certainly also change the number of periods that we block for to ease the timing constraints.

PR incoming.

**Comment by zwass** [comment]
I dramatically increased the margin for scheduling conflicts causing flakiness in this test. If it ever gets flaky again, we should probably consider just killing it.

**Comment by theopolis** [comment]
Still seeing this: https://jenkins.osquery.io/job/osqueryPullRequestBuild/TargetSystem=osx11/3005/console

**Comment by zwass** [comment]
Want me to submit a PR to kill it?

**Comment by theopolis** [comment]
I'm not at a computer, but I wonder if we can request several runs and emit success if any complete successfully?

**Comment by theopolis** [comment]
I made some changes to `Dispatcher` to make it easier to test. Hopefully I haven't removed any test coverage: #2358.

**Comment by zwass** [comment]
I think it effectively renders this test redundant with the others, but if it means we are better testing the `Dispatcher` functionality, then we should be good.
