### ISSUE TITLE
Change Log Line Format

### ISSUE THREAD

**Issue by geek876** [facebook/osquery#2240]
Is there a way to change the `Log line format` to an ISO standard format within osquery.\* logs ?

Currently the format is (osqueryd.INFO logfile)
`Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg`
The logs come out as:
`I0712 16:12:40.150096  1167 virtual_table.cpp:226] Error casting gid () to BIGINT`

It would be better to have full date with year included so that it could be parsed easily for logstash/fluentd etc ?

**Comment by theopolis** [comment]
Hey @geek876 do you know a way to change GLog's prefix or format? We don't handle the log line writing directly.

**Comment by geek876** [comment]
@theopolis Nope.
