### ISSUE TITLE
Install error on Ubuntu 16.04

### ISSUE THREAD

**Issue by kurttheviking** [facebook/osquery#2246]
We have been using OSQuery on Ubuntu 14.04 and are upgrading to 16.04 for a variety of internal reasons. When I run the [standard install commands](https://osquery.readthedocs.io/en/stable/installation/install-linux/#dpkg-based-distros) on a fresh image I am seeing an install error. My packaging fu is not strong so apologies in advance if this error is my own.

In any case, running the following commands...

```sh
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B
sudo add-apt-repository "deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/xenial xenial main"
sudo apt-get update
````

Results in some warnings then an error...

```sh
W: The repository 'https://osquery-packages.s3.amazonaws.com/xenial xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://osquery-packages.s3.amazonaws.com/xenial/dists/xenial/main/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Checking the [S3 location for xenial](https://osquery-packages.s3.amazonaws.com/xenial/dists/xenial/main/binary-amd64/Packages) does indeed result in an S3 error (resource not publicly accessible?) though it works fine for [trusty](https://osquery-packages.s3.amazonaws.com/trusty/dists/trusty/main/binary-amd64/Packages).

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>3F69469837B74776</RequestId>
  <HostId>
    WuHmqGtPSLFU1sDnBUpEtBfv3r0IefsugE1kN4P3gHXxA0/52DK0VfxtNQq+wstvtmHj7yAcXKA=
  </HostId>
</Error>
```

Any suggestions would be much appreciated.

**Comment by theopolis** [comment]
Hey @kurttheviking, I just flipped the Xenial publishing script bit, do you mind checking again?

**Comment by kurttheviking** [comment]
:clap: thanks for the quick turnaround; looks good from my end.

I'll leave this issue open in case you need anything else from me. Otherwise, feel free to close.

**Comment by XizzoR** [comment]
Hello there!
I am trying to archive the same as @kurttheviking and it seems that problem still exist (?)

`...
Ign:13 https://osquerypackages.s3.amazonaws.com/xenial xenial/main Translation-en_US
Ign:14 https://osquerypackages.s3.amazonaws.com/xenial xenial/main Translation-en
Err:9 https://osquerypackages.s3.amazonaws.com/xenial xenial/main amd64 Packages
  404  Not Found
Ign:11 https://osquerypackages.s3.amazonaws.com/xenial xenial/main all Packages
Ign:13 https://osquerypackages.s3.amazonaws.com/xenial xenial/main Translation-en_US
Ign:14 https://osquerypackages.s3.amazonaws.com/xenial xenial/main Translation-en
Fetched 15.5 kB in 4s (3,469 B/s)
Reading package lists... Done
W: The repository 'https://osquerypackages.s3.amazonaws.com/xenial xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://osquerypackages.s3.amazonaws.com/xenial/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
`

Sorry for such necro comment.
