### ISSUE TITLE
logged_in_users table shows 'reboot' user

### ISSUE THREAD

**Issue by danielpops** [facebook/osquery#2249]
This may be by design since the "logged_in_users" appears to just be querying the wtmp data, but since the goal of the "logged_in_users" is assumedly to see who has been logged in to the machine at a given time, I *think* that including the 'reboot' entries is a bit misleading.

Expected: logged_in_users table only contains data about logged-in users
Actual: logged_in_users table contains data about logged-in users, and also occasionally contains "reboot" users

Is that by design?

**Comment by theopolis** [comment]
@danielpops I could go either way, let me try to extend this table a bit and see if we can offer clarity.
