### ISSUE TITLE
Check wiki for valid links in CI

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#2273]
`mkdocs` makes it easy to catch invalid links to markdown files within the wiki. Running `mkdocs build --clean -s` will exit with a nonzero status if any of the linked files are invalid. This completes in under 1 second on my machine.

Running this on the Jenkins build could help us catch broken links before they make it into the wiki (such as https://github.com/facebook/osquery/pull/2272).

**Comment by theopolis** [comment]
We have a few options on how to accomplish this:
1. Add the command/flags to the `build()` bash function: https://github.com/facebook/osquery/blob/master/tools/lib.sh
2. Add a `make docs-test` that calls `mkdocs` then update (1) to call `$MAKE docs-test`.
3. Add this step to `make docs` then update (1) to call `$MAKE docs`.
4. Add a new build step in Jenkins to run the command.

Or any combo / subset of the above.

My 2c, let's run this with `make docs` then add a new build job that runs the docs. I can then include that in the PR matrix.

**Comment by zwass** [comment]
@theopolis Did you add the `make docs` job to Jenkins?
