### ISSUE TITLE
Mispell in debian.sh file

### ISSUE THREAD

**Issue by ch0ks** [facebook/osquery#2318]
Hi, I was in your Defcon workshop, actually I am listening to Javier while writing this. Anyways, I tried to install osquery in a Debian Jessie machine and the process broke. Checking the error I noted that there is an spelling mistake in line 17 of this file:

https://github.com/facebook/osquery/blob/master/tools/provision/debian.sh

Awesome project, thanks for sharing the passion and knowledge.

Adrian Puente Z.

**Comment by PoppySeedPlehzr** [comment]
Thanks @ch0ks !
