### ISSUE TITLE
Integer underflow in buffered log purge count

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#2324]
@mwielgoszewski reports the following error message:

```
W0808 14:18:24.360587 42971136 buffered.cpp:122] Purging buffered logs limit (1000000) exceeded: 18446744073709551614
E0808 14:18:24.360694 42971136 buffered.cpp:136] Trying to purge 18446744073708551614 logs but only found 4
```

This indicates that something is broken in the counting logic for buffered logs.

Code: https://github.com/facebook/osquery/blob/master/osquery/logger/plugins/buffered.cpp#L136

The effects of this currently should only be the error message being printed, and no buffered logs being purged (because the `BufferedLogForwarder::purge()` function returns after printing the error.

**Comment by zwass** [comment]
@mwielgoszewski Also reports crashes that appear related to this (turning off TLS logger plugin) fixes crashes.

**Comment by groob** [comment]
I noticed this the other day as well when testing `osqueryd` 1.8.2 on 10.11.6. 
For me, it appears to only break after an unsuccessful startup

Here's how I can reproduce:
startup:
```
osqueryd --verbose \                                                                                           ⏎
    --pidfile /tmp/osqueryd.pid \
    --database_path /tmp/osquery.db/ \
    --tls_hostname osquery.groob.io:8000 \
    --tls_server_certs ./combined.crt \
    --config_plugin tls \
    --config_tls_endpoint /config \
    --logger_tls_endpoint /logger \
    --logger_plugin tls  \
    --enroll_tls_endpoint /enroll \
    --enroll_secret_path ./secret.txt
```

Immediately hit `CTRL+C` to terminate the process. On the next run I see the same errors as @mwielgoszewski 

```
W0808 15:22:30.193828 3211264 buffered.cpp:122] Purging buffered logs limit (1000000) exceeded: 18446744073709551615
E0808 15:22:30.193897 3211264 buffered.cpp:136] Trying to purge 18446744073708551615 logs but only found 2```

**Comment by zwass** [comment]
As a temporary workaround, the flag `--buffered_log_max=0` can be passed, which will turn off the buffered log purging code that prints this message.
