### ISSUE TITLE
osqueryctl has shell syntax error

### ISSUE THREAD

**Issue by gkeramidas** [facebook/osquery#2329]
This is a syntax error:

```
$ sudo osqueryctl lol
/usr/bin/osqueryctl: line 52: [: missing `]'
Usage: /usr/bin/osqueryctl {clean|config-check|start|stop|status|restart}

$ cat -n $(which osqueryctl) | grep 52
    52    if [ ! -e "$INIT_SCRIPT_PATH" && ! -f "$SERVICE_SCRIPT_PATH" ]; then
```

Each conditional should be wrapper in its own [ ... ] pair.

**Comment by theopolis** [comment]
Got it: https://github.com/facebook/osquery/commit/e1ad335987782f3353081e9bb75bd3ca03428924#diff-222a24caab1c62c8ff40402b33b5e25cR120! Thanks @gkeramidas
