### ISSUE TITLE
Install the boost chocolatey package to normal installation directory

### ISSUE THREAD

**Issue by artemdinaburg** [facebook/osquery#2338]
Right now the boost chocolatey package installs to C:\local, which makes us do extra work in CMake. Every other package installs to `%ChocolateyInstall%`. Boost should also install itself there.

**Comment by theopolis** [comment]
I think we can call this complete: https://github.com/facebook/osquery/commit/381e86a931f7bc86eaacd8c7ca6c80e4869459c0
