### ISSUE TITLE
./tools/profile.py psutils cpu_percent is throwing an exception

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2342]
To reproduce: `./tools/profile.py`.

**Comment by taqiu** [comment]
./tools/profile.py doesn't work correctly from 1.8.0 (it works for 1.7.4 and 1.7.7)
I tested it on rhel 6.5 and my macbook.
It will raise below exception.
```
Traceback (most recent call last):
  File "tools/profile.py", line 348, in <module>
    timeout=args.timeout, count=args.count, rounds=args.rounds
  File "tools/profile.py", line 189, in profile
    result = run_query(shell, query, timeout=timeout, count=count)
  File "tools/profile.py", line 132, in run_query
    ], timeout=timeout, count=count)
  File "/home/taqiu/osquery/tools/tests/utils.py", line 182, in profile_cmd
    raise Exception("No stats recorded, perhaps binary returns -1?")
Exception: No stats recorded, perhaps binary returns -1?
```

It works for some queries, and the results look weird.
```
 D:0  C:1  M:1  F:1  U:3  setuid (1/1): duration: -0.991484880447 cpu_time: 0.49 memory: 11571200 fds: 11 utilization: 97.8 
Profiling query: SELECT * FROM interface_addresses WHERE interface NOT LIKE 'lo%';
```
The duration is less than 0, and the utilization is very high.

**Comment by taqiu** [comment]
I attached the sample output of the same queries from one rhel 6.5 host below

1.7.4 
```
Profiling query: SELECT * FROM suid_bin;
 D:2  C:1  M:1  F:0  U:2  setuid (1/1): duration: 1.01901388168 cpu_time: 0.71 memory: 10874880 fds: 5 utilization: 47.2333333333 
Profiling query: SELECT * FROM interface_addresses WHERE interface NOT LIKE 'lo%';
 D:0  C:0  M:1  F:0  U:1  interface_information (1/1): duration: 0.514357805252 cpu_time: 0.08 memory: 10559488 fds: 5 utilization: 8.0 
.......
```

1.8.2
```
Profiling query: SELECT * FROM suid_bin;
 D:0  C:1  M:1  F:0  U:3  setuid (1/1): duration: -0.993211984634 cpu_time: 0.49 memory: 11567104 fds: 7 utilization: 97.9 
Profiling query: SELECT * FROM interface_addresses WHERE interface NOT LIKE 'lo%';
Traceback (most recent call last):
  File "tools/profile.py", line 348, in <module>
    timeout=args.timeout, count=args.count, rounds=args.rounds
  File "tools/profile.py", line 189, in profile
    result = run_query(shell, query, timeout=timeout, count=count)
  File "tools/profile.py", line 132, in run_query
    ], timeout=timeout, count=count)
  File "/home/taqiu/osquery/tools/tests/utils.py", line 181, in profile_cmd
    raise Exception("No stats recorded, perhaps binary returns -1?")
Exception: No stats recorded, perhaps binary returns -1?
```

**Comment by fuzzball5000** [comment]
+1 also getting this behaviour.

**Comment by fuzzball5000** [comment]
Have applied the fix, built, and still getting the error. Even with the query which previous returned with the odd result:

`root@gary-VirtualBox:~/osquery# python ./tools/profile.py --config ./osquery.conf
Profiling query: SELECT * FROM suid_bin;
Traceback (most recent call last):
  File "./tools/profile.py", line 348, in <module>
    timeout=args.timeout, count=args.count, rounds=args.rounds
  File "./tools/profile.py", line 189, in profile
    result = run_query(shell, query, timeout=timeout, count=count)
  File "./tools/profile.py", line 132, in run_query
    ], timeout=timeout, count=count)
  File "/home/gary/osquery/tools/tests/utils.py", line 173, in profile_cmd
    raise Exception("No stats recorded, perhaps binary returns -1?")
Exception: No stats recorded, perhaps binary returns -1?
`
