### ISSUE TITLE
Build: CMake on Windows cannot find several libraries

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2354]
See:
```
-- [31mCould not find library: netapi32.lib[m
-- [31mDependent library 'netapi32.lib' not found[m
-- [31mCould not find library: rpcrt4.lib[m
-- [31mDependent library 'rpcrt4.lib' not found[m
-- [31mCould not find library: shlwapi.lib[m
-- [31mDependent library 'shlwapi.lib' not found[m
-- [31mCould not find library: wbemuuid.lib[m
-- [31mDependent library 'wbemuuid.lib' not found[m
```

Example build log: https://jenkins.osquery.io/job/osqueryPullRequestWindows/TargetSystem=win10/49/console

It seems like this does not affect the build result. Are these libraries needed? Perhaps VS2015 finds and links them automatically. Either we remove them or append a few search paths to our CMake macros so they can be included in the link step.

**Comment by yying** [comment]
The libraries are needed and VS2015 does find them and link to them automatically. 

In order for CMake to find these libraries, CMake must be run within a `VS2015 x64 Native Tools Command Prompt` (which sets up the search paths for said libraries).

**Comment by theopolis** [comment]
Do we care to keep them in the `CMakeLists.txt` then? Let's remove them if VS is finding/linking automatically.

**Comment by artemdinaburg** [comment]
The 1.8 build system may require them to be found; the correct way would be to launch cmake from a command prompt with the correct visual studio related environment variables loaded. Going to test a fix to the build batch file to load the VS environment for 64-bit x86 prior to running cmake.
