### ISSUE TITLE
aws_util build issues with aws-sdk-cpp 0.14.4

### ISSUE THREAD

**Issue by ilovezfs** [facebook/osquery#2362]
Hey @theopolis 

I was trying to upgrade the osquery brew formula to 1.8.1 but still hit the aws-sdk-cpp issue I'd mentioned.

```
[ 51%] Building CXX object osquery/logger/CMakeFiles/osquery_logger_plugins.dir/plugins/aws_firehose.cpp.o
cd /tmp/osquery-20160814-43457-1nlvhp9/osquery/logger && /usr/local/Library/Homebrew/shims/super/clang++   -DBOOST_NETWORK_ENABLE_HTTPS -DBOOST_NO_CXX11_VARIADIC_TEMPLATES -DDARWIN -DDARWIN_10_11 -DHAS_SSL_TXT_TLSV1_2 -DNDEBUG -DOSQUERY_BUILD_DISTRO=10.11 -DOSQUERY_BUILD_PLATFORM=darwin -DOSQUERY_BUILD_SDK_VERSION=1.8.1 -DOSQUERY_THRIFT="" -DOSQUERY_THRIFT_LIB=thrift -DOSQUERY_THRIFT_POINTER=boost -DOSQUERY_THRIFT_SERVER_LIB=thrift/server -DSTRIP_FLAG_HELP=1 -I/usr/local/opt/openssl/include -I/tmp/osquery-20160814-43457-1nlvhp9/third-party/gmock-1.7.0/gtest/include -I/tmp/osquery-20160814-43457-1nlvhp9/third-party/gmock-1.7.0/include -I/tmp/osquery-20160814-43457-1nlvhp9/generated/gen-cpp -I/tmp/osquery-20160814-43457-1nlvhp9/third-party/sqlite3 -I/tmp/osquery-20160814-43457-1nlvhp9/include -I/tmp/osquery-20160814-43457-1nlvhp9 -I/usr/local/include -I/include -I/tmp/osquery-20160814-43457-1nlvhp9/third-party/sysroots/darwin  -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.11    -std=c++11 -stdlib=libc++ -static -Qunused-arguments -Wstrict-aliasing -Wno-missing-field-initializers -Wno-unused-local-typedef -Wno-unknown-warning-option -Wnon-virtual-dtor -Wchar-subscripts -Wpointer-arith -Woverloaded-virtual -Wformat -Wformat-security -Werror=format-security -Wabi-tag -fpermissive -fstack-protector-all -fPIE -fpie -fPIC -fpic -pipe -fdata-sections -ffunction-sections -mmacosx-version-min=10.11 -Os -march=x86-64 -mno-avx -Wall -Wextra -Wno-unused-parameter -o CMakeFiles/osquery_logger_plugins.dir/plugins/aws_firehose.cpp.o -c /tmp/osquery-20160814-43457-1nlvhp9/osquery/logger/plugins/aws_firehose.cpp
In file included from /tmp/osquery-20160814-43457-1nlvhp9/osquery/logger/plugins/aws_firehose.cpp:27:
/tmp/osquery-20160814-43457-1nlvhp9/osquery/logger/plugins/aws_util.h:115:26: error: unexpected namespace name 'Region': expected expression
Status getAWSRegion(Aws::Region &region);
                         ^
/tmp/osquery-20160814-43457-1nlvhp9/osquery/logger/plugins/aws_util.h:115:34: error: use of undeclared identifier 'region'
Status getAWSRegion(Aws::Region &region);
                                 ^
/tmp/osquery-20160814-43457-1nlvhp9/osquery/logger/plugins/aws_util.h:133:14: error: type 'osquery::Status' does not provide a call operator
  Status s = getAWSRegion(client_config.region);
             ^~~~~~~~~~~~
3 errors generated.
make[2]: *** [osquery/logger/CMakeFiles/osquery_logger_plugins.dir/plugins/aws_firehose.cpp.o] Error 1
make[1]: *** [osquery/logger/CMakeFiles/osquery_logger_plugins.dir/all] Error 2
make: *** [all] Error 2
```

Vendoring 0.12.4 seems undesirable though. Thanks for your help :)

**Comment by theopolis** [comment]
Is this because we need an updated AWS SDK formula in brew first?

**Comment by ilovezfs** [comment]
It's been updated passed 0.12.4 for a while: https://github.com/Homebrew/homebrew-core/commits/master/Formula/aws-sdk-cpp.rb

I think this is only surfacing now because the current formula doesn't depend on aws-sdk-cpp yet: https://github.com/Homebrew/homebrew-core/blob/master/Formula/osquery.rb#L17-L31 though I've known about the issue for a while but assumed you were well aware of it.

**Comment by theopolis** [comment]
Totally! I just checked and the issue is the inverse. We need to update our "vendored in" version to be compatible with 14.4 (which is in brew). Right now we are using [0.13.8](https://github.com/facebook/osquery/blob/master/tools/provision/formula/aws-sdk-cpp.rb#L6), updating that to 0.14.4 produces the same errors.

**Comment by ilovezfs** [comment]
@theopolis yup, we're on the same page now!

**Comment by ilovezfs** [comment]
@theopolis Your changes in #2371 make osquery build if a statically built aws-sdk-cpp, but with a non-static aws-sdk-cpp the build is still a tad petulant: https://gist.github.com/ilovezfs/8a1c6d03fa7ea37e744add5cc2805980

**Comment by theopolis** [comment]
Interesting, this is with a `--head` build of the formula?

**Comment by ilovezfs** [comment]
Yep. There seem to be several more places where there are still type mismatches between the osquery code and the current aws-sdk-cpp code, awsstring vs. string, etc.

**Comment by ilovezfs** [comment]
@theopolis I think if you open a PR to upgrade osquery in homebrew to your latest version you'll immediately experience the joy.

**Comment by ilovezfs** [comment]
@theopolis you can make the PR for HEAD itself by "cheating" like this:
https://github.com/Homebrew/homebrew-core/pull/4312

We can just tack don't merge on it until it's actually the real tag, ready to ship, etc.

**Comment by ilovezfs** [comment]
@theopolis fixed now?

**Comment by theopolis** [comment]
Ah, I was calling it fixed with the vendor-ed in version landing into the Homebrew formula. :P

**Comment by ilovezfs** [comment]
@theopolis Ah, OK!
