### ISSUE TITLE
Windows: script to produce an osquery choco package

### ISSUE THREAD

**Issue by PoppySeedPlehzr** [facebook/osquery#2393]

**Comment by theopolis** [comment]
The `make packages` (or equiv `.bat` script) should produce an osquery choco package.

**Comment by theopolis** [comment]
Here's the existing CMake logic, which only calls to a script in tools: https://github.com/facebook/osquery/blob/master/CMake/Packages.cmake

And the Linux/OS X script: https://github.com/facebook/osquery/tree/master/tools/deployment
That "deployment" directory includes other package artifacts that may be nice on Windows too.

**Comment by svmastersamurai** [comment]
Just letting y'all know: consider generating APPX packages as well. With the advent of Server 2016 Nano that is the only format you can install software in that environment since MS ripped out all the GUI components. Maybe in version 2.0?? ;)

**Comment by theopolis** [comment]
APPX should be relatively straightforward. We can create the package from a build host, push the result to our intermediate storage (a NAS on the Jenkins server), then periodically scan and sign (manual process) and finally ship/host on S3.

We host the apt/yum repos this way and serve symlinks to the latest package for each supported platform except for Windows.

The project needs 2 things:

1. A script within the osquery repository to generate the APPX after a build.
2. Logic/tooling to pull apart the APPX, sign binaries, then rebuild.*

*For OS X, PKG and Mach-O binary signing is proprietary so we have both a Linux signing/package host and an OS X one; if we need to add a third that not a huge issue.

**Comment by PoppySeedPlehzr** [comment]
I'm going to consider this issue closed, as #2890 brought in a powershell script to give us this logic. If we need to open up a new issue exploring APPX or package signing or whatnot feel free to open a new issue.
