### ISSUE TITLE
Darwin: the package_receipts table should be modified to be more accurate

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#2400]
Currently the package_receipts table for darwin uses filesystem artifacts to collect information. Since 10.5 `/Library/Receipts` should not be populated by almost all installers (in the older bundle-style format), and there have been long periods of time where all receipts are [wiped during an OS upgrade](https://derflounder.wordpress.com/2015/12/11/upgrading-to-os-x-el-capitan-using-the-os-x-10-11-2-installer-removes-package-installation-receipts/), or not properly handled by installer, which would lead you to believe the files-on-disk aren't what Apple wants you to judge installation state on . 

There is also a pretty huge mismatch between those logged in the pkgutil db and the filesystem:

```
$ pkgutil --pkgs | wc -l 
     196
```

vs. (1.8.2 osquery results)

```
select count(*) from package_receipts;
+----------+
| count(*) |
+----------+
| 97       |
+----------+
```

An alternative method is demonstrated in this gist: https://gist.github.com/arubdesu/19a9af076b45a0de95fc04c8c5a3a6dc

As much as I liked [nersniping](https://gist.github.com/pudquick/d64234a093e223e319d2d7a104d4b85e) my homie @pudquick, it's unfortunately a private framework...😢

**Comment by pudquick** [comment]
@arubdesu Did you mean this gist? 😄

https://gist.github.com/pudquick/d64234a093e223e319d2d7a104d4b85e
