### ISSUE TITLE
Proposal: tls-exp plugin with experimental features

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#2401]
For those who use osquery's TLS plugins, the stability of the APIs provided by those plugins is clearly really important. osquery's TLS plugins expect an osquery TLS server to respond in a very specific way with very specific response formats. Since the TLS plugins are baked into the binary itself, it's not reasonable to change these APIs from version to version as one might change internal SDK APIs since there are so many open source (and potentially closed source) implementations of an osquery TLS server that adhere to the current API. The versions of the osquery instances that talk to these servers might vary dramatically. If they all expected different versions of the API, that would be most unfortunate. 

After much discussion with @zwass while developing an osquery TLS server implementation, we'd like to add a new set of plugins to the osquery codebase: TLS Experimental plugins (plugin name: `tls-exp`) (name is up for debate).

This would allow us to rapidly develop additional TLS communication capabilities and additional plugin logic in an open environment while collaborating with the needs of other osquery TLS server developers. If the community can come to a consensus on what format works best for them and can appropriately orchestrate a migration, we can merge features from the experimental plugin-set to the stable plugin-set.

Think of it as a safe proving ground for new features and capabilities.

I'm interested in what @theopolis thinks of this from a design perspective and I'm also interested what @mwielgoszewski, @blackfist, @sroberts, etc. think of this from an osquery TLS server developer perspective.

**Comment by theopolis** [comment]
The stability requirement of the TLS plugin(s) in relation to any other plugin is equal.

A `tls-exp` seems like a bad idea.

Let me offer two observations/thoughts:
(1) Most REST interfaces/APIs establish versions and contracts (promises/release announcements) for support. Refactoring the endpoint format requirement to include `/vN/` may work. Going forward you may declare the "non-versioned" API as `v0` and introduce a `v1` with the changes you'd like.

(2) The choice for cpp-netlib over the "HEAD" of Thrift was required last year, that may no longer be true. If Thrift's TLS implementation is now adequate, it is a desired replacement along with a specification. Those specs may be morphed to support a versioned API but will also support "ABI" compliant optional additional methods going forward.

You may create a "options" API call, which triggers a selection of additional features to emulate a versioned API too.

**Comment by marpaia** [comment]
The idea of versioning the API that the TLS plugin adheres to is super interesting and not one that I've thought of so I'd like to think on that a bit.

Speaking thrift and adhering to a well versioned API similar to a programmatic API would be interesting if Apache Thrift had mature TLS implementations or osquery was able to migrate to fbthrift, although I definitely want to experiment with a more stateful connection option for distributed queries, like websockets, and I'm unsure if there's anything similar in thrift.

**Comment by marpaia** [comment]
@theopolis how do you feel about adding an options call (maybe as a response to enrollment?) and then switching on it within the implementations of the TLS plugins if the API changes? It would couple the various TLS plugins together in a way in which they're not coupled today, so I'm not sure if that's acceptable.

Obviously the approval of such an approach would not approve any of the underlying proposed API changes, but that's a discussion for another PR.

**Comment by zwass** [comment]
With versioning (1), how would the osqueryd client indicate to the server which version it speaks? Would we just use an implicit v0 for the existing version, and then have new versions send a "version" key or the like in their post body?

Just to clarify, in point (2) are you discussing dropping raw HTTPS in favor of Thrift over TLS?

**Comment by theopolis** [comment]
Versioned REST APIs usually take the form: `/vN/ENDPOINT/`. It's interesting that the client expects each endpoint to be defined via CLI/flagfile options. This can be deprecated and "hidden" fairly easily and a `v(1-N` can be supported with a `--tls_api_version` or something similar. If you don't use that flag and instead set the other hidden flags it's assumed v=0.

If you want to place the version into the expected enroll/etc response then the client can support 0-N fairly transparently-- if there's no `{"api": "1"}` or similar key in the response then the client assumes v=0. Substitute the `{"api"...}` key for a supported-options set for a "version-less?" API. Both of these secondary approaches require at least one additional RTT, but that's not a significant concern.

While I have no experience using Apache Thrift's TLS implementations, they look OK: 
- https://github.com/apache/thrift/blob/master/lib/cpp/src/thrift/transport/TSSLSocket.h
- https://github.com/apache/thrift/blob/master/lib/py/src/transport/TSSLSocket.py

**Comment by marpaia** [comment]
This is interesting. The fact that the current implementation requires you to specify endpoints as flags does add some spice.

We could continue defining endpoints via flags. It would be troublesome if API v0 and API v1 started to diverge in endpoints required and not just params, which they almost definitely will. But perhaps at that case, one could just declare what API version they want to speak via a flag?

We could alternatively be more opinionated about the distributed API endpoints, but that's just as much of a breaking change as anything that I'd like to do to the API, so I'm not sure if that's an awesome idea.

**Comment by zwass** [comment]
I'm still of the opinion that if we want to do something that departs from the behavior of the existing plugins, we should just write another plugin. That way the existing plugin users are entirely unaffected, and new development can be free to take whatever path that is useful.

**Comment by mwielgoszewski** [comment]
I anticipated versioning of API's when developing Doorman from the get go. See https://github.com/mwielgoszewski/doorman/blob/master/doorman/api.py#L112 for an example. I rely on the osquery endpoint flags specified in the osquery.flags file I distribute to nodes to do versioning. I push an osquery package out to a couple nodes with a versioned API endpoint and monitor that endpoint for performance/issues before rolling it out to the other nodes. I've found this workflow to work quite well.

I would be opposed to introducing a `--tls_api_version` for this purpose. IMO, it's best to leave this to the endpoint flags and TLS server endpoint to respond accordingly. I don't think the client should change its behavior. If that means having some nodes be a couple release versions behind, then so be it. Adding support for multiple versions in the osquery endpoint is just a recipe for increasing code complexity and introducing new bugs IMO.

**Comment by zwass** [comment]
@mwielgoszewski, to be clear I understand your approach...

You're saying that you just modify the `*_endpoint` flags to do the versioning? And so if we wanted to change the client/server behaviors, we could set older `osqueryd` clients that don't speak the new protocol to use `--config_tls_endpoint=/v1/config` and newer clients set to `--config_tls_endpoint=/v2/config`?

How do we deal with an `osqueryd` client that speaks a newer version of the protocol than the server?

**Comment by marpaia** [comment]
I have a few ideas for how we could do this in a backwards compatible way, so I'm going to close this and (soon, hopefully) put up a PR with a potential implementation.
