### ISSUE TITLE
Discussion: docs for expectations re: utility tables, sudo/root vs. user 

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#2402]
Currently there are over 30 discrepancies between the `osqueryi count(*)` output from a root shell and a standard user on macOS. These differences bring up the possible opportunity to guide users as to what the expected use is per table. In most cases the output count from a (standard or otherwise) user is _higher_, which I don't believe would be obvious to a beginner - as we know, often you need to join/mix and match things after enumerating all users to have them be optimized from osqueryd. Also, it's not as if running as root and joining data from the users table to others makes osqueryd tell launchd it wants to use its [asuser](https://derflounder.wordpress.com/2016/03/25/running-processes-in-os-x-as-the-logged-in-user-from-outside-the-users-account/) functionality to execute the query with the users rights or environment. That could cause unexpected results when converting ad-hoc osqueryi queries to a pack that will be run by launchd.
Another point is that selecting * from 20+ tables w/ osqueryi as root, not including `_events` tables, returns 0 results. I wouldn't want users to believe these are because things are broken, but instead is either a. the system the query was run on was not in an applicable state, or b. the table needs to be treated as a 'utility' to join applicable fields against other tables.

On top of that, the `docs/table` page on osquery.io makes a separation between platforms and utility tables, but there is a learning curve to figure out what's both a. applicable for the targeted platform (e.g., that macos/Darwin actually falls under the POSIX headings) and b. recommended tables to 'mashup' to get the full range of results that the osquery's devs intended (as they included/merged the table in the first place). I'd want users to understand that in some cases criteria they may feel is missing is actually provided by joining the results of a subquery to the applicable 'utility' table. I'm not sure how best to document that and make that discoverable.

_As a point of reference, the way I collected the information references above was through the following filthy bash:_
```sh
osqueryi --csv '.tables' | awk '{print $2}' >> /tmp/theTables.txt
# manually filter out table names that end with _events, then
for table in `cat /tmp/theTables-minusEvents.txt`; do echo $table && osqueryi --csv "select count(*) from $table;"; done >> /tmp/output.txt
# repeat in a root shell
```

**Comment by theopolis** [comment]
Check out: #2432

I'll work on the `*_events` tables when `--enable_events` is not set too.

**Comment by arubdesu** [comment]
I love this, better than I could have envisioned! Pushing the reasoning down into the code itself and providing clear guidance is genius.

**Comment by theopolis** [comment]
:+1:
