### ISSUE TITLE
OSquery defunct process

### ISSUE THREAD

**Issue by msims-okta** [facebook/osquery#2405]
osquery-1.8.1-1.el6.x86_64 installed
Using AWS Linux.

Every few minutes the osquery process becomes defunct. A new one does start up but we're left with this:

> root     12730 28.2  0.0      0     0 ?        ZN   15:53   0:52 [osqueryd] \<defunct\>
> root     16092 11.0  0.2 967984 19792 ?        SNl  15:56   0:00 osqueryd                                                                                         
> root     30296  0.0  0.0 285932  7248 ?        SNsl 15:40   0:00 osqueryd --config_path=/etc/osquery/osquery.conf --pidfile=/var/run/osqueryd.pid --daemonize=true
> 

These are the last lines in WARNING before the process dies.

> W0823 14:40:07.895736 20294 events.cpp:304] Expiring events for subscriber: file_events limit (1000) exceeded: 1248
> W0823 14:40:10.598011 20293 events.cpp:304] Expiring events for subscriber: process_events limit (1000) exceeded: 1255
> W0823 14:40:11.580380 20294 events.cpp:304] Expiring events for subscriber: file_events limit (1000) exceeded: 1196
> W0823 14:40:15.710403 20294 events.cpp:304] Expiring events for subscriber: file_events limit (1000) exceeded: 1246
> W0823 14:40:20.127872 20294 events.cpp:304] Expiring events for subscriber: file_events limit (1000) exceeded: 1163

**Comment by msims-okta** [comment]
Some more info, verbose logging:

> W0823 15:19:11.074777 11601 events.cpp:304] Expiring events for subscriber: file_events limit (1000) exceeded: 1222
> I0823 15:19:11.101375 11601 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:11.102169 11593 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:11.132314 11595 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:11.594897 11601 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:11.652662 11601 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:11.660203 11592 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:11.683194 11595 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:12.427634 11601 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:12.847084 11601 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:12.943608 11601 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:12.953240 11595 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:13.054108 11601 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:13.396833 11594 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:13.467980 11601 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:13.534819 11600 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0823 15:19:13.915518 11601 inotify.cpp:117] inotify was overflown, attempting to restart handle

I performed an strace on the process as it failed:

> Process 11583 attached
> futex(0x7f02fb6ac9d0, FUTEX_WAIT, 11591, NULL
>  <unfinished ...>
> +++ killed by SIGABRT +++

**Comment by theopolis** [comment]
The osquery worker process is being killed because it is using too many resources. Check out the couple of debugging options here: http://osquery.readthedocs.io/en/stable/deployment/debugging/#running-the-daemon-in-the-foreground

From the logs you've posted it seems the paths you've configured for FIM are very noisy. That can lead to a LOT of processing. If you want to disable this "watchdog" feature use `--disable_watchdog`. In your `--flagfile` or as a configuration option: http://osquery.readthedocs.io/en/stable/installation/cli-flags/#cli-only-initialization-flags

**Comment by msims-okta** [comment]
OK so we reduced our config to a bare minimum. It's no longer crashing, and hasn't produced a defunct process.

Here is our config:

```
{
  "options": {
    "config_plugin": "filesystem",
    "logger_plugin": "filesystem",
    "logger_path": "/var/log/osquery",
    "schedule_splay_percent": "10",
    "database_path": "/var/osquery/osquery.db",
    "verbose": "true",
    "worker_threads": "6",
    "enable_monitor": "true"
  },
  "decorators": {
    "load": [
      "SELECT uuid AS host_uuid FROM system_info;",
      "SELECT user AS username FROM logged_in_users ORDER BY time DESC LIMIT 1;"
    ]
  },
  "file_paths": {
    "etc": [
      "/etc/"
    ]
  },
  "file_accesses": ["homes", "etc"]
}
```

And here's the output that we're seeing. We're still getting file_events limit, even with out reduced files.

> W0824 19:29:37.448751  9051 events.cpp:304] Expiring events for subscriber: file_events limit (1000) exceeded: 1125
> I0824 19:29:37.779434  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:37.796177  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:37.803145  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:38.133569  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:38.143846  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:38.156339  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:38.158325  9044 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:38.164180  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:38.483911  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:38.499297  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:38.512091  9045 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> W0824 19:29:38.525624  9051 events.cpp:304] Expiring events for subscriber: file_events limit (1000) exceeded: 1230
> I0824 19:29:38.531671  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:38.859729  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:38.859943  9046 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:38.878888  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:38.888475  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:38.903308  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:39.215378  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:39.232940  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:39.240908  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:39.875843  9051 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3
> I0824 19:29:39.876065  9046 rocksdb.cpp:130] RocksDB: [WARN] [queries] Stopping writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 3

**Comment by fuzzball5000** [comment]
Could it be the file_accesses query which is causing the excessive chatter here? From https://github.com/facebook/osquery/blob/edc3fa5a258a255bdcd2c12fb0cedcf401b6938b/docs/wiki/deployment/file-integrity-monitoring.md:

"File accesses on Linux using inotify may induce unexpected and unwanted performance reduction."

What's the objective of this query? I haven't tested this in my own config yet, but I would imagine that many processes access files in /etc frequently, and this could result in a lot of noise. If you're looking to get a deep insight on this system as to what is being executed, perhaps the process_events table with some conditionals applied for tuning or user_events might be more suitable... although on a busy system both of those could also cause performance hits, depending on the query and the intervals. 

Also, your worker_threads setting is 3 times higher than the default, so we have 6 threads potentially writing to Rocks' memtables?

**Comment by mattjane-okta** [comment]
As it stands right now, we've actually disabled all queries, packs, etc.  What you see in the config above is the entire config. 

The objective here is to do file integrity monitoring on the /etc directory.  However, in this case we've removed all the actual queries and all that remains is the
 `"file_paths": {
    "etc": [
      "/etc/"
    ]
  }`

The worker thread config is set to 6 here, but has been set to everything from 1 to 6 with no change in teh issues we're seeing.  We had set it higher in this particular instance to see if having more threads would enable osquery to process data faster.

Hope that helps!

**Comment by fuzzball5000** [comment]
What (I think) your config is doing is monitoring all *access* on the /etc path (you don't have a path defined for "homes"), which is probably very chatty and isn't actually going to return any file modification events. Try going for a basic config which queries the file_events table on a reasonable interval and see where you get with that. 

I did this on my blog a few months back: http://malwarewolf.blogspot.co.uk/2016_02_01_archive.html It's a very, VERY basic introduction, and doesn't go into using decorators or joins, but it does give you a starting point. Try the config with your own path and see if the warnings go quiet.

**Comment by theopolis** [comment]
Right, edit the config just a tad and feel free to re-enables all of the queries:
```
{
  "options": {
    "config_plugin": "filesystem",
    "logger_plugin": "filesystem",
    "logger_path": "/var/log/osquery",
    "schedule_splay_percent": "10",
    "database_path": "/var/osquery/osquery.db",
    "verbose": "true",
    "worker_threads": "6",
    "enable_monitor": "true"
  },
  "decorators": {
    "load": [
      "SELECT uuid AS host_uuid FROM system_info;",
      "SELECT user AS username FROM logged_in_users ORDER BY time DESC LIMIT 1;"
    ]
  },
  "file_paths": {
    "etc": [
      "/etc/"
    ]
  }
//, "file_accesses": ["homes", "etc"]
}
```

**Comment by theopolis** [comment]
Here's the note about what this config option does: https://osquery.readthedocs.io/en/stable/deployment/file-integrity-monitoring/#file-accesses

**Comment by msims-okta** [comment]
Thanks all for your assistance. We pointed file_access to a quiet directory only (/root) and all the warnings stopped. So we'll figure out how to proceed with this.

**Comment by theopolis** [comment]
Awesome! I'm adding a few more performance optimizations for events too, the next release should help. :)
