### ISSUE TITLE
Add additional types to WMI wrapper

### ISSUE THREAD

**Issue by PoppySeedPlehzr** [facebook/osquery#2429]
Currently the WMI wrapper only supports getting some types of data (string, string[], . Below is the Win32_NetworkAdapterConfiguration class with numerous types of data that can be queried.

https://msdn.microsoft.com/en-us/library/aa394217(v=vs.85).aspx

Flush out support for the remainder of types being returned by WMI.  Examples of types that need support, uint8, uint16, uint32, ...

VARIENT Union - https://msdn.microsoft.com/en-us/library/windows/desktop/ms221627(v=vs.85).aspx
VARTYPES enum - https://msdn.microsoft.com/en-us/library/windows/desktop/ms221170(v=vs.85).aspx

**Comment by theopolis** [comment]
Ping @PoppySeedPlehzr, can this be closed since @2430 has landed?

**Comment by PoppySeedPlehzr** [comment]
Yeah I believe so. There may be more types we end up wanting in the future, but I think we're relatively well covered for now.
