### ISSUE TITLE
Consolidate pathExists and namedPipeExists 

### ISSUE THREAD

**Issue by yying** [facebook/osquery#2446]
`pathExists` currently is used to check if a specified domain socket exists. `namedPipeExists` is used for a similar check but against Windows named pipes. Is there a way to consolidate the two into one function?

**Comment by theopolis** [comment]
There are relatively few callsites of `namedPipeExists` but each introduces another `#WIN32` preprocessor branch. This makes static analysis harder and may reduce code coverage in tests.

Here are all the instances:
```bash
~/git/osquery/osquery(branch:master) » grep -rn namedPipeExists . -C 3
./filesystem/fileops.h-111-
./filesystem/fileops.h-112-#ifdef WIN32
./filesystem/fileops.h-113-/// Checks for the existence of a named pipe socket
./filesystem/fileops.h:114:Status namedPipeExists(const std::string& path);
./filesystem/fileops.h-115-
./filesystem/fileops.h-116-/**
./filesystem/fileops.h-117- * @brief Stores information about the last Windows async request
--
./filesystem/windows/fileops.cpp-1191-}
./filesystem/windows/fileops.cpp-1192-
./filesystem/windows/fileops.cpp-1193-#ifdef WIN32
./filesystem/windows/fileops.cpp:1194:Status namedPipeExists(const std::string& path) {
./filesystem/windows/fileops.cpp-1195-  // Wait 500ms for the named pipe status
./filesystem/windows/fileops.cpp-1196-  if (::WaitNamedPipeA(path.c_str(), 500) == 0) {
./filesystem/windows/fileops.cpp-1197-    DWORD error = ::GetLastError();
--
./extensions/extensions.cpp-134-#ifdef WIN32
./extensions/extensions.cpp-135-    // This makes sure the pipe exists in some capacity (could be busy at the
./extensions/extensions.cpp-136-    // moment)
./extensions/extensions.cpp:137:    if (namedPipeExists(path).ok()) {
./extensions/extensions.cpp-138-      return Status(0, "OK");
./extensions/extensions.cpp-139-    }
./extensions/extensions.cpp-140-#else
--
./extensions/extensions.cpp-204-  bool core_sane = true;
./extensions/extensions.cpp-205-#ifdef WIN32
./extensions/extensions.cpp-206-  // Check to see if the pipe name is a valid named pipe
./extensions/extensions.cpp:207:  if (!namedPipeExists(path_).ok()) {
./extensions/extensions.cpp-208-    core_sane = false;
./extensions/extensions.cpp-209-  }
./extensions/extensions.cpp-210-#else
--
./extensions/extensions.cpp-244-    auto path = getExtensionSocket(uuid);
./extensions/extensions.cpp-245-#ifdef WIN32
./extensions/extensions.cpp-246-    // Check to see if the pipe name is a valid named pipe
./extensions/extensions.cpp:247:    if (!namedPipeExists(path).ok()) {
./extensions/extensions.cpp-248-      LOG(INFO) << "Extension UUID " << uuid << " ping failed";
./extensions/extensions.cpp-249-
./extensions/extensions.cpp-250-      // Immediate fail non-writable paths.
--
./extensions/tests/extensions_tests.cpp-44-    socket_path += "testextmgr" + std::to_string(rand());
./extensions/tests/extensions_tests.cpp-45-
./extensions/tests/extensions_tests.cpp-46-#ifdef WIN32
./extensions/tests/extensions_tests.cpp:47:    if (namedPipeExists(socket_path).ok()) {
./extensions/tests/extensions_tests.cpp-48-#else
./extensions/tests/extensions_tests.cpp-49-    remove(socket_path);
./extensions/tests/extensions_tests.cpp-50-    if (pathExists(socket_path).ok()) {
--
./extensions/tests/extensions_tests.cpp-114-    int delay = 0;
./extensions/tests/extensions_tests.cpp-115-    while (delay < kTimeout) {
./extensions/tests/extensions_tests.cpp-116-#ifdef WIN32
./extensions/tests/extensions_tests.cpp:117:      if (namedPipeExists(socket_path).ok()) {
./extensions/tests/extensions_tests.cpp-118-#else
./extensions/tests/extensions_tests.cpp-119-      if (pathExists(socket_path).ok() && isReadable(socket_path).ok()) {
./extensions/tests/extensions_tests.cpp-120-#endif
```

One recommendation is to create a new method:
```
Status osquerySocketExists(const std::string& path);
```

It can be defined in `./osquery/filesystem/fileops.h` and have an implementation in `./osquery/filesystem/windows` and `./osquery/filesystem/posix`. The Windows implementation would use the existing logic in `namedPipeExists` and the POSIX implementation can simply be: `pathExists() && isReadable()` as demonstrated at `./osquery/extensions/tests/extension_tests.cpp`.

**Comment by xinan** [comment]
I can do this. My plan is 

- [ ] Add the new API
- [ ] Change callsites of `pathExists` and `namedPipeExists` to use the new API
- [ ] Remove the old `namedPipeExists`

Shall I do all these in the same PR, or shall I separate them into 2 or 3 PRs? :smile:

**Comment by theopolis** [comment]
Hi @xinan, thanks for looking into this! Doing all 3 in a single PR seems best. :)

**Comment by xinan** [comment]
No problem. I was a bit busy last week. Will finish it this week!

**Comment by xinan** [comment]
@theopolis I see some callsites are calling `pathExists() && isWritable()`(e.g. `/osquery/extensions/extensions.cpp:141`). Shall I include `isWritable()` together with `isReadable()` in the posix version of `osquerySocketExists()`?

**Comment by theopolis** [comment]
That sounds great!

**Comment by xinan** [comment]
@theopolis In fact, I found out that `isReadable()` and `isWritable()` are all calling `pathExists()` first. Therefore, calls like `pathExists() && isReadable()` or `pathExists()` and `isWritable()` are redundant. However, I am not sure whether it is a good idea to combine `isReadable()` and `isWritable()` into `osquerySocketExists()` because that makes `osquerySocketExists()` not doing what its name says.

I think another way to do this will be, implement the Windows version of `pathExists()` with the current implementation of `namedPipeExists()`, and then try to make `isReadable()` and `isWritable()` work for Windows too. What do you think?

**Comment by theopolis** [comment]
Wow, thanks for looking into that flow. I wonder if we can write an appropriate `isReadable()`, `isWritable()` for named pipes in Windows, (@PoppySeedPlehzr @yying) may know?

In the `osquerySocketExists` implementation you can also do something like:
```cpp
if (!platformType(PlatformType::TYPE_WINDOWS)) {
  return (isReadable() && isWriteable());
}
```
