### ISSUE TITLE
Bundle augeas lenses in osquery distribution

### ISSUE THREAD

**Issue by thedrow** [facebook/osquery#2490]
Augeas lenses are the configuration files that instruct augeas how to parse various configuration files.
After we merge #2181 we need to bundle the augeas lenses in the osquery distribution.
The alternative is to require augeas to be installed as a dependency of OSQuery which will provide the lenses.
Without lenses the augeas table would be useless since it won't parse anything.
I don't think we need to require augeas to be installed though. We can automate bundling the lenses when we package osquery.

**Comment by theopolis** [comment]
CC: @lutter 

We're considering bundling the Augeas lenses when folks run the osquery package-building scripts. The result would be installing a copy of the distribution's lenses into a path like `/usr/share/osquery/augeas/lenses` (or similar). I'm assuming the lenses, like Augeas, are licensed LGPL 2.1. I would consider the lens logic as source code and thus we need to include a copy of the license alongside their source distribution. Would including the Augeas project's `COPYING` file in the lens directory be acceptable/appropriate?

**Comment by lutter** [comment]
Yes, the lenses are licensed under LGPL 2.1, and I would certainly consider including the COPYING file as sufficient to comply with the license (would be even better if you include a quick README to tell people where those files came from, but that's not a requirement)

If you want to be extra-conscientious you could send a headsup to the mailing list (augeas-devel@redhat.com) but you should be fine even without that.

**Comment by spasam** [comment]
This can be closed
