### ISSUE TITLE
Add Homebrew license to tools/provisioning/formula

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2491]
Several of the bundled Homebrew formulas are slight modifications from 'upstream'* homebrew-core belonging to Homebrew or Linuxbrew. They should include the Homebrew contributors license.

* Note, upstream means the local formula should continue to track/monitor changes but they are not on-track for upstream committing.

**Comment by theopolis** [comment]
//cc @MikeMcQuaid 👍

**Comment by MikeMcQuaid** [comment]
😍 thanks @theopolis!
