### ISSUE TITLE
[Windows] Feature Request: Service (daemon) table

### ISSUE THREAD

**Issue by tedkol** [facebook/osquery#2540]
It would be great to have a list of all services (daemons) running, and some basic information about them.

For example, I might want to know if the Adobe acrobat update servce was running:

PS C:\ProgramData\osquery> Get-Service AdobeARMservice | fl *

Name                : AdobeARMservice
RequiredServices    : {}
CanPauseAndContinue : False
CanShutdown         : False
CanStop             : True
DisplayName         : Adobe Acrobat Update Service
DependentServices   : {}
MachineName         : .
ServiceName         : AdobeARMservice
ServicesDependedOn  : {}
ServiceHandle       : SafeServiceHandle
Status              : Running
ServiceType         : Win32OwnProcess
StartType           : Automatic
Site                :
Container           :

**Comment by theopolis** [comment]
Original request: https://github.com/facebook/osquery/issues/2152

**Comment by mtmcgrew** [comment]
Is there any way we can include the ServiceDLL reg key for each service? One of the main ways for malware to hide as a service is to just modify that key. I don't see that info being capture from the proposed table.

Skip down to "Identifying Rogue Service DLLs with Tanium"

https://blog.tanium.com/back-basics-detecting-malicious-windows-services-tanium/

**Comment by PoppySeedPlehzr** [comment]
@mtmcgrew it seems like that might be something best obtained by `join`ing the the registry table against the services table? The currently proposed table that @ExtremeGTX has up contains the binary path, but it seems like if there's a registry entry that can be modified to hide the location of the backing DLL then this wouldn't be data that should be rolled into the table natively, but rather something obtained with a schedule or a query pack?  Thoughts?

**Comment by theopolis** [comment]
Thanks again @ExtremeGTX!
