### ISSUE TITLE
deps: Update sleuthkit to sleuthkit-4.3.0

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2545]
We should update our local `sleuthkit` formula to version 4.3.0: https://github.com/sleuthkit/sleuthkit/releases/tag/sleuthkit-4.3.0

If everything goes according to plan this should be straight-forward:

1. Change the `url` here to point to the `4.3.0` URL: https://github.com/facebook/osquery/blob/master/tools/provision/formula/sleuthkit.rb#L6
2. Update the `sha256` value.

To test run:

1. `make deps`
2. `/usr/local/osquery/bin/brew uninstall sleuthkit`
3. `OSQUERY_BUILD_DEPS=1 make deps`

The last two tests are somewhat optional. They assure us that the package can be "bottled" for binary distribution.

**Comment by danielbayerlein** [comment]
@theopolis Done 👉 #2557
