### ISSUE TITLE
deps: Update yara to version 3.5.0

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2546]
We should update our local `yara` formula to version 3.5.0: https://github.com/VirusTotal/yara/releases/tag/v3.5.0

If everything goes according to plan this should be straight-forward:

1. Change the `url` here to point to the `3.5.0` URL: https://github.com/facebook/osquery/blob/master/tools/provision/formula/yara.rb#L6
2. Update the `sha256` value.

To test run:

1. `make deps`
2. `/usr/local/osquery/bin/brew uninstall yara`
3. `OSQUERY_BUILD_DEPS=1 make deps`

The last two tests are somewhat optional. They assure us that the package can be "bottled" for binary distribution.

**Comment by lnsp** [comment]
I'm on it :)
