### ISSUE TITLE
windows test: The windows build does not run unit tests

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2550]
The build script used within our Jenkins CI: https://github.com/facebook/osquery/blob/master/tools/make-win64-binaries.bat#L6

Does not run our unit tests.

This may be as simple as appending a:
```
ctest
```
to the script. Or it may involve adding lines to execute `.\osquery_tests.exe` and `.\osquery_additional_tests.exe`.

**Comment by madduci** [comment]
Done in pull request #2558
