### ISSUE TITLE
windows: Script to run a memory-leak-check build

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2551]
See: https://msdn.microsoft.com/en-us/library/x98tx3cf.aspx for details on building on Windows with memory-leak-detection.

We need a script, similar to https://github.com/facebook/osquery/blob/master/tools/make-win64-binaries.bat that runs a build with these includes/defines enabled and then executes our tests.

**Comment by PoppySeedPlehzr** [comment]
This is addressed with #2661, through the use of cppcheck. I'd still like to see more analyzers added, but this has already caught a good resource leak bug from the use of Windows APIs.
