### ISSUE TITLE
virtual table: Windows System Drivers

### ISSUE THREAD

**Issue by PoppySeedPlehzr** [facebook/osquery#2556]
A table to enumerate the windows system drivers would super awesome!

**Comment by ExtremeGTX** [comment]
I will start on implementation of this table soon, So what is the most critical info here we should include and what is not necessary
 
Here is the info we can get about installed drivers in Windows:
### Windows Drivers table:

**Info provided by SCM APIs :**
- [ ] Name
- [ ] Display name
- [ ] Status
- [ ] Start type
- [ ] Path
- [ ] Driver type [Kernel, FileSystem]
- [ ] Error Control
- [ ] Load order group
- [ ] **Extra info:**
	- [ ] CanPauseAndContinue
	- [ ] CanShutdown
	- [ ] CanStop

**Info provided by EnumDrivers API :**
- [ ] ImageBase


**Additional Info provided by File properties:**
- [ ] File Version
- [ ] Description
- [ ] Digital Signature


**Additional Info provided by Registry:**
- [ ] inf name

**Comment by friedbutter** [comment]
I have a few questions:
1) Can SCM APIs lie and don't report all the drivers?
2) Should we check the driver locations (such as `C:\windows\system32`) also?

**Comment by mtmcgrew** [comment]
I would think these are the most important Name, Display Name, Status, Start Type, Path, Driver Type, Description, Digital Signature 

@friedbutter we can always use the file table to query C:\windows\system32

**Comment by mtmcgrew** [comment]
Maybe it would be better to implement the digital signature info in the file table then we could just join on that using the path? cc @PoppySeedPlehzr

**Comment by PoppySeedPlehzr** [comment]
@mtmcgrew I agree with that point. We had talked about where the Digital Signature information might live, and I think having it rolled into the file table might be a good idea, or rather build out another table that contains digital signature information, as well as re-computes the digital signature to check it's integrity.

@ExtremeGTX for columns, I think I find the following the most important: 
 Name
 Display name
 Status
 Start type
 Path
 Driver type

Also, depending on how easy it is to get, I'd be interested in the .inf information as well. Do you possibly have any sample images of what you might have so far? :)

**Comment by ExtremeGTX** [comment]
Sample of current result (w/o Display Name)
![osquery_drivers](https://cloud.githubusercontent.com/assets/6371120/19419417/46a9d51e-93d7-11e6-989d-ba6793fd31b9.png)

but some drivers not get listed using `EnumServicesStatusEx` like: `ntoskrnl.exe`, `bootvid.dll`, `cdd.dll`

**Comment by friedbutter** [comment]
@ExtremeGTX, this looks pretty good :) For digital signers, we can create a different table and join by the path to get the signature info. We have implement the table for OS X, thus we should do the same for Windows. It doesn't have to exist in this table.  @PoppySeedPlehzr, thoughts? 

Just curious, I haven't looked. Is there a way to get the version of a driver?

**Comment by ExtremeGTX** [comment]
@friedbutter I think all info we can get from File Properties should be included in a single table, may be the file table.

For the driver version i think it's actually the `FileVersion` field of .sys file

![image](https://cloud.githubusercontent.com/assets/6371120/19602566/f3493844-97ad-11e6-8077-10a92cb70402.png)

**Comment by ExtremeGTX** [comment]
After a discussion with @PoppySeedPlehzr we found that implementing driver version will require a lot of effort because of paths returned by Enum functions will require calls to internal NT APIs which needs special way of invoking, for now it will be postponed.

**Comment by ExtremeGTX** [comment]
Some references about the NT Path issue:
[How can I convert a native (NT) pathname into a Win32 path name?](http://stackoverflow.com/questions/4445108/how-can-i-convert-a-native-nt-pathname-into-a-win32-path-name)

[Obtaining a File Name From a File Handle](https://msdn.microsoft.com/en-us/library/aa366789(v=vs.85).aspx)

[NtOpenFile function](https://msdn.microsoft.com/en-us/library/bb432381(v=vs.85).aspx)

**Comment by PoppySeedPlehzr** [comment]
Thanks @ExtremeGTX for this info!

**Comment by friedbutter** [comment]
Thanks @ExtremeGTX !!

**Comment by PoppySeedPlehzr** [comment]
Closing this, as it was addressed with #2675
