### ISSUE TITLE
virtual table: Windows os_version

### ISSUE THREAD

**Issue by PoppySeedPlehzr** [facebook/osquery#2564]
We need a Windows version of the `os_version` virtual table. Check out the [linux](https://github.com/facebook/osquery/blob/master/osquery/tables/system/linux/os_version.cpp) and [OS X](https://github.com/facebook/osquery/blob/master/osquery/tables/system/darwin/os_version.cpp) equivalents. To get started you can copy either the darwin or linux equivalents and start modifying the API calls.  

Once you've got a pretty good table layout, you'll need to move the `os_version.table` from `specs\posix\os_version.table` to `specs\os_version.table`

Reach out to @poppyseedplehzr if you have questions on how to get started!

**Comment by ExtremeGTX** [comment]
@PoppySeedPlehzr I will start working on this issue. 
The implementation will be based on WMI as "osquery/tables/system/windows/users.cpp"
