### ISSUE TITLE
virtual table: Windows etc_protocols equivalent

### ISSUE THREAD

**Issue by PoppySeedPlehzr** [facebook/osquery#2566]
We need an equivalent virtual table to the posix `etc_protocol` table, but this data may or may not exist in Windows native API calls.  For this issue, we'll need to look into what types of information might suffice as an equivalent as I don't think there'll be a 1:1 mapping. 

To get started, checkout the [posix](https://github.com/facebook/osquery/blob/master/osquery/tables/networking/posix/etc_protocols.cpp) `etc_protocol` table to get a feel for the types of data we'll need from Windows. Drop the table into the `osquery\tables\networking\windows`, and once you've got a functioning virtual table, you'll need to move the spec file `specs\posix\etc_protocols.table` to `specs\etc_protocols.table`.

Hit up @poppyseedplehzr if you have any questions!

**Comment by ExtremeGTX** [comment]
the equivalent file for /etc/protocols is available at %WINDIR%\System32\Drivers\etc\protocol
the file has relatively smaller table. 
The API `getprotobynumber()` depends on this file only.
