### ISSUE TITLE
xattr "wherefrom" for downloaded items

### ISSUE THREAD

**Issue by mtmcgrew** [facebook/osquery#257]
In OSX when you download a file from the internet it adds extended attributes to the file that shows where it was downloaded from.

It would be awesome if you could do something like "select file, url from osx_downloads" or something like that to find out what someone has downloaded and where it came from.

http://en.wikipedia.org/wiki/Extended_file_attributes#OS_X

```
mcgrew-mbp:Downloads mcgrew$ xattr -p com.apple.metadata:kMDItemWhereFroms uTorrent.dmg | xxd -r -p | plutil -convert xml1 -o - -
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<string>http://download-new.utorrent.com/endpoint/utmac/os/osx/track/stable/</string>
	<string>http://www.utorrent.com/downloads/complete/os/osx/track/stable</string>
</array>
</plist>
```

**Comment by theopolis** [comment]
Using a master task of issues: https://github.com/facebook/osquery/issues/619
