### ISSUE TITLE
consider using slackarchive.io to archive slack conversations 

### ISSUE THREAD

**Issue by groob** [facebook/osquery#2571]
Slack is a place where a lot of useful conversations related to the development and deployment of osquery happens. Unfortunately, the free version of slack only archives 10000 messages and deletes the rest. This is a problem, because a lot of useful information is removed after a few days.

Other open source communities using slack have chosen to use http://slackarchive.io/ to archive slack conversations and make them available for search at a later time. 
Would integrating the osquery slack with slackarchive be a something the osquery team is willing to explore?

**Comment by theopolis** [comment]
@marpaia, is this something you have cycles to look into?

**Comment by marpaia** [comment]
on it

**Comment by marpaia** [comment]
ok, i set up the bot (username: archiver) and had it join general. slackarchive.io isn't fully automated, so I guess they'll email me when the archives are ready. if we like it, i'll add the bot to the rest of the channels too and give archiver a cool photo.

**Comment by marpaia** [comment]
This is working now: http://osquery.slackarchive.io/

I confirmed messages are being logged for #general and I added the archiver bot to the rest of the channels as well. The rest of the channels should be showing up on http://osquery.slackarchive.io/ soon.

Feel free to close this.

**Comment by theopolis** [comment]
Perfect, thanks Mike!
