### ISSUE TITLE
Support Windows 7 and Server 2008

### ISSUE THREAD

**Issue by dguido** [facebook/osquery#2572]
osquery for Windows has been tested to work on Windows 8.1, Windows 10, and Windows Server 2012. It does not work on Windows 7, Vista, or Server 2008. This is due to osquery core using a few APIs that are specific to those later versions.

We should track down the APIs that are not available in 7 and work around them.

**Comment by zhangchenwhu** [comment]
does this project support windows7 now？@dguido

**Comment by PoppySeedPlehzr** [comment]
@zhangchenwhu currently the osquery client and daemon both only work on Windows 8.0 +.  This is because some of the API calls leveraged during the implementation process didn't exist until Windows 8.

I'm under the impression that back-porting osquery to Windows 7 and Server 2008 might not be too difficult, as it seems it would largely just being converting Windows API calls, however this is currently on our immediate roadmap.

**Comment by cyborg00101** [comment]
@dguido @PoppySeedPlehzr any updates of back-porting Win7 and Server 2008 API calls in the roadmap?

**Comment by PoppySeedPlehzr** [comment]
Hey @cyborg00101, sorry for the late response!  Currently this isn't on the primary osquery developer teams roadmap, however there've been internal teams asking about it, and I know there's plenty of interest externally. As such, I've been toying around with doing this on my own time, so I'll try and put some effort into assessing what APIs need changing.

The first one that I know of was `GetOverlappedResultEx` inside of the `PlatformFile` async reading functionality [here](https://github.com/facebook/osquery/blob/ef3de3d0308720cb1ad6d9faafab25e2aa187cde/osquery/filesystem/windows/fileops.cpp#L821), [here](https://github.com/facebook/osquery/blob/ef3de3d0308720cb1ad6d9faafab25e2aa187cde/osquery/filesystem/windows/fileops.cpp#L871), and [here](https://github.com/facebook/osquery/blob/ef3de3d0308720cb1ad6d9faafab25e2aa187cde/osquery/filesystem/windows/fileops.cpp#L887). The MSDN Documents a `GetOverlappedResult`, which allegedly runs on Windows XP and forward.  That being said, I'm not sure what other API calls will fail if this one is switched out.

**Comment by PoppySeedPlehzr** [comment]
Overall looks like this is pretty feasible. I'm worried somethings concerning the read/write functionality _may_ be broken as the `GetOverlappedResultEx` gives us an `Alertable` flag, but changing that API call to `GetOverlappedResult` is all that was needed.

![windows7](https://cloud.githubusercontent.com/assets/1328916/22052461/40eb70da-dcff-11e6-9936-8014c5441da4.PNG)

I'll keep exploring if this messes with anything, and we'll see about bringing Win7/Server2k8 into the fold.

**Comment by PoppySeedPlehzr** [comment]
So, to take this a measure even further, I got osqueryi and osqueryd building and running on Windows 7, x86, **no** SP 1. This is still pretty experimental, and _not_ guaranteed to be stable as there are numerous warnings, but it looks like the only code mods required are in #2952

![16425405_10100924134299703_741385755_n](https://cloud.githubusercontent.com/assets/1328916/22456324/892256c4-e746-11e6-9b33-9434da590015.png)

**Comment by PoppySeedPlehzr** [comment]
I'm going to close this out, as osquery should now be runnable on Windows 7 and Server 2008. We'll explore getting CI up for 7/2k8, but for now it looks like this is no longer an issue.

**Comment by cyborg00101** [comment]
@poppyseedplehzr Awesome! We have a few 100 in a test group, can't wait to test over the next few weeks.

**Comment by kemalbayar** [comment]
@muffins  I can't run osuqery on windows 7 and windows server 2008

I got the error shown in the picture (1) and when I corrected the permission issue on the folder then I entered the command \programdata\osquery\osqueryd\osquery.exe --install  but I got the error "isnt compatible with this version of windows"

![image](https://user-images.githubusercontent.com/33925821/37396950-6f118d82-278b-11e8-8a95-315aa6e8452c.png)

**Comment by kemalbayar** [comment]
@muffins  I managed to install osquery on windows 7 64 bit and Windows server 2008 R2 64 bit but I couldn't install it on Windows Server 2008 SP2 32 bit (Not R2,64bit)

![image](https://user-images.githubusercontent.com/33925821/37512203-81fa88d0-2912-11e8-82dd-4a0d66d4324d.png)

**Comment by kemalbayar** [comment]
https://github.com/facebook/osquery/issues/2856
i think it's still valid so couldn't install on 32 bit OS ?
