### ISSUE TITLE
Is there any guide for how to configure remote request osquery or any webui for osquery?

### ISSUE THREAD

**Issue by foreversunyao** [facebook/osquery#2580]
Hi everyone,
    I want to set up a remote application to connect to osquery using mysql protocol or any other api. Is there any method to do this ?
   Thanks.

**Comment by kcreyts** [comment]
https://github.com/facebook/osquery/blob/666198909a45ceeb6ec6bd4594cd992b92e943dd/docs/wiki/deployment/remote.md

**Comment by theopolis** [comment]
@kcreyts hit the nail on the head! Let us know if their response wasn't what you had expected and we'll reopen. :)

**Comment by foreversunyao** [comment]
@kcreyts  thank you , I just want to know is there any a whole example for this remote request demo ?  I think these details are too many to build a little demo .
