### ISSUE TITLE
Tables with same name columns can overwrite each other.

### ISSUE THREAD

**Issue by trizt** [facebook/osquery#2581]
Sorry, not sure if this an implementation error from my side or if there is a fault somewhere in osquery.

I have two tables portage_mask and portage_unmask, both with the columns package and version.
The implementation is based on the one for hosts table.

if run the following query:
```sql
select * from portage_unmask 
left join portage_mask on portage_mask.package = portage_unmask.package;
```

I get the following output:
```
+------------------------------+----------+------------------------------+----------+
| package                      | version  | package                      | version  |
+------------------------------+----------+------------------------------+----------+
|                              |          |                              |          |
|                              |          |                              |          |
|                              |          |                              |          |
| mail-client/thunderbird      | >=40.0.0 | mail-client/thunderbird      | >=40.0.0 |
| app-emulation/vmware-modules | <308.1.1 | app-emulation/vmware-modules | <308.1.1 |
+------------------------------+----------+------------------------------+----------+

```
if I instead specify all the tables and use aliases for them, for example the following query:
```sql
select u.package, u.version, m.version as masked from portage_unmask u 
left join portage_mask m on m.package = u.package;
```
which results in the following list:
```
+------------------------------+-----------+----------+
| package                      | version   | masked   |
+------------------------------+-----------+----------+
| sys-devel/automake           | =1.14.1   |          |
| dev-lang/mono                | =4.0.1.34 |          |
| media-libs/opencv            | =3.0.0    |          |
| mail-client/thunderbird      | =38.8.0   | >=40.0.0 |
| app-emulation/vmware-modules | =308.1.1  | <308.1.1 |
+------------------------------+-----------+----------+
```

I would have expected those two queries to give quite similar out put. Have I missed something or this something that may happen?

**Comment by theopolis** [comment]
Right, this is how SQLite parses and interprets your output. There is one artifact introduces by osquery, and that "we expect you to not have collision in column names" meaning alias the resultant names within the explicit select statement, which is completely valid in SQLite; but otherwise you can (in the shell) use `.mode line`.

**Comment by trizt** [comment]
Thanks for explaining that it's behaving as expected, then I take the liberty and close this issue.
