### ISSUE TITLE
backspace key not updating terminal output correctly

### ISSUE THREAD

**Issue by dennisjac** [facebook/osquery#2592]
When entering osqueryi interactive mode on a CentOS 7 system the backspace key seems to update the internal buffers correctly but in the terminal the output is broken. When I enter "xxx" and then hit the backspace key three times the cursor will move to the right once with each key press instead of moving to the left and deleting one "x". Pressing backspace a fourth time will not move the cursor to the right anymore and hitting enter will just result in another prompt which leads me to believe that the internal buffers are updated correctly i.e. after hitting backspace three times the three x's are removed from the internal buffer and hitting enter has the same effect as hitting enter on an empty line.

This renders the interactive mode sort of unusable unless you never make a typo and combined with issue #2591 which i reported earlier renders the tool as a whole pretty much impossible to work with.

**Comment by theopolis** [comment]
I cannot reproduce this behavior. Help me debug by including all the details required to reproduce your environment/setup.

**Comment by dennisjac** [comment]
This is the same system as reported in issue #2591 :
```
[root@virt86 ~]# rpm -qa|grep osquery
osquery-s3-centos7-repo-1-0.0.noarch
osquery-2.0.0-1.el7.x86_64
[root@virt86 ~]# cat /etc/redhat-release 
CentOS Linux release 7.1.1503 (Core) 
[root@virt86 ~]# osqueryi --version
osqueryi version 2.0.0
```

**Comment by theopolis** [comment]
We use `readline` and `ncurses`, in bash and zsh this works, using OS X's default terminal emulator and sshing into a CentOS 7 box-- I still cannot reproduce.

**Comment by aadamowski** [comment]
Got a repro on CentOS 6 and CentOS 7. Working with @theopolis on diagnosing it.

**Comment by theopolis** [comment]
This should be addressed with https://github.com/facebook/osquery/pull/2613
