### ISSUE TITLE
Issue Parsing Existing Pidfiles on Windows

### ISSUE THREAD

**Issue by Centurion89** [facebook/osquery#2598]
Tested on: Windows 2012

Issue: IIf osqueryd.exe is started, creates a pidfile, and then is stopped, any future executions generate a "Could not parse pidfile" error message.
Workaround: Delete osqueryd.pidfile before running it

Repro Steps:
1. Run osqueryd.exe on windows 
2. osqueryd.pidfile gets written to C:\programdata\osquery\osqueryd.pidfile
3. Kill osqueryd.exe and the stale pidfile remains
4. Re-run osqueryd and it will throw a "could not parse pidfile error"

```
PS C:\ProgramData\osquery> dir

    Directory: C:\ProgramData\osquery

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        10/6/2016   8:25 PM                log
d-----        10/6/2016   8:22 PM                osquery.db
d-----        10/6/2016   7:46 PM                osqueryd
-a----        10/6/2016   7:52 PM            224 osquery.conf
-a----        10/1/2016  12:00 PM             51 osquery.flags
-a----        9/28/2016  12:37 PM        8310784 osqueryd.exe
-a----        10/6/2016   8:22 PM              4 osqueryd.pidfile


PS C:\ProgramData\osquery> .\osqueryd.exe --config_path="c:\ProgramData\osquery\osquery.conf" --allow_unsafe --verbose
I1006 20:33:37.225191  5092 init.cpp:342] osquery initialized [version=1.8.2-162-gb77c217]
E1006 20:33:37.240823  5092 init.cpp:376] osqueryd initialize failed: Could not parse pidfile
```

**Comment by PoppySeedPlehzr** [comment]
@yying mentioned this may be throwing a `bad_lexical_cast` exception somewhere.

**Comment by Centurion89** [comment]
We also suspected that there might be a newline present in the pidfile but ruled that out via a hex editor

**Comment by yying** [comment]
Source of the error message: https://github.com/facebook/osquery/blob/master/osquery/core/system.cpp#L198

**Comment by Centurion89** [comment]
Confirmed this is not affecting Win10 and is only occurring on Win2012
