### ISSUE TITLE
windows virtual table: extended kernel_info to Windows

### ISSUE THREAD

**Issue by PoppySeedPlehzr** [facebook/osquery#2604]
Let's extend the `kernel_info` table to Windows

**Comment by ExtremeGTX** [comment]
if we shall use same columns from POSIX table, here is what i have got:

- Kernel version: `10.0.14393.206` [NTOSKRNL.exe file version]
- Kernel arguments: `NOEXECUTE=OPTIN  HYPERVISORLAUNCHTYPE=OFF  NOVGA` [HKLM\SYSTEM\CurrentControlSet\Control\SystemStartOptions]
- Kernel path: `%WINDIR%\System32\ntoskrnl.exe` [Constant]
- Kernel device identifier: c1062db8-adf7-11e4-8254-448a5bd04b8f [Volume GUID]

I will submit a PR soon!

**Comment by theopolis** [comment]
Thanks again @ExtremeGTX!
