### ISSUE TITLE
logger_mode within config file is decimal instead of octal

### ISSUE THREAD

**Issue by 0xd0** [facebook/osquery#2609]
Trying to set the file permissions for the osqueryd.results.log file.  Initially attempted to set to 644 (-rw-r--r--) by setting the logger_mode value within osquery.conf.  Instead, I get 204 (--w----r-T).  If I set the mode to 420, I get the correct file permissions.  This seems to be a decimal/octal conversion error.  Perhaps this is correct behaviour but looking at the documentation would seem to be incorrect then.

Thanks

**Comment by theopolis** [comment]
Right, the documentation is confusing:
```
--logger_mode=640

File mode for output log files (provided as an octal string). Note that this affects both the query result log and the status logs. Warning: If run as root, log files may contain sensitive information!
```

The example value it shows suggests decimal. Mind changing this here: https://github.com/facebook/osquery/blob/master/docs/wiki/installation/cli-flags.md

**Comment by theopolis** [comment]
To be clear, the change needed is to update that markdown wiki page and set the example value to 420.
