### ISSUE TITLE
windows: Clean up Windows virtual tables code

### ISSUE THREAD

**Issue by yying** [facebook/osquery#2620]
A few of the Windows virtual tables use C-style (manual) resource/memory management which may introduce extra complexity, verbosity, and possible resource leakage.

**Comment by PoppySeedPlehzr** [comment]
Should this issue be expanded to just general code cleanup? There's a few other small things @theopolis and I have discussed that could be rolled into this issue as well.

**Comment by yying** [comment]
I think those should be separate issues to make things simpler.

**Comment by PoppySeedPlehzr** [comment]
@yying do you by chance have any specific tables where you saw the worst offenders of this? I'll try and start compiling a list of tables that need some love.

**Comment by yying** [comment]
I took a quick look through the `system/windows/` tables and found the following that have C-style resource management. Some cases may be fine (opening and closing of a resource without any branches/error conditions in between).

https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/kernel_info.cpp
https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/registry.cpp
https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/services.cpp
https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/users.cpp
https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/processes.cpp

**Comment by poppyseedplehzr** [comment]
For some added clarity in respect to the `oss sprint` tag:

This task is focused on upgrading some of the memory management functions leveraged throughout the windows code base to that of a more C++11 styling. For example, a few spots in [kernel_info](https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/kernel_info.cpp#L38) make use of C-style character buffers, and it might be better to leverage `std::vector<char>` for some added potential memory safety.

Additionally there are numerous spots in the Windows code base where we leverage [C-style explicit casts](https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/kernel_info.cpp#L40) and it might be better to make use of a C++ `static_cast` if at all possible.

Feel free to hit up @poppyseedplehzr (or thor in slack) if you have any additional questions of how to approach this or test this!

**Comment by poppyseedplehzr** [comment]
I'm going to go ahead and close this issue out, as almost all of these C-style resources have been addressed in recent PRs by @ryanheffernan. Feel free to re-open or file a new issue if you find more C-style code usage, but I think there aren't _too_ many of these left in the Windows code base :)
