### ISSUE TITLE
windows: Build out more test coverage for PlatformFile, Reading, and Writing

### ISSUE THREAD

**Issue by PoppySeedPlehzr** [facebook/osquery#2622]
We need more test coverage for the PlatformFile class to check for issues with reading and writing in large  cases.  Ensure we have something that stresses Async and overlap reading functionality in Windows.

**Comment by theopolis** [comment]
Addressed in: https://github.com/facebook/osquery/commit/e5ba82993a9f70cb223a9ae1cc407c4ff521ae6d
