### ISSUE TITLE
After upgrade to 2.0 from 1.8.2, kinesis output plugin fails to connect with cert verification failed

### ISSUE THREAD

**Issue by jfdive** [facebook/osquery#2635]
-> After the upgrade, the verbose logs shows:
I1018 07:37:05.157685 21771 aws_util.cpp:325] Using AWS region from flag: us-east-1                                                                                      
E1018 07:37:05.168006 21771 aws_util.cpp:171] Exception making HTTP request to URL (https://kinesis.us-east-1.amazonaws.com): certificate verify failed
E1018 07:37:05.178159 21771 aws_util.cpp:171] Exception making HTTP request to URL (https://kinesis.us-east-1.amazonaws.com): certificate verify failed                  

-> Checked with openssl s_connect:
openssl s_client -showcerts -connect kinesis.us-east-1.amazonaws.com:443 | grep Verify
    Verify return code: 0 (ok)

-> Same end host checked via tcpdump (dns load balancing @ aws i think)
-> downgraded to 1.8.2, its working again.
-> Unaware of a means to enable more debugs to know what is failing.

**Comment by jfdive** [comment]
-> binaries in the test are ubuntu 16.04 packages distributed from osquery.io
-> relevant configuration:
        "aws_access_key_id": "KEY_ID",
        "aws_secret_access_key" : "ACCESS_KEY",
        "aws_region" : "us-east-1",
        "logger_plugin": "aws_kinesis",
        "aws_kinesis_stream" : "osquery.stream1",

**Comment by theopolis** [comment]
Are you using the `--tls_server_certs` flag to provide Amazon's root (and/or intermediates)? Check out: http://osquery.readthedocs.io/en/stable/installation/cli-flags/#remote-settings-optional-for-configloggerdistributed-flags

Check out the release notes for 1.8.2 related to the AWS plugins: https://github.com/facebook/osquery/releases/tag/1.8.2

**Comment by theopolis** [comment]
@jfdive confirmed the TLS server cert must now be explicitly set with Kineses.
