### ISSUE TITLE
tests: Windows' osquery_tests is failing without stdout

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2637]
As of the PR: https://github.com/facebook/osquery/pull/2619 the Windows' `osquery_tests` is always failing.

**Comment by PoppySeedPlehzr** [comment]
I think I've isolated this. It looks like the `platformGetUid` function doesn't return `0` when it's being run as an Administrator, as is intended, which causes the below test to run, and thus fail.

https://github.com/facebook/osquery/pull/2619/files#diff-d664dfa1633378d6f8880fad80628db6R102

**Comment by theopolis** [comment]
So is the test working as intended?

**Comment by PoppySeedPlehzr** [comment]
I believe so yes. I think we are returning in correct results when the tests are being run as an Administrator, which causes `FilesystemTests.test_read_limit` to fail. I've nearly got a PR ready.
