### ISSUE TITLE
How can we retrieve information regarding firewall / ports?

### ISSUE THREAD

**Issue by eldhoj** [facebook/osquery#2642]
Dear Support Team,

We have been researching on osquery for the past couple of days. So far so good. But we have some doubts related to the points listed below.

1. How can we add custom tables?
2. How can we retrieve information regarding firewall / ports from the existing table/s? For eg to get port details from table named "iptables".
3. Is remote querying possible with osquery?

Could you please help me to clarify these doubts as soon as possible. Thanks in advance!

**Comment by PoppySeedPlehzr** [comment]
Hey @eldhoj,

1.) There's some good documentation on creating [new tables here](https://osquery.readthedocs.io/en/stable/development/creating-tables/)
2.) There's a thorough listing of all currently [existing virtual tables here](https://osquery.io/docs/tables/)
3.) We are currently experimenting with this concept, but I don't think there's anything official yet. I believe the client is capable of remote querying it simply needs a backend to help out with maintaining jobs and results.

Hope that helps!

**Comment by PoppySeedPlehzr** [comment]
Also, feel free to re-open or hit me up on slack if you have any additional questions or anything was unclear!
