### ISSUE TITLE
windows: Scheduled Tasks virtual table

### ISSUE THREAD

**Issue by poppyseedplehzr** [facebook/osquery#2645]
Something numerous folks have asked us for is a Windows Scheduled Tasks table.  You'll need to look into getting all of the data that the `at` and `schtasks` commands return from the Windows commandline, and investigate any C++ Windows APIs that might help you retrieve this data.

Ping @poppyseedplehzr (or thor in the slack) if you have any questions!

This might be helpful: https://msdn.microsoft.com/en-us/library/windows/desktop/aa446881(v=vs.85).aspx

**Comment by thor** [comment]
I'm glad you're awake and up, and developing on this cool project, but I'd
recommend not pinging me, seeing as I'm a different @thor to the one you
might've had in mind!

Same goes for the other two issues. :)

Have a good workday!

19. okt. 2016 20:24 skrev "Nick Anderson" <notifications@github.com>:

**Comment by PoppySeedPlehzr** [comment]
@thor my apologies!  Didn't mean to drop that @!

**Comment by thor** [comment]
No problem! I'm curious how come you use that name as a nick when it's not your name, but that's besides the point! 


Sorry for spamming up the project - which really does seem quite interesting. :)


Fra: Nick Anderson

Sendt: onsdag 19. oktober, 20:38

Emne: Re: [facebook/osquery] windows: Scheduled Tasks virtual table (#2645)

Til: facebook/osquery

Kopi: Thor K. H., Mention



@thor my apologies! Didn't mean to drop that @!

**Comment by ExtremeGTX** [comment]
Implementation in progress ....

**Comment by ExtremeGTX** [comment]
@PoppySeedPlehzr 
Here is a list of most properties we can get about a Scheduled task 

**Basic Info:** [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380751(v=vs.85).aspx)
- [ ] Enabled
- [ ] LastRunTime
- [ ] LastTaskResult
- [ ] Name
- [ ] NextRunTime
- [ ] NumberOfMissedRuns
- [ ] Path
- [ ] State


**TaskActions:**[MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa446895(v=vs.85).aspx)
 - [ ] Action Type 
 - [ ] Action Details (depends on type)


**TaskSettings:**[MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa381843(v=vs.85).aspx)
- [ ] AllowDemandStart
- [ ] AllowHardTerminate
- [ ] Compatibility
- [ ] DeleteExpiredTaskAfter
- [ ] DisallowStartIfOnBatteries
- [ ] Enabled
- [ ] ExecutionTimeLimit
- [ ] Hidden
- [ ] IdleSettings
- [ ] MultipleInstances
- [ ] NetworkSettings
- [ ] Priority
- [ ] RestartCount
- [ ] RestartInterval
- [ ] RunOnlyIfNetworkAvailable
- [ ] StartWhenAvailable
- [ ] StopIfGoingOnBatteries
- [ ] WakeToRun
- [ ] XmlText

**TaskPrincipal:**[MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa380742(v=vs.85).aspx)
- [ ] DisplayName
- [ ] GroupId
- [ ] Id
- [ ] LogonType
- [ ] RunLevel
- [ ] UserId

**Comment by PoppySeedPlehzr** [comment]
Hey @ExtremeGTX, this looks great!

I think I'd be interested in grabbing the `LastRunTime` value, as it might be nice to know if a potentially malicious scheduled task has already run at least once. Additionally, what are your thoughts on grabbing data from the `TaskSettings` interface? It seems like getting that `Hidden`, `Enabled`, and some of the `Run` fields might be nice-to-haves.

**Comment by ExtremeGTX** [comment]
@PoppySeedPlehzr 
**Additional info added to current draft implementation:**
- [x] LastRunTime
- [x] LastTaskResult
- [x] NextRunTime
- [x] Logon Type

and based on your comment i will add
- [x] Enabled
- [x] Hidden

I'm not sure what do you mean by `Run` fields, Can you please explain more ?

**Comment by PoppySeedPlehzr** [comment]
`RunOnlyIfNetworkAvailable` and `WakeToRun`. Not entirely convinced those are necessary though, but if the data is there and available maybe grab it?

**Comment by poppyseedplehzr** [comment]
@ExtremeGTX any progress on this?

**Comment by poppyseedplehzr** [comment]
This table has been implemented and merged into master.
