### ISSUE TITLE
windows: Listening ports virtual table

### ISSUE THREAD

**Issue by PoppySeedPlehzr** [facebook/osquery#2648]
Let's extend the posix `listening_ports` virtual table to support Windows.  Some example output can be achieved by typing `netstat -anob` on the Windows command line.  To accomplish this you'll need to investigate which Windows C++ API calls might be able to get you back the data that is populating the [posix equivalent table here](https://osquery.io/docs/tables/#listening_ports)

**Comment by PoppySeedPlehzr** [comment]
Just so folks know, I'm currently working on this table.

**Comment by theopolis** [comment]
Listening ports? ;)
