### ISSUE TITLE
Add virtual table for Windows to list Browser Helper Objects

### ISSUE THREAD

**Issue by friedbutter** [facebook/osquery#2649]
We should enumerate the BHO list. 

> The relevant registry key is: HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Browser Helper Objects.  If this key exists and there are CLSID’s listed underneath it, then Internet Explorer uses that information to create an instance of each object.  The CLSID of the object must be listed as a subkey and not a named value.  These registry keys can be created manually although the self-registration of the BHO may create the registry key as well.  Again, it’s important to note that multiple copies of the BHO are loaded if you explicitly open new instances of Internet Explorer.  Opening a new window from IE is different than launching a new instance of iexplore.exe.  When you open new windows from Internet Explorer, each window is duplicated in a new thread without originating a new process – and therefore without reloading BHO’s.  By comparison, Windows File Explorer will load a separate BHO instance for each new window that is created.

Ref: https://en.wikipedia.org/wiki/Browser_Helper_Object

**Comment by poppyseedplehzr** [comment]
@friedbutter is this still relevant if we have the Windows registry virtual table? Can we just enumerate the values of that key? Maybe this issue wuuld be better suited as a pack instead?

**Comment by friedbutter** [comment]
It would be nice to get all the BHO. Perhaps we can build a view instead since there could be multiple locations to store BHOs.

**Comment by theopolis** [comment]
I agree, this should be it's own table and use the registry methods.

**Comment by UnrealAkama** [comment]
I sat down to take a stab at this but it appears it's already done.
https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/ie_extensions.cpp
Should this issue be closed?

**Comment by muffins** [comment]
@UnrealAkama ah yeah, sorry about that! Closing out.
