### ISSUE TITLE
linting: change NULLs to nullptrs

### ISSUE THREAD

**Issue by PoppySeedPlehzr** [facebook/osquery#2651]
There's a few instances of `NULL` being used throughout our code base. Go through and change these occurances to make use of `nullptr` to make our linters happy. For more information about why one should use `nullptr` over `NULL`, check out [this doc](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2431.pdf)

Ping @poppyseedplehzr (or thor in the slack) if you have any questions!

```
osquery/tables/applications/windows/carbon_black.cpp
Advice	(FBCPP3) CppLint Advice at line 122
Advice: Prefer `nullptr' to `NULL' in new C++ code.

osquery/tables/system/uptime.cpp
Advice  (FBCPP3) CppLint Advice at line 30
Advice  (FBCPP3) CppLint Advice at line 35
Advice: Prefer `nullptr' to `NULL' in new C++ code.
```

**Comment by IamAdiSri** [comment]
Hey, I'm beginning work on this.
From what I understand, every single `NULL` in the code is to be replaced by 'nullptr', right?

**Comment by IamAdiSri** [comment]
@PoppySeedPlehzr r?

**Comment by PoppySeedPlehzr** [comment]
@IamAdiSri Yep!  That should largely be it, thanks!
