### ISSUE TITLE
linting: shorten long lines

### ISSUE THREAD

**Issue by PoppySeedPlehzr** [facebook/osquery#2652]
Our linter gets upset with lines over the 80 character column limit. We can have a deep and insightful philosophical debate in this issue regarding the optimal column limit, but in the meantime let's make our linter happy and reduce the length of these lines!

Ping @poppyseedplehzr (or thor in the slack) if you have any questions!

**Edit: this list turned out to be much shorter than I originally though ;)  Will update if I find any more.**

```
osquery/logger/plugins/filesystem.cpp
Advice  (LINE_WRAP1) Line Too Long at line 153
This line is 84 characters long, but the convention is 80 characters.

osquery/main/lib.cpp
Advice  (LINE_WRAP1) Line Too Long at line 37
This line is 84 characters long, but the convention is 80 characters.

osquery/remote/transports/tls.h
Advice  (LINE_WRAP1) Line Too Long at line 26
This line is 81 characters long, but the convention is 80 characters.
Advice  (LINE_WRAP1) Line Too Long at line 29
This line is 101 characters long, but the convention is 80 characters.
```

**Comment by JamesShaeffer** [comment]
There is no "generated" folder that I can find.

**Comment by cglewis** [comment]
I'll take a stab at this one.

**Comment by PoppySeedPlehzr** [comment]
@cglewis sounds good! Thanks for letting us know!

**Comment by va6996** [comment]
@PoppySeedPlehzr , I was planning on making a script that automates this procedure. In case you want to switch back to >80 char columns, you could just modify the script and there you are!

**Comment by cglewis** [comment]
@va6996 feel free to take over if you'd like.

**Comment by va6996** [comment]
Cool!

**Comment by va6996** [comment]
@PoppySeedPlehzr , after, having a look at the files, I couldn't find few of the files as mentioned and other files don't have characters > 80.
eg https://github.com/facebook/osquery/blob/master/osquery/sql/sqlite_math.cpp
line 26 is
#include "osquery/core/utils.h"

**Comment by PoppySeedPlehzr** [comment]
@va6996 Yeah I think I have the files associated with the wrong linting errors, things got mixed up when I was copying them over. Give me just a bit and I'll try and clean this up!

**Comment by PoppySeedPlehzr** [comment]
@va6996 Also I might be bundling up some of our third party code linting errors >.> My apologies, I'll get the issue cleaned up.

**Comment by va6996** [comment]
@PoppySeedPlehzr , I had created a script. It more or less works fine.
But here are some implementation doubts:
In osquery/include/osquery/tables.h, line 29,
there is a \ in the 81st column. The script automatically moves the \ to another line which is redudant. Also, comments larger than 80 characters also get \ appended which is redundant.

**Comment by PoppySeedPlehzr** [comment]
@va6996 I would say whatever our .clang-format file formats the files too is what we want :)

Tabs should be 2 spaces. Let me know if you have any other questions, thanks!
