### ISSUE TITLE
linting: header include order

### ISSUE THREAD

**Issue by PoppySeedPlehzr** [facebook/osquery#2653]
We have numerous linting errors regarding the ordering of our header includes. Go through and re-order the headers to satisfy our linter!

Ping @poppyseedplehzr (or thor in the slack) if you have any questions!

**Note: This one might be a little trickier to test, as I don't believe our `.clang-format` file checks for these orderings.  I'll update as soon as I can with a good method for checking your progress!

Each one of the following entries has this linter error:
```
The associated header file of .cpp files should be included before any other includes. (This helps catch missing header file dependencies in the .h)
```

```
osquery/extensions/interface.cpp
Error (FBCPP1) CppLint Error at line 20

osquery/config/parsers/decorators.cpp
Error (FBCPP1) CppLint Error at line 16

osquery/core/watcher.cpp
Error (FBCPP1) CppLint Error at line 28

osquery/core/windows/wmi.cpp
Error (FBCPP1) CppLint Error at line 14

osquery/database/query.cpp
Error (FBCPP1) CppLint Error at line 15

osquery/dispatcher/distributed.cpp
Error (FBCPP1) CppLint Error at line 17

osquery/dispatcher/scheduler.cpp
Error (FBCPP1) CppLint Error at line 23

osquery/events/darwin/iokit.cpp
Error (FBCPP1) CppLint Error at line 17

osquery/events/kernel.cpp
Error (FBCPP1) CppLint Error at line 14

osquery/events/linux/audit.cpp
Error (FBCPP1) CppLint Error at line 20

osquery/events/linux/inotify.cpp
Error (FBCPP1) CppLint Error at line 22

osquery/events/linux/syslog.cpp
Error (FBCPP1) CppLint Error at line 31

osquery/logger/plugins/aws_firehose.cpp
Error (FBCPP1) CppLint Error at line 26

osquery/logger/plugins/aws_kinesis.cpp
Error (FBCPP1) CppLint Error at line 28

osquery/logger/plugins/aws_util.cpp
Error (FBCPP1) CppLint Error at line 32

osquery/logger/plugins/buffered.cpp
Error (FBCPP1) CppLint Error at line 25

osquery/logger/plugins/tls.cpp
Error (FBCPP1) CppLint Error at line 22

osquery/remote/serializers/json.cpp
Error (FBCPP1) CppLint Error at line 12

osquery/sql/sqlite_util.cpp
Error (FBCPP1) CppLint Error at line 16

osquery/sql/virtual_table.cpp
Error (FBCPP1) CppLint Error at line 18

osquery/tables/applications/browser_utils.cpp
Error (FBCPP1) CppLint Error at line 13

osquery/tables/system/darwin/packages.cpp
Error (FBCPP1) CppLint Error at line 18

osquery/tables/system/posix/magic.cpp
Error (FBCPP1) CppLint Error at line 12

osquery/tables/system/windows/registry.cpp
Error (FBCPP1) CppLint Error at line 29

osquery/tests/test_util.cpp
Error (FBCPP1) CppLint Error at line 30
```

**Comment by PoppySeedPlehzr** [comment]
I'll update this issue here in a bit, apparently it got posted before I was ready!

**Comment by cornelisonc** [comment]
I can pick this up when it is ready.

**Comment by PoppySeedPlehzr** [comment]
@cornelisonc sounds good! I'll update the issue here in a bit, I'm en route to my office so don't have my laptop for a bit.

**Comment by vjon** [comment]
@PoppySeedPlehzr, any update on that progress checking method?

**Comment by PoppySeedPlehzr** [comment]
Hey @vjon, really sorry to due this, but on second thought I think we're going to close this out and table this topic for a while.

Right now we don't have a good way to test this, as these issues span across OS, and the linter I keep referring to is an internal one. Moreover, we're not entirely sure that this linters suggestions is the direction we want to take, which uncovered a bigger issue -- Do we want to simply make an overhaul attempt on header includes, and have a centralized header that pulls all of our header deps, a la `Windows.h` style, or should we continue on with our current implementation.

Really sorry to bail on this issue, and I hope you hadn't invested too much time in it.  My apologies!

**Comment by vjon** [comment]
Sounds good, just glad I checked in before putting in any work :)
