### ISSUE TITLE
RocksDB Permission denied on OS X makes osqueryd hang

### ISSUE THREAD

**Issue by zbuc** [facebook/osquery#2690]
I am running `osqueryd` 2.0.0 as root on OS X 10.12.1.

The invocation looks like this (hostname censored):

`/usr/local/bin/osqueryd --database_path=/usr/local/zentral/osquery/db --tls_hostname=myhostname --enroll_tls_endpoint=/osquery/enroll --enroll_secret_path=/usr/local/zentral/osquery/enroll_secret.txt --config_plugin=tls --config_tls_endpoint=/osquery/config --config_tls_refresh 120 --logger_plugin=tls --logger_tls_endpoint=/osquery/log --logger_tls_period 60 --disable_distributed=false --distributed_plugin=tls --distributed_tls_read_endpoint=/osquery/distributed/read --distributed_tls_write_endpoint=/osquery/distributed/write --distributed_interval 60 --tls_server_certs=/usr/local/zentral/tls_server_certs.crt`

Every once in a while, `osqueryd` grinds to a halt and I see something similar to the following in the client logs:

`I1027 12:54:44.806229 169996288 rocksdb.cpp:134] RocksDB: [WARN] Compaction error: IO error: /usr/local/zentral/osquery/db/000055.sst: Permission denied`

The permissions on the file and directory look okay to me:

```
root# ls -la /usr/local/zentral/osquery/db/
total 20208
drwx------  28 root  admin     952 Oct 27 12:54 .
drwxr-xr-x   4 root  admin     136 Oct 26 21:07 ..
-rw-r--r--   1 root  admin  370189 Oct 26 21:08 000008.sst
-rw-r--r--   1 root  admin    1239 Oct 27 12:41 000024.sst
-rw-r--r--   1 root  admin    9990 Oct 27 12:41 000026.sst
-rw-r--r--   1 root  admin  613971 Oct 27 12:41 000027.log
-rw-r--r--   1 root  admin  670371 Oct 27 12:43 000029.log
-rw-r--r--   1 root  admin  610794 Oct 27 12:45 000031.log
-rw-r--r--   1 root  admin  610794 Oct 27 12:46 000033.log
-rw-r--r--   1 root  admin  610794 Oct 27 12:47 000035.log
-rw-r--r--   1 root  admin  610797 Oct 27 12:48 000038.log
-rw-r--r--   1 root  admin  616931 Oct 27 12:49 000040.log
-rw-r--r--   1 root  admin  620722 Oct 27 12:49 000042.log
-rw-r--r--   1 root  admin  616184 Oct 27 12:50 000044.log
-rw-r--r--   1 root  admin  617601 Oct 27 12:49 000046.sst
-rw-r--r--   1 root  admin  615932 Oct 27 12:51 000047.log
-rw-r--r--   1 root  admin  307985 Oct 27 12:50 000048.sst
-rw-r--r--   1 root  admin  616058 Oct 27 12:53 000049.log
-rw-r--r--   1 root  admin  307985 Oct 27 12:51 000050.sst
-rw-r--r--   1 root  admin  615932 Oct 27 12:54 000051.log
-rw-r--r--   1 root  admin  307985 Oct 27 12:53 000052.sst
-rw-r--r--   1 root  admin     662 Oct 27 12:54 000053.log
-rw-r--r--   1 root  admin  307985 Oct 27 12:54 000054.sst
-rw-r--r--   1 root  admin  617601 Oct 27 12:54 000055.sst
-rw-r--r--   1 root  admin      16 Oct 27 12:41 CURRENT
-rw-r--r--   1 root  admin      33 Oct 26 21:07 IDENTITY
-rw-r--r--   1 root  admin       0 Oct 26 21:07 LOCK
-rw-r--r--   1 root  admin    2104 Oct 27 12:54 MANIFEST-000025
```

Any ideas?

**Comment by zbuc** [comment]
I have tried `rm -rf`ing the `/usr/local/zentral/osquery/db/` directory, which causes it to be rebuilt, but eventually I see the error message again.

`osquery` was installed from the osquery.io website.

**Comment by theopolis** [comment]
@zbuc I don't think we ever found out what was causing the DB error in versions `1.7.x`. I'm curious, when you encounter this issue does restarting the service without touching the rRB files help? If that's the case then a quick fix from our side would be to restart the worker if it encounters DB `IO error`s.

**Comment by zbuc** [comment]
@theopolis Yep, restarting the service seems to clear it up, at least until it hangs again:

```I1028 11:49:42.022681 27328512 rocksdb.cpp:134] RocksDB: [WARN] Compaction error: IO error: /usr/local/zentral/osquery/db/000070.sst: Permission denied

*here I kill and restart the daemon*

I1031 11:20:47.292186 3029070784 rocksdb.cpp:191] Opening RocksDB handle: /usr/local/zentral/osquery/db
E1031 11:20:47.563021 3029070784 init.cpp:574] [Ref #1629] osqueryd initialize failed: Could not initialize database
I1031 11:20:57.457983 3029070784 rocksdb.cpp:191] Opening RocksDB handle: /usr/local/zentral/osquery/db
I1031 11:21:00.126502 3029070784 events.cpp:637] Event publisher failed setup: kernel: Cannot access /dev/osquery
I1031 11:21:00.152559 3029070784 events.cpp:637] Event publisher failed setup: scnetwork: Publisher not used
I1031 11:21:00.178539 3029070784 events.cpp:863] Error registering subscriber: process_events: No kernel event publisher
I1031 11:21:00.204174 3029070784 events.cpp:863] Error registering subscriber: process_file_events: No kernel event publisher```

**Comment by zbuc** [comment]
Ran from start at `11:20:47` until just now, hanging with the same error:

```
I1031 11:33:55.124588 161333248 rocksdb.cpp:134] RocksDB: [WARN] Compaction error: IO error: /usr/local/zentral/osquery/db/000104.sst: Permission denied
```

**Comment by theopolis** [comment]
I don't think it does. :( Take a look at the second status line after you restart.

**Comment by theopolis** [comment]
Are there any other osquery processes running that may be accessing the same DB path?

**Comment by zbuc** [comment]
@theopolis yeah, it looks like the database doesn't initialize, but `osqueryd` is able to run, execute scheduled queries, and send data back to my server.

There is another `osqueryd` process running, labeled `worker`:

```
root             41144   0.0  0.2  2545504  33500   ??  SN   11:20AM   0:09.12 osqueryd: worker
root             41143   0.0  0.1  2466372   9432   ??  SNs  11:20AM   0:00.23 /usr/local/bin/osqueryd --database_path=/usr/local/zentral/osquery/db --tls_hostname=MYHOSTNAME --enroll_tls_endpoint=/osquery/enroll --enroll_secret_path=/usr/local/zentral/osquery/enroll_secret.txt --config_plugin=tls --config_tls_endpoint=/osquery/config --config_tls_refresh 120 --logger_plugin=tls --logger_tls_endpoint=/osquery/log --logger_tls_period 60 --disable_distributed=false --distributed_plugin=tls --distributed_tls_read_endpoint=/osquery/distributed/read --distributed_tls_write_endpoint=/osquery/distributed/write --distributed_interval 60 --tls_server_certs=/usr/local/zentral/tls_server_certs.crt
```

**Comment by zbuc** [comment]
I don't seem to have any other LaunchAgents that should run another instance of `osqueryd`:

```
$ sudo launchctl list | grep -i osq
41143	78	com.facebook.osqueryd
```

**Comment by theopolis** [comment]
Ok, the worker process is fine.

**Comment by theopolis** [comment]
This might be the fix: https://github.com/facebook/osquery/pull/2908 the watcher should impose an actual wait for the child worker.

**Comment by jedi22** [comment]
@zbuc Are you still experiencing this hang on the new versions of osquery (or at least a version that contains fix #2908)?

**Comment by zbuc** [comment]
No, now I receive an OOM error:

```
W0318 15:51:47.529023 71049216 watcher.cpp:251] osqueryd worker (31004): Memory limits exceeded: 293859328
W0318 15:51:47.529078 71049216 watcher.cpp:407] osqueryd worker respawning too quickly: 19 times
```

**Comment by theopolis** [comment]
Wow, I can't imagine what's causing that massive allocation. If you set `--watchdog_memory_limit=500000` (around 500mB) it may get past the allocation request. It could be a large LaunchDaemon/LaunchAgent?

**Comment by jedi22** [comment]
@zbuc Did you figure out what was causing such massive allocations?

**Comment by theopolis** [comment]
Let's close this out and re-open if it's still occurring!
