### ISSUE TITLE
Integrate with MariaDB Connect engine for cross-table queries

### ISSUE THREAD

**Issue by andrisi** [facebook/osquery#2691]
Seems like the perfect match: https://mariadb.com/kb/en/mariadb/connect/

**Comment by theopolis** [comment]
Hi @andrisi, what use cases or example did you have in mind?

**Comment by andrisi** [comment]
@theopolis Good question. This "see the whole world as a relational database" is a longtime research project of mine, but I am not sure there is a good business case for it in osquery. I always look for connections between databases/tables that could be useful. Something like look at processes/files owned by recently hired employees? Average load generated by someone at the marketing department? I'll think about it a bit more. Do you see the potential for the connect engine in MariaDB otherwise?

**Comment by theopolis** [comment]
Sorry for ignoring this for so long. If there's active work or requirements we need to implement please feel free to update; otherwise let's mark wishlist and keep inactive.
