### ISSUE TITLE
Implement 'extended' os_version columns for darwin and Windows

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2701]
The Linux `os_version` table was extended to include some new columns. These are empty on the `windows` and `darwin` platforms. It would be helpful to represent similar data.

**Comment by PoppySeedPlehzr** [comment]
I don't think this should be closed yet as we still need this implemented for Windows?

**Comment by theopolis** [comment]
:+1:

**Comment by theopolis** [comment]
Now fixed in https://github.com/facebook/osquery/pull/2715.
