### ISSUE TITLE
TLS Config plugin makes GET requests since v2.1.0

### ISSUE THREAD

**Issue by np5** [facebook/osquery#2705]
The 2.1 and 2.1.1 versions of osqueryd make `GET` requests to the config endpoint. It used to be `POST` requests, as documented [here](https://osquery.readthedocs.io/en/stable/deployment/remote/).

I might be wrong, but I think this is a consequence of b00118a2930dc402fc743255573a8034b1f06a82.

**Comment by PoppySeedPlehzr** [comment]
Hey @np5, that's a good call. We had a bug with the logger `tls` plugin being migrated to the `Request` API as was mentioned in the discussion thread of that PR, but it looks like we never got around to updating the documentation on what this process looks like.

Thanks!

**Comment by theopolis** [comment]
Fixed in #2708.
