### ISSUE TITLE
want a file

### ISSUE THREAD

**Issue by bluebirdx** [facebook/osquery#2707]
hi guys i m new here ....i want a ddos script file ....where ca i get it?

**Comment by PoppySeedPlehzr** [comment]
Hey @bluebirdx! Welcome to github!  I think you might be looking in the wrong place for that type of a script ;) osquery is a tool designed for host based introspection, and falls on the defensive side of things.  Let us know if you have any questions getting started with osquery though, if you decide you want to checkout the defensive side of life :)

**Comment by mtmcgrew** [comment]
I do have such file. But it will cost you...

![t](http://s2.quickmeme.com/img/76/762195e1666497074ede151e0cbeb39738a411d967572cbbe24b90cf8db6011f.jpg)

**Comment by bluebirdx** [comment]
lol....you guys .......i think i'm gonna have fun learning in this site
 :dagger:
