### ISSUE TITLE
Dump ALL available info to JSON?

### ISSUE THREAD

**Issue by josdotso** [facebook/osquery#2723]
I'm new to osquery.  Is there an easy way to generate a, probably very large, JSON object which contains all that osquery knows about the entire system?

**Comment by theopolis** [comment]
Not exactly unfortunately.

You can try something like:
```bash
for name in `osqueryi --noheader "select name from osquery_registry where registry = 'table'" --csv`;\
  do osqueryi --json "select * from $name"; done
```

But it's not proper JSON, just a `\n\n` delimited set of arrays.

**Comment by theopolis** [comment]
Let me know if there's anything else we can help with! :)
