### ISSUE TITLE
osqueryd does not parse all users HKEY_CURRENT_USER hive

### ISSUE THREAD

**Issue by PoppySeedPlehzr** [facebook/osquery#2732]
Currently osqueryd runs as the `SYSTEM` user on Windows, which means that any queries to `HKEY_CURRENT_USER` will not return results, as we don't parse individual users `HKCU` hives.

**Comment by theopolis** [comment]
A WARNING message was added if `HKCU` is used: https://github.com/facebook/osquery/commit/476cd714f41412531cbfcb5fb49b977c96de4523

The correct approach is to use the `HKEY_USERS` hive.
