### ISSUE TITLE
[Feature Request] - Granular control flags for watchdog levels

### ISSUE THREAD

**Issue by mattjane-okta** [facebook/osquery#2736]
Looking for the ability to modify the watchdog limits beyond the settings of 0,1 and -2.  
Would like to be able to explicitly set limits via either command line flag or config option.

@theopolis for awareness re: slack chat

IE:
```
MEMORY_LIMIT=250
UTILIZATION_LIMIT=500
RESPAWN_LIMIT=60
RESPAWN_DELAY=2
LATENCY_LIMIT=10
{INTERVAL, {3, 3, 3}},
```

**Comment by theopolis** [comment]
We went with two additional flags to control the watchdog (#2858):
* `watchdog_memory_limit`
* `watchdog_utilization_limit`

Short writeups here: http://osquery.readthedocs.io/en/stable/installation/cli-flags/

I think this is good to go!
