### ISSUE TITLE
Bump augeas to 1.7 GA

### ISSUE THREAD

**Issue by thedrow** [facebook/osquery#2773]
We are currently 3 commits behind 1.7 GA.
We need to upgrade as soon as we can.

**Comment by theopolis** [comment]
Is there anything in these commits that we need? I know shipping with the GA is well organized and recommended, but if there are no high priority changes we need I'll let this sit for a while.

Migrating the formula to build from release code will take some more thought, and then it means rerolling bottle hashes and syncing them to S3.

**Comment by thedrow** [comment]
I don't think there's relevant code as it seems that it only refers to translations e.g. https://github.com/hercules-team/augeas/commit/a198ea74fe58ce780edfe890a21272b23dc29a3d but it's still a best practice.

**Comment by theopolis** [comment]
We feel a little behind, but now we're at 1.8.0: https://github.com/facebook/osquery/pull/3126
