### ISSUE TITLE
Event publisher failed setup: kernel: Could not allocate shared buffer

### ISSUE THREAD

**Issue by finid** [facebook/osquery#2801]
On Ubuntu 16.04, I got the following error after `touch`-ing /dev/osquery, whose absence was generating an error of its own:

```
Event publisher failed setup: kernel: Could not allocate shared buffer
```
Any clues?

TIA

**Comment by PoppySeedPlehzr** [comment]
Hey @finid, as I mention in #2802, we've got a slack that should be better for troubleshooting issues such as these: https://osquery-slack.herokuapp.com/

daemon errors about the publishers failing shouldn't stop too much up, that being said are you running the daemon as root? Can you post the output of running the daemon with `--verbose`? Also, if you don't mind, hit me up on the slack and we can figure things out there. :)

**Comment by theopolis** [comment]
The `kernel` publisher on Linux is a no-op. We use this only on OS X. If there is no device node for osquery in `/dev/` please don't try to create it yourself. :O

This message should be `INFO`rmational, use of the optional device node is documented loosely here: http://osquery.readthedocs.io/en/stable/development/kernel/. Regardless, perhaps we can improve the `INFO` line here.

**Comment by finid** [comment]
OK, I need to be on Slack.

By the way, I run the daemon as root.

See you on slack sometime tomorrow.

**Comment by PoppySeedPlehzr** [comment]
I'm going to go ahead and close this issue out then, please feel free to re-open, or just hit us up on slack if you have more questions :)

**Comment by finid** [comment]
Response on slack seems to be slow in coming, so I'm trying here. 

The error that preceded this one has to do with the kernel publisher failing because it could not find `/dev/osquery`

I think that should qualify as a bug and not a configuration issue. That file is supposed to be created automatically, right?

If correct, what's the solution? http://osquery.readthedocs.io/en/stable/development/kernel/ doesn't help very much.
