### ISSUE TITLE
Query has invalid interval: file_paths: 3600

### ISSUE THREAD

**Issue by finid** [facebook/osquery#2802]
Trying to get file integrity monitoring to work, so I copied the configuration below the [official guide]() and put it in a `fim-conf` file under `/usr/share/osquery/packs`.

```
{
        "queries": {
                "file_events": {
                        "query": "select * from file_events;",
                        "removed": false,
                        "interval": 300
                },
                "file_paths": {
                        "homes": [
                                "/root/.ssh/%%",
                                "/home/%/.ssh/%%"
                        ],
                        "etc": [
                                "/etc/%%"
                        ],
                        "tmp": [
                                "/tmp/%%"
                        ]
                }
        }
}
```

When I run `osqueryctl config-check`, I get the following error:

```
W1128 19:55:18.566701  5881 packs.cpp:189] Query has invalid interval: file_paths: 3600
```
Don't know what to do about that error. Searching does not turn up anything useful. As you can see from the configuration above, the interval defined for file event queries is 300, not 3600. And aside from intervals defined in other pack files, the only other occurrence of the 3600 interval is in `osquery.conf`, under the system_info scheduled query.

By the way, this is an attempt on osquery running on Ubuntu 16.04.

**Comment by PoppySeedPlehzr** [comment]
Hey @finid!  We have a slack channel that might be a little better suited to troubleshooting configuration issues: https://osquery-slack.herokuapp.com/

That being said, what does the contents of your `osquery.conf` file look like? Does the `config-check` pass if you check the conf file? I'm not spotting any issues with your FIM pack, but I could be missing something.

**Comment by theopolis** [comment]
Is this the guide: http://osquery.readthedocs.io/en/stable/deployment/file-integrity-monitoring/ (the OP link isn't working for me).

Your configuration is placing `file_paths` into the `schedule`, that's incorrect. ;D

Instead you should write:
```json
{
        "queries": {
                "file_events": {
                        "query": "select * from file_events;",
                        "removed": false,
                        "interval": 300
                }
        },
        "file_paths": {
                "homes": [
                        "/root/.ssh/%%",
                        "/home/%/.ssh/%%"
                ],
                "etc": [
                        "/etc/%%"
                ],
                "tmp": [
                        "/tmp/%%"
                ]
        }
}
```

**Comment by finid** [comment]
Thanks, that fixed it. `config-check` passes now. Only [#2801](https://github.com/facebook/osquery/issues/2801) remains.
