### ISSUE TITLE
make deps fails on Ubuntu Lucid

### ISSUE THREAD

**Issue by danielpops** [facebook/osquery#2804]
Something must have changed with homebrew since the last time I ran the `make deps` target on 11/25/2016, as it now fails with an error about running as root:

```
Step 17 : RUN make deps
 ---> Running in 57182ffab8b8
./tools/provision.sh build lucid
[+] found ubuntu provision script: /osquery/osquery/tools/provision/ubuntu.sh
[+] creating build dir: /usr/local/osquery
[+] requesting sudo: mkdir -p /usr/local/osquery
[+] setting up new brew in /usr/local/osquery
Initialized empty Git repository in /usr/local/osquery/.git/
[+] refreshing local tap: osquery-local
[+] installing and updating Homebrew core
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
make: *** [deps] Error 1
The command '/bin/sh -c make deps' returned a non-zero code: 2
make: *** [docker_build] Error 2
```

As of last week, this used to be a warning, but it now appears to be an error that fails the `make deps` target immediately.

Sure, I can change the user to e.g. nobody, but certain parts of the `make deps` target then fail for various reasons:

```
Error: Failed to download resource "libaptpkg"
Download failed: https://osquery-packages.s3.amazonaws.com/bottles/libaptpkg
Warning: Bottle installation failed: building from source.
==> Downloading https://github.com/Debian/apt/archive/1.3.1.tar.gz
==> Downloading from https://codeload.github.com/Debian/apt/tar.gz/1.3.1
==> Patching
patching file CMake/Documentation.cmake
patching file CMakeLists.txt
patching file apt-pkg/CMakeLists.txt
Error: Permission denied @ dir_s_mkdir - /nonexistent
```

or

```
[+] brew package osquery/osquery-local/glibc installing new version: 2.19
==> Installing glibc from osquery/osquery-local
==> Downloading https://osquery-packages.s3.amazonaws.com/bottles/glibc-2.19.x86_64_linux.bottle.tar.gz
==> Pouring glibc-2.19.x86_64_linux.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall osquery/osquery-local/glibc`
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local/osquery.

osquery runtime

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/osquery/opt/glibc/lib
    CPPFLAGS: -I/usr/local/osquery/opt/glibc/include
```

and some others that are too far beyond my scrollback at the moment. I have been playing wak-a-mole to get sufficient permissions on all relevant folders, but I figured I would ask here and see if this is a problem that somebody else has already solved?

**Comment by theopolis** [comment]
Wait, you definitely don't need root permissions here.

Can you try:
```
$ make depsclean
$ make deps
```

**Comment by theopolis** [comment]
We don't support building on Lucid, that's so far into the past it's just not possible to set up and maintain our AWS CI for a 2010 OS. 

Do you know what `glibc` runtime your servers use?

If it's `>=2.13` then you can use the `precise` or `trusty` packages (they're essentially the same binaries, same with `xenial` only that DEB will install a `systemd` service.

If it's `<2.13` then even the Lucid build is not going to work since osquery's deps now pull down and link against an exact version of `glibc==2.13`.

**Comment by theopolis** [comment]
If you're in the `<2.13` boat then the only way forward is a small experiment I'm planning. The unified Linux build can produce a RPM/DEB/TGZ that has an osquery with a `RPATH` to a linker + glibc + friends + zlib that we control. That "universal" install will be rather large, but allow for relics of the past or odd network equipment that has an x86_64 processor to run the binaries.

**Comment by danielpops** [comment]
I am observing the same behavior on lucid, trusty, and xenial.  I've created a dockerfile for each distro to serve as a repro for what I'm seeing.

If I run as `root`, I'm faced with the error from my first message:
```
Step 10 : RUN make deps
 ---> Running in 3ab8b52c55cb
./tools/provision.sh build trusty
[+] found ubuntu provision script: /osquery/osquery/tools/provision/ubuntu.sh
[+] creating build dir: /usr/local/osquery
[+] requesting sudo: mkdir -p /usr/local/osquery
[+] setting up new brew in /usr/local/osquery
Cloning into '/usr/local/osquery'...
[+] refreshing local tap: osquery-local
[+] installing and updating Homebrew core
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
make: *** [deps] Error 1
The command '/bin/sh -c make deps' returned a non-zero code: 2
make: *** [docker_build_trusty] Error 2
```

If I run as the `nobody` user, I get challenged for sudo:
```
Step 9 : USER nobody
 ---> Using cache
 ---> dd50a3669c27
Step 10 : RUN make deps
 ---> Running in 49039c266ffa
./tools/provision.sh build xenial
[+] found ubuntu provision script: /osquery/osquery/tools/provision/ubuntu.sh
[+] requesting sudo: apt-get -y update
sudo: no tty present and no askpass program specified
make: *** [deps] Error 1
Makefile:123: recipe for target 'deps' failed
The command '/bin/sh -c make deps' returned a non-zero code: 2
make: *** [docker_build_xenial] Error 2
```

So I go down the rabbit hole of trying to grant whatever permissions necessary to the `nobody` user (wack-a-mole like i said... add passwordless sudo, create and chown /root/.cache, create and chown /usr/local/osquery, etc.).  Its surprising to me that I'm the only one seeing this.

**Comment by theopolis** [comment]
Got it! That looks like a different issue.

For automation you'll have to add some configuration so your user can `sudo`. I can help with that if you post your `Dockerfile` since I do it all the time for various things in AWS. But I don't think there're any action items for changing the osquery tooling.

For more details about `make deps` check out the building wiki page: http://osquery.readthedocs.io/en/stable/development/building/

**Comment by defaultnamehere** [comment]
I'm having the same issues now that homebrew forbids running as root. I've added a non-sudo user (Generic Dockerfile below), but it looks like `make deps` isn't requesting sudo for the git clone, but it is for the creation of /usr/local/osquery, so it can't clone there without root.

```
ubuntu1504_1  | [+] creating build dir: /usr/local/osquery
ubuntu1504_1  | [+] requesting sudo: mkdir -p /usr/local/osquery
ubuntu1504_1  | [+] setting up new brew in /usr/local/osquery
ubuntu1504_1  | Cloning into '/usr/local/osquery'...
ubuntu1504_1  | /usr/local/osquery/.git: Permission denied
ubuntu1504_1  | Makefile:116: recipe for target 'deps' failed
```

Indeed, it doesn't request sudo in `tools/provision/lib.sh`

```
 25   if [[ ! -d "$DEPS/.git" ]]; then
 26     log "setting up new brew in $DEPS"
 27     git clone $BREW_REPO "$DEPS"

```

Maybe I messed up the Dockerfile or something, since I feel like `make deps` should be able to run without root.


```
FROM {{ docker_image }}
MAINTAINER <redacted>

<snip, installing deps with apt-get>

RUN useradd osquery -d /osquery

{% if "centos" in docker_image %}
RUN usermod -aG wheel osquery
# Enable passwordless sudo for users under the "wheel" group
RUN sed -i.bkp -e 's/%wheel\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%wheel ALL=NOPASSWD:ALL/g' /etc/sudoers
{% else %}
RUN adduser osquery sudo
# Enable passwordless sudo for users under the "sudo" group
RUN sed -i.bkp -e 's/%sudo\s\+ALL=(ALL\(:ALL\)\?)\s\+ALL/%sudo ALL=NOPASSWD:ALL/g' /etc/sudoers
{% endif %}

# We're going to do our stuff in here.
WORKDIR /osquery

RUN mkdir /osquery/osquery
RUN chown -R osquery /osquery

USER osquery

# Run the build script which we mount at /entrypoint via docker-compose
CMD <entrypoint script>
```

**Comment by danielpops** [comment]
@defaultnamehere: I ended up having to hack up a bunch of mkdirs and chowns in my dockerfiles to address this. Take a look at the dockerfiles in my repository, https://github.com/danielpops/osquery-build. They should work.

Side Note: I thought I was being smart by adding this RUN command at one point to suppress all the "cannot change locale (en_US.UTF-8): No such file or directory" warnings during `make deps`:
`RUN localedef -i en_US -f UTF-8 en_US.UTF-8`

But it ended up doing more harm than good, and actually causing some of the post-install steps that linuxbrew does to fail. So, don't fall in that trap :)

**Comment by defaultnamehere** [comment]
@danielpops: Thanks! I tried using the additions you made to the xenial Dockerfile, but no luck, still getting permission denied on /usr/local/osquery/.git.

But also, there must be a better way to build osquery without root permissions?

**Comment by danielpops** [comment]
@defaultnamehere Are you sure you've incorporated lines 44-47 of the [xenial dockerfile](https://github.com/danielpops/osquery-build/blob/7f93f02f82bfd3e537da94e0c74c58a7404c4cee/dockerfiles/xenial/Dockerfile#L44-L47) prior to running make deps?

You should not get permission denied on anything inside of /usr/local/osquery/

**Comment by theopolis** [comment]
The `/.cache` work is interesting. That should be controlled by: https://github.com/facebook/osquery/blob/master/tools/provision/lib.sh#L48

I wonder if that ENV variable is no longer valid within Homebrew.

The `./tools/provision.sh` script should handle the ownership and directory creating: https://github.com/facebook/osquery/blob/master/tools/provision.sh#L210

That's worrisome that you have to do it prior to calling `make deps`.

**Comment by theopolis** [comment]
I want to stress again, that building on Lucid is a no-op. On every Linux, when using `make deps` (which is supposed to be optional, but convenient, @defaultnamehere) is using the same compiler and C/zlib runtimes to link. There will be no difference in compatibility for the output if you build on CentOS 7 or Lucid.

**Comment by defaultnamehere** [comment]
@danielpops: Yep, I'm sure I did that stuff.

@theopolis: Interesting, I didn't know it was supposed to be optional. I've been using it so far with plenty of success.

In an effort to help understand this, I'm attaching a scrubbed build log below.
This is the build log of osquery being cloned and built inside several docker machines (a few ubuntu versions, debian8, centos7). Interestingly/terrifyingly, they fail at several different points.

You can see the dockerfiles executing commands in the build log (but let me know if you'd prefer to see the dockerfiles individually).

Build log:
https://gist.github.com/defaultnamehere/ad5d72c4232f9d8782d47147dcf8d8e3

**Comment by theopolis** [comment]
It looks like they all fail at the same place, a permissions issue. Am I reading your build log incorrectly?

**Comment by theopolis** [comment]
Also, for reference, the way we recommend building and the way we test the build is here: http://osquery.readthedocs.io/en/stable/development/building/ using Vagrant. And the CI test that makes sure the source is built from 0-state is here: https://jenkins.osquery.io/job/osqueryMasterDependenciesLinux/

So if you encounter building errors or dependency install errors please check that those two methods are working for you first. And it's most likely the case that the environment / users / etc in the docker environment are slightly different than what the build scripts expect. I would recommend tweaking the build scripts and making sure the vagrant method still works-- if that's the case we can merge your changes into master.

**Comment by theopolis** [comment]
How goes it folks, is there anything we need to fix within the `make deps` logic to make this easier?

**Comment by danielpops** [comment]
I was able to get everything working as exemplified in these lines from my dockerfile (https://github.com/danielpops/osquery-build/blob/7f93f02f82bfd3e537da94e0c74c58a7404c4cee/dockerfiles/lucid/Dockerfile#L54-L74). It actually ended up not being all that wack-a-mole-ish after all. I suppose that the make deps target could do the `sudo mkdir` and `sudo chown $user` commands.

I think we can close the ticket for now.
