### ISSUE TITLE
build: provisioning invokes the system package manager

### ISSUE THREAD

**Issue by orangecms** [facebook/osquery#2813]
Background: I wanted to build osquery from source, and I'm running Arch Linux. There is a package in AUR, the Arch Linux User Repository: https://aur.archlinux.org/packages/osquery-git

Issue: I was very confused when the build process invoked `pacman`, the system package manager. So I grepped through this repo and saw that the provisioning script enforces updates, which should be a user's choice and not invoked without their consent. In my case, updating the whole system is currently undesired, as it would update the kernel and modules and thus the modules of the currently running kernel couldn't load, I would be forced to reboot. I can patch this myself for the local build of course, but wanted to share this concern as it probably affects other users as well.

**Comment by theopolis** [comment]
Hello @orangecms! Take a look at the build documentation here: http://osquery.readthedocs.io/en/stable/development/building/

The `make deps` host provisioning is provided as a convenience to create a deterministic environment complete with all dependencies built from source. This is specifically targeted for our continuous build hosts. If you want to skip the update you can use set the environment variable `SKIP_DISTRO_MAIN=1`. No need to patch. In that wiki page there are several other variables that twist and tweak the dependencies installs. 

It didn't always do that, but folks wanted the `deps` target to be everything and the kitchen sink. :)

**Comment by theopolis** [comment]
It might be worthwhile to split the `make deps` into a:
```
make sysprep
make deps
```

Where `sysprep` handled the calls to the native package manager, system updates, and package installs. Then `deps` handled setting up the reproducible build environment in `/usr/local/osquery`.

**Comment by orangecms** [comment]
Hi @theopolis 🙋,
I see, that makes sense. So that is mentioned in #2253 as I see now. :)

I searched through the issues here, but didn't really know what to look for. Maybe those details could be copied from the issue to the docs? Was the env var renamed ar some point? The docs also mention `RUN_BUILD_DEPS`. Does it makes sense to have a more direct statement when linking the build docs like e.g. including more subsequent words than just "building"? I didn't really notice that there is a link to be honest. 🙃

Thank for your guidance and quick reply!

**Comment by theopolis** [comment]
> Does it make sense to have a more direct statement when linking the build docs like e.g. including more subsequent words than just "building"?

Not sure I'm tracking, are you suggesting some improvements to the wiki? I'm always excited for those! The markdown is kept within [`./docs/wiki`](https://github.com/facebook/osquery/tree/master/docs/wiki). I do my best to make them legible and thoughtful, but I'm not good at it.

**Comment by orangecms** [comment]
Sorry, I just mean the README.md. I created a PR :)

**Comment by theopolis** [comment]
:rocket:
