### ISSUE TITLE
Android + iOS

### ISSUE THREAD

**Issue by reader-man** [facebook/osquery#2815]
Thanks for this great product.
But as you know, Android Tablets + iPads + Mobiles that have andoid + iOS are becoming corporate devices that are used for the enterprise software, for managing & notifications.

So, are Android + iOS included/supported by this product?

Regards.

**Comment by PoppySeedPlehzr** [comment]
Hey @reader-man,

osquery currently doesn't run on iOS and/or Android. We've had this discussion numerous times, and while it may one day be on the roadmap, it currently isn't on our development track for at least the next year. Keep your eyes on our slack and website though, perhaps one day it'll be ported! I'm going to close this issue out, but if you feel it's a bigger discussion that the community should be having, please feel free to open back up :)

**Comment by PoppySeedPlehzr** [comment]
Also, as a follow up, here's the link to our slack where this conversation might be better facilitated: https://osquery-slack.herokuapp.com/
