### ISSUE TITLE
packages: Build single RPM and DEB that installs either upstart or systemd script

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#2816]
Right now `make packages` builds two RPMs and two DEBs, one for upstart/initd and the other for systemd. The only difference between these two RPMs is including either the init script or systemd service.

We should produce a single RPM and single DEB that has logic to detect if the target system is using systemd or initd and installs the appropriate script at install time. We can include both scripts in the RPM and DEB in `/usr/share/osquery/script` and `ln` appropriately or `cp`, whatever is recommended.

**Comment by theopolis** [comment]
Logic that calls the package building: https://github.com/facebook/osquery/blob/master/CMake/Packages.cmake (we'll need to reduce that to 1 call to make a DEB, and 1 call to make a RPM)

Logic that determines what script to include: https://github.com/facebook/osquery/blob/master/tools/deployment/make_linux_package.sh#L160

**Comment by javuto** [comment]
For the DEB package, the fpm parameters will be ```--before-install``` and ```--after-install``` and those will adjust the ```preinst``` and ```postinst``` scripts of the ```.deb``` package.
More info: 
https://github.com/jordansissel/fpm/wiki

For the RPM package, the rpmbuild paramenter will be ```-bp``` to run the ```%prep``` section and ```--clean``` after the installation is finished.
More info: 
http://rpm.org/max-rpm-snapshot/ch-rpm-b-command.html

**Comment by vjon** [comment]
I've got an initial implementation of this running locally.

The current implementation is in line with your suggestion, with both the init scripts & systemd files installed to `/usr/share/osquery/scripts` and with a post-install script copying the appropriate files to the system directories based on running init system & Debian/CentOS distinction.

However, the problem with this implementation is that commands like `apt purge osquery` do not automatically remove the init scripts/systemd files as they should, instead leaving behind the copies/links.

This note is mostly for myself, to make it easier to pick this up again tomorrow/in the near future, but I thought you might be interested to see this as well.

**Comment by theopolis** [comment]
Ah, do the various removal commands have uninstall scripts that the packages could define?

**Comment by vjon** [comment]
Yes, defining another script to be run pre-uninstall is the most straightforward option. Hopefully I can find a more elegant solution, but if not, that's what I'll be implementing.
