### ISSUE TITLE
not compiling because of assignment of const char* to char*

### ISSUE THREAD

**Issue by orangecms** [facebook/osquery#2833]
Issue: When building osquery, my compiler complained about the assignment in https://github.com/facebook/osquery/blob/master/osquery/events/linux/audit.cpp#L385. My system is Arch Linux (amd64).

Solution: Removing the `const` made it work, but I'm not a C/++ developer and couldn't figure out much about it when googling, so I wouldn't just file a PR with that.

**Comment by theopolis** [comment]
Interesting, I don't see any errors/warnings using Clang 3.8.1

And the `libaudit.h` header:
```cpp
$ cat /usr/local/osquery/include/libaudit.h| grep "struct audit_reply" -A 15
struct audit_reply {
	int                      type;
	int                      len;
	struct nlmsghdr         *nlh;
	struct audit_message     msg;

	/* Using a union to compress this structure since only one of
	 * the following should be valid for any packet. */
	union {
	struct audit_status     *status;
	struct audit_rule_data  *ruledata;
	struct audit_login      *login;
	const char              *message;
	struct nlmsgerr         *error;
	struct audit_sig_info   *signal_info;
	struct daemon_conf      *conf;
[...]
```

But it should be fine to assign a `const char *` from a `char *`.
