### ISSUE TITLE
Darwin: Add table for listing Quartz Event Services EventTaps

### ISSUE THREAD

**Issue by evenfowler** [facebook/osquery#2838]
[Quartz Event Services](https://developer.apple.com/reference/coregraphics/1658572-quartz_event_services?language=objc) event taps can be used by malicious applications to log HID events as they are passed to the window server or into a specific login session. It would be useful to have a virtual table that returns information about installed event taps. This can be obtained by calling [CGGetEventTapList](https://developer.apple.com/reference/coregraphics/1455395-cggeteventtaplist?language=objc) which returns [CGEventTapInformation](https://developer.apple.com/reference/coregraphics/cgeventtapinformation?language=objc) structure for installed taps.

Fields from the `CGEventTapInformation` structure that are particularly useful for malware detection are:

```
tapPoint
eventsOfInterest
tappingProcess
processBeingTapped
enabled
```

Taps that are useful for global keylogging typically have a `tapPoint` of `kCGHIDEventTap` and have `eventsOfInterest` of `kCGEventKeyDown` and/or `kCGEventKeyUp`.

**Comment by kcreyts** [comment]
I have much love for this contribution.
