### ISSUE TITLE
Documentation: Add a simple query example

### ISSUE THREAD

**Issue by fabianfrz** [facebook/osquery#2843]
For querying osqueryd it would be great, if there would be some kind of a documentation, which explains how to build a simple client to fetch the information (the problem is that the documentation seems to include only extensions to the server).

From [this](https://github.com/osquery/osquery-python) repository, it is looking like it is using the same thrift interface like the server extensions.

**Comment by theopolis** [comment]
Right, the only way to communicate with an `osqueryd` daemon is by the Thrift UNIX domain socket (extensions socket). The Thrfit specification is: https://github.com/facebook/osquery/blob/master/osquery.thrift and can be used to generate server or client code in any language using the Thrift compiler.

The project doesn't include a user-facing thrift client.

Is there a specific workflow/use case you'd like? Describe how you'd like to communicate to the daemon and maybe we can figure something out.

**Comment by fabianfrz** [comment]
Hi @theopolis ,

it should be possible to request information from a script, do some checks on the output and maybe do some action based on the information. For example check if a specific process exists on a number of hosts so you can collect this information from different operating systems by just sending the SQL query to them. When the information is directly received, it reduces the overhead of spawning child processes, connecting sockets etc. which will result in fewer resources required and faster execution.

**Comment by theopolis** [comment]
Maybe you're thinking of something like: https://github.com/mwielgoszewski/doorman

When the scope of work goes beyond a single host there are tons of engineering and security considerations. For the moment, automation and scripting interfaces beyond the scope of a single host should be other add-on projects. :)

Always happy to brainstorm ideas, but this sort of feature wont show up anytime soon. If there's some immediate action or development you'd like to add pleas let me know and we'll re-open and offer as much help as possible.
