### ISSUE TITLE
make externals not executable on trusty and xenial

### ISSUE THREAD

**Issue by jgshomo** [facebook/osquery#2844]
I attempted to build example_extension.cpp by placing it in the externals folder in a subfolder named "extension_example" (I know this code is compiled under examples but I was just doing this to test building externals). The file was successfully compiled using the "make externals" command but when I attempted to execute the compiled extension I received the following error:

_./build/trusty/external/external_extension_example.ext: /usr/local/osquery/legacy/lib/libc.so.6: version `GLIBC_2.14' not found (required by /lib/x86_64-linux-gnu/libgcc_s.so.1)_

This occurred using a fresh install of both trusty and xenial. The version compiled under the examples folder executes fine.

**Comment by theopolis** [comment]
Ah, thanks for pointing out that linking problem. We can fix that.
