### ISSUE TITLE
Documentation Defect: on_disk -1 vs 0

### ISSUE THREAD

**Issue by zbuc** [facebook/osquery#2849]
Various pieces of documentation say that `on_disk = 0` is the correct way to check for processes whose associated binary is no longer on disk, however `on_disk = -1` seems to be the correct check.

See documentation at:

https://code.facebook.com/posts/844436395567983/introducing-osquery/
https://osquery.io/community/queries/
https://github.com/facebook/osquery

Test:

```
$ cat removes_self.c
#include <stdio.h>
#include <unistd.h>

int main(int argc, char* argv[]) {
    printf("Removing %s\n", argv[0]);

    printf("Result: %d\n", unlink(argv[0]));

    printf("Press ctrl-c to end.\n");

    while (1) {
    }
}

$ ./removes_self
Removing ./removes_self
Result: 0
Press ctrl-c to end.


# other shell
$ osqueryi
osquery - being built, with love, at Facebook
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Using a virtual database. Need help, type '.help'
osquery> select * from processes where on_disk = 0;
osquery> SELECT pid, cmdline, on_disk FROM processes WHERE on_disk <> 1;
+------+----------------+---------+
| pid  | cmdline        | on_disk |
+------+----------------+---------+
| 2008 | ./removes_self | -1      |
+------+----------------+---------+
```

**Comment by theopolis** [comment]
The documentation is correct (or at least the intended correct).

The `-1` value means osquery encountered an error while checking if the process's associated binary still exists. Here're my results:
```
$ osqueryi "select name, cmdline, path, pid, on_disk from processes where on_disk = 0"
+-------+---------+-------------------------------+------+---------+
| name  | cmdline | path                          | pid  | on_disk |
+-------+---------+-------------------------------+------+---------+
| a.out | ./a.out | /home/teddy/git/osquery/a.out | 4833 | 0       |
+-------+---------+-------------------------------+------+---------+
$ osqueryi --version
osqueryi version 2.1.2
```

Inspecting a bit more:
```
ls -la /proc/4833/exe
lrwxrwxrwx 1 teddy teddy 0 Dec 10 17:06 /proc/4833/exe -> /home/teddy/git/osquery/a.out (deleted)
```

On caveat is if you execute the "process that deletes itself" as a user in which the `osqueryi` executor cannot inspect you'll see:
```
$ sudo ./a.out
^Z
$ osqueryi "select name, cmdline, path, pid, on_disk from processes where name = 'a.out'"
+-------+---------+------+------+---------+
| name  | cmdline | path | pid  | on_disk |
+-------+---------+------+------+---------+
| a.out | ./a.out |      | 5018 | -1      |
+-------+---------+------+------+---------+
```

**Comment by zbuc** [comment]
`osqueryd` is running as `root`, and the self-deleting process is running as my local user account -- I don't think it's a permissions issue. Is there any debugging I could do to see what is causing this? We are seeing this across our entire fleet (machines showing `-1` for deleted binaries).

**Comment by theopolis** [comment]
What OS and version? Seems like we need to narrow a bit more to help reproduce.

**Comment by theopolis** [comment]
Ping @zbuc!

**Comment by theopolis** [comment]
That would explain it, my tests were on Linux :)
