### ISSUE TITLE
new table: access to AWS metadata

### ISSUE THREAD

**Issue by jfdive** [facebook/osquery#2852]
AWS hosted virtual machines (EC2's) have access to their AWS specific data via a specific URL that is only accessible from the said machine: http://169.254.168.254/latest/ Various information are available trough this means as described at: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html A great gain for this support is to be able to link osquery generated data with other AWS logs like cloudtrail using the instance-id. An instance-id could be used as query decorator to identify the machine for exemple.

**Comment by godinezj** [comment]
+1

**Comment by smeier00** [comment]
+1

**Comment by mime-frame** [comment]
Need to be careful to not grab /security-credentials
