### ISSUE TITLE
RPM not signed from yum repo

### ISSUE THREAD

**Issue by SubatomicHero** [facebook/osquery#2863]
When attempting to download the rpm from the osquery repo it fails to install with an error stating that the rpm is not signed. I have imported the gpg key and still no luck. Ive have currently installed it with --nogpgcheck but this is not ideal.

I have installed osquery-s3-centos7-repo-1-0.0.noarch but without passing the above argument I cannot install the package via yum.

**Comment by theopolis** [comment]
I was moving our package publishing scripts this weekend and caused some issues.

Here is the errant experience:
```bash
[vagrant@localhost ~]$ sudo rpm -ivh https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm
Retrieving https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm
warning: /var/tmp/rpm-tmp.gY55IP: Header V4 RSA/SHA1 Signature, key ID c9d8b80b: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:osquery-s3-centos7-repo-1-0.0    ################################# [100%]
[vagrant@localhost ~]$ rpm -ql osquery-s3-centos7-repo
/etc/pki/rpm-gpg/OSQUERY-S3-RPM-REPO-GPGKEY
/etc/yum.repos.d/osquery-s3-centos7.repo
[vagrant@localhost ~]$ cat /etc/pki/rpm-gpg/OSQUERY-S3-RPM-REPO-GPGKEY
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1

mQINBFTC4xABEADYBQa4v0v1UI0ikTL1neuaWYOia23TE3R4BprcztGUlzO97cqF
AKkrvs0bze0NcCKxz+5mISRnkwIp4H8JaM3yffhC2Bx3Cc7fPcuyBmZtwMVS9/p/
yjP1LSVatLbBXjymzCyv4DNlyVtVe4UeMpek82PwBzcWPWB1hiNzQUr508vFT01x
c19B4Niswqwm1OjKNVtjFoinX4aU7ZqEo+EvPPthGMxMkfwGnQLpaqAv7PLGQbHz
Dd1fTwWOcOpzcfUP/6n1G7uRIiIdRkya5UDwCfJxYzNhM/7LA4mrd5JAqAUFIZX8
XHUXAysU+09beyBqY678Ary4rIqZCXx2/IrqzFrFGZAPZ8dR2B6aUN03F23stBvJ
+z7Ge4/JUvswqjpJ7P3Ug/tSI9mTcmjaCvIRHJecRKIlvb4OeRQ3pC7BY8f6hPoH
sx/I1ZIcd2mPf4GWwK0o4PjcnyvO3qSV4NDlwMRBqTZfdtxQ5jxEHBhPSrEs6kr2
wTBnk+YC2XGHuZzmJb7HEX0MTvSuihmWXRixEwOpHmP+2fy20v/6yeNsiKV7LtS/
4M7aIy1iwG/etiWtm6k+wMTmiAl017tqVm9kni80wuG5c6jVUw5maNHXvQiRIB7e
NN5fDGQL/1lQjXucbVzagbTyYrv9Agmg89TanC3+UYSS5FQ2qGse8q3lAwARAQAB
tCJvc3F1ZXJ5IChvc3F1ZXJ5KSA8b3NxdWVyeUBmYi5jb20+iQI3BBMBCgAhBQJU
wuMQAhsDBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEJeoDGPJ2LgLEKoQAJ6w
8uKo8+WosiCbKrioPCirGH3RW703AQ+RHb5+XojpbCsuqnqDRI4dZKLhnI60kpLX
Fstz+P3PofYKFJDoSAwb0351StE6iWkCW5lWYIH/VpiYcSl5eg2+G8wd7aAL6huK
vt0NqsknmDa/4MuKFjWKSWjlApI5qu1ZV3h9C3n5qrWuMby5ooGM2VO93yKUu1l2
MVj72OCIWlG0RYfCRdyDtDfHFwtw5aKim8VpbD+w5Ge+Hyd0RCNaUPj7v6jaESjY
cH5zcpHt11j0kzfQ3byKHKuau+Yp8Nqj4fUJB+H9mILpy+AzJkxI+KbZBJ2LQ9rf
itmAy7/KjFG01i3mHMNmmRTNCfJijfP5wC/cAbG7H9QN25MsZ0oqo0NqkVYPjBAe
hY3qu35i+dH/yODy/2pK00UkobXqwsPlQyn/f7AhP7Rm+t8557LAo7GK8SyjN8Kv
zJAspACGogxx5l4fkWMKXoy5sEQyJ55jZAtC4Am3bA/hMgDycoIJ90y/Jl/mSb5k
GEcIUDI/MSWDhG8B0THyj7tGLAbWbx45nDQyrl6T9N5haDkVVIIz1UY+s1q89YXU
OK8afUibFh1drpfHx/sbHqMnAxDsA5HqYYjO5A7teKQTkvXn77zph7C/oi8g29WF
gHczO/S/I3qyGBkU+lsDG0JAVP5gMk4CKBb372svuQINBFTC4xABEAC2XUgq3NEP
4Uiz/3pWeNMvGKP+7JGZgDstgid86OYZ0aKA1vJ+khyJd3xT/dMH0wm7RVgjm9Jn
TEZvIpWpvxoVmxNUoM/DwlavYBJmsuI6jXPJBX+hfNkG9N9VlQBUZAZZIsSMLs4x
qGw1QyMcOf3KmqwmwHAqniyptZqGOt3GEPIUXHL7Cw+BVKy2Jt83z3glLEI9i+iS
dMWefMDmGxXMrTfIUxG39nFDtAV/8Jp3kbtTxduKfG12uy81ST39YjFAZzwavW3E
d5grtwJqpLA6vCK6iR2NMp2NT69HHey+cLlTqcgxPI8ptypPVF2WyvytvVLT7Hm2
Cpz6faACd5JKGWAc7Tb3ZjfG1zmJGcbu/1CFt8gSa/b0ZW1uw1fLAGBmsZq1t0XT
8IlLf1BpajgwxJRMfr+kjW8eoHnI8Gthb3PIip6bOZVTbPp67ybJ8kVPzpBY9ePo
xSF90uuvONpl7uJp7qgHNxtx4tacyzK7CEWiMXjOgmjHDjNTKFC4MNHs++Ube7o4
53CjmiFyrYObLwJPL5Gtir6owbk0jGlz8FIdp8UWMRzUR+7QDZZv10tRQ4FRg3V/
OUwE5clT8mbU66jXD6IK5+tKfYJO4cr4dhpcbyVp5ZGM9yDGmXCvwCg37jFXScGK
3FQZOFxiOeXITFq6ooLVhu0EG7yKCKSSuwARAQABiQIfBBgBCgAJBQJUwuMQAhsM
AAoJEJeoDGPJ2LgL6jkQANDHRpPX5cpfJHt/NsKYKz7ABoFkXtv+xA/AW92C+hNP
3aeo5MOGwHtJ4hQI0s2Z/r9mH8C7IQ2UOlEvl1r5GXUmoMqKbvNkjJo+kWG+3gd8
es/Ua3nuQGGuGb1TzP2ONHlsvkiKz4pTEc8Owrg3dTE065fbYxsgyCOOuMksmEll
s6ypl0nCjAcrTEvx7t/yyqR8p8GUnSXbIx5q0KMKYxiA0mV4jvoWCPkNJxVk9YY4
Ot9bl4QkPK100rEEPaMWvj01DYveZRz1Ab22zBCaj82dMEFtuulg7jNm1DNHKFd2
Z1Dy/rDJBcF59A/1K5HiZERDyGSw6p0nnMjtU+PGGT/7slzRah+IpK6XLl/2/U5k
X3T3k+2M+zT+U+/f6jHpq23ii9lPFLe3qZ3mEuDWNnV6ui6D1oCWpF2DqVLoxjjF
gDJCamKZURaPsA6GRlZhCogHKmpnShezPm4StMS7ECp7+XXMzvVIFTlfkwCfDkMK
qifLlfpRxyhQkmWdiBe9WP7mO3QIOLGzSFr+CKSWl1QOownASYD7UiQdP06Pceae
Rc7zizaDGqJKw/uiXwcq0ExiiIVdyC4PZ6nh/yISNqQDa308u0qkDxycNVHgjYSv
gaS/aDkkb7zrq/37KTGwlMHFgVNgnRw3LB0zHRw/1+FDlRCfhEedS4rsUS8EvZHm
=4n44
-----END PGP PUBLIC KEY BLOCK-----
[vagrant@localhost ~]$ cat /etc/yum.repos.d/osquery-s3-centos7.repo
[osquery-s3-centos7-repo]
name=name=osquery CentOS 7 RPM repository - $basearch
baseurl=https://s3.amazonaws.com/osquery-packages/centos7/$basearch/
enabled=1
gpgkey = file:///etc/pki/rpm-gpg/OSQUERY-S3-RPM-REPO-GPGKEY
gpgcheck=1
```

```bash
[vagrant@localhost repo]$ sudo yum install osquery
Loaded plugins: fastestmirror
Determining fastest mirrors
 * base: repo1.sea.innoscale.net
 * extras: mirror.sjc02.svwh.net
 * updates: centos.chicago.waneq.com
base/7/x86_64/primary_db                                                                                                                                                                                                                                    | 5.6 MB  00:00:00     
Resolving Dependencies
--> Running transaction check
---> Package osquery.x86_64 0:2.1.2-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved
[...]
Package osquery-2.1.2-1.el7.x86-64.rpm is not signed
```

But if you pull down the package as published/linked:
```
[vagrant@localhost ~]$ wget https://s3.amazonaws.com/osquery-packages/centos7/osquery-2.1.2-1.el7.x86_64.rpm
[vagrant@localhost ~]$ rpm -qvip ./osquery-2.1.2-1.el7.x86_64.rpm 
warning: ./osquery-2.1.2-1.el7.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID c9d8b80b: NOKEY
Name        : osquery
Version     : 2.1.2
Release     : 1.el7
Architecture: x86_64
Install Date: (not installed)
Group       : default
Size        : 36616758
License     : BSD
Signature   : RSA/SHA256, Fri 04 Nov 2016 11:10:08 PM UTC, Key ID 97a80c63c9d8b80b
Source RPM  : osquery-2.1.2-1.el7.src.rpm
Build Date  : Fri 04 Nov 2016 09:38:39 PM UTC
Build Host  : centos7
Relocations : / 
Packager    : osquery@osquery.io
Vendor      : Facebook
URL         : https://osquery.io
Summary     : osquery is an operating system instrumentation toolchain.
Description :
osquery is an operating system instrumentation toolchain.
[vagrant@localhost ~]$ sudo rpm --import /etc/pki/rpm-gpg/OSQUERY-S3-RPM-REPO-GPGKEY 
[vagrant@localhost ~]$ rpm -K ./osquery-2.1.2-1.el7.x86_64.rpm 
./osquery-2.1.2-1.el7.x86_64.rpm: rsa sha1 (md5) pgp md5 OK
```

The issue is the yum repo is serving:
```
https://s3.amazonaws.com/osquery-packages/centos7/x86_64/osquery-2.1.2-1.el7.x86-64.rpm
```
Note the `x86-64` vs `x86_64`. This was caused by a poorly constructed regular expression used to rename packages with their version, revision, and architecture. We use a single expression for all platforms: darwin, debian, redhat.

I fixed this and re-synced our repos.

**Comment by theopolis** [comment]
@SubatomicHero, do you mind checking to see if this is fixed?

I was using a new `vagrant up centos7.1` (from osquery's `./Vagrantfile`) to test, seems OK from this end.

**Comment by SubatomicHero** [comment]
`rpm -ivh https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm
Retrieving https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm
warning: /var/tmp/rpm-tmp.msSDSC: Header V4 RSA/SHA1 Signature, key ID c9d8b80b: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
   1:osquery-s3-centos7-repo-1-0.0    ################################# [100%]
[12:43]root@img-basic-centos-72:/home/vagrant# yum list osquery
Loaded plugins: fastestmirror
osquery-s3-centos7-repo                                                                                                 | 3.3 kB  00:00:00
osquery-s3-centos7-repo/x86_64/primary_db                                                                               | 8.3 kB  00:00:00
Loading mirror speeds from cached hostfile
 * epel: epel.check-update.co.uk
Available Packages
osquery.x86_64                                               2.1.2-1.el7                                                osquery-s3-centos7-repo
[12:43]root@img-basic-centos-72:/home/vagrant# yum install osquery
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * epel: epel.check-update.co.uk
Resolving Dependencies
--> Running transaction check
---> Package osquery.x86_64 0:2.1.2-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===============================================================================================================================================
 Package                      Arch                        Version                           Repository                                    Size
===============================================================================================================================================
Installing:
 osquery                      x86_64                      2.1.2-1.el7                       osquery-s3-centos7-repo                       13 M

Transaction Summary
===============================================================================================================================================
Install  1 Package

Total download size: 13 M
Installed size: 35 M
Is this ok [y/d/N]: y
Downloading packages:
Package osquery-2.1.2-1.el7.x86-64.rpm is not signed     90% [==========================================     ] 2.5 MB/s |  12 MB  00:00:00 ETA
osquery-2.1.2-1.el7.x86-64.rpm                                                                                          |  13 MB  00:00:03


Package osquery-2.1.2-1.el7.x86-64.rpm is not signed
[12:43]root@img-basic-centos-72:/home/vagrant# rpm --import .
./             ../            .bash_logout   .bash_profile  .bashrc        .ssh/          .vbox_version
[12:43]root@img-basic-centos-72:/home/vagrant# rpm --import /etc/pki/rpm-gpg/OSQUERY-S3-RPM-REPO-GPGKEY
[12:44]root@img-basic-centos-72:/home/vagrant# yum install osquery
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * epel: epel.check-update.co.uk
Resolving Dependencies
--> Running transaction check
---> Package osquery.x86_64 0:2.1.2-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===============================================================================================================================================
 Package                      Arch                        Version                           Repository                                    Size
===============================================================================================================================================
Installing:
 osquery                      x86_64                      2.1.2-1.el7                       osquery-s3-centos7-repo                       13 M

Transaction Summary
===============================================================================================================================================
Install  1 Package

Total size: 13 M
Installed size: 35 M
Is this ok [y/d/N]: y
Downloading packages:


Package osquery-2.1.2-1.el7.x86-64.rpm is not signed`

Still getting this issue sadly

**Comment by theopolis** [comment]
Ah, so sorry, I don't know why I didn't catch this before. I have a backup S3 job that runs every night. I just shut that down, should be working again!

**Comment by SubatomicHero** [comment]
Yes, last test works as expected. Thanks for the fix :)

**Comment by theopolis** [comment]
Sorry for the trouble! I don't expect any more "redesigns" anytime soon so it should be stable going forward. Working towards saving the release code and signing/publishing logic alongside the repo so everyone can help triage issues and regressions.
