### ISSUE TITLE
1.8.2 deb download checksum changed

### ISSUE THREAD

**Issue by tomelliff** [facebook/osquery#2869]
We rebuild all of our test environments each morning and they all failed to come up this morning as the checksum for osquery 1.8.2 seems to have changed:
```
05:17:28 TASK: [monitoring/osquery | download] ***************************************** 
05:17:47 <app-1.aat1.wxpci.test01.aws.travisperkins.com> REMOTE_MODULE get_url url=https://osquery-packages.s3.amazonaws.com/xenial/osquery-1.8.2.deb dest=/usr/lib/osquery-1.8.2.deb sha256sum=1fec8997c0bd9f6b85731be694360085c029b2bad93fd8f217ba36814dd45fc8
05:17:47 failed: [app-1] => {"failed": true}
05:17:47 msg: The SHA-256 checksum for /usr/lib/osquery-1.8.2.deb did not match 1fec8997c0bd9f6b85731be694360085c029b2bad93fd8f217ba36814dd45fc8; it was 8f7e1971388cc11bba464f19379ca9483631f42b2ef3d1f074d631e133ebf22e.
05:17:55 <app-2.aat1.wxpci.test01.aws.travisperkins.com> REMOTE_MODULE get_url url=https://osquery-packages.s3.amazonaws.com/xenial/osquery-1.8.2.deb dest=/usr/lib/osquery-1.8.2.deb sha256sum=1fec8997c0bd9f6b85731be694360085c029b2bad93fd8f217ba36814dd45fc8
05:17:55 failed: [app-2] => {"failed": true}
05:17:55 msg: The SHA-256 checksum for /usr/lib/osquery-1.8.2.deb did not match 1fec8997c0bd9f6b85731be694360085c029b2bad93fd8f217ba36814dd45fc8; it was 8f7e1971388cc11bba464f19379ca9483631f42b2ef3d1f074d631e133ebf22e.
```

One of my colleagues spotted this and pushed a quick change with the new checksum but I'm reasonably wary that we haven't changed what we were downloading but now have a new checksum. Particularly with a security sensitive piece of software I'd rather not just assume that everything's okay.

Is this at all related to https://github.com/facebook/osquery/issues/2863 ? And can you confirm that the new checksum (`8f7e1971388cc11bba464f19379ca9483631f42b2ef3d1f074d631e133ebf22e`) is correct?

**Comment by theopolis** [comment]
Ah, yes, all of repos were regenerated, the package contents are the same, but they were resigned as they were imported using `freight` so the checksums will change.

I didn't anticipate folks using older packages and thus never made guarantees about their statefullness. Going forward the S3 repo hosting the binaries is now backed by `git`, and the release process is much more automated. I cannot make promises just yet about the stability of those checksums (only the consistency of the signing key), but will work towards that.

I can confirm `8f7e1971388cc11bba464f19379ca9483631f42b2ef3d1f074d631e133ebf22e` for Xenial version 1.8.2 is the reimported package.

**Comment by theopolis** [comment]
Again, sorry for this issue. We have protections to make sure it doesn't happen again!
