### ISSUE TITLE
make sysprep fails on fresh Ubuntu14 Vagrant VM

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#2871]
I created a new Ubuntu14 VM, and found that `make sysprep` fails because git is not installed:

```
vagrant@vagrant-ubuntu-trusty-64:~$ cd /vagrant
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ make sysprep
Problem: cannot find 'git'
make: *** [.setup] Error 1
```

In order to get past this I had to `sudo apt-get update && sudo apt-get -y install git`.

I'm not sure what's going on, because it looks like this is the first thing that `make sysprep` should try to do...

**Comment by theopolis** [comment]
It's perhaps in the `Makefile` logic. There used to be some targets that did not try to `.setup`, perhaps `sysprep` was overlooked by error.
