### ISSUE TITLE
"Could not initialize database" error after worker terminated for exceeding System performance limits

### ISSUE THREAD

**Issue by danielpops** [facebook/osquery#2873]
I have been trying to diagnose an intermittent crash that we've been seeing. I *think* that I've identified a relatively consistent symptom when this happens. Consider the following output:

> I1214 13:21:22.765341 2848825 scheduler.cpp:122] Found results for query: ops_processes
> I1214 13:21:38.773545 2848825 scheduler.cpp:63] Executing scheduled query: ops_interface_reports: SELECT interface, mac, ipackets, opackets, ibytes, obytes FROM interface_details WHERE mac!='';
> I1214 13:21:38.931769 2848825 scheduler.cpp:122] Found results for query: ops_interface_reports
> I1214 13:21:38.933768 2848825 scheduler.cpp:63] Executing scheduled query: ops_suid_bin: SELECT * FROM suid_bin;
> I1214 13:22:43.057114 2848825 scheduler.cpp:63] Executing scheduled query: forensics_etc_hosts: SELECT * FROM etc_hosts;
> I1214 13:23:48.173202 2848825 scheduler.cpp:63] Executing scheduled query: forensics_groups: SELECT gid, groupname FROM groups;
> I1214 13:26:39.298176 2848825 scheduler.cpp:63] Executing scheduled query: ops_logged_in_users: SELECT * FROM logged_in_users;
> I1214 13:26:39.458415 2848825 scheduler.cpp:122] Found results for query: ops_logged_in_users
> I1214 13:26:46.471544 2848825 scheduler.cpp:63] Executing scheduled query: ops_listening_ports: SELECT pid, port, protocol, family, address FROM listening_ports;
> I1214 13:26:47.475261 2848825 scheduler.cpp:122] Found results for query: ops_listening_ports
> I1214 13:27:32.581991 2848825 scheduler.cpp:63] Executing scheduled query: ops_kernel_modules: SELECT * FROM kernel_modules;
> I1214 13:28:43.703991 2848825 scheduler.cpp:63] Executing scheduled query: forensics_users: SELECT uid, gid, username, description FROM users;
> I1214 13:29:38.886261 2848825 scheduler.cpp:63] Executing scheduled query: forensics_open_sockets: SELECT protocol, local_address, remote_address, local_port, remote_port FROM process_open_sockets;
> W1214 13:29:51.863957 2344719 watcher.cpp:241] osqueryd worker (2848543): System performance limits exceeded
> I1214 13:29:51.864984 2344719 watcher.cpp:446] osqueryd watcher (2344717) executing worker (2982568)
> I1214 13:29:51.878283 2982568 init.cpp:361] osquery worker initialized [watcher=2344717]
> I1214 13:29:51.878540 2982568 extensions.cpp:334] Found autoloadable module: /var/lib/osquery/modules/libmodscribe.so
> I1214 13:29:51.881556 2982568 registry.cpp:624] Initialized module: /var/lib/osquery/modules/libmodscribe.so
> I1214 13:29:51.881638 2982568 rocksdb.cpp:187] Opening RocksDB handle: /var/osquery/osquery.db
> E1214 13:29:51.882249 2982568 init.cpp:565] [Ref #1629] osqueryd initialize failed: Could not initialize database

It seems that sometimes when the System performance limits are exceeded, the re-spawned process cannot access the database files/folder. If I restart osquery immediately after without making any other changes, everything appears to be fine. My best guess is that the previously terminated worker has a lingering handle to some of those files that are not cleaned up by the time the new worker is launched. 

Does that theory hold any weight?

Has anyone seen this type of behavior in the past?

**Comment by PoppySeedPlehzr** [comment]
What OS is this on? Would you mind posting your config files?

**Comment by danielpops** [comment]
We run on lucid and trusty. I've observed this on several lucid hosts for sure. Not sure if it's occurred on trusty yet, but I'll try to take note when it happens next.  On that note, this occurred again this morning on another entirely different host (physical host this time):

I1216 11:01:30.953930  5852 query.cpp:72] Scheduled query has been updated: ops_listening_ports
I1216 11:01:31.009714  5852 scheduler.cpp:122] Found results for query: ops_listening_ports
I1216 11:01:59.338037  5852 scheduler.cpp:63] Executing scheduled query: ops_processes: SELECT DISTINCT name, uid, username, cmdline from processes JOIN users using(uid);
I1216 11:01:59.506638  5852 scheduler.cpp:122] Found results for query: ops_processes
I1216 11:02:40.592869  5852 scheduler.cpp:63] Executing scheduled query: forensics_groups: SELECT gid, groupname FROM groups;
I1216 11:02:40.606964  5852 query.cpp:72] Scheduled query has been updated: forensics_groups
I1216 11:03:01.610823  5852 scheduler.cpp:63] Executing scheduled query: forensics_open_sockets: SELECT protocol, local_address, remote_address, local_port, remote_port FROM process_open_sockets;
I1216 11:03:02.096997  5852 query.cpp:72] Scheduled query has been updated: forensics_open_sockets
I1216 11:03:13.574954  5852 scheduler.cpp:122] Found results for query: forensics_open_sockets
W1216 11:03:15.560384  5756 watcher.cpp:241] osqueryd worker (5757): Memory limits exceeded: 152792000
I1216 11:03:15.561043  5756 watcher.cpp:446] osqueryd watcher (5755) executing worker (11466)
I1216 11:03:15.571979 11466 init.cpp:361] osquery worker initialized [watcher=5755]
I1216 11:03:15.572157 11466 extensions.cpp:334] Found autoloadable module: /var/lib/osquery/modules/libmodscribe.so
I1216 11:03:15.574543 11466 registry.cpp:624] Initialized module: /var/lib/osquery/modules/libmodscribe.so
I1216 11:03:15.574589 11466 rocksdb.cpp:187] Opening RocksDB handle: /var/osquery/osquery.db
E1216 11:03:15.575026 11466 init.cpp:565] [Ref #1629] osqueryd initialize failed: Could not initialize database

**Comment by danielpops** [comment]
Here is a copy of my config for reference:

```
{
  "options": {
    "config_plugin": "filesystem",
    "logger_plugin": "scribe",
    "logger_host": "localhost",
    "logger_port": "1463",
    "logger_category": "osquery",
    "logger_status_category": "osquery_status",
    "worker_threads": "4"
  },
  "scheduledQueries": [
    {
      "name": "ops_osquery_info",
      "query": "SELECT * FROM osquery_info JOIN time;",
      "interval": 1800
    },
    {
      "name": "ops_logged_in_users",
      "query": "SELECT * FROM logged_in_users;",
      "interval": 600
    },
    {
      "name": "ops_last",
      "query": "SELECT * FROM last WHERE username!='';",
      "interval": 1800
    },
    {
      "name": "ops_listening_ports",
      "query": "SELECT pid, port, protocol, family, address FROM listening_ports;",
      "interval": 600
    },
    {
      "name": "ops_interface_reports",
      "query": "SELECT interface, mac, ipackets, opackets, ibytes, obytes FROM interface_details WHERE mac!='';",
      "interval": 600
    },
    {
      "name": "ops_crontab",
      "query": "SELECT * FROM crontab;",
      "interval": 600
    },
    {
      "name": "ops_kernel_modules",
      "query": "SELECT * FROM kernel_modules;",
      "interval": 600
    },
    {
      "name": "ops_suid_bin",
      "query": "SELECT * FROM suid_bin;",
      "interval": 600
    },
    {
      "name": "forensics_open_sockets",
      "query": "SELECT protocol, local_address, remote_address, local_port, remote_port FROM process_open_sockets;",
      "interval": 600
    },
    {
      "name": "forensics_etc_hosts",
      "query": "SELECT * FROM etc_hosts;",
      "interval": 600
    },
    {
      "name": "ops_processes",
      "query": "SELECT DISTINCT name, uid, username, cmdline from processes JOIN users using(uid);",
      "interval": 600
    },
    {
      "name": "forensics_users",
      "query": "SELECT uid, gid, username, description FROM users;",
      "interval": 3600
    },
    {
      "name": "forensics_groups",
      "query": "SELECT gid, groupname FROM groups;",
      "interval": 600
    },
  ]
}
```

**Comment by theopolis** [comment]
This may have been caused by a bug in the permissions handling for some tables on OS X and Linux. Prior to version 2.2.0 when a temporary permissions drop was requested the entire process would drop (meaning the RocksDB thread too). If any action were performed by that thread the process might resume in a state where the content could not be read.

The suspect error was `IOError` and `Permission denied`. The fix was dropping permissions for the thread querying the virtual table only.

Your theory does hold, while the watcher does try to reap it's children there's no complete guarantee there are no zombie children when the next worker is spawned: https://github.com/facebook/osquery/blob/master/osquery/core/watcher.cpp#L271

**Comment by danielpops** [comment]
I upgraded to the latest and greatest osquery (2.2.1) and I still observe the same behavior:

```
I1221 11:52:23.727336 24018 scheduler.cpp:63] Executing scheduled query: forensics_open_sockets: SELECT protocol, local_address, remote_address, local_port, remote_port FROM process_open_sockets
;
I1221 11:52:33.384675 24018 scheduler.cpp:122] Found results for query: forensics_open_sockets
W1221 11:52:35.039963 14134 watcher.cpp:251] osqueryd worker (24010): Memory limits exceeded: 135316000
I1221 11:52:35.041129 14134 watcher.cpp:459] osqueryd watcher (14133) executing worker (4884)
I1221 11:52:35.056792  4884 init.cpp:361] osquery worker initialized [watcher=14133]
I1221 11:52:35.057083  4884 extensions.cpp:334] Found autoloadable module: /var/lib/osquery/modules/libmodscribe.so
I1221 11:52:35.060469  4884 registry.cpp:624] Initialized module: /var/lib/osquery/modules/libmodscribe.so
I1221 11:52:35.060535  4884 rocksdb.cpp:195] Opening RocksDB handle: /var/osquery/osquery.db
E1221 11:52:35.060864  4884 init.cpp:565] [Ref #1629] osqueryd initialize failed: Could not initialize database
dpopes@host1:~$ osqueryi --version
osqueryi version 2.2.1
```

I've observed this now across both lucid and trusty flavors.

**Comment by theopolis** [comment]
I had added some refactoring to the worker/watcher to more carefully stop the worker process.

We can add some more logic to the database start-up to wait for the database lock to be available. Previous worker processes could be holding the lock for just a moment longer.

**Comment by theopolis** [comment]
Let me know if this is still an issue and we'll reopen and investigate more. :)
