### ISSUE TITLE
fuzz testing with ALF-fuzz

### ISSUE THREAD

**Issue by kamikaze123** [facebook/osquery#2885]
Is it possible to use all-fuzz on osquery? I can not find a document for fuzz testing... so I am asking...

**Comment by kamikaze123** [comment]
No one pay attention to my question...

**Comment by theopolis** [comment]
Hello @kamikaze123! Just a note, you should generally give folks more than 3 days during the holiday season to answer open source questions. Before assuming no one is paying attention to you, you should look at the project as a whole and see if anyone is active.

To answer your question, there is a basic `make fuzz` (see http://osquery.readthedocs.io/en/stable/development/building/#debug-builds-formatting-and-more) that runs `zzuf` on each virtual table. I am not sure what "all-fuzz" is so I cannot say if it can be used on the osquery codebase. :)

**Comment by kamikaze123** [comment]
@theopolis I am really sorry for delay...

I mean afl-fuzz. Is there a way to use afl-fuzz on osquery?

afl-fuzz: http://lcamtuf.coredump.cx/afl/

**Comment by kamikaze123** [comment]
I could not build from this command... I am not sure why:(( 

CC= afl-clang CXX=afl-clang++ make

**Comment by kamikaze123** [comment]
This is error message

--------------------------------------------------------------------------

[  5%] Building CXX object osquery/extensions/CMakeFiles/osquery_extensions.dir/__/__/generated/gen-cpp/Extension.cpp.o
[  5%] Building CXX object osquery/extensions/CMakeFiles/osquery_extensions.dir/__/__/generated/gen-cpp/ExtensionManager.cpp.o
[  5%] Building CXX object osquery/extensions/CMakeFiles/osquery_extensions.dir/__/__/generated/gen-cpp/osquery_types.cpp.o
[  5%] Building CXX object osquery/extensions/CMakeFiles/osquery_extensions.dir/extensions.cpp.o
afl-cc 2.33b by <lcamtuf@google.com>
In file included from /home/kaze/osquery/osquery/extensions/extensions.cpp:16:
/home/kaze/osquery/include/osquery/core.h:15:10: fatal error: 'shared_mutex' file not found
#include <shared_mutex>
         ^
1 error generated.
make[3]: *** [osquery/extensions/CMakeFiles/osquery_extensions.dir/extensions.cpp.o] エラー 1
make[2]: *** [osquery/extensions/CMakeFiles/osquery_extensions.dir/all] エラー 2
make[1]: *** [all] エラー 2
make: *** [all] エラー 2


------------------------------------------------------------------------

**Comment by theopolis** [comment]
I've never tried using ALF fuzz, there shouldn't be an issue but we do have a fairly complicated build process. The error you're seeing with `shared_mutex` is most likely because the compiler is not using our explicit compiler flags, in this case we need C++14 for that header.

**Comment by kamikaze123** [comment]
@theopolis I was able to resolve this issue by installing gcc-5.x.

----------------------------------------------------

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-5 g++-5

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5

**Comment by kamikaze123** [comment]
Another error.....;((( After hitting 79%...

--------------------------------------------

[ 79%] Building CXX object osquery/CMakeFiles/osquery_tables_tests.dir/tables/events/tests/file_events_tests.cpp.o
[ 79%] Building CXX object osquery/CMakeFiles/osquery_tables_tests.dir/tables/networking/tests/networking_tables_tests.cpp.o
[ 79%] Building CXX object osquery/CMakeFiles/osquery_tables_tests.dir/tables/system/tests/system_tables_tests.cpp.o
[ 79%] Linking CXX executable osquery_tables_tests
afl-cc 2.33b by <lcamtuf@google.com>
CMakeFiles/osquery_tables_tests.dir/main/tests.cpp.o: file not recognized: ファイル形式が認識できません
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [osquery/osquery_tables_tests] エラー 1
make[2]: *** [osquery/CMakeFiles/osquery_tables_tests.dir/all] エラー 2
make[1]: *** [all] エラー 2
make: *** [all] エラー 2

**Comment by kamikaze123** [comment]
This is a file, I can not compile... I uploaded on google drive. 

https://drive.google.com/open?id=0B1vJ77JB-BeobE85dms0RDlPUWc

----------------------------------------------------------------------------------------

afl-fuzz is using special compiler(afl-clang & afl-clang++) for building source code. I think osquery is not made for afl-fuzz....:(((

**Comment by kamikaze123** [comment]
@theopolis  I was able to build osquery with afl-fuzz. I hit many errors because my afl-clang was using wrong clang(/usr/bin/clang).

afl-clang needs to be build with (/usr/local/osquery/clang).
