### ISSUE TITLE
homebrew_packages not returning anything

### ISSUE THREAD

**Issue by kayji** [facebook/osquery#2897]
Hi,

When I run 'select * from homebrew_packages;', there was nothing return. Even though, I have a lot of packages installed through brew. Can you let me know what the issue is?

Thanks!

**Comment by PoppySeedPlehzr** [comment]
Could you be more specific? What version of OS are you running? What is the output of `brew list`? Also, as a more rapid mechanism of triaging issues, you should jump in our slack channel and ask there as there are typically more eyes :) - https://osquery-slack.herokuapp.com/

**Comment by theopolis** [comment]
On my system (just reinstalled Homebrew):
```
osqueryi -A homebrew_packages --verbose
I0110 20:48:24.213852 3209782208 init.cpp:364] osquery initialized [version=2.2.1]
I0110 20:48:24.214228 3209782208 extensions.cpp:275] Could not autoload extensions: Failed reading: /var/osquery/extensions.load
I0110 20:48:24.214316 3209782208 extensions.cpp:288] Could not autoload modules: Failed reading: /var/osquery/modules.load
I0110 20:48:24.216030 3209782208 init.cpp:606] Error reading config: config file does not exist: /var/osquery/osquery.conf
I0110 20:48:24.240357 3209782208 homebrew_packages.cpp:97] Could not list Homebrew packages: No Homebrew Cellar found
```

**Comment by kayji** [comment]
I'm running osquery on Mac OS X 10.12. The output of my 'brew list' is:

`➜  ~ brew list
cmake		glib		oniguruma	pkg-config	yasm
gdb		jq		openssl		srcclr
gettext		libffi		pcre		wget`

And:

`osqueryi -A homebrew_packages --verbose
I0112 10:38:39.515089 2822939584 init.cpp:364] osquery initialized [version=2.2.0]
I0112 10:38:39.515326 2822939584 extensions.cpp:275] Could not autoload extensions: Failed reading: /var/osquery/extensions.load
I0112 10:38:39.515349 2822939584 extensions.cpp:288] Could not autoload modules: Failed reading: /var/osquery/modules.load
I0112 10:38:39.516311 2822939584 init.cpp:606] Error reading config: config file does not exist: /var/osquery/osquery.conf
I0112 10:38:39.535491 2822939584 homebrew_packages.cpp:97] Could not list Homebrew packages: No Homebrew Cellar found`

**Comment by theopolis** [comment]
Right, did you see my fix above? :)
