### ISSUE TITLE
Any way to configure an HTTP proxy for enrollment?

### ISSUE THREAD

**Issue by dannykopping** [facebook/osquery#2900]
I'm struggling to debug an issue with enrollment, and I can't find any option to set an HTTP proxy. osquery doesn't seem to respect my system-defined HTTP proxy either.

Is there a way I can do this?

**Comment by dannykopping** [comment]
I found a tool called ProxyChains which does the trick:
http://proxychains.sourceforge.net/

But it would be nice if osquery respected the `http(s)_proxy` environment vars.

**Comment by theopolis** [comment]
We'd most likely need to implement this within `cpp-netlib`: https://github.com/cpp-netlib/cpp-netlib/issues/50

**Comment by dannykopping** [comment]
Any other tips for inspecting the req/resp? The `--verbose` flag doesn't print this out, IMHO it should

**Comment by fuzzball5000** [comment]
My go-to in this situation would be a virtual machine and MITM proxy: https://zignar.net/2015/12/31/sniffing-vbox-traffic-mitmproxy/

**Comment by dannykopping** [comment]
Using proxychains has helped get around the immediate issue, I'm thinking now more for other devs who encounter this...

**Comment by theopolis** [comment]
If you want to print the HTTP body from TLS requests/responses try `--tls_dump`.

**Comment by dannykopping** [comment]
Ah! Rad, thanks @theopolis!

**Comment by Shazzam123** [comment]
Hi @dannykopping, 

My application uses cpp_netlib (as an http client) an needs to connect to a http proxy but I am having trouble getting this to work with proxychains.

Did you face any issues? If so, how were you able to make this work?  I am using the cpp_netlib example called simple_wget and It seems to hang on the response.

My setup is as follows:
Squid3
proxychains
simple_wget
 
please see output below using normal wget:

```
proxychains wget http://www.google.com.au
ProxyChains-3.1 (http://proxychains.sf.net)
--2017-04-04 20:04:17--  http://www.google.com.au/
Resolving www.google.com.au (www.google.com.au)... 216.58.200.99, 2404:6800:4006:808::2003
Connecting to www.google.com.au (www.google.com.au)|216.58.200.99|:80... |D-chain|-<>-10.10.0.157:3128-<><>-216.58.200.99:80-<><>-OK
connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'index.html.3'

    [ <=>                                                                                                                                                                                                           ] 10,470      --.-K/s   in 0s      

2017-04-04 20:04:18 (76.6 MB/s) - 'index.html.3' saved [10470]
```

please see output below using normal simple_wget:

```
proxychains cpp-netlib/build/example/simple_wget http://www.google.com.au
ProxyChains-3.1 (http://proxychains.sf.net)
Saving to: index.html
|D-chain|-<>-10.10.0.157:3128-<><>-216.58.200.99:80-<><>-OK
```
