### ISSUE TITLE
interface_details table is incomplete on Windows

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#2907]
On Windows, although the `interface_details` is supported, much of the data is not returned. 

For example, consider some output from the `interface_details` table on my laptop:

```
osquery> .all interface_details
                     interface = 12
                           mac =
                          type =
                           mtu =
                        metric =
                      ipackets =
                      opackets =
                        ibytes =
                        obytes =
                       ierrors =
                       oerrors =
                        idrops =
                        odrops =
                   last_change =
                   description = Microsoft Kernel Debug Network Adapter
                  manufacturer = Microsoft
                 connection_id =
             connection_status = 12
                       enabled =
              physical_adapter = 0
                         speed =
                  dhcp_enabled = 1
            dhcp_lease_expires =
           dhcp_lease_obtained =
                   dhcp_server =
                    dns_domain =
dns_domain_suffix_search_order =
                 dns_host_name =
       dns_server_search_order =

                     interface = 20
                           mac = XX:XX:XX:XX:XX:XX
                          type =
                           mtu =
                        metric =
                      ipackets =
                      opackets =
                        ibytes =
                        obytes =
                       ierrors =
                       oerrors =
                        idrops =
                        odrops =
                   last_change =
                   description = Killer Wireless-n/a/ac 1535 Wireless Network Adapter
                  manufacturer = Qualcomm Communications Inc.
                 connection_id = Wi-Fi
             connection_status = 2
                       enabled = 1
              physical_adapter = 1
                         speed =
                  dhcp_enabled = 1
            dhcp_lease_expires = 20170112162759.000000-420
           dhcp_lease_obtained = 20170111162759.000000-420
                   dhcp_server = 192.168.0.1
                    dns_domain = hsd1.co.comcast.net.
dns_domain_suffix_search_order = hsd1.co.comcast.net.
                 dns_host_name = marpaia
       dns_server_search_order = hsd1.co.comcast.net., 75.75.75.75, 75.75.76.76
osquery>
```

Much of the [current implementation](https://github.com/facebook/osquery/blob/57a6a9441eeece53a77b7c07fc79e444808adafe/osquery/tables/networking/windows/interfaces.cpp#L24-L80) uses WMI to retrieve the relevant data.

It seems as though @mtmcgrew is the original author. I wonder if he (or anyone else) has tips on how this data could be extended as I'm not super familiar with the API.

**Comment by PoppySeedPlehzr** [comment]
It seems like this table might just need some API love. I think Windows has numerous APIs that can be tapped to get the extra data, but I believe @mtmcgrew was mostly trying to #movefast and get this table shipped as we had need of it.

If I get some time over the weekend I can possibly look into this, but if anyone decides to beat me to it, the [GetIpStatistics](https://msdn.microsoft.com/en-us/library/aa365959(VS.85).aspx) function would be a great start :)

**Comment by marpaia** [comment]
Cool @PoppySeedPlehzr, I have a few other issues I'm working on as well, so feel free to play around with this is you get some time, otherwise I'll mess with this as well, thanks for the `GetIpStatistics` pointer :)

**Comment by marpaia** [comment]
Do you guys think we can add this to the milestone for 2.3? I'll work on this for that release.

**Comment by theopolis** [comment]
Also: We had discussed offline the ability to have "platform specific" columns for tables. Essentially at runtime, based on the platform, the table schema would label columns `HIDDEN`. This way a `SELECT *` on Linux would not return a large set of empty columns. At the same time column types could still be deduced for data coming from any platform via a daemon running on any other platform.

I think this mostly applies to the inverse of the issue here. The details filled in for Windows are missing on POSIX. ;)

**Comment by marpaia** [comment]
That's cool and makes tons of sense. So you could say that some columns in `interface_details` were POSIX only or something to have variable schemas across platforms? That's neat but it presents some interesting documentation UX concerns.

But in this case, I'd rather actually have the Windows table return the data (at least about interface throughput) since we use that data to determine the primary IP interface (and thus the primary IP address of a host) in @kolide.

**Comment by tehmas** [comment]
I haven't been able to find the right function in Microsoft API documentation. Winpcap library is expected to provide this information but that will obviously add a dependency to the project. I am going to consult an expert on this matter tomorrow.

**Comment by tehmas** [comment]
Yes it turns out that there isn't a specific function available for this. Would have to look into winsock2 and ws2tcpip libraries.

**Comment by muffins** [comment]
#3684 addresses this.
