### ISSUE TITLE
windows: Certificates Virtual Table

### ISSUE THREAD

**Issue by muffins** [facebook/osquery#2922]
We could use a virtual table for the Windows Certificate stores.  There's a great set of MSDN example code [here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa382363(v=vs.85).aspx) but know that most of the MSDN C examples are severely outdated (and sometimes pretty buggy). I'd recommend using the afore mentioned link as example code for structuring API calls and then building out the table with the [drivers](https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/drivers.cpp), [users](https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/users.cpp), or [kernel_version](https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/kernel_info.cpp) tables as an examples. Note that all of these tables leverage the native Windows APIs to get the job done. This is preferred as it is often more robust, and faster, than calling out to the Windows WMI abstraction, however if you checkout the [patches](https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/patches.cpp) or [system info](https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/system_info.cpp) tables you'll see that they're a little more strait forward. If you can find WMI tables that store the Certificate information, this may be a much faster way to implement this table, however I'm not seeing much for WMI classes containing certificate information.

To roll out the table you'll need to drop all of your code in `osquery/tables/system/windows/`, probably called `certificates.cpp`, as well as a matching `.table` spec file in `specs/windows`. There already exists a `specs/darwin/certificates.table` file so you'll want to do the best you can to get matching data for Windows and you can for now just copy the darwn `.table` file to the Windows directory and then rerun cmake to regenerate the Visual Studio projects.

To get started with Windows development, checkout the [Windows 10 Development Guide](https://osquery.readthedocs.io/en/stable/development/windows-provisioning/) and let me know if you have any issues!

**Comment by juju4** [comment]
To feed the need on windows, see also https://github.com/iadgov/certificate-authority-situational-awareness.
Maybe an easier approach would to query through powershell or check corresponding code for `dir cert:\ -rec`

**Comment by muffins** [comment]
This table is getting closer to completion, I haven't had enough time to dedicate to it, but I should have some cycles next week and I'll try to get this closed out: https://github.com/muffins/osquery/tree/win-certificates-table

**Comment by muffins** [comment]
This was addressed by #3498
