### ISSUE TITLE
Question about pip support for installation

### ISSUE THREAD

**Issue by kravivar** [facebook/osquery#2951]
Hello,

I was working on getting some salt osquery modules work on coreos and was wondering if it is safe for me to use pip based installation - https://pypi.python.org/pypi/osquery/1.8.0

Also I notice that the pypi libaries were never updated. Also it would lot helpful if we can get it running with pip installer since its much easy to get it running on multiple operating systems.

Thanks,
Kripa

**Comment by theopolis** [comment]
Hi @kravivar, I just updated the module to 2.2.0: https://pypi.python.org/pypi/osquery it should be safe to use. @jedi22 uses it quite a bit. There might be some edges in documentation so feel free to ask questions here and we'll get issues / questions sorted out ASAP.

**Comment by kravivar** [comment]
@theopolis : I was reading thru the code at https://github.com/osquery/osquery-python/tree/master/osquery ( I may be missed something on that repo ) and did not find any association with osqueryi or osqueryd binary.

Am I safe to assume that I dont need to use the osquery binaries compiled from source code ? and I can straight away use the pypi library in my source code right ?

**Comment by jedi22** [comment]
@kravivar You'll need the library if you're running osqueryi or osqueryd and want to register as an extension as it will handle all the thrift stuff for you.

**Comment by kravivar** [comment]
Great thank you that helps.
