### ISSUE TITLE
Enhance SQLiteUtilTests.test_reset

### ISSUE THREAD

**Issue by vjon** [facebook/osquery#2953]
PR #2896 exposed an edge case whereby this test fails an `EXPECT_NE` evaluation. The failure was detected on Windows, but the error might exist on other platforms.

Refer to Jenkins Build Number 1029 for further details:
https://jenkins.osquery.io/job/osqueryPullRequestWindows/TargetSystem=aws-windows-2016/1029/

**Comment by theopolis** [comment]
The test logic was refactored a bit here: https://github.com/facebook/osquery/commit/691aefe1f8a4e4d8c2e8fefbbd8044d5005d1029 this should cover the flakiness.
