### ISSUE TITLE
augeas table returns no data

### ISSUE THREAD

**Issue by lukehinds** [facebook/osquery#2956]
This might well be from myself being new to osquery, if so apologies for the noise.

I have the current release, deployed on CentOS 7

    osqueryi --version
    osqueryi version 2.2.1

    uname -r
    3.10.0-514.6.1.el7.x86_64

When I attempt to use the augeas table, I cannot get any data to return:

    osquery> select * from augeas where path = '/etc/hosts';
    osquery> select * from augeas where path = '/tmp/test.txt';
    osquery> select * from augeas;
    osquery> 

    # cat /tmp/test.txt
    testconfig = testvalue

Am I missing a pre-step here? 

I have `augtool` installed and I can use it to manage files with `set` commands etc.

**Comment by theopolis** [comment]
Right, we are not yet packaging the lenses with the osquery package. When you build from source the content is placed correctly in `/usr/local/osquery`. We'll need to alter the package build scripts to include and install these.

Requirements:
- Alter logic in the package scripts to install Augeas lenses into `/usr/share/osquery/lenses` on Linux, and `/var/osquery/lenses/` on OS X.
- Alter the table logic to search for lenses in the above locations, based on the platform.
- Include (install) the proper license covering the content.

**Comment by lukehinds** [comment]
Thanks..it works well after building.

```
osquery> select * from augeas where path = '/etc/hosts';
+------------------------------+-------------------------+-----------+------------+
| node                         | value                   | label     | path       |
+------------------------------+-------------------------+-----------+------------+
| /files/etc/hosts             |                         | hosts     | /etc/hosts |
| /files/etc/hosts/1           |                         | 1         | /etc/hosts |
| /files/etc/hosts/2           |                         | 2         | /etc/hosts |
| /files/etc/hosts/1/ipaddr    | 127.0.0.1               | ipaddr    | /etc/hosts |
| /files/etc/hosts/1/canonical | localhost               | canonical | /etc/hosts |
| /files/etc/hosts/1/alias[1]  | localhost.localdomain   | alias     | /etc/hosts |
| /files/etc/hosts/1/alias[2]  | localhost4              | alias     | /etc/hosts |
| /files/etc/hosts/1/alias[3]  | localhost4.localdomain4 | alias     | /etc/hosts |
| /files/etc/hosts/2/ipaddr    | ::1                     | ipaddr    | /etc/hosts |
| /files/etc/hosts/2/canonical | localhost               | canonical | /etc/hosts |
| /files/etc/hosts/2/alias[1]  | localhost.localdomain   | alias     | /etc/hosts |
| /files/etc/hosts/2/alias[2]  | localhost6              | alias     | /etc/hosts |
| /files/etc/hosts/2/alias[3]  | localhost6.localdomain6 | alias     | /etc/hosts |
+------------------------------+-------------------------+-----------+------------+


```
I would have a stab at this, but don't know the build scripts to well..still I will take a look and see what I can figure out.

**Comment by spasam** [comment]
Am seeing the same issue. Can this be fixed by adding a command line argument **augeas_loadpath** and passing that to **aug_init** here: https://github.com/facebook/osquery/blob/master/osquery/tables/system/posix/augeas.cpp#L144

This also solves the problem if the users want to load their own custom lenses!

Another option to bundling the lenses would be to add a rpm/deb dependency on augeas-lenses package.

**Comment by spasam** [comment]
Nevermind, the latest version of augeas available on Ubuntu 16.04 is 1.4.x. Lenses from this package are not parseable by augeas 1.8.x version used in OSQuery.

**Comment by spasam** [comment]
This can be closed

**Comment by lukehinds** [comment]
@spasam I am not following, have @theopolis change recommendations been merged ?

**Comment by spasam** [comment]
@lukehinds Yes. See https://github.com/facebook/osquery/pull/3260

**Comment by lukehinds** [comment]
thanks @spasam
