### ISSUE TITLE
osqueryd fail on macos 10.10.5 (master)

### ISSUE THREAD

**Issue by nigifabio** [facebook/osquery#2988]
hi all,
build it up with all the test passed and package created smoothly 
if installed on macos 10.10.5
i received this error 
any idea how to make it work across versions?

sudo osqueryctl start
dyld: lazy symbol binding failed: Symbol not found: __ZNSt3__118shared_timed_mutexC1Ev
  Referenced from: /usr/local/bin/osqueryd (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libc++.1.dylib

dyld: Symbol not found: __ZNSt3__118shared_timed_mutexC1Ev
  Referenced from: /usr/local/bin/osqueryd (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libc++.1.dylib

/usr/local/bin/osqueryctl: line 19: 81215 Trace/BPT trap: 5       $EXEC --config_path=$REAL_CONFIG_PATH --config_check

**Comment by theopolis** [comment]
Fixed with d1d21cda78d60c1fe7cc2f86fe206522d0134528
