### ISSUE TITLE
aws_util.cpp region of aws are not complete, osquery fail to find kinesis stream

### ISSUE THREAD

**Issue by nigifabio** [facebook/osquery#2999]
hi guys, 
E0214 11:31:53.415592 3014595520 init.cpp:539] Cannot activate aws_kinesis logger plugin: Invalid aws_region specified: ap-south-1

https://github.com/facebook/osquery/blob/d1240f05e59e14e4b1e2cfb5b6fdc4bd98a44543/osquery/logger/plugins/aws_util.cpp

seem to miss the India's aws region

**Comment by nigifabio** [comment]
missing few information:
http://docs.aws.amazon.com/general/latest/gr/rande.html full list of region actually supporting kinesis 
seem to miss 
us-east-2	
ca-central-1	
ap-south-1	
eu-west-1	
eu-west-2

**Comment by theopolis** [comment]
@nigifabio do you mind sending us a pull request with the additions?

**Comment by nigifabio** [comment]
just did, let me know if it's ok
