### ISSUE TITLE
profile.py error: could not find --shell

### ISSUE THREAD

**Issue by iyerabhi07** [facebook/osquery#3002]
Hello,
I am trying to run the profile.py on my config and I am getting this error:
Cannot find --shell: ./build/linux/osquery/osqueryi

I am running this- ./tools/analysis/profile.py --config /etc/osquery/osquery.conf 

Thanks.

**Comment by lhtest429** [comment]
> Hello,
> I am trying to run the profile.py on my config and I am getting this error:
> Cannot find --shell: ./build/linux/osquery/osqueryi
> 
> I am running this- ./tools/analysis/profile.py --config /etc/osquery/osquery.conf
> 
> Thanks.

what happen?i came cross this

**Comment by voxelvortex** [comment]
You can append `-shell /usr/bin/osqueryi` to your command to fix this error, hope that helps
