### ISSUE TITLE
No osquery> prompt in Ubuntu 16.10

### ISSUE THREAD

**Issue by rajat1saxena** [facebook/osquery#3007]
I have made a fresh install of osquery and did some configurations using [this](https://www.digitalocean.com/community/tutorials/how-to-monitor-your-system-security-with-osquery-on-ubuntu-16-04) tutorial.
Now, when I am issuing the command:
`sudo osqueryi --config_path /etc/osquery/osquery.conf --verbose`
it is dropping to a promptless mode and nothing is getting returned.

**Comment by poppyseedplehzr** [comment]
Are you seeing any output from verbose at all? Would you mind attaching a snapshot? Does adding the `--debug` flag give any extra output? Would you also mind attaching your `/etc/osquery/osquery.conf` file?

**Comment by rajat1saxena** [comment]
Here is the snapshot:
![image](https://cloud.githubusercontent.com/assets/821092/23111150/aaecbebe-f74c-11e6-9f10-250007612e61.png)

Here is the content of my config file:
`
{
  "options": {
    "config_plugin": "filesystem",
    "logger_plugin": "filesystem",
    "logger_path": "/var/log/osquery",
    "disable_logging": "false",
    "log_result_events": "true",
    "schedule_splay_percent": "10",
    "pidfile": "/var/osquery/osquery.pidfile",
    "events_expiry": "3600",
    "database_path": "/var/osquery/osquery.db",
    "verbose": "false",
    "worker_threads": "2",
    "enable_monitor": "true",
    "disable_events": "false",
    "disable_audit": "false",
    "audit_allow_config": "true",
    "host_identifier": "hostname",
    "enable_syslog": "true",
    "audit_allow_sockets": "true",
    "schedule_default_interval": "3600" 
  },
  "schedule": {
    "crontab": {
      "query": "SELECT * FROM crontab;",
      "interval": 300
    },
	"system_info": {
      "query": "SELECT hostname, cpu_brand, physical_memory FROM system_info;",
      "interval": 3600
    }
  },
  "decorators": {
    "load": [
      "SELECT uuid AS host_uuid FROM system_info;",
      "SELECT user AS username FROM logged_in_users ORDER BY time DESC LIMIT 1;"
    ]
  },
  "packs": {
     "osquery-monitoring": "/usr/share/osquery/packs/osquery-monitoring.conf",
     "incident-response": "/usr/share/osquery/packs/incident-response.conf",
     "it-compliance": "/usr/share/osquery/packs/it-compliance.conf",
     "vuln-management": "/usr/share/osquery/packs/vuln-management.conf",
	 "fim": "/usr/share/osquery/packs/fim.conf"
  }
}
`

**Comment by theopolis** [comment]
Can you try with version 2.3.2?

```
vagrant@vagrant:/vagrant$ sudo ./build/linux/osquery/osqueryi --verbose --config_path /tmp/config.json 
I0221 02:06:34.188235  2353 init.cpp:380] osquery initialized [version=2.2.3-16-g2e5662a]
I0221 02:06:34.188518  2353 extensions.cpp:292] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I0221 02:06:34.188645  2353 extensions.cpp:305] Could not autoload modules: Failed reading: /etc/osquery/modules.load
I0221 02:06:34.189462  2355 interface.cpp:308] Extension manager service starting: /home/vagrant/.osquery/shell.em
I0221 02:06:34.205950  2353 system.cpp:184] Using UUID 05DBF458-6AE4-4F3B-B1C8-07804BCB219C as host identifier
I0221 02:06:34.206404  2353 smbios_tables.cpp:103] Reading SMBIOS from sysfs DMI node
W0221 02:06:34.310117  2353 syslog.cpp:70] [Ref #1964] Problems encountered creating pipe: Error in mkfifo: No such file or directory
Using a virtual database. Need help, type '.help'
osquery> .all os_version
+--------+---------------------+-------+-------+-------+-------+----------+---------------+----------+
| name   | version             | major | minor | patch | build | platform | platform_like | codename |
+--------+---------------------+-------+-------+-------+-------+----------+---------------+----------+
| Ubuntu | 16.10 (Yakkety Yak) | 16    | 10    |       |       | ubuntu   | debian        | yakkety  |
+--------+---------------------+-------+-------+-------+-------+----------+---------------+----------+
osquery> 
```

Or maybe syslog is not working as a target on your system? Can you also try flipping `enable_syslog` to `false`?

**Comment by fuzzball5000** [comment]
Is passing a config file to osqueryi going to work?

**Comment by rajat1saxena** [comment]
My version is already 2.3.2

![image](https://cloud.githubusercontent.com/assets/821092/23341854/7fa4df38-fc75-11e6-940c-47fb9b0c54bd.png)

**Comment by poppyseedplehzr** [comment]
@rajat1saxena could you possibly provide more details about your host ubuntu env? We're having quite a bit of difficulty repro'ing this issue.

**Comment by theopolis** [comment]
What about `osqueryi --config_path /dev/null`?

**Comment by theopolis** [comment]
I'm assuming we solved this, please re-open and let us know if any more debugging uncovered details. Thanks!
