### ISSUE TITLE
Join query bug

### ISSUE THREAD

**Issue by cooniur** [facebook/osquery#3010]
OS: macOS 10.12.3
osquery version: 2.3.3

# Context
To get a table of process listening ports, including process names, process path and protocol name, one can use the following join query.

```
select l.*, p.name, p.path, t.name from listening_ports l, processes p, etc_protocols t where l.pid = p.pid and l.protocol = t.number;
```

Result:

```
+-------+-------+----------+--------+-----------+------+--------------------------------------------------------------------------------------------------------------------+------+
| pid   | port  | protocol | family | address   | name | path                                                                                                               | name |
+-------+-------+----------+--------+-----------+------+--------------------------------------------------------------------------------------------------------------------+------+
| 114   | 0     | 0        | 0      |           | ip   | /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow                                            | ip   |
| 114   | 0     | 17       | 2      | 0.0.0.0   | udp  | /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow                                            | udp  |
| 654   | 49274 | 6        | 2      | 0.0.0.0   | tcp  | /Users/foo/Applications/dev/IntelliJ IDEA CE.app/Contents/MacOS/idea                                              | tcp  |
| 654   | 65485 | 6        | 2      | 127.0.0.1 | tcp  | /Users/foo/Applications/dev/IntelliJ IDEA CE.app/Contents/MacOS/idea                                              | tcp  |
| 654   | 6943  | 6        | 2      | 127.0.0.1 | tcp  | /Users/foo/Applications/dev/IntelliJ IDEA CE.app/Contents/MacOS/idea                                              | tcp  |
| 654   | 63342 | 6        | 2      | 127.0.0.1 | tcp  | /Users/foo/Applications/dev/IntelliJ IDEA CE.app/Contents/MacOS/idea                                              | tcp  |
+-------+-------+----------+--------+-----------+------+--------------------------------------------------------------------------------------------------------------------+------+
```

# The Bug

However, if protocol name is put as the first column, the protocol's name becomes process's name:

```
select t.name, l.*, p.name, p.path from listening_ports l, processes p, etc_protocols t where l.pid = p.pid and l.protocol = t.number;
```

Result:

```
+-------------------------------+-------+-------+----------+--------+-----------+-------------------------------+--------------------------------------------------------------------------------------------------------------------+
| name                          | pid   | port  | protocol | family | address   | name                          | path                                                                                                               |
+-------------------------------+-------+-------+----------+--------+-----------+-------------------------------+--------------------------------------------------------------------------------------------------------------------+
| loginwindow                   | 114   | 0     | 0        | 0      |           | loginwindow                   | /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow                                            |
| loginwindow                   | 114   | 0     | 17       | 2      | 0.0.0.0   | loginwindow                   | /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow                                            |
| idea                          | 654   | 49274 | 6        | 2      | 0.0.0.0   | idea                          | /Users/foo/Applications/dev/IntelliJ IDEA CE.app/Contents/MacOS/idea                                              |
| idea                          | 654   | 65485 | 6        | 2      | 127.0.0.1 | idea                          | /Users/foo/Applications/dev/IntelliJ IDEA CE.app/Contents/MacOS/idea                                              |
| idea                          | 654   | 6943  | 6        | 2      | 127.0.0.1 | idea                          | /Users/foo/Applications/dev/IntelliJ IDEA CE.app/Contents/MacOS/idea                                              |
| idea                          | 654   | 63342 | 6        | 2      | 127.0.0.1 | idea                          | /Users/foo/Applications/dev/IntelliJ IDEA CE.app/Contents/MacOS/idea                                              |
+-------------------------------+-------+-------+----------+--------+-----------+-------------------------------+--------------------------------------------------------------------------------------------------------------------+
```

This seems a pretty obvious bug, as osquery gets confused about two columns with the same name (column `name` from `processes` and `etc_hosts` tables).

**Comment by cooniur** [comment]
This query works well, though

```select t.alias, l.*, p.name, p.path from listening_ports l, processes p, etc_protocols t where l.pid = p.pid and l.protocol = t.number;```

Result:

```
+-------+-------+-------+----------+--------+-----------+-------------------------------+--------------------------------------------------------------------------------------------------------------------+
| alias | pid   | port  | protocol | family | address   | name                          | path                                                                                                               |
+-------+-------+-------+----------+--------+-----------+-------------------------------+--------------------------------------------------------------------------------------------------------------------+
| IP    | 114   | 0     | 0        | 0      |           | loginwindow                   | /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow                                            |
| UDP   | 114   | 0     | 17       | 2      | 0.0.0.0   | loginwindow                   | /System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow                                            |
| TCP   | 654   | 49274 | 6        | 2      | 0.0.0.0   | idea                          | /Users/foo/Applications/dev/IntelliJ IDEA CE.app/Contents/MacOS/idea                                              |
| TCP   | 654   | 65485 | 6        | 2      | 127.0.0.1 | idea                          | /Users/foo/Applications/dev/IntelliJ IDEA CE.app/Contents/MacOS/idea                                              |
| TCP   | 654   | 6943  | 6        | 2      | 127.0.0.1 | idea                          | /Users/foo/Applications/dev/IntelliJ IDEA CE.app/Contents/MacOS/idea                                              |
| TCP   | 654   | 63342 | 6        | 2      | 127.0.0.1 | idea                          | /Users/foo/Applications/dev/IntelliJ IDEA CE.app/Contents/MacOS/idea                                              |
+-------+-------+-------+----------+--------+-----------+-------------------------------+--------------------------------------------------------------------------------------------------------------------+

```

**Comment by marpaia** [comment]
This has come up before:

- https://github.com/facebook/osquery/issues/1482
- https://github.com/facebook/osquery/issues/1859

Quotes from the above issues:

> It's mostly a benign/cosmetic bug, and yes ideally it should be fixed. But fixing the bug is way more effort and comparatively it's little to no effort to fix the query
> @sharvilshah 

> In both you have duplicate name columns but in the second you see the expected values for each. This is due to the undefined behavior of column conflicts. There is a fixable bug here in the default "pretty print" output but I think it should remain "wont fix". It is almost always recommended to avoid those column conflicts. 
>
> Legit, but benign, bug-- won't be addressed
> @theopolis

**Comment by cooniur** [comment]
Hello @marpaia , thanks for providing the context!

Because osquery is aimed to leverage "the power of a complete SQL language", the argument made by @theopolis that "This is due to the undefined behavior of column conflicts" doesn't truly hold.

In the SQL language, the table name modifier in front of the column name (`select <table_name>.<column_name> from <table_name>`) is well enough to differentiate columns with the same names, and this behavior is expected by users who are familiar with the SQL language.

Certainly fixing the bug could be difficult but I just wanted to point out that it is a real bug and needs some attention.

Thanks!

**Comment by marpaia** [comment]
@cooniur I don't know, in my personal opinion, it doesn't seem like the juice is really worth the squeeze here. Why would you schedule a query that has name queried twice like that? How would you expect an osquery scheduled query log line to look? You should be renaming them as `select p.name as process_name, t.name as etc_protocols_name ...` or whatever you'd like.

Also, it should be noted that this isn't a bug with osquery's SQL implementation or anything, it's just a bug with the pretty printer. If you enter `.mode line` before executing your first query, it will work just fine.

**Comment by cooniur** [comment]
@marpaia If it's a bug in the pretty printer, then firstly the data should be displayed correctly, even if the column name is the same or in conflict. IMHO, this not something like "juice worth squeezing"; it's a bug. One cannot expect the same SQL query would work under line mode, however, not work under pretty mode.

Secondly, having the same column names in the scheduled query log line would be something that the user would worry about, but at least the data should be correctly populated. And populating data correctly is our developers' job, isn't it?

**Comment by marpaia** [comment]
¯\_(ツ)_/¯ I'm just surfacing some history and offering personal commentary.

**Comment by cooniur** [comment]
@marpaia No panic. I'm just sharing my perspective with you and the team behind osquery. It's an awesome tool by the way! :)

**Comment by theopolis** [comment]
Good news: we can definitely (and do) detect column alias collisions post-scan during column population. If you use a query in your schedule that has a collision you will get a WARNING ;)

Bad news: no one has submitted a patch to make the `pretty` printer handle these cleanly. Happy to do a code review if anyone is willing to take on this challenge 💃

**Comment by theopolis** [comment]
Thanks folks for filling in context and additional thoughts/concerns. Unless someone raises their hand to donate time for a fix, I'll consider this a wishlist and close out the issue.
