### ISSUE TITLE
chrome_extensions table does not account for internationalization

### ISSUE THREAD

**Issue by andrewrosezen** [facebook/osquery#3011]
[As mentioned in the docs](https://developer.chrome.com/extensions/i18n), Chrome extensions which provide support for multiple languages do so by providing a `_locales` directory, and then referencing keys within `_locales/<locale>/messages.json` in order to provide user-facing strings that make sense in the user's language of choice.

Currently, when osquery pulls this data from the manifest, it appears to return the raw value of each key.
![image](https://cloud.githubusercontent.com/assets/20543515/23179935/8c035bf6-f824-11e6-9df0-f4d65fc620eb.png)

While I think that there is probably not a perfect solution to finding the right value in the right locale for all users, I think it would be reasonable to look for the referenced values inside of the `default_locale`, which _must_ be present on extensions that use i18n, in order to return a consistent value across a fleet of computers that might have different locales.

**Comment by andrewrosezen** [comment]
Looks like someone has had this idea before, though I think reading the default locale and looking for the actual key's name would be more reliable. Not every extension might have an `en` or `en_US`, necessarily.
https://github.com/brad-anton/extension_finder/blob/master/extension_finder/Browsers/Chrome.py#L84-L101

**Comment by jedi22** [comment]
This change has been merged in. If people need more sophisticated i18n support, they should open a new task.
