### ISSUE TITLE
link in the faq doesn't work

### ISSUE THREAD

**Issue by beamzer** [facebook/osquery#3015]
On https://osquery.io/faq/
the link using-osqueryd points to https://osquery.readthedocs.org/latest/introduction/using-osqueryd/ which produces a 404

**Comment by poppyseedplehzr** [comment]
Interesting, looks like maybe `readthedocs` updated their uri format? The correct link is:
`https://osquery.readthedocs.io/en/latest/introduction/using-osqueryd/`

@theopolis would you mind updating the `https://osquery.io` site to include the `en` specification?

**Comment by poppyseedplehzr** [comment]
Better yet, I think I know where to fix this, gunna check if I have push perms :)

**Comment by poppyseedplehzr** [comment]
Site has been udpated to reflect these changes.

**Comment by beamzer** [comment]
thanks for fixing it ;)
