### ISSUE TITLE
Add log rotation option for osqueryd.results.log

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#302]
Should osqueryd implement a bool to turn on log rotation for `osqueryd.results.log`? The default location is `/var/log/osquery/osqueryd.results.log`. The best solution is a line in logrotate for this folder/file, but we could support an gflags option to turn on manual (as in osqueryd will) rotation. Thoughts?

**Comment by RaulMartinPineda** [comment]
Hi.
Any information on whether osquery already supports log rotation natively?
Best Regards.

**Comment by inhappiness** [comment]
Hi.
Any information on whether osquery already supports log rotation natively?
Best Regards.

**Comment by directionless** [comment]
This was implemented in #7015. See the `--logger_rotate` flag
