### ISSUE TITLE
sql: Investigate method / function to pivot key-values into columns

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#3025]
There are several tables that return `key` and `value` columns. We should investigate additions to SQLite (as extension or functions) that allow easy pivoting. 

Overview of various SQL-databases and pivoting: http://modern-sql.com/use-case/pivot

The example that works with SQLite:
```sql
SELECT _id
     , MAX(CASE WHEN key='name'    THEN value END) name
     , MAX(CASE WHEN key='email'   THEN value END) email
     , MAX(CASE WHEN key='website' THEN value END) website
  FROM some_table
 GROUP BY _id
```

**Comment by theopolis** [comment]
Let's just call this the accepted solution, make sure to `CAST AS TEXT` since SQL will consider the column values as integer types.

**Comment by directionless** [comment]
We do a lot of this internally, and just wrote up https://blog.kolide.com/manipulating-plist-and-registry-output-in-osquery-ad98b067c574 about it
