### ISSUE TITLE
windows doc: Update the provisioning doc to clarify build steps

### ISSUE THREAD

**Issue by poppyseedplehzr** [facebook/osquery#3028]
The [Windows Provisioning doc](https://osquery.readthedocs.io/en/stable/development/windows-provisioning/) could use some clarity on the process of provisioning and building osquery. Make these docs a little more clear on running the scripts out of the root of the repository, and add any more documentation that you think might help make our instructions more explicit and clear.

**Comment by MobeenAshraf** [comment]
I will work on that

**Comment by tehmas** [comment]
@MobeenAshraf I am trying to solve the same issue. The major problem lies in the arrangement of sections of the document. Meet me on slack so that we can fix the problem.

**Comment by MobeenAshraf** [comment]
ok

**Comment by poppyseedplehzr** [comment]
Hey @tehmas, I agree that the overall doc could use a lot more restructuring, but as this has shown up rapidly in the past few days, we'll move ahead with closing @MobeenAshraf's PR, and we can open up another issues concerned with the larger picture restructuring of that doc. Do you have a PR ready for the changes?
