### ISSUE TITLE
Ubuntu Xenial GPG error

### ISSUE THREAD

**Issue by tunkaflux** [facebook/osquery#3031]
Hello,

I receive the following errors while trying to update apt:

```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://osquery-packages.s3.amazonaws.com/xenial xenial Release: The following signatures were invalid: BADSIG 97A80C63C9D8B80B osquery (osquery) <osquery@fb.com>
W: Failed to fetch https://osquery-packages.s3.amazonaws.com/xenial/dists/xenial/Release.gpg  The following signatures were invalid: BADSIG 97A80C63C9D8B80B osquery (osquery) <osquery@fb.com>
W: Some index files failed to download. They have been ignored, or old ones used instead.
```

Any idea on what might be going wrong?

**Comment by jedi22** [comment]
I was able to repro this error, but running this command fixed it:

`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B`

Did you do that but received the error anyway? If this solves the problem please let me know and I'll close out the task.

**Comment by tunkaflux** [comment]
Yes, that's what I did. I've removed the key and added it again and now it seems to work... strange.

I do still get this error when doing apt-get update:
`W: Invalid 'Date' entry in Release file /var/lib/apt/lists/partial/osquery-packages.s3.amazonaws.com_xenial_dists_xenial_Release`

**Comment by jedi22** [comment]
That is strange but I'm glad it's fixed now. That other error is being tracked in this issue https://github.com/facebook/osquery/issues/3000 and we're going to try and solve that as soon as possible.

**Comment by tunkaflux** [comment]
Thanks!
