### ISSUE TITLE
Add config option (CLI flag) to disable status logs

### ISSUE THREAD

**Issue by doe-john** [facebook/osquery#3041]
Hi!

Could you please add config option to disable status logs and leave results. Option `--disable_logging` disables both status and result logs.

Or maybe you can add log rotating for status logs after app restart. Cause we face the same issue as here https://github.com/google/glog/issues/36 .

Thanks in advance.

**Comment by theopolis** [comment]
I know this is not in our `--help` or CLI options list, but we inherit from GLOG: `--minloglevel`, maybe try setting this to `>3` to "disable" statuses.

**Comment by doe-john** [comment]
I've tried `sudo osqueryd --config_path=/var/osquery/osquery.conf --minloglevel=4` but new log files `/var/log/osquery/osqueryd.INFO` are still being created.

**Comment by theopolis** [comment]
Ok, thanks for checking @doe-john, we should write a test for these and either expose that flag or build a similar that does what you need, also a way to disable statuses all together.

**Comment by theopolis** [comment]
The new flag `--logger_min_status=10` will disable all status logs. I updated the Wiki in #3131 to include the new flag too.
