### ISSUE TITLE
windows: Programs virtual table is incomplete - only lists programs with an uninstall registry key

### ISSUE THREAD

**Issue by bp-ross** [facebook/osquery#3043]
Seems like we can make the programs table more robust by adding a couple of locations in rather than just querying the uninstall registry key.

**Comment by Jackbennett** [comment]
Ah well this would explain why `select * programs` doesn't match the wmi `Get-WMI win32_product` list. osquery on my test machine misses for instance: sketchup, 7-zip, inkscape, nodejs. I'm not sure what wmi uses to build the list because it's found Brackets which isn't actually installed (has been previously). Could be a to do with my roaming profile I'm running as.

Just commenting to show interest in this feature. It was one way I wanted to justify deploying the agent. I've found win32_product to be very slow by the way.

**Comment by poppyseedplehzr** [comment]
@Jackbennett Excellent thanks for showing support!  yeah we tend to prefer native Windows APIs if at all possible to avoid the tax on the system that comes with WMI queries. I haven't had time to take this on yet, I would love it if someone jumped on it!

**Comment by jackatbancast** [comment]
@poppyseedplehzr referenced my post but it's likely to be useful posted here as well.

> When querying the installed programs on a Windows 10 installation, I found that the list of programs > reported by osquery was incomplete.
> 
> Examples of some omissions include Inkscape and Spotify.
> 
> The issue appears to be that [osquery queries the registry for uninstallers](https://github.com/facebook/osquery/blob/5671bb720b19816c4973f3ecede9c299bd8c01fb/osquery/tables/system/windows/programs.cpp#L31).
> This works for well-behaved software but requires the software to write to this area specifically.
> 
> After some research`wmic` (e.g. `wmic products get installdate,vendor,installlocation,version /format:json` in `cmd.exe`) appears to perform a query to `HKEY_CLASSES_ROOT\Installer\Products`, which does produce a different list that appears to be more complete.
> 
> A better behaviour may be list the output of a combined query of the Uninstaller section of the registry alongside a query for installer products?

**Comment by jackatbancast** [comment]
For the interface it might make more sense to show entries in duplicate if there are any, as the `distinct` operator can be used to show single programs.
It also makes sense to deduplicate between the lists, however this adds additional complexity.

Thoughts?

**Comment by muffins** [comment]
This should largely be addressed #3945. I did some tests and found that our set of programs retrieved back is a super set of WMI, so it should be the case that we're getting all of the same applications as WMI, as well as applications that WMI isn't finding such as customized installers for local users. If anyone else finds additional applications missing from the osquery data, feel free to shoot me repro instructions and I'll re-open this issue.
