### ISSUE TITLE
boost from osquery-packages returning 403

### ISSUE THREAD

**Issue by basepi** [facebook/osquery#3044]
Hopefully this is the right place for this issue.

When building osquery via linux brew, most of the dependencies pour without issue. But recently the `boost` package has started returning 403:

```
==> Downloading https://osquery-packages.s3.amazonaws.com/bottles/boost-1.63.0_4.x86_64_linux.bottle.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "boost"
Download failed: https://osquery-packages.s3.amazonaws.com/bottles/boost-1.63.0_4.x86_64_linux.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

Building from source works, but it's much slower (sourceforge mirrors), and sometimes the checksums don't match so I have to clean up the failed build manually.

Can someone check into the permissions on https://osquery-packages.s3.amazonaws.com/bottles/boost-1.63.0_4.x86_64_linux.bottle.tar.gz so that the bottle installation will work again?

Thanks!

**Comment by poppyseedplehzr** [comment]
Ah!  Looks like that package doesn't actually exist. Bummer that it's returning a 403 instead of a 404 or the like.

Anywho, looks like we need to get that package built and hosted.

**Comment by basepi** [comment]
Today's build had a new one as well: https://osquery-packages.s3.amazonaws.com/bottles/cpp-netlib-0.12.0_6.x86_64_linux.bottle.tar.gz

Might be worth checking that while you're at it, or I can create a separate issue. :)

**Comment by basepi** [comment]
This is actually on a linux box via linux brew, not OS X. Unless I'm missing something WRT labels.

**Comment by poppyseedplehzr** [comment]
@basepi got it. I'd say let's just leave the cpp-netlib concern in this issue also, we can make sure this doesn't get closed out until both have been generated. Thanks!

**Comment by basepi** [comment]
Thanks, those links are now working great!

**Comment by basepi** [comment]
@poppyseedplehzr Looks like it's failing again:

```
==> Installing boost from osquery/osquery-local
==> Downloading https://osquery-packages.s3.amazonaws.com/bottles/boost-1.63.0_7.x86_64_linux.bottle.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "boost"
Download failed: https://osquery-packages.s3.amazonaws.com/bottles/boost-1.63.0_7.x86_64_linux.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

I'm also seeing the same from `rocksdb`:

```
==> Installing rocksdb from osquery/osquery-local
==> Downloading https://osquery-packages.s3.amazonaws.com/bottles/rocksdb-5.1.4.x86_64_linux.bottle.tar.gz

curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "rocksdb"
Download failed: https://osquery-packages.s3.amazonaws.com/bottles/rocksdb-5.1.4.x86_64_linux.bottle.tar.gz
Warning: Bottle installation failed: building from source.
```

I can create a new issue if you'd like.

**Comment by poppyseedplehzr** [comment]
Ah yeah, that's a newer revision of our boost package, and we recently bumped rocksdb as well without adding the new bottles, but building from source should still at least get one by. I'll re-open this issue and we'll get the bottles added.

**Comment by basepi** [comment]
Yes, I should be clear that the build still works great, it's just slower. :)
