### ISSUE TITLE
[Web site: Brand issue] Windows logo is incorrect, while Apple logo isn't 

### ISSUE THREAD

**Issue by arebee** [facebook/osquery#3047]
##Problem##
On the [https://osquery.io/](https://osquery.io/) home page, there is some stylized version of the Windows Logo from the Windows XP days, while the Apple Logo is consistent with the Apple brand. OsQuery supports a minimum of Windows 8 which introduced a new brand identity https://news.microsoft.com/windows_logo_cyan_rgb_d/

##Fix##
Base it on the official brand guidelines. https://news.microsoft.com/windows_logo_cyan_rgb_d/

http://ncmedia.azureedge.net/ncmedia/2014/10/Windows_logo_Cyan_rgb_D.png

**Comment by poppyseedplehzr** [comment]
Site code has been updated. @theopolis is out for the remainder of this week, but when he gets back next week we can re-gen the site code and it'll be fixed.

Thanks for filing :)
