### ISSUE TITLE
OSQuery failed to build on windows due to error C3861: '__cpuidex': identifier not found 

### ISSUE THREAD

**Issue by KarenHuang2016** [facebook/osquery#3051]
We (the MSVC++ team) do a nightly build of the latest OSQuery sources as a compiler "Real World Code" test. We noticed error C3861 is reported after commit  x65899a "Bumping cpp-netlib and boost libs". This warning is reported form file cpuid.cpp like below:
 D:\OSQuery\src\osquery\tables\system\cpuid.cpp(59): error C3861: '__cpuidex': identifier not found

The definition of "__cpuidex" is in VC header file "intrin.h". Do you foget to include this header file? Could you please take a look at this? Thanks!

**Comment by poppyseedplehzr** [comment]
@KarenHuang2016 thanks so much for the report! Could you help me understand how to repro? Is this building a VS 2017 project? I have a PR incoming with the fix, but I was hoping I could verify it's working somehow :)

**Comment by poppyseedplehzr** [comment]
Hey @KarenHuang2016, @MobeenAshraf actually just reached out to me mentioning he was also experiencing this issue. Is running `tools\make-win64-dev-env.bat` a part of your build process? As we just updated the boost and cpp-netlib libraries, both might need to be updated to resolve this issue?
