### ISSUE TITLE
Virtual table: listing python packages installed on a linux system

### ISSUE THREAD

**Issue by Rubab-Syed** [facebook/osquery#3053]
This virtual table would basically provide information about all the python packages installed in a system.
It would have an implementation file called `python_packages.cpp` under `osquery/tables/system/linux/` directory and a `python_packages.table` spec file under `specs/linux` directory. Following is the column spec that I'm suggesting:  

1. name
2. version
3. virtualenv
4. location/path
5. description
6. author
7. license

I have already started figuring out how to collect this information in C++ and I would really appreciate any kind of feedback on this issue :)

**Comment by theopolis** [comment]
Closed by https://github.com/facebook/osquery/pull/3089
