### ISSUE TITLE
Building osquery on Ubuntu 32bit

### ISSUE THREAD

**Issue by avaneendra** [facebook/osquery#3054]
Hi
 I successfuly built the execcutables and ran on OS X. Now that I am trying to build and run on Ubuntu I am runing into problems. Here is the output from the build logs. Not sure if this is the right forum. Please advise any inputs on this.

Thanks

Hello from osquery setup: glibc-legacy
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-
Last 15 lines from /home/avaneendra/.cache/Homebrew/Logs/glibc-legacy/01.configure:
checking for make... make
checking version of make... 4.1, ok
checking for gnumsgfmt... no
checking for gmsgfmt... no
checking for msgfmt... msgfmt
checking version of msgfmt... 0.19.7, ok
checking for makeinfo... makeinfo
checking version of makeinfo... 6.1, bad
checking for sed... sed
checking version of sed... v. ?.??, bad
checking for autoconf... autoconf
checking whether autoconf works... yes
configure: error: 
*** These critical programs are missing or too old: as ld
*** Check the INSTALL file for required versions.

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
osquery/osquery-local

/usr/local/osquery/Library/Homebrew/utils/github.rb:226:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/osquery/Library/Homebrew/utils/github.rb:184:in `open'
	from /usr/local/osquery/Library/Homebrew/utils/github.rb:233:in `issues_matching'
	from /usr/local/osquery/Library/Homebrew/utils/github.rb:266:in `issues_for_formula'
	from /usr/local/osquery/Library/Homebrew/exceptions.rb:338:in `fetch_issues'
	from /usr/local/osquery/Library/Homebrew/exceptions.rb:334:in `issues'
	from /usr/local/osquery/Library/Homebrew/exceptions.rb:396:in `dump'
	from /usr/local/osquery/Library/Homebrew/brew.rb:133:in `rescue in <main>'
	from /usr/local/osquery/Library/Homebrew/brew.rb:31:in `<main>'
Makefile:123: recipe for target 'deps' failed
make: *** [deps] Error 1
avaneendra@chitti:~/open-src/osquery$ ^C
avaneendra@chitti:~/open-src/osquery$

**Comment by theopolis** [comment]
Seems like you're trying to do something special, please provide more information about how you're trying to build and more details about the OS.

**Comment by avaneendra** [comment]
After researching some more, looks like I am unable to install any packages with brew:
I tried to install "build-essential" package. even then it does not help.

114 configure:5235: $? = 0
115 configure:5224: /usr/bin/gcc-5 -V >&5
116 gcc-5: error: unrecognized command line option '-V'
117 gcc-5: fatal error: no input files
118 compilation terminated.
119 configure:5235: $? = 1
120 configure:5224: /usr/bin/gcc-5 -qversion >&5
121 gcc-5: error: unrecognized command line option '-qversion'
122 gcc-5: fatal error: no input files
123 compilation terminated.


avaneendra@chitti:~/test$ brew install xz
==> Downloading https://fossies.org/linux/misc/xz-5.2.3.tar.gz
Already downloaded: /home/avaneendra/.cache/Homebrew/xz-5.2.3.tar.gz
==> ./configure --disable-silent-rules --prefix=/home/avaneendra/.linuxbrew/Cellar
Last 15 lines from /home/avaneendra/.cache/Homebrew/Logs/xz/01.configure:

Initializing Automake:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether ln -s works... yes
checking for style of include used by make... GNU
checking for gcc... /usr/bin/gcc-5
checking whether the C compiler works... no
configure: error: in `/tmp/xz-20170312-17467-1skxg36/xz-5.2.3':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://github.com/Linuxbrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting

**Comment by theopolis** [comment]
I cannot follow :'(

Are you using the Linux build steps here: http://osquery.readthedocs.io/en/stable/development/building/#building-on-linux?

If so then you should be running `make deps`, which does not compile, configure, or run any build logic, just downloads and untars our prebuilt dependencies. If you're trying compile/build our dependencies from source using the other sections in that guide please explain a bit more.

From the output you included:
- Needing to compile `glibc` or its dependencies is weird.
- Running the `brew` command is not part of osquery's build, we include an inline brew but the command is not made available in your path and is not intended to be run except within our scripts.
- It's still unclear what you're trying to achieve.
- What OS is this? What version? Is it clean?

If you provide a lot more details I can try my best to help. :)

**Comment by avaneendra** [comment]
Thanks for stepping up to help me here. 
Here is the os details. Yes its a clean system. So far I have been trying to build
the source on the native Linux system (Ubuntu 16.04)

avaneendra@chitti:~$ uname -a
Linux chitti 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:59 UTC 2016 i686 i686 i686 GNU/Linux
avaneendra@chitti:~$ 

Linux version 4.4.0-47-generic (buildd@lgw01-19) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.2) ) #68-Ubuntu SMP Wed Oct 26 19:39:59 UTC 2016
avaneendra@chitti:~$ 


I am referring back to the link that explains how to build for linux is using Vagrant commands to create sandbox environment.
"
For each supported distro, we supply vagrant infrastructure for creating native operating system packages. To create a package (e.g. a deb on Ubuntu or an rpm on CentOS), simply spin up a vagrant instance.
"
Does it mean the build will not work on the native Linux OS?. Do I need to get the build only using Vagrant?.

-Avaneendra

**Comment by theopolis** [comment]
You can build on systems outside of Vagrant. Can you try:
```
make depsclean
make sysprep
make
```

**Comment by avaneendra** [comment]
I did try these steps

make sysprep fails with the following:
hecking version of msgfmt... 0.19.7, ok
checking for makeinfo... makeinfo
checking version of makeinfo... 6.1, bad
checking for sed... sed
checking version of sed... v. ?.??, bad
checking for autoconf... autoconf
checking whether autoconf works... yes
configure: error: 
*** These critical programs are missing or too old: as ld
*** Check the INSTALL file for required versions.

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
osquery/osquery-local

/usr/local/osquery/Library/Homebrew/utils/github.rb:226:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/osquery/Library/Homebrew/utils/github.rb:184:in `open'
	from /usr/local/osquery/Library/Homebrew/utils/github.rb:233:in `issues_matching'
	from /usr/local/osquery/Library/Homebrew/utils/github.rb:266:in `issues_for_formula'
	from /usr/local/osquery/Library/Homebrew/exceptions.rb:338:in `fetch_issues'
	from /usr/local/osquery/Library/Homebrew/exceptions.rb:334:in `issues'
	from /usr/local/osquery/Library/Homebrew/exceptions.rb:396:in `dump'
	from /usr/local/osquery/Library/Homebrew/brew.rb:133:in `rescue in <main>'
	from /usr/local/osquery/Library/Homebrew/brew.rb:31:in `<main>'
Makefile:126: recipe for target 'sysprep' failed
make: *** [sysprep] Error 1

**Comment by theopolis** [comment]
There's still not enough information here, maybe we could help if we had the entire output of `make sysprep`?

**Comment by avaneendra** [comment]
avaneendra@chitti:~/Open-Src/osquery$ make sysprep
[+] found ubuntu provision script: /home/avaneendra/Open-Src/osquery/tools/provision/ubuntu.sh
[+] requesting sudo: apt-get -y update
[sudo] password for avaneendra: 
Sorry, try again.
[sudo] password for avaneendra: 
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:3 http://archive.ubuntu.com/ubuntu xenial-backports InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-security InRelease
Reading package lists... Done                     
[+] git is already installed. skipping.
[+] gawk is already installed. skipping.
[+] autotools-dev is already installed. skipping.
[+] autopoint is already installed. skipping.
[+] g++ is already installed. skipping.
[+] ruby is already installed. skipping.
[+] curl is already installed. skipping.
[+] bison is already installed. skipping.
[+] flex is already installed. skipping.
[+] checking for updates to brew
[+] refreshing local tap: osquery-local
[+] installing and updating Homebrew core
HEAD is now at 600e146 leiningen: update 2.6.1 bottle for Linuxbrew.
[+] installing and updating Homebrew dupes
HEAD is now at 83cad3d Merge branch homebrew/master into linuxbrew/master
[+] running unified platform initialization
[+] brew package patchelf is already installed: 0.9
[+] brew package xz is already installed: 5.2.2
[+] brew package zlib is already installed: 1.2.8
[+] brew package binutils is already installed: 2.26
[+] brew package linux-headers is already installed: 3.18.27
[+] brew package gmp installing new version: 6.1.0
==> Downloading https://gmplib.org/download/gmp/gmp-6.1.0.tar.xz
Already downloaded: /usr/local/osquery/.cache/gmp-6.1.0.tar.xz
==> ./configure --prefix=/usr/local/osquery/Cellar/gmp/6.1.0 --enable-cxx
==> make
==> make install
/usr/local/osquery/Cellar/gmp/6.1.0: 20 files, 3.2M, built in 1 minute 11 seconds
[+] brew package mpfr installing new version: 3.1.4
==> Downloading https://mirrors.ocf.berkeley.edu/debian/pool/main/m/mpfr4/mpfr4_

curl: (22) The requested URL returned error: 404 Not Found
Trying a mirror...
==> Downloading https://ftp.gnu.org/gnu/mpfr/mpfr-3.1.4.tar.xz
######################################################################## 100.0%
==> Downloading https://raw.githubusercontent.com/Homebrew/patches/30141937f9d16
######################################################################## 100.0%
==> Patching
==> Applying 3.1.4-patches.diff
patching file PATCHES
patching file VERSION
patching file src/mpfr-impl.h
patching file src/mpfr.h
patching file src/version.c
==> ./configure --prefix=/usr/local/osquery/Cellar/mpfr/3.1.4 --disable-silent-r
==> make
==> make check
==> make install
/usr/local/osquery/Cellar/mpfr/3.1.4: 27 files, 3.6M, built in 1 minute 13 seconds
[+] brew package libmpc installing new version: 1.0.3
==> Downloading http://ftpmirror.gnu.org/mpc/mpc-1.0.3.tar.gz
==> Downloading from http://open-source-box.org/mpc/mpc-1.0.3.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/osquery/Cellar/libmpc/1.0.3 --with-gmp=/usr/
==> make
==> make check
==> make install
/usr/local/osquery/Cellar/libmpc/1.0.3: 13 files, 386.9K, built in 48 seconds
[+] brew package isl installing new version: 0.15
==> Downloading http://isl.gforge.inria.fr/isl-0.15.tar.bz2
######################################################################## 100.0%
==> ./configure --disable-silent-rules --prefix=/usr/local/osquery/Cellar/isl/0.
==> make install
/usr/local/osquery/Cellar/isl/0.15: 72 files, 3.7M, built in 42 seconds
[+] brew package pkg-config installing new version: 0.29.1
==> Downloading https://pkgconfig.freedesktop.org/releases/pkg-config-0.29.1.tar
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/osquery/Cellar/pkg-config/0.29.1 --disable-h
==> make
==> make check
==> make install
/usr/local/osquery/Cellar/pkg-config/0.29.1: 11 files, 654.7K, built in 46 seconds
[+] brew package osquery/osquery-local/glibc installing new version: 2.19
==> Installing glibc from osquery/osquery-local
==> Downloading ftp.gnu.org/gnu/glibc/glibc-2.19.tar.bz2
######################################################################## 100.0%
Hello from osquery setup: glibc
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-
==> make
==> make install
Hello from osquery setup: glibc
==> /usr/local/osquery/Cellar/glibc/2.19/bin/localedef -i en_US -f UTF-8 en_US.U
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local/osquery.

osquery runtime

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/osquery/opt/glibc/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/osquery/opt/glibc/sbin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/osquery/opt/glibc/lib
    CPPFLAGS: -I/usr/local/osquery/opt/glibc/include


==> Summary
/usr/local/osquery/Cellar/glibc/2.19: 1,412 files, 39.5M, built in 4 minutes 5 seconds
[+] brew package osquery/osquery-local/glibc-legacy installing new version: 2.13
==> Installing glibc-legacy from osquery/osquery-local
==> Downloading ftp.gnu.org/gnu/glibc/glibc-2.13.tar.bz2
######################################################################## 100.0%
==> Patching
patching file configure
Hunk #1 succeeded at 5041 (offset -148 lines).
Hunk #2 succeeded at 5104 (offset -148 lines).
patching file math/bits/mathcalls.h
Hello from osquery setup: glibc-legacy
==> ../configure --disable-debug --disable-dependency-tracking --disable-silent-
Last 15 lines from /home/avaneendra/.cache/Homebrew/Logs/glibc-legacy/01.configure:
checking for make... make
checking version of make... 4.1, ok
checking for gnumsgfmt... no
checking for gmsgfmt... no
checking for msgfmt... msgfmt
checking version of msgfmt... 0.19.7, ok
checking for makeinfo... makeinfo
checking version of makeinfo... 6.1, bad
checking for sed... sed
checking version of sed... v. ?.??, bad
checking for autoconf... autoconf
checking whether autoconf works... yes
configure: error: 
*** These critical programs are missing or too old: as ld
*** Check the INSTALL file for required versions.

If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
osquery/osquery-local

/usr/local/osquery/Library/Homebrew/utils/github.rb:226:in `raise_api_error': curl failed!  (GitHub::Error)
curl: (22) The requested URL returned error: 422 Unprocessable Entity
curl: (3) <url> malformed
	from /usr/local/osquery/Library/Homebrew/utils/github.rb:184:in `open'
	from /usr/local/osquery/Library/Homebrew/utils/github.rb:233:in `issues_matching'
	from /usr/local/osquery/Library/Homebrew/utils/github.rb:266:in `issues_for_formula'
	from /usr/local/osquery/Library/Homebrew/exceptions.rb:338:in `fetch_issues'
	from /usr/local/osquery/Library/Homebrew/exceptions.rb:334:in `issues'
	from /usr/local/osquery/Library/Homebrew/exceptions.rb:396:in `dump'
	from /usr/local/osquery/Library/Homebrew/brew.rb:133:in `rescue in <main>'
	from /usr/local/osquery/Library/Homebrew/brew.rb:31:in `<main>'
Makefile:126: recipe for target 'sysprep' failed
make: *** [sysprep] Error 1
avaneendra@chitti:~/Open-Src/osquery$

**Comment by theopolis** [comment]
Interesting, it should not be trying to build `gmp` from source. I hope there are no `OSQUERY*` environment variables set?

**Comment by avaneendra** [comment]
I did not set any. Is there a way I can check if the env variables are set?.

**Comment by poppyseedplehzr** [comment]
You can run either `export` or `env` from your command line and that should dump out set environment variables. Look in there for anything with `OSQUERY` in the name, see anything?

**Comment by dannykopping** [comment]
I'm experiencing the exact same issue on a 32-bit Debian Wheezy VM, no `OSQUERY` env variables set

**Comment by theopolis** [comment]
Ah, that's totally it, we don't support 32-bit Linux with now. We don't have plans to support it either, so if you'd like 32-bit support it'll be a fun project! :)

**Comment by dannykopping** [comment]
Thanks for the clarification @theopolis
