### ISSUE TITLE
os_version table does not report platform on centos6

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#3068]
```
[root@56ca98cffcd3 /]# osqueryi
I0315 00:49:51.305150   380 options.cpp:61] Verbose logging enabled by config option
I0315 00:49:51.306079   380 events.cpp:917] Error registering subscriber: socket_events: Subscriber disabled via configuration
Using a virtual database. Need help, type '.help'
osquery> select * from os_version;
+--------+----------------------------+-------+-------+-------+-------+----------+---------------+----------+
| name   | version                    | major | minor | patch | build | platform | platform_like | codename |
+--------+----------------------------+-------+-------+-------+-------+----------+---------------+----------+
| CentOS | CentOS release 6.8 (Final) | 6     | 8     | 0     |       |          | rhel          |          |
+--------+----------------------------+-------+-------+-------+-------+----------+---------------+----------+
```

I believe this is because the `/etc/redhat-release` file on centos6 does not have the [expected fields](https://github.com/facebook/osquery/blob/master/osquery/tables/system/linux/os_version.cpp#L33-L41). This is what the file looks like:

```
[root@56ca98cffcd3 /]# cat /etc/redhat-release
CentOS release 6.8 (Final)
```

I propose that if at the end of the [genOSVersion](https://github.com/facebook/osquery/blob/master/osquery/tables/system/linux/os_version.cpp#L129) function we don't have any value for `platform`, we do a string comparison on the `name` column to attempt to detect `centos` for CentOS6.

If this seems like an acceptable solution, I will submit a PR.

**Comment by theopolis** [comment]
That sounds reasonable :)
