### ISSUE TITLE
AWS-based plugins do not implement status logging

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#3077]
I cannot remember if the AWS logger plugins:
https://github.com/facebook/osquery/blob/master/osquery/logger/plugins/aws_firehose.h#L29
https://github.com/facebook/osquery/blob/master/osquery/logger/plugins/aws_kinesis.h#L29

did not implement `logStatus` for a reason? Perhaps @zwass remembers?

**Comment by zwass** [comment]
My memory is that @mimeframe and @jacknagz didn't want to have status logs going to those plugins at the time they were implemented. Unfortunately we don't have the Slack archives, so I can't go back to the actual conversations to understand this better.

I know that they want those status logs in the plugins now, and I don't see any reason not to implement that (but it's not something I can take on right now).
