### ISSUE TITLE
The events and syslog_events limits have inconsistencies

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#3078]
Upon testing the enforcement of `syslog_events_max` and `events_max`, log lines and WARNings were created when bypassing a default `--events_max` (1024) for the `syslog` publisher. We need to double check that every use of `_expiry` and `_max` use the publisher-abstracted methods.

**Comment by theopolis** [comment]
Closed by https://github.com/facebook/osquery/pull/3091

**Comment by zwass** [comment]
Hey Ted, I can't find any change in #3091 that seems to be replacing any raw uses of `_expiry` and `_max` with their abstracted methods. Did this turn out to be a non-bug, or is it possible that something is still lurking?
