### ISSUE TITLE
Hash table shouldn't return the hash of an empty file if the file is too big to hash

### ISSUE THREAD

**Issue by mew1033** [facebook/osquery#3080]
I just ran into a problem where I was getting back hashes of certain files where the hash was that of an empty file. I ran md5sum on the file and it was definitely not empty. Turns out it was the read_max and read_user_max flags. I discovered that I can pass in values to those parameters and override the defaults. However, I think that the behavior or returning a hash of nothing when the file can't be hashed doesn't make sense. If I'm not running in verbose mode, I don't get any indication that the file wasn't actually hashed, or that the hashes presented in the output aren't accurate.

**Comment by jedi22** [comment]
osquery now emits a warning if you try to hash a file that is too large, this was merged in https://github.com/facebook/osquery/pull/3090. If you continue to have problems please reopen this task.

**Comment by mew1033** [comment]
@jedi22 Sweet, that should help a lot.
However it still seems like unexpected behavior to report a hash of an empty file as if it was the correct hash. Perhaps instead the hash table should be populated with a custom value of "file_exceeded_read_limit" or something.
