### ISSUE TITLE
No default config files present from CentOS7 RPM

### ISSUE THREAD

**Issue by zcatbear** [facebook/osquery#3093]
I'm running Centos 7.3 and I have installed via the RPM instructions in the readthedocs page
```
$ sudo rpm -ivh https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm
$ sudo yum install osquery
```
The documentation references the configurations in `/etc/osquery/osquery.conf` and `/osquery/osquery/osquery.conf.d/` but neither one is present. 
After doing `rpmrebuild -s osquery.spec osquery` and inspecting the specfile returned, there is no mention of those files being created in the file system. 
```
%files
%dir %attr(0775, root, root) "/etc/osquery"
%attr(0664, root, root) "/etc/sysconfig/osqueryd"
%attr(0775, root, root) "/usr/bin/osqueryctl"
%attr(0775, root, root) "/usr/bin/osqueryd"
%attr(0775, root, root) "/usr/bin/osqueryi"
%attr(0664, root, root) "/usr/lib/systemd/system/osqueryd.service"
%attr(0664, root, root) "/usr/share/osquery/certs/certs.pem"
%attr(0664, root, root) "/usr/share/osquery/osquery.example.conf"
%attr(0664, root, root) "/usr/share/osquery/packs/hardware-monitoring.conf"
%attr(0664, root, root) "/usr/share/osquery/packs/incident-response.conf"
%attr(0664, root, root) "/usr/share/osquery/packs/it-compliance.conf"
%attr(0664, root, root) "/usr/share/osquery/packs/osquery-monitoring.conf"
%attr(0664, root, root) "/usr/share/osquery/packs/osx-attacks.conf"
%attr(0664, root, root) "/usr/share/osquery/packs/vuln-management.conf"
%dir %attr(0775, root, root) "/var/log/osquery"
%dir %attr(0775, root, root) "/var/osquery"
%changelog```

**Comment by jedi22** [comment]
You can create `/etc/osquery/osquery.conf` and it should read from that file by default using the filesystem plugin. Here is an example configuration from our readthedocs.

```json
{
  "options": {
    "host_identifier": "hostname",
    "schedule_splay_percent": 10
  },
  "schedule": {
    "macosx_kextstat": {
      "query": "SELECT * FROM kernel_extensions;",
      "interval": 10
    },
    "foobar": {
      "query": "SELECT foo, bar, pid FROM foobar_table;",
      "interval": 600
    }
  }
}
```

**Comment by poppyseedplehzr** [comment]
We drop the example conf for you. It's listed in your output, it's maybe just not named well enough :) 
```
%attr(0664, root, root) "/usr/share/osquery/osquery.example.conf"
```
This hasn't come up as being problematic before, however it could just be that folks haven't brought it to our attention in the past. If you're interested we'd welcome a PR with some documentation or suggestions, but otherwise I'm going to close this out. Please feel free to re-open if you think it's still an issue or would like to further discuss how we should approach this :)
