### ISSUE TITLE
Implement path and directory LIKEs for extended_attributes table

### ISSUE THREAD

**Issue by mtmcgrew** [facebook/osquery#3099]
LIKEs don't seem to be implemented for the extended_attributes like they are in the file table. 

https://github.com/facebook/osquery/blob/master/osquery/tables/system/darwin/extended_attributes.cpp#L230 vs https://github.com/facebook/osquery/blob/master/osquery/tables/utility/file.cpp#L124

Seems like an easy fix.

**Comment by theopolis** [comment]
Implemented with: https://github.com/facebook/osquery/pull/3541
