### ISSUE TITLE
glog locking issues with nested logging

### ISSUE THREAD

**Issue by yying** [facebook/osquery#3119]
It is possible to trigger a log message within the control flow of flushing a log message. Since `google::LogMessage::Flush` acquires `log_mutex` prior to the invocation of `google::LogMessage::SendToLog`, we need to ensure the code path within this lock to be free of log messages:
* `google::LogMessage::~LogMessage`
   * `google::LogMessage::Flush`
     * `google::LogMessage::SendToLog`
       * `osquery::BufferedLogSink::send`
         * `osquery::RegistryFactory::call`
           * `osquery::RegistryFactory::call`
             * `osquery::RegistryInterface::call`
               * `osquery::LoggerPlugin::call`
                 * `osquery::TLSLoggerPlugin::logStatus`
                   * `osquery::BufferedLogForwarder::logStatus`
                     * `osquery::BufferedLogForwarder::addValueWithCount`
                       * `osquery::setDatabaseValue`

However, this is not the case. In [`osquery::RegistryFactory::call`](https://github.com/facebook/osquery/blob/master/osquery/registry/registry.cpp#L413), an exception within the `try` block will trigger an error message to be logged.

In the current codebase (ignoring #3116), you can trigger this by setting up TLS logging and triggering a `osquery::resetDatabase` via `--schedule_reload 5`. After 5 seconds of running, the reset database operation will trigger the exception within `osquery::RegistryFactory::call` and cause the main worker to `abort()`.

**Comment by theopolis** [comment]
@yying, this was fixed with #3116, right?

**Comment by yying** [comment]
@theopolis Not really, #3116 fixes an issue with locking in the database code. This issue describes a related but different issue with locking within glog. The problem mostly stems with the logging code path and how given an exception within `osquery::RegistryFactory::call`, it is possible to trigger a log message with the handling of an existing log message, which, would cause an `abort` to occur in `google::LogMessage::Flush`.

See https://github.com/facebook/osquery/blob/master/osquery/registry/registry.cpp#L413 and https://github.com/facebook/osquery/blob/master/osquery/registry/registry.cpp#L420

I think one possible solution might be to find a way to defer the logging of the messages until the current logging operation is complete?

**Comment by theopolis** [comment]
Ah, ok, right that would be awesome!
