### ISSUE TITLE
[bug] FIM: no trigger if base directory created after osquery initialization?

### ISSUE THREAD

**Issue by juju4** [facebook/osquery#3122]
Hello,

If in my FIM config, I have a directory, /var/www for example, which doesn't exist,
1- osquery complains at start (/var/log/osquery/osquery.WARNING)
```
Could not add inotify watch on: /var/www
```
2- if directory/subdir/files are created but osquery not restarted: no notification
3- osquery restart. new changes will be reported.

is it an inotify limitation?
Is it the same for complex file paths like /var/www/%%/config/%.xml or /var/www/%%/app/%%/config/%.conf

Thanks

Osquery 2.3.4, Centos7

**Comment by fuzzball5000** [comment]
This is a limitation of inotify, you can't add a watch on a non-existent directory. For paths including wildcards, I believe the behaviour will be the same as for explicitly defined paths, the matching directory structures would be traversed when osquery starts and inotify would attempt to create watches in the same way.

**Comment by juju4** [comment]
Ok. Thanks for the quick confirmation

**Comment by theopolis** [comment]
It's possible to write logic to detect the existence at start time, and periodically scan for those during run time but then expressions like:
`/path/to/dir/*/tmp/*` would not make much sense if intermediate directories existed and you expected all `/path/to/dir/{1,2,3,4}` to be watched as they were created.
