### ISSUE TITLE
Reduce AWS Kinesis/Firehose Plugins serialization/deserialization operations

### ISSUE THREAD

**Issue by yying** [facebook/osquery#3132]
Currently, the path to logging to Kinesis/Firehose requires deserializing JSON to a `ptree`, adding a new parameter, and reserializing the `ptree` back to JSON. Is there a better method to accomplish this with less serialization/deserialization operations?

Continued from https://github.com/facebook/osquery/pull/3115/files/8356d09770645281c5702ec5b6048512afcd5d6e#diff-886ba738b51894c5a543205ffad3c969

**Comment by theopolis** [comment]
The newer buffered logger and refactored AWS plugins should have taken care of this?

**Comment by theopolis** [comment]
@alessandrogario is there still an action item here, or should we close this out?

**Comment by theopolis** [comment]
This was mostly covered in the AWS logger plugin refactoring.
