### ISSUE TITLE
darwin: system_info table on sometimes fails to return a serial number 

### ISSUE THREAD

**Issue by groob** [facebook/osquery#3140]
Started to notice an occasional bug with one of our mac devices.
Osquery version: 2.3.3
MacOS Version 10.12.4
 
Sometimes 
```
select * from system_info
``` 

returns a full table, but others I'm getting 

```
osqueryi --line 'select * from system_info'
          hostname = User-MacBook-Pro.local
              uuid = BA0311B4-121E-5228-812D-7501918FCF24
          cpu_type = x86_64h
       cpu_subtype = Intel x86-64h Haswell
         cpu_brand = Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
cpu_physical_cores = 4
 cpu_logical_cores = 8
   physical_memory = 17179869184
   hardware_vendor =
    hardware_model =
  hardware_version =
     hardware_serial =
     computer_name =
```

I tried to backtrack through the results/status logs. The status log is not very helpful, just shows that the query was successful. 
The result log for this mac mostly fails, but sometimes I see a valid response. 

Running `system_profiler SPHardwareDataType` displays the missing values like serial and machine model.  

I tried to follow the code here:
https://github.com/facebook/osquery/blob/5877c3d464024ef6f33d4b9f0baa8918394ee48c/osquery/tables/system/darwin/system_info.cpp#L84

```
    DarwinSMBIOSParser parser;
    if (!parser.discover()) {
      r["hardware_model"] = "";
      r["hardware_vendor"] = "";
      r["hardware_version"] = "";
      r["hardware_serial"] = "";
```

Which would indicate that if the parser returns false, those values would be set. 
So I tried this little objc script on the mac:

```
import objc
from Foundation import NSBundle

IOKit = NSBundle.bundleWithIdentifier_('com.apple.framework.IOKit')

functions = [("IOServiceMatching", b"@*"),
            ("IOServiceGetMatchingService", b"II@")
            ]

objc.loadBundleFunctions(IOKit, globals(), functions)


matching = IOServiceGetMatchingService(0, IOServiceMatching("AppleSMBIOS"))
print(matching)
``` 

but `IOServiceGetMatchingService` returns a valid value on the mac, which stumped me. 

I have time to look into this issue more, but not completely sure what I can look into to reliably reproduce the issue.

**Comment by theopolis** [comment]
So this is an intermittent issue? If you run your python script in a loop for hours, will the value change?

**Comment by groob** [comment]
good question @theopolis 

I'm seeing the python script succeed on the mac while osquery is continuously failing to get that data. I do realize I missed a whole other section to check with the python script:
https://github.com/facebook/osquery/blob/8fcb3659eeeac56847ee6d26b138b6bddc941a6a/osquery/tables/system/darwin/smbios_tables.cpp#L72-L92

 The failures I'm seeing is less related to how many times I run osquery as to time of day/location of mac. 
If it helps, the user is at a conference with bad wifi right now, which made me think it's somehow related to network issues (I know apple gets the branding name over the network and then caches it). 
I don't think it's a network issue anymore, but I'm also not sure how to reproduce it.
