### ISSUE TITLE
osquery Support Vendors

### ISSUE THREAD

**Issue by DahBizomb** [facebook/osquery#3143]
Hello,

     We are trying to find vendor to help us with an Enterprise Wipe deployment of osquery. I have read the documentation but I don't see a lot of information on Enterprise Deployment, Management, Reporting, etc. Can anyone recommend any vendors that could provide those services? 

Thanks,

Mark

**Comment by zwass** [comment]
Hi Mark,

I'm a Co-founder and Principal Engineer at [Kolide](https://kolide.co), where we are building a supported, Enterprise ready osquery fleet management tool. In this early stage our product mostly helps with the deployment and management of osquery (in addition to enabling live queries across your fleet), but we intend to provide reporting and insights as soon as possible.

Besides Kolide, there are other community-supported tools such as Doorman, Zentral (mostly Mac support). The osquery community is also quite active on the [osquery Slack](https://osquery-slack.herokuapp.com/) if you'd like help there. You can reach me on that Slack with @zwass.

Best,
Zach

**Comment by poppyseedplehzr** [comment]
I'm going to go ahead and close this issue out, but feel free to re-open or open another issue if you have additional questions :) As @zwass mentioned, we have a [slack](https://osquery-slack.herokuapp.com/) that's a great outlet for such things.
