### ISSUE TITLE
Enhancement request - Windows Free disk space

### ISSUE THREAD

**Issue by adent** [facebook/osquery#3152]
Can Windows free disk (partition) space please be made available in osquery. 
One possible way is to use WMI which allows for FreeSpace to be obtained from Win32_LogicalDisk.

**Comment by muffins** [comment]
This task will require building out a virtual table for Windows. One will need to add a new `.table` file containing the table schema, and add in the new implementation code under `osquery/tables/system/windows`. [Here](https://osquery.readthedocs.io/en/stable/development/windows-provisioning/) is a walkthrough on getting started with provisioning a Windows environment, and [here](https://osquery.readthedocs.io/en/stable/development/creating-tables/) is a guide for building out new tables. As the task description mentions, you can very easily make use of the `Win32_LogicalDisk` WMI table to get this data, and [the patches table](https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/patches.cpp) is a great example of a virtual table making use of our WMI subsystem. Please feel free to ping me on Slack, I'm Thor, if you have any questions - Happy Hacking!

**Comment by fmanco** [comment]
Seems this was already implemented by #3818. Closing.
