### ISSUE TITLE
TLSRequestHelper::go(uri, output) documentation references "params"

### ISSUE THREAD

**Issue by tpott** [facebook/osquery#3161]
https://github.com/facebook/osquery/blob/59f0bad67c9e04159619fca37d08d95bb584b077/osquery/remote/utility.h#L162,L169 references "params" but the paramter is for the output, and the function actually creates it's own params variable locally

**Comment by poppyseedplehzr** [comment]
Ah, are you saying that this is likely the documentation that needs updating? Or are you wanting to have an option to pass in the params? I think that this function might've just been a helper function to get off just a quick GET and there's a different utility func you should be using?

**Comment by tpott** [comment]
Just that the function documentation mentions "params", as if they are what gets sent to the server. In reality, this function doesn't have a "params" parameter, and rather has an "output" parameter, which is probably the output from the server.

**Comment by jedi22** [comment]
It looks like it gets sent to the server here: https://github.com/facebook/osquery/blob/7844a8ea1be9bf2f08dda95aa3adbbb16a0113fa/osquery/remote/utility.h#L114
