### ISSUE TITLE
inotify subscriber fails to restart cleanly

### ISSUE THREAD

**Issue by akerl** [facebook/osquery#3162]
Under load, the inotify subscriber restarts itself but fails to cleanly start up again.

Test config:

```
# cat osquery.conf
{
  "options": {
    "schedule_splay_percent": 10
  },
  "schedule": {
    "file_events": {
      "query": "SELECT * FROM file_events;",
      "interval": 5,
      "removed":false
    }
  },
  "file_paths": {
    "configuration": [
      "/etc/%%"
    ]
  },
  "events": {
    "disable_subscribers": ["user_events"]
  }
}

# cat osquery.flags
--disable_audit=false
--audit_allow_config=true
--audit_persist=true
--audit_allow_sockets
--logger_plugin=filesystem
--events_max=100000
--watchdog_memory_limit=350
--events_expiry=1
```

Test daemon command:

```
# osqueryd --flagfile=/etc/osquery/osquery.flags --config_path=/etc/osquery/osquery.conf --pidfile=/var/run/osqueryd.pid --daemonize=false --verbose
```

Test case:

```
# mkdir /etc/testdir
# for i in {1..10000} ; do touch /etc/testdir/testfile$i ; done
```

The result is initially what I'd expect: osqueryd starts trying to eat all the events, and the DB activity spikes to match:

```
I0413 14:57:05.087421 23206 rocksdb.cpp:149] RocksDB: [WARN] [queries] Stalling writes because we have 3 immutable memtables (waiting for flush), max_write_buffer_number is set to 4 rate 1683623
```

Following the log, it tracks from testfile1 up to around ~6200 or so, at which point the daemon output gives this:

```
I0413 14:58:50.788100 23212 inotify.cpp:128] inotify was overflown, attempting to restart handle
I0413 14:58:51.189088 23212 events.cpp:767] Event publisher inotify run loop terminated for reason: Overflow
```

Unfortunately, from this point, the inotify handle never logs another file event.

I'm not sure the best way to ID whether it's failing to restart vs restarting and failing to register the right kernel inotify hooks vs something else. Happy to run more debugging commands to help isolate that.

**Comment by theopolis** [comment]
I tried to address this here: https://github.com/facebook/osquery/pull/3376/files which should be fixed in 2.5.0. I'm not 100% sure it will solve the overflowing (+restart) issue but it's a better attempt at restarting state if anything goes wrong.

If you can reproduce this error condition and don't mind re-testing with 2.5.0, it would be very helpful :)
