### ISSUE TITLE
Install OSQUERY in 32 bit CentOS

### ISSUE THREAD

**Issue by DwijadasDey** [facebook/osquery#3163]
I am facing issue in installing CentOS 7 32 bit using yum. I have used the following method from guidelines to install OSQUERY. While installing through YUM, it gives 403 - Forbidden error.

$ rpm -ivh https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm
Retrieving https://osquery-packages.s3.amazonaws.com/centos7/noarch/osquery-s3-centos7-repo-1-0.0.noarch.rpm
warning: /var/tmp/rpm-tmp.BB953P: Header V4 RSA/SHA1 Signature, key ID c9d8b80b: NOKEY
Preparing...                          ################################# [100%]
Updating / installing...
1:osquery-s3-centos7-repo-1-0.0    ################################# [100%]

$ yum install osquery

https://s3.amazonaws.com/osquery-packages/centos7/i386/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
Trying other mirror.

Dwijadas Dey

**Comment by theopolis** [comment]
We only have build and package support for 64bit Linux.

**Comment by poppyseedplehzr** [comment]
I'm going to go ahead and close this out, but feel free to re-open if you have more questions!  I'd also encourage you to checkout our [slack](https://osquery-slack.herokuapp.com/) for more information.
