### ISSUE TITLE
Table foo_events is event-based but events are disabled

### ISSUE THREAD

**Issue by DwijadasDey** [facebook/osquery#3166]
Hi
    I have enabled/configured syslog logging to true and the syslogs are consumed from the pipe and are written to /var/log/osquery/osqueryd.results.log but when i issue the following query, osquery says events are disabled. In osquery configuration, i have enabled events through "disable_events": "false". Are there anything more to be configured so that syslog_events or process_events table gets filled up ? I am using Ubuntu 16.10.

"options": {
    "config_plugin": "filesystem",
    "logger_plugin": "filesystem",
    "logger_additional_plugin": "syslog",
    "logger_path": "/var/log/osquery",
    "disable_logging": "false",
    "log_result_events": "true",
    "schedule_splay_percent": "10",
    "pidfile": "/var/osquery/osquery.pidfile",
    "events_expiry": "3600",
    "database_path": "/var/osquery/osquery.db",
    "verbose": "true",
    "worker_threads": "2",
    "enable_monitor": "true",
    "disable_events": "false",
    "disable_audit": "false",
    "audit_allow_config": "true",
    "host_identifier": "hostname",
    "enable_syslog": "true",
    "audit_allow_sockets": "true",
    "schedule_default_interval": "3600"
  },
..........................
..........................

osquery> select * from syslog_events;
W0415 15:29:58.882632  6692 virtual_table.cpp:513] Table syslog_events is event-based but events are disabled

osquery> SELECT * FROM process_events;
W0415 15:26:18.724334  6692 virtual_table.cpp:513] Table process_events is event-based but events are disabled

Thanks

**Comment by poppyseedplehzr** [comment]
Looks like you're running those commands from the `osqueryi` shell. When you launched `osqueryi`, did you pass the path to the configuration? `osqueryi --config_path=/path/to/osquery.conf`?

**Comment by DwijadasDey** [comment]
Hi
    Nick
              I have started osquery in daemon mode which will read the configuration file in /etc/osquery/osquery.conf and then started the osqueryi shell. Also I have tried with non daemon mode by stopping it and executed the following command from the terminal -

$ osqueryi --config_path=/etc/osquery/osquery.conf

The result is same-
W0415 18:10:50.713146  8327 virtual_table.cpp:513] Table file_events is event-based but events are disabled

**Comment by poppyseedplehzr** [comment]
@DwijadasDey if you're still getting that warning that means the configuration file you're pointing at doesn't have `--disable_events=false`. Try `osqueryi --config_path=/etc/osquery/osquery.conf --disable_events=false`? For troubleshooting FIM configurations, I like to make an `osquery_fim.flags` file that contains a configuration similar to what's detailed [here](https://osquery.readthedocs.io/en/stable/deployment/file-integrity-monitoring/), and then run `osqueryi --flagfile=/path/to/osquery_fim.flags`. I'd also encourage you to jump into our [slack](https://osquery-slack.herokuapp.com/) where we have a #fim channel which might elicit faster responses in setting up your configuration :)

**Comment by DwijadasDey** [comment]
@poppyseedplehzr The configuration mistakes on my part is that, default daemon script for osquery points PID location to /var/run/osquery, i changed it to /var/osquery/osquery.pidfile and the error goes away. 
Now i am not using daemon script, instead fall back to osqueryi --config_path=/etc/osquery/osquery.conf but there seems to be an error in the setup-

> Event publisher failed setup: audit: Could not set audit PID

The audit daemon is running correctly . Just need to find why it could not set it up. Also the result from the query select * from syslog; always blank.

I have already posted the issue in the #fim channel.

Thanks

**Comment by theopolis** [comment]
We had resolved this in Slack. The system cannot run auditd and osquery (with audit support enabled) simultaneously.
