### ISSUE TITLE
Node.js Driver

### ISSUE THREAD

**Issue by carloscarcamo** [facebook/osquery#317]
Would be awesome if you provide a Node.js driver, I would like to build a Node.js app on top of osquery :)

**Comment by marpaia** [comment]
This is being tracked in #623.

**Comment by Downchuck** [comment]
seems incomplete: https://github.com/sidorares/osquery-node

**Comment by marpaia** [comment]
We (the osquery team at Facebook) don't support the node driver, so we can't control how complete it may or may not be :/

**Comment by Downchuck** [comment]
Pull Requests welcome ;-)

**Comment by marpaia** [comment]
![image](https://cloud.githubusercontent.com/assets/927168/9478657/ef8e5e14-4b2d-11e5-8999-d276d8f74b67.png)

**Comment by sidorares** [comment]
@Downchuck I'm keen to add new features, let me know what is your priorities

**Comment by Downchuck** [comment]
Just looking to see "DOUBLE" working -- I have not cross-tested, to see if Python and Node can both use "DOUBLE" types. Everyone loves TEXT, of course.
