### ISSUE TITLE
osquery > 2.1 crashes on Win10

### ISSUE THREAD

**Issue by doe-john** [facebook/osquery#3171]
Hi.

If you start osqueryi or osqueryd (version > 2.1) as admin user on Win 10 with non-US locale it will crash on selecting any data from processes table. On Win7 it works fine, on Win10 as regular user, or on Win10 with US locale, or osquery v.2.1 also works good. But e.g. osqueryi 2.4.0-13-g352b43a on Win10ru gives you:

`Exception thrown at 0x00007FF80E973C58 in osqueryi.exe: Microsoft C++ exception: std::range_error at memory location 0x000000D079D0E210`

in function `wide_string from_bytes(const char *_First, const char *_Last)` (`// convert byte sequence [_First, _Last) to a wide string`). while it's trying to handle the word "Администраторы" it throws an exception `_THROW_NCEE(range_error, "bad conversion")`

**Comment by poppyseedplehzr** [comment]
Hey @doe-john, I actually just landed https://github.com/facebook/osquery/pull/3170 which should address this issue. Give it a shot on master and it should be querying correctly.  I'm going to close this issue out, but feel free to re-open or create a new one if you're finding the issue persists!

**Comment by doe-john** [comment]
Thx! It works now!
