### ISSUE TITLE
Error when loading config values from CLI vs config file

### ISSUE THREAD

**Issue by adamenger** [facebook/osquery#3172]
Currently we (@bt3gl and @adamenger) are trying to load OSquery in a development environment by passing a local config using `--config_path` argument. However, what we're seeing is that OSQuery will load and boot with default values instead of reading from the values supplied in `osquery.conf` locally. We've verified this by running osquery like so:

**Our command**

```
✗ /usr/local/bin/osqueryd --config_path config/osquery.conf
W0418 14:36:06.858420 2044129280 system.cpp:291] Unable to remove the osqueryd pidfile
E0418 14:36:06.858678 2044129280 init.cpp:421] osqueryd initialize failed: Could not create file: /var/osquery/osqueryd.pidfile
```

**Our config**

```
{
  "options": {
    "config_plugin": "filesystem",
    "logger_plugin": "filesystem",
    "logger_path": "tmp/log/osquery",
    "pidfile": "tmp/osquery.pidfile",
    "events_expiry": "3600",
    "database_path": "tmp/osquery.db",
    "schedule_splay_percent": 10,
    "host_identifier": "hostname",
    "verbose": "false"
  },
  "decorators": {
    "load": [
      "SELECT uuid AS host_uuid FROM system_info;",
      "SELECT user AS username FROM logged_in_users ORDER BY time DESC LIMIT 1;"
    ]
  },
  "packs": {
    "*": "./packs/osx/*"
  }
}
```
We can get OSQuery running properly by supplying the config values on the command line directly like so:

``` 
osquery: /usr/local/bin/osqueryd --flagfile tmp/osquery.flags --pidfile tmp/osquery.pid --database_path tmp/os
```

Can you let us know if we're doing something wrong here or if this smells like a bug?

Cheers,

**Comment by poppyseedplehzr** [comment]
What Linux are you running on just for clarity?

It looks like a few of your configurations are trying to use relative paths, such as here:
```
...
    "logger_path": "tmp/log/osquery",
    "pidfile": "tmp/osquery.pidfile",
...
```
Does changing those, as well as your `--config_path` invocation, to absolute help? Also, just to rule it out, I'd encourage you to try running as `sudo` and with the `--verbose` flag to get extra output from the daemon, in case there's additional information being suppressed.

For prototyping deploy configurations, it can also help to use the `osqueryi` shell component and check what the flags are set to, so for example you could do
```
C:\Users\Nicholas> osqueryi --config_path=/absolute/path/to/config/osquery.conf
osquery> select * from osquery_flags where default_value <> value;
+-------------------+--------+-----------------------------------------------------+---------------------------------+-------------------------------------+------------+
| name              | type   | description                                         | default_value                   | value                               | shell_only |
+-------------------+--------+-----------------------------------------------------+---------------------------------+-------------------------------------+------------+
...
```
Hope that helps, let us know!

**Comment by poppyseedplehzr** [comment]
Was this still an issue? @adamenger did you get it figured out?

**Comment by theopolis** [comment]
Definitely let us know if this is still an issue! The goal is to have 2 categories of "flags", which are also "options" to the configuration:
- Flags that can only be set from a `flagfile`, or via the CLI.
- Flags that can be overridden within the configuration's options.

`osqueryd` tries to help by listing these:
```
osqueryi --help
osquery 2.4.2, your OS as a high-performance relational database
Usage: osqueryi [OPTION]... [SQL STATEMENT]

osquery command line flags:

    --flagfile PATH                           Line-delimited file of additional flags
    --alarm_timeout VALUE                     Seconds to wait for a graceful shutdown
    [...]

osquery configuration options (set by config or CLI flags):

    --audit_allow_config                      Allow the audit publisher to change auditing configuration
    --audit_allow_sockets                     Allow the audit publisher to install socket-related rules
    --audit_persist                           Attempt to retain control of audit
    [...]
```

The order then becomes:
1. Read the CLI flags, override the hard-coded defaults.
2. Read the `--flagfile` and override the CLI options.
3. Attempt to fetch a configuration, read all of the `{"options": {}}` values and override the `flagfile`.
