### ISSUE TITLE
Logging deadlock in getHostIdentifier

### ISSUE THREAD

**Issue by tpott** [facebook/osquery#3174]
When logging inside of getHostIdentifier, osquery enters a deadlock and is no longer able to able to continue. 

While working on https://github.com/facebook/osquery/pull/3165 I was getting blocked whenever I'd log the error message. This currently could affect getInstanceUUID and getHostUUID, since they also log from inside of getHostIdentifier, but I didn't test these two options.

**Comment by poppyseedplehzr** [comment]
Specifically this can be repro'd by adding a `VLOG(1)` line [here](https://github.com/facebook/osquery/pull/3165/files#diff-1302c71760ba770392c0d3a1ef040053R221)

**Comment by theopolis** [comment]
Fixed here: https://github.com/facebook/osquery/commit/65ef94f053df933bcb7324cc9efdb48bfd57bdea
