### ISSUE TITLE
process auditing: CentOS6 (Linux 2.6) possible soft locks

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#3184]
There are multiple reports of the Linux audit integration used for `process_events`, `socket_events` and `user_events` on CentOS6 causing locks.

Example configuration `--flagfile`:
```
--disable_audit=false
--audit_allow_config=true
--audit_persist=true
--audit_allow_sockets
--logger_plugin=syslog
--events_max=100000
--watchdog_memory_limit=350
--events_expiry=1
```

Starting the shell:
```
sudo osqueryi --flagfile /etc/osquery/osquery.flags \
  --nodisable_database --verbose --nodisable_events 
```

For a test host use: `vagrant up centos6.5`, then:
```
sudo /etc/init.d/auditd stop
```

To similar load use:
```
cd /vagrant/
sudo ./tools/analysis/system_stress.py -i eth0 -n 10
```

This should take about `28.3-33s` to complete, but coming out of a system reboot it will take `88-110s`.

**Comment by theopolis** [comment]
The initial CentOS6.5 state:
```
osquery> .all kernel_info
  version = 2.6.32-573.el6.x86_64
arguments = ro rd_NO_LUKS LANG=en_US.UTF-8 rd_NO_MD rd_LVM_LV=VolGroup/lv_swap SYSFONT=latarcyrheb-sun16 crashkernel=129M@0M rd_LVM_LV=VolGroup/lv_root KEYBOARDTYPE=pc KEYTABLE=us rd_NO_DM rhgb quiet
     path = 
   device = /dev/mapper/VolGroup-lv_root

osquery> .all system_info
I0420 03:35:54.541285 11534 system.cpp:184] Using UUID 4B7D5306-BDD8-4E09-8CE4-99A97CCE3EF9 as host identifier
          hostname = localhost.localdomain
              uuid = 4B7D5306-BDD8-4E09-8CE4-99A97CCE3EF9
          cpu_type = 6
       cpu_subtype = 78
         cpu_brand = Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
cpu_physical_cores = 2
 cpu_logical_cores = 2
   physical_memory = 4016668672
   hardware_vendor = innotek GmbH
    hardware_model = VirtualBox
  hardware_version = 1.2
   hardware_serial = 0
     computer_name = localhost.localdomain
```

To test with `auditd`, `vagrant reload centos6.5` and do not stop the daemon.

Use:
```
sudo /sbin/auditctl -a always,exit -S execve
sudo /sbin/auditctl -a always,exit -S bind
sudo /sbin/auditctl -a always,exit -S connect
```

To install the rules osquery uses, then configure the backlog limit to `1024`:
```
sudo /sbin/auditctl -b 1024
```
and finally fire up the stress test. The results (80-110s) response time should be the same.

**Comment by theopolis** [comment]
The newest-available CentOS6.5 2.6.32 kernel: `2.6.32-696.1.1.el6`

Does not have: https://lkml.org/lkml/2013/9/2/473

**Comment by theopolis** [comment]
Yes: https://lkml.org/lkml/2013/9/2/479
Nope: https://lkml.org/lkml/2013/9/2/473

There are several other parts of the patch set here: http://linux-audit.redhat.narkive.com/DT9B4qNS/patch-0-8-audit-backlog-queue-fixes-related-to-soft-lockup

that are not included.

Unfortunately, this CentOS6 2.6.32 kernel uses a static:
```
./audit.c:99:static int	audit_backlog_wait_time = 60 * HZ;
```
So nasty locks will occur, meaning we better dequeue from audit a lot faster, as requested here: https://github.com/facebook/osquery/issues/3149

**Comment by theopolis** [comment]
On newer kernels we can configure the wait time using: http://man7.org/linux/man-pages/man3/audit_set_backlog_wait_time.3.html

**Comment by Centurion89** [comment]
@theopolis - just to make sure I'm understanding this comment (https://github.com/facebook/osquery/issues/3184#issuecomment-295568146) correctly, are you saying that 2.6.32-696.1.1.el6 has been patched and does not experience the lockup that prior kernel versions do?

**Comment by theopolis** [comment]
This ended up being an issue with syslog-ng locking.
