### ISSUE TITLE
Issues found when building with MSVC + /permissive-

### ISSUE THREAD

**Issue by xiangfan-ms** [facebook/osquery#3194]
The C++ compiler team is currently doing daily RWC (Read World Code) testing which includes osquery.

We are also working with internal partners and the community to fix source issues exposed by "/permissive-".
The option isn’t finalized yet (we plan to add some large impact features into it in the incoming VS update), so we don’t suggest to adopt it yet.
In the meantime, we want to address these source issues as early as possible so that the community can adopt it when it is finalized.

We discover some source issues when we build it with "/permissive-".

The issue is in src\osquery/events/windows/windows_event_log.h(93):
error C4596: 'parseEvent': illegal qualified name in member declaration

class WindowsEventLogEventPublisher
{
static Status **WindowsEventLogEventPublisher::**parseEvent(EVT_HANDLE evt, boost::property_tree::ptree& propTree); //line 93
}

The part is bold is illegal.

What is the best practice to get the issue fixed? We'd like to establish a channel so that we can communicate incoming compiler changes which impact existing (non-conformant) code transparently.
We also prefer to just provide the suggestion and ask the owner to make the actual change because sometimes the issue can become complex and we don’t always have enough expertise to find the appropriate fix or the knowledge/resource to do full validation.

Thanks!

**Comment by poppyseedplehzr** [comment]
Hey @xiangfan-ms, thanks for letting us know!  You can feel free to just open up Github issues with any issues you might find and we'll jump on them asap!  Can you be more specific on what the recommended fix here is?
