### ISSUE TITLE
debian support? 

### ISSUE THREAD

**Issue by carloscarcamo** [facebook/osquery#320]
I'm trying to install osquery on debian but it fails when I use make deps, it seems like osquery needs some packages that aren't in debian wheezy repositories.

Is there anyway to install osquery on debian wheezy?

**Comment by mathieuk** [comment]
@marpaia I'm also interested in getting osquery working on Debian. I've gotten osquery to compile on Debian Wheezy and it seems all the tests run fine, so I'm now creating provisioning shell scripts to easily reproduce the build. Would you be interested in getting a PR on that ?

**Comment by theopolis** [comment]
Always!

**Comment by ageis** [comment]
Still no osquery Debian .debs? What's the hold up? ;P
