### ISSUE TITLE
deps: Update Windows dependencies: boost, openssl, aws-sdk-cpp

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#3206]
Linux and macOS have updated their dependencies:
- `boost` -> 1.64
- `openssl` -> 1.0.2k
- `aws-sdk-cpp` -> 1.0.107

**Comment by poppyseedplehzr** [comment]
We have `openssl` and `aws-sdk-cpp` upgraded. The revert of boost 1.64 puts us even with posix. Closing out for now.
