### ISSUE TITLE
Yara-related linker errors with 2.4.0 on FreeBSD

### ISSUE THREAD

**Issue by lxcode** [facebook/osquery#3224]
With yara and yara_events un-blacklisted, an error occurs when linking osqueryd:

`[ 98%] Linking CXX executable osqueryd
cd /root/osquery-port/work/.build/osquery && /usr/local/bin/cmake -E cmake_echo_color --cyan --bold --\ Building\ osqueryd:\ /root/osquery-port/work/.build/osquery/osqueryd
-- Building osqueryd: /root/osquery-port/work/.build/osquery/osqueryd
cd /root/osquery-port/work/.build/osquery && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/daemon.dir/link.txt --verbose=1
/usr/bin/c++  -O2 -pipe -fstack-protector -fno-strict-aliasing -O2 -pipe -fstack-protector -fno-strict-aliasing   -fstack-protector CMakeFiles/daemon.dir/main/posix/daemon.cpp.o  -o osqueryd -Wl,-whole-archive libosquery.a -Wl,-no-whole-archive -Wl,-whole-archive libosquery_additional.a -Wl,-no-whole-archive -lz /usr/local/lib/libgflags.so /usr/local/lib/libthrift.so /usr/local/lib/liblz4.so /usr/local/lib/libglog.so /usr/local/lib/libicuuc.so /usr/local/lib/libboost_system.so /usr/local/lib/libboost_filesystem.so /usr/local/lib/libboost_thread.so /usr/local/lib/libboost_context.so -lrt -lc -llzma -rdynamic -Wl,-zrelro -Wl,-znow -pie /usr/local/lib/librocksdb-lite.so /usr/local/lib/libboost_regex.so /usr/local/lib/libcppnetlib-uri.so /usr/local/lib/libcppnetlib-client-connections.so /usr/local/lib/libsnappy.so -lssl /usr/local/lib/libyara.so -lcrypto -lpthread /usr/local/lib/liblinenoise.a -lbz2 -lprocstat -lutil -lkvm -lelf /usr/local/lib/liblldpctl.so -lmagic /usr/local/lib/libtsk.so /usr/local/lib/libaugeas.so /usr/local/lib/libfa.so /usr/local/lib/libxml2.so
libosquery_additional.a(additional_amalgamation.cpp.o): In function 'osquery::yaraTablePlugin::generate(osquery::QueryContext&)':
/root/osquery-port/work/.build/generated/additional_amalgamation.cpp:(.text._ZN7osquery15yaraTablePlugin8generateERNS_12QueryContextE[_ZN7osquery15yaraTablePlugin8generateERNS_12QueryContextE]+0x20): undefined reference to 'osquery::tables::genYara(osquery::QueryContext&)'
c++: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[4]: *** [osquery/CMakeFiles/daemon.dir/build.make:135: osquery/osqueryd] Error 1
gmake[4]: Leaving directory '/root/osquery-port/work/.build'
gmake[3]: *** [CMakeFiles/Makefile2:523: osquery/CMakeFiles/daemon.dir/all] Error 2
gmake[3]: Leaving directory '/root/osquery-port/work/.build'
gmake[2]: *** [Makefile:144: all] Error 2
gmake[2]: Leaving directory '/root/osquery-port/work/.build'
*** Error code 1`

**Comment by theopolis** [comment]
I bet there's logic in CMake that is preventing some YARA utility code from being compiled (in the ./osquery/tables directory).

**Comment by lxcode** [comment]
Indeed! There was a stray NOT FREEBSD in there for the "other" tables. Works now.
