### ISSUE TITLE
Windows 10 installation ERROR: Exception calling "RemoveAccessRule"

### ISSUE THREAD

**Issue by ogoudron** [facebook/osquery#3230]
"choco install osquery" command fail with this error message on my Windows 10 Family PC.

ERROR: Exception calling "RemoveAccessRule" with "1" argument(s): "Some or all identity references could not be translated."
The install of osquery was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\osquery\tools\chocolateyinstall.ps1'.

Test from admin account with admin console shell on a French Windows 10 Family version 1607 (14393.1066)

Full message in log file
2017-04-28 15:31:38,203 [INFO ] - VERBOSE: Importing alias 'Start-ChocolateyProcess'.
2017-04-28 15:31:38,375 [ERROR] - ERROR: Exception calling "RemoveAccessRule" with "1" argument(s): "Some or all identity references could not be translated."
2017-04-28 15:31:38,781 [ERROR] - The install of osquery was NOT successful.
2017-04-28 15:31:38,797 [ERROR] - Error while running 'C:\ProgramData\chocolatey\lib\osquery\tools\chocolateyinstall.ps1'.
 See log for details.
2017-04-28 15:31:40,875 [WARN ] - 
Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
2017-04-28 15:31:40,891 [INFO ] - 
2017-04-28 15:31:40,907 [ERROR] - Failures
2017-04-28 15:31:40,922 [ERROR] -  - osquery (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\osquery\tools\chocolateyinstall.ps1'.
 See log for details.
2017-04-28 15:31:40,938 [WARN ] -

**Comment by poppyseedplehzr** [comment]
Hey @ogoudron, I _think_ I know what's going on here. When we install osquery on a system, we typically ensure that there are "safe" permissions placed on the file. This means ensuring that the binary as well as the parent directory are non-writeable by Everyone. So in Windows this translates to a Deny-Write ACL being placed on the folder where osquery is installed to, `C:\ProgramData\osquery\osqueryd`.  Does that folder exist on your system? Or did the failed choco install completely remove the binary?

If you get a chance, would you mind pasting the output of `choco install -yfvd osquery'? That should give us a sizeable amount of debugging output, and show precisely where the failure occured in our Powershell scripts. I suspect the failure is [happening here](https://github.com/facebook/osquery/blob/master/tools/provision/chocolatey/osquery_utils.ps1#L27-L34), as you mentioned it's a French system, does the `Everyone` group exist? I'm betting it's not spelled in English :)

**Comment by poppyseedplehzr** [comment]
My bet is that we need to derive the group `Everyone`s name at run time, so that we can derive locality and get the correct string value, as opposed to statically coding the group name.

**Comment by ogoudron** [comment]
I think you are right.
C:\ProgramData\osquery\osqueryd exist and in my French Windows version the group "everyone" is named "Tout le monde".

[osquery-pb.txt](https://github.com/facebook/osquery/files/965038/osquery-pb.txt)

**Comment by poppyseedplehzr** [comment]
Hah, yeah we can fix this by setting the perms via the `World` SID as [detailed here](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379649(v=vs.85).aspx) I'll have a fix up soon, thanks!

**Comment by ogoudron** [comment]
Thanks for your help.

**Comment by poppyseedplehzr** [comment]
@ogoudron would you mind testing the attached chocolatey osquery package to see if this issue is resolved? I'm pretty confident the fix works, but I'm not sure if the `write` permission needs to be derived also..
[osquery.2.4.2-g3821db0.nupkg.zip](https://github.com/facebook/osquery/files/978138/osquery.2.4.2-g3821db0.nupkg.zip)

**Comment by ogoudron** [comment]
Hello,
I have tested both install and unsintall and it works.
I have checked acces right on osqueryd directory and "tout le monde" have deny-write.
I think that this issue is resolved.
Many thanks.
