### ISSUE TITLE
Integration with `mdfind` / Spotlight on macOS

### ISSUE THREAD

**Issue by stouset** [facebook/osquery#3232]
It would be very useful to have a table that allows querying Spotlight (possibly via `mdfind`) on macOS boxes.

**Comment by jedi22** [comment]
https://developer.apple.com/library/content/documentation/Carbon/Conceptual/SpotlightQuery/Concepts/Introduction.html

**Comment by arubdesu** [comment]
@stouset This literally is a request to be able to reimplement spotlight query format as an input to another query? Got any exact use cases/workflows this would enable? Would this always return a file/directory object, or are executables in play as well?

**Comment by stouset** [comment]
A simple example will probably give you an idea of what I'm hoping to do. We're using osquery as a decentralized host-monitoring tool across our fleet, for the purposes of both intrusion detection and to ensure good hygiene.

One thing we want to look for is unencrypted 1Password archives (typically made by the Export option in the File menu).

With osquery currently we either have to scan the filesystem (which will trigger the watchdog to terminate the process early) or limit ourselves to a fixed set of directories:

```sql
SELECT
    `users`.`uid`,
    `file`.`path`
  FROM `file`
  JOIN `users` ON
      `file`.`directory` IN (
        `users`.`directory`,
        `users`.`directory` || '/Documents',
        `users`.`directory` || '/Downloads'
      )
  WHERE `file`.`filename` LIKE '%.1pif';
```

What we'd love to do is be able to replace this with a Spotlight query. Something like:

```sql
SELECT
    `users`.`uid,
    `file`.`path`
  FROM `file`
  JOIN `spotlight` ON
      `spotlight`.`kMDItemFSName` = '*.1pif' AND
      `spotlight`.`pathname` = `file`.`pathname`
  JOIN `users` ON
      `users`.`uid` = `file`.`uid`
```

Possibly even better would be to use `` `kMDItemKind` = '1Password Interchange File `` instead of the file extension (but that might just desugar to checking the extension internally, I'm unsure).

Obviously this is a pretty simple example. But the idea is that the current `file` table is very limited in how it can be queried performantly. Taking advantage of os-builtin filesystem indexes greatly expands the ability to query the filesystem while reducing the actual overhead of doing so.

**Comment by keeleysam** [comment]
+1 on this issue - I stumbled upon this with recursive directory searching where there were a huge number of files.  Spotlight's database isn't always perfect and up to date, but this would be of great benefit.

**Comment by obelisk** [comment]
This is now up for consideration into core here: #4313 

I'm going to close this issue and any further discussion can happen there.
