### ISSUE TITLE
Windows 7 support planned?

### ISSUE THREAD

**Issue by gfeezel** [facebook/osquery#3258]
Are there any plans to support Microsoft Windows 7?

**Comment by poppyseedplehzr** [comment]
Windows 7 should currently be working. 7 32 bit is something that will take more time as we need to port the third party libs, but for now if you pull the latest bins they _should_ be working on Windows 7 x64. We should also be getting close to having a Server 2008 box in our CI build.

That being said there's a number of issues currently opened to address possible bugs with the daemons behavior. Let us know if you find any issues!
