### ISSUE TITLE
Results in file_events have target_paths with semicolons in them

### ISSUE THREAD

**Issue by Centurion89** [facebook/osquery#3262]
While reviewing some file_event logs, I noticed there were quite a few columns.target_path entries that contained a semicolon followed by 8 alphanumeric characters.

![image](https://cloud.githubusercontent.com/assets/5092699/25831837/8c020a84-341b-11e7-99b2-551d09773973.png)

This is happening for the following FIM actions:
UPDATED, CREATED, ATTRIBUTES_MODIFIED, MOVED_FROM

Repro Splunk search:
`index=osquery name=file_events columns.target_path=*;*`

Seeing this on both CentOS6 and CentOS7

**Comment by Centurion89** [comment]
Whatever the 8 character string is on the end of the filename is seems to have a one to many relationship from the host to the filenames. Using the photo above as an example, all of the entries containing 590ba2fe belong to a single host, and all of the entries containing 590cc9ae belong to a different host. From what I can tell, this doesn't seem to be a log formatting issue on the Splunk side or anything like that.

**Comment by theopolis** [comment]
What do you use for configuration management?

**Comment by Centurion89** [comment]
Puppet primarily

**Comment by Centurion89** [comment]
Based on this set of events (which I'm reading from bottom to top), it looks like something is creating this file (maybe as some sort of tempfile?) modifying it, then copying it over to replace the existing `kernel-2.6.32-696.1.1.el6.x86_64.conf` file. Another issue is that timestamps are only recorded with second-based granularity, so figuring out the order in which file_events happened requires some guesswork :-/

![image](https://cloud.githubusercontent.com/assets/5092699/25925086/28556946-359b-11e7-992a-d1ef206615eb.png)

**Comment by theopolis** [comment]
I see similar backup-replace occurring with Chef and RPM/DEB installs when there's local modifications to configurations.

**Comment by theopolis** [comment]
The second precision is annoying, understandable, that should be fixed wholesale.

**Comment by theopolis** [comment]
I'll close this, assuming it is an artifact from Puppet or configuration management.
