### ISSUE TITLE
Purged log number bug

### ISSUE THREAD

**Issue by jacknagz** [facebook/osquery#3264]
## System Info
```
osquery_version: 2.4.2
platform: Ubuntu Trusty 14.04
````

## Error
We are seeing a high volume of the following messages via status logs:

```
error 1:   Purging buffered logs limit (1000000) exceeded: 18446744073709551615
error 2:   Trying to purge 18446744073708551615 logs but only found 0

file:      buffered.cpp
line:      137
severity:  2
```

The exceeded numbers are consistent, and it seems like a bug as that number is close to the integer limit (I would be amazed if syslog was able to process that many messages 😄 )

**Comment by theopolis** [comment]
This should have been fixed with https://github.com/facebook/osquery/pull/3588 (available in version 2.7.0) let me know if you're still seeing the errors.
