### ISSUE TITLE
windows: thrift extensions are verbose

### ISSUE THREAD

**Issue by poppyseedplehzr** [facebook/osquery#3272]
Regardless of the `--verbose` flag, any windows extensions are outputing to stdout via this line: https://github.com/apache/thrift/blob/19baeefd8c38d62085891d7956349601f79448b3/lib/cpp/src/thrift/transport/TPipeServer.cpp#L236

**Comment by theopolis** [comment]
You solved this by patching the distributed thrift library right?

**Comment by poppyseedplehzr** [comment]
Yes. Patching out those lines worked.
