### ISSUE TITLE
Support creation of tables in other languages such a Java, Lua, Rust, Go

### ISSUE THREAD

**Issue by cetra3** [facebook/osquery#3287]
This has probably already been answered, but I'm wondering if there is a way to extend osquery to provide tables that other languages provide the results from for some custom stuff?

At the moment it looks like you need to use C++ to create any custom tables, but it would be nice if this could potentially be scripted out, so that something like a java app or similar could provide the implementation.

**Comment by poppyseedplehzr** [comment]
Hey @cetra3, we currently support [Python extension tables](https://osquery.readthedocs.io/en/stable/development/osquery-sdk/) on posix platforms, and soon Windows.  All of the extension tables talk to the osquery daemon over a thrift socket, so in theory if there were extension frameworks for said other languages that thrift supports, one could support other languages, but this isn't something in our immediate roadmap. We're always open to folks opening new PRs though!  I'm going to close this out for now, but feel free to re-open if you'd like. This question might also be best continued in [the osquery Slack?](https://osquery-slack.herokuapp.com/)
