### ISSUE TITLE
Non-numeric comparisons in "select max(fahrenheit) from temperature_sensors;" ?

### ISSUE THREAD

**Issue by jhurliman** [facebook/osquery#3292]
Running `select max(fahrenheit) from temperature_sensors;` returns the closest two digit number to 100 rather the the highest numeric value (currently 111.2 on my MBP). It seems to be doing a character comparison and ranking 9 higher than 1 rather than a numeric comparison.

**Comment by jedi22** [comment]
Good catch!

**Comment by jedi22** [comment]
Thanks for reporting this bug! This should be fixed in master now, please reopen if you find it's still not working as intended!
