### ISSUE TITLE
Random crashes: related to DB reset and schedule reload

### ISSUE THREAD

**Issue by spasam** [facebook/osquery#3294]
Ubuntu 16.04
OSQuery 2.4.4

Am seeing frequent crashes with the following error:
```
osqueryd[27275]: terminate called after throwing an instance of 'std::runtime_error'
osqueryd[27275]:   what():  Cannot get database values
```

It looks like when resetDatabase() flips kDBInitialized, database is being accessed and causing this!

**Comment by spasam** [comment]
@theopolis Isn't resetDatabase() supposed to acquire write lock on kDatabaseReset?

**Comment by spasam** [comment]
Or may be not! Anyway, this seems to be easy to reproduce by setting schedule_reload to a very small value (eg: 5)

**Comment by theopolis** [comment]
Right, while this may be a locking issue, it's a logic issue not an unprotected critical section.
