### ISSUE TITLE
aws_firehose logger plugin reports 'success' but doesn't send anything to firehose stream

### ISSUE THREAD

**Issue by ghexp** [facebook/osquery#3310]
Using aws_firehose logger plugin on mac os x (10.12.5) with config below.  Running 2.4.2 installed from .pkg. osqueryd --verbose reports queries executing and 'success' sending 0 logs to Firehose. Repeating "Successfully sent 0 logs to Firehose." with no data received by Firehose stream.  Stream verified as running and accepting data via curl. Firehose plugin reports successful initiation. (log below).  Any additional debugging output possible?

Config (/var/osquery.conf):
```
{
  "options": {
    "host_identifier": "hostname",
    "schedule_splay_percent": 10,
    "logger_plugin": "aws_firehose",
    "aws_firehose_stream": "osquery",
    "aws_firehose_period": 10,
    "aws_access_key_id": "<snip>",
    "aws_secret_access_key": "<snip>",
    "aws_region": "us-east-1"
  },
  // Define a schedule of queries:
  "schedule": {
     "time": {
     "query": "SELECT * FROM time;",
     "interval": 2,
     "removed": false
     }
  }
}
```
osqueryd --ephemeral --database_path /tmp/osquery.db --verbose
Output:
```
08:47:37.808974 3696231360 init.cpp:383] osquery initialized [version=2.4.2]
08:47:37.810426 263774208 watcher.cpp:465] osqueryd watcher (7917) executing worker (7918)
08:47:37.818892 3696231360 init.cpp:380] osquery worker initialized [watcher=7917]
08:47:37.819735 3696231360 rocksdb.cpp:205] Opening RocksDB handle: /tmp/osquery.db
08:47:37.824524 121147392 interface.cpp:317] Extension manager service starting: /var/osquery/osquery.em
08:47:37.825426 3696231360 aws_util.cpp:340] Using AWS region from flag: us-east-1
08:47:37.825537 3696231360 aws_firehose.cpp:138] Firehose logging initialized with stream: osquery
08:47:37.827044 3696231360 preferences.cpp:216] Cannot find/read defaults plist from path: /private/var/db/receipts/com.facebook.osquery.kernel.plist
08:47:37.827114 3696231360 events.cpp:827] Event publisher failed setup: kernel: Cannot access /dev/osquery
08:47:37.827133 3696231360 events.cpp:827] Event publisher failed setup: scnetwork: Publisher not used
08:47:37.827420 3696231360 events.cpp:1080] Error registering subscriber: process_events: No kernel event publisher
08:47:37.827515 3696231360 events.cpp:1080] Error registering subscriber: process_file_events: No kernel event publisher
08:47:37.843750 3696231360 daemon.cpp:38] Not starting the distributed query service: Distributed query service not enabled.
...
08:47:38.844130 124903424 scheduler.cpp:74] Executing scheduled query time: SELECT * FROM time;
08:47:38.847478 124903424 scheduler.cpp:132] Found results for query: time
08:47:39.130697 121683968 aws_firehose.cpp:115] Successfully sent 0 logs to Firehose.
08:47:39.257388 121683968 aws_firehose.cpp:115] Successfully sent 0 logs to Firehose.
08:47:40.406997 121683968 aws_firehose.cpp:115] Successfully sent 0 logs to Firehose.
```

**Comment by ghexp** [comment]
Similar reporting of the same issue:
https://medium.com/@rtacconi/i-tried-to-configure-kinesis-but-all-i-can-do-is-1651e5d1bc64

**Comment by zwass** [comment]
Does this bug occur with older versions of osquery?

Is anyone able to get a pcap of the request/response when this fails? That would really help.

I wonder if some error is being hit and reported in a different way than the individual record errors are reported. If folks are willing, we may be able to make a debug build and get some more information here, but it would probably be basically the same info we could get from a pcap.

**Comment by ghexp** [comment]
Above example was 2.4.2.  Also repeated in 2.5.0.  How far back of a release should I try? I do have a pcap, but I need to sanitize it.  Do you need payload data or just traffic?  I'm also happy to run a debug build, since it may be faster than convincing myself that the pcap is sufficiently sanitized.

**Comment by theopolis** [comment]
@ghexp, if you have time to test try with:
- https://osquery-packages.s3.amazonaws.com/darwin/osquery-2.4.0.pkg
- https://osquery-packages.s3.amazonaws.com/darwin/osquery-2.3.4.pkg

Thanks!

**Comment by zwass** [comment]
@ghexp I'd be interested in payload data, and in particular the responses from the server (if that helps with sanitization). You can PM me the data on the osquery Slack if that makes you feel any better.

If not, I may be able to put together a debug build sometime tomorrow.

**Comment by ghexp** [comment]
I've got a debug build running, but I don't see any real difference in the log output for the firehose logging.  I'm running with --verbose_debug.  Am I missing something or do a need to run with breakpoints?
The server response payload data is encrypted in the pcap, so I'm not sure that helps troubleshoot.

**Comment by theopolis** [comment]
Wouldn't the PCAP just include your TLS hellos and then encrypted content?

**Comment by zwass** [comment]
Yeah we'd need a pcap with the TLS proxied so we had visibility into the content.

When I said debug build I was referring to adding some additional logging of the request and response contents in a custom build so that we could see similar information to what a proxied pcap would look like. I have a feeling there is some error being reported in a way that is different than what we expected, and I'd like to try to verify that.

**Comment by zwass** [comment]
@ghexp Please try building and running with the following commit (or make the change manually yourself):
https://github.com/zwass/osquery/commit/df8400cd73780b365d8f55d09a6609ff0513c14a

On a hunch, I tried setting my AWS region incorrectly, and encountered the same symptom. I have a feeling this may be your issue.

```
{"__type":"ResourceNotFoundException","message":"Firehose osquery_test not found under account 277476773993."}
I0619 12:52:10.494671 163971072 aws_firehose.cpp:115] Successfully sent 0 logs to Firehose
```

We used to do a check on startup that we were able to access the stream, but that was removed in https://github.com/facebook/osquery/pull/2867. Looks like the error handling needs to be fixed now.

**Comment by zwass** [comment]
I will make a PR in the next couple days that checks these errors correctly. I think this manual printing will help @ghexp figure things out right now, and that PR should be a more sustainable solution.

**Comment by ghexp** [comment]
That did the trick.  It was a permissions issue, despite using the auto-generated AWS firehose delivery policy, the AWS credentials still didn't have sufficient privileges.  Specifically the error/exception (unhandled) was:
{"__type":"AccessDeniedException","Message":"User: arn:aws:iam::snipsnipsnip:user/foosnip is not authorized to perform: firehose:PutRecordBatch on resource: arn:aws:firehose:us-east-1:snipsnipsnip:deliverystream/snipstreamname"}
Thank you all for your help.  I'm happy to close this if helpful and maybe even contribute some error checking code if @zwass doesn't beat me to it.  
Thank you all for your help and @zwass to instrumenting the right spot.

**Comment by zwass** [comment]
@ghexp Glad that worked out for you. The above PR fixes the error handling so that in the future folks will directly see the errors.

**Comment by ghexp** [comment]
@zwass or @theopolis, close this issue or keep it open until PR is accepted?

**Comment by zwass** [comment]
I'd say we should leave the issue open and let it auto-close when the PR is merged.
