### ISSUE TITLE
Windows Driver Versions

### ISSUE THREAD

**Issue by TheVakman** [facebook/osquery#3313]
I think I read that this was tabled after the initial driver table implementation but it'd be one of my main reasons to implement this at all in our environment.

I am looking to query on driver versions from device drivers on Windows. Does anyone know if there is a way to do this or an extension to do this? Alternatively, if this could be a feature request that is put back on the table.

**Comment by ryanheffernan** [comment]
I added some best effort support for this, in cases where the registry entry contains version info. Not all drivers have this, so will need to dig further to see where we can get version info for those ones. Perhaps from the .inf files?

**Comment by TheVakman** [comment]
Thanks, I'll keep my eye out for that update!

That could work, I think that's what the version comes from when you view the version in Device Manager, minus the date that's prefixed when viewing the actual .inf file.

Today, I also run this PowerShell command when I need to, I doubt this would help you though:
Get-WmiObject Win32_PnPSignedDriver | select devicename, driverversion

**Comment by ryanheffernan** [comment]
Yep, I've been looking at that command as well. WMI would have this info, but I'm trying to find a non-WMI way to get this info. Will try to get this out for testing next week.

**Comment by ryanheffernan** [comment]
Feel free to try this out in master and let me know if you have any feedback. Required quite a bit of rework in the drivers table, but it's for the best as now the table is much more accurate :).

**Comment by TheVakman** [comment]
Thanks, it's a good update but it seems a little odd in some cases?

As one example, if I put it on a laptop here, for this Intel WiFi 8265 adapter osquery returns a version of 19.1.50.5 but the above WMI command above returns the version as expected which is also the one reported in Device Manager/by other inventory tools: 19.50.1.5. It's almost like the numbers are swapped for multiple drivers on the system when reported by osquery.
