### ISSUE TITLE
Windows Installed programs list not complete

### ISSUE THREAD

**Issue by jackatbancast** [facebook/osquery#3318]
When querying the installed programs on a Windows 10 installation, I found that the list of programs reported by osquery was incomplete.

Examples of some omissions include Inkscape and Spotify.

The issue appears to be that [osquery queries the registry for uninstallers](https://github.com/facebook/osquery/blob/5671bb720b19816c4973f3ecede9c299bd8c01fb/osquery/tables/system/windows/programs.cpp#L31).
This works for well-behaved software but requires the software to write to this area specifically.

After some research`wmic` (e.g. `wmic products get installdate,vendor,installlocation,version /format:json` in `cmd.exe`) appears to perform a query to `HKEY_CLASSES_ROOT\Installer\Products`, which does produce a different list that appears to be more complete.

A better behaviour may be list the output of a combined query of the Uninstaller section of the registry alongside a query for installer products?

**Comment by poppyseedplehzr** [comment]
Hey @jackatbancast, we actually already have an issue tracking this, which I'll rename to be more descriptive ;). Would you mind reposting this data there? I'm going to close this out so we can move the discussion into the existing thread. Thanks!
