### ISSUE TITLE
When building and putting dependencies in non-default location, pip fails to upgrade

### ISSUE THREAD

**Issue by nbigaouette-eai** [facebook/osquery#3374]
If I use `OSQUERY_DEPS` to place osquery's compile-time dependencies in a non-default location (say `${HOME}/osquery_deps_dir`, the step `upgrading pip and installing python dependencies` of `make deps` will fail with:

```
[+] upgrading pip and installing python dependencies
Traceback (most recent call last):
  File "${HOME}/osquery_deps_dir/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 658, in _build_master
    ws.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 959, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 846, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pip==8.1.2' distribution was not found and is required by the application
```

The content of `${OSQUERY_DEPS}/bin/pip` is as follow:
```
#!/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
# EASY-INSTALL-ENTRY-SCRIPT: 'pip==8.1.2','console_scripts','pip'
__requires__ = 'pip==8.1.2'
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.exit(
        load_entry_point('pip==8.1.2', 'console_scripts', 'pip')()
    )
```

I'm not sure why the shebang should be the system python and not the one that is installed by osquery's homebrew in `${OSQUERY_DEPS}`. I guess it shouldn't?

Note that this is with a "pristine" macOS system (only Xcode 8.3.2 has been installed): pip has never been installed for the system Python.

Thanks!

**Comment by nbigaouette-eai** [comment]
To bypass this problem, I can either rebuild everything (with `build_deps` make target) or force building Python only.

If I force Python to build using this patch:
```
diff --git a/tools/provision.sh b/tools/provision.sh
index b800af58..7b704f39 100755
--- a/tools/provision.sh
+++ b/tools/provision.sh
@@ -116,7 +116,11 @@ function platform_darwin_main() {
 
   brew_dependency osquery/osquery-local/libxml2
   brew_dependency osquery/osquery-local/openssl
+  # Force Python to be built from source
+  prev_OSQUERY_BUILD_DEPS=${OSQUERY_BUILD_DEPS}
+  export OSQUERY_BUILD_DEPS=1
   brew_tool osquery/osquery-local/python
+  export OSQUERY_BUILD_DEPS=${prev_OSQUERY_BUILD_DEPS}
   brew_tool osquery/osquery-local/cmake --without-docs
 
   platform_posix_main
```

then the build proceeds successfully, but some tests fail and I can't create the packages (see #3373).

The patch is just a hack though.

**Comment by theopolis** [comment]
Did we resolve this? I forget ;)

**Comment by nbigaouette-eai** [comment]
Unfortunately, this was never resolved (we still carry the patch locally).

And the more I work with osquery's build system, the more I believe using `OSQUERY_DEPS` to place dependencies in a non-default location is broken.

I have hit many difficulties when using it. And I don't think it is solvable as the binaries themselves reference the path in so many different location.

For example a build on Linux is not possible with `OSQUERY_DEPS` pointing to something else than `/usr/local/osquery`: curl simply cannot connect to the network if the files are not in the default location.

I think the only valid solutions are to either 1) drop completely the variable (and force the default location) or 2) force a full recompilation of dependencies when it is used (as finding exactly _what_ to recompile could be quite time consuming and error prone) and a deep review of the code base for explicit usage of the path...

Something in between could be done where `OSQUERY_BUILD_DEPS` could be split into one variable per dependency so as to be able to control which packages absolutely need to be recompiled...

🤔

**Comment by theopolis** [comment]
I feel you pain and ran into similar issues when trying to use `linuxbrew`'s pre-compiled bottles. Maybe the build system can `chroot` before building osquery then use `/usr/local/osquery` relative to that root?

**Comment by nbigaouette-eai** [comment]
Building for Linux was actually easier, even though `OSQUERY_DEPS` was not working.

I was able to assemble a (relatively) simple Dockerfile, based on ubuntu:16.04, with the required dependencies and build user.

Since the build process is then happening inside a container, I can simply ignore the `OSQUERY_DEPS` issue; I let linuxbrew install to `/usr/local/osquery`.

I did tried the vagrant files but was not successful. I don't remember the details though, it's been a few weeks. Going through Docker was actually a lot simpler and probably faster (at least when building on Linux).

That way, building osquery _for_ Linux is possible on both macOS and Linux, thanks to Docker!

If only we could have a macOS in a container...

All in all, that let me to believe the `OSQUERY_DEPS` is almost completely broken... :(

**Comment by theopolis** [comment]
Sounds good :) the `vagrant`-based testing on Linux was broken for a while because LLVM's LLD was having trouble with NFS-like filesystems. I ran this down to several `mmap` and `fallocate`s that did not have fallbacks for filesystem's that don't implement the syscalls. That should be fixed now through some clever uses of symlinking to the VM's tmpfs. The `./Vagrantfile` does have targets for `macos10.12`. If that's appropriate you can cover all OSes.
