### ISSUE TITLE
Permissions issue during 'make deps' when building from source

### ISSUE THREAD

**Issue by snoozesecurity** [facebook/osquery#3385]
Hello, I attempted to run 'sudo make deps' on Ubuntu 16.04.2 LTS and got the following:

Error: Running Homebrew as root is extremely dangerous and no longer supported.  As Homebrew does not drop privileges on installation you would be giving all build scripts full access to your system.

I then removed 'sudo' but still got an error:

./tools/provision.sh build xenial
[+] checking for updates to brew
error: cannot open .git/FETCH_HEAD: Permission denied

Makefile:127: recipe for target 'deps' failed
make: *** [deps] Error 255

Is there a known solution for this?  I am unable to build from source.  I would try to install via apt-get but that is failing with a 403 (this has been reported in another issue).

Thanks!

**Comment by poppyseedplehzr** [comment]
Ooo yeah, we encourage you to never use root if you can avoid it. What might've happened is the repo you're working out of got "owned" by root? Any chance you could run `sudo chown -R $(whoami) <Insert name of osquery repo>`? Once you get the osquery repo folder owned by your current user, you should be able to do the `make sysprep`, `make deps`, and `make` combo and be good. The `make sysprep` step will prompt you for a sudo credential, but that's mostly for running a system update. None of the third party libs or generated binary files should be owned by root for best user experience :)

**Comment by snoozesecurity** [comment]
Unfortunately this still yields the following:

./tools/provision.sh build xenial
[+] checking for updates to brew
error: cannot open .git/FETCH_HEAD: Permission denied

Makefile:127: recipe for target 'deps' failed
make: *** [deps] Error 255

I even did a 'git clone' to my ~/Documents directory.  Issue persists.

**Comment by theopolis** [comment]
Hi @snoozesecurity!

You're most likely seeing the "Permission denied" because the original `sudo make deps` performed some actions as root. You should run `sudo make depsclean` then `make deps`. 

Let me know if that doesn't fix the issue and we'll reopen and dig deeper. It should be creating and checking out brew into `/usr/local/osquery`. That's the folder your user does not have access to clone into.
