### ISSUE TITLE
Cannot activate syslog logger plugin: Unknown registry plugin: syslog

### ISSUE THREAD

**Issue by juju4** [facebook/osquery#3395]
Hello,

I recently upgrade from 2.4.2 and 2.4.6 and I have regression on all setups with syslog logger.
osqueryd can't start with above error message

Example
https://travis-ci.org/juju4/ansible-osquery/jobs/241321012
```
Jun 09 19:23:57 f502f61ad1d7 osqueryd[578]: osqueryd started [version=2.4.6]
Jun 09 19:23:57 f502f61ad1d7 osqueryd[578]: E0609 19:23:57.666172   584 init.cpp:551] Cannot activate syslog logger plugin: Unknown registry plugin: syslog
```

filesystem logger is not affected.

Thanks

**Comment by ryanheffernan** [comment]
Can you confirm the platform you see this on? I.e. windows, darwin, etc..

**Comment by juju4** [comment]
Linux (redhat, ubuntu at least - see travis)

**Comment by Centurion89** [comment]
+1, also seeing this on a CentOS6 box

**Comment by theopolis** [comment]
Seems like the `syslog` plugin needs some unit testing :)

**Comment by theopolis** [comment]
The plugin is not included: https://github.com/facebook/osquery/blob/master/osquery/logger/CMakeLists.txt#L14 if there was a unit test for the logger this would not have happened. We do not use the `syslog` logger plugin so this is easily missed. We'd need to get that test landed before calling this fixed.

**Comment by juju4** [comment]
Hello @theopolis 

any reason, why just linux?
https://github.com/facebook/osquery/pull/3401/commits/9e7fea4e6c02b35f6e9376a4adf5aad533c017d8#diff-81a5a39e3cf862ddd15f6b2f5d3f6312R21

syslog doesn't apply to windows clearly but it can for Macos.

Thanks a lot!

**Comment by theopolis** [comment]
I'm not sure, I think the APIs are different, macOS should be using ASL. Do you mind prototyping?

**Comment by juju4** [comment]
A bit more complicated. since sierra, there is a third option "unified logging" which superseded both
https://developer.apple.com/documentation/os/logging?preferredLanguage=occ
https://www.mac4n6.com/blog/2016/11/13/new-macos-sierra-1012-forensic-artifacts-introducing-unified-logging

At this point, i would still go for syslog as probably easier, known better. It's not clear to me how to centralize logs with unified logging.
I can give a try, not sure when but will try.

**Comment by groob** [comment]
writing to the unified logging means you can't really read from it using an API. 

the ASL logging still works if you compile against it, which is how https://github.com/facebook/osquery/pull/1915 continues to work on 10.12.
