### ISSUE TITLE
No way to get username running a process for domain users on Windows 

### ISSUE THREAD

**Issue by mew1033** [facebook/osquery#3400]
The processes table includes a uid, but not a username. When users are local to the machine, that uid matches what's in the uid table. However, if the user is a domain user, they're uid is -1, so there's no way to tell which user is actually running a process.

**Comment by poppyseedplehzr** [comment]
I'll have to look into this more, there should be a good way for us to make this connection as we get the `uid` for domain users via the `sid`, but I need to double check how that ties with the `processes` table.

**Comment by mew1033** [comment]
Any updates on this?

**Comment by muffins** [comment]
@mew1033 ah my apologies for letting this get stale! I'll double check the state of this, and if it's still broken I'm working on some overhauls to the `processes` table anyway and will ensure this is do-able!

**Comment by muffins** [comment]
@mew1033 yeah this looks to be a limitation of the way the processes table works. I'll see if I can't address this here soon - again apologies for letting this issue go stale, this fix might prove to be a little tricky.

**Comment by muffins** [comment]
#3574 fixes this issue.
