### ISSUE TITLE
Missing info in socket_events

### ISSUE THREAD

**Issue by iBigQ** [facebook/osquery#3410]
When I look at the table `socket_events` there is no 'local_address' and 'local_port' for the action 'connect'. Also, the 'protocol' field is always 0 (I would expect e.g. 6 or 11 as in `process_open_sockets`).

Is this expected behavior and limited by audit?

**Comment by theopolis** [comment]
I don't think the `connect` syscall contains that information? Maybe `protocol` can be deduced?
