### ISSUE TITLE
Use 'localhost' for machines without a hostname

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#3425]
Some machines may not have a hostname configured. We should return 'localhost' for these machines. Or perhaps `(none)`?

**Comment by jedi22** [comment]
What about their UUID?

**Comment by theopolis** [comment]
Not sure, it is useful to have the hostname and if someone is requesting `--host_identifier` to send the hostname, we should indicate that they don't have one somehow. This has only shown up on FreeBSD so it's low-pri.

**Comment by theopolis** [comment]
Maybe we can leave it as is and handle it on the backend (for our hosts).
