### ISSUE TITLE
--disable_watchdog disables rocksdb as well

### ISSUE THREAD

**Issue by jedi22** [facebook/osquery#3435]
Using disable_watchdog forces an ephemeral database. This was reproed on macOS and FreeBSD

**Comment by theopolis** [comment]
I introduced this regression, which exists in 2.5.0 and 2.5.1: https://github.com/facebook/osquery/commit/f8f57182975b8c6da15439e862bd6a5ca736dcfb essentially `--disable_watchdog` will disable the DB and logging too.

**Comment by theopolis** [comment]
Fixed with: 89ee28dcc4932139c6d292b8262ccbbe22997b33
