### ISSUE TITLE
SIGTERM handler may cause osqueryi can't exit

### ISSUE THREAD

**Issue by imliuda** [facebook/osquery#3445]
the version of osquery is 1.6.4.

I have a osqueryd running in background to collect hardware events. in another program, i use osqueryi to query history events, because there are lot of data, query may be run over 30 seconds, in which case, we send a SIGTERM signal to osqueryi process, mostly osqueryi will exit normally, but sometime osqueryi get blocked. we examined the running state of osqueryi with pstack program, found it got a deadlock. as showed in the follow picture.

![m3 h vk4hkm36827tlbl l](https://user-images.githubusercontent.com/11783644/27585389-b04d6a94-5b6e-11e7-8e83-12b39fb23c89.png)

I googled this problem, saying it is caused by using malloc in signal handler. malloc is not signal safety function. I have tried use v2.5.0 version with file_events table to repeat this case, but this version, osqueryi don't use the --database_path parameter, it always return 0 rows of query. it seems that osqueryi use a in memory database.

**so i want to know how to fix this problem, and if the newer version has fixed this problem? if the newer version has fixed this problem, how can i use osquery for querying the events data in my "osquery.db"**

**Comment by theopolis** [comment]
Hi @imliuda, you're correct, we shouldn't be using `malloc` in a signal handler. It's not safe, but we normally get away with it.

To use the `file_events` table with `osqueryi` use: `osqueryi --disable_events=false`.

**Comment by imliuda** [comment]
yes, i added the --disable_events=false option. the command line is `osqueryi --disable_events=false --database_path=/home/blue/osquery.db/ --config_path=/home/blue/osquery.conf`, when i write some text to the monitored file, i can get the file event from database using `select * from file_events`, but when i quit the osqueryi, and run that command again without changing the monitored file, i can't get the previous event data, that query return empty, the data are not saved to the "osquery.db", i seems that osqueryi use a in memory database. i know osqueryd will save the events to the "osquery.db" directory, because the directory size is growing. with version 1.6.4, i can get the data using this command `osqueryi --database_path=some_place "select * from file_events"`, but v2.5.0 can't, is there a way can achieve this?

**Comment by theopolis** [comment]
Thanks @imliuda, this should be fixed with the most recent version 2.5.2. Packages wont be available for a few days, but if you build from master you can verify.

**Comment by imliuda** [comment]
thanks @theopolis
