### ISSUE TITLE
Building from scratch fails on `make deps`; problem with homebrew?

### ISSUE THREAD

**Issue by nbigaouette-eai** [facebook/osquery#3460]
I am building osquery from scratch since a couple of weeks without major issue. Last time I've made a clean build from scratch was on June 28th; I then had to pull the build dependencies using `make deps`.

Unfortunately, there is a problem with homebrew today. Running `make deps` fails:
```
./tools/provision.sh build darwin10.12
[+] setting up new brew in /Users/nicolas/deps_dir
Cloning into '/Users/nicolas/deps_dir'...
remote: Counting objects: 87586, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 87586 (delta 15), reused 19 (delta 7), pack-reused 87550
Receiving objects: 100% (87586/87586), 20.36 MiB | 1.95 MiB/s, done.
Resolving deltas: 100% (63208/63208), done.
HEAD is now at ea8be174f Merge pull request #2631 from GauthamGoli/audit_homepage_rubocop
[+] refreshing local tap: osquery-local
[+] installing and updating Homebrew core
==> Tapping homebrew/core
Cloning into '/Users/nicolas/deps_dir/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 363199, done.
remote: Total 363199 (delta 0), reused 0 (delta 0), pack-reused 363198
Receiving objects: 100% (363199/363199), 123.64 MiB | 1.93 MiB/s, done.
Resolving deltas: 100% (212747/212747), done.
Error: Invalid formula: /Users/nicolas/deps_dir/Library/Taps/homebrew/homebrew-core/Formula/ckan.rb
invalid attribute for formula 'ckan': version (nil)
Error: Invalid formula: /Users/nicolas/deps_dir/Library/Taps/homebrew/homebrew-core/Formula/clojurescript.rb
invalid attribute for formula 'clojurescript': version (nil)
Error: Invalid formula: /Users/nicolas/deps_dir/Library/Taps/homebrew/homebrew-core/Formula/eprover.rb
invalid attribute for formula 'eprover': version (nil)
Error: Invalid formula: /Users/nicolas/deps_dir/Library/Taps/homebrew/homebrew-core/Formula/fibjs.rb
invalid attribute for formula 'fibjs': version (nil)
Error: Invalid formula: /Users/nicolas/deps_dir/Library/Taps/homebrew/homebrew-core/Formula/metabase.rb
invalid attribute for formula 'metabase': version (nil)
Error: Invalid formula: /Users/nicolas/deps_dir/Library/Taps/homebrew/homebrew-core/Formula/nuget.rb
invalid attribute for formula 'nuget': version (nil)
Error: Cannot tap homebrew/core: invalid syntax in tap!
```
Looking under `deps_dir/Library/Taps/` the directory `homebrew` is effectively absent; there is only an `osquery` directory, which contains a single symbolic link `homebrew-osquery-local` pointing to `/Users/nicolas/osquery.git/tools/provision/formula`.

I don't think it's an osquery issue _per-se_ because I've tried with an older version (tag `2.4.6`) and got the same problem. I would say the problem lies with homebrew (or the handling of homebrew). Since homebrew is, to my knowledge, pulling the tap's HEAD, maybe something changed in how homebrew should be integrated with osquery.

I'm not sure how to handle this one... 😕

**Comment by nbigaouette-eai** [comment]
Note that in the working "already cached" `deps_dir` directory the directory `deps_dir/Library/Taps/homebrew/homebrew-core/Formula` has `https://github.com/Homebrew/homebrew-core` as its remote and is at 4e686a0a2a23d4075077eed5a1250fc020ab1864.

**Comment by nbigaouette-eai** [comment]
It's the tap that fails: [tools/provision/lib.sh line 66](https://github.com/facebook/osquery/blob/2.5.0-6-ge75575ea/tools/provision/lib.sh#L66)

**Comment by nbigaouette-eai** [comment]
Really weird, manually tapping works:
```
$ ./deps_dir/bin/brew tap homebrew/core
==> Tapping homebrew/core
Cloning into '/Users/nicolas/deps_dir/Library/Taps/homebrew/homebrew-core'...
remote: Counting objects: 4465, done.
remote: Compressing objects: 100% (4261/4261), done.
remote: Total 4465 (delta 35), reused 463 (delta 12), pack-reused 0
Receiving objects: 100% (4465/4465), 3.54 MiB | 1.93 MiB/s, done.
Resolving deltas: 100% (35/35), done.
Tapped 4258 formulae (4,509 files, 11MB)
```

`make deps` is unfortunately failing further down the road with:
```
fatal: Could not parse object '4e686a0a2a23d4075077eed5a1250fc020ab1864'.
```
This commit is actually `HOMEBREW_CORE` from `osquery.git/tools/provision.sh`.

**Comment by jedi22** [comment]
We pull a specific version of brew to prevent a new commit that breaks a package from breaking our build. It looks like brew updated and now the formulas need to be updated as well. I fixed this today when I was building on High Sierra, I'll update my pull request and try to get the fix out soon.

**Comment by nbigaouette-eai** [comment]
It's good that the dependencies are fixed (I was asking myself that exact question).

But the issue is in  [tools/provision/lib.sh line 66](https://github.com/facebook/osquery/blob/2.5.0-6-ge75575ea/tools/provision/lib.sh#L66) which simply calls `$BREW tap homebrew/core --full`, without specific commit id. The following line is reseting the HEAD pointer to the pinned version. So if the commit was not present in the repo then I understand the reset operation failing, but it's the clone operation (the brew tap) that fails... 🤔

**Comment by jedi22** [comment]
The first error you posted, is it still present in the High Sierra Fix pull request #3454 ?

**Comment by nbigaouette-eai** [comment]
I've tried 02a7485bd062724621234b805651648653f77591 from your jedi22/hsbuild branch and the error is not there anymore. I'm on Sierra though, not HS.

**Comment by jedi22** [comment]
Yeah, when I created the fix I thought the problem was limited to High Sierra. That pull is merging in nowish so it should be fixed in master soon.

**Comment by nbigaouette-eai** [comment]
So after investigation, the only needed fix is this one:
```diff
diff --git a/tools/provision.sh b/tools/provision.sh
index b800af58..d020851f 100755
--- a/tools/provision.sh
+++ b/tools/provision.sh
@@ -19,9 +19,10 @@ LINUXBREW_REPO="https://github.com/Linuxbrew/brew"

 # Set the SHA1 commit hashes for the pinned homebrew Taps.
 # Pinning allows determinism for bottle availability, expect to update often.
 HOMEBREW_CORE="4e686a0a2a23d4075077eed5a1250fc020ab1864"
 LINUXBREW_CORE="501c656e81770ff64f12131a20535795e9229e44"
-HOMEBREW_BREW="ea8be174f6009bc9bdec67b13ca501b5b83fc4b8"
+HOMEBREW_BREW="b5529084906af89827f6d9befd613457a1615918"
 LINUXBREW_BREW="1d16368a177807663e1b3146d71fcd69e2061e27"

 # If the world needs to be rebuilt, increase the version
```
No need to bump `HOMEBREW_CORE`.

That's simply on top of e75575ea.

**Comment by jedi22** [comment]
Cool! The High Sierra fix is merged so you should be good either way. I'm going to close this issue out.
