### ISSUE TITLE
bulid error

### ISSUE THREAD

**Issue by qhdwns123** [facebook/osquery#3463]
HI.

I get an error.

What is the workaround?

command: make deps

./tools/provision.sh build zesty
[+] checking for updates to brew
Merge tag Homebrew/1.1.13 into Linuxbrew/master
[+] refreshing local tap: osquery-local
[+] installing and updating Homebrew core
==> Tapping homebrew/core
'/usr/local/osquery/Library/Taps/homebrew/homebrew-core'
remote: Counting objects: 384048, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 384048 (delta 3), reused 9 (delta 3), pack-reused 384038
 100% (384048/384048), 145.33 MiB | 557.00 KiB/s, 
100% (228430/228430), 
Error: Invalid formula: /usr/local/osquery/Library/Taps/homebrew/homebrew-core/Formula/metabase.rb
invalid attribute for formula 'metabase': version (nil)
Error: Invalid formula: /usr/local/osquery/Library/Taps/homebrew/homebrew-core/Formula/clojurescript.rb
invalid attribute for formula 'clojurescript': version (nil)
Error: Invalid formula: /usr/local/osquery/Library/Taps/homebrew/homebrew-core/Formula/llvm.rb
Unable to determine the system's glibc version
Error: Invalid formula: /usr/local/osquery/Library/Taps/homebrew/homebrew-core/Formula/eprover.rb
invalid attribute for formula 'eprover': version (nil)
Error: Invalid formula: /usr/local/osquery/Library/Taps/homebrew/homebrew-core/Formula/ckan.rb
invalid attribute for formula 'ckan': version (nil)
Error: Invalid formula: /usr/local/osquery/Library/Taps/homebrew/homebrew-core/Formula/nuget.rb
invalid attribute for formula 'nuget': version (nil)
Error: Invalid formula: /usr/local/osquery/Library/Taps/homebrew/homebrew-core/Formula/gcc.rb
Unable to determine the system's glibc version
Error: Invalid formula: /usr/local/osquery/Library/Taps/homebrew/homebrew-core/Formula/fibjs.rb
invalid attribute for formula 'fibjs': version (nil)
Error: Cannot tap homebrew/core: invalid syntax in tap!

Thanks.

**Comment by jedi22** [comment]
Are you rebased on master?

**Comment by qhdwns123** [comment]
Yes, My OS ubuntu

**Comment by jedi22** [comment]
@qhdwns123 Does that pull request fix your issue?

**Comment by muffins** [comment]
This should be resolved. @qhdwns123 try rebasing off of master and see if you can `make deps` now. Going to close this issue out, but please let us know if there's still any problem! Thanks!
