### ISSUE TITLE
Flag to purge existing audit rules on startup

### ISSUE THREAD

**Issue by jaredledvina** [facebook/osquery#3468]
Currently, it appears that osqueryd will load the following rules:
```
# auditctl -l
-a always,exit -S execve
-a always,exit -S bind
-a always,exit -S connect
```

However, we've seen that if there are existing rules loaded, when starting osquery they aren't purged causing some inconsistencies across our systems. With other applications that use the kernel audit functionality, we've had the following bit in the `audit.rules`:
```
# cat /etc/audit/rules.d/audit.rules

# This file contains the auditctl rules that are loaded
# whenever the audit daemon is started via the initscripts.
# The rules are simply the parameters that would be passed
# to auditctl.

# First rule - delete all
-D

.....continue on to rules....
```

Could osqueryd have an optional flag that would configure it to purge all existing rules from the system on start? 

Current `osquery.flags` config:
```
# cat /etc/osquery/osquery.flags
--disable_audit=false
--audit_allow_config=true
--audit_persist=true
--audit_allow_sockets
--logger_plugin=syslog
--events_max=100000
--watchdog_memory_limit=350
--events_expiry=1
```

Running OSQuery 2.5.0 on CentOS release 6.9 (Final) and CentOS Linux release 7.3.1611 (Core)

Happy to provide any details I might have missed above!

**Comment by clong** [comment]
It looks like this issue can probably be closed with the introduction of the `--audit_force_reconfigure` and `--audit_force_unconfigure` flags.

**Comment by jaredledvina** [comment]
Yep, this is good to close, thanks @alessandrogario!
