### ISSUE TITLE
osquery crashing on Win10 

### ISSUE THREAD

**Issue by raviteja7** [facebook/osquery#3477]
Hello,
osqueryi crashing when querying 'interface_details' table.

I will upload the crashdump on slack channel (github not accepting it)

![osquery_crash](https://user-images.githubusercontent.com/2549509/28344187-f2b171c8-6bef-11e7-9885-2b54d580a46e.PNG)

Thanks

**Comment by ryanheffernan** [comment]
Thanks for the report. Is this occuring on master?

**Comment by raviteja7** [comment]
Yes.

**Comment by obelisk** [comment]
I can repro this.

**Comment by muffins** [comment]
Looks like @obelisk got this issue resolved. @raviteja7 let us know if it's still an issue!  Thanks again for reporting and helping to fix!

**Comment by theopolis** [comment]
PSA: Remember to link bug fixes to their bug reports! 

This is fixed by #3478.
