### ISSUE TITLE
feature request: Hardware Info table

### ISSUE THREAD

**Issue by muffins** [facebook/osquery#3490]
With mac patching issues like [10.12.6](https://www.intego.com/mac-security-blog/apple-releases-macos-sierra-10-12-6-and-more-with-security-fixes/) it might be nice to have a `hardware_info` table mentioning chipset manufacturers and firmware versions for various devices on platforms. This doesn't even need to be restricted to macos, but would likely be very helpful from a vulnerability management standpoint.

**Comment by theopolis** [comment]
I think the core-ask here was a `device_firmware` table to double check patches to BMC43xx devices. We have that implemented here: https://github.com/facebook/osquery/pull/3499

If folks would like hardware info, check out the `pci_devices`, `usb_devices`, `block_devices` and `platform_info`.
