### ISSUE TITLE
Max OSX processes start_time

### ISSUE THREAD

**Issue by hughneale** [facebook/osquery#3495]
If I run the following query on Linux I get the expected start_time (Process start in seconds since boot (non-sleeping)) of 1500967857 which is correct when I create a new process. However, on my Mac if I run the same query after a reboot it works and I get the expected start_time. Although when I put my mac to sleep it starts to drift. After 8 days I end up with a start_time of 1500344171 (141810) which is only a day and a bit. I'm fairly sure over the course of the last 8 days I've used my mac more than 1.6 days. Is there anyway to determine the correct start time? Or the amount of time the laptop has been sleeping? Or am I barking up the wrong tree? Thanks.

`SELECT p.pid, p.name, (time.unix_time - (uptime.total_seconds-p.start_time)) AS start_time, p.path, p.state FROM processes AS p, uptime, time  ORDER BY start_time DESC LIMIT 1;`

**Comment by theopolis** [comment]
I've seen the same thing, and haven't dug too deep into it. I was using `osquery_info.start_time`, which is the UNIX time when the osquery process starts, and then taking the relative difference when compared to it's `processes.start_time`.

**Comment by hughneale** [comment]
Thanks for your reply. However, I can't get your workaround to work (Though `osquery_info.start_time` is correct ). As the `start_time` for processes just differ too much between multiple system sleeps. 

Still trying to diagnose the issue. I'm also having issues with scheduled queries which don't seem to be able to figure out the difference between queries and is posting (to my remote endpoint) wildly invalid timestamps. All works fine, until the machine sleeps. I have re-produced this issue across multiple mac-books.

Thanks.

**Comment by hughneale** [comment]
> ri_proc_start_abstime is absolute time which is the time since some reference point. The reference point usually is the system boot time but this is not necessary true in all versions of OSX. For example in Sierra Mac OS 10.12 the reference point is not really the boot time. To be always accurate in our calculations we don’t assume the reference point to be the boot time and instead we calculate it by calling GetTimebaseInfo which is a wrapper for native mach_absolute_time(). That method returns the current time referenced to the needed start point. Then we can subtract the returned time from DateTime.UtcNow and we’ll get the exact reference point.

from [https://fossies.org/linux/mono/external/corefx/src/System.Diagnostics.Process/src/System/Diagnostics/Process.OSX.cs](url)

**Comment by hughneale** [comment]
Working on a PR.
