### ISSUE TITLE
macOS preferences not checking the by-host level. 

### ISSUE THREAD

**Issue by groob** [facebook/osquery#3501]
# Issue
If a preference is set at the "Current Host"(as opposed to AnyHost), then osquery will miss it. 

# Overview

If a preference was set with `CFPreferencesSetAppValue` it was set for `current user/any host`, but if the preference was set with `CFPreferencesSetValue` it might be set at the current-host/by-host level. Less common than any-host but still a possibility. 

In a [document on preferences](https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFPreferences/CFPreferences.html), apple notes that preferences could exist in any of the following domains. 

<img width="396" alt="cfpref_scopes" src="https://user-images.githubusercontent.com/1526945/28689880-2d352424-72e5-11e7-97d4-3951a74a2d17.png">

This issue is a follow up to https://github.com/facebook/osquery/issues/3083,which was addressed in #3455.

# Repro

Using the script below, we'll set the preference as `False` for `kCFPreferencesCurrentHost`, but `True` for `kCFPreferencesAnyHost`. Because CurrentHost has a higher order in the search list above, False is actually the effective value for that key.

```
#!/usr/bin/python

from Foundation import (
        kCFPreferencesAnyUser,
        kCFPreferencesCurrentUser,
        kCFPreferencesAnyHost,
        kCFPreferencesCurrentHost,
        CFPreferencesCopyKeyList,
        CFPreferencesCopyAppValue,
        CFPreferencesCopyValue,
        CFPreferencesSetValue,
        CFPreferencesAppValueIsForced,
        )


BUNDLE_ID = 'com.apple.screensaver'
key = "askForPassword"


# set current host to false
CFPreferencesSetValue(key, False, BUNDLE_ID, kCFPreferencesCurrentUser, kCFPreferencesCurrentHost)

# set any host to true
CFPreferencesSetValue(key, True, BUNDLE_ID, kCFPreferencesCurrentUser, kCFPreferencesAnyHost)
```

Run osqueryi. The reported value is the one set for `kCFPreferencesAnyHost`

```
sudo osqueryi --line 'select * from preferences where domain="com.apple.screensaver" AND key="askForPassword" AND username="victor"'
  domain = com.apple.screensaver
     key = askForPassword
  subkey =
   value = true
  forced = 0
username = victor
```

Now I will use this [this](https://gist.github.com/gregneagle/010b369e86410a2f279ff8e980585c68) script by @gregneagle to read the actual value. The script reads all the possible levels and reports the effective value as well as where it is set. 

```
python fancy_defaults_read.py com.apple.screensaver askForPassword

askForPassword: False
Type: boolean
Defined: /Users/victor/Library/Preferences/ByHost/com.apple.screensaver.xxxx.plist
```

**Comment by groob** [comment]
An additional note. I was just tinkering with the `com.apple.bluetooth PrefKeyServicesEnabled` key, by checking/unchecking the bluetooth sharing key in System Preferences. 

<img width="780" alt="screenshot 2017-07-27 17 38 47" src="https://user-images.githubusercontent.com/1526945/28693406-7672e77c-72f2-11e7-9c49-4bb061e8890b.png">

CFPreferences reports that they key is set in the ByHost level when checked in the GUI.

I am not sure, but it's likely that this behavior is default for many of the system GUI panes that the user interacts with. If so, having osquery read the CurrentHost domain seems very important if we're to rely on the table for compliance. 

Running `ls -l ~/Library/Preferences/ByHost` reveals a long list of preferences being set at that level, mostly by apple, including the `.GlobalPreferences.FA01680E-98CA-5557-8F59-7716ECFEE964.plist` plist.

**Comment by gregneagle** [comment]
Much here boils down to:
1) Do you want to know all the preferences at every level? or
2) Do you want to know the _effective_ preference for a given domain/key ?

**Comment by groob** [comment]
@gregneagle #2 

Most of it was addressed by @theopolis in #3455, but that PR did not account for ByHost domains. 
We don't need to expose what level it's set at (although would be a nice column), just the effective value.

**Comment by gregneagle** [comment]
So you should always be using CFPreferencesCopyAppValue and never CFPreferencesCopyValue.

**Comment by groob** [comment]
@gregneagle osquery runs as root though, you'd have to check the given preference as a user since CFPreferencesCopyAppValue  assumes CurrentUser, no?

**Comment by gregneagle** [comment]
Yup.

**Comment by gregneagle** [comment]
But it's the only way to be managed preferences aware.

**Comment by gregneagle** [comment]
Your table above under Overview needs a row 0 listing managed preferences.
