### ISSUE TITLE
Periodic coverity scans

### ISSUE THREAD

**Issue by spasam** [facebook/osquery#3511]
It might be beneficial to the project to setup nightly coverity scans. It is free for OSS for 28 builds per week, with a maximum of 4 builds per day. I set one up and uploaded a build output: https://scan.coverity.com/projects/osquery

This can be automated from nightly Jenkins jobs (had to disable ccache to get this working). If you (FB) would like to take over above project, please send me your email and I will make you owner.

**Comment by theopolis** [comment]
At this time we're choosing not to have automatic Coverity integration. But we do appreciate you running the tools and providing us feedback. :D
