### ISSUE TITLE
bug: block_devices size column is inaccurate

### ISSUE THREAD

**Issue by vishwa35** [facebook/osquery#3538]
According to documentation, `SELECT * FROM block_devices;` the size column should return size in bytes. On linux the unit is block size, and on darwin there is a 32bit bit truncation.

Proposed solution is to add a `block_size` column to `block_devices` and leave the Linux size column using block units. To maintain consistency, the Darwin implementation should provide the size in block sizes as well, and the conversion error needs to be corrected.

**Comment by theopolis** [comment]
Thanks for pointing that out and submitting a fix!
