### ISSUE TITLE
Provide documentation on how to uninstall osquery (on OS X, etc.)

### ISSUE THREAD

**Issue by mpathy** [facebook/osquery#3548]
I wanted to deinstall the OS X package, after I evaluated it on a Mac.
Couldnt find any information.

I guess, this should do the trick:
`sudo pkgutil --forget com.facebook.osquery`
..but it should be documented somehow (and maybe I am wrong)

**Comment by Centurion89** [comment]
This gets asked in Slack once and awhile. Stealing guidance from @groob:

```
There's no direct "uninstall" for mac pkgs. To uninstall osquery you'll have to 
a) remove all osquery files. these are  `/usr/local/bin/osquery*`, `/private/var/osquery`, `/etc/osquery/` 
b) unload any launchdaemons and remove the launchd (`com.facebook.osquery`)

you'll also need to `sudo pkgutil --forget com.facebook.osquery` which will remove the package receipt
```

**Comment by mpathy** [comment]
There should be some info in the documentation, and maybe some uninstall script..
Even better, some brew package, so it can be done with a proper package manager..

**Comment by muffins** [comment]
Totally agree that our Mac docs could be more filled out for removing osquery!  I think that on most of the Linux systems we support and Windows this process is a little easier. We also love getting PRs if you happen to already have a good methodology of removing osquery fully from the system :)

**Comment by theopolis** [comment]
I'd suggest updating this Wiki page: https://github.com/facebook/osquery/blob/master/docs/wiki/installation/install-osx.md with the uninstall directions.
