### ISSUE TITLE
OSQuery failed to build with error C1083: Cannot open include file: 'rapidjson/document.h': No such file or directory 

### ISSUE THREAD

**Issue by KarenHuang2016** [facebook/osquery#3558]
We tried to build OSQuery with VS2017 Update 2 on Windows. It failed to build with error C1083: Cannot open include file: 'rapidjson/document.h': No such file or directory. Could you please help to take a look at this? Thanks in advance!

**Reproduce steps:**
1. git clone --recursive https://github.com/facebook/osquery D:\OSQuery\src
2. Open Open a VS 2017 x64 command prompt and browse to D:\OSQuery\src
3. tools\make-win64-dev-env.bat
4. mkdir build\windows10 && pushd build\windows10
5. cmake -G "Visual Studio 15 Win64" -DCMAKE_SYSTEM_VERSION=10.0.15063.0 ..\..
6. cmake --build . --target shell --config Release -- /maxcpucount

**Actual result:**
[OSQuery_build_shell.txt](https://github.com/facebook/osquery/files/1221442/OSQuery_build_shell.txt)

D:\OSQuery\src\osquery/core/json.h(20): fatal error **C1083**: Cannot open include file: 'rapidjson/document.h': No such file or directory (s:\dd\feature\winc\src\vctools\compiler\cxxfe\sl\p1\c\p0prepro.c:1654) [D:\OSQuery\src\build\windows10\osquery\extensions\osquery_extensions.vcxproj]
D:\OSQuery\src\osquery/core/json.h(20): fatal error **C1083**: Cannot open include file: 'rapidjson/document.h': No such file or directory (s:\dd\feature\winc\src\vctools\compiler\cxxfe\sl\p1\c\p0prepro.c:1654) [D:\OSQuery\src\build\windows10\osquery\extensions\osquery_extensions.vcxproj]

**Comment by obelisk** [comment]
@muffins Can you repro this? I just tried and it built successfully.

**Comment by muffins** [comment]
Hrm, I'm having some troubles repro-ing this, and it also looks as though it might be related to your extension? Have you tried deleting the `build` directory and re-running the `.\tools\make-win64-binaries.bat` to trigger a clean build?

**Comment by KarenHuang2016** [comment]
OSQuery can be built successfully with latest reivision 6600361. Thank you!

**Comment by muffins** [comment]
@KarenHuang2016 ah perfect!  Yeah based off of the information you posted it looks like it's related to your extension. Perhaps try rebuilding your extensions after having re-run the `.\tools\make-win64-dev-env.bat`?
