### ISSUE TITLE
start_time columns for windows processes table ?

### ISSUE THREAD

**Issue by aktxyz** [facebook/osquery#3562]
With the following query, I am seeing the start_time column always set to 0 when running on windows, anyone know if this is a known limitation?

select start_time,path,name from processes;

**Comment by muffins** [comment]
Hey there, this was indeed an issue, but was resolved with #3536 and will be fixed in the next release. Let us know if this issue is persistent on master!  Thanks :)

**Comment by aktxyz** [comment]
bam - thanks !
