### ISSUE TITLE
language bindings?  looking for c#

### ISSUE THREAD

**Issue by aktxyz** [facebook/osquery#3564]
Have googled around looking for language bindings to make osquery queries, have not found much.

They may not exist or be limited, or I am going about it the wrong way (ie is the intent to run the daemon with scheduled queries and then read the log files?).

**Comment by muffins** [comment]
@aktxyz that is correct. The agent itself is typically used as a daemon monitoring system state, or an interactive shell as a command line utility. There is the possibility of leveraging the daemon via what we call [extensions](https://osquery.readthedocs.io/en/stable/deployment/extensions/) wherein one can retrieve and act on data from within third party applications, however on Windows this is still relatively limited. 

This all operates via a thrift socket that's spawned by the daemon/shell, and so long as you can speak the correct language to the thrift socket in your language you can interact with it. Currently this is only Go and C++ on Windows, but Python support exists on posix systems. Check out the extensions link for more info!  We also have a Slack I'd encourage you to checkout: https://osquery-slack.herokuapp.com/

Feel free to reopen this issue or kick another one if you'd like more info :)
