### ISSUE TITLE
"Too many open files" errors when sending to kinesis

### ISSUE THREAD

**Issue by danielpops** [facebook/osquery#3566]
`osquery_version: osqueryd version 2.6.0`
`ubuntu: 14.04 (trusty)`

We are using the Kinesis logger on the osquery 2.6 release on ubuntu trusty hosts. Occasionally we see osquery crash on certain hosts, and see the following logs in the `status` logs going to the kinesis stream:

```
[registry.cpp] table registry process_open_sockets plugin caused exception: boost::filesystem::directory_iterator::construct: Too many open files: "/proc"
[aws_util.cpp] Exception making HTTP request to URL (https://kinesis.us-west-2.amazonaws.com): eventfd_select_interrupter: Too many open files
[aws_kinesis.cpp] Kinesis write failed: Unable to connect to endpoint
```

Is there something that I can do to avoid running into this?

**Comment by danielpops** [comment]
I have a few additional questions about other status messages coming out of osquery:

`"Trying to purge" messages`
We see lots of:
* Trying to purge 18446744073708549807 logs but only found 0

And also some with a non-zero "only found" value:
* Trying to purge 18446744073708549807 logs but only found 439

Are those safe to ignore or do they indicate some systemic issue?

`"Purging buffered logs" messages`
We see lots of these:
* Purging buffered logs limit (1000000) exceeded: 18446744073709544040

Are those safe to ignore or do they indicate some systemic issue?

`"Schedule query may have failed" messages`:
* Scheduled query may have failed: <scheduled query name>

When those occur, I don't see any related status messages with any more context. Is there any way to get more information about what may have caused those queries to fail?

**Comment by jacknagz** [comment]
We have also been seeing these same messages

**Comment by danielpops** [comment]
I actually noticed at least in once instance that this didn't actually cause a crash in the osquery process. Maybe the crashes are being caused by something else. 

Are these log messages we're seeing benign? Have they been known to cause crashes in osquery? Would appreciate any insight. Thanks!!

**Comment by theopolis** [comment]
I'll ask @zwass for help on the AWS/Kinesis errors.

For the `"Schedule query may have failed"` messages, this indicates that osquery was stopped/exited while it was trying to run a query. All the information it has is that the process started to run a query, and never indicated that it had finished.

**Comment by theopolis** [comment]
The note about too-many-open files is concerning. This may mean there's a FD leak in osquery (or the way you're using it), or the file attempts to use too many concurrent FDs. Normally this would be >1024. I will check the `process_open_sockets` implementation and see if it's order of FDs it variable.

**Comment by zwass** [comment]
That AWS error is a new one to me. I am about to go off the grid for a couple weeks, and need to wrap up some other work, so I can't give this much time right now.

Based on googling for the error message, I have a feeling there is some large payload being sent and the timeout is being exceeded (https://github.com/aws/aws-sdk-cpp/issues/171).

**Comment by jacknagz** [comment]
@zwass maybe it's related to #3568

**Comment by theopolis** [comment]
See #3599 that @jacknagz referred to in #3568. I'm going to close this since that is merged. If we still see errors let's reopen and triage again.
