### ISSUE TITLE
Windows Build issue ("The C compiler identification is unknown")

### ISSUE THREAD

**Issue by dlobutters** [facebook/osquery#3567]
When following the [Windows build process](http://osquery.readthedocs.io/en/stable/installation/install-windows/#packaging-osquery) I have found on 2 computers when running '.\tools\make-win64-binaries.bat' or running cmake ../../ -G "Visual Studio 14 2015 Win64" from the build\windows10 folder that the build will fail with the following message:

Full Error Output:
c:\osquery>.\tools\make-win64-binaries.bat
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:341 (project):
  The CMAKE_C_COMPILER:

    clang

  is not a full path and was not found in the PATH.

CMake Error at CMakeLists.txt:341 (project):
  The CMAKE_CXX_COMPILER:

    clang++

  is not a full path and was not found in the PATH.

-- Configuring incomplete, errors occurred!
See also "C:/osquery/build/windows10/CMakeFiles/CMakeOutput.log".
See also "C:/osquery/build/windows10/CMakeFiles/CMakeError.log".
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: shell.vcxproj
---------------------------------------------------------------------------------------------------------------
Worked with @muffins to try and resolve but we were unsuccessful. 

What we tried:

- Removing Visual Studios on both computers and then running make-win64-dev-env.bat again to reinstall

- Removing the chocolaty folder and then then running make-win64-dev-env.bat again to reinstall

- Invoking "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\vcvars64.bat then running cmake ..\.. -G "Visual Studio 14 2015 Win64"

- cmake ../../ -G "Visual Studio 14 2015 Win64" -T v140

- tested the system PATH to ensure we could call cl, clang and clang++ as well as copy the PATH from a working computer

NOTE: One thing these computers had in common is that both chocolaty and Visual Studios were installed before following the build process. Being that chocolaty is just a folder it is unlikely that is the issue. If you had Visual Studios installed on your computer before the build process will possibly fail.

Current workaround:
Reimage or get a computer that has never had Visual Studios. So far all computers that have never had Visual Studios have no issues following the build steps.

**Comment by muffins** [comment]
I think that this issue more or less boiled down to our provisioning scripts aren't ready to handle existing installations of Visual Studio - but it should. When we first developed these scripts we decided to attempt to control the environment, however as our build system for Windows has matured I think we should encompass folks bringing their own IDE and making best efforts to identify/find the compiler - especially as we work towards moving to clang builds.

**Comment by muffins** [comment]
I ran into this issue tonight myself when I had inadvertently upgrade to VS 2017. This was pretty infuriating, and the fix ultimately was to uninstall _all_ versions of Visual Studio as well as SDK and Runtimes, and re-run our provisioning script. This got our environment set back up and builds kicked off successfully.

**Comment by realnemo** [comment]
I landed up in the same issue. This is my first time trying to build the OSQuery on windows. My system had Visual Studio 2013 pre-installed. 

C:\osquery>tools\make-win64-dev-env.bat
[+] Provisioning a Win64 build environment for osquery
<snip>
[+] Done.
Refreshing environment variables from registry for cmd.exe. Please wait...Finished..

C:\osquery>tools\make-win64-binaries.bat
-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:341 (project):
  The CMAKE_C_COMPILER:

    clang

  is not a full path and was not found in the PATH.



CMake Error at CMakeLists.txt:341 (project):
  The CMAKE_CXX_COMPILER:

    clang++

  is not a full path and was not found in the PATH.



-- Configuring incomplete, errors occurred!
See also "C:/osquery/build/windows10/CMakeFiles/CMakeOutput.log".
See also "C:/osquery/build/windows10/CMakeFiles/CMakeError.log".
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: shell.vcxproj

**Comment by muffins** [comment]
@realnemo I'll try and sort this issue out today, sorry this is happening to you :S We've definitely resolved that this issue occurs when multiple VS installations exist, so we're going to try and add some logic to the build system to derive pre-existing installations, and not bring VS community from chocolatey unless it can't find any other toolkits.

**Comment by zwass** [comment]
Following the directions for installing clang with VS2015 seemed to resolve this error for me (https://blogs.msdn.microsoft.com/vcblog/2016/03/31/clang-with-microsoft-codegen-march-2016-released/).

**Comment by muffins** [comment]
I think I've got the fix for this sorted and ready, but I'll need to do some testing and extend our `provision.ps1` script to get it fixed up. In the interim, for those encountering this issue, you can fix our build setups by changing the explicit build spec to the latest version you have installed. For me I installed Visual Studio 2017, and all that was required was changing [this line](https://github.com/facebook/osquery/blob/master/tools/make-win64-binaries.bat#L10) to be:
```
cmake ..\.. -G "Visual Studio 15 2017 Win64" -T 140
```
I'll have a full fix up, hopefully very soon, to add logic to derive these values dynamically and ensure we're building without assurances on the VS installed.

**Comment by muffins** [comment]
Hrm, that fix mentioned above was working for my laptop, however not for my desktop, will continue investigating.
