### ISSUE TITLE
Kinesis/Firehose Record Size Check Failures

### ISSUE THREAD

**Issue by jacknagz** [facebook/osquery#3568]
## Configuration
osquery version: `2.6.1`
operating system: `Mac OS Sierra`
output plugins: `aws_firehose,aws_kinesis`

## Background
Currently, the following Kinesis/Firehose messages are sending via `status` logging:

```
"Firehose write failed: Records size exceeds 4 MB limit"

"Kinesis log too big, discarding!"

"Firehose write failed: 2 validation errors detected: Value 'java.nio.HeapByteBuffer[pos=0
 lim=1045710 cap=1045710]' at 'records.<integer-number-of-records-here>.member.data' failed 
to satisfy constraint: Member must have length less than or equal to 1024000; Value 
'java.nio.HeapByteBuffer[pos=0 lim=1045662 cap=1045662]' at 'records.<integer-number-of-
records-here>.member.data' failed to satisfy constraint: Member must have length less than or 
equal to 1024000"

"Kinesis write failed: 2 validation errors detected: Value 'java.nio.HeapByteBuffer[pos=0 
lim=1058543 cap=1058543]' at 'records.<integer-number-of-records-here>.member.data' failed 
to satisfy constraint: Member must have length less than or equal to 1048576; Value 
'java.nio.HeapByteBuffer[pos=0 lim=1058496 cap=1058496]' at 'records.<integer-number-of-
records-here>.member.data' failed to satisfy constraint: Member must have length less than or 
equal to 1048576"
```

## Investigation

The [AWS documentation](http://docs.aws.amazon.com/firehose/latest/dev/limits.html) specifies the following Firehose limits:

* The maximum size of a record sent to Kinesis Firehose, before base64-encoding, is 1000 KB.
* The PutRecordBatch operation can take up to 500 records per call or 4 MB per call, whichever is smaller. 

Kinesis Streams [PutRecords Limits:](http://docs.aws.amazon.com/cli/latest/reference/kinesis/put-records.html)

* Each put-records request can support up to 500 records.
* Each record in the request can be as large as 1 MB, up to a limit of 5 MB for the entire request, including partition keys

### Kinesis Firehose Issues
1. The max reocrd size in the `aws_firehose` plugin appears to be slightly incorrect, as indicated [here](https://github.com/facebook/osquery/blob/master/osquery/logger/plugins/aws_firehose.cpp#L39-L40).  Firehose has no concept of a partition key (only Kinesis Streams), so the max can simply be `1000000` bytes.

2. There is not a check on the max batch size of 4MB (as indicated above) for a Firehose batch request.

3. The [Firehose error message](https://github.com/facebook/osquery/blob/master/osquery/logger/plugins/aws_firehose.cpp#L84) indicating a log is too big should print more information such as the log's query name and log size.  **There is also no logic to `break`/`continue` from the send function after this error message is called.**

### Kinesis Streams Issues

1. (Same as above) The [Kinesis error message](https://github.com/facebook/osquery/blob/master/osquery/logger/plugins/aws_kinesis.cpp#L108) indicating a log is too big should print more information such as the log's query name and log size.  **There is also no logic to `break`/`continue` from the send function after this error message is called.**

2. Each record should be checked for a max size of 1MB, **and each PutRecords batch should be checked for a limit of 5MB** minus the partition key prior to sending.  The former currently happens (with the subtraction of the partition key, which is unnecessary for individual records), but the latter does not, which is potentially causing the errors seen above.

**Comment by jacknagz** [comment]
cc @zwass, thanks for helping me with the initial triage!

**Comment by jacknagz** [comment]
related PR #3599 (thanks @alessandrogario!), I will resolve once we deploy the change and verify end to end

**Comment by alessandrogario** [comment]
Thanks for taking the time to test this! Please let me know if you find issues (I'm also on the osquery Slack if you prefer).

**Comment by theopolis** [comment]
I'm going to close this as #3599 is merged. If there are still errors then we can reopen and triage again.
