### ISSUE TITLE
Block Checksum Mismatch Error

### ISSUE THREAD

**Issue by jacknagz** [facebook/osquery#3570]
## Configuration

osquery version: `2.6.1`
operating system: `Mac OS Sierra`
output plugins: `aws_firehose,aws_kinesis`

## Error

Getting thousands of these error messages per day:

```"Error adding new results to database: Corruption: block checksum mismatch"```

Do we need to reset the `osquerydb`?

**Comment by theopolis** [comment]
One host or multiple?

**Comment by jacknagz** [comment]
@theopolis it's coming from 2 hosts, sending thousands of messages a day

**Comment by GMACKZWORLD** [comment]
Omg😵

**Comment by theopolis** [comment]
We've made a lot of changes and we've updated RocksDB a few times. Please re-open if you're still seeing errors like this!
