### ISSUE TITLE
packs: how to handle duplicate queries

### ISSUE THREAD

**Issue by juju4** [facebook/osquery#3575]
Hello,

There are multiple queries that are present in multiple packs.

rpm_packages, apt_sources, chrome_extensions,deb_packages: it-compliance, vuln-management
kernel_modules: it-compliance, vuln-management, incident-response, hardware-monitoring
disk_encryption, iptables, mounts: it-compliance, incident-response
kernel_info: it-compliance, hardware-monitoring, vuln-management
usb_devices: it-compliance, hardware-monitoring

Currently, when loading many packs, it seems those queries are re-executed for each pack.
is it the case?
if yes, the quick way is to remove duplicates from config but pack seems a good categorization to me that needs to be kept. 

Could osquery alias results to another if same query and same interval?

Thanks

**Comment by muffins** [comment]
I think the best approach here would be to ensure that the queries which are duplicates actually _belong_ in the packs they're residing. Some queries might merit showing up in multiple packs, so long as the values being queried match the theme of the pack.

I'd say for the packs that exist on the repo - feel free to throw up PRs correcting them and see what the rest of the community thinks. I've always been of the opinion that we provide those query packs as good examples of starting points for queries you might want to ask, but they're by no means definitive. I'd encourage you to modify them locally to match the needs of your organization. Just my 2 cents :)

**Comment by theopolis** [comment]
For a lot of tables, the queries are not re-executed, but rather the cached contents are returned. In a way, this achieves the alias concept from the perspective of saving CPU cycles. It will still return duplicated data. See the [cacheable](http://osquery.readthedocs.io/en/stable/development/creating-tables/) tables, marked within their specfiles.

I understand the concern about duplicated data when a query is run "twice". In practice, we often use the same query name, say "processes" within different packs, where the pack restricts or identifies the type of systems to run on. This makes it difficult to detect duplicate names and prevent them from running in the schedule.

I 100% agree with @muffins, in that the recommend use of the included packs is as examples. But they can absolutely use more attention and organization.

**Comment by juju4** [comment]
I already use customized pack but it's mostly complimentary for example a snapshots pack or some docker pack.
AFAIC, categorization in current packs is good.

If cached content is used, that's perfect.
I just need to customize pack to also avoid duplicate in logging backend

Thanks for the quick feedback!
