### ISSUE TITLE
os query remote execution

### ISSUE THREAD

**Issue by anishvarghese** [facebook/osquery#3582]
Hello Team,
     I am new in osquery, let me know how we can execute osqueries  from Machine B using  Machine A (where osquery server installed).

**Comment by muffins** [comment]
Hey @anishvarghese, you might wanna check out the [Slack](https://osquery-slack.herokuapp.com/) for questions such as these. In short, there is no way to connect from one host running the osquery daemon to another in an ad-hoc fashion.

Typically the way this is accomplished is via a service running the osquery distributed capability (currently this is doorman, Kolide, and Uptycs to name just a few), wherein you can specify the query you wish to run on a specified host, and the server takes care of issuing the distributed query. Hop on the Slack and ask this question for more information, as there's quite a few people who have deployed this at their enterprise.
