### ISSUE TITLE
ERROR: {Firehose,Kinesis} write failed: Signature expired:...

### ISSUE THREAD

**Issue by mime-frame** [facebook/osquery#3593]
**Overview**

We're seeing errors like the following:

```

"Firehose write failed: Signature expired: 20170821T052717Z is now earlier than 20170821T054443Z (20170821T054943Z - 5 min.)
"Firehose write failed: Signature expired: 20170821T041102Z is now earlier than 20170821T045027Z (20170821T045527Z - 5 min.)
"Kinesis write failed: Signature expired: 20170821T192400Z is now earlier than 20170822T011221Z (20170822T011721Z - 5 min.)
"Firehose write failed: Signature expired: 20170820T063520Z is now earlier than 20170820T083041Z (20170820T083541Z - 5 min.)
```

It appears this is caused by time drift, which is common in many environments.

**Fix**

Regardless of host time drift, signatures should not fail

**Details**
- osquery v2.6.1
- macOS devices

**Comment by theopolis** [comment]
Has this been fixed with recent updates to AWS plugins?

**Comment by mime-frame** [comment]
We're almost at 100% rollout, need another week or two to confirm

**Comment by theopolis** [comment]
It's been a while since v2.6.1, please let me know if you're still seeing this error and we can re-open!
