### ISSUE TITLE
Improve: System performance limits exceeded warning and handling

### ISSUE THREAD

**Issue by mime-frame** [facebook/osquery#3604]
**Overview**

Example log:

`W0824 23:30:08.092156  7210 watcher.cpp:250] osqueryd worker (7211): System performance limits exceeded`

This denotes the watchdog limits were exceeded, as outlined here: http://osquery.readthedocs.io/en/stable/installation/cli-flags/#daemon-control-flags

Unfortunately, the warning doesn't say what aspect of the criteria was violated. Was it memory or was it CPU?

Assuming I'm reading the code correctly, it appears that warning means the service gets disabled too: https://github.com/facebook/osquery/blob/master/osquery/core/watcher.cpp#L436-L438, which also isn't clear in the warning.

This raises more questions - is is disabled forever? How does one re-enable it?

Lastly, there doesn't appear to be any special handling / last ditch effort attempts to ensure that this warning log is sent to defined outputs when performance limits are hit, resulting in system owners never knowing this issue is actually happening. 

**Proposal** 

- Update the warning to denote CPU or memory and which retry #
- Update the warning to denote the service is being disabled (if that's the case)
- Update the docs to explain what service disablement means and what one is supposed to do about it
- When performance limits are hit, make a better effort to send the warning log to defined outputs vs. letting it get gobbled up / thrown away

**Comment by theopolis** [comment]
We've not differentiated the reasons why a worker or extension will be forcefully stopped. Those are sent to the watchdog's `stderr`. For some platform configurations, e.g., systemd, the `stderr` can be found in journald. We can improve this with a call to `systemLog`.

There's nothing in the watchdog that will disable the service. There was another issue (#3931) related to scheduled queries with `removed: False` that was causing the worker and watcher to stop, meaning the launch daemon or service would exit. My guess is, that observation was captured here, and should now be fixed.

We should also enforce a (maybe configurable) max delay. I don't want a death-by-1000 respawns to push out the max delayed time past 10 minutes. In other words we should try to accommodate a worker that respawns often. Something like a maximum of 10mins waiting to respawn sounds tolerable.
