### ISSUE TITLE
Link with jemalloc by default

### ISSUE THREAD

**Issue by thedrow** [facebook/osquery#3605]
jemalloc is a much more effiecient allocator and since we have some threads it will improve the overall performance of osquery.
jemalloc 5.0 dropped support for valgrind so we'd need to adjust our profiling tools.
jemalloc is not supported on Windows as far as I know so we'd need to make jemalloc an optional dependency that is only linked to osquery on POSIX systems.

**Comment by theopolis** [comment]
If we do this we'll need to make sure to limit the number of arenas, or provide this as a configuration option with a default of `1` for example. ;)

**Comment by thedrow** [comment]
Why do we need to limit the number of arenas?

**Comment by theopolis** [comment]
We had some trouble with this on Homebrew, see the deadlocking from #3632.

**Comment by thedrow** [comment]
This should already be fixed. https://github.com/jemalloc/jemalloc/pull/954
Is it possible that the OP in #3632 had an older version of jemalloc?

**Comment by thedrow** [comment]
Won't fix.
