### ISSUE TITLE
ERROR: RocksDB - No space left on deviceAccumulated background error counts

### ISSUE THREAD

**Issue by mime-frame** [facebook/osquery#3620]
**Overview**

Example:

`RocksDB: [ERROR] Waiting after background flush error: IO error: No space left on device/var/osquery/osquery.db/373224.sst: No space left on deviceAccumulated background error counts: 0`

Details:
- osquery v2.4.2
- Ubuntu

**Comment by theopolis** [comment]
Is the disk filled? Hehe?
