### ISSUE TITLE
Port not available in iptables table

### ISSUE THREAD

**Issue by mew1033** [facebook/osquery#3621]
The iptables (https://osquery.io/docs/tables/#iptables) doesn't include the port. Not all iptables rules use port, but many do. Is there any way to add in port information?

**Comment by micheal-o** [comment]
I will work on this.

**Comment by mew1033** [comment]
Awesome! Thanks!
@fossam, do you have anything else you'd like to see in here besides the port?

**Comment by fossam** [comment]
If possible I'd like to see fully detailed information that gives a clear picture of all iptables rules in all the tables and their order at a time the query ran. But I know that representing this in sql tables is a tall order. Command that produces the information is `iptables -L -v -n --line -t <table>` or alternatively `iptables-save` .

**Comment by micheal-o** [comment]
@fossam Please kindly create a separate issue for your feature request and it will be looked into. @mew1033 Your request has been implemented and this issue can be closed.
