### ISSUE TITLE
ERROR: Error adding new results to database: <unspecified file>(1): invalid code sequence

### ISSUE THREAD

**Issue by mime-frame** [facebook/osquery#3631]
**Overview**

We're seeing the following on macOS devices running osquery v2.6.1

`scheduler.cpp`:

`Error adding new results to database: <unspecified file>(1): invalid code sequence`

with a severity level of `2`

**Desired outcomes**

- Understanding what this means
- Either better handling it or outputting an error that explains what it means and what are the necessary steps to combat it
- Verifying the severity level is correct

**Comment by theopolis** [comment]
It's been a while since v2.6.1. Please let me know if you're still seeing this error and we can re-open!
