### ISSUE TITLE
Document which version of psutil is required for utils.py

### ISSUE THREAD

**Issue by jaredledvina** [facebook/osquery#3657]
Hi! I'm trying to give `profile.py` a shot on CentOS 6 w/ Python 2.6. I have installed `python-psutil`:
```
Installed Packages
Name        : python-psutil
Arch        : x86_64
Version     : 0.6.1
Release     : 1.el6
Size        : 354 k
Repo        : installed
From repo   : ptepel-beta
Summary     : A process and system utilities module for Python
URL         : http://psutil.googlecode.com/
License     : BSD
Description : psutil is a module providing an interface for retrieving information on all
            : running processes and system utilization (CPU, memory, disks, network, users) in
            : a portable way by using Python, implementing many functionalities offered by
            : command line tools such as: ps, top, df, kill, free, lsof, free, netstat,
            : ifconfig, nice, ionice, iostat, iotop, uptime, pidof, tty, who, taskset, pmap.
```

However, when running `python profile.py --verbose --config /etc/osquery/osquery.conf --shell /usr/bin/osqueryi` I get the following traceback:
```
Traceback (most recent call last):
  File "profile.py", line 364, in <module>
    timeout=args.timeout, count=args.count, rounds=args.rounds
  File "profile.py", line 200, in profile
    result = run_query(shell, query, timeout=timeout, count=count)
  File "profile.py", line 143, in run_query
    ], timeout=timeout, count=count)
  File "/root/utils.py", line 166, in profile_cmd
    while p.is_running() and p.status() != psutil.STATUS_ZOMBIE:
TypeError: 'constant' object is not callable
```

I assume it's because the version of `psutil` I'm installing is way too old. Any chance we can update https://github.com/facebook/osquery/blob/master/requirements.txt#L7 with the minimum version required for this to work? 

Just noting that my environment does not have access to PyPi for pip installing the latest `psutil` package from https://pypi.python.org/pypi/psutil

**Comment by theopolis** [comment]
Interesting, I'm tried to trace the changes to `Process::status` back and found the first release was `0.2.1`, though `Process::is_running` was introduced in 2014 with version `2.0.0` so I'm guessing that's the winner. Do you mind installing version `2.0.0` or later and seeing if that works?

**Comment by jaredledvina** [comment]
Ah cool, thanks for running that down! Let me give `2.0.0` a shot and see if that works.

**Comment by jaredledvina** [comment]
The easiest way for me to verify this was to jump on a CentOS 7 box which from EPEL can install version `2.2.1` of `python-psutil`:
```
Installed Packages
Name        : python-psutil
Arch        : x86_64
Version     : 2.2.1
Release     : 1.el7
Size        : 498 k
Repo        : installed
From repo   : ptepel-beta
Summary     : A process and system utilities module for Python
URL         : http://psutil.googlecode.com/
License     : BSD
Description : psutil is a module providing an interface for retrieving information on all
            : running processes and system utilization (CPU, memory, disks, network, users) in
            : a portable way by using Python, implementing many functionalities offered by
            : command line tools such as: ps, top, df, kill, free, lsof, free, netstat,
            : ifconfig, nice, ionice, iostat, iotop, uptime, pidof, tty, who, taskset, pmap.
```

So, that works for our CentOS 7 boxes! \o/ 
I'll try to see if I can modify `profile.py` on our end to work with `psutil` v0.6.1. Otherwise, I'll have to adventure down the rabbit hole of getting a newer version into our internal repo's...

Thanks for looking into this @theopolis!
