### ISSUE TITLE
empty process_events table in 2.7.0 on macOS using kernel extension

### ISSUE THREAD

**Issue by doe-john** [facebook/osquery#3659]
After upgrading from 2.5.0 to 2.7.0 on macos we lost process events. kernel extension has the same version as binary. But scheduled queries return 0 rows.

**Comment by theopolis** [comment]
We're preparing to completely remove the kernel extension for 10.13. Is it possible to transition to the BSM Audit process auditing for macOS? http://osquery.readthedocs.io/en/stable/deployment/process-auditing/#macos-process-auditing
