### ISSUE TITLE
Detect MacOS auto update is enabled

### ISSUE THREAD

**Issue by bshepard211** [facebook/osquery#3666]
Is there a way to detect if auto update is enabled on MacOS?

**Comment by muffins** [comment]
@obelisk or another resident mac expert - thoughts? I'm not entirely sure what tables one might query for that.

**Comment by ternus** [comment]
Pretty sure it's `/Library/Preferences/com.apple.commerce.plist` -- you can check if updates are enabled with `defaults read /Library/Preferences/com.apple.commerce AutoUpdate`.

**Comment by theopolis** [comment]
Right, use:
```sql
select * from plist where path = '/Library/Preferences/com.apple.commerce.plist' and key = 'AutoUpdate'
```
