### ISSUE TITLE
Decorators in distributed queries

### ISSUE THREAD

**Issue by securityclippy** [facebook/osquery#3669]
Currently (2.7) it appears that decorators are not including when returning distributed query results to the TLS server.  This seems like an expected behavior, so I'd like to get some clarification around if this is working as intended or is a bug.  

Perhaps (yet another) flag could be implemented to toggle decorators on distributed queries?

**Comment by mattjane-okta** [comment]
closing.  As discussed in office hours, this is a thing that should happen.  Opened issue 3718 as action
