### ISSUE TITLE
Is windows supporting FIM events?

### ISSUE THREAD

**Issue by nishitm** [facebook/osquery#3682]
I checked and found out that file_event table is not available for windows machine. So can anyone tells me a way to monitor file_events on windows machine using osquery.

**Comment by muffins** [comment]
We don't currently have this feature ported and this isn't a current priority for us, so it might be a while before the feature lands on Windows. That being said, we're always excited about folks in the open source community throwing up PRs with features such as this :) It's on the roadmap for the project, but it might be a while before any of us get time to land the feature.
