### ISSUE TITLE
Convert Linux process_events mode column to octal

### ISSUE THREAD

**Issue by Centurion89** [facebook/osquery#3699]
The events on linux systems from process_events log the "mode" column in decimal. However, the OpenBSM stack on OSX appropriately converts it to octal. This should be consistent (octal) across operating systems.

Context in Slack
https://osquery.slack.com/archives/C08V7KTJB/p1505428514000089

**Comment by micheal-o** [comment]
Hi, I will like to work on this but I have few questions, as I am not yet familiar with the code base. 
First, I am unable to access the context in slack link you posted. Also, I checked out the process_events.cpp code and I think the change can be made here. But not sure If this is right. Please I will like to know the expectation for this change? Thanks

**Comment by micheal-o** [comment]
I am working on this.

**Comment by muffins** [comment]
@micheal-o are you participating in #hacktoberfest? Would you like us to tag this up for you?

**Comment by micheal-o** [comment]
Yes, I am. Please do, thanks.

**Comment by micheal-o** [comment]
PR #3800

**Comment by uptycs-nishant** [comment]
#3825
