### ISSUE TITLE
display binary signature status

### ISSUE THREAD

**Issue by mtmcgrew** [facebook/osquery#370]
Anywhere a binary is displayed (like in the processes table) it would be awesome if it checked the signature status of the binary. This would allow checking for processes that should be signed but are not.

Displaying some information from here would be great

#codesign --display --verbose=4 /bin/ls
Executable=/bin/ls
Identifier=com.apple.ls
Format=Mach-O thin (x86_64)
CodeDirectory v=20100 size=261 flags=0x0(none) hashes=8+2 location=embedded
Hash type=sha1 size=20
CDHash=b583404214ff4e0bee6e0662731bff5555c24621
Signature size=4097
Authority=Software Signing
Authority=Apple Code Signing Certification Authority
Authority=Apple Root CA
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=1 size=60

**Comment by theopolis** [comment]
Using a master task of issues: https://github.com/facebook/osquery/issues/619
