### ISSUE TITLE
windows: relax "safe" permissions for service run

### ISSUE THREAD

**Issue by muffins** [facebook/osquery#3704]
Currently we require an explicit `Deny-Write` ACL for the Everyone group on Windows systems for the binary to be considered "safe", however these restrictions are rather intense, and not exactly needed. A good counter-case here is for traditional Windows installations it's assumed a user requires elevated or administrative permissions to modify the installation, yet if these permissions are obtained an attacker already has privilege to munge the installation. As such we should relax the permissions required to match that of a traditionally installed Windows service, thus alleviating some of the overhead and headache of deploying osquery on Windows.

**Comment by muffins** [comment]
Nearly got this sorted. The last component is fixing up how `platformChmod` behaves, as our tests are currently failing because it always adds the Deny-Write ACE

**Comment by theopolis** [comment]
Fixed with #3727
