### ISSUE TITLE
packs: Windows specific attack packs

### ISSUE THREAD

**Issue by muffins** [facebook/osquery#3725]
This issue is concerned with writing query packs to look for malware or bad behavior on Windows platforms. We have quite a few [generic packs](https://github.com/facebook/osquery/tree/master/packs) tailored towards catching attack like behavior, but as we continue to develop more Windows features and tables we could use more Windows specific packs and configurations. Let's use this issue to track out adding packs or configs that make monitoring Windows specifics easier with an out-of-box osquery installation. You'll want to start by making a `windows-attacks.conf` file, similar to the `osx-attacks.conf`, and make use of
```
osqueryi --config_path=C:\Path\To\windows-attacks.conf --config_check
```
to help ensure the pack is properly JSON formatted.

**Comment by micheal-o** [comment]
Hi, I am new to osquery and I think this would be a nice first issue. Is there a minimum number of queries required for the windows-attacks.conf PR?

**Comment by micheal-o** [comment]
I am working on this.

**Comment by muffins** [comment]
Thanks for letting us know @micheal-o!

**Comment by muffins** [comment]
#3754 addresses this.
