### ISSUE TITLE
TLS distributed queries pull from osqueryd cache & don't include live data

### ISSUE THREAD

**Issue by Centurion89** [facebook/osquery#3733]
Platform: OSX 10.12.6
Osquery Versions: 2.6.1, 2.7.0

I encountered this bug today while doing some testing. The ultimate problem here is that the TLS endpoint appears to only pull results from the osquery cache, which leads to data potentially being missed. For example, running the same query with `osqueryi` and a distributed query from a TLS endpoint leads to inconsistent results. 

I think this is a fairly high-priority bug to fix because I was under the assumption that a TLS distributed query was a snapshot in time and produced 100% live results. However, this issue shows that if the event is not in the cache yet, it will not be seen by a distributed query.

Here's how to repro on OSX:

1. Create a fake malicious plist in `/Users/username/Library/LaunchAgents/com.pwned.plist` with the following content:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KeepAlive</key>
	<dict>
		<key>SuccessfulExit</key>
		<false/>
	</dict>
	<key>Label</key>
	<string>com.pwned</string>
	<key>LimitLoadToSessionType</key>
	<string>Aqua</string>
	<key>ProgramArguments</key>
	<array>
		<string>/bin/hostname</string>
	</array>
	<key>RunAtLoad</key>
	<true/>
</dict>
</plist>
```
2. You may have to `sudo chgrp <groupname> com.pwned.plist` to match the group permissions of other launchagents in that folder
3. `launchctl load com.pwned.plist`
4. 
```
sudo osqueryi
osquery> .mode line
osquery> select * from launchd where name = 'com.pwned.plist' or name = 'com.openbundle.plist' or name = 'com.adobe.reader.plist';
               path = /Users/user/Library/LaunchAgents/com.pwned.plist
               name = com.pwned.plist
              label = com.pwned
              <snip>
```
This step **should** return results

5. Run the same query using a TLS distributed query - it returns 0 results, which is inconsistent with what osqueryi displayed. TLS dump output shows that it's reading from the cache:
```
I0926 12:05:15.918933 132849664 distributed.cpp:127] Executing distributed query: kolide_distributed_query_25: select * from launchd where name = 'com.pwned.plist' or name = 'com.openbundle.plist' or name = 'com.adobe.reader.plist';
I0926 12:05:15.919761 132849664 tables.cpp:194] Retrieving results from cache for table: launchd
I0926 12:05:15.954036 132849664 tables.cpp:194] Retrieving results from cache for table: launchd
I0926 12:05:15.989285 132849664 tables.cpp:194] Retrieving results from cache for table: launchd
```

**Comment by mattjane-okta** [comment]
Just replicated using a custom TLS endpoint.  No bueno =(

**Comment by theopolis** [comment]
Neat! Good find
