### ISSUE TITLE
System Call monitoring using osquery

### ISSUE THREAD

**Issue by nishitm** [facebook/osquery#3747]
Hi,

I have read issue [#128](https://github.com/facebook/osquery/issues/128). I wanted to ask that does current version of osquery supports system call monitoring? If yes then how to enable it(any configuration manual)?

Thanking you in advance.
Nishit

**Comment by muffins** [comment]
@nishitm hey there, sorry for the delay! Firstly I'd encourage you to [jump into our Slack](https://osquery-slack.herokuapp.com/), as it can often elicit much faster responses to questions :)

Secondly osquery is [capable of using Linux Audit](https://osquery.readthedocs.io/en/stable/deployment/process-auditing/#linux-process-auditing) for recording process events on the system, but it's likely not going to give you syscall level granularity if that's what you're needing. Inside of Slack we have a `#process-auditing` channel where you might get some better answers.
