### ISSUE TITLE
Feature Request: display error message if flagfile cannot be parsed

### ISSUE THREAD

**Issue by Centurion89** [facebook/osquery#3749]
Current behavior: specifying a flagfile with invalid flags/content does not generate any errors, even when running osquery in verbose mode

Expected behavior: An error message should be displayed to the user saying something along the lines of "The specified flagfile could not be validated". Bonus points if it can tell the user what line the problem is on or which flag is invalid.

**Comment by theopolis** [comment]
I’ll investigate, but we inherit this functionality from GFlags. I remember looking for this before but will check again and more closely with the current code in their repo.

**Comment by spasam** [comment]
Are you expecting same behavior for both osqueryi and osqueryd? This might be appropriate for osqueryi and for osquerd probably a warning?

**Comment by muffins** [comment]
@spasam yeah this was both the shell and daemon, and since `2.8.0` the deamon and shell are the same binary. I think the biggest issue was just the user experience of not having explicit notice that the flag file being loaded is not what you're expecting.

**Comment by spasam** [comment]
@muffins Thanks. Understand the binary part but in the code we differentiate between shell vs daemon.
* Logging error in both cases make sense whether the flag is specified on command line or from flagfile
* Exiting the shell with error when incorrect flag/value is specified is also appropriate
* My only concern is if daemon exits when it sees unrecognized flag/incorrect value. Especially if the flag/value came from config endpoint

**Comment by theopolis** [comment]
If the config contains an unknown flag as an `option` you'll see a warning: https://github.com/facebook/osquery/blob/master/osquery/config/parsers/options.cpp#L66

**Comment by theopolis** [comment]
It seems like invalid flags defined in a flagfile cannot be detected: https://github.com/gflags/gflags/blob/aa2d0f7b4ed11849f40c3a1dc573ac331ebdaebd/src/gflags.cc#L1338 from what I can tell we'd need to implement our own flagfile scanning and parsing to detect these.
