### ISSUE TITLE
Jekyll docs still on osquery.io

### ISSUE THREAD

**Issue by rmetzler** [facebook/osquery#3755]
A copy of the original Jekyll docs is still hosted on https://osquery.io/docs/home/
because the of the files here https://github.com/facebook/osquery/blob/master/docs/_docs/index.md

I would suggest to improve the website further. As a user I would be very interested in seeing the difference between tables in 2.8.0 vs 2.7.0

**Comment by theopolis** [comment]
That's intentional to help the community get started with writing documentation. One goal of moving to an in-repo hosted Jekyll is that the osquery user base would start writing documentation, news, guides, etc. :)
