### ISSUE TITLE
Windows osqueryi: hash table returning inconsistent values

### ISSUE THREAD

**Issue by Centurion89** [facebook/osquery#3756]
OS: Win10
Osquery Version: 2.8.0

I noticed today that the hash table in osquery was returning inconsistent results:

**Example:** Hashing a single file:
`select path, sha256 from hash where path="C:\windows\system32\calc.exe";`
Repro steps: Run the above query multiple times, observe that the hash value changes with each query:
```
osquery> select path, sha256 from hash where path="C:\windows\system32\calc.exe";
+------------------------------+------------------------------------------------------------------+
| path                         | sha256                                                           |
+------------------------------+------------------------------------------------------------------+
| C:\windows\system32\calc.exe | c4337e09c6ee8625065dcdfeac56f099345a2bb329813f227718b45e1f7f04a0 |
+------------------------------+------------------------------------------------------------------+
osquery> select path, sha256 from hash where path="C:\windows\system32\calc.exe";
+------------------------------+------------------------------------------------------------------+
| path                         | sha256                                                           |
+------------------------------+------------------------------------------------------------------+
| C:\windows\system32\calc.exe | b093fd472121cda0bbb1e0079479de36325f1b2faa7fda54c4f757565572fe1d |
+------------------------------+------------------------------------------------------------------+
osquery> select path, sha256 from hash where path="C:\windows\system32\calc.exe";
+------------------------------+------------------------------------------------------------------+
| path                         | sha256                                                           |
+------------------------------+------------------------------------------------------------------+
| C:\windows\system32\calc.exe | b093fd472121cda0bbb1e0079479de36325f1b2faa7fda54c4f757565572fe1d |
+------------------------------+------------------------------------------------------------------+
```

In the event that you are not able to repro the above (it seems to be intermittent), this query reliably reproduces if run multiple times in succession:
`select path, sha256 from hash where path="C:\windows\system32\sethc.exe" OR path="c:\windows\system32\utilman.exe" OR path="c:\windows\system32\osk.exe" OR path="c:\windows\system32\narrorator.exe" OR path="c:\windows\system32\magnify.exe" OR path="c:\windows\system32\displayswitch.exe";`

**Comment by Centurion89** [comment]
Was able to repro successfully from another Win10 hosts. Unclear at the moment whether or not osqueryd is affected.

**Comment by muffins** [comment]
Can confirm, I can repro this on my setup also:
```
osquery> select md5, sha1, sha256 from hash where path='C:\Windows\system32\calc.exe';
   md5 = ec6318cd3c84279960c78873dc7ce3f0
  sha1 = 701bc755d6e7305e071709687a1b0763b67e2a27
sha256 = 6ff3f4054694c72926bdc5e987f4fa33d731bb5cb2c41642c4792f2edaabac9f
osquery> select md5, sha1, sha256 from hash where path='C:\Windows\system32\calc.exe';
   md5 = 4824350cf8f2e0e6238f3c357ffce8bf
  sha1 = 8f7d132067896aeb45f0d90a68b84fc2bfb81872
sha256 = c4337e09c6ee8625065dcdfeac56f099345a2bb329813f227718b45e1f7f04a0
osquery> select md5, sha1, sha256 from hash where path='C:\Windows\system32\calc.exe';
   md5 = 4673c27fdcab6166578a1863060d83ff
  sha1 = 4a2446ee9651d90ac6c5613bddf416df197f6401
sha256 = b093fd472121cda0bbb1e0079479de36325f1b2faa7fda54c4f757565572fe1d
osquery> select md5, sha1, sha256 from hash where path='C:\Windows\system32\calc.exe';
   md5 = 4673c27fdcab6166578a1863060d83ff
  sha1 = 4a2446ee9651d90ac6c5613bddf416df197f6401
sha256 = b093fd472121cda0bbb1e0079479de36325f1b2faa7fda54c4f757565572fe1d
```

**Comment by mike-myers-tob** [comment]
It seems like the behavior is related to the volume of your query. Querying a directory, even a small one, shows it returning the same hash for many of the files.

`osquery> select md5, sha1, sha256 from hash where directory='C:\Windows\';
+----------------------------------+------------------------------------------+------------------------------------------------------------------+
| md5                              | sha1                                     | sha256                                                           |
+----------------------------------+------------------------------------------+------------------------------------------------------------------+
| d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 |
| ad424b832a408f096d7db6b2138d258b | bb34796d404788b914c01da85f7a95453564d681 | f5b73d54a5fdab8160a1a42722ac63f4e5e4dd6ef1b6cc15b4780c913744035a |
| d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 |
| 0251b2852bc1f1f344c24c9896036e43 | 9b319ed0d2da0fcd5dc6c06b7d5798ea5d232ef2 | 4b58885b96f9239b5573796372df7b5abee3bc88fbdd7e6dd7cc817af3ccd7a0 |
| d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 |
| d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 |
| d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 |
| d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 |
| d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 |
| 641d94d8f94a891cd71edb9526537b99 | dbb9bc39b12644c3281718d4e2869210dab3a4af | 9dc73c8b044af2bf72273b29aaa6ae40c8bd682a9c812b5bcfec24eb02a90a30 |
| d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 |
| d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 |
| dcc07fe2003aad34bcdd286b4d41804b | b0dc7edaef562bc8b7e2338068b4e65d5813305b | bb19e02d1b46860f7e3f638bde9371c883c787ab3189e704cccdd06a499e7a06 |
| d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 |
| fa05a6649889a11afef315fe0109a1f1 | 524aeb8ee53411d395cf0de76bb72e2442734957 | 4b369e1732bc5bad2e5c81838f98195d3420db973173f1a018773b90044025b1 |
| d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 |
| d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 |
| 23cf8138f49416231807e6de371fb9e6 | 973672eeae5a05447e47395cde37e8121b7c90fe | 6b3d6e268dcb76e175a7db3d9e031349ab2c32654c7e57581a851e64dd6214ab |
| c844ca459f3b209329984772269b6e56 | 3e9d904e01a9c0f57a937f532af7f2f11aef0dee | 7d592c61d98abf019ad7c47fb074f9c25a58149ceaf536005306d9d9ed2c1d01 |
| 038356387332650843bcb352bb89a101 | 3b8d3231499998ba9ad0365c92276f7704c36395 | 492c9b102256321fb5598ff87ed5bccab8159f36dd8416ce4011ffbf5e96048d |
| d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 |
| d41d8cd98f00b204e9800998ecf8427e | da39a3ee5e6b4b0d3255bfef95601890afd80709 | e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 |
+----------------------------------+------------------------------------------+------------------------------------------------------------------+`
