### ISSUE TITLE
path on darwin launchd table not acting as it should

### ISSUE THREAD

**Issue by barn-stripe** [facebook/osquery#3760]
using `like` on the `path` column doesn't appear to work (it's the primary key, if that's relevant).

```
osquery> select count(*) from launchd where name like 'com.apple.%';
+----------+
| count(*) |
+----------+
| 590      |
+----------+
```

so we have a few in there, but if we try using path instead of name:

```
osquery> select count(*) from launchd where path like "/System/%";
+----------+
| count(*) |
+----------+
| 0        |
+----------+
```

if we just do `select count(*) from launchd where path like "%";` we still get 0 results.

Tried this on 2.7.0 and 2.8.0, no difference.

There are a number of packs using this type of query too, which is concerning.

**Comment by theopolis** [comment]
Interesting behavior, from a quick look at the implementation: https://github.com/facebook/osquery/blob/master/osquery/tables/system/darwin/launchd.cpp the intended behavior is for the `LIKE` expression to return results.

**Comment by uptycs-nishant** [comment]
#3816
