### ISSUE TITLE
Unable to detect osquery platform: ./tools/get_platform.py failed

### ISSUE THREAD

**Issue by micheal-o** [facebook/osquery#3810]
I am trying to build osquery on an Ubuntu system but I keep getting this error when I run "make".
-- Unable to detect osquery platform: ./tools/get_platform.py failed
CMake Error at CMakeLists.txt:83 (message):
  Cannot proceed without knowing the build platform

I ran "uname -s" and it returned "Linux". Please any suggestions?

**Comment by spasam** [comment]
I have seen this. Do: `chmod +x tools/get_platform.py`

**Comment by micheal-o** [comment]
@spasam It's still failing.

**Comment by spasam** [comment]
What do you get for:
`python tools/get_platform.py `

**Comment by micheal-o** [comment]
ubuntu;xenial

**Comment by spasam** [comment]
Not sure what is going on. I saw similar issues recently and chmod fixed it for me (not sure if it was necessary because py was not directly invoked). Can you run make in verbose mode and see what's going on?

**Comment by micheal-o** [comment]
@spasam Thanks for your suggestions. I ran make in verbose mode, below is the output:

GNU Make 4.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'Makefile'...
Updating goal targets....
Considering target file 'all'.
 File 'all' does not exist.
  Considering target file '.setup'.
   File '.setup' does not exist.
   Finished prerequisites of target file '.setup'.
  Must remake target '.setup'.
  Successfully remade target file '.setup'.
 Finished prerequisites of target file 'all'.
Must remake target 'all'.
-- Unable to detect osquery platform: ./tools/get_platform.py failed
CMake Error at CMakeLists.txt:83 (message):
  Cannot proceed without knowing the build platform

Makefile:123: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by micheal-o** [comment]
@spasam Thanks for your suggestions.
It works now, I saw the following when I ran make in verbose mode:
if [ ! -d build/xenial ]; then \
	echo "The build directory cannot be used: build/xenial"; \
	echo "Consider: make distclean; make"; \
	false; \
fi
I ran the command "make distclean; make" and it worked.

**Comment by spasam** [comment]
This is what I was going to suggest:

* make distclean depsclean sysprep
* make

**Comment by micheal-o** [comment]
Thanks. Issue resolved.
