### ISSUE TITLE
[Feature request] SSL cert table for linux [2/3]

### ISSUE THREAD

**Issue by friedbutter** [facebook/osquery#3812]
We would like to have a table called ssl_cert. The table should have the following schema:

```
issued_common_name
issued_organization
issued_organization_unit
issued_serial_number
issuer_cn
issuer_organization 
issuer_organization_unit
valid_from 
valid_to 
sha256_fingerprint
sha1_fingerprint
```
How to use it:

```
select * from ssl_cert where domain = 'www.facebook.com';
```

It will fetch the certificate from the domain and parse out the cert. 

You should use openssl lib since it's on mac/linux and windows.

**Comment by muffins** [comment]
As this implementation should be so similar to the MacOS one (**should** be), we'll track the progress for this issue in #3811
