### ISSUE TITLE
[Feature request] SSL cert table for windows

### ISSUE THREAD

**Issue by friedbutter** [facebook/osquery#3813]
We would like to have a table called ssl_cert. The table should have the following schema:

```
issued_common_name
issued_organization
issued_organization_unit
issued_serial_number
issuer_cn
issuer_organization 
issuer_organization_unit
valid_from 
valid_to 
sha256_fingerprint
sha1_fingerprint
```
How to use it:

```
select * from ssl_cert where domain = 'www.facebook.com';
```

It will fetch the certificate from the domain and parse out the cert. 

You should use openssl lib since it's on mac/linux and windows.

**Comment by muffins** [comment]
#3811 is tracking the progress of building the certs table for Posix, however we'd like this functionality on Windows as well. It **should** be the case that you can close out #3811, and this issue will simply be checking that the code ports to Windows. PM me for more details on Slack!

**Comment by muffins** [comment]
I have a branch inbound for this.
