### ISSUE TITLE
osquery executes queries more times than it says in the schedule

### ISSUE THREAD

**Issue by Chrisbuuren** [facebook/osquery#3815]
Hello, I have a small problem, i have osquery installed on couple  of machines and on some hosts oquery executes the queries at random time intervals such as 5/10/11/ minutes.
All my nodes get the config via **--config_tls_endpoint=/config**. 
Osquery version: **osqueryd version 2.4.6**

The config looks something like that:

> {'packs': {}, 'schedule': {u'uptime': {'platform': u'all', 'version': u'', 'snapshot': False, 'description': u'Track time passed since last boot.', 'query':u'select * from uptime; ', 'removed': False, 'interval': 10800, 'value': u''}, u'os_version': {'platform': u'all', 'version': u'', 'snapshot': False, 'description': u'A single row containing the operating system name and version.','query': u'select * from os_version;', 'removed': False, 'interval': 10800, 'value': u''} 'file_paths': {}}

And the queries on the machines is  made like this:

> Oct 10 10:49:16 hostname osqueryd: I1010 10:49:16.815779 27995 scheduler.cpp:73] Executing scheduled query uptime: select * from uptime;
> Oct 10 11:05:44 hostname osqueryd: I1010 11:05:44.446658 27995 scheduler.cpp:73] Executing scheduled query uptime: select * from uptime;
> Oct 10 11:18:40 hostname osqueryd: I1010 11:18:40.242887 27995 scheduler.cpp:73] Executing scheduled query uptime: select * from uptime;

**Comment by muffins** [comment]
@Chrisbuuren are these log entires all from the same host? Or is there one result for each of the hosts you're running it on? Where are you viewing these log lines?

The scheduler can be a little bit un-intuitive from an initial use perspective, but we made decisions about it's logic to ensure we never miss getting data from a query. When the daemon starts up it grabs the current timestamp, and uses this internally to decide when queries should be run. As your query has an `'interval': 10800`, then once every 3 hours osquery will check if it's **internal** time representation mod your interval count +/- a `schedule_splay_percent` == 0. If it does your query is executed. More details are below, taken from our readthedocs:
```
NOTICE: that the interval time in seconds is how many seconds the daemon itself has been running before the scheduled query will be executed. If the system is suspended or put to sleep the progression of time "freezes" and resumes when the system comes back online. For example a scheduled query with an interval of 84600, or 24 hours, running on a laptop system could take a few days before the query executes if the system is suspended at night.
```

**Comment by Chrisbuuren** [comment]
@muffins all the logs are from the same host. I just run **cat /var/log/messages | grep uptime** an there is where i saw them. 
The hosts were never put to sleep and the uptime is greater than 50 days. On some hosts the queries execute correct but on some I have this problem. 
I checked the time and is properly set and even restarted the daemon for that hosts but the queries executes same as before at random interval times.
The os I am running for all my hosts is Centos 7.3 and I use ntpd for time synchronization so I don't have differences in time.

**Comment by muffins** [comment]
Interesting, I don't believe we've had folks see behavior like this. We can leave this issue open to try and track this down further, but to potentially speed up debugging this issue I'd encourage you to jump into [our Slack](https://osquery-slack.herokuapp.com/) and ask this question in our general channel to see if some other folks might have any ideas about what's going on here.

**Comment by theopolis** [comment]
I would check if your config is valid. It doesn't look correct in the paste above. Perhaps hosts are using an older config with lower intervals?

Here's what I've massaged it to:
```json
{
  "packs": {},
  "schedule": {
    "uptime": {
      "platform": "all",
      "snapshot": "false",
      "description": "Track time passed since last boot.",
      "query": "select * from uptime; ",
      "removed": "false",
      "interval": 10800,
      "value": ""
    },
    "os_version": {
      "platform": "all",
      "version": "",
      "snapshot": "false",
      "description": "A single row containing the operating system name and version.",
      "query": "select * from os_version;",
      "removed": "false",
      "interval": 10800,
      "value": ""
    }
  },
  "file_paths": {}
}
```

There will be slight variations in the times when queries execute. But these times are far too often to be correct (given your intervals of 10800 seconds, are you sure these are intended?). The variations come from schedule "splays" the default splay is 10% meaning when a configuration is updated each interval may be morphed + or - 10% of the input interval.

**Comment by Chrisbuuren** [comment]
I stopped and the started the service on two machines and now the queries execute at the given interval.
There is no other config file on the machines, because this is how I get my config https://github.com/facebook/osquery/blob/master/docs/wiki/deployment/remote.md.
The configure i posted was just a print, but I assure you that the same config is present on all the other hosts(1000+ hosts).
There are some hosts that fail to execute the queries as there is in the config.

**Comment by uptycs-nishant** [comment]
@Chrisbuuren , two questions -
1. Are you running your 'query': 'select * from uptime'  at 'interval': 10800 ?
2. Can you provide all the logs lines in between the three log lines you pasted above?

**Comment by theopolis** [comment]
Will close for now, if this still needs investigation we can reopen, thanks all!
