### ISSUE TITLE
Clarification needed: Using osquery remote without authentication

### ISSUE THREAD

**Issue by itskenny0** [facebook/osquery#3820]
Hi there,

I'd like to use osquery without any form of authentication and enrollment to a server.
You might say this is a huge security risk, but there is a strong authentication layer on the subnet the hosts will reside in. Ideally, I would like to have the following scenario:

- Hosts with osquery installed listen on a port, providing a HTTP API.
- The HTTP API is ideally plaintext without encryption.
- The API can be queried by all hosts within a specific subnet or network interface, not having to negotiate authentication (Allow from all).
- The port is NOT reachable from any public internet interfaces, if present (so limited to a specific network interface or subnet).

Is a scenario like this possible using osquery? If yes, could you point me to a documentation/resource that explains how to implement this? Unfortunately, I did not find any indication of zero authentication being supported in [the docs](https://osquery.readthedocs.io/en/stable/deployment/remote/).
The infrastructure in question will mainly be GNU/Linux.

Thanks a lot in advance and thank you for this great piece of software!

Best,
kenny

**Comment by muffins** [comment]
Hey @itskenny0,

I don't believe we allow for this model currently. While it might be possible to extend out the client to allow for this behavior, you'd also still need to have a backend TLS enrollment service that would allow for it as well, and I don't think ay of the popular enrollment servers (Kolide, upytcs, doorman, ...) allow for this. That all being said, I'd encourage you to [checkout our Slack](https://osquery-slack.herokuapp.com/) to see if others might have more insight for you.
