### ISSUE TITLE
tool to parse log files with SQL

### ISSUE THREAD

**Issue by andyrat33** [facebook/osquery#385]
Hi,
I just heard about OSquery and I think it's a brilliant concept and I can already see some really great security use cases. However, I just wondered if you had considered expanding the concept out a little further to be able to query log and event data. One of the tools I use regularly is Microsoft Log Parser 2.2 - it is one of the best ways there is for working with ad-hoc log and event data. There are some examples on my blog http://blog.infosecmatters.net . 
The details for MS Log Parser can be found here:
http://technet.microsoft.com/en-gb/scriptcenter/dd919274.aspx

I have often wished that a similar tool was available for Linux. Perhaps this would something you could incorporate into OSQuery.

**Comment by marpaia** [comment]
This should be much more of a viable option now that every query passes around it's query context (https://github.com/facebook/osquery/wiki/creating-a-new-table#whats-a-querycontext)

**Comment by marpaia** [comment]
Moving the tracking for this to #619.
