### ISSUE TITLE
macOS: make deps fails in a machine with osquery already installed

### ISSUE THREAD

**Issue by javuto** [facebook/osquery#3860]
If you try to build osquery from source in a machine that has it already installed from a package, it will fail due to the existance of `/usr/local/osquery` and not being empty:
```
$ make deps
-- Warning! The only Apple OS supported for building is 10.12
-- Note: Installing and running osquery is supported on versions 10.9+
./tools/provision.sh build darwin10.13
[+] setting up new brew in /usr/local/osquery
fatal: destination path '/usr/local/osquery' already exists and is not an empty directory.
make: *** [deps] Error 128
```
This happens after running `make sysprep`.

A quick fix could be check for the existance of that directory and show a message to point the variable to a different location instead of just failing. I have a PR ready that can mitigate this.

**Comment by javuto** [comment]
Problem happens [here](https://github.com/facebook/osquery/blob/master/tools/provision/lib.sh#L32), when trying to clone something into a not empty directory.

**Comment by theopolis** [comment]
Why does that directory exist?

**Comment by javuto** [comment]
Osquery was already installed in the system with puppet. It drops the binaries in that directory.

**Comment by theopolis** [comment]
You can change that error to be more friendly, but if you use another `OSQUERY_DEPS` environment variable value you wont be able to use the Homebrew cached packages. A lot of those bottles use hard coded paths internally.
