### ISSUE TITLE
Create a virtual table to list pipes in Windows 

### ISSUE THREAD

**Issue by friedbutter** [facebook/osquery#3888]
Similar to https://docs.microsoft.com/en-us/sysinternals/downloads/pipelist, we need a table to list pipes. 
It would be nice to get the pipe names, and processes using the pipes, but I'm not sure how difficult that is in Windows.

**Comment by muffins** [comment]
I'll work on this. Likely we'll need to walk through processes list and enumerate pipes for each, as I'm not sure there's a way to get a generic list of all pipes. This will probably need to be joined off of the processes table by pid.

**Comment by muffins** [comment]
This was addressed with #3893
