### ISSUE TITLE
Detect hidden modules

### ISSUE THREAD

**Issue by unixed** [facebook/osquery#389]
Common techniques for hiding a kernel rootkit are: unlinking itself from the global linked list of modules, removing itself from sysfs, from debugfs and more.

One way I've come up with that doesn't rely on certain artifacts left in known data structures or in the kernel's process space is to detect the module's non-removal. When a typical module is removed, something calls `rmmod`, the system call `delete_module` is executed, and the kernel removes its traces.

If the user allows camb to hook the init_module/delete_module pair of system calls, all modules, malicious or otherwise, may be watched.

If at some point camb detects that a previously-inserted module is not in the normal places (linked list, sysfs), it can check if the module was removed normally. If so, stop tracking it and continue chugging on. If it wasn't removed normally and is no longer found in the normal data structures, this could be cause for alarm.

This comes with the caveat that we can simply hook a system call. I'm not sure what the implications are from the standpoint of other security software (LSM, A/V). Other systems may assume that they can hook stuff themselves/instead or that things shouldn't be hooked.

**Comment by theopolis** [comment]
We have camb in master now. Let's table this issue-discussion to a mailing list later on or as feature-improvements/PRs. :)
