### ISSUE TITLE
Snapshot empty results return empty string and not empty list

### ISSUE THREAD

**Issue by javuto** [facebook/osquery#3891]
### Context

When running a snapshot query, the field `snapshot` usually returns a list of the columns queried. But if the results are empty, the return value in JSON is a empty string `""` instead of an empty list `[]`, so further processing of the logs can be problematic.

### Steps to reproduce

Having a linux system with osquery 2.9.0 installed from the deb package:
```
root@vagrant:~# osqueryi -version
osqueryi version 2.9.0
```

Using this sample configuration in `/etc/osquery/osquery.conf`:
```
{
  "options": {
    "config_plugin": "filesystem",
    "logger_plugin": "filesystem",
    "logger_path": "/tmp/osquery",
    "database_path": "/tmp/osquery/osquery.db",
    "utc": "true"
  },
  "schedule": {
    "testing_bug": {
      "query": "SELECT path FROM file WHERE directory = '/tmp/osquery/testing_bug/';",
      "snapshot": true,
      "interval": "10"
    }
  }
}
```
The results of the snapshot query show the field `snapshot` to be an empty string:
```
root@vagrant:~# cat /tmp/osquery/osqueryd.snapshots.log | tail -1
{"snapshot":"","action":"snapshot","name":"testing_bug","hostIdentifier":"vagrant","calendarTime":"Thu Oct 26 18:27:55 2017 UTC","unixTime":"1509042475","epoch":"0","counter":"0"}
```
And if I generate data that is not emtpy, it shows as a list:
```
root@vagrant:~# touch /tmp/osquery/testing_bug/lol
root@vagrant:~# cat /tmp/osquery/osqueryd.snapshots.log | tail -1
{"snapshot":[{"path":"\/tmp\/osquery\/testing_bug\/lol"}],"action":"snapshot","name":"testing_bug","hostIdentifier":"vagrant","calendarTime":"Thu Oct 26 18:28:58 2017 UTC","unixTime":"1509042538","epoch":"0","counter":"0"}
```

Ideal outcome is that the empty field would be an empty list `"snapshot":"[]"`

Similar behavior can be seen in the field `diffResults` but I haven't managed to reproduce it yet. 
I believe the problem can be isolated in the usage of ptree when the results get serialized, in `osquery/core/query.cpp`.

**Comment by obelisk** [comment]
This is the new output from `master`:

```JSON
{"snapshot":[],"action":"snapshot","name":"testing_bug","hostIdentifier":"obelisk-mbp5","calendarTime":"Thu Mar  1 07:19:04 2018 UTC","unixTime":1519888744,"epoch":0,"counter":0}
```
