### ISSUE TITLE
osqueryd 2.10.0 doesn't add port to Host header

### ISSUE THREAD

**Issue by ecneladis** [facebook/osquery#3898]
I run osqueryd with option `--tls_hostname=osquery.example.com:8443`.
 
`osquery/2.9.0` adds port to Host header - `osquery.example.com:8443`
`osquery/2.10.0` does not - `osquery.example.com`

It seems to be introduced with this commit: https://github.com/facebook/osquery/commit/9b3d02ff2f8e0749cedd8cd5428ab19734a0095e. Can it be considered as a bug? Currently I run TLS endpoints behind nginx and it breaks communication with latest agents.

---

Logs from nginx:
```nginx
[30/Oct/2017:15:14:58 +0000] "POST osquery.example.com:8443 https://osquery.example.com/enroll HTTP/1.1" 200 83 "-" "osquery/2.9.0" 0.021
[30/Oct/2017:15:15:04 +0000] "POST osquery.example.com https://osquery.example.com/enroll HTTP/1.1" 404 4233 "-" "osquery/2.10.0" 0.032
```

Nginx log format:
```nginx
log_format main '$http_x_forwarded_for - $remote_user [$time_local] '
'"$request_method $http_host $scheme://$host$request_uri $server_protocol" '
'$status $body_bytes_sent "$http_referer" '
'"$http_user_agent" $request_time';
```

**Comment by theopolis** [comment]
I don't mind releasing a 2.10.1 once the fix lands for this bug.
