### ISSUE TITLE
Proposal: rename the ssl_cert tables to curl_tls_cert

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#3900]
I think the fact that this table goes and performs some network action is significant. The `curl` table is fairly obvious, but that obviousness is lost here (at least for me).

If we rename `curl_tls_cert` then it's more like "please curl and display the TLS cert".

**Comment by micheal-o** [comment]
@theopolis I see your point. I can go ahead and rename the table. But I think the curl prefix makes it seem like the table uses libcurl. What do you think about renaming it to remote_tls_cert or web_tls_cert or something else?

**Comment by theopolis** [comment]
We had the same discussion about the `curl` table, which actually doesn't use `curl` either, haha! The name is just so recognizable. ;)

**Comment by thedrow** [comment]
Shouldn't this issue be closed now that #3903 is merged?
