### ISSUE TITLE
[RFC] Osquery Website Redesign

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#3930]
In an effort to make the https://osquery.io a fun, beautiful website for the osquery community, we have been reasoning about and planning a redesign of the website that is tailored to a set of specific requirements that embody the openness that is so critical to the DNA of the osquery project.

The following issue outlines the requirements of the website redesign, which were enumerated by talking to stakeholders throughout the osquery community. Also included are an enumeration of "MVP" features (get these out quickly and #shipit) and "Post-MVP" features (features that don't currently exist on the website that will improve the communities ability to collaborate).

Finally, the actual designs of the new osquery site are included as well. Please note that the copy and the text in the buttons are subject to change, the designs are more of a visual representation of page structure. Scroll down to the end of this document to see all of them and comment on this issue with your feedback if you have concerns about the usability of the application that we can address!

### Openness of data, accessible to contribute to

The site should be interactive and fun to use, but not at the expense of making the data that powers the website feel opaque. Whenever possible, ensure that data (schema specifications, blog content, etc) can be statically compiled into included JSON files and, most importantly, easily updated via a GitHub PR from a member of the osquery community.

### Minimize hosting, maximize usability

The site should continue to be as static as possible. It should, however, also easily support effective interaction with APIs if such features become necessary or desired. Additionally, you should be able to browse the site easily in adverse network conditions.

To this end, we will be creating the site with React as a [Progressive Web App](https://developers.google.com/web/progressive-web-apps/). The documentation for the [Create React App](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app) project say the following about Progressive Web Apps:

Progressive Web Apps are faster and more reliable than traditional web pages, and provide an engaging mobile experience:

- All static site assets are cached so that your page loads fast on subsequent visits, regardless of network connectivity (such as 2G or 3G). Updates are downloaded in the background.
- Your app will work regardless of network state, even if offline. This means your users will be able to use your app at 10,000 feet and on the subway.
- On mobile devices, your app can be added directly to the user's home screen, app icon and all. You can also re-engage users using web push notifications. This eliminates the need for the app store.

### Beautiful, useful user experience

The site should be static, it should be progressive, it should be easy to contribute to, but it also must be beautiful, fun, and useful! We should take the requisite steps and spend time to create a beautiful application user-experience for the osquery community. Emphasis will be spent on effective web design and usability. If the application does not feel usable once the site starts to come to life, please provide feedback early and often!

## Development Plan

The plan for the redesign is for work to happen in the open. Development will take place in the [osquery/osquery-site](https://github.com/osquery/osquery-site) repo. When the new site is deployable, we will ship it and host it at https://beta.osquery.io. When the site is feature complete and adding value, we will cut it over to https://osquery.io.

We will be creating several GitHub issues in the `osquery-site` repo, so be sure to "Watch" that repo if you're interested in keeping up with development.

## MVP Features

We are limiting the MVP feature-set to the following features.

- Homepage
- Osquery Schema Browser
- Downloads Page
- Blog

A first implementation of the website containing just the above pages will be used as a minimum cut-off point to make sure we're shipping early and often.

## Post-MVP Features

Once "MVP" features are developed and shipped, development will begin on the following additional features:

- Integrated Wiki (deprecating https://osquery.readthedocs.io)
- Integrated Query Pack intelligence sharing

These features represent functionality not currently offered by the website, but we believe that features will add value to the osquery community and add utility to the osquery project as a whole

### Home Page

![osquery-io-again-again](https://user-images.githubusercontent.com/927168/32960580-a66cf290-cb82-11e7-98f3-3acaf1788a8b.png)

### Schema Browser

![osqueryio-schema-flatter](https://user-images.githubusercontent.com/927168/32960586-ad3b16f6-cb82-11e7-8ac9-389ebbed911f.png)

### Downloads Page

![osqueryio-downloads-new](https://user-images.githubusercontent.com/927168/32963758-3852655e-cb8e-11e7-94a9-e3658ca6a88e.png)

### Pack Sharing

![osqueryio-packs-revised](https://user-images.githubusercontent.com/927168/32960594-b89de820-cb82-11e7-8bf7-a3d9efc908aa.png)

**Comment by clong** [comment]
Okay to close this now?
