### ISSUE TITLE
osqueryd shuts down with error logging results of query

### ISSUE THREAD

**Issue by mcburrlin** [facebook/osquery#3931]
Our fleet is experiencing issues after building osquery 2.10.0 and running scheduled queries. In short, the daemon receives a message for requestShutdown(CATASTROHPIC_EXIT) (taken from here: https://github.com/facebook/osquery/blob/2.10.0/osquery/dispatcher/scheduler.cpp#L144).

The error message is: 
`E1116 13:05:04.013469  8944 scheduler.cpp:146] Error logging the results of query: running_processes: No diff results or snapshot results`

The "no diff results or snapshot results" seems to be related to this section of code (or somewhere nearby):
https://github.com/facebook/osquery/blob/418973f3334118617f099a90e7da7f324323b1e1/osquery/core/query.cpp#L560

The query that is causing the issue is:
`select h.md5, p.name, p.path, p.cmdline, p.state, p.cwd, p.on_disk from processes as p, hash as h where p.path=h.path group by h.md5,p.on_disk;`

So this query successfully runs and returns results, but after x number of runs (random) it will cause the CATASTROPHIC_EXIT as described above. 

Distros: Ubuntu 14.04, Ubuntu 16.04
osquery version(s) causing this issue: 2.10.0 and 2.10.2
query types: scheduled packs
query frequency: Every 10 minutes

Let me know what other data I can provide to help triage this issue, thanks.

**Comment by theopolis** [comment]
Ah, I see the logic problem here. This has nothing to do with the version of osquery, it's because your scheduled query has `removed: False` and there were only removed events recorded.
