### ISSUE TITLE
Include location context for Windows 'certificates' table

### ISSUE THREAD

**Issue by cryps1s** [facebook/osquery#3934]
The certificates virtual table in osquery (for Windows) currently provides a path, like the following: 

`path = Trusted Root Certification Authorities`

However, this path lacks critical information for _which_ path is referenced. For instance, users (without administrative rights) could load a new certificate into the Trusted Root Certification Authorities path for their user. When this data is ingested in osquery, it appears identical to certificates loaded into the Trusted Root Certification Authorities path for the local system. 

For instance, please reference the following example: 
```
osquery> select common_name, subject, issuer, sha1, path from certificates WHERE common_name = "Microsoft Root Certificate Authority";
common_name = Microsoft Root Certificate Authority
    subject = com, microsoft, Microsoft Root Certificate Authority
     issuer = com, microsoft, Microsoft Root Certificate Authority
       sha1 = 0C4340FEA1F5D6E67E98BBE79E1AB8B1E367C6F4
       path = Trusted Root Certification Authorities

common_name = Microsoft Root Certificate Authority
    subject = com, microsoft, Microsoft Root Certificate Authority
     issuer = com, microsoft, Microsoft Root Certificate Authority
       sha1 = CDD4EEAE6000AC7F40C3802C171E30148030C072
       path = Trusted Root Certification Authorities
```
One of these certificates is loaded in the Root Certification Authorities store for the Local System, and is a legitimate Microsoft certificate. The other is a malicious certificate that was loaded in the Root Certification Authorities store for a local user. The path presented by osqeury cannot distinguish the two, making it difficult to identify if a malicious certificate was loaded onto a system.

Ideally, there would be another column that would identify where the path was sourced from (e.g. the user it was sourced from, or the local machine). This would allow us to run searches against certificates loaded into _user_ stores, which have a higher likelihood of maliciousness.

**Comment by muffins** [comment]
this was addressed with #3947.
