### ISSUE TITLE
[RFC] Discussion about 3.0.0 breaking changes

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#3940]
As discussed in today's (Nov 17, 2017) osquery office hours, if we had the opportunity to cut a new major version and make some breaking changes, what would be on our shortlist of things that we could change that would make working with osquery more intuitive. This issue serves as a forum that allows people from throughout the community to discuss what changes they would like to see. I will continuously edit the description of this issue with ideas that need more discussion, ideas that people are largely in support of, and ideas that people are largely opposed to.

When someone proposes an idea below, please consider reacting to the comment with 👍 or :-1: based on how you feel about such a change being introduced into osquery.

**Comment by groob** [comment]
It would be nice to create a Project + Milestone for 3.0(no due date) so that individual issues could be linked to that.

**Comment by zwass** [comment]
From the office hours discussion:

Require that integers in configuration files are expressed as integers and not strings.

**Comment by marpaia** [comment]
I would like to propose changing the TLS API in a few ways that might make it easier to write servers against. In order of least to most objectionable:

### Start versioning the TLS API independently of osquery version releases.

This would require us to implement some mechanism for the client and server to resolve their supported version. Something like this might make it easier and less existential to add/remove things from the API.

### Make the plugins less long-poll and more live sockets

Establish built-in support in distributed read/write for websocket based communication that allows for more instant access to devices.

### Consider supporting the merge of distributed read with config acquisition as well as distributed write with logging

These two concepts are similar and this idea was originally brought up by @theopolis in the [original PR that implemented the distributed query API](https://github.com/facebook/osquery/pull/1500#issuecomment-138382665). I advocated against it then because there are cases where you might want them to be different. Now, however, I feel as though if you're using the same server for `/config` and `/distributed_read`, it might be interesting if you could just define `/updates` and `/logs` or something similar. 

For configs, if we actually did add live websocket communication to distributed read, I would want to be able to push my configs in the same way. The inverse would be also be true: if we improved the rate at which we could distribute configs, I would want that capability for distributed read as well.

For logging, this is tough now because the errors of a on-demand query are sent to `/log`, not `/distributed_write`. Having disparate endpoints for where logs for things can go makes things complicated sometimes.

**Comment by thedrow** [comment]
I'd like to break the API for the extensions so that the results will contain a union of types (which is supported by thrift).
It will make the reporting more accurate and prevent us from converting everything to/from strings which is much more efficient.

The only place where only strings are accepted is LevelDB which we need to somehow resolve.

**Comment by groob** [comment]
A breaking change for distributed writes I'd like to see is having a `error` field that comes in the response. 

Right now, if a TLS plugin user tries to schedule an ad hoc query, and the query fails because the table requires a JOIN, the user will never know why the query failed unless they look at the status log.

**Comment by marpaia** [comment]
I would also like to propose establishing a rigid set of guidelines for tables/plugins that should/shouldn't live in osquery core and removing tables/plugins that don't adhere to those guidelines and breaking them out into an official extension.
