### ISSUE TITLE
syslog logger_plugin: how to change program name?

### ISSUE THREAD

**Issue by juju4** [facebook/osquery#3941]
Hello,

when using osquery (latest) with syslog output.
the program name or daemon appearing in syslog message can either be osqueryd, either worker.

any way to force one name like osqueryd? worker is a bit too generic.
pid anyway will allow to differentiate

Thanks

**Comment by muffins** [comment]
Hey @juju4, you might wanna try asking this question in [our Slack](https://osquery-slack.herokuapp.com/) as you'll likely get faster responses. That being said, I'm not sure if you can change that name, as we use `worker` to differentiate the watchdog process from the worker process. However that being said, there should be some indication that the process does belong to osqueryd. I'll need to refresh my memory on what that output looks like, but likely someone in Slack has a better answer for you :)

**Comment by theopolis** [comment]
I've tried forcing the "name" with syslog a few times with mixed results. Right now we are explicitly setting `osqueryd` in the `openlog` syslog API call. I played with incantations of closing the log, re-opening, etc and it seems to do what it wants.

In my opinion we should abandon the `argv[0]` rewriting which would preserve any internal detection of process name by other libraries.

**Comment by juju4** [comment]
from a process perspective, I'm fine with current state even if I would prefer something more clear like sshd does
```
sshd
sshd: test [priv]
```
so
```
osqueryd
osqueryd [worker]
```
or something similar

it's more on syslog side where having multiple identifiers (potentially changing?) is kind of making classification harder and force to rebuild index which is more or less annoying depending on target log collection. having just osqueryd and eventually add a tag/value inside the message to say it is from workerX (if pid not enough) seems more reasonable to me.

comments?

Thanks

**Comment by theopolis** [comment]
My preference is still to remove the renaming.

I do like the differentiation of the worker/watcher process via easy inspection of `argv[0]` but in practice, making sure this is clean on all platforms is a PITA. I've noticed that on macOS the `processes` table reports a weird looking `cmdline` for processes that do this "copy over `const char* argv[0]` trick.

**Comment by juju4** [comment]
Thanks a lot @theopolis !
