### ISSUE TITLE
Windows: osqueryd service throws System error 7034 on restart

### ISSUE THREAD

**Issue by straffin** [facebook/osquery#3950]
When restarting the osqueryd service on Windows, the Service Control Manager throws an error of Event 7034: "The osqueryd service terminated unexpectedly." Other Windows services do not do this. The osqueryd service should me made to stop gracefully.

**Comment by muffins** [comment]
What version of osquery are you running? We definitely have had issues in the past with shutting down in a "non-graceful" way, but if we're still doing this we'll definitely want to fix that up.

**Comment by straffin** [comment]
Chocolatey-installed osquery 2.9.0

**Comment by muffins** [comment]
@straffin great, thanks. Will investigate. 2.10.2 is available on Chocolatey, but I'm not positive that there's a fix for this behavior between 2.9.0 and 2.10, so I'll look into it.

**Comment by muffins** [comment]
This was fixed with #3973
