### ISSUE TITLE
aws_firehose_logger broken in 2.10.1_1 +

### ISSUE THREAD

**Issue by mattjane-okta** [facebook/osquery#3953]
It seems that something introduced in 2.10.1_1 has caused the signature calculation for aws_firehose sending has broken.

error message: 

```
aws_firehose: Complete request failure: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

Tested on ubuntu 16.04, versions 2.10.1_1, 2.10.2_1 and 2.10.3_1.

2.10.0_1 has been verified working.

Unfortunately it appears 2.10.2_1 is the version shipping from the apt repositories.

**Comment by mattjane-okta** [comment]
Affects OSx and Windows as well

**Comment by theopolis** [comment]
@uptycs-nishant is this related to the `beast` refactor?

**Comment by uptycs-nishant** [comment]
@mattjane-okta , can you provide the post request headers for 2.10.0_1  and 2.10.1_1 ?

**Comment by securityclippy** [comment]
tracked down the error message at least, it first appears here via this commit: https://github.com/facebook/osquery/commit/58fa4a68993c5a030b68c0f5349d8b7c93d4866b#diff-20fbdada1729a78df943fa0e265d0120

in this file https://github.com/facebook/osquery/blob/58fa4a68993c5a030b68c0f5349d8b7c93d4866b/osquery/logger/plugins/aws_log_forwarder.h

@uptycs-nishant will work on grabbing headers for ya.

**Comment by uptycs-nishant** [comment]
Thanks @securityclippy

**Comment by securityclippy** [comment]
@uptycs-nishant actually, don't thank me yet.  It appears I have no idea what I'm doing.  --tls_dump did not give me the headers I was hoping for.  Is there a way to dump headers you can point me to?

**Comment by uptycs-nishant** [comment]
@securityclippy what url you are using?

**Comment by uptycs-nishant** [comment]
@securityclippy a quick compilation of the code -

Can you put the LOG message at "./utils/aws_util.cpp:123" ?
    for (const auto& requestHeader : request.GetHeaders()) {
>> LOG(WARNING) << "header: " << requestHeader.first << "value: " << requestHeader.second;
      req << http::Request::Header(requestHeader.first, requestHeader.second);
    }

**Comment by securityclippy** [comment]
@uptycs-nishant thanks!  never compiled from source before, so bear with me a while.  Will try to get info out in an hour or two!

**Comment by uptycs-nishant** [comment]
can you give me the url for http request ?

**Comment by securityclippy** [comment]
@uptycs-nishant not sure which URL you're referring to tbh.  Hit me up on slack?  i'm @clippy in the osquery slack.

**Comment by alessandrogario** [comment]
Hey everyone! I submitted this PR when osquery was still using the older library (my tests were performed with cpp-netlib). It has been merged after Boost Beast has been introduced, so it is possible that something broke. I can look into it if you would like.

**Comment by theopolis** [comment]
Thanks all!
