### ISSUE TITLE
Securing the TLS connection from http_client

### ISSUE THREAD

**Issue by rhonnava** [facebook/osquery#3955]
In osquery/remote/http/http_client.cpp, inside the function ```void Client::encryptConnection()``` I notice that the HTTPS connection is over SSLv2/v3 as per this like `boost_asio::ssl::context ctx{boost_asio::ssl::context::sslv23};`, which is vulnerable and also does not confirm to some regulatory requirements like PCI.

Wondering if it can be changed to:

```
boost_asio::ssl::context ctx{boost_asio::ssl::context::tls_client}; //Enable all versions 

ctx.set_options(boost::asio::ssl::context::no_sslv2 |
                         boost::asio::ssl::context::no_sslv3 ); // Disable the vulnerable older versions
```

Also to make it more secure, we can even disable tlsv1 allowing only TLSv1.1 and TLSv1.2. In addition we can also 

`ctx.set_options(boost::asio::ssl::context::single_dh_use);` as a way to implement perfect forward secrecy.

**Comment by theopolis** [comment]
Hi @rhonnava, thanks for pointing this out! Despite the name `sslv23`, this is actually the selection for OpenSSL's default-enabled set of protocols. So this does include TLSv1. We take several steps to make sure SSLv2 and SSLv3 cannot be used:
- Define the removal headers: https://github.com/facebook/osquery/blob/master/osquery/remote/http_client.h
- Remove SSLv2 and SSLv3 in the OpenSSL build: https://github.com/facebook/osquery/blob/master/tools/provision/formula/openssl.rb#L46
- And we also explicitly set a cipher suite: https://github.com/facebook/osquery/blob/master/osquery/remote/transports/tls.cpp#L26

So we're covered!

The note about PFS is another good one. In our opinion, we shouldn't force PFS on folks within the client. However if there are no downsides to this, e.g., some deployments may use a corporate proxy where PFS could be incompatible, we can enable it. I think the best course of action is to expose the cipher suite configuration and let the deployment decide if they want to force PFS.

**Comment by rhonnava** [comment]
Thanks for the answer on SSLv2/v3! 

Regarding PFS, I agree that it should not be forced and making it a configurable option. I can send a pull request for this.
