### ISSUE TITLE
file_events not watching file after vim edit

### ISSUE THREAD

**Issue by UntilDoomsday** [facebook/osquery#3991]
I have found that if I edit a file I am monitoring using vim on CentOS7 it will cause the monitoring to fail on that file only. Other files being monitored will continue to report changes. I am able to consistently reproduce this issue by opening a monitored file with vim, editing the file, writing the output, then waiting a few second and writing the output again. The first write will produce a file event, any after will not. This remains the case until osquery is restarted. I have worked with the folks in the Slack channel to try common solutions like changing inotify limits, without success. Conf and flags file below:

--disable_events=false
--events_expiry=3600
--events_max=50000
--logger_plugin=filesystem
--watchdog_memory_limit=350

{
  "options": {
    "logger_snapshot_event_type": "true",
    "schedule_splay_percent": 10
    },
  "platform": "linux",
  "schedule": {
    "file_events": {
      "query": "SELECT * FROM file_events;",
      "interval": 10,
      "removed":false
    }
  },
  "file_paths": {
    "configuration": [
      "/etc/passwd",
      "/etc/shadow",
      "/etc/ld.so.conf.d/%%",
      "/etc/pam.d/%%",
      "/etc/resolv.conf",
      "/etc/rc%/%%",
      "/etc/my.cnf",
      "/etc/hosts",
      "/etc/hostname",
      "/etc/fstab",
      "/etc/crontab",
      "/etc/cron%/%%",
      "/etc/init/%%",
      "/etc/rsyslog.conf",
      "/etc/login.defs"
    ],
    "binaries": [
      "/usr/bin/%%",
      "/usr/sbin/%%",
      "/bin/%%",
      "/sbin/%%",
      "/usr/local/bin/%%",
      "/usr/local/sbin/%%"
    ]
  }
}

**Comment by uptycs-nishant** [comment]
I could not reproduce the issue -

[root@nishant ~]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)

[root@nishant ~]# uname -a
Linux nishant 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

vim version -
version 7.4.160

You also mentioned on slack channel that you dont see this problem when you use nano editor ?

my config -

EXAMPLE_CONFIG = {
    "schedule": {
        "file_events": {"query": "select * from file_events;", "interval": 10}
    },
   "file_paths": { "tmp": ["/tmp/fimtest/%%"] },
   "options": { "schedule_epoch": "1234" },
   "node_invalid": False
}

**Comment by UntilDoomsday** [comment]
Correct, I do not see this issue with nano. I also could not recreate in /tmp like your example, however I could recreate on files in /etc consistently. I set up a new VM on a different host using CentOS7 minimal, same issue using /etc/hosts and /etc/login.defs as the test files.

**Comment by uptycs-nishant** [comment]
vim is playing tricks here, every time you open a file in edit mode and write, it creates new file. 
you can observe this behavior via following test -
[root@nishant ~]# ls -li /etc/hosts
67155107 -rw-r--r--. 1 root root 158 Dec 11 06:53 /etc/hosts
[root@nishant ~]# vim /etc/hosts <--- open the file and write and exit from vim
[root@nishant ~]# ls -li /etc/hosts
67155112 -rw-r--r--. 1 root root 158 Dec 11 07:31 /etc/hosts

 Check inode of the file "/etc/hosts" changed it means it is new file. Because of this being new file watch is dropped here and you get the event only once since original file which was being monitored is gone.

Inside "/tmp" folder vim's behavior is different that is configured that way, you can check this configuration inside "/etc/vimrc". 

To address your problem cause by vim -
You need to put the entire "/etc" folder under watch.

**Comment by UntilDoomsday** [comment]
That makes sense. Given how common it is to use vi/vim and to monitor files in /etc, I wonder if this is worth adding a note to the documentation. I am sure many people are not accounting for this in their configuration.

**Comment by theopolis** [comment]
@UntilDoomsday, I agree with the node about documenting this behavior. Do you mind reading through the file-integrity-monitoring markdown and adding that note where you see fit? 

Here's the Markdown: https://github.com/facebook/osquery/blob/master/docs/wiki/deployment/file-integrity-monitoring.md

**Comment by packetzero** [comment]
A note on this for posterity.  It seems to be fixed V4 kernels.

Works:
Ubuntu 18 kernel 4.15
Ubuntu 16 kernel 4.15

Fails:
CentOS 6.10     kernel 2.6.32-754
CentOS 7.5  kernel 3.10.0-862
