### ISSUE TITLE
Startup Items table does not parse path out of "com.apple.loginitems.plist" properly.

### ISSUE THREAD

**Issue by PickmanSec** [facebook/osquery#3994]
* It's possible this is a misunderstanding about the startup items table. 

I added a login item to my account and noticed the path field wasn't being parsed out of the file. I believe I added it using "https://github.com/pudquick/pyLoginItems/blob/master/pyLoginItems.py"
I noticed that when you look at the contents of `~/Library/Preferences/com.apple.loginitems.plist`  you can get the correct path.

**Comment by PickmanSec** [comment]
so since I am really bad a bug reports: there appears to be a discrepancy between what I see when I decode the alias in `/Library/Preferences/com.apple.loginitems.plist`for one particular item and what osquery returns when I run `sudo osqueryi "select * from startup_items"`

**Comment by pudquick** [comment]
One may want to investigate, on 10.13 (and possibly earlier?) machines the undocumented class "SFLManager", which has a shared instance for tracking SharedFileList types - of which LoginItems now is.


on 10.13:
```
python -c 'import sys; from Foundation import SFLManager; manager = SFLManager.sharedInstance(); map(lambda x: sys.stdout.write(str(x.bookmark()) + "\n"), manager.loginItems().allItems())'
```

```
manager.recentDocumentsForBundleIdentifier_("com.apple.TextEdit")
```


```
>>> SFLManager.listIdentifiers()
(
    "com.apple.LSSharedFileList.FavoriteVolumes",
    "com.apple.LSSharedFileList.FavoriteItems",
    "com.apple.LSSharedFileList.SavedSearches",
    "com.apple.LSSharedFileList.ProjectsItems",
    "com.apple.LSSharedFileList.RecentApplications",
    "com.apple.LSSharedFileList.RecentDocuments",
    "com.apple.LSSharedFileList.RecentServers",
    "com.apple.LSSharedFileList.RecentHosts",
    "com.apple.LSSharedFileList.NetworkBrowser",
    "com.apple.LSSharedFileList.AutomountedServers",
    "com.apple.LSSharedFileList.FavoriteServers",
    "com.apple.LSSharedFileList.SessionLoginItems",
    "com.apple.LSSharedFileList.GlobalLoginItems",
    "com.apple.LSSharedFileList.ManagedSessionLoginItems",
    "com.apple.LSSharedFileList.SharePoints",
    "com.apple.LSSharedFileList.ManagedShared",
    "com.apple.LSSharedFileList.ApplicationRecentDocuments",
    "com.apple.LSSharedFileList.DockApplications",
    "com.apple.LSSharedFileList.iCloudItems",
    "com.apple.LSSharedFileList.SFLServiceManagementLoginItems",
    "com.apple.LSSharedFileList.SFLLaunchdJobs"
)
```
etc.

This class has the potential to provide a great deal of information osquery may like.

/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework

**Comment by theopolis** [comment]
On 10.12 this isn't exactly the same. `SFLManager` does not exist, 

```
Python 2.7.13 (default, Apr  4 2017, 08:47:57) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; from Foundation import SFLListManager;
>>> manager = SFLListManager.sharedInstance();
>>> manager.listsByIdentifier()
NSMapTable {
}
>>> manager.listWithIdentifier_('com.apple.LSSharedFileList.GlobalLoginItems').items()
(
)
>>> manager.listWithIdentifier_('com.apple.LSSharedFileList.SessionLoginItems').items()
(
)
>>> 
```

**Comment by theopolis** [comment]
I have a really crappy way of handling these errors in development.

The issue, AFAIK, is the `path` is not valid so macOS's URL resolution from the bookmark data fails. We can fall-back to just parsing the content from the Alias structure; it's lame.

Using the reference here: https://github.com/al45tair/mac_alias/blob/master/doc/alias_fmt.rst I have a simple loop to search for the POSIX path tag.
