### ISSUE TITLE
load query history while reopen `osqueryi`

### ISSUE THREAD

**Issue by TennyZhuang** [facebook/osquery#4012]
like `.bash_history`

**Comment by theopolis** [comment]
Normally, `osqueryi` should do this, if you look in:

```
ls -la ~/.osquery/.history 
-rw-------  1 reed  staff  6300 Dec 20 16:06 /Users/reed/.osquery/.history
```

They query history is in that file. If you hit (up) in `osqueryi` it will cycle through those queries.

**Comment by TennyZhuang** [comment]
Got it.

My `~/.osquery` is owned by root only, maybe I execute `osqueryi` by sudo firstly, I have `chown` on it.

Thanks
