### ISSUE TITLE
speculative info/PCID, cpuid flags on linux not consistent

### ISSUE THREAD

**Issue by juju4** [facebook/osquery#4043]
I see that a new table has been created https://github.com/facebook/osquery/commits/00040c6c1a7abbe8ed2ff3549eef8bb4a986b97d/osquery/tables/system/windows/kva_speculative_info.cpp

On Linux, system_info is parsing /proc/cpuinfo but does not return flags like PCID.
I can go through cpuid table but in some testing, I got invpcid but not pcid, even if /proc/cpuinfo has it (but not invpcid).

Comments?

Thanks

**Comment by mew1033** [comment]
+1

I was just examining the cpuid table for the PCID flag listed in `/proc/cpuinfo`. I see it in the file, but osquery doesn't pick it up. This (https://github.com/facebook/osquery/blob/master/osquery/tables/system/cpuid.cpp#L32-L64) makes it looks like it's only grabbing certain parameters.

**Comment by theopolis** [comment]
Right, it's only grabbing certain flags. If a flag is not in the CPUID table that means we did not test for it.

**Comment by mew1033** [comment]
@theopolis What are the chances of adding additional flags?

**Comment by juju4** [comment]
Thanks @theopolis !
