### ISSUE TITLE
Update Choco package?

### ISSUE THREAD

**Issue by Jackbennett** [facebook/osquery#4052]
Hi, I tried to have a poke around to get an answer first.

Is there a schedule to getting the choco package updated? currently it's 2.10.4 which isn't exactly old but it's marked a pre-release and I'd appreciate the easier time using event log support added in 2.11

Looked like the windows [jenkins queue is turned off](https://jenkins.osquery.io/view/All/job/osqueryMasterBuildWindows10/changes) possibly related to #3801

**Comment by muffins** [comment]
@Jackbennett ah truly sorry about that! We had a small hold up with our internal deployment so this fell behind. I just uploaded the package, and once it finishes verification (usually about 20 or 30 mintues) it'll be publicly listed: https://chocolatey.org/packages/osquery/2.11.0

Thanks for the ping, and please feel free to open if it doesn't show up shortly!
