### ISSUE TITLE
OS query logo is broken

### ISSUE THREAD

**Issue by mingrammer** [facebook/osquery#4057]
The logo image on  README is broken

**Comment by theopolis** [comment]
How so?

**Comment by mingrammer** [comment]
Why not do you fix it?

**Comment by mingrammer** [comment]
Official site using https://osquery.io/img/logo-2x.png as logo one. I think you should fix the current broken link with that

**Comment by mingrammer** [comment]
Cat I fix that it with PR?

**Comment by fiorix** [comment]
Yeah send in a PR

**Comment by mingrammer** [comment]
@fiorix Yes I will .. but, there is a problem I missed. Above image has `white` area, so the center of logo would not be shown correctly. The dark version is required.

**Comment by mingrammer** [comment]
Does osquery team has dark version one?

**Comment by fiorix** [comment]
I haven't looked but I assume there should be a png with transparent background.
