### ISSUE TITLE
Build version 2.11+ on FreeBSD

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#4059]
FreeBSD's port is a little behind. Here are the things we need to get it going again.

1. The `rocksdb-lite` port will need the following environment variables defined when building. `USE_RTTI=1`, `DISABLE_JEMALLOC=1`.
2. The `cpp-netlib` and `linenoise-ng` ports are no longer needed, `asio` is no longer needed either, if it is used.
3. The thrift library should be at version `0.11` or greater, it may be way behind, at something like `0.9.3` or `0.10.0`.

/cc @lxcode

**Comment by lxcode** [comment]
I pinged the thrift port maintainer. I'll test the changes to rocksdb-lite and commit those.

**Comment by lxcode** [comment]
Thrift has been updated to 0.11.0, and I should have the USE_RTTI/JEMALLOC changes in shortly. These are both still necessary, right?

**Comment by lxcode** [comment]
Ok, rocksdb and thrift are updated, and osquery has been brought up to date. Do note that I found that the build would fail without asio.

**Comment by theopolis** [comment]
I'm seeing issues with LLDPD:
```
[100%] Linking CXX executable osqueryd
-- Building osqueryd: /var/jenkins/workspace/osqueryPullRequestFreeBSD/TargetSystem/aws-freebsd-11/build/freebsd11.1/osquery/osqueryd
/usr/local/lib/liblldpctl.so: undefined reference to `__safestack_unsafe_stack_ptr'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
Similar to: https://github.com/HardenedBSD/hardenedBSD/issues/275

For LLDPD:
- Port: https://svnweb.freebsd.org/ports/head/net-mgmt/lldpd/Makefile?view=markup
- `--enable-hardening`: https://github.com/vincentbernat/lldpd/blob/master/configure.ac#L106

For now I'm going to change our builds to include `SKIP_LLDPD`.

**Comment by theopolis** [comment]
Some changes addressed in: https://github.com/facebook/osquery/pull/4166

**Comment by lxcode** [comment]
With the most recent LLDPD in the ports tree, it builds fine now. I think we can close this out regardless.
