### ISSUE TITLE
Add InRelease file to apt repository

### ISSUE THREAD

**Issue by pmahoney-raise** [facebook/osquery#4081]
In Ubuntu 17.10 with apt 1.5, I am unable to add osquery as a package source.

sources.list:
```
deb      [arch=amd64] "https://pkg.osquery.io/deb" deb main
```

what happens:
```
$ sudo apt-get update
...
Err:5 https://osquery-packages.s3.amazonaws.com/deb deb InRelease
  403  Forbidden
Reading package lists... Done
E: Failed to fetch https://pkg.osquery.io/deb/dists/deb/InRelease  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
$ echo $?
100
```

From [DebianRepositoryFormat](https://wiki.debian.org/DebianRepository/Format), I understand that `InRelease` is a version of `Release` with the gpg signature inline, rather than in the separate `Release.gpg`.

`apt-get` has logic to try `InRelease` and fallback to `Release`, but in apt 1.5 and newer, this fails for repositories hosted in s3, which returns http code 403 for the `InRelease` file, where apt was expecting 404.

See https://github.com/Debian/apt/commit/197c53951430bcb267ddd6e398439a8a5d9a83ad which suggests adding an `InRelease` file.

**Comment by lexelby** [comment]
403 is thrown because we don't have access to `ListBucket`.

**Comment by vpavic** [comment]
Any updates on this? I've ran into the same problem trying to install on Ubuntu 17.10.

Thanks.

**Comment by muffins** [comment]
Sorry, looks like this fell off of our radar a bit! We'll figure out what's up.

**Comment by fmanco** [comment]
This should be fixed now. Feel free to reopen if not.
