### ISSUE TITLE
Dead link README.md

### ISSUE THREAD

**Issue by simonsigre** [facebook/osquery#4088]
The link in README.md  for 'https://osquery.io/downloads' is incorrect it should be 'https://www.osquery.io/downloads/' (prefixed with www... for some reason?)

**Comment by simonsigre** [comment]
Looks to be a broader issue most links on the site that dont reference "www." are not working .. is there a 30x redirect missing for www --> @ ?

**Comment by muffins** [comment]
I think you've got the links flipped? There shouldn't be a `www` prefix, and it seems that the sites without the `www` are working, along with the links on the site. Can you check again to verify the links aren't working? As we just made the site change you've might've been experiencing some residual issues, but it seems to be working fine for me.

**Comment by simonsigre** [comment]
I’ve just tried again and the downloads link fails both time now (with and without www.)

**Comment by muffins** [comment]
I'm still not able to repro this. Tried visiting all of the links you have and I'm getting a valid site. The website itself is hosted here: https://github.com/osquery/osquery-site so perhaps we can file this issue there? Maybe it's been fixed recently? Looks like we've had quite a few commits relatively recently.

**Comment by muffins** [comment]
Ah! Looks like there's a good discussion happening about this in the Slack in #website. @simonsigre coudl you test _one more time_ and let us know if we're good? Seems like a fix went out. Going to close this issue but please let us know if it's still broken, thanks for the report!

**Comment by simonsigre** [comment]
Yeah it looks to be fixed now.
