### ISSUE TITLE
osquery-2.11.2.msi failed to install on Windows 10 French version

### ISSUE THREAD

**Issue by ogoudron** [facebook/osquery#4097]
I tried to install osquery-2.11.2.msi on two Windows 10 (Professional and Family).
Both Windows are FRENCH versions and up to date (version 1709 - 16299.192).
There's no AD domain controller and theses two machines are in "workgroup mode".
Installation was tried with a user having admin rights.

In both cases i have this error message :
"An error occurred while applying security settings. Users is not a valid user or group. This cloud be a problem with the package, or a problem connecting to a domain controller on the network. Check your network connection and click Retry or Cancel to end the install."

**Comment by obelisk** [comment]
Heyo, this might be related to the following issue: #4089 

Are there special characters in the username or group?

**Comment by ogoudron** [comment]
I installed from an admin user without any special character (hougouadmin) and this user is in the default admin group.
I supposed that it was related to a similar problem i encountered few months ago #3230.

Maybe you should inspect this file :
https://github.com/facebook/osquery/blob/master/tools/deployment/make_windows_package.ps1
And more specially this part :
<CreateFolder>
                <Permission User="Users" Read="yes"
                  ReadExtendedAttributes="yes" Traverse="yes"
                  ReadAttributes="yes" ReadPermission="yes" Synchronize="yes"
                  GenericWrite="no" WriteAttributes="no"/>
                <Permission User="Administrators" GenericAll="yes"/>
                <Permission User="SYSTEM" GenericAll="yes"/>
 </CreateFolder>
In French Windows versions, the group "Administrators" is replaced by "Administrateurs".

**Comment by obelisk** [comment]
Yep, that seems like it. We'll have to figure out a new way to do this. Thank you for reporting this!

cc: @muffins

**Comment by 1ihor1** [comment]
Hello,
Just FYI - I'm encountering a similar issue with Ukrainian and Russian Windows versions.
Regards,
Ihor

**Comment by muffins** [comment]
#4112 addresses this.
