### ISSUE TITLE
2.11.2 MSI uninstall does not remove any files

### ISSUE THREAD

**Issue by clong** [facebook/osquery#4099]
OS: Win 10
MSI: 2.11.2 downloaded from osquery.io

Installing the MSI with `msiexec /i osquery-2.11.2.msi` works great.
However, attempting to uninstall osquery with `msiexec /x osquery-2.11.2.msi` does not appear to remove any files (although it seems to remove the entry in programs and features)

**Comment by muffins** [comment]
Interesting. I just tested off of master, and it's removing the files that it's (the MSI) "touched". Below is before and after of the installation/uninstallation. I wonder if there's something using the file, thus preventing the MSI from uninstalling anything?
![after](https://user-images.githubusercontent.com/1328916/35938817-34007bd8-0bff-11e8-9b31-861f907894c0.PNG)
![before](https://user-images.githubusercontent.com/1328916/35938818-3428d7a4-0bff-11e8-8f8c-ad5f42cb4b01.PNG)

**Comment by muffins** [comment]
So even with using `msiexec` I get the same behavior, however it _is_ worth noting that I needed to stop the `osqueryd` service before the uninstallation would go through. @clong could you test stopping the service and see if that fixes? I can look into having the MSI do the service stop before attempting an uninstall rq, but I'm wondering if that's the only reason it's not removing any files?

**Comment by muffins** [comment]
Also tested running this with our internal corp configuration, which is pretty intense, and I still see all of the files removed, with the exception of the log and database directories and the pidfile.

**Comment by clong** [comment]
Totally strange - it must be something organizationally that is causing this to happen because you are correct - I just tried to repro on a fresh Win10 VM and uninstall works fine. Sorry about the false positive!
