### ISSUE TITLE
apt_sources does not return anything

### ISSUE THREAD

**Issue by fossam** [facebook/osquery#4104]
_select * from apt_sources ;_ 
does not return anything on Linux distros that use apt to manage their deb packages even though there are the default entries in /etc/apt/sources.list.

**Comment by fossam** [comment]
Clarification: apt_sources does not return anything in the currently published releases (2.11.0)
However, it does work on 3.1.0-50-g06117da0 .

**Comment by fmanco** [comment]
@fossam thanks for reporting this is fixed on master. I believe #4034 fixed this problem. I'll close this issue now but feel free to reopen if you have more questions.
