### ISSUE TITLE
osquery extensions which is relaying on 3rd party Kernel module

### ISSUE THREAD

**Issue by abazhaniuk** [facebook/osquery#4122]
Hi guys,

Try to understand how to write OSquery extensions which is relaying on 3rd party Kernel module.
So, I have scenario when my OSquery extensions need to talk to some 3rd party device.
In this case should i load driver before run OSquery or should my OSquery extensions load it when it will collecting data? 
For example we have chipsec tool (https://github.com/chipsec/chipsec), which is collecting a lot of data related to hardware/firmware. 
This tool has it's own driver. I want to write OSquery extensions which will use functionality from chipsec but it require someone to load chipsec driver. Is it suppose to be OSquery extensions  or someone else? 

Thanks,

**Comment by muffins** [comment]
Yeah osquery extension would work best for what you're looking for here, and I believe you'd only want to have the extension load the third party driver when it starts up, which osquery can do for you. So osquery will spawn your extension, which in turn will load your third party driver, from which you can now query the information, package, and ship back to osquery. Hope that helps!

I'd encourage you to checkout [our Slack](https://osquery-slack.herokuapp.com/) which should elicit some faster responses :)
