### ISSUE TITLE
Issues found when building with MSVC + /permissive-

### ISSUE THREAD

**Issue by PhoebeHui** [facebook/osquery#4123]
Build OSQuery with MSVC permissive- failed with error C2664, the issue in https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/bitlocker_info.cpp#L24 
The code snippet is
WmiRequest wmiSystemReq("SELECT * FROM Win32_EncryptableVolume", 
                          L"ROOT\\CIMV2\\Security\\MicrosoftVolumeEncryption"); 

One workaround is 
WmiRequest wmiSystemReq("SELECT * FROM Win32_EncryptableVolume", 
                       (BSTR)L"ROOT\\CIMV2\\Security\\MicrosoftVolumeEncryption"); 

Failures:
D:\OSQuery\src\osquery\tables\system\windows\bitlocker_info.cpp(24): error C2664: 'osquery::WmiRequest::WmiRequest(const osquery::WmiRequest &)': cannot convert argument 2 from 'const wchar_t [46]' to 'BSTR'

**Comment by muffins** [comment]
Thanks for reporting, we'll get on these :)

**Comment by obelisk** [comment]
#4131
