### ISSUE TITLE
Unreliable audit-based file integrity monitoring 

### ISSUE THREAD

**Issue by cocowalla** [facebook/osquery#4149]
I've cloned the git repo, built osquery from source, and am trying to get the new audit-based file integrity monitoring working on a CentOS 7 box.

I've stopped the default auditd daemon and have this in my config for options;

```
    "disable_events": "false",
    "disable_audit": "false",
    "audit_allow_config": "true",
    "audit_persist": "true",
    "audit_allow_process_events": "true",
    "audit_allow_fim_events": "true",
    "audit_allow_user_events": "true",
    "audit_allow_sockets": "true",
    "extensions_socket": "/tmp/audit_test",
    "verbose": "true",
    "log_result_events": "true",
    "enable_monitor": "true",
````
as well as this:
````
"file_paths": {
    "tmp": [
    "/tmp/test/%%"
  ]
}
````
When starting osquery, I see these lines in the output, which looks promising, other than the unexpected mention of inotify:
````
Enabling audit rules for the process_file_events table
Starting event publisher run loop: auditeventpublisher
Starting event publisher run loop: inotify
````

However, when I make changes to files in the monitored path, it seems that nothing is written to the `process_files_events` table. After a while I noticed that _sometimes_ a few events would be written, but with a delay of over _2 minutes_!

I notice however that the old inotify-based method still seems to be operating, as I see entries in the `file_events` table?

How can I reliably get FIM events from audit into the `file_process_events` table?

**Comment by clong** [comment]
@cocowalla can you share your config? Are you testing in osqueryi or just using the daemon + config?

**Comment by cocowalla** [comment]
@clong I think the relevant parts of my config were in my OP, but I've copied the whole thing to [this gist](https://gist.github.com/cocowalla/564163fee44d39b67cc1a14e4a5b3724). I did try playing around with the settings, but always got the same result.

I put it aside when I opened this issue, but I recall trying both osqueryi and the daemon, with the same results.

**Comment by fmanco** [comment]
Hi @cocowalla apologies for the only coming back to you now. If you're still looking into this, could you please run osquery in verbose mode and paste the results of a few seconds run (preferably while you change the files you're monitoring)? Thank you!

**Comment by fmanco** [comment]
Hi @cocowalla I'll close this since there is not activity, however if you're still having trouble feel free to re-open once you come back to this. Thanks!

**Comment by cocowalla** [comment]
Haven't had a chance to gather the info you requested yet - I'll try to follow up soon.

**Comment by fmanco** [comment]
No worries at all, just re-open once you have more information. Thanks!

**Comment by loqpa** [comment]
Hello @fmanco . I am facing the same problem. Should i post logs here or should i create new issue?

**Comment by abhayanoop** [comment]
@fmanco I'm facing a similar problem and I have opened a new issue for it - https://github.com/osquery/osquery/issues/6740
Please let me know if I'm doing something wrong. Your help is much appreciated. Thanks!

cc: @cocowalla  @loqpa

**Comment by fmanco** [comment]
@abhayanoop I'm no longer working on the project and don't have context on recent changes. I'm sure folks will be able to help you on your task. You can also ask for help in slack.
