### ISSUE TITLE
windows_events - invalid JSON in `data` column

### ISSUE THREAD

**Issue by mime-frame** [facebook/osquery#4164]
**Issue:**

The `windows_events` table captures invalid JSON in the `data` column.

Namely, occurrences of `\x0A` are to blame

This makes it difficult for downstream systems (like a SIEM) to parse and analyze the results.

**Example:**

```
{"EventData":{"<xmlattr>":"","AccountExpires":"%%1794","AllowedToDelegateTo":"-","DisplayName":"foo","Dummy":"-","HomeDirectory":"%%1793","HomePath":"%%1793","LogonHours":"%%1797","Name":"Dummy,TargetUserName,TargetDomainName,TargetSid,SubjectUserSid,SubjectUserName,SubjectDomainName,SubjectLogonId,PrivilegeList,SamAccountName,DisplayName,UserPrincipalName,HomeDirectory,HomePath,ScriptPath,ProfilePath,UserWorkstations,PasswordLastSet,AccountExpires,PrimaryGroupId,AllowedToDelegateTo,OldUacValue,NewUacValue,UserAccountControl,UserParameters,SidHistory,LogonHours","NewUacValue":"0x210","OldUacValue":"0x210","PasswordLastSet":"2\/24\/2018 3:23:11 AM","PrimaryGroupId":"513","PrivilegeList":"-","ProfilePath":"%%1793","SamAccountName":"hello","ScriptPath":"%%1793","SidHistory":"-","SubjectDomainName":"blah","SubjectLogonId":"0x3e7","SubjectUserName":"baz$","SubjectUserSid":"S-1-5-18","TargetDomainName":"baz","TargetSid":"S-1-5-21-123-123-123-123","TargetUserName":"foo","UserAccountControl":"-","UserParameters":"-","UserPrincipalName":"-","UserWorkstations":"%%1793"}}\x0A
```

**Comment by muffins** [comment]
@mime-frame yeah this was definitely an issue!  https://github.com/facebook/osquery/pull/3985 resolved this so the next stable release of osquery on Windows shouldn't have this.

**Comment by muffins** [comment]
Closing this out for now, feel free to re-open if you like :)

**Comment by mime-frame** [comment]
Nice! When's a new stable release for Windows happening @muffins

**Comment by muffins** [comment]
@mime-frame hopefully soon. I'm a little unsure on that as I haven't been at work for the past couple months, but we'll try to get something cut soon as we don't currently have a stable in 3.X yet.
