### ISSUE TITLE
Deleting osqueryd.exe (file is open in DHCP client)

### ISSUE THREAD

**Issue by kemalbayar** [facebook/osquery#4171]
after processed the command choco uninstall osquery, C:\programdata\osquery\osqueryd\osqueryd.exe file is still existed and when I try to delete file, I get the following warning...  What is the relationship between them?

![image](https://user-images.githubusercontent.com/33925821/36888574-1dc1dc26-1e07-11e8-990c-878bb594295d.png)

**Comment by muffins** [comment]
Interesting, haven't seen the daemon behave this way before. Are you able to reproduce this after a reboot? Can you try restarting your system, installing osquery via chocolatey as normal, and then uninstalling? Do you get the same issue?

**Comment by kemalbayar** [comment]
You seem to fixed it.

**Comment by muffins** [comment]
Closing this out as the issue seems stale. Feel free to re-open if you're still seeing this problem :)
