### ISSUE TITLE
PID value equals -1 in process_open_sockets using SUDO

### ISSUE THREAD

**Issue by bpruce** [facebook/osquery#4173]
osqueryd running as root is reporting pid=-1 for a majority of open network connections events. If i launch osqueryi running as root and use "select * from proces_open_sockets;"  all of the correct pid values are present. 

seems to be the same issue here but it was closed : https://github.com/facebook/osquery/issues/3625

Testing:
If i run curl www.google.com every event thats returned by osqueryd will be pid=-1.  Likewise I can capture this same event where running the same command then using osqueryi to find the connection. 
| -1   | -1 | 0      | 2      | 6        | xxx.xx.xx.xxx | 172.217.15.100 | 34720      | 80          |      |

i have 3 open ssh connections to the host running osquery and these appear to sometimes contain the real pid, and sometimes contain -1 value

While root running osqueryi if i run  "select * from proces_open_sockets where pid=-1;" it returns every result with pid and fd equal to -1. Run the same search again without the where clause and the correct pids are back.  

To help limit potential problem paths, I observed the same issue in the following:
(AWS)- ubuntu xenial, osquery 2.11
(GCP) - ubuntu xenial osquery 2.11
(AWS) ubuntu xenial running osquery 2.6.0 and 2.6.1
(on prem) - centOS6/7 running osquery 1.8.1 (I know, I'm sad too)
(on-prem) - ubuntu xenial running osquery 2.6.1

**Comment by bpruce** [comment]
perhaps the issue is an open socket being captured by the query that hasnt completely closed..so half open sockets(scanners for instance since im in aws), or an application that doesnt properly initiate socket close events?

**Comment by fossam** [comment]
I can confirm, happens on all _released_ versions. I cannot yet confirm this for recent versions where official default packages are not available.

**Comment by bpruce** [comment]
So I did a little more testing here, and I believe there are two unrelated issues. 1 issue relates to osqueryi where including the where clause "where pid=-1" is setting all pids to -1.  That seems like a bug. 

The other issue I think is more of a consequence of using open sockets and I would presume listening_ports acts the same way.  I setup a test ubuntu server and installed 2.11.0 as well as logstash and nothing else.  I set a single query "select * from process_open_sockets"; running every 5 seconds and then let it run over 24 hours.  Additionally I set up iptables to try and mirror the osquery activity being picked up from logstash sending out logs to my collector endpoint.  This was to try and attempt to determine when the pid=-1 values were being returned.  

IPtables:
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-A OUTPUT -p tcp -m tcp --tcp-flags FIN,SYN,RST,ACK SYN -m tcp --dport 443 -m state --state NEW -j LOG --log-prefix "New: "
-A OUTPUT -p tcp -m tcp --tcp-flags RST RST -m tcp --dport 443 -m state --state ESTABLISHED -j LOG --log-prefix "Rst: "
-A OUTPUT -p tcp -m tcp --tcp-flags FIN FIN -m tcp --dport 443 -m state --state ESTABLISHED -j LOG --log-prefix "Fin: "


Logstash has 3 connection exit scenarios from what I can see;  an Rst flag which cleanly closes a connection, Fin flag which cleanly closes a connection, and timeout or lost connection which is not clean.  The 3rd case seems to be the only time in which -1 pids are being returned.  This doesnt look like the only scenario that produces -1 pids. I also observed when scanners hit my host looking for an open ssh port these tended to produce -1 pids intermittently as well. Without looking closer, my guess is half open connection scanners vs attempting to actually complete tcp connection, but this is just a guess..

So this may not be "fixable", but I'm wondering if these two tables can implement a check during the diff stage and if all values queried match, and the new event has pid=-1 then silently ignore that event?  Sort of the first thing that pops to mind.

**Comment by fossam** [comment]
@bpruce does the `ss` command handles these situations correctly?

**Comment by bpruce** [comment]
Consider the following: 
sudo ss -pet | grep '172.31.16.119' (clipped)

LAST-ACK   0      32      ::ffff:172.31.16.119:58844                   ::ffff:<masked ip>:https                 timer:(on,8.020ms,7) ino:0 sk:69 ---
ESTAB      0      0       ::ffff:172.31.16.119:36222                 ::ffff:<masked ip>:https                 users:(("java",pid=11945,fd=87)) uid:999 ino:55984 sk:76 <->

I think process_open_sockets is picking these last-ack events up as a new event since it lost its inode ref and pid/program reference. This is logstash running as the only active device.  I can say for certain this is not a logstash only problem though as we see this on production hosts too.

**Comment by fossam** [comment]
Much of the underlying code seems to have changed in #4024 not too long ago, especially those parts we're having issues with. There doesn't seem to be a tag or a release yet that include those changes. Once available, those tables need to be tested again.

**Comment by fmanco** [comment]
@fossam Can tou take another look at this with 3.2.4? Thanks!

**Comment by fossam** [comment]
Yes, it is still there. Tested with both 3.2.4 and 3.2.5.
```
$ osqueryi --line  " select * from process_open_sockets where pid=-1 ; "
           pid = -1
            fd = -1
        socket = 0
        family = 2
      protocol = 6
 local_address = 192.168.122.63
remote_address = 52.x.y.z
    local_port = 53609
   remote_port = 80
          path = 
         state = TIME_WAIT
 net_namespace = 4026531956

           pid = -1
            fd = -1
        socket = 0
        family = 2
      protocol = 6
 local_address = 192.168.122.63
remote_address = 52.x.y.z
    local_port = 53610
   remote_port = 80
          path = 
         state = TIME_WAIT
 net_namespace = 4026531956
```

**Comment by fmanco** [comment]
Oh, I see. I think it is because the process for this socket no longer exists which makes sense because the socket is in `TIME_WAIT`. Can you confirm that with something like netstat?

**Comment by fossam** [comment]
Ah yes, thanks for catching that. The box contacts the remote host frequently so it was in the ```TIME_WAIT``` state. From the output below it's obvious that only those sockets are returned and it looks that the bug is gone.

```
ss -tauepnn 
Netid  State      Recv-Q Send-Q                  Local Address:Port                                 Peer Address:Port              
udp    UNCONN     0      0                                   *:68                                              *:*                   users:(("dhclient",pid=642,fd=6)) ino:15089 sk:ffff88007861ec00 <->
udp    UNCONN     0      0                                   *:36135                                           *:*                   users:(("dhclient",pid=642,fd=20)) ino:15066 sk:ffff88007861e800 <->
udp    UNCONN     0      0                                  :::30666                                          :::*                   users:(("dhclient",pid=642,fd=21)) ino:15067 sk:ffff88007bde4000 v6only:1 <->
tcp    LISTEN     0      128                                 *:22                                              *:*                   users:(("sshd",pid=858,fd=3)) ino:16061 sk:ffff88007ba08000 <->
tcp    LISTEN     0      100                         127.0.0.1:25                                              *:*                   users:(("master",pid=955,fd=13)) ino:16625 sk:ffff88007ba08780 <->
tcp    TIME-WAIT  0      0                      192.168.122.63:49804                                 52.x.y.z:80                  timer:(timewait,41sec,0) ino:0 sk:ffff88007a3ee000
tcp    TIME-WAIT  0      0                      192.168.122.63:49805                                 52.x.y.z:80                  timer:(timewait,42sec,0) ino:0 sk:ffff88007a3eeb00
tcp    ESTAB      0      0                      192.168.122.63:22                                  192.168.122.1:37842               users:(("sshd",pid=961,fd=3)) timer:(keepalive,50min,0) ino:17157 sk:ffff88007ba08f00 <->
tcp    LISTEN     0      128                                :::22                                             :::*                   users:(("sshd",pid=858,fd=4)) ino:16070 sk:ffff88007b690000 v6only:1 <->
tcp    LISTEN     0      100                               ::1:25                                             :::*                   users:(("master",pid=955,fd=14)) ino:16626 sk:ffff88007b690840 v6only:1 <->
```
Since centos 7 by default doesn't come anymore with the _netstat_ command i used _ss_.

**Comment by fmanco** [comment]
Awesome, I'll close then. If you find out this is happening for a case where the process still exists then feel free to re-open. Thanks!
