### ISSUE TITLE
docker socket behind a proxy does not return data

### ISSUE THREAD

**Issue by fossam** [facebook/osquery#4179]
In cases where the Docker socket is fronted by a proxy that does not return with HTTP/1.0 osquery does not return data. The check is likely in the following line: 
https://github.com/facebook/osquery/blob/1e432dcd4c287807f37d7fe28a8ae9a2316e8af1/osquery/tables/applications/posix/docker.cpp#L86

For example, we've seen the following behavior:
> sendmsg(7, {msg_name(0)=NULL, msg_iov(1)=[{" HTTP/1.0\r\nAccept: */*\r\nConnection: close\r\n\r\n", 45}],
> recvmsg(7, {msg_name(0)=NULL, msg_iov(1)=[{"HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nDate: Wed, 28 Feb 2018 22:22:57 GMT GMT\r\nContent-Length: 53446\r\n\r\n ...

Would it be possible to create a workaround where the ```HTTP/1.1``` returns are also accepted by osquery?

**Comment by spasam** [comment]
Forgot who it was, but someone on slack had same issue. We can relax the HTTP/1.0 response assertion. Although I have no idea why HTTP/1.1 is returned for 1.0 request :laughing:

**Comment by fossam** [comment]
That was me.
Unfortunately it's a closed source app that behaves this way - getting it changed in a timely manner would be difficult at best.

**Comment by spasam** [comment]
Yep, that is what I figured. Unless you already fixed docker.cpp, I can take a stab it this.

**Comment by fossam** [comment]
It would be greatly appreciated if you do.
Hopefully it will get into upcoming release.

**Comment by spasam** [comment]
https://github.com/facebook/osquery/pull/4180

**Comment by spasam** [comment]
This can be closed now!
