### ISSUE TITLE
How to output message to kafka as json instead of a string value of message property? 

### ISSUE THREAD

**Issue by jjqq2013** [facebook/osquery#4198]
HI, 
When use kafka output, the result sent to kafka is:

```
{
  "_index": "osquery-2018.03.16",
  "_type": "logs",
  "_id": "AWItCTVn_159CzEuQH4F",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2018-03-16T04:20:00.984Z",
    "@version": "1",
    "message": "{\"name\":\"logged_in_users\",\"hostIdentifier\":\"unittest05node1\",\"calendarTime\":\"Fri Mar 16 04:20:00 2018 UTC\",\"unixTime\":\"1521174000\",\"epoch\":\"0\",\"counter\":\"4\",\"columns\":{\"host\":\"\",\"pid\":\"2066\",\"time\":\"1521170533\",\"tty\":\"pts\\/2\",\"type\":\"dead\",\"user\":\"\"},\"action\":\"added\"}"
  },
  "fields": {
    "@timestamp": [
      1521174000984
    ]
  },
  "sort": [
    1521174000984
  ]
}
```

You can see all actual information is stored as a string in message property.

How can configure osquery to output a json object inside it?

Is there a limitation that osquery plugin framework can only let you fill the string in message property instead of expand it as a json sub object?

**Comment by muffins** [comment]
Hey there! This might be a question better [answered in our Slack](https://osquery-slack.herokuapp.com/). Hop in and throw this to the #general channel and you should get some good responses. I'm going to close this out for now, but feel free to re-open if you're still having issues :)
