### ISSUE TITLE
FR: osqueryd service recovery

### ISSUE THREAD

**Issue by kemalbayar** [facebook/osquery#4200]
could be made an improvement ? It might be useful

![image](https://user-images.githubusercontent.com/33925821/37524948-730fd422-293c-11e8-8b3a-23fa273d0df3.png)

**Comment by muffins** [comment]
That is a good question. My immediate thoughts on this are that a typical deployment already makes use of the watchdog, which itself has recovery mechanisms for the worker. If the Windows service is failing to start, it's most likely the case that there's unsafe file permissions or some other misconfiguration is preventing the daemon from starting, and thus the attempts at a service recovery would fail anyhow. Do you have any particular requested recovery actions you'd be interested in seeing?

**Comment by kemalbayar** [comment]
is osqueryd.exe controlled by the osqueryd service? (the service runs the command \programdata\osquery\osqueryd\osqueryd.exe --flagfile=\programdata\osquery\osquery.flags in the background).
If the service fails any way, osqueryd.exe (and the watchdog) does not run anymore. therefore isn't it a need to configure service recovery?

**Comment by muffins** [comment]
This was addressed with #4565
