### ISSUE TITLE
'process_open_sockets' table does not show the sockets opened inside a docker container

### ISSUE THREAD

**Issue by sanghyunhong** [facebook/osquery#4205]
Hello Guys, 

It seems like the 'process_open_sockets' table does not include the information about the sockets opened at docker containers. The problem can be reproduced by the sequence below:

- Install the osquery and docker at an AWS EC2 instance.
- Run the Ubuntu container by the command `docker run -it ubuntu`
- Run the `osqueryi --json "select * from process_open_sockets" > <state-before>`
- Make the outbound connection at the Ubuntu container shell: `wget www.google.com`
- Run the `osqueryi --json "select * from process_open_sockets" > <state-after>`
- Compare the <state-before> and the <state-after>

I found that there is no connection information recorded by the command `wget`. Is it a normal behavior (correct me if I am wrong)?

S.

**Comment by Ngo-The-Trung** [comment]
I think (haven't verified) it's because the docker daemon launches the docker process as root and thus their resources can't be seen by user processes.

**Comment by fmanco** [comment]
Hi @sanghyunhong, apologies for the delay.

What version of osquery are you using? Sockets open inside containers are in their own network namespace. Until recently osquery wasn't looking into those but that should be functioning in the latest version.

If this is not working with 3.2.2 please let us know.

**Comment by fmanco** [comment]
I'm closing this since there is not activity. Feel free to re-open if needed.
