### ISSUE TITLE
rapidjson: query results migration issue after 3.1.0+

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#4206]
Results stored with PTREE use the improper JSON form:
```
queries[dns_resolvers]: {"":{"address":"8.8.8.8","id":"0","netmask":"32","options":"524993","type":"nameserver"},"":{"address":"8.8.4.4","id":"1","netmask":"32","options":"524993","type":"nameserver"},"":{"address":"","id":"0","netmask":"","options":"524993","type":"search"}}
```
These will need to be converted to proper JSON.

One method, use a trace variable in the DB, `resultsversion=1` if you don't find this then run the migration, load the results using PTREE, then for each row place them into a RapidJSON object and finally write out the results.

**Comment by muffins** [comment]
#4207 addressed this.
