### ISSUE TITLE
querying IP

### ISSUE THREAD

**Issue by kemalbayar** [facebook/osquery#4209]
There are three table to get the IP of the agent; interface_addresses and Interface_details and routes table but simply I want to add the IP addres(es) of the each agent to the log(json).

to do this, I used decorator feature but I have to use such a query like that
select address as IP_Address from interface_addresses where address like '10%';
because the tables contains mixed content so I have to filter.

![image](https://user-images.githubusercontent.com/33925821/37661316-93ec38b2-2c65-11e8-913d-f337c98bc6d0.png)

is there a more simple way to get the IP address(es) of agents without using such the query like above?

**Comment by muffins** [comment]
@kemalbayar try using a join on the `interface` column:
```
select * from interface_details id join interface_addresses ia on ia.interface = id.interface;
```
We also have the #sql channel in the slack, where this question might get answered faster :)

**Comment by kemalbayar** [comment]
@muffins  :)
