### ISSUE TITLE
no result from "select * from startup_items"

### ISSUE THREAD

**Issue by jjqq2013** [facebook/osquery#4227]
Is there anyone really get any result from table "startup_items" in linux now?

I am sure I'v ever successfully called "select * from startup_items;" from osqueryi and get several line output, such as a job from cron.

But now, it output nothing.  Both for 2.11.0 and 2.11.2, ubuntu xenial or centos7.4.

```
[root@host ~]# osqueryi --verbose "select * from startup_items;"
I0329 02:14:46.981292 25132 init.cpp:368] osquery initialized [version=2.11.0]
I0329 02:14:46.981323 25132 extensions.cpp:300] Could not autoload extensions: Failed reading: /etc/osquery/extensions.load
I0329 02:14:46.981341 25132 init.cpp:597] Cannot start extension manager: Extensions disabled
I0329 02:14:46.993332 25132 smbios_tables.cpp:102] Reading SMBIOS from sysfs DMI node
I0329 02:14:46.993628 25132 events.cpp:1078] Error registering subscriber: socket_events: Subscriber disabled via configuration
```

```
[root@host ~]# find /etc/cron.* -type f |xargs grep chef
/etc/cron.d/sysstat:# managed by chef-client
/etc/cron.d/cron_usercreation:0 */6 * * * root /usr/bin/chef-client -o users
```

Any idea?

**Comment by muffins** [comment]
This is happening for me also on Ubuntu 17.04

**Comment by Ngo-The-Trung** [comment]
The table is [empty](https://github.com/facebook/osquery/blob/master/osquery/tables/system/linux/users.cpp#L88)

**Comment by guliashvili** [comment]
Hi,
I will be working on that. Will let you know the updates.

**Comment by fmanco** [comment]
@guliashvili Thanks for working on this.

**Comment by fmanco** [comment]
The empty implementation was removed by #4373 and implementing this for linux is going to be tracked on #4392 so closing this now.
