### ISSUE TITLE
osquery.flags table: values aren’t matching with currently active values

### ISSUE THREAD

**Issue by kemalbayar** [facebook/osquery#4243]
when I run the query  select * from osquery_flags;
I noticed that some columns isn't matching with my current configuration in osquery.flags

for example: for Windows_event_channels, 

default value
System,Application,Setup,Security and value

value
System,Application,Setup,Security and value

but my current config is that: Windows powershell, Security in osquery.flags file

**Comment by muffins** [comment]
@kemalbayar can you verify that osquery is actually loading up your flagfile? Seems like osquery might be having an issue parsing out the values you've set. Further, can you keep questions regarding your deployment to Slack? If this really is an issue, let's iron out the details in Slack first, and cut a GH issue regarding the actual problem.

**Comment by muffins** [comment]
Didn't mean to close that out, my apologies. Can you verify that osquery is actually parsing your flags? If you're seeing different values in the osquery flags table it's likely there's something wrong with your flagsfile.

**Comment by kemalbayar** [comment]
I noticed that the query 'select * from osquery_flags', reads the 'osquery.flags.default' flag file.
Steps I've taken:
I copied osquery.flags file as osquery.flags.default and I noticed the situation when I ran the query again

**Comment by fmanco** [comment]
Hi @kemalbayar `osquery.flags.default` is the default file osquery uses when no flags file is provided. Did you try something like `osqueryi --flagfile=/path/to/osquery.flag 'select * from osquery_flags;'` and see what that yields?

If this still doesn't work please provide the output of `osqueryi --verbose 'select * from osquery_flags;'` (notice the verbose) and the contents of both flags files.

Thank you!

**Comment by fmanco** [comment]
Hi @kemalbayar I'll close this since there is not activity, but feel free to re-open if you come back to this and are still having issues. Thanks!
