### ISSUE TITLE
investigate schema changes to log json in 3.x

### ISSUE THREAD

**Issue by groob** [facebook/osquery#4251]
Following up from a conversation in the #core channel in slack. 

I'm playing with 3.2.0 and I'm seeing that column values are still always strings. Is that going to change with RapidJSON?
For example, (with 3.2 osquery)

```
{
  "diffResults": {
    "removed": [],
    "added": [
      {
        "description": "victor",
        "directory": "/Users/victor",
        "gid": "20",
        "gid_signed": "20",
        "shell": "/bin/zsh",
        "total_seconds": "366459",
        "uid": "501",
        "uid_signed": "501",
        "username": "victor",
        "uuid": "00A4617C-AC3A-4CEC-95F4-3143161820DA"
      }
    ]
  },
  "calendarTime": "Sun Apr  1 18:37:10 2018 UTC",
  "unixTime": 1522607830,
  "epoch": 0,
  "counter": 0
}
```

`uid, gid, uid_signed, total_seconds` are all BIGINT columns, yet the json for all the rows shows these as a map of strings. 

Is the intention for 3.x to address the JSON types of osquery table columns? Or are these intended to stay as strings?

**Comment by zwass** [comment]
And if the types do change, will proper `null` values be introduced?

**Comment by obelisk** [comment]
I believe all row values are staying as strings because the underlying datatype (Row) is a std::map<std::string, std::string> which is what is passed to our RapidJSON serializer.

**Comment by groob** [comment]
That sounds good to me.
