### ISSUE TITLE
Compilation failure with NixOS

### ISSUE THREAD

**Issue by Infinisil** [facebook/osquery#4257]
I'm trying to update osquery for NixOS but I'm getting some errors when compiling:

    /build/source/osquery/utils/aws_util.h:197:54:
      error: invalid initialization of reference of type 'std::__cxx11::string& {aka std::__cxx11::basic_string<char>&}'
      from expression of type 'Aws::String {aka std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> >}'
        Status s = getAWSRegion(client_config.region, sts);
                                                         ^

    /build/source/osquery/logger/plugins/aws_firehose.cpp:79:59:
      error: no matching function for call to 'Aws::Firehose::Model::PutRecordBatchRequest::WithDeliveryStreamName(fLS::clstring&)'
        request.WithDeliveryStreamName(FLAGS_aws_firehose_stream)
                                                                ^

    /build/source/osquery/utils/aws_util.h:202:26:
      error: no match for 'operator=' (operand types are 'Aws::String {aka std::__cxx11::basic_string<char, std::char_traits<char>, Aws::Allocator<char> >}'
      and 'const string {aka const std::__cxx11::basic_string<char>}')
        client_config.region = region;
        ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~

    /build/source/osquery/logger/plugins/aws_kinesis.cpp:90:50:
      error: no matching function for call to 'Aws::Kinesis::Model::PutRecordsRequest::WithStreamName(fLS::clstring&)'
        request.WithStreamName(FLAGS_aws_kinesis_stream).SetRecords(batch);
                                                       ^

Along with a bunch more. The full logs of the compilation can be found [here](https://gist.github.com/7d9f16f474a8deb7a032812874761157).
If you have Nix you can reproduce the problem with this (https://github.com/infinisil/osqueryRepro):

```
nix-build https://github.com/infinisil/osqueryRepro/archive/master.tar.gz
```

I'm using osquery3.2.2, gcc7.3, aws-sdk-cpp1.4.24 (with API's firehose, kinesis, sts and ec2). Changing to aws-sdk-cpp1.2.7 as specified here https://github.com/facebook/osquery/blob/9797276fc8f38d5be3ceba44ec39e0816cf2d820/tools/provision/formula/aws-sdk-cpp.rb#L7 made no difference to the errors, so I think we can assume the aws api is backwards compatible regarding that.

**Comment by Infinisil** [comment]
Ping @cstrahan as he was the one who initially packaged (https://github.com/NixOS/nixpkgs/pull/27347) osquery for NixOS, the build is however broken now. @cstrahan: To see whether your patches were necessary with the new major version, I started with a fresh nix expression, it seems to not require them. I also needed to fix the rocksdb_lite package (see https://github.com/NixOS/nixpkgs/pull/38415).

**Comment by muffins** [comment]
Ah, we currently have an issue open to upgrade the AWS package that we have, and that looks like it might be what's wrong here.

**Comment by Infinisil** [comment]
@muffins As already mentioned, switching to 1.2.7 doesn't change any of the errors, and looking at [aws-sdk-cpp's changelog](https://github.com/aws/aws-sdk-cpp/blob/master/CHANGLOG.md) this makes sense, as there weren't any related breaking changes.

Hoping somebody has some slight clue as to what could cause this error.

**Comment by Infinisil** [comment]
https://github.com/NixOS/nixpkgs/pull/39336
