### ISSUE TITLE
Clarification Request - Are contributions licensed under GPLv2 ?

### ISSUE THREAD

**Issue by spectejb** [facebook/osquery#4258]
"By contributing to osquery, you agree that your contributions will be licensed under both the LICENSE file and the COPYING file in the root directory of this source tree. " 

Am I interpreting this correctly to mean that any contributions made to osquery will be licensed under Apache 2.0 and GPLv2?  If so, can you help me understand how the project can be Apache 2.0-licensed when ultimately including a GPLv2 open source component would require the entire project to be GPLv2-licensed? 

Thanks, in advance, for your help!

**Comment by muffins** [comment]
@spectejb @theopolis might be able to correct me here if this is wrong, but contributions to the osquery project are licensed under _both_ Apache 2.0 and GPLv2, and upon _using_ the project code you _decide_ which licensing you'd like to use and move forward with that. I know we have this documented somewhere but I haven't been able to track that down.

**Comment by spectejb** [comment]
Thank you for the quick response, @muffins !  

I did a quick search about the license compatibility and found [this site](https://www.apache.org/licenses/GPL-compatibility.html) which includes a lot of helpful info on the topic, including the following:

"The ASF will not dual-license our software because such licenses make it impossible to determine the conditions under which we have agreed to collaborate on a collective product, and are thus contrary to the Apache spirit of open, collaborative development among individuals, industry, and nonprofit organizations."

@theopolis @muffins - What are your thoughts on licensing the entire project (use + contributions) as Apache 2.0?  Big fan of the project and this update would definitely allow us to contribute more in a corporate environment.

**Comment by spectejb** [comment]
@theopolis @muffins - Since everyone has a lot they are balancing, wanted to check in on this issue.  Thanks!

**Comment by muffins** [comment]
@spectejb I'll reach out to our open source teams to try and get clarification on that, unless @theopolis  recalls what the issues were, but I don't believe we are capable of moving to a purely Apache 2.0 license at this time.

**Comment by theopolis** [comment]
Hello, the information here is good! You as the user of osquery can choose what license you want to use. I like the ASF's opinion on dual licenses, it is valid. Keep in mind that osquery is not a ASF project and we have no plans on becoming one.

We feel pretty strongly that we should give users the choice of ASL 2.0 or GPLv2. This does mean if you are contributing code you allow us to extend the same choice to people using that code as part of the project's license.

> Big fan of the project and this update would definitely allow us to contribute more in a corporate environment.

Thanks! 🎉 Can you explain the specifics here? I am not aware of how the choice limits the usability or ability to contribute. Feel free to reach out to me at reed@fb.com :)

PS. You, or your company, will also have to sign our contributor license agreement: https://code.facebook.com/cla/corporate if you would like to contribute.

**Comment by spectejb** [comment]
I appreciate the additional context, @theopolis!  I had never seen a license description for a contribution like this before but it makes sense now.  Ultimately, the CLA will govern and the contributor should be aware that someone may choose a GPL or Apache license for the project, if needed.  Many thanks also to @muffins as well.
