### ISSUE TITLE
Incomplete interface flags on Linux

### ISSUE THREAD

**Issue by fmanco** [facebook/osquery#4272]
#4063 changed the way flags are captured for network interfaces on linux. Before, flags would come from `getifaddrs`. With this PR flags are now read from '/sys/class/net/<dev>/flags'.

The problem is that not all flags are exported via `sysfs`, namely `volatile` flags as you can see at https://github.com/torvalds/linux/blob/master/include/uapi/linux/if.h.

We need to either revert to the old method or get this information from somewhere else. At least some information is exported via other files in `sysfs`.

**Comment by fossam** [comment]
I filed the original bug that started the change to sysfs. The problem with the old way was that it wasn't correctly representing the promiscuous mode set in a common way. If at all possible, let's try to settle on a solution that preserves a way to accurately expose the promiscuous mode.

**Comment by fmanco** [comment]
Hi @fossam thanks for the tip. I'll make sure I don't break that. I think the solution will be to get the missing information from other sources, but I still need to investigate.
