### ISSUE TITLE
file table needs max depth of processing 

### ISSUE THREAD

**Issue by SAlexandru** [facebook/osquery#4293]
Running osquery 2.11.2, Mac OS High Sierra
You can create a symlink folder loop (the easiest is to create a symlink to the current folder) 
When you try to query the file table for information of all the files in that path, osqueryi will die with 

> terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::status: Too many levels of symbolic links

The easiest is to add max depth of search for queryies that contain `SELECT * FROM file WHERE path LIKE '/Applications/%%%'`

**Comment by fmanco** [comment]
Fixed on latest version.
