### ISSUE TITLE
windows msi packaging

### ISSUE THREAD

**Issue by Apptestingrd** [facebook/osquery#4299]
I generated my custom msi package using the following scripts

.tools/make-win64-dev-env.bat
.\tools\make-win64-binaries.bat
.tools/deployment/make_windows_package.ps1

I've encountered some issues

1-   I installed osquery to windows server 2012 using the msi package which I generated by the scripts but it is seen as "incoming host" waiting in this way continiously on Kolide. No problem with the msi package downloaded from official site. I mentioned previously the errors i got when I generating the msi package but told me that it was no problem with the errors. _(full script output is attached)_

2-I installed osquery using the same msi package to windows 10, in this case it become online state but when performing a distributed query it fails _(as shown in the image)_

3- on the agent which I installed the same osquery package generated by the scripts, it still appears an osquery process in taskmgr despite the osquery is uninstalled from the machine _(as shown in the image)_

![screen shot 2018-04-17 at 16 25 43](https://user-images.githubusercontent.com/38127874/38922463-e4719f0a-4300-11e8-8d52-57f9fa791891.png)

![screen shot 2018-04-17 at 16 32 37](https://user-images.githubusercontent.com/38127874/38922468-e811a4ca-4300-11e8-8f42-53b5d446fa8c.png)

full script output:
[output.pdf](https://github.com/facebook/osquery/files/1923200/output.pdf)

**Comment by Apptestingrd** [comment]
I've repeated the test, the packgage generated by the scripts is now **3.2.3** (previously 3.2.2)
the distributed query problem is still occuring.

also you may want to know that I see some old config\queries in the output of osquery agents (--verbose --tls_dump=true) 
but that's a different situation showing up that there is a problem with Kolide

**Comment by obelisk** [comment]
This seems like a Kolide error. @zwass could you take point on this?

**Comment by zwass** [comment]
@Apptestingrd if you are having issues with Fleet, please file them in the https://github.com/kolide/fleet repo.

**Comment by Apptestingrd** [comment]
I haven't encountered the problem since I build using git checkout tags/2.11.2

**Comment by Apptestingrd** [comment]
@obelisk i want to ask you before file an issue

after i uninstall the osquery using add/remove control panel, i see "Windows installer" process in task manager's background process section (this is actually windows installer service and this service default is in Manual state on windows os)

is it normal behaviour that this service is in Running state after osquery uninstalled?
