### ISSUE TITLE
Scheduler loop loses time

### ISSUE THREAD

**Issue by jkeljo** [facebook/osquery#4301]
https://github.com/facebook/osquery/blob/483fbbb594fe7172d6c008e1a018eb9c107ba99e/osquery/dispatcher/scheduler.cpp#L154

The loop variable used by the scheduler is supposed to be the time, but it tracks time imprecisely and generally loses time. This is because `i` is incremented by the loop, and the loop generally runs for *at least* one second (the `pauseMillis(1000)` call plus however long any queries take to run. (The slower the query, the further behind the loop will fall.)

This likely doesn't matter much for detection scenarios, but I've been using osquery for more performance-monitoring cases, which has meant more frequent (and sometimes higher-overhead) queries that can result in larger slips. I'd prefer to see logic where on each run through the loop it would execute (once) any queries that were scheduled to run at least once since the last start-of-loop timestamp. That way a single slow query could delay another query scheduled during the same time window, but would not have a cascading impact on other queries.

**Comment by fmanco** [comment]
Hi @jkeljo, yeah it looks you're correct, but I'm not sure I follow the solution you're proposing. Could you please explain?

**Comment by theopolis** [comment]
Right, osquery intervals are loosely based on time. And time is a seed as to where to start incrementing.

> This likely doesn't matter much for detection scenarios

Right!

> but would not have a cascading impact on other queries

I think real-time query intervals are doable. You can use a `rt-interval` or a boolean `realtime: True` to distinguish.

**Comment by jkeljo** [comment]
@fmanco, I'm imagining a priority queue of queries ordered by next run time. Then the scheduler loop looks something like (pseudocode):

```
while (!should_stop) {
  current_time = get_current_time();
  query = queue.peek();
  if (query.next_run_time <= current_time) {
    queue.dequeue();
    query.run();
    while (query.next_run_time <= current_time) {
      // If some previous query was really slow, this might skip multiple intervals. That's OK;
      // it's like dropping a frame in an animation
      query.next_run_time += query.interval;
    }
    queue.enqueue(query);
    current_time = get_current_time();  // Refresh current time so we don't oversleep
  }
  next_query = queue.peek();
  sleep(next_query.next_run_time - current_time);
}
```

@theopolis something like the above wouldn't need queries to opt-in; is there a concern with doing it this way?

**Comment by jkeljo** [comment]
Oh, forgot to mention... if the main loop is written that way, it's probably not just queries, but various kinds of tasks. (E.g. the first loop has some logic to update the decorators every 60 seconds; that could just be another task with a 60-second interval.)

**Comment by akindyakov** [comment]
Hi @jkeljo , does PR #4393 solve this problem? Is here something else to do in terms of this issue?

**Comment by guliashvili** [comment]
@jkeljo ping

**Comment by jkeljo** [comment]
I think #4393 is good enough for now.
