### ISSUE TITLE
handles leak in genMemoryMap under windows

### ISSUE THREAD

**Issue by redplait** [facebook/osquery#4317]
it seems that handle after OpenProcess does not closing in https://github.com/facebook/osquery/blob/master/osquery/tables/system/windows/processes.cpp

**Comment by obelisk** [comment]
Heyo,

I'll try to take a look at this later today, Windows is not generally my wheelhouse though so it might take me a little longer.

**Comment by redplait** [comment]
you could just add line like
CloseHandle(proc);
before each return
