### ISSUE TITLE
Extend /etc/hosts to include hosts.ics for Windows

### ISSUE THREAD

**Issue by cryps1s** [facebook/osquery#4330]
I'd like to request the etc_hosts table be expanded to also include the contents of the "hosts.ics" file in Windows. This file is dynamically generated and modified by the internet connection service (ICS), and is used primarily by ICS and Hyper-V. 

This file can be malicious modified as a more stealthy hosts file override. The end goal of this FR would be to include changes to the hosts.ics file as part of the normal "etc_hosts" table for Windows systems.

Details on this issue can be found here: http://www.hexacorn.com/blog/2018/03/31/the-little-known-i-think-secret-of-hosts-ics/

**Comment by dhaynespls** [comment]
I was checking this issue out, specifically in 

https://github.com/facebook/osquery/blob/master/osquery/tables/networking/etc_hosts.cpp

Would the ideal route to go about this to be modifying `kEtcHosts` to be a list in the windows case to hold both files to parse? Given they contain the same data and layout it would make sense to handle them equally, but just as another iteration step in `parseEtcHostsContent`.

**Comment by dhaynespls** [comment]
This got closed by #4686
