### ISSUE TITLE
Build issues using Xcode

### ISSUE THREAD

**Issue by avaneendra** [facebook/osquery#4342]
Hi
 I am running into build issues with xcode. I see these errors;

The build must define OSQUERY_BUILD_SDK_VERSION.
What should be the value for these?
#if !defined(OSQUERY_BUILD_SDK_VERSION)
#error The build must define OSQUERY_BUILD_SDK_VERSION.
#elif !defined(OSQUERY_BUILD_PLATFORM)
#error The build must define OSQUERY_BUILD_PLATFORM.
#elif !defined(OSQUERY_BUILD_DISTRO)
#error The build must define OSQUERY_BUILD_DISTRO.
#endif

#include "osquery/core/windows/wmi.h" osquery/core/windows/wmi.h' file not found

Appreciate help 

thanks
-Avaneendra

**Comment by obelisk** [comment]
How are you building with XCode? We generally don't support building with it and use CMake. You can have cmake generate an XCode project if you'd like but there are also some build issues there which haven't been ironed out. See PR #4178

**Comment by avaneendra** [comment]
Thanks Obelisk. Checking out the PR#4178

**Comment by obelisk** [comment]
This is not something we're supporting right now so I'm going to close this issue. If we want to support it more broadly let's open an issue to that effect or continue discussion on the PR.
