### ISSUE TITLE
osquery::getFqdn() may not use correct logic on macOS

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#4371]
(Reporting this on behalf of other users, so I don't have the most specific details. Hopefully we can get clarification from them.)

In multiple instances reported recently, users have found unexpected names for `hostname` in `system_info`. It looks like these are associated with edits to the `hosts` file.

See [chat transcript](https://osquery.slack.com/archives/C1XCLA5DZ/p1524786088000314) with @clong for example.

We saw another report from a user that they modified their `resolv.conf` and this affected the hostname reported by osquery (sorry I don't have more details on this one).

@theopolis I see you made some changes to this in https://github.com/facebook/osquery/pull/3846. Is some of our logic incorrect here?

**Comment by groob** [comment]
I can repro the issue on darwin. It appears that the `hostname` value behaves different depending on which values I have set.

If I `sudo scutil --set HostName "foobar"`, then `hostname` becomes`foobar`.
if I `sudo scutil --set HostName ""` then `hostname` becomes the value of `LocalHostname` and then `ComputerName` in that order. 

If I clear both of those, it becomes `macbook-pro.local`.

**Comment by fmanco** [comment]
Looking at #3846 it seems that we at least have a naming problem here. I don't have enough historical context so maybe @theopolis can help, but `hostname` is in fact a FQDN and `computer_name` a simple hostname. `local_hostname` is weird because it is the same as `hostname` for

**Comment by theopolis** [comment]
RIght. `hostname` in our case is the FQDN. This was the original intent of the column and we fixed (or tried to fix at least) this in #3846. We invented the `computer_name` to better identify the short "name" of a computer/host. `local_hostname` is something unique to macOS. I don't have strong opinions beyond keeping `hostname` the FQDN value.

**Comment by nhsoukai** [comment]
In that case I guess this is not an issue then as it it does the intended  behavior.

**Comment by fmanco** [comment]
@zwass @groob What is the output you were expecting? It looks like hostname is the FQDN (coming from `getaddrinfo()`) which is as expected, but there might be a case here to simplify the other two as they are confusing and different between linux and macOS.

**Comment by groob** [comment]
I have a user who is reporting a separate value between `hostname -f` and `select hostname from system_info;` 
I did my best to repro their exact setup but was unfortunately not able to get a conclusive result. 
I did learn however that the way they're getting the bad hostname value is by creating the following file:

```
cat /etc/resolver/go
search golinks.io
```

And then `golinks.io` becomes the result osquery sees even though `hostname -f` shows up as their actual hostname value that they set with `scutil --set HostName`. 
I tried to repro the exact setup on my mac but was unable to get the same results. 

I'm not convinced that there's a bug in osquery but it's probably worth it to wait and see if someone reports a similar inconsistency.

**Comment by clong** [comment]
@groob not sure if this was implied from your latest comment, but I'm guessing that user had a local instance of dnsmasq, thus the `/etc/resolver` file: https://gist.github.com/ogrrd/5831371

**Comment by ccoy** [comment]
I tested this while traveling and got some interesting results. I had previously set my hostname to be "name." Running `hostname -f` returns "name." Running `scutil --get HostName` returns "name." Running `osqueryi 'select hostname from system_info'` returns "name.www.amtrakconnect.com" (I was on a train). So only osquery seems to be reporting the hostname incorrectly.

**Comment by fmanco** [comment]
This is not necessarily incorrect. osquery returns the FQDN as hostname which effectively might change depending on the network you're connected too.

I have no idea how macOS handles this and why is `hostname -f` not returning a FQDN. But from a quick look at the code getting the hostname boils down to a `getaddrinfo` with the `AI_CANONNAME` option. So the os is providing the hostname osquery reports.

However, I don't disagree this merits a bit more investigation.

**Comment by fmanco** [comment]
Since there isn't enough evidence this is broken I'll close the issue for now. If needed feel free to re-open. If you want to suggest changes to how hostnames are reported please open a new issue.
