### ISSUE TITLE
users table documentation inaccuracies for Windows

### ISSUE THREAD

**Issue by scottlundgren** [facebook/osquery#4421]
all versions - this is a documentation issue

### What have you already tried?
Reading the docs for the 'users' table.

### What did you expect to see?
An understanding of the table with respect to Windows.  In particular, the documentation suggests that the purpose of the users table _on Windows_ is to enumerate _local_ users and that the UUID column is applicable only to macOS.  

### What did you see instead?
The table enumerates all users, both local and domain, which have logged on locally (or otherwise created a local registry profile).  Also, the stringified Windows account SID is in the UUID field.

**Comment by fmanco** [comment]
Closed by #4422 .
