### ISSUE TITLE
osquery 3.2.4 enroll not working with wildcard certificate

### ISSUE THREAD

**Issue by rubenrodr-versia** [facebook/osquery#4427]
### What version of `osquery` are you using? What operating system. Be specific.
osquery_version = 3.2.4
     os_version = 12-SP2
       os_build =
    os_platform = sles

### What have you already tried?
Using self-signed certificates works fine, using wildcard one osquery fails to enroll to fleet
### What did you expect to see?
osquery enrolling to fleet with wildcard certificate
### What did you see instead?
W0524 17:25:19.083045  8120 tls_enroll.cpp:66] Failed enrollment request to https://fleet_server/api/v1/osquery/enroll (Request error: certificate verify failed) retrying...
I0524 17:25:20.084237  8120 smbios_tables.cpp:102] Reading SMBIOS from sysfs DMI node
I0524 17:25:20.084980  8120 smbios_tables.cpp:102] Reading SMBIOS from sysfs DMI node
I0524 17:25:20.085374  8120 tls.cpp:241] TLS/HTTPS POST request to URI: https://fleet_server/api/v1/osquery/enroll

**Comment by rubenrodr-versia** [comment]
Hi,

As suggested by @rada on #kolide slack channel i have used the bundle and now is working fine with the wildcard certificate.

Thanks.

**Comment by ashwindesikan** [comment]
what bundle ddi you use? could you please share the same?
