### ISSUE TITLE
OSQuery failed with error C2440 when build with permissive- by msvc on Windows

### ISSUE THREAD

**Issue by QuellaZhang** [facebook/osquery#4456]
OSQuery failed with error C2440 when build with permissive- by msvc on Windows, I use latest source on master branch. Could you please help take a look at this? Noted that this issue only found when compiles with unreleased vctoolset, that next release of MSVC will have this behavior. Thanks in advance!

**You can repro this issue as the steps below:**

1. 	git clone --recursive https://github.com/facebook/osquery D:\OSQuery\src
2. 	Open a VS 2017 x64 command prompt and browse to D:\OSQuery\src
3. 	set CL=/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING /permissive-
4. 	tools\make-win64-dev-env.bat
5. 	mkdir build\windows10 && pushd build\windows10
6. 	cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.16299.0 ..\..
7. 	cmake --build . --target shell --config Release -- /maxcpucount

**Error info:**

D:\OSQuery\src\osquery\tables\system\windows\wmi_bios_info.cpp(30): error C2440: 'initializing': cannot convert from 'initializer list' to 'std::map<std::string,std::pair<std::string,BSTR>,std::less<_Kty>,std::allocator<std::pair<const _Kty,_Ty>>>'
        with
        [
            _Kty=std::string,
            _Ty=std::pair<std::string,BSTR>
        ]
D:\OSQuery\src\osquery\tables\system\windows\wmi_bios_info.cpp(37): note: No constructor could take the source type, or constructor overload resolution was ambiguous

**Comment by muffins** [comment]
Will get this fixed, thanks for reporting!

**Comment by muffins** [comment]
@QuellaZhang this should be fixed with #4481, would you mind testing for us that it's fixed? I don't have my env setup currently for /permissive- builds. If not that's fine, I should be able to get something setup soon :)

**Comment by QuellaZhang** [comment]
Thank you very much Nick, OSQuery works well now!
