### ISSUE TITLE
Status logs unexpectedly showing up in /tmp directory

### ISSUE THREAD

**Issue by binary-dr01d** [facebook/osquery#4459]
Problem:
Logs are unexpectedly showing up in the /tmp directory, even when '--logger_path' is set.

### What version of `osquery` are you using?
```
osquery_version = 3.2.6
     os_version = CentOS Linux release 7.4.1708 (Core)
       os_build = 
    os_platform = rhel
```
Version listed above is prod server.  I am able to reproduce this on uBuntu 16.04 as well.  Tested on both CentOS and uBuntu hosts using newly created vagrant VMs to ensure a clean starting environment.

### What have you already tried?
Config options:
```
        "options": {
        "disable_audit": false,
        "audit_allow_config": true,
        "audit_persist": true,
        "disable_events": "false",
        "logger_plugin": "syslog",
        "config_plugin": "filesystem",
        "logger_syslog_prepend_cee": true,
```
Flags:
```
--config_refresh=300
--config_accelerated_refresh=600
--logger_path=/var/log/osquery/
```
### What did you expect to see?
Expected to see all logs (Status and Results) to show up in "/var/log/osquery" as defined with "--logger_path"

We use the 'syslog' plugin and configure rsyslog to split the Status and Results logs, sending to /var/log/osqueryd.log and /var/log/osquery.results.log, respectively.  Both of these files are populated with the data we expect to see, there is no issue with this forwarding.

### What did you see instead?
When osquery starts, files in "/tmp" are created.  "/tmp/osqueryd.INFO" symlink points to /tmp/<glog.file.name.format> file.  Log entries will continue to append to '/tmp/osqueryd.INFO' file as scheduled queries run.

Scheduled queries are written to both logs (rsyslog output file /var/log/osqueryd.log and symlinked file in /tmp).

**Comment by muffins** [comment]
Thanks for cutting this, we need to sort out why logs are getting dumped there, but my bet is this is a "best effort" location somehow, and we either need to update docs or add some more verbosity around this experience.

**Comment by nickryand** [comment]
@muffins I believe this is actually a fallback for glog if the destination is not explicitly configured
* https://github.com/google/glog/blob/master/src/logging.cc#L1824
* https://github.com/google/glog/blob/master/src/logging.cc#L1884

Should the log destination be set to the osquery default via [SetLogDestination](https://github.com/google/glog/blob/v0.3.5/src/glog/logging.h.in#L1401) prior to initializing glog?

**Comment by muffins** [comment]
@nickryand yeah I was betting that was the case. My two-cents is we _should_ set the log location default to the osquery filesystem logging default, as to me that makes the most intuitive sense. That being said, I'd welcome a discussion if others have strong feelings against that behavior, as having osquery logs drop to `/tmp` might be desired for those just prototyping or testing - imo it's a bit counter intuitive, as our docs will point you to /var/log/osquery/osqueryd.results.log

```
The osquery daemon uses a default filesystem logger plugin. Like the config, output from the filesystem plugin is written as JSON. Results from the query schedule are written to  /var/log/osquery/osqueryd.results.log
```

**Comment by binary-dr01d** [comment]
To add a little info here, I've done some additional testing with OSquery 3.2.6-1 running on CentOS 7.4.
In `/etc/sysconfig/osqueryd`, I added the following `GOOGLE_LOG_DIR="/var/log/osquery/"`.
Once I add this entry and restart both osqueryd/rsyslog, my desired functionality is restored (logs only show up in /var/log/osquery/).

Using OSquery version "2.11.0-1" running on CentOS 7.4, I see logs show up in '/tmp/' also.  I applied the same work-a-round as used with version 3.2.6 (In `"/etc/sysconfig/osqueryd"`, I added the following `GOOGLE_LOG_DIR="/var/log/osquery/"`).  Again the desired functionality is restored (logs only show up in /var/log/osquery/).

In OSquery version "2.10.2-1" logs never show up in /tmp/.

Based on my testing, it seems this change in functionality occurred before version 3.0.

**Comment by binary-dr01d** [comment]
@muffins I agree that sending logs to '/tmp/' maybe helpful for prototyping or testing, but it does seem counter-intuitive based on the documentation.

I vote that sending to '/var/log/osquery/' is the better choice.

**Comment by theopolis** [comment]
I think this only occurs when `--verbose` is used.

**Comment by theopolis** [comment]
This is very annoying!
