### ISSUE TITLE
macOS disk_encryption producing errors in 3.2.6

### ISSUE THREAD

**Issue by rmcvey** [facebook/osquery#4479]
Hello! I'm seeing some errors when I query the `disk_encryption` table on macOS, with or without elevated privileges.

```bash
osquery> select * from disk_encryption;
E0602 19:42:17.168584 3052168064 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0602 19:42:17.170701 3052168064 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0602 19:42:17.172094 3052168064 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0602 19:42:17.173445 3052168064 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0602 19:42:17.337844 3052168064 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0602 19:42:17.339026 3052168064 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0602 19:42:17.340062 3052168064 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0602 19:42:17.341210 3052168064 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0602 19:42:17.342548 3052168064 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0602 19:42:17.344045 3052168064 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
+--------------+--------------------------------------+-----------+-----------------+-----+--------------------------------------+
| name         | uuid                                 | encrypted | type            | uid | user_uuid                            |
+--------------+--------------------------------------+-----------+-----------------+-----+--------------------------------------+
...expected results
```

### What version of `osquery` are you using?

```
+-----------------+------------+----------+-------------+
| osquery_version | os_version | os_build | os_platform |
+-----------------+------------+----------+-------------+
| 3.2.6           | 10.13.4    | 17E202   | darwin      |
+-----------------+------------+----------+-------------+
```

### What have you already tried?

I tried running with 2.11.2, 3.2.4, 3.2.6 stable and debug, with and without elevated privileges. Tried uninstalling/reinstalling. v3.2.6 is the only version that produces this error message

### What did you expect to see?
I expect to see the query results without errors.

### What did you see instead?
I see a number of these errors:
```bash
E0602 19:42:17.168584 3052168064 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
```

Followed by the expected query results

**Comment by mkareta** [comment]
Before 3.2.6 osquery was faling to report this error. In short errors were always there :( 
Now we need to check should we silnce it or not. 
Can you please share more details about your disk encryption setup?

**Comment by rmcvey** [comment]
Thanks for responding @mkareta, I have FileVault enabled for my boot disk "Macintosh HD". Here are the results of the `disk_encryption` query:

```bash
osquery> select name, encrypted, type, uid from disk_encryption;
E0604 11:28:46.444109 2879107968 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0604 11:28:46.445091 2879107968 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0604 11:28:46.445972 2879107968 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0604 11:28:46.446876 2879107968 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0604 11:28:46.616693 2879107968 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
E0604 11:28:46.617642 2879107968 disk_encryption.mm:259] Error calling isEncryptedVolume:encrypted:
+--------------+-----------+-----------------+-----+
| name         | encrypted | type            | uid |
+--------------+-----------+-----------------+-----+
| /dev/disk0   |           |                 |     |
| /dev/disk0s1 |           |                 |     |
| /dev/disk0s2 |           |                 |     |
| /dev/disk1   |           |                 |     |
| /dev/disk1s1 | 1         | APFS Encryption | 501 |
| /dev/disk1s2 | 0         |                 |     |
| /dev/disk1s3 | 0         |                 |     |
| /dev/disk1s4 | 0         |                 |     |
| /dev/disk2   |           |                 |     |
| /dev/disk2s1 |           |                 |     |
+--------------+-----------+-----------------+-----+
```

And here is a screenshot verifying in Disk Utility 
![disk_utility](https://user-images.githubusercontent.com/307161/40934801-d38acf18-67ea-11e8-8fa7-e847621fc7fd.png)

We are currently shelling out (`osqueryi --json $QUERY`) and this is causing issues for us. We can work around this by suppressing STDERR, but this error is confusing since the query seems to be working correctly.

**Comment by arubdesu** [comment]
Possible wrinkle: I'm not seeing this on 10.13.5 with an HFS+ formatted volume, this could be APFS-specific

**Comment by terracatta** [comment]
This is likely the the PR that broke the table https://github.com/facebook/osquery/pull/4404

**Comment by mkareta** [comment]
@terracatta  Table is not broken, technically it was broken before, becuase it was not reporting errors, now when repotirng is correct we need to silence or handle errors. Problem is that error is from private framework and we need to do reverse engineer to get real reason. 
@rmcvey  Thanks for info, I will try to reproduce it and check why isEncryptedVolume:encrypted:
returing the error

**Comment by mkareta** [comment]
@terracatta True behavior is slighlty changed, which is bad, before osquery was reporting isEncrypted as 0 when was not able to get encryption status from disk, and now its reports empty result. I will restore old behaviour for now, but in future encrypted column will be replaced with encryption_status = encrypted | not encrypted | undefined (error), or somethign similar to provide more information instead of ignoring errors

**Comment by mkareta** [comment]
Issue fixed, with old behavior restored for "encrypted" column, new column "encryption_status" is added that provide more context about disk encryption, please see table schema for details.
