### ISSUE TITLE
OSQuery provides a warning message when queries are run frequently (1 second intervals)

### ISSUE THREAD

**Issue by srikwit** [facebook/osquery#4500]
### What version of `osquery` are you using? What operating system. Be specific.
You can run this query to get the necessary details: 
```
osqueryd -S --line 'SELECT oi.version as osquery_version, os.version AS os_version, os.build AS os_build, os.platform AS os_platform FROM os_version AS os JOIN osquery_info as oi;'
```
osquery_version = 3.2.4
     os_version = 10.0.17134
       os_build = 17134
    os_platform = windows
### What have you already tried?
I have tried the following custom query pack:

{
	"platform": "windows",
	"queries": {
		"a": {
			"query": "select pid, cmdline, parent from processes where cmdline like '%net_%start_%_%';",
			"interval": 3,
			"value":"security,compliance,operations"
		},
		"b": {
			"query": "select pid, cmdline, parent from processes where cmdline like '%net_%stop_%_%';",
			"interval": 3,
			"value":"security,compliance,operations"
		},
		"c": {
			"query": "select pid, cmdline, parent from processes where cmdline like '%net_%user_%add%';",
			"interval": 1,
			"value":"security,compliance,operations"
		},
		"d": {
			"query": "select pid, cmdline, parent from processes where cmdline like '%net_%user %';",
			"interval": 1,
			"value":"security,compliance,operations"
		}		
	}
}

### What did you expect to see?
I was expecting atleast one of the values to be found successfully in the logs given sufficiently large run time.

### What did you see instead?
I0606 12:36:30.802021 15508 scheduler.cpp:75] Executing scheduled query pack_c: select pid, cmdline, parent from processes where cmdline like '%net_%user_%add%';
I0606 12:36:31.240113 15508 scheduler.cpp:75] Executing scheduled query pack_d: select pid, cmdline, parent from processes where cmdline like '%net_%user %';
I0606 12:36:32.661115 15508 scheduler.cpp:75] Executing scheduled query pack_a: select pid, cmdline, parent from processes where cmdline like '%net_%start_%_%';
I0606 12:36:32.962559 15508 scheduler.cpp:75] Executing scheduled query pack_b: select pid, cmdline, parent from processes where cmdline like '%net_%stop_%_%';
I0606 12:36:33.252656  5572 rocksdb.cpp:66] RocksDB: [WARN] [c:\users\thor\work\repos\osquery\build\chocolatey\rocksdb\rocksdb-5.7.1\db\column_family.cc:675] [queries] Stalling writes because we have 15 immutable memtables (waiting for flush), max_write_buffer_number is set to 16 rate 16777216
I0606 12:36:33.426476 15508 scheduler.cpp:75] Executing scheduled query pack_c: select pid, cmdline, parent from processes where cmdline like '%net_%user_%add%';
I0606 12:36:33.845753 15508 scheduler.cpp:75] Executing scheduled query pack_d: select pid, cmdline, parent from processes where cmdline like '%net_%user %';
I0606 12:36:34.047977  5572 rocksdb.cpp:66] RocksDB: [WARN] [c:\users\thor\work\repos\osquery\build\chocolatey\rocksdb\rocksdb-5.7.1\db\column_family.cc:675] [queries] Stalling writes because we have 15 immutable memtables (waiting for flush), max_write_buffer_number is set to 16 rate 16777216
I0606 12:36:34.058957 15332 rocksdb.cpp:66] RocksDB: [WARN] [c:\users\thor\work\repos\osquery\build\chocolatey\rocksdb\rocksdb-5.7.1\db\column_family.cc:675] [queries] Stalling writes because we have 15 immutable memtables (waiting for flush), max_write_buffer_number is set to 16 rate 16777216
I0606 12:36:34.116351 16100 rocksdb.cpp:66] RocksDB: [WARN] [c:\users\thor\work\repos\osquery\build\chocolatey\rocksdb\rocksdb-5.7.1\db\column_family.cc:675] [queries] Stalling writes because we have 15 immutable memtables (waiting for flush), max_write_buffer_number is set to 16 rate 16777216
I0606 12:36:35.236958 15508 scheduler.cpp:75] Executing scheduled query pack_c: select pid, cmdline, parent from processes where cmdline like '%net_%user_%add%';
I0606 12:36:35.675050 15508 scheduler.cpp:75] Executing scheduled query pack_d: select pid, cmdline, parent from processes where cmdline like '%net_%user %';
I0606 12:36:37.111090 15508 scheduler.cpp:75] Executing scheduled query pack_c: select pid, cmdline, parent from processes where cmdline like '%net_%user_%add%';
I0606 12:36:37.501567 15508 scheduler.cpp:75] Executing scheduled query pack_d: select pid, cmdline, parent from processes where cmdline like '%net_%user %';
I0606 12:36:39.078001 15508 scheduler.cpp:75] Executing scheduled query pack_a: select pid, cmdline, parent from processes where cmdline like '%net_%start_%_%';
I0606 12:36:39.599776 15508 scheduler.cpp:75] Executing scheduled query pack_b: select pid, cmdline, parent from processes where cmdline like '%net_%stop_%_%';
I0606 12:36:39.850056  5572 rocksdb.cpp:66] RocksDB: [WARN] [c:\users\thor\work\repos\osquery\build\chocolatey\rocksdb\rocksdb-5.7.1\db\column_family.cc:675] [queries] Stalling writes because we have 15 immutable memtables (waiting for flush), max_write_buffer_number is set to 16 rate 16777216
I0606 12:36:40.038270 15508 scheduler.cpp:75] Executing scheduled query pack_c: select pid, cmdline, parent from processes where cmdline like '%net_%user_%add%';
I0606 12:36:40.693972 15508 scheduler.cpp:75] Executing scheduled query pack_d: select pid, cmdline, parent from processes where cmdline like '%net_%user %';

I suspect that this is related to rocks db tuning:
https://github.com/facebook/rocksdb/wiki/RocksDB-Tuning-Guide

**Comment by obelisk** [comment]
Pinging @muffins because those logs look off as well.

As for the warnings, they are in the RocksDB code it's going to be hard to control them. Is the data still getting through correctly though or is it getting lost?

**Comment by muffins** [comment]
This might actually be quite tough to get logging information for these queries. Before we dive too deeply into that, I'd encourage you to check out the Windows Event Log plugin and using process start auditing for Windows, as this will be a much more reliable way to get process starts, but to your question, you're trying to run scheduled queries to catch the `net` command with specific command line flags, however you're very likely not going to get results, considering the osquery query will need to run at _precisely_ the exact same time that the `net` command is running, which will be very hard to do. It looks like we already have another issue tracking the DB warnings, so I'm going to close this out. Feel free to hit up the #windows channel in Slack for more discussion, but what you're seeking will much better be accomplished with eventing tables as opposed to standard scheduled queries.
