### ISSUE TITLE
[WINDOWS] Osquery does not request configuration even though settings demand it.

### ISSUE THREAD

**Issue by temp-defualt** [facebook/osquery#4522]
### What version of `osquery` are you using? What operating system. Be specific.
tested under 3.2.6 and 2.11.2 , windows 10 & windows 7.

### What have you already tried?
i setted the proper configuration in order to set config plugin to perfrom tls request from my server.
the client do Enroll requests (and get proper response) , and also doing LOG request but does not request CONFIG in any time....

here is a copy of my configurations:
https://pastebin.com/VckTMBwD

is that a bug or mismatch in my configuration ( i checked online tutorials but everything looks same as my configuration).

yours,
ori.

**Comment by muffins** [comment]
@temp-defualt can you shoot us the invocation of osquery in verbose mode?
```
C:\ProgramData\osquery\> osqueryd\osqueryd.exe --flagfile=C:\ProgramData\osquery\osquery.flags --verbose
```
We haven't seen this as being an issue, so I'm wondering if it's not just a misconfiguration, but there should be a log line indicating it failed to parse the config or offering more details about why it couldn't retrieve one.

**Comment by temp-defualt** [comment]
**i fixed the issue!!**
i found 2 bugs in the osquery under windows while trying to fix the problem:

1) under windows the client ignore the config part in the conf file (that the original bug i opened the issue for ) ,after some research - **it does work when executing the file with FLAGS :)**

2) windows agent does only distributed requests when running with -D  (not a bug? but must be documented because it made me burn some hours on trying to understand whats wrong)

thanks anyway,
yours - Ori.

**Comment by muffins** [comment]
@temp-default glad to hear it! I think both of those are known behaviors, and might merit some documentation love. I’m going to close out this issue as your problem has been resolved but feel free to reopen if you’d like and feel free to open up a PR updating the docs if you’d like!
