### ISSUE TITLE
Website "jumps around" when mousing over the schema reference

### ISSUE THREAD

**Issue by kbd** [facebook/osquery#4526]
In the [schema documentation](https://osquery.io/schema/3.2.6), when mousing over the list of tables to the left, the scrollbar for the main browser window is hidden, causing the content of the page to "jump around" as it shifts left and right depending on whether the scrollbar is present.

Tested in both current Chrome and Firefox.

**Comment by muffins** [comment]
Hey there! Thanks for reporting, but I think this issue might best be brought up on the website repository here: https://github.com/osquery/osquery-site

I'm going to close this issue out and re-open an issue on the site repo for this to be triaged :) thanks!

**Comment by muffins** [comment]
Issue [#93](https://github.com/osquery/osquery-site/issues/93) for reference.

**Comment by kbd** [comment]
> but I think this issue might best be brought up on the website repository here

Apologies! I didn't realize the website was in a separate repo. Thanks for opening it in the right place.
