### ISSUE TITLE
Website bug: processes on_disk does not detect modified binary

### ISSUE THREAD

**Issue by droe** [facebook/osquery#4536]
The website at osquery.io contains the following statement:

> **Processes running without a binary on disk**
> Frequently, attackers will leave a malicious process running but delete the original binary on disk. This query returns any process whose original binary has been deleted _or modified_ (which could be an indicator of a suspicious process).

(Emphasis on «or modified» added.)

Checking `osquery/tables/system/*/processes.cpp` for the code which generates the `on_disk` flag, none of the implementations actually detect a modified binary. Linux has a check for the inode number in a corner case, but even then does not check if the file was modified in-place, leaving the inode intact but pointing to different content on disk. All other platforms simply check if the path exists. Therefore I suggest to remove the "or modified" from the website at osquery.io. The actual documentation agrees with the source code and only refers to deleted, not modified binaries.

I could not find the source code for osquery.io in the repository, otherwise I would have submitted a pull request.

**Comment by groob** [comment]
@droe the website repo is https://github.com/osquery/osquery-site

**Comment by droe** [comment]
Thank you, I apologize for missing the osquery-site repo.

**Comment by marpaia** [comment]
The fix has been merged and deployed: https://github.com/osquery/osquery-site/pull/94

**Comment by groob** [comment]
No worries @droe, I enjoyed reading the bug report.
