### ISSUE TITLE
osqueryd CPU usage spikes when writes performed to /dev/null

### ISSUE THREAD

**Issue by zbuc** [facebook/osquery#4537]
### What version of `osquery` are you using? What operating system. Be specific.
3.2.6, MacOS 10.13.4

We are seeing a strange behavior where when many writes are performed to `/dev/null`, CPU usage of `osqueryd` spikes.

We have reproduced this on every MacOS box we've tested on by doing the following:

1) download and install OSQuery 3.2.6 from osquery.io
2) launch the process `sudo /usr/local/bin/osqueryd`
3) watch CPU usage of the `osqueryd` processes in Activity Monitor -- usage should be low
4) begin writing to `/dev/null`: `dd if=/dev/zero of=/dev/null`
5) watch CPU usage of the `osqueryd` processes in Activity Monitor -- one of them will spike to 100 and remain there
6) wait, observe, and see that CPU usage of `osqueryd` remains high
7) kill the `dd` process writing to `/dev/null`
8) observe CPU usage of `osqueryd` processes -- the process that was spiking will fall back down to very low levels

I believe this requires having the watchdog disabled, otherwise it should theoretically kill the `osqueryd` process.

**Comment by fmanco** [comment]
Hi @zbuc I cannot reproduce this.

Are you using any flags file or configuration? Are you launching osqueryd without any flags?

**Comment by zbuc** [comment]
I am launching it without any flags. I did not change the configuration files after installing from the .pkg.

**Comment by zbuc** [comment]
I took a video showing my reproduction: https://www.dropbox.com/s/jail5atacgxk0fq/osquery_weirdness.mov?dl=0

**Comment by fmanco** [comment]
Okay, I can repro now. If I had to guess I would point at https://github.com/facebook/osquery/blob/master/osquery/events/darwin/fsevents.cpp#L70-L73

**Comment by fmanco** [comment]
@zbuc as a temporary add monitoring for a file that rarely changes on your configuration. That will prevent `/dev/null` to be added on that code.

**Comment by fmanco** [comment]
@theopolis can you provide some input on why this is done? Introduced at https://github.com/facebook/osquery/commit/31dfad2515e5399c9b48b89a97d68fd4a1b7292e.

**Comment by fmanco** [comment]
I've created a PR, but lets wait for @theopolis input here.

**Comment by theopolis** [comment]
I don't remember :)

**Comment by fmanco** [comment]
Fair enough :D. Just doing some more testing and then we can hopefully merge the fix.

**Comment by zbuc** [comment]
It looks like 31dfad2 may have been a typo fix to remove the trailing slash, and it had no performance impact before because `/dev/null/` was nonexistent? Funny that nobody else noticed since then, though!

**Comment by fmanco** [comment]
My bad, I meant https://github.com/facebook/osquery/commit/9f79d74c605f6d5f33caa48d1eef56c318db8ef5.
