### ISSUE TITLE
Did not find  'benchmark/benchmark.h' file

### ISSUE THREAD

**Issue by kjaisinghyadav** [facebook/osquery#4554]
Hi,
   I am geting this error when i try to build the Osquery Cannot open include file: 'benchmark/benchmark.h': No such file or directory. Even i try to check this file but i didn't get.

**Comment by akindyakov** [comment]
Thank you for the question.

Looks like missing dependency. Did you run `make deps` before build?
This is some instructions to build [link](https://osquery.readthedocs.io/en/latest/development/building/)

**Comment by kjaisinghyadav** [comment]
This i am running on windows.

**Comment by theopolis** [comment]
I don't think we install `google-benchmark` using the scripts/tooling. I think this is because we have never run or built the benchmark tests on Windows.

Perhaps some recent change added benchmark-related sources to the default build? /cc @mkareta who has been playing with CMake recently.

**Comment by muffins** [comment]
I'm having some trouble replicating this behavior, @kjaisinghyadav could you shoot us the invocations you are using? The typically build process is usually:
```
.\tools\make-win64-dev-env.bat
.\tools\make-win64-binaries.bat
```
But running from a mostly clean environment I don't seem to be able to trigger this behavior. Have you tried deleting the `build` directory and re-running the build scripts?

**Comment by kjaisinghyadav** [comment]
i am using Windows 10 for this. For build process i am using this:

.\tools\make-win64-dev-env.bat
.\tools\make-win64-binaries.bat

I have deleted the build  directory and tried again but facing same issue. Even when i run .\tools\make-win64-binaries.bat  , few test getting failed. @muffins

**Comment by muffins** [comment]
@kjaisinghyadav I mentioned this in the other issue, but it sounds like you're trying to build the `Debug` release, you need to switch to the `RelWithDebInfo` or `Release` targets to build osquery. Give that a shot and let us know if it works, we definitely need to update the solution generation to make `RelWithDebInfo` the default target.

**Comment by kjaisinghyadav** [comment]
@muffins In release or RelWithDebInfo i am getting these error it ask benchmark.h file, if i provide "google" benchmark.h than it throws an error like cannot open input file 'benchmark.lib'

**Comment by muffins** [comment]
@kjaisinghyadav try blowing away the `build` directory, and rebuilding from the command line with `$env:RELWITHDEBINFO=1; .\tools\make-win64-binaries.bat`

**Comment by muffins** [comment]
I'm going to close this issue out, as it looks like things are working correctly. Feel free to re-open, but these issues might better be triaged in [our Slack](https://osquery-slack.herokuapp.com/). Thanks!
