### ISSUE TITLE
Update Windows Query Packs Configs to Remove Extra Backslashes

### ISSUE THREAD

**Issue by jslopak** [facebook/osquery#4560]
osquery version 3.2.0.  SQLite 3.19.3.  OS = Windows 10, x64, v1803.

Query Pack File: https://github.com/facebook/osquery/blob/master/packs/windows-attacks.conf 

The following queries contain double backslashes in file paths:

(1)
SELECT * FROM processes WHERE LOWER(name)='conhost.exe' AND LOWER(path)!='c:\\windows\\system32\\conhost.exe' AND path!='';

(2)
SELECT * FROM processes WHERE LOWER(name)='dllhost.exe' AND LOWER(path)!='c:\\windows\\system32\\dllhost.exe' AND LOWER(path)!='c:\\windows\\syswow64\\dllhost.exe' AND path!='';

(3)
SELECT * FROM processes WHERE LOWER(name)='lsass.exe' AND LOWER(path)!='c:\\windows\\system32\\lsass.exe' AND path!='';

(4)
SELECT * FROM processes WHERE LOWER(name)='svchost.exe' AND LOWER(path)!='c:\\windows\\system32\\svchost.exe' AND LOWER(path)!='c:\\windows\\syswow64\\svchost.exe' AND path!='';

The problem is that these queries look for processes masquerading as legitimate Windows processes and ideally should not return anything on a healthy system.  However, due to double backslashes, they return legitimate Windows processes.  For example:

![capture](https://user-images.githubusercontent.com/28153757/41422351-bd0fd222-6fc6-11e8-9113-2d91aded3911.PNG)

**Comment by fmanco** [comment]
Hey @jslopak indeed the escaping is seems wrong. @muffins did the escaping changed at some point in time?

**Comment by muffins** [comment]
Hrm, the escaping hasn't changed in quite some time, I'll take a look but changing the query packs is easy and should be fine.

**Comment by jslopak** [comment]
Thanks folks!  This is an issue when I copy and paste a query with double-slashes from .conf file and paste it into osqueryi directly.  However, if the file is used as a json input file for osqueryd, it's not an issue.  So, maybe it's not a bug.  Thanks!

**Comment by fmanco** [comment]
Oh right, `\\` is json escaping for the `\` character. Indeed not a bug. I'll close then.
