### ISSUE TITLE
Issue in downloading developer tools

### ISSUE THREAD

**Issue by srikwit** [facebook/osquery#4569]
### What version of `osquery` are you using? 
```
osqueryd -S --line 'SELECT oi.version as osquery_version, os.version AS os_version, os.build AS os_build, os.platform AS os_platform FROM os_version AS os JOIN osquery_info as oi;'

+-----------------+------------+----------+-------------+
| osquery_version | os_version | os_build | os_platform |
+-----------------+------------+----------+-------------+
| 3.2.4           | 10.0.17134 | 17134    | windows     |
+-----------------+------------+----------+-------------+
```
### What have you already tried?
1. Retry normal installation:
tools\make-win64-dev-env.bat

2. choco install llvm-clang --version=4.0.1

3. choco install llvm
### What did you expect to see?
LLVM package should have been installed

### What did you see instead?
Chocolatey v0.10.11
Installing the following packages:
llvm-clang
By installing you accept licenses for the packages.
Unable to read package from path 'llvm-clang\llvm-clang.nupkg'.

**Comment by muffins** [comment]
Hey @srikwit, is there a reason you're manually installing `llvm-clang and `llvm`? We typically recommend just running the following two utilities for builds:
```
.\tools\make-win64-dev-env.bat
.\tools\make-win64-binaries.bat
```
The llvm packages are installed when you run the first line, you shouldn't need to run the subsequent installations. Also we don't currently use llvm clang for windows builds, just for Clang format, our build is still leveraging `cl`

**Comment by scottlundgren** [comment]
to @muffins point, I (yesterday) did a clean win10 install, installed git, clone'd osquery, and ran the two batch files as documented above.  Worked like a charm.  I've done this probably 10 times (on clean VMs) over the past three months, the only error I've seen is timeouts on pulling down packages, usually on slow links.  re-running has always worked.

**Comment by srikwit** [comment]
@muffins, I resorted to manually installing the packages when I started receiving the error and I used provision.ps1 to find the package details.

@scottlundgren currently I am on a slow link so I am facing the timeout that you have mentioned. Please give me 2 more days to retry this in my office network.

**Comment by muffins** [comment]
@srikwit see the notes in the Slack, I think you might want to try manually uninstalling all choco packages you have installed manually and re-running the provisioning script.

**Comment by srikwit** [comment]
Sorry @muffins for the delay, closing the issue.
