### ISSUE TITLE
unable to build on suse 11 

### ISSUE THREAD

**Issue by rubenrodr-versia** [facebook/osquery#4598]
I'm trying to build osquery 3.2.6 on SuSE 11 

>lsb_release -a
>LSB Version:    n/a
>Distributor ID: SUSE LINUX
>Description:    SUSE Linux Enterprise Server 11 (x86_64)
>Release:        11
>Codename:       n/a

The system is using glibc 2.11, so i cannot install the rpm build which depends on glibc 2.12

When i try to run the sysprep i get the following error:

> make sysprep
> which: no cscope in (/home/versia/bin:/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin:/usr/games:/usr/lib/mit/bin:/usr/lib/mit/sbin)
>[+] found suse provision script: /home/versia/osquery-master/tools/provision/suse.sh
>[+] requesting sudo: zypper update -y
>Loading repository data...
>Reading installed packages...
>
>The following package update will NOT be installed:
>  yast2-perl-bindings
>
>Nothing to do.
>[+] [notice] dependencies directory '/usr/local/osquery' already exists
>[+] setting up new brew in /usr/local/osquery
>fatal: destination directory '/usr/local/osquery' already exists.
>make: *** [sysprep] Error 128

I tried to build on SuSE 12 and work fine.

**Comment by muffins** [comment]
Unfortunately we don't explicitly support SuSE for osquery builds, only those operating systems listed in the `README.md` under the jenkins CI builds. Is there a strong reason you can't leverage SuSE 12 or upgrade your glibc version to 2.12? You might also try asking around in [our Slack](https://osquery-slack.herokuapp.com/) if folks have worked around the 2.12 restriction, namely the #core channel, but iirc this version is something of a hard dependency. I'm going to close this issue out, but please feel free to re-open if you'd like to continue the conversation here.
