### ISSUE TITLE
Flaky test: Windows thrash service

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#4601]
See: https://jenkins.osquery.io/job/osqueryPullRequestWindows/4598/TargetSystem=aws-windows-2016/console

**Comment by muffins** [comment]
Another instance: https://jenkins.osquery.io/job/osqueryPullRequestWindows/4634/TargetSystem=aws-windows-2016/console

**Comment by kjaisinghyadav** [comment]
I am also facing same issue. In my case Test Case 3 & 6 getting failed.

**Comment by muffins** [comment]
Hopped on the jenkins box, this looks to be related to residual services from previous test runs not getting cleaned up correctly. I'm going to modify the test run to ensure that all system services have been removed before running, and that no osquery processes still exist before we start. That being said, it's yet another question why there are residual services and processes still running. It could be from the Jenkins issues we've been facing, but there might be other issues lingering...

**Comment by kjaisinghyadav** [comment]
After running these test if i open osquery.sln and compile then i get errors like:

warning treated as error - no 'object' file generated
Did not find 'benchmark/benchmark.h' file
cannot open input file '\osquery\core\osquery_core.dir\Debug\conversions.obj'	
"cmd.exe" exited with code 1.	
cannot open input file 'Debug\osquery.lib'

**Comment by muffins** [comment]
@kjaisinghyadav ensure that you are building the `RelWithDebInfo` or `Release` target, as the `Debug` target is currently not working.

**Comment by kjaisinghyadav** [comment]
thank you very much, in release mode its running properly.

**Comment by kjaisinghyadav** [comment]
@muffins   In release or RelWithDebInfo   i am getting these error it  ask benchmark.h file, if i provide  google benchmark.h  than it throws an error like cannot open input file 'benchmark.lib'

**Comment by theopolis** [comment]
Was this change successful?

**Comment by muffins** [comment]
I think it has been considering recent PRs, have you seen it failing @theopolis? We _might_ be able to close this out.
