### ISSUE TITLE
Osquery scripts for Windows Provisioning (on Windows 10) not working properly

### ISSUE THREAD

**Issue by Anirudh95** [facebook/osquery#4610]
The scripts (tools\make-win64-dev-env.bat & tools\make-win64-binaries.bat) need fixes to ensure smooth installation and build of Windows environment.

### What version of `osquery` are you using? What operating system. Be specific.
You can run this query to get the necessary details: 
```
osqueryd -S --line 'SELECT oi.version as osquery_version, os.version AS os_version, os.build AS os_build, os.platform AS os_platform FROM os_version AS os JOIN osquery_info as oi;'
```
osquery_version :  3.2.4
os_version :   10.0.17134
os_build :  17134
os_platform :  windows    

### What have you already tried?
- Tried running scripts with Visual Studio (VS) 2015 manually installed
- Tried running scripts with clean install of Windows 10 on VM and was getting errors when Visual Studio 2017 latest version was to be downloaded using chocolatey. Had to download a pervious version and use choco upgrade later on and run "tools\make-win64-dev-env.bat"
- After installation, the build script caused errors with not being able to run msbuild (msb1009 error)

### What did you expect to see?
- Expected clean install and build on Windows 10

### What did you see instead?
- Errors with installation. Installation of manual VS also caused errors in script
- Msbuild errors

**Comment by Anirudh95** [comment]
After a lot of code reading, researching online and trial and error, I found out that cloning the repository on the user desktop rather than System32 worked fine, at least for me. Just make sure to switch directories when opening command line with adminstrator mode.
Would still need to try it again on a different VM with clean WIndows 10 OS install to make sure that this method is not just a fluke...

**Comment by theopolis** [comment]
Thanks for debugging @Anirudh95!
