### ISSUE TITLE
Query profiler reports negative duration for query

### ISSUE THREAD

**Issue by NickTitle** [facebook/osquery#4657]
### What version of `osquery` are you using? What operating system. Be specific.
osquery_version = 2.10.3
     os_version = 10.13.4
       os_build = 17E202
    os_platform = darwin

### What have you already tried?
running the profiler

### What did you expect to see?
a positive duration for all queries in the config

### What did you see instead?
a negative duration for one of the queries in the config

here's the config i'm passing in:
```
{
  "schedule": {
    "macOS kexts v1": {
      "query": "SELECT k.path, name, version, authority, team_identifier, identifier FROM kernel_extensions k JOIN signature s ON k.path=s.path WHERE team_identifier != '';",
      "interval": 60
    },
    "macOS kexts v2": {
      "query": "SELECT k.path, name, version, authority, team_identifier, identifier FROM kernel_extensions k JOIN signature s ON k.path=s.path WHERE team_identifier != '' AND name NOT LIKE ‘com.apple_%’;",
      "interval": 60
    }
  }
}
```

and here's my output
```
./tools/analysis/profile.py --conf ~/Desktop/example.conf
Profiling query: SELECT k.path, name, version, authority, team_identifier, identifier FROM kernel_extensions k JOIN signature s ON k.path=s.path WHERE team_identifier != '';
/Users/nicholasesposito/projects/osquery/tools/analysis/../tests/utils.py:147: FutureWarning: memory_info_ex() is deprecated and will be removed; use memory_info() instead
  "memory": p.memory_info_ex(),
 D:3  C:2  M:2  F:0  U:3  macOS kexts v1 (1/1): duration: 7.52999901772 cpu_time: 6.183422208 memory: 24412160 fds: 5 utilization: 77.06875
Profiling query: SELECT k.path, name, version, authority, team_identifier, identifier FROM kernel_extensions k JOIN signature s ON k.path=s.path WHERE team_identifier != '' AND name NOT LIKE ‘com.apple_%’;
 D:0  C:0  M:2  F:0  U:0  macOS kexts v2 (1/1): duration: -0.489871025085 cpu_time: 0.024266762 memory: 13934592 fds: 4 utilization: 4.6
```

**Comment by muffins** [comment]
@NickTitle have you tried this with the latest stable tag, 3.2.6?

**Comment by theopolis** [comment]
@NickTitle, I never had enough time to dig into this, but also experienced the same when "very quickly taking two times in Python and finding the difference". I can imagine a lot of nuance scenarios where this could occur.

In my opinion the best/easiest fix is to take the difference and report 0 if the value is negative. Do you mind fixing this?

**Comment by NickTitle** [comment]
Not at all! I'll probably push that up this week

**Comment by fmanco** [comment]
Fix merged so will close this now.
