### ISSUE TITLE
How to add mongocxx and bsoncxx libraries in Osquery

### ISSUE THREAD

**Issue by AustinSolomonDsouza** [facebook/osquery#4663]
### What version of `osquery` are you using? What operating system. 

 osquery_version = 3.2.9-2-g0ae3c0b
 os_version = CentOS Linux release 7.2.1511 (Core)
 os_platform = rhel

### What I want to achieve?

I wanted to save the output of scheduled query which is in JSON object into MongoDB, I have written a function in c++ to save the obtained JSON object in filesystem_logger.cpp file.
However while building the code using make command giving me the following error :

>>>[ 83%] Linking CXX executable osquery_additional_tests
/usr/local/osquery/bin/ld.lld: error: undefined symbol: bsoncxx::v_noabi::builder::core::key_owned(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)
>>> referenced by key_context.hpp:84 (/home/tg1/development/Aeverie_Softwares/osquery/include/bsoncxx/builder/stream/key_context.hpp:84)
>>>               /home/tg1/development/Aeverie_Softwares/osquery/build/centos7/cache/llvmcache-6394EFF0D08516CB88568DF6DBFA8D472A356497:(osquery::startInsert(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&))
clang-6.0: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [osquery/osquery_additional_tests] Error 1
make[2]: *** [osquery/CMakeFiles/osquery_additional_tests.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [all] Error 2

### What have you already tried?

I have included the below line in osquery/logger/CMakeLists.txt file
  ADD_OSQUERY_LINK_ADDITIONAL("mongocxx")
  ADD_OSQUERY_LINK_ADDITIONAL("bsoncxx")

and added the source code of mongocxx and bsoncxx in osqurey/include path, still getting the same error.

Can someone help me to solve this issue.

Thanks in advance.

**Comment by muffins** [comment]
@AustinSolomonDsouza I think you're approaching this from the right angle, you'll definitely need to change some CMake logic to get this working, and I'd be under the impression you might need to modify some of our database abstraction to get it working, but as this isn't a supported feature, this might be a conversation better had in our [Slack](osquery.slack.com). That being said, it looks like this is an issue linking the test libs, have you tried building like `SKIP_TESTS=1 make -j 4`?

I'm going to close this out, but please feel free to keep the conversation going in the Slack, perhaps in the #core or #general channels?
