### ISSUE TITLE
windows osqueryi  can not open RocksDB handle

### ISSUE THREAD

**Issue by turtlejamesw** [facebook/osquery#4672]
Dear all,
I want to readout osquery table data via osqueryi, my idea is 
(1) enabled osqueryi in-memory database
(2) use C# sqllite framework to connect/query RocksDB database
But i found out osqueryi can't open RocksDB  in Windows osqueryi
details are as follows -

H:\Release>osqueryi.exe --database_path=H:\Release\osquery.db\ --verbose
I0705 09:58:16.142879 50500 init.cpp:396] osquery initialized [version=3.2.6]
I0705 09:58:16.145881 50500 extensions.cpp:342] Could not autoload extensions: Failed reading: \ProgramData\osquery\extensions.load
I0705 09:58:16.159935 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:18.285419 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:20.402000 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:22.553530 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:24.691035 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:26.836580 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:28.997081 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:31.122604 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:33.275100 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:35.422618 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:37.538120 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:39.687641 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:41.803139 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:43.946642 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:46.033118 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:48.120592 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:50.247242 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:52.392788 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:54.552289 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:58:58.241892 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:59:00.358391 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:59:02.461035 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:59:06.197665 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:59:08.322168 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
I0705 09:59:10.451673 50500 rocksdb.cpp:132] Opening RocksDB handle: H:\Release\osquery.db\
E0705 09:59:12.446084 50500 init.cpp:608] [Ref #1629] osqueryi initialize failed: Could not initialize database

Does any suggest about this ?

**Comment by muffins** [comment]
@turtlejamesw the osquery database prevents anyone less than SYSTEM from accessing the database. We currently have an issue open to relax these permissions in #4172.

To your question: if you'd like to see the contents of the database, it's typically better to invoke with `osqueryi --database_path=C:\Path\To\Db --database_dump`. Hooking up the way you're doing will just use that database as a backing store.  Further -- we typically only dump out the database contents for debugging purposes. The data that osquery provides is generated at query time, so there's nothing cached locally. The content that is stored in the DB is used for differential purposes, so it's only ever used if you're doing differential queries, but again, that's not where _results_ are stored, that's just used to "diff" the data that osquery is receiving from the DB. Hope that helps :)

I'm going to close out this issue, and let's keep tabs on tracking these permissions in #4172. If you'd _really_ still like to hook up to the DB, you can grab [psexec](https://docs.microsoft.com/en-us/sysinternals/downloads/psexec) and launch a SYSTEM level shell: `psexec -i -s -d powershell.exe`, and then invoke osqueryi from that shell.
