### ISSUE TITLE
[FeatureRequest] log rotation under windows

### ISSUE THREAD

**Issue by juju4** [facebook/osquery#4680]
Currently, it does not seem there option to rotate either results file, either status files (INFO, WARNING, ERROR)

Same than following issues but on Windows
https://github.com/facebook/osquery/issues/112
https://github.com/facebook/osquery/issues/302

### What version of `osquery` are you using? What operating system. Be specific.
3.2.6, Windows 10, logging to files (not event log)

### Workarounds
use windows event log but not covering status files I believe.

**Comment by theopolis** [comment]
Hi @juju4, I can absolutely understand the need for log rotation. This is outside of the scope of osquery right now. We rely on system-provided log rotation tools since this is a common requirement for lots of tools.

**Comment by grjones** [comment]
It makes total sense that this may not be high priority, but to close this request altogether I think is really too bad. The inability for osquery to rotate its own logs seems like an unfinished product.

**Comment by directionless** [comment]
This was implemented in #7015. See the `--logger_rotate` flag
