### ISSUE TITLE
Support for OpenBSD

### ISSUE THREAD

**Issue by dspruell** [facebook/osquery#4703]
What are the prospects for adding support for OpenBSD to osquery? I noticed FreeBSD support and also that a number of tables are unavailable on that platform as per https://github.com/facebook/osquery/blob/master/specs/blacklist. How involved is such a porting effort (both in terms of general support, and in knocking out some of the blacklisted tables)?

**Comment by obelisk** [comment]
Heyo,

So generally getting core to compile is usually a significant challenge and then needs to be maintained by someone, especially the AWS, YARA, etc extensions. From there, the difficulty of porting a table really depends on while table. Some will probably be quite easy while others might involve concepts that don't transfer cleanly to another operating system (we see this a lot with porting tables to Windows).

**Comment by fmanco** [comment]
I'll close this as it looks the question is answered. Feel free to reopen if needed.
