### ISSUE TITLE
osqueryi crashes on linux when using --profile

### ISSUE THREAD

**Issue by rustybrooks** [facebook/osquery#4712]
We are testing upgrading to a new version of osquery (from 2.11.2 to a 3.2.x version).  Our build process includes testing our queries with the --profile option to osqueryi.  We noticed that with 3.2.6 on linux (specifically I have been testing with ubuntu 16.04) there would be an error/crash.  I have replicated this with some other versions also.

I think the easiest way to reproduce is to use my attached Dockerfile.  It checks out an ubuntu image, installs osquery, and demonstrates the problem.  Note that there are some commented lines in there - one for each version I tried.  You can uncomment the apt-get install for the version of osquery to test against.  If you'd rather not use the Dockerfile, I think it will still give you a very good idea of how to reproduce the issue.

It will print any error messages and at the end will print
`status=<SOMENUMBER>`
where 0 is OK and anything else is an error

The simplest way to try this is to save the Dockerfile, and assuming you have docker installed, run
`docker build . t osquerytest && docker run -it osquerytest`

With osquery 2.11.2 (which works), you would see this:
```
status=0
```

With osquery 3.2.6 (which does not work) you see this:
```
terminating
terminate_handler unexpectedly threw an exception
/bin/bash: line 1:     8 Aborted                 (core dumped) /usr/bin/osqueryi --profile 2 --profile-delay 1 "SELECT * from users" --disable-extensions
status=134
```

Dockerfile
```
FROM ubuntu:16.04

RUN apt-get -y update && apt-get install -y software-properties-common apt-transport-https

RUN export OSQUERY_KEY=1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B \
 && apt-key adv --keyserver keyserver.ubuntu.com --recv-keys $OSQUERY_KEY \
 && add-apt-repository 'deb [arch=amd64] https://pkg.osquery.io/deb deb main' \
 && apt-get update

# These versions work
# RUN apt-get install osquery=2.11.2-1.linux
# RUN apt-get install osquery=3.1.0-1.linux

# These versions do not
# RUN apt-get install osquery=3.2.0-1.linux
# RUN apt-get install osquery=3.2.4-1.linux
RUN apt-get install osquery=3.2.6-1.linux

ENTRYPOINT /bin/bash -c '/usr/bin/osqueryi --profile 2 --profile-delay 1 "SELECT * from users" --disable-extensions; echo status=$?'
```

### What version of `osquery` are you using? What operating system. Be specific.

Fails for me on ubuntu 16.04 version 3.2.0 3.2.4 and 3.2.6
works with versions 2.11.2 and 3.1.0
All versions were install using apt from the repos given in the osquery installation pages

### What have you already tried?

See dockerfile

### What did you expect to see?

Should execute with return code=0

### What did you see instead?

Gives error messages and return code = 134

**Comment by npamnani** [comment]
#4628 fix this

**Comment by rustybrooks** [comment]
I can confirm that if I apply these fixes (mainly the change to main.cpp) then my problem goes away.  I can't comment on the issues brought up in the PR, though.
