### ISSUE TITLE
osqueryi cannot query extension tables from command line

### ISSUE THREAD

**Issue by jkeljo** [facebook/osquery#4723]
### What version of `osquery` are you using? What operating system. Be specific.
```
osquery_version = 3.2.6
     os_version = 10.13.5
       os_build = 17F77
    os_platform = darwin
```

### What have you already tried?
```osqueryi 'select * from some_extension_table;'```

### What did you expect to see?
Results from `some_extension_table`.

### What did you see instead?
```Error: no such table: some_extension_table```

Running `osqueryi` and then entering the query interactively produces results as expected.

**Comment by jkeljo** [comment]
I think this also means that `tools/analysis/profile.py` can't profile extension tables.

**Comment by fmanco** [comment]
This is a race condition because of the way extensions work. Try using `--extensions_require my_extension` and let me know if it works.

**Comment by fmanco** [comment]
Closing, @jkeljo if this didn't fix the issue feel free to reopen.
