### ISSUE TITLE
Kinesis appears non-functioning in osquery 3.2.8

### ISSUE THREAD

**Issue by rustybrooks** [facebook/osquery#4735]
### What version of `osquery` are you using? What operating system. Be specific.

All of my testing has been on ubuntu14.04.  I'm compiling from scratch because I'm trying to use 3.2.8, which is not available as a stable release yet.

The specific version(s) are outlined below - essentially I tried 3.2.6 (which worked) and 3.2.8 (which didn't) and a lot of git revisions in between.

### What have you already tried?

I have a simple osquery config that I have used to test whether osquery can send to kinesis (see below).  I first verified that it worked up to 3.2.6 and failed in 3.2.8, and then started a git bisect between the two.  I finally nailed it down to this commit:
https://github.com/facebook/osquery/commit/9e98cefd22d3399582b016d484506ff110cd33a0
Unsurprisingly, the commit message is

"deps: Update aws-sdk-cpp to version 1.4.55 (#4437)"

If you look at this change, it's only changing some tests, and updating the AWS SDK dependency.  Apparently, something in this upgrade has broken kinesis.

### What did you expect to see?

When using my test config, I have a scheduled query running every few seconds, and it's configured to log via kinesis.  When it succeeds, you'll see messages like

```
 I0719 01:43:55.058900  1567 aws_log_forwarder.h:222] aws_kinesis: Successfully sent 3 out of 3 log records
```

### What did you see instead?

In versions where kinesis is non functional, instead, I will see this

```
E0719 12:02:17.132575  1559 aws_log_forwarder.h:247] aws_kinesis: Complete request failure: Unable to connect to endpoint
```

It takes 10 seconds or so to start seeing these error messages - I assume it's exhasting a number of retries before complaining

Here is the script I use to run the test:

```
#!/bin/bash

mkdir -p /var/log/osquery

touch /tmp/flagfile

/srv/osquery/build/xenial/osquery/osqueryi \
    --tls_server_certs=/tmp/osquery_packaging/prefix/usr/share/osquery/certs/certs.pem \
    --disable-enrollment \
    --flagfile=/tmp/flagfile \
    --config_path=/srv/patch/osquery.conf \
    --watchdog_memory_limit=350 \
    --verbose \
    --logger_path=/tmp
```

And here is the config file I use

```

{
    "schedule": {
        "test": {
            "interval": 2,
            "query": "SELECT strftime('%s','now')"
        }
    },
    "options": {
        "logger_path": "/var/log/osquery/",
        "disable_logging": false,
        "aws_access_key_id": "XXX",
        "logger_event_type": true,
        "aws_region": "us-east-1",
        "aws_kinesis_stream": "my-stream-name",
        "enable_monitor": true,
        "aws_kinesis_random_partition_key": true,
        "logger_plugin": "aws_kinesis,filesystem",
        "logger_min_status": 1,
        "aws_secret_access_key": "YYY",
        "logger_snapshot_event_type": true
    }
}
```

**Comment by arirubinstein** [comment]
+1, confirmed with same behavior on `osquery-3.3.0-1.linux.x86_64.rpm` on amzn2-ami-hvm-2.0.20180810-x86_64-gp2

**Comment by mproffitt** [comment]
I am also seeing this issue when building against the head of master.

Systems tested: ubuntu18.04, centos7.5
Log output 
`aws_log_forwarder.h:247] aws_firehose: Complete request failure: Unable to connect to endpoint`. 

Possibly related is https://github.com/aws/aws-sdk-cpp/issues/794 however I don't ever see a connection being made when running tcpdump over the interface which would suggest the client isn't initialising properly, whilst https://github.com/aws/aws-sdk-cpp/issues/794 relates to a curl redirect issue.

Config file:
```
{
  "options": {
    "config_plugin": "filesystem",
    "logger_plugin": "aws_firehose,filesystem",
    "logger_path": "/var/log/osquery",
    "schedule_splay_percent": "10",
    "pidfile": "/var/osquery/osquery.pidfile",
    "events_expiry": "3600",
    "database_path": "/var/osquery/osquery.db",
    "aws_firehose_stream": "<DELIVERY_STREAM>",
    "aws_access_key_id": "<ACCESS_ID>",
    "aws_secret_access_key": "<SECRET>",
    "aws_region": "us-east-2",
    "verbose": "true",
    "worker_threads": "2",
    "enable_monitor": "true",
    "enable_syslog": "false",
    "disable_audit": "false",
    "disable_events": "false",
    "disable_logging": "false",
    "audit_allow_config": "true",
    "host_identifier": "hostname",
    "audit_allow_sockets": "true",
    "schedule_default_interval": "3600"
  },
  "schedule": {
    "syslog": {
        "query": "SELECT * FROM syslog;",
        "interval": 10
    }
  }
}
```

**Comment by rustybrooks** [comment]
I think I actually narrowed it down to a specific commit - it's the one where they upgraded to a newer version of the AWS library.  I am not sure *why* this has this effect, but if I reverse their change, it works for me.  Let me see if I can find the version # again.

**Comment by mikejwhitehead** [comment]
hey @rustybrooks - running into this same issue as well. Can you let me know what commit you narrowed it down to?

**Comment by rustybrooks** [comment]
I believe it's this commit:
https://github.com/facebook/osquery/commit/9e98cefd22d3399582b016d484506ff110cd33a0

Undoing the change to aws-sdk-cpp.rb "fixed" the problem for me, but obviously that means I'd still be  using the older AWS SDK library.

I'm not currently using a 3.x version, because of this problem and some others (such as, syslog doesn't work on linux now), so I couldn't actually say if reverting the AWS version upgrade would cause other problems.

**Comment by mproffitt** [comment]
So I now believe I have got to the bottom of this.

AWS have changed the implementation and call to HttpClient::MakeRequest, deprecating out the referenced request in favour of a shared pointer.

OsqueryHttpClient only implements:

```cpp
  std::shared_ptr<Aws::Http::HttpResponse> MakeRequest(
      Aws::Http::HttpRequest& request,
      Aws::Utils::RateLimits::RateLimiterInterface* readLimiter = nullptr,
      Aws::Utils::RateLimits::RateLimiterInterface* writeLimiter =
          nullptr) const override;
```
As a result of the AWS change, this never gets called, instead falling back to the AWS default implementation at [AWS::HttpClient#L62)(in https://github.com/aws/aws-sdk-cpp/blob/97dd77fbcdf3d1565a04bea7941421adaed5bfc9/aws-cpp-sdk-core/include/aws/core/http/HttpClient.h#L62) which is defined as:

```cpp
virtual std::shared_ptr<HttpResponse> MakeRequest(const std::shared_ptr<HttpRequest>& request,
                Aws::Utils::RateLimits::RateLimiterInterface* readLimiter = nullptr,
                Aws::Utils::RateLimits::RateLimiterInterface* writeLimiter = nullptr) const
            {
                AWS_UNREFERENCED_PARAM(request);
                AWS_UNREFERENCED_PARAM(readLimiter);
                AWS_UNREFERENCED_PARAM(writeLimiter);
                return nullptr;
            }
```
It looks like this change was introduced in AWS commit [9932464dd84](https://github.com/aws/aws-sdk-cpp/commit/9932464dd84)

By adding an override of this method in https://github.com/facebook/osquery/blob/0314871908273b2770129da9f5a7c3206f224f68/osquery/utils/aws_util.h#L65 which calls `MakeRequest(HttpRequest& ...)` and dereferencing the pointer to `request`, the requests go through successfully.

```cpp
std::shared_ptr<Aws::Http::HttpResponse> OsqueryHttpClient::MakeRequest(
      const std::shared_ptr<Aws::Http::HttpRequest>& request,
      Aws::Utils::RateLimits::RateLimiterInterface* readLimiter,
      Aws::Utils::RateLimits::RateLimiterInterface* writeLimiter) const {
    VLOG(1) << "Using shared_ptr for request";
    return MakeRequest(*request, readLimiter, writeLimiter);
}
```

This is probably not the cleanest method but suffices for now and would enable the AWS SDK to be upgraded to 1.6.15 and above.

**Comment by rustybrooks** [comment]
This appears to be fixed in master, but does not exist in a tagged release yet, but I expect it will soon.
