### ISSUE TITLE
Incorrect Results in Gatekeeper Table

### ISSUE THREAD

**Issue by kliseb** [facebook/osquery#4748]
### What version of `osquery` are you using? What operating system. Be specific.
```
osquery_version = 3.2.6
     os_version = 10.13.6
       os_build = 17G65
    os_platform = darwin
```

### What have you already tried?
When running a query on hosts to check if gatekeeper is enabled, I found that it returns incorrect results. As you can see here, gatekeeper is enabled on my machine:
```
$ spctl --status
assessments enabled
```
I looked in `gatekeeper.cpp` and found that `genGateKeeper()` first checks to see if `/var/db/SystemPolicy-prefs.plist` exists and sets `assessments_enabled` to 0 if it does not exist, even if gatekeeper *is* enabled.

The issue I found is that a lot of times `/var/db/SystemPolicy-prefs.plist` doesn't exist by default, yet the system still knows if gatekeeper is enabled (when I ran `spctl --status` above, `/var/db/SystemPolicy-prefs.plist` didn't exist). However, if you run `sudo spctl --master-enable`, or if you change your settings in `System Preferences -> Security & Privacy -> Allow apps downloaded from:`, the file is created and the gatekeeper table returns the correct results, but I don't want to require every user in our fleet to do this.

### What did you expect to see?
Without having to run a command or change settings as I mentioned above, I would expect to see this:
```
osquery> select * from gatekeeper;
+---------------------+----------------+---------+----------------+
| assessments_enabled | dev_id_enabled | version | opaque_version |
+---------------------+----------------+---------+----------------+
| 1                   | 1              | 7.2     | 148            |
+---------------------+----------------+---------+----------------+
```

### What did you see instead?
```
osquery> select * from gatekeeper;
+---------------------+----------------+---------+----------------+
| assessments_enabled | dev_id_enabled | version | opaque_version |
+---------------------+----------------+---------+----------------+
| 0                   |                | 7.2     | 148            |
+---------------------+----------------+---------+----------------+
```

**Comment by rhuddleston** [comment]
Any update on this issue? I've been trying to roll osquery out and most of my users show as having gatekeeper disabled even though that's not the case. Looks like /var/db/SystemPolicy-prefs.plist doesn't exist unless the user actually tries to change their gatekeeper settings from the default.

**Comment by terracatta** [comment]
I might have time to do fix this over the weekend but here is the fix:

On https://github.com/facebook/osquery/blob/master/osquery/tables/system/darwin/gatekeeper.cpp#L79

Instead of setting to 0 we want to set both `assessments_enabled` and `dev_id_enabled` to 1.

That should do the trick.
