### ISSUE TITLE
windows: intel_me_info table broken on newer Intel hardware

### ISSUE THREAD

**Issue by keeleysam** [facebook/osquery#4765]
### What version of `osquery` are you using? What operating system. Be specific.
osquery 3.2.9
Windows 10 1803

### What have you already tried?
I have tried to use the `intel_me_info` table on some newer Windows laptops, including a 2017 ThinkPad X1 Carbon, ThinkPad 25, and Dell Latitude 3490.

### What did you expect to see?
I expected to see the version of the management engine returned, such as `11.8.50.3425`.

### What did you see instead?
It always returns `0.0.0.0`

### Notes
This table definitely works on some older devices, such as a Vizio CT15-A1 which I dug up.  On that one, it returns `8.0.2.1410` as expected.

This table should be very useful for verifying patch status for recent Intel ME vulnerabilities such as https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00086.html and https://www.intel.com/content/www/us/en/security-center/advisory/intel-sa-00112.html.

**Comment by muffins** [comment]
I'm seeing the same behavior on my MSI Z170A with an Intel Skylake i5, and also a Lenovo T470s

**Comment by keeleysam** [comment]
From running this internally, it seems to be working on 4th gen and older (major versions of 7, 8, 9) but broken on 6th gen and later (major version of 11).  Not sure about 5th gen (major version 10), as I don't have one on hand to test with.

**Comment by keeleysam** [comment]
Thanks for the fix!
