### ISSUE TITLE
Report on Oracle Linux Server 6.6 build

### ISSUE THREAD

**Issue by jfunction** [facebook/osquery#479]
Hi - I just wanted to say a thing or two about my experience compiling osquery on Oracle Linux Server 6.6
If this isn't the place for such a report, I apologize. Please redirect me and close the issue.

Firstly, the kernel headers (3.8) are older than the prerequisite in provision.sh (3.10), so I scrapped that line.
Secondly, I had to make sure gcc was updated which didn't seem to be the case by the time glog was being built.
Lastly, I had to add pthread to the list of libraries being linked in tools/CMakeLists.txt, so that the changed line became:
TARGET_LINK_LIBRARIES(flag_test gflags glog pthread)

In particular I wondered why it was compiling on Ubuntu without this change and why the dependancy for kernel version 3.10 was required. I did however note that Oracle Linux 7 comes with kernel 3.10.

My build passes all tests and I was able to query each table without errors/warnings.

**Comment by theopolis** [comment]
Hey @jfunction can you check if this is still an issue? I've made some modifications to linking/building and may have introduced more problems or fixed these. ;)

**Comment by theopolis** [comment]
I think we're more or less GTG with the dependencies now.
