### ISSUE TITLE
 Cannot use kafka_producer logger on windows

### ISSUE THREAD

**Issue by thordin9** [facebook/osquery#4795]
I am trying to setup osquery using kafka_producer on windows.  i am running
c:\ProgramData\osquery\osqueryd> .\osqueryd.exe --verbose from powershell as an admin
using with the following configuration file osquery.conf (in C:\ProgramData\osquery\)
taken from https://osquery.readthedocs.io/en/stable/deployment/logging/#logging-as-a-kafka-producer
```

{
  "options": {
    "logger_plugin": "kafka_producer",
    "logger_kafka_brokers": "xxxxx",
    "logger_kafka_topic": "base_topic",
    "logger_kafka_acks": "1"
  },
  "packs": {
    "system-snapshot": {
      "queries": {
        "some_query1": {
          "query": "select * from system_info",
          "snapshot": true,
          "interval": 60
        },
        "some_query2": {
          "query": "select * from md_devices",
          "snapshot": true,
          "interval": 60
        },
        "some_query3": {
          "query": "select * from md_drives",
          "snapshot": true,
          "interval": 60
        }
      }
    }
  },
  "kafka_topics": {
    "test1_topic": [
      "pack_system-snapshot_some_query1"
    ],
    "test2_topic": [
      "pack_system-snapshot_some_query2"
    ],
    "test3_topic": [
      "pack_system-snapshot_some_query3"
    ]
  }
}
```
### What version of `osquery` are you using? What operating system. Be specific.
Version is 3.2.9 (chocolatey) or 3.2.6 (msi installer) on windows server 2016 standard 64bit
version 10.0.14393 build 14393

### What have you already tried?

I tried installing different versions using chocolatey and msi installer 3.2.9, 3.2.6 and 2.11.2
I tried using the same osquery.conf on linux fedora 28 64bit using the latest rpm 3.2.6
and it works as expected.
### What did you expect to see?
i expected the same as in the linux system that is the osquery to communicate with the kafka broker and log in topics.

### What did you see instead?
execution stops with error
E0802 13:41:23.590608   740 init.cpp:557] Cannot activate kafka_producer logger plugin: Unknown registry plugin: kafka_producer

```
PS C:\ProgramData\osquery\osqueryd> .\osqueryd.exe --verbose
I0802 13:41:23.340605  4800 init.cpp:380] osquery initialized [version=2.11.2]
I0802 13:41:23.371860  4800 system.cpp:344] Found stale process for osqueryd (1620)
I0802 13:41:23.371860  4800 system.cpp:377] Writing osqueryd pid (4016) to \ProgramData\osquery\osqueryd.pidfile
I0802 13:41:23.371860  4800 extensions.cpp:300] Could not autoload extensions: Failed reading: \ProgramData\osquery\exte
nsions.load
I0802 13:41:23.403107  4920 watcher.cpp:549] osqueryd watcher (4016) executing worker (5056)
I0802 13:41:23.434356   740 init.cpp:377] osquery worker initialized [watcher=4016]
I0802 13:41:23.434356   740 rocksdb.cpp:132] Opening RocksDB handle: \ProgramData\osquery\osquery.db
I0802 13:41:23.481232  2928 interface.cpp:338] Extension manager service starting: \\.\pipe\osquery.em
W0802 13:41:23.574978   740 options.cpp:75] Cannot set unknown or invalid flag: logger_kafka_brokers
W0802 13:41:23.574978   740 options.cpp:75] Cannot set unknown or invalid flag: logger_kafka_topic
W0802 13:41:23.574978   740 options.cpp:75] Cannot set unknown or invalid flag: logger_kafka_acks
E0802 13:41:23.590608   740 init.cpp:557] Cannot activate kafka_producer logger plugin: Unknown registry plugin: kafka_producer
```

**Comment by guliashvili** [comment]
Hi @thordin9,
Thanks for opening the issue.

Looks like it's the expected behavior. Please see.
https://github.com/facebook/osquery/blob/master/osquery/logger/CMakeLists.txt#L54

Right now, there are no plans of extending current implementation for other platforms. I would be more than happy to support you if you decide to implement it.

**Comment by thordin9** [comment]
hi @guliashvili that clears it up! i appreciate your fast response on this.

**Comment by thordin9** [comment]
@guliashvili hi again, i and my colleagues are interested in implementing this. i can see in
https://github.com/facebook/osquery/pull/3155/commits/afd2e73843facb0dc77c65b45e98a45d833b87c3#diff-81a5a39e3cf862ddd15f6b2f5d3f6312R65
that windows support was disabled from the initial commit that kafka producer was added. can you please expain the reason we this is and/or provide some information about what needs to be done to enable this?

**Comment by guliashvili** [comment]
@thordin9 probably it was not needed, so no one put extra effort in that. For that, adding dependencies for windows would be necessary. I think, reviewing how other plugins are implemented for windows will help. This doc might also be helpful https://osquery.readthedocs.io/en/stable/development/windows-provisioning/.

**Comment by Vbakalis** [comment]
@guliashvili  I removed "AND NOT WINDOWS" as per your instructions and i get this error :"fatal error librdkafka/rdkafka.h no such file or directory". I  copied the librdkafka file from here : https://github.com/MichaelZhangCA/confluent-kafka-python/tree/master/librdkafka-reference/librdkafka ,to the same directory that contain the other header files, but i still get the same error. Can you please guide me through?
