### ISSUE TITLE
Build fails on macOS 10.13 ssdeep bottles are not correct arch

### ISSUE THREAD

**Issue by terracatta** [facebook/osquery#4855]
# Bug report

### What operating system and version are you using?

macOS 10.13.6 (17G65)

### What version of osquery are you using?
commit cf59b05

### What steps did you take to reproduce the issue?

1. `git clone` the osquery repository
1. run `make depsclean` to ensure you do not have any existing osquery dependencies installed
1. run `make deps`
1. run `make`

### What did you expect to see?

A successful build

### What did you see instead?

```
[ 81%] Linking CXX executable osquery_additional_tests
ld: warning: ignoring file /usr/local/osquery/lib/libfuzzy.a, file was built for archive which is not the architecture being linked (x86_64): /usr/local/osquery/lib/libfuzzy.a
Undefined symbols for architecture x86_64:
  "_fuzzy_hash_filename", referenced from:
      osquery::tables::genHashForFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, osquery::QueryContext&, std::__1::vector<std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > >, std::__1::allocator<std::__1::map<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::less<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >, std::__1::allocator<std::__1::pair<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > > > >&) in lto.o
  "_fuzzy_compare", referenced from:
      osquery::sqliteSsdeepCompareFunc(sqlite3_context*, int, sqlite3_value**) (.llvm.D284339E) in lto.o
ld: symbol(s) not found for architecture x86_64
```

The commit that prevents me from building osquery is b7079f41f55f61804f7b9f088db570b73aef536. If I roll back before this commit and follow the repro steps, I get a successful build.

**Comment by fmanco** [comment]
@jkeljo manage to reproduce this under some conditions, but we need to investigate a bit more what's going on. I'll look into this.

**Comment by theopolis** [comment]
So is the root cause that the bottles were built on a 10.12 host, preventing linking on a 10.13 host? If so then we should move the deps build Vagrant to 10.13.

For context, the ssdeep-cop bottles were built using the same tools/release/deps_release script as all others.

**Comment by theopolis** [comment]
Wait, this is much simpler and annoying. I haven’t verified this in code but macOS is selecting the first bottle hash, for this formula the x86_64/Linux comes before Sierra.

The solution is flipping the order of hashes in the formula, and changing the revision to 201 to clear out previous installs.

**Comment by jkeljo** [comment]
@theopolis like this (#4975)? Seems to work locally, though I don't know how to do the rest of the stuff in https://github.com/facebook/osquery/blob/master/docs/wiki/development/building.md#adding-or-changing-dependencies

**Comment by fmanco** [comment]
@theopolis but isn't this going to make Linux not work? Or is this behaviour of picking the first only on macs?

**Comment by jkeljo** [comment]
@fmanco from the test runs on #4975 it certainly seems like Linux still works
