### ISSUE TITLE
Error when trying to run osqueryd (1.1.0) on Mavericks

### ISSUE THREAD

**Issue by timberbee** [facebook/osquery#494]
dyld: Library not loaded: /usr/local/lib/libgflags.2.dylib
  Referenced from: /usr/local/bin/osqueryd
  Reason: image not found
Trace/BPT trap: 5
And it's not lying, that dylib is not there or anywhere else on my machine. How can i restore it?

**Comment by dejayc** [comment]
Can someone please explain why this issue was closed?  I just tried to install the osquery 1.5.0 package on Mavericks, and I'm getting exactly the same issue above.

**Comment by marpaia** [comment]
@dejayc `brew update && brew upgrade osquery`

**Comment by marpaia** [comment]
https://github.com/Homebrew/homebrew/pull/41965

**Comment by dejayc** [comment]
You can imagine how much I want to cry when I see this message, when attempting to install on Mavericks:

```osquery: OS X Yosemite or newer is required.```

**Comment by theopolis** [comment]
Upgrade to 10.10!

**Comment by dejayc** [comment]
Wish it were that simple.  osquery supports Mavericks, no?  I get the error above when installing via the official binary package.  So I guess osquery doesn't really support Mavericks any longer, which is a shame.  The documentation should be updated to reflect that.

**Comment by timberbee** [comment]
I have it installed via homebrew and it works fine 

Tim Burby
| 415.328.6100 cell |

**Comment by theopolis** [comment]
Yeah, I realize and share the annoyance. We're working slowing to get 10.9 back online. The struggle is around a single OS X package that runtime determines what APIs/frameworks are available and likewise enables additional tables on newer operating systems. The easy way out is a package per version, but then easy turns into complicated when considering hosting/signing baggage for multiple package forks.

**Comment by dejayc** [comment]
Awesome.  You'll have this problem going forward, too, as I assume the successor to Yosemite will have features and utilities not available to Yosemite or Mavericks.  Solving it the right way, once, would be a good thing.
