### ISSUE TITLE
osquery.man missing from msi, ok chocolatey

### ISSUE THREAD

**Issue by juju4** [facebook/osquery#5067]
# Bug report

### What operating system and version are you using?
Windows server 2016 or Win10

### What version of osquery are you using?

3.2.6

### What steps did you take to reproduce the issue?

install osquery from msi

### What did you expect to see?

osquery.man file in c:\ProgramData\osquery

### What did you see instead?

no file.
https://ci.appveyor.com/project/juju4/ansible-win-osquery/build/0.1.x.63/job/l6smsm51ob1nwa9j?fullLog=true#L1478

but present if doing install with chocolatey.

**Comment by muffins** [comment]
> but present if doing install with chocolatey.

This file isn't bundled with _either_ the MSI or the Chocolatey repo, as it's somewhat non-standard (for osquery) to come with the `.man` file on Windows. It shouldn't be too difficult for the file to be bundled along with deployments, if anyone were so inclined to add this to the deployment scripts :)

**Comment by juju4** [comment]
it is inside chocolatey. 
It was not inside my ansible role and I could apply documented install step directly.
I had to with a msi install.

https://github.com/facebook/osquery/blame/master/tools/deployment/make_windows_package.ps1#L496 has the line for osquery.man: "$windowsEventLogManifestPath".
=> only part of function New-ChocolateyPackage()

function New-MsiPackage() does not include $windowsEventLogManifestPath either in params, either in $wix xml config

**Comment by juju4** [comment]
fixed
