### ISSUE TITLE
Translate Readme.md to Spanish

### ISSUE THREAD

**Issue by ucdstudent95618** [facebook/osquery#5079]
Hi osquery team,

I want to translate the GitHub page to Spanish, where can I find the files to do it?

Thanks,

Miguel

**Comment by muffins** [comment]
Hey @ucdstudent95618! All of the osquery documentation lives in the repository under the [`docs`](https://github.com/facebook/osquery/tree/master/docs) folder, you should be able to use those as a starting ground for translation. I'm going to close this issue out, but feel free to re-open or let us know if you have any other further questions, happy hacking! :)
