### ISSUE TITLE
Update Yum/Apt repos with up to date packages when releases are marked stable

### ISSUE THREAD

**Issue by clong** [facebook/osquery#5110]
Hi folks, this is just an issue to report that the last 2-3 releases of osquery have had massively delayed deployments to Yum/Apt. Can a process be implemented to ensure there's not a multi-day delay when this happens in the future?

**Comment by rhuddleston** [comment]
It's been over 50 days since osquery came out can we please update the apt repo :)

**Comment by wirehat** [comment]
Any update on this?

**Comment by frankgraziano** [comment]
Any update on this?

**Comment by robusto** [comment]
3.3.2 has recently been released and the latest reported is still 3.2.6 for Debian and Yum packages.

**Comment by theopolis** [comment]
I am working on this https://github.com/osquery/osquery-site/pull/115

A fair heads up, the 3.3.2 version has not been 'battle tested' as much as previous releases. I see a significant number of Windows hosts running 3.3.1 and a significant number of Linux hosts running a few commits behind 3.3.1. I will end to end test 3.3.2, land the site-stable bump for downloads, then move the repository indexes to point to 3.3.2 as well.

It would be great to get some quick feedback here if you deploy and have issues.

**Comment by clong** [comment]
I think we're probably good to close this issue out, but would like to see better communication from the osquery team about release timelines especially if there is expected to be a large delta between the website release vs repo releases
