### ISSUE TITLE
How to build osquery on ARMv7 architecture running ubuntu-18.04 ?

### ISSUE THREAD

**Issue by abhi18av** [facebook/osquery#5252]
Hi Facebook team,

I'd like to know if it's possible to build osquery for the ARM architectures ?  I'm running scaleway C1 bare metal server and I'd like to experiment with osquery on that server.

**Comment by muffins** [comment]
Hey there! Currently ARM support for osquery isn't supported. I believe it might be possible to make this happen, but it's not something we can help you with, and will likely be very difficult to make happen.

**Comment by jbyrnescu** [comment]
Just as a clarification, (as I f things aren’t clear enough right?), I built this for another arm architecture (aarch or aarch64, or something like that.). It’s just when I attempted to do the same for armv7l 32 bit architecture, it specifically errored out saying this architecture wasn’t supported.

**Comment by jbyrnescu** [comment]
So _ some_ arm architectures work.  Just not armv7l.

**Comment by theopolis** [comment]
Right, armv7l doesn't seem like a worthwhile investment. I'm unsure of anyone running production services on 32-bit ARM.
