### ISSUE TITLE
Multiple problems with YARA

### ISSUE THREAD

**Issue by thomasareed** [facebook/osquery#5272]
# Bug report

### What operating system and version are you using?

```
osquery> select version, build, platform from os_version;
 version = 10.14
   build = 18A391
platform = darwin
```

### What version of osquery are you using?

```
osquery> select version from osquery_info;
version = 3.3.0
```

### What steps did you take to reproduce the issue?

1. Create a yara rule to match the string "com.apple.Safari.content-blocker" at the following path: /private/var/osquery/Safari_ext.sig
2. Verify that the yara rule file works properly when run using yara at the command line
3. Use on demand yara in osquery to scan paths in the Applications folder - both with wildcards and specifying an exact file - that should match a particular Info.plist file, for testing purposes

### What did you expect to see?

I would expect to see a result like the following:

```
     path = /Applications/AdBlock.app/Contents/PlugIns/AdBlock-Extension.appex/Contents/Info.plist
  matches = Safari_ext
    count = 1
sig_group = /private/var/osquery/Safari_ext.sig
  sigfile = /private/var/osquery/Safari_ext.sig
  strings = $a:572
     tags = 
```

### What did you see instead?

Results for each query tried are as follows:

`select * from yara where pattern='/Applications/%.app/Contents/PlugIns/%.appex/Contents/Info.plist' and sigfile='Safari_ext.sig';`

Results: an error message reading "Error: no such column: pattern". There is a disconnect between the documentation at the following page and the actual yara table.

https://osquery.readthedocs.io/en/stable/deployment/yara/

`select * from yara where path like '/Applications/%.app/Contents/PlugIns/%.appex/Contents/Info.plist' and sigfile='Safari_ext.sig';`

No results.

`select * from yara where path='/Applications/%.app/Contents/PlugIns/%.appex/Contents/Info.plist' and sigfile='Safari_ext.sig';`

No results.

`select * from yara where path='/Applications/AdBlock.app/Contents/PlugIns/AdBlock-Extension.appex/Contents/Info.plist' and sigfile='Safari_ext.sig';`

No results. (Using exactly the same Info.plist file path and yara rules file with yara directly shows a match.)

`select * from yara where path like '/Applications/%.app/Contents/PlugIns/%.appex/Contents/Info.plist' and sigfile='/private/var/osquery/Safari_ext.sig';`

Results: data for a large number of Info.plist files with matching paths is output, despite the fact that few of them actually match the yara rule provided.

**Comment by packetzero** [comment]
Using a query like the following should work.
```
path LIKE '/Applications/%.app/Contents/PlugIns/%.appex/Contents/Info.plist'
  AND sigfile='/tmp/test1.yara'
  AND count > 0
```
A few things to note:
 -  The LIKE keyword enables the path wildcards.
 - Use full path to the sigfile.
 - specify count > 0 to only return results that match

That said, the documentation referencing 'pattern' column needs to be updated.

**Comment by thomasareed** [comment]
Thanks, that works!

**Comment by obelisk** [comment]
Closing this issue. Reopen if I missed something. Thanks @packetzero!
