### ISSUE TITLE
Weekend days missing from kernel_panics

### ISSUE THREAD

**Issue by init99** [facebook/osquery#5297]
# Bug report

### What operating system and version are you using?
macOS Mojave 10.14.1

### What version of osquery are you using?
3.2.4

### What steps did you take to reproduce the issue?

1. Have, or edit, a kernel panic occurring on a weekend. E.g. /Library/Logs/DiagnosticReports/Kernel_2018-10-28-085150_username-macbookpro.panic 

### What did you expect to see?
osquery> select time, path from kernel_panics;
+--------------------------+------------------------------------------------------------------------------------------+
| time                     | path                                                                                     |
+--------------------------+------------------------------------------------------------------------------------------+
| Sun Oct 28 08:51:50 2018 | /Library/Logs/DiagnosticReports/Kernel_2018-10-28-085150_username-macbookpro.panic       |

### What did you see instead?
osquery> select time, path from kernel_panics;
+--------------------------+------------------------------------------------------------------------------------------+
| time                     | path                                                                                     |
+--------------------------+------------------------------------------------------------------------------------------+
|  | /Library/Logs/DiagnosticReports/Kernel_2018-10-28-085150_username-macbookpro.panic       |

**Comment by init99** [comment]
Set to fix: https://github.com/facebook/osquery/blob/37e5c9f4b6d406b554e8af9b9eb230fc51a6e830/osquery/tables/system/darwin/kernel_panics.cpp#L42

**Comment by obelisk** [comment]
This is awesome
