### ISSUE TITLE
osquery occupies too much disk

### ISSUE THREAD

**Issue by dabeike** [facebook/osquery#5310]
# Bug report

### What operating system and version are you using?

```
# osqueryi --line "SELECT version, build, platform FROM os_version;"
 version = CentOS Linux release 7.4.1708 (Core)
   build = 
platform = rhel
```

### What version of osquery are you using?

```
# osqueryi --line "SELECT version from osquery_info;"
version = 3.3.0
```

### What steps did you take to reproduce the issue?

I add a schedule query for osqueryd to collect disk size used by rocksdb :
```
select sum(size) as bytes_disk from file where path like '/var/osquery/osquery.db/%';
```
In order to reduce disk occupied by it, I add some limitations in osquery.flags:
![image](https://user-images.githubusercontent.com/9197693/49077419-31c72e80-f276-11e8-98c8-9585c7fb790a.png)

But the result still turns out to be like this:
![image](https://user-images.githubusercontent.com/9197693/49080030-41964100-f27d-11e8-8e7b-22e0aa2f8b51.png)

### What did you expect to see?
Most of the machines take up less than 200M of disk space, while a few of it  takes up to 600M of disk space.

I read the content of the .sst file, and grep it by name. Here is the command:
```
sudo /tmp/sst_dump --file=/var/osquery/osquery.db/ --command=scan | wc -l
sudo /tmp/sst_dump --file=/var/osquery/osquery.db/ --command=scan  | grep process_events | wc -l 
sudo /tmp/sst_dump --file=/var/osquery/osquery.db/ --command=scan  | grep socket_events | wc -l 
```
And here is the result:
```
# host_1
1380917
1281996
62917
 
# host_2
1149855
1126230
14024
 
# host_3
1693820
1649105
23780
 
# host_4
1173181
1117843
45165
```

Rocksdb saves 100w+ lines, while 99% of it are process_events data. It's obvious that the `events_max` flag didn't take effect.

I want to know if this is normal. And What should I do to reduce the disk usage? How osqueryd expiring data?

Need your help. Thanks!

**Comment by dabeike** [comment]
I found that osquery will expire events when starting, so I made a test.
Firstly, I saw the numbers of socket_events log before restart osqueryd
```
sst_dump --file=/var/osquery/osquery.db/ --command=scan  | grep socket_events | wc -l
577486
```
And then executed:
```
systemctl restart osqueryd
```

And got this in `/var/log/osquery/osquery.INFO`:
```
Log file created at: 2018/11/28 16:07:35
Running on machine: hostname
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1128 16:07:35.702229 31583 events.cpp:862] Event publisher not enabled: syslog: Publisher disabled via configuration
I1128 16:07:45.402627 31583 events.cpp:1115] Error registering subscriber: process_file_events: Subscriber disabled via configuration
I1128 16:07:48.002794 31583 events.cpp:1115] Error registering subscriber: selinux_events: Subscriber disabled via configuration
W1128 16:07:50.805047 31583 events.cpp:311] Expiring events for subscriber: socket_events (overflowed limit 5000)
I1128 16:07:50.805352 31583 events.cpp:313] Subscriber events socket_events exceeded limit 5000 by: 15280
I1128 16:07:59.304909 31583 events.cpp:744] Subscriber expiration is too low: process_events
I1128 16:07:59.509066 31927 events.cpp:783] Starting event publisher run loop: auditeventpublisher
I1128 16:07:59.509125 31929 events.cpp:783] Starting event publisher run loop: inotify
I1128 16:07:59.509127 31930 events.cpp:783] Starting event publisher run loop: udev
I1128 16:07:59.509690 31925 auditdnetlink.cpp:302] Attempting to configure the audit service
I1128 16:07:59.509744 31925 auditdnetlink.cpp:320] Enabling audit rules for the socket_events table
I1128 16:07:59.509760 31925 auditdnetlink.cpp:329] Enabling audit rules for the process_events table
```
And in `/var/log/osquery/osquery.WARNING`:
```
Log file created at: 2018/11/28 16:07:50
Running on machine: hostname
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
W1128 16:07:50.805047 31583 events.cpp:311] Expiring events for subscriber: socket_events (overflowed limit 5000)
```
And then saw socket_event count again:
```
./sst_dump --file=/var/osquery/osquery.db/ --command=scan  | grep socket_events | wc -l
571097
```

It's very strange. I have 500,000+ lines of socket_events log actually, but osqueryd only found (5000+15280=20280)   of it.

And expiring while inserting data into rocksdb seems to be stopped.  I waited for half an hour, and executed:
```
> sst_dump --file=/var/osquery/osquery.db/ --command=scan  | grep socket_events | wc -l
576331
> cat /var/log/osquery/osqueryd.INFO | grep "Subscriber events"
I1128 16:07:50.805352 31583 events.cpp:313] Subscriber events socket_events exceeded limit 5000 by: 15280
```
The only log is logged when starting osqueryd...

It seems that osquery lost the control of old log in rocksdb. This should be why osquery occupies so much disk in a few of my machines.

**Comment by dabeike** [comment]
I watched the source code, and found some logical error in it.

Firstly,  the expireCheck is not running as expect.
![image](https://user-images.githubusercontent.com/9197693/49434361-fd5fef00-f7ee-11e8-810a-0718859fc55c.png)

And normally, events datas in rocksdb should be devided into two types:
* records.auditeventpublisher.socket_events: it records the index_key for the real socket_events logs
* data.auditeventpublisher.socket_events: it records the real log

When it's normal, it should be like this:
![image](https://user-images.githubusercontent.com/9197693/49434603-7fe8ae80-f7ef-11e8-874d-7990cfd4bd3f.png)
In the machines which didn't remove old logs, it didn't have `records log`:
![image](https://user-images.githubusercontent.com/9197693/49434693-b4f50100-f7ef-11e8-9d9d-407aef918464.png)

I think it's why osqueryd can't expire these old logs, it just can't found the `data log` without `records log`. 

But I don't know why osquery removed `records log` without remove `data log`. It happens in 10% of all my machines, but it affects on-line progress heavily. My solution now is remove `*.sst` file older than 1 day by bash shell, but I do want to find an elegant solution for this problem. 

Looking forward for your reply. TKS!

**Comment by guliashvili** [comment]
This is great catch. Thank you for finding it. Will fix it as soon as I have some time.

**Comment by guliashvili** [comment]
#5335 should have solved it

**Comment by uptycs-nishant** [comment]
@dabeike 

./sst_dump --file=/var/osquery/osquery.db/ --command=scan  | grep socket_events | wc -l

Does not mean that all the data is coming from events column family. Reading from sst files include everything

Use -
ldb --db=<path to db> scan --column_family="events"
 for exact count of events

**Comment by dabeike** [comment]
thanks, but I don't think the PR has fix all the problems. There's still a lots of old sst file in rocksdb's directory.
![image](https://user-images.githubusercontent.com/9197693/53163195-832e5200-3608-11e9-8061-218512fb28bf.png)

The content of the sst file are mainly datas. In this machine, it has 1,021,003 lines. These `data`'s eid are not logged in any `records` and `indexes`. 
![image](https://user-images.githubusercontent.com/9197693/53163705-a279af00-3609-11e9-9784-122d2576766e.png)

![image](https://user-images.githubusercontent.com/9197693/53164033-52e7b300-360a-11e9-96cb-925363b71ff2.png)

I review the function expireRecord and expireIndexes in events.cpp,  trying to find why osquery deleted the `records` and `indexes` line without deleted the `data` line. But nothing found.

**Comment by packetzero** [comment]
Do you have extensions enabled?  Can you turn off extensions and try again?  It looks like a code path in checkExpire() will call scanDatabaseKeys(), and if there's an external registry, the database will never be scanned... leading to event cache that never gets cleaned up.  I'm going to guess that most of us that tried to reproduce this did it without extensions on.
![ssscandatabasekeys](https://user-images.githubusercontent.com/20775507/53194683-94139f00-35d9-11e9-9260-2112a91b9c68.png)

**Comment by dabeike** [comment]
Sorry to say, I didn't use any extension. Does osquery have any default extension? 
I found most of the logs are starting from Feb 15. I remember that I should have changed some config using tls (doorman), maybe there is some problem with config change?

I can send you a pack of db files. Maybe it can stimulate your inspiration.

**Comment by packetzero** [comment]
I must be wrong about that then.  the get().external() must mean "if I am an extension" rather than "if I have an extension"

**Comment by dabeike** [comment]
![image](https://user-images.githubusercontent.com/9197693/53223773-6a2bac80-36ad-11e9-8d0e-578116964a07.png)

Is there any multi_processing used when inserting when to rocksdb? If `expire_records` are not sorted,   it's possible for osquery to delete the `indexes` and `records` without delete **all** the `data`

**Comment by uptycs-nishant** [comment]
@dabeike , is it possible for you to provide the DB for analysis?

**Comment by dabeike** [comment]
@uptycs-nishant  sorry for seeing this message so late. 
Yes, I can send you the db files.  Please me your email address, or contact me at slack (@fr1day). I searched your name in  the slack's osquery #general group, but couldn't find you.
