### ISSUE TITLE
Watchdog process not stopping when osqueryd service is stopped

### ISSUE THREAD

**Issue by sm-green** [facebook/osquery#5341]
# Bug report

### What operating system and version are you using?

 version = 10.0.15063
   build = 15063
platform = windows

This behavior is also seen on Windows 7 and Windows Server 2012 r2

### What version of osquery are you using?

version = 3.3.1-1-g5188ce52

### What steps did you take to reproduce the issue?
In Services, stop osqueryd.  Open Task Manager, an osqueryd.exe process still exists.

When uninstalling:
Use WiX to build an osquery MSI with extensions  included
Install the osquery package on a Windows 10 host
Uninstall osquery from the Control panel
Confirm in Task Manager whether any osqueryd.exe processes remain

### What did you expect to see?
No running osqueryd.exe processes after stopping osqueryd service in Windows

### What did you see instead?
After stopping osqueryd, which reports as stopped, I see an osqueryd.exe process still running and keeping a file lock on osquery.db.

This started as an issue during uninstallation of osquery, but I'm expanding it to include the stopping of the service.  We have multiple extensions running with osquery.

Related thread from Slack:
greetings all, 2 part question.  1) when stopping osqueryd service, there still remains an osqueryd.exe process, which I assume is the watchdog process.  this looks to keep a lock on osquery.db/, which prevents a clean uninstall.  is that expected behavior?  2) I'm trying to build a custom msi with the WiX toolset and using a custom action to taskkill osqueryd.exe, but that doesn't work.  anyone have some experience there?

I'm using 3.3.1 from git as my source and testing on Windows 10.

thor
1.) Not expected behavior. If you can reliable repro this would you mind cutting an issue for us? We had issues with this previously, and we've seen it happening in our environment, but specifically it's only when we have extensions running with the watchdog process disabled. Osquery on it's own, no extensions, with watchdog _enabled_ doesn't seem to have this issue from what I've seen on 3.3.1

thor
2.) For the custom WiX script -- we have a `tools\deployment\make_windows_package.ps1` I think, which renders the XML for a WiX script to create an MSI for deployment. It's pretty basic and generic, but you should be able to follow what that script is doing and make changes as needed to get your custom logic. Aside from that I think @groob had some experience messing with WiX scripts for deployment?

**Comment by sm-green** [comment]
This issue also affects restarting the osqueryd service in Windows 10, Windows 7, and Windows Server 2012 r2.  After stopping the osqueryd service, there is a zombie osqueryd.exe process showing in the Task Manager, and you need to manually kill it.

**Comment by muffins** [comment]
This looks like #4235 isn't fully fixed. We've seen this issue before, not sure what specifically is broken but I'll take a look when I get time!

**Comment by muffins** [comment]
Also to be clear, I don't think this is the watchdog process that isn't stopping, as that exits just fine, this is the worker process not exiting. All `InternalRunnables` are being notified to interrupt and shut down, I still haven't root-caused what's preventing this process from tearing down, it still looks like one of the threads isn't successfully being brought down.

**Comment by muffins** [comment]
This should be resolved in #5421.
