### ISSUE TITLE
Failure to build on macOS

### ISSUE THREAD

**Issue by fxcoudert** [facebook/osquery#5349]
# Bug report

### What operating system and version are you using?

macOS, all versions from 10.12 to 10.14
System compiler is Apple clang

### What version of osquery are you using?

Trying to build osquery 3.3.2

### What steps did you take to reproduce the issue?

```
cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/osquery/3.3.2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -Daws-cpp-sdk-core_library:FILEPATH=/private/tmp/osquery-20190112-81242-1gcek9k/osquery-3.3.2/brew_vendor/aws-sdk-cpp/lib/libaws-cpp-sdk-core.a -Daws-cpp-sdk-firehose_library:FILEPATH=/private/tmp/osquery-20190112-81242-1gcek9k/osquery-3.3.2/brew_vendor/aws-sdk-cpp/lib/libaws-cpp-sdk-firehose.a -Daws-cpp-sdk-kinesis_library:FILEPATH=/private/tmp/osquery-20190112-81242-1gcek9k/osquery-3.3.2/brew_vendor/aws-sdk-cpp/lib/libaws-cpp-sdk-kinesis.a -Daws-cpp-sdk-sts_library:FILEPATH=/private/tmp/osquery-20190112-81242-1gcek9k/osquery-3.3.2/brew_vendor/aws-sdk-cpp/lib/libaws-cpp-sdk-sts.a -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/libxml2 -I/private/tmp/osquery-20190112-81242-1gcek9k/osquery-3.3.2/brew_vendor/aws-sdk-cpp/include
```

### What did you expect to see?

Successful build.

### What did you see instead?

```
In file included from /tmp/osquery-20190112-81242-1gcek9k/osquery-3.3.2/osquery/utils/aws_util.cpp:37:
/tmp/osquery-20190112-81242-1gcek9k/osquery-3.3.2/osquery/utils/aws_util.h:78:13: error: only virtual member functions can be marked 'override'
      const override;
            ^~~~~~~~
```

**Comment by packetzero** [comment]
Did you happen to do an update on an existing build (e.g. v2.11.2) in the same directory?  If so, the AWS sdk may differ from your previous version, as well as the CMakeLists files.  In this case, you should make clean, make deps.  To check aws sdk used in standard 3.3.1 build (aws sdk v1.4.55 expected):
```
/usr/local/osquery/bin/brew info aws-sdk-cpp
```

**Comment by scpeters** [comment]
It looks like we had updated `aws-sdk-cpp` to 1.4.45 in https://github.com/Homebrew/homebrew-core/pull/35941, which gave us the same error, but it build successfully in https://github.com/Homebrew/homebrew-core/pull/37556 when using 1.4.55.

I think this can now be closed.

**Comment by fmanco** [comment]
@scpeters thanks. closing.
