### ISSUE TITLE
Document existing event publishers

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#552]
Similarly to how we document table APIs, we should document even publishers and their capabilities.

**Comment by theopolis** [comment]
I'd like some suggestions/help on how to scale the docs (essentially specs) for publishers. #551 would benefit from a spec-style definition for each publisher subscription context and event context. Both of the context structs are highly flexible and often contain the raw const pointers from the eventing OS API.

**Comment by marpaia** [comment]
perhaps we can use doxygen to pull out documentation from the code and render that into html for the website?

**Comment by marpaia** [comment]
Added a bullet to #972, closing this for now.
