### ISSUE TITLE
Build fails on ubuntu 18.04 on link stage: undefined reference to symbol 'pthread_setname_np@@GLIBC_2.12'

### ISSUE THREAD

**Issue by mogrein** [facebook/osquery#5536]
# Bug report
### What operating system and version are you using?
Ubuntu 18.04 clean installation

### What version of osquery are you using?
https://github.com/facebook/osquery/commit/45c0b3d636e96f622380e99267c67195993587a3
Experimental branch

### What steps did you take to reproduce the issue?
1. Create new ubuntu 18.04 installation
2. Follow instructions from BUILD.md, aside from using buck v2019.01.10 instead of buck 2018.**
3. Try to build debug version of binary:
`buck build @mode/linux-x86_64/debug //osquery:osqueryd -v 3`

### What did you expect to see?
Build succeeds.

### What did you see instead?
Link stage fails with the following error:
```
(cd /path/to/osquery && TMPDIR=/path/to/osquery/buck-out/debug/bin/osquery/osqueryd#binary /usr/bin/clang++ @/path/to/osquery/buck-out/debug/bin/osquery/osqueryd#binary/linker.argsfile)

/usr/bin/ld: buck-out/debug/gen/osquery/core/core#linux-x86_64,static/libcore.a(system.cpp.o): undefined reference to symbol 'pthread_setname_np@@GLIBC_2.12'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I've watched `/path/to/osquery/buck-out/debug/bin/osquery/osqueryd#binary/linker.argsfile` and haven't found `-pthread` flag there. Adding `-pthread` flag resolves the issue.

[linker.argsfile.txt](https://github.com/facebook/osquery/files/3004693/linker.argsfile.txt)

**Comment by theopolis** [comment]
I think I can help. The issue looks like a linking dependency problem.

**Comment by theopolis** [comment]
@mogrein, ping me if this is still broken for you on `experimental`.

**Comment by mogrein** [comment]
Thank you, @theopolis. With your fix issue is resolved.
