### ISSUE TITLE
ClamAV Related Queries

### ISSUE THREAD

**Issue by tbhaxor** [facebook/osquery#5581]
# Feature request

### What new feature do you want?
Adding queries for clamav antivirus
1. get config
    1. clamd.conf
     2. freshclam.conf
2. scan file/dir using

### How is this new feature useful?
This could provide high level interface to sysadmins and other soc providers to scan file / dir

### How can this be implemented?

_for linux_

1. reading and parsing .conf file
      1. /etc/clamav/clamd.conf
      2. /etc/clamav/freshclam.conf
2. scan file/dir using `/usr/lib/libclamav.so`

**Comment by tbhaxor** [comment]
Closing because no reply

**Comment by zshehri** [comment]
This might be relevant
https://github.com/puffyCid/clamav-osquery

**Comment by theopolis** [comment]
@zshehri and @tbhaxor can you try:
```sql
select * from augeas where path = '/etc/clamav/clamd.conf';
```
