### ISSUE TITLE
Update deployment page on wiki & cached thrift/rocksdb/boost dylib dependencies

### ISSUE THREAD

**Issue by eastebry** [facebook/osquery#573]
After 51425c89, this does not appear to be the case anymore:

>make_osx_package.sh uses homebrew to create an exact replica of your installed packages. This ensures osquery has it's specific dependencies bundled (ex: Boost 1.56.0), but also ensures that existing environment/system dependencies aren't clobbered.

Doesn't look like these libraries are rolled into the package anymore, so it won't work right out of the box.

**Comment by theopolis** [comment]
Correct, `make_osx_package.sh` should be much simpler now. And the documentation will reflect that shortly. 

Those dependent libraries are linked statically so the binaries should work on systems without having to lay down a brew install at all.

**Comment by theopolis** [comment]
@eastebry does your dependent linking look different, or does your system not include the libraries below?

```
[reed@reed-mbp] ~/git/github/osquery(branch:master) » otool -L ./build/darwin/osquery/osqueryi
./build/darwin/osquery/osqueryi:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libssl.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libedit.3.dylib (compatibility version 2.0.0, current version 3.0.0)
	/usr/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.5)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 59.0.0)
	/System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration (compatibility version 1.0.0, current version 596.15.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1056.16.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 855.17.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 55471.14.21)
	/System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by eastebry** [comment]
CMakeCache issue, looks good now. Thanks @theopolis!

**Comment by theopolis** [comment]
If anyone else finds `/usr/local/lib...` in their `otool -L` output then you'll need to `rm ./build/darwin/CMakeCache.txt` or `make clean`. This was an oversight on my part from moving from hard-coded library paths when linking to the variables set by CMake's `find_package` methods.
