### ISSUE TITLE
add glog and gflags to third-party

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#578]
After talking with @theopolis, we decided that in order to solve the unfortunate libunwind/lzma linker issues that we've been having with glog, we're going to add it to third-party so that we can custom compile it. we can then specify some special flags to fix everything up and we should be good to go. this is kind of firmly going to put us in the "we statically link things" category of software, but I think that's the right call.

also, while we're at it, we're going to also throw gflags in third-party because of the gflags namespace instability issues that everyone who uses gflags has.

**Comment by theopolis** [comment]
Not so much worried about gflags given the amount of work required to get glog to build in third-party. Let's table gflags until it becomes a problem (aka more supported OSes decide to ship with a `google::` namespace). Sound good?

**Comment by marpaia** [comment]
Deal!
