### ISSUE TITLE
Use RAII for resource cleanup in virtual tables

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#579]
Currently, `goto` is used liberally for resource cleanup in virtual table functions. We should consider whether this idiom can be replaced by RAII.

See possible cases by searching `goto` in this repo (https://github.com/facebook/osquery/search?utf8=%E2%9C%93&q=goto).

For example, in https://github.com/facebook/osquery/blob/b74ce26a8c5f8c47e76b925a9437ca961a85ad9c/osquery/tables/networking/linux/routes.cpp, can we replace the explicit calls to close `socket_fd` and free `netlink_buffer` with the use of `std::unique_ptr`?

    std::unique_ptr<struct nlmsghdr> netlink_msg(new struct nlmsghdr);
    std::unique_ptr<int, decltype(close)*> socket_fd(socket(PF_NETLINK, SOCK_DGRAM, NETLINK_ROUTE), close);

See http://www.codeproject.com/Articles/820931/Using-std-unique-ptr-RAII-with-malloc-and-free for discussion of using custom deleters with unique_ptr.

**Comment by theopolis** [comment]
:+1:

**Comment by marpaia** [comment]
:fireworks: :fireworks: :fireworks:

**Comment by theopolis** [comment]
I don't think the netlink code needs an RAII wrapper/change. But we could "up for grabs"/"wishlist" the change and call this note complete?

**Comment by marpaia** [comment]
We could change the name of this issue as well?

**Comment by theopolis** [comment]
I'd vote to close this and open an issue for each wishlisted change and we can treat them like bootcamp tasks.
