### ISSUE TITLE
Missing libraries from latest build

### ISSUE THREAD

**Issue by maus-** [facebook/osquery#582]
Centos 6.0+ 

When installing osquery-1.2.2_112_gdbb7050-1.x86_64 it fails due to unmet dependencies 

output of running a yum localinstall. 
Resolving Dependencies
--> Running transaction check
---> Package osquery.x86_64 0:1.2.2-1 will be updated
---> Package osquery.x86_64 0:1.2.2_112_gdbb7050-1 will be an update
--> Processing Dependency: libglog.so.0()(64bit) for package: osquery-1.2.2_112_gdbb7050-1.x86_64
--> Processing Dependency: libthrift-0.9.1.so()(64bit) for package: osquery-1.2.2_112_gdbb7050-1.x86_64
--> Finished Dependency Resolution
Error: Package: osquery-1.2.2_112_gdbb7050-1.x86_64 (/osquery-1.2.2-112-gdbb7050-Linux)
           Requires: libthrift-0.9.1.so()(64bit)
Error: Package: osquery-1.2.2_112_gdbb7050-1.x86_64 (/osquery-1.2.2-112-gdbb7050-Linux)
           Requires: libglog.so.0()(64bit)

Looks like its missing a library now? The last version I have working is version 1.2.2

**Comment by marpaia** [comment]
Hey @theopolis, this seems to be related to the new `find_package` stuff. Any guidance on that?

**Comment by theopolis** [comment]
I have no idea what's going on here. O.o, does someone maintain a yum repo with builds of osquery from GitHub?

Can you point me to the RPM? Or yum repo/source? We don't maintain an official repo or RPM build yet. :)

**Comment by marpaia** [comment]
Oh, is this you installing an RPM created with `make package`, @maus-? 

I thought this was during build.

**Comment by maus-** [comment]
You can trivially build out a RPM for centos using cmake28 with the following steps.

1.) Build osquery as usual.
    make clean; make deps; make; make package

2.) Install rpm-build for cmake to use 
     yum install -y rpm-build

3.) Drop into the centos build directory and have cmake28 build your RPM. It'll use a generic generated spec.
    cd /vagrant/build/centos/ 
    cmake28 -G RPM

4.) Profit.

**Comment by marpaia** [comment]
can you run `rpm -qpiR <filename>` on both the RPM that works for you (1.2.2) and the RPM that doesn't (master)?

**Comment by maus-** [comment]
To further demonstrate the issue at hand I've updated my osquery-chef git repo to have both packages. 
feel free to clone and run a vagrant up you should see everything working as it should.. (Excluding the previous bug where config options are not being passed). 

https://github.com/maus-/osquery-cookbook

However if you modify this line https://github.com/maus-/osquery-cookbook/blob/master/chef/cookbooks/osquery/recipes/default.rb#L12  so it installs osquery-1.2.2-112-gdbb7050-Linux it'll fail due to unmet dependencies.


@marpaia as per your request 
Running 1.2.2: https://gist.github.com/maus-/d09efc7ad266988bc62c
Running 1.2.2_112_gdbb7050 https://gist.github.com/maus-/65369061eddac43b08b3

**Comment by theopolis** [comment]
Awesome, I'm just now working through `make package` support. CentOS 6.6 is next on my list to work through dependent library minimization and proper package dependency descriptions. So that generated RPM will include the correct package dependency versions. 

I'm not sure off the top of my head what would have changed with the linking that would require thrift and glog other than using the CMake `find_package` variables AND them preferring linking dynamically. Perhaps CPack is smart enough to use cache variables set in the included find CMake module includes. Worst case we'll add a line to provision.sh to install/link the static version of thrift on your build host and build glog/gflags locally: #578.

**Comment by maus-** [comment]
Looks like this has been resolved in the latest build.
