### ISSUE TITLE
make format only formats staged files

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#586]
I'm guessing this is intended, but it's a little confusing. If I make a couple commits then run `make format`, nothing will happen because there are no files staged.

The [wiki](https://github.com/facebook/osquery/wiki/formatting-your-code) says
> After you've written some code, execute make format from the root of the repository. This automatically runs clang-format on all C/C++/Objective-C source code.

which led me to believe that *all* files would be formatted.

I think we should either update the docs to indicate the actual behavior, or update the behavior to format all files.

**Comment by theopolis** [comment]
Yes, let's update the docs. Having clang-format only run on staged files is ideal. You can make sure temporary source/text is not formatted (sometimes I leave targets of redirects to grep through in the root dir, I wouldn't want them formatted). And more importantly you can `git diff` easily following the `make format` to see what clang-format changed-- as the changes from the format are unstaged. Sometimes there are unwanted changes. ;)

**Comment by zwass** [comment]
I updated the docs to make this clear.
