### ISSUE TITLE
Replace uses of sprintf/strcpy with snprintf/strncpy for memory safety

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#588]
There are three instances of the use of `sprintf`, and these should be replaced by `snprintf` to ensure we can't overflow the target buffers.

**Comment by jedi22** [comment]
These are all removed now

**Comment by jedi22** [comment]
There is one instance of strcpy at utils.cpp at line 115

**Comment by zwass** [comment]
I think this is now sorted with #678
