### ISSUE TITLE
isolate build VMs more effectively

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#591]
Yesterday, one build failed which seems to have caused failures for other, unrelated pull requests. This isn't good for obvious reasons. Let's isolate build roots better.

**Comment by javuto** [comment]
Looking at it right now

**Comment by theopolis** [comment]
Isolation in this case means (A) cleaning up after a failed build? Or (B) doing a VM-resume from a known-good/known-recent `make deps`?

**Comment by marpaia** [comment]
I would prefer B personally.

**Comment by javuto** [comment]
This is, IMHO, mitigated by having a clean snapshot for each of the build VMs. If something goes wrong, we can go back to the installation status and start from there. The process is manual, now, a different story would be to automate it

**Comment by marpaia** [comment]
i love having a clean snapshot for each build. is there a way to have jenkins revert/provision VMs on build?
