### ISSUE TITLE
iokit_hid.cpp:51 - Cannot open IOKit HID Manager

### ISSUE THREAD

**Issue by mimeframe** [facebook/osquery#592]
Saw this errors on 15+ hosts in the past 24 hours.

Samples:

```
Log file created at: 2015/01/09 14:33:53
Running on machine: foo-bar
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0109 14:33:53.987787 81768448 iokit_hid.cpp:51] Cannot open IOKit HID Manager
```

```
Log file created at: 2015/01/09 10:48:40
Running on machine: dead-beef
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0109 10:48:40.885144 156725248 iokit_hid.cpp:51] Cannot open IOKit HID Manager
```

I also experienced this when running osqueryi on a remote host:

```
cafe-babe:~ admin$ osqueryi
-~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
osquery - being built, with love, at Facebook
-~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
osquery> E0109 12:54:28.579792 183963648 iokit_hid.cpp:51] Cannot open IOKit HID Manager
```

**Comment by theopolis** [comment]
The error is generated from: https://github.com/facebook/osquery/blob/master/osquery/events/darwin/iokit_hid.cpp#L57

The IOKit API call: `IOHIDManagerOpen` is returning a non-success error: https://developer.apple.com/library/mac/documentation/DeviceDrivers/Conceptual/HID/new_api_10_5/tn2187.html

**Comment by theopolis** [comment]
We should emit a less-scary warning/notice. And the text should indicate that everything is fine, but IOKit events will be disabled for the run of the daemon or shell.

**Comment by mimeframe** [comment]
I dig your offline comment of referencing a TN URL so there can be additional details for this warning/error and future warning/errors. What are IOKit events, what things can you expect to not see, how can this be fixed or why does it happen, ....

**Comment by theopolis** [comment]
I added an example "callout" to an issue, which somewhat binds the project to Github issues for bug/note/decision tracking. See https://github.com/facebook/osquery/blob/master/CMake/FindGlog.cmake#L16

**Comment by theopolis** [comment]
See: #617 for the reference, or technical note that is attached to the log item, which is now a warning (https://github.com/facebook/osquery/pull/618). We treat this as a warning as it WILL affect the iokit-based event subscribers but has no impact on osquery core.
