### ISSUE TITLE
[RFC] osquery logging for table-specific OS API return codes

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#593]
A table implementation using an OS API with a non-success return should NOT emit an error. Errors are reserved for recoverable to mildly recoverable osquery issues. 

Warnings should be used for semi- catastrophic table implementation errors such as those tables used as conduits for others (processes/users) and event publishers. 

Notices should be used for OS API failures that may affect data output. 

Verbosity logs should be used for expected variances/issues when generating sporadic/unpredictable data (e.g., parsing liberally-enforced plist attributes).

Debug logs should be used for dragon fighting and similar feats of strength.

**Comment by theopolis** [comment]
This is also a call to action to update our table code to NOT produce scary looking errors/warnings. These logging targets are used for collecting performance statistics and improving our deployments.

**Comment by marpaia** [comment]
I'm assuming this is an attempt at systemically solving #592? I agree. "Error" means something different in our codebase than our users expect.

**Comment by mimeframe** [comment]
![Dragon fighting]
(http://i.imgur.com/3UDNhfp.jpg)

**Comment by theopolis** [comment]
What do you think of:

1. We make a Github issues tag: api_note or tech_note, or TN, or reference
2. We add a set of additional logging macros to `logger.h` like:
  * `TLOG << "This is an informational one-off error/note/warning log from a table"`
  * `CLOG(TYPE) << "This is a log from a core component"` TYPE = {INFO, WARNING, ERROR}
  * `RLOG(#) << "This is a log that has a reference on GitHub issues"` # = reference number

Then we can force TLOG/RLOG as verbose.
