### ISSUE TITLE
Startup Items virtual table

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#6]
Let's create a virtual table which displays all of the items that will be executed when a host boots.

For OS X, there's a neat tool which already does this: https://github.com/synack/knockknock. We should port it's functionality to C++ and get this in there.

**Comment by 0xdabbad00** [comment]
Is anything still happening with this?  Seems like only a subset of KnockKnock was implemented.

**Comment by theopolis** [comment]
Hey @0xdabbad00, I never looked at KnocKnock's implementation but are you interested in a specific source of data? The paths @marpaia listed above are included in:

- `/Library/StartupItems/` => `select * from startup_items`
- `/System/Library/StartupItems/` same
- `/Library/ScriptingAdditions/` => missing
- `/Library/Internet Plug-Ins/` => `select * from browser_plugins`
- `/Applications/Mail.app/Contents/PlugIns/` => missing
- `/var/root/` not sure about context here
- `/Library/Scripts/Folder Action Scripts` => missing

I think startup items are well covered. We might benefit from a scripting addons table and a mail-app plugins table. There are precedent tables for chrome/firefox/safari and opera specifically that list their respective "extensions" types.
