### ISSUE TITLE
Disable/hide/alert for tables that depend on kernel modules

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#603]
Right now we have kernel_integrity that requires a kernel module to work. Otherwise the sysfs paths are not found. 

It makes sense to compile these table implementations into the daemon/shell but we should consider the UX of having an empty table OR the table showing up at all. 

Thoughts?

**Comment by marpaia** [comment]
Could we have a conditional in [`osquery::tables:: attachVirtualTables `](https://github.com/facebook/osquery/blob/b74ce26a8c5f8c47e76b925a9437ca961a85ad9c/osquery/core/virtual_table.cpp#L76-L84) which only loads the table if the kernel module has been detected?

**Comment by theopolis** [comment]
What about something in the .spec that identifies the requirement for the kernel module. Then we can generate meaningful API documentation and generate a flag/code to make that check. 

Later we can poll for the module load, flip a bit, and register the tables.

**Comment by marpaia** [comment]
the would be super neat!

**Comment by marpaia** [comment]
closing this as it still has the RFC tag and we'll still get alerts if anyone comments
