### ISSUE TITLE
[master task] language bindings

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#623]
This issue tracks requested/planned additions to supported language bindings for osquery. If you would like to suggest/discuss a new language binding please comment on this issue. If you would like to implement one of the features or need a focused discussion please open a separate issue dedicated to that feature.

Bindings that have been requested before:

* Python: https://github.com/osquery/osquery-python
* PHP PDO driver
* node.js

Existing bindings:

* squery (PHP): http://squery.thephpleague.com/

**Comment by eg0r** [comment]
There is some progress in the library for Python?

**Comment by theopolis** [comment]
Hey @eg0r, I just updated the task to add the in-development link to the Python bindings (https://github.com/osquery/osquery-python). Those are definitely beta, and could use some recommendations and help.

**Comment by eg0r** [comment]
@theopolis It only supports the creation of extensions, without executing queries? (like https://github.com/thepauleh/osquery-python)

**Comment by marpaia** [comment]
@eg0r 

```
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import osquery
>>> client = osquery.ExtensionClient(path="/Users/marpaia/.osquery/shell.em")
>>> client.open()
>>> client.extension_client().query("select * from time")
ExtensionResponse(status=ExtensionStatus(message='OK', code=0, uuid=0), response=[{'seconds': '16', 'minutes': '9', 'hour': '15'}])
>>>
```

**Comment by eg0r** [comment]
Thanks, @marpaia

**Comment by marpaia** [comment]
I'm going to close this out. We're going to maintain the python bindings as a reference implementation for working with the thrift API, but further language bindings should be left to community development.
