### ISSUE TITLE
Hash Table Query Failures

### ISSUE THREAD

**Issue by jedi22** [facebook/osquery#630]
```sql
select * from hash where path="/bin/bash";
```

Works but not after

```sql
select * from hash where directory="/bin/";
```

The inverse is also true

**Comment by marpaia** [comment]
@theopolis, do you think this is a bug in QueryContext, or in SQLite itself?

**Comment by theopolis** [comment]
Good find, I can definitely repro the issue. Looking into it, I'd guess it's (a) some stacking of constraints memory during xBestIndex calls, or (b) unknown persistence of the QueryContext struct between table generations = stacking of constraints.
