### ISSUE TITLE
improve documentation - "using osqueryi"

### ISSUE THREAD

**Issue by n1tr0g** [facebook/osquery#654]
Hey,

first of all nice job with the tool. I will install it as a standard package on our nodes :) 

Anyway I found the command PRAGMA table_info(TABLE_NAME); really helpful, so I think you should mention it in the wiki page (https://github.com/facebook/osquery/wiki/using-osqueryi).

cheers

**Comment by theopolis** [comment]
Thanks @n1tr0g, will do!

**Comment by marpaia** [comment]
Thanks, @n1tr0g! Happy to see you're enjoying osquery. If there's anything we can do to help out with your internal deployment, let us know!
