### ISSUE TITLE
clean up test_util.h/test_util.cpp

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#658]
test_util is an artifact of when the osquery codebase was small enough that having a ton of test utilities in a single file made sense. We've outgrown this now, so let's clean it up.

**Comment by theopolis** [comment]
This was cleaned a bit as part of the SDK reorganization. The changes mostly includes removing SDK-included dependencies and SQL-implementation testing since the SQL-implementation (SQLite) is not shipped with the osquery SDK.
