### ISSUE TITLE
strict alias compiler error in events

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#729]
```
osquery/events.h: In instantiation of 'static osquery::Status osquery::EventFactory::registerEventSubscriber(std::shared_ptr<_Tp1>) [with T = osquery::Plugin]':
osquery/events/events.cpp:581:71:   required from here
osquery/events.h:428:62: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
osquery/events.h:428:62: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
```

**Comment by theopolis** [comment]
I'm working on this! https://github.com/facebook/osquery/pull/737

**Comment by marpaia** [comment]
Like a baus!

**Comment by theopolis** [comment]
I'm testing with `-Werror=strict-aliasing` locally and not seeing this warn or error. What clang/llvm version is throwing this?

**Comment by marpaia** [comment]
@theopolis this was in fbcode, which always seem to throw compiler warnings/errors that aren't thrown in our setup. Not entirely sure what flags/compilers/etc combination caused it off the dome.

**Comment by theopolis** [comment]
I'm inclined to completely agree with what it's warning on ;) But I'd love to know how we surface those warnings in our build. Maybe we have a "make extreme_deps" that pulls in bleeding edge compilers/CMake/etc?

**Comment by marpaia** [comment]
Jim Meyering has been doing a lot of really great work on this internally. Perhaps we can try to enlist his thoughts on what we should be doing better to surface bugs like this in our own build?
