### ISSUE TITLE
add launchd startup items to the startup_items table

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#749]
Right now, startup_items returns programs that will start when your OS X machine boots. However, it doesn't include data from launchd:

```sql
SELECT
  name,
  program || program_arguments AS executable
FROM launchd
WHERE
  (run_at_load = 'true')
AND
  (program != '' OR program_arguments != '');
```

We should add this data to the startup_items table.

**Comment by theopolis** [comment]
Revisiting this, startup_items is an OS X concept that's separate from their daemonization/run level organization. We'll have a sister table on Linux that lists the details of sysv/init.d BUT we could also include startup_items as a catch for GTK/Unity/KDE-startup items.

On the other hand we do have tables that are effectively subsets of others, like listening ports. So there's precedent for startup_items to contain all of the traditional startup_items + launchd. However, in this case, parsing launchd + startup_items will incur a significant performance hit. Finally, consider the launchd/launchagents that run at login time. Those are more closely aligned with what startup_items reports. Is it worth separating them more completely than a column?

What was the driver for having startup_items be a superset of launchd?

**Comment by marpaia** [comment]
I think mostly because OS X has so many disparate places that "startup items" can be, we wanted to aggregate a unified interface to them.

**Comment by marpaia** [comment]
cc @mago0

**Comment by theopolis** [comment]
After giving it another think I'm for keeping these separate from a table implementation perspective. We can publish a query which selects from both into an aggregate list.
