### ISSUE TITLE
Add Custom Extension Tables to Fleet UI

### ISSUE THREAD

**Issue by theterribletrivium** [facebook/osquery#7580]
# Feature request

### What new feature do you want?

Currently, when viewing queries that have custom tables in Fleet, it shows as broken, with a Platform of --- and a syntax error when you view the detailed query view. Running the query through the UI works, it just shows a syntax error. I would like a way to add these custom tables so that Fleet will identify that these tables exist.

### How is this new feature useful?

Right now, any query with a custom table will show as a "syntax error" which prevents you from knowing if your syntax is truly correct or not.

### How can this be implemented?

Unsure, perhaps a comma separated list that could be provided via UI or API? Not really sure.

**Comment by mike-myers-tob** [comment]
Hi @theterribletrivium , this is a request related to the FleetDM user interface, not the osquery agent, so I would encourage you to re-open it at https://github.com/fleetdm/fleet
