### ISSUE TITLE
Add osquery docs to readthedocs.org

### ISSUE THREAD

**Issue by zwass** [facebook/osquery#760]
Documentation on https://readthedocs.org/ is super easy to read, and it would be nice for anyone interested in working on osquery code.

**Comment by jedi22** [comment]
@theopolis did this

**Comment by theopolis** [comment]
Implementation: https://github.com/facebook/osquery/commit/2df9a6558e43365adc97136ded2f6dcf36fef6ac
Documentation is built from the translated github wiki pages that now live in [/docs/wiki](https://github.com/facebook/osquery/tree/master/docs/wiki)
Read the docs uses mkdocs (set in the admin configuration) and reads our [mkdocs.yml](https://github.com/facebook/osquery/blob/master/mkdocs.yml)
Read the docs: https://osquery.readthedocs.org/
