### ISSUE TITLE
"Certificate verify failed" when sending to AWS Firehose without TLS or any other certificate related config.

### ISSUE THREAD

**Issue by rjromay** [facebook/osquery#7632]
# Bug report

### What operating system and version are you using?

admin@xxxxxxxxxxx:~$ osqueryi --line "SELECT version, build, platform FROM os_version;"
 version = 10 (buster)
   build =
platform = debian

Running on AWS EC2

### What version of osquery are you using?

admin@xxxxxxxxxxx:~$ osqueryi --line "SELECT version from osquery_info;"
version = 5.3.0

### What steps did you take to reproduce the issue?

After a fresh installation, I configured an aws firehose logger. No aws config file, profile, keys... as my intention is that osquery uses the machine Role, which has permissions to perform put_record_batch on the configured firehose (tested to be working from the same machine with a simple python script).

Config:
{
  "options": {
    "logger_plugin": "filesystem,aws_firehose",
    "aws_firehose_stream": "osquery",
    "aws_region": "eu-west-1",
    "aws_debug": true,
    "verbose": "true",
    "enable_syslog": "true",
    "audit_allow_sockets": "true"
  },
  "schedule": {
    "crontab": {
      "query": "SELECT * FROM crontab;",
      "interval": 300
    },
    "syslog": {
      "query": "SELECT * FROM syslog_events;",
      "interval": 300
    }
  },
  "decorators": {
    "load": [
      "select instance_id, local_ipv4, account_id, iam_arn from ec2_instance_metadata;"
    ]
  }
}

### What did you expect to see?

Data is received in the firehose.

### What did you see instead?

I'm getting the following errors and no data is sent to the firehose:

Jun 16 09:39:36  osqueryd[2455]: I0616 09:39:36.560292  2579 scheduler.cpp:185] Found results for query: crontab
Jun 16 09:39:39  osqueryd[2455]: E0616 09:39:39.581405  2576 aws_util.cpp:223] Exception making HTTP POST request to URL (https://firehose.eu-west-1.amazonaws.com): certificate verify failed
Jun 16 09:39:39  osqueryd[2455]: I0616 09:39:39.581598  2576 aws_log_forwarder.h:219] aws_firehose: Successfully sent 4 out of 4 log records

Tested the connectivity and the server certificate chain to be ok using:
openssl s_client -showcerts -verify 5 -connect firehose.eu-west-1.amazonaws.com:443

Using tcpdump I can see how, after the server presents its certificate chain, the client gives an error of Unknown CA.

The behavior seems to be similar to the issue #7449 but this was fixed in #7450 and I'm not using tls_server_certs anyway.

Another cosmetic issue is the misleading trace of "Successfully sent x records" that seems to be printed regardless of the result of the send operation.

Thanks for your support.

**Comment by rjromay** [comment]
Hi,

I've just created a clean Debian 11 instance on EC2 to build osquery from sources. I've tested first the behavior in this OS version installing osquery from .deb package and using the same configuration file. I've got the same behavior.

Best regards,
Raúl.

**Comment by rjromay** [comment]
Update:

Fresh build of osquery: same behavior.
Added CA cert to /opt/osquery/share/osquery/certs/certs.pem: same behavior
Added CA cert to /etc/ssl/certs/ca-certificates.crt: same behavior

".all certificates" shows all the certificates in /etc/ssl/certs/ca-certificates.crt

I've discovered that, while ".all ec2_instance_metadata" works fine, ".all ec2_instance_tags" exhibits the same behavior, "certificate verify error".

Having a look to the source code, issue #7450 , the main change is calling getOptions instead of getInternalOptions from aws_util.cpp. 

If I revert just this single line to call again getInternalOptions, it works, and i.e. ".all ec2_instance_tags" return values. Of course, this is introducing again the bug #7449.

The implementation of getOptions returns a default Options object, but it is not setting openssl_certificate as it is done in getInternalOptions:

options.openssl_certificate(server_certificate_file_);

Now, if we revert aws_util.cpp to call getOptions with this line added in getOptions(), it works again. This is still unsafe, as it will create problems with flag tls_server_certs. It should be set to OSQUERY_CERTS_HOME as defined in default_paths.h and taking into account platform differences.

This means that openssl has no default path for looking for CA certs if this option is not set. I would expect this to be /etc/ssl/certs/ca-certificates in linux. It was not so clear to me after reading the documentation that everything relied on a hardcoded path to /opt/osquery/share/osquery/certs/certs.pem

Best regards,
Raúl.

**Comment by yonnym** [comment]
I think the solution would be to rollback [7450](https://github.com/osquery/osquery/pull/7450) and require users to supply all CAs.

**Comment by yonnym** [comment]
@Smjert you are correct, the change did not make it work - mea culpa, I should have tested it sooner.

**Comment by Smjert** [comment]
> @Smjert you are correct, the change did not make it work - mea culpa, I should have tested it sooner.

Ok that clarifies it, thanks!

I'll revert the PR. I think it's still worth to look more into this, because I've seen the AWS SDK searching for the system certificates and I'm currently not 100% sure what it's doing with them.
It also make sense evaluating adding more flags to control certs for specific endpoints, or at least have one for the osquery internal use, and another set for external things (like AWS, Azure, YCloud and so on).
