### ISSUE TITLE
osqueryi json output sometimes includes thrift text

### ISSUE THREAD

**Issue by jamesmulcahy** [facebook/osquery#768]
Occasionally, when I run osqueryi --json, I get Thrift debug output prepended to the JSON.  This breaks my JSON parsing, which is a bit of a pain.

Command was:

/path/to/bin/osqueryi --json=true "SELECT remote_address from process_open_sockets WHERE remote_port='50010' AND pid='42487'

Output was:

-- BEGIN -- 
Thrift: Tue Feb 17 15:16:08 2015 TServerSocket::listen() PATH /tmp/osquery/shell.em
[

]
-- END --

**Comment by theopolis** [comment]
Hey @jamesmulcahy, definitely a problem. I'm looking into how to silence that thrift-write to stdout.

**Comment by jamesmulcahy** [comment]
Sorry, my bad; looks like there was something lower in the stack which was aggregating stderr into stdout.  This output is actually on stderr; which isn't such a problem, but is still a little on the noisy side

**Comment by theopolis** [comment]
Ok cool, that makes a lot more sense. It looks like this it emitted to stderr when not `-DNDEBUG`.

**Comment by theopolis** [comment]
The next release will be built without the lines to stderr: https://github.com/facebook/osquery/blob/master/CMakeLists.txt#L69!
