### ISSUE TITLE
Installing from Homebrew doesn't create /var/osquery

### ISSUE THREAD

**Issue by lyricsboy** [facebook/osquery#785]
With a fresh install of v1.4.1 on OS X Yosemite via Homebrew, osqueryd fails to start (whether directly or via launchd) due to:

```
E0221 10:31:33.792289 2066727680 init.cpp:174] osqueryd initialize failed: Could not create file: /var/osquery/osqueryd.pidfile
```

Is it possible to `mkdir /var/osquery` somewhere along the way?

**Comment by marpaia** [comment]
This stems from `make install` not setting up the filesystem with temp files and such.

**Comment by theopolis** [comment]
We can have the daemon try to make the intermediate folders? The general consensus around this sort of stuff is 50/50, some believe a hard fail with default configurations with non-sane directory paths is OK, some believe they should be silently created with a hard fail on permissions errors, others say a --create_dirs erases all doubt.

I vote for silently creating, and hard fail on permissions error.

**Comment by marpaia** [comment]
Not super convicted on this, but I don't think that the binary should create directories like this. I'm all for adding it to the brew package.

**Comment by marpaia** [comment]
Actually, we can't create `/var/osquery` from the homebrew install, we're not allowed to touch anything outside of `/usr/local/Cellar`. Better known as `$PREFIX`.

**Comment by lyricsboy** [comment]
I think at a minimum you could include instructions for creating that in the "caveats" section that shows up post-install.

**Comment by marpaia** [comment]
I see the options as follows:

- add it to the caveats section of the brew install, mark this as #wontfix
- add a mkdir for `/var/osquery` to the codebase
- move the pidfile to a location that always exists

Thoughts? Vote?

**Comment by lyricsboy** [comment]
Take a look at what the [redis formula](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/redis.rb) is doing. It has a pidfile and logs and stuff.

**Comment by marpaia** [comment]
Yeah, they move their pidfile and config out of `/var/run` and into `/usr/localCellar`.

**Comment by marpaia** [comment]
They seem to define their pidfile path as somewhere else in the config. You can also do that as well with osqueryd (`--pidfile`) as well as with the config (`--config_path`).

**Comment by marpaia** [comment]
we talked through this internally, we have a "solution" incoming. i'll link the the PR with a further explanation shortly.

**Comment by marpaia** [comment]
diff out

**Comment by marpaia** [comment]
closing here in favor of tracking on #794
