### ISSUE TITLE
more OSX Keychain(s) items

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#786]
Hey there, followed along loosely with @marpaia's talk at macbrained, hope this is a good place to discuss a possible feature request. I see ca_certs as a table, but not other keychain/password items. My use case is between the client certs we use with puppet/munki, the issue I'm having with 802.1x password caching (and YoYo's crappy Wi-Fi handling in general), and our websense filtering, keychain-specific auditing is becoming more of a priority. Is the schema for these other classes of items already there and I'm missing it?

**Comment by theopolis** [comment]
Hey @arubdesu, you're not missing anything. ;)

Right now the only Keychain items/information in osquery are items from system Keychains matching x509 certificates with the CA: true basic constraint. There are two considerations for that limitation, (1) the way we build osquery makes requesting user-Keychain information unreliable; (2) there are plenty of privacy concerns.

I'd be happy to look into exposing more than just "CA: true" for certificates in `/System/Library/Keychains` and `/Library/Keychains`, that'll get you leaf/entity 802.1X certs. Network passwords are also saved in those keychains, although those are available to the whole system, the name's/dates are sensitive. The contents, encrypted keys, are protected by the keychain ACLs so at best we'd be able to list the sensitive metadata.

Thoughts?

**Comment by arubdesu** [comment]
Personally I'm primarily concerned with system keychain items, so interacting with each user per machine (I need to take into account shared usage models, so there could potentially be a bunch) and privacy becomes at least somewhat less of an issue or priority in the short term. I can't say that I've done extensive work with ACLs/etc besides programmatically shoving certs in if not found, but the examples I mentioned will require monitoring that could potentially be costly if left to my own devices 😅

**Comment by theopolis** [comment]
@arubdesu, I renamed ca_certs to certificates and included all x509 items. I checked against some example 802.1X entity/left certs added to OS X using default Keychain APIs and they are placed into the user-searchable system Keychain (opposed to the system keychain's that are not automatically added to user search paths).

`certificates` makes sense here since I can pair it with the PEM bundle discovery/parsing on Linux. I can add an additional Keychain table that takes a path as input and parses every item within. So a `select * from keychain where path = '/Library/Keychains/System.keychain'` would give system-saved/available passwords. Sound good?

**Comment by arubdesu** [comment]
Sounds great! In light of the komodia kerfuffle my boss became quite interested in this, although I know 'keychain' is a heading for a bunch of stuff and there be dragons along the way - not sure where a full listing of root certs would come from with osquery, but I know tehGoog guys have convenience functions for that in [gmacpyutil](https://github.com/google/macops/blob/master/gmacpyutil/gmacpyutil/certs.py).

I built from source and see the new path schema, so that's excellent. I checked the keychainAccess GUI to see if the way our radius 802.1x password's stored is special and it seems it should allow all apps to access it.
The munki.keychain([the code for its handling, fyi](https://github.com/munki/munki/blob/master/code/client/munkilib/keychain.py)) I believe gets recreated on every run to make sure you're using fresh client certs in the event of rotation, but at present it doesn't return with info when I target its path in ```/Library/Managed Installs/Keychains``` at present. It should contain a client cert, private key, and identity pref. I'm not sure if it also does some runtime juggling as root, I'll ping their dev list.
Looking good, thanks much!

**Comment by theopolis** [comment]
Ok! Right now `certificates` does not "act" on a `where path = '/path/to/custom/awesome.keychain` but it should! It should also include a few more default filesystem search paths including `/Library/Managed Installes/Keychains`. That'll satisfy a check for munki's transient cert store, which is a great use case. 

Thanks for the links to the code, give me one more pass at `certificates` features and then I'll add `keychain_items`, eta, sometime this weekend.

**Comment by theopolis** [comment]
Ready to go! Let me know/reopen if there's more keychain/certificate info needed!
