### ISSUE TITLE
browser extension auditing

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#787]
Pardon I see #24 re: browser 'extensions'  got subsumed into #619, I'm currently doing something very naïve with JAMF's [extension attributes](https://gist.github.com/arubdesu/152e6a29b8c9efa583a4) to report on plugin's/add-ons/etc. for all three browsers we deploy/support(sorry, Opera). I only went ahead and wrote what I did because the other security auditing tools I found were either just out of date enough not to support all browsers, or would be impractical to deploy with their dependencies(or I just didn't understand their model well enough(sorry, Yelp)). As with my other request, #786, I'm not sure if you have the schema already and I'm just not seeing it, and pardon if I'm not asking in the right place.
(Y'all don't like mailing lists?) Thanks

**Comment by theopolis** [comment]
@marpaia where we're we with that google group mailing list? We have #osquery on freenode in the mean time. :)

@arubdesu you can *try* to get extensions information with the [preferences](http://osquery.io/docs/tables/#preferences) table if the extension information is kept in a plist. `select * from preferences where path = '/path/to/extensions/plist.plist';`. But that's not sustainable or complete. I can hi-pri the Safari/Chrome/Opera/Firefox/Mail.app extensions and plugins. :+1:

**Comment by arubdesu** [comment]
Thanks for advocating for this, and good call for Mail.app. As my gist currently demonstrates, it's a lot of json that you interact with when dealing with at least the metadata about the extensions themselves, so plists aren't in play much of the time.

**Comment by theopolis** [comment]
Right! I went through your gist, and poked around at the files + what Apple, Google, and Firefox document about how to extend the browsers in various ways. It looks like there's no magic other than scraping folders for known-paths/files and parsing a bit of plist+JSON data.

The diff I just posted should cover most stuff sans Opera. :/ I'll take a look and see what's needed for Opera support first thing tomorrow!

**Comment by theopolis** [comment]
Hey @arubdesu, for Opera, are you installing content/settings/plugins into `/Library/Preferences/Opera Preferences`? It's documented by Opera as the site/system-specific place to manage Opera, but I'm not sure how commonly it's used: http://www.opera.com/docs/operafiles/.

I'm thinking for an `opera_plugins` osquery will scan: /Applications/Opera.app/Contents/PlugIns/, /Library/Internet Plug-Ins, ~/Library/Internet Plug-Ins.

And `opera_extensions` osquery will scan: ~/Library/Application\ Support/com.operasoftware.Opera/Extensions, similar to chrome.

Any suggestions/tips?

**Comment by arubdesu** [comment]
I don't actually support Opera, but perhaps @keeleysam can weigh in? I'll try to find him...

**Comment by theopolis** [comment]
Thanks! I'll try to find some folks who've deployed/managed Opera too, but I'm not hopeful I'll find any :( If we're feeling really enterprising we *should* crack open the bin/source and look for all possible plugin/extension search paths.

**Comment by theopolis** [comment]
I'm still tracking on opera. I was debating adding a category to each table as the list on OS X is getting a bit large. Browsing the tables docs on the homepage is a bit cumbersome too.

I was thinking: application, network, system, hardware. The immediate issue being quite a few tables fall into multiple categories.

Any update on extensions management?

**Comment by theopolis** [comment]
@jedi22 merged support for opera extensions: https://github.com/facebook/osquery/commit/b67ca8598b73a1d8aa5ae7dc0eeac23f72670f6a

- [x] Safari plugins
- [x] Safari extensions
- [x] Chrome extensions
- [x] Firefox addons
- [x] Opera extensions

Anything we forgot/missed?
