### ISSUE TITLE
add signing entity on kernel_extensions on OS X

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#800]
All kernel extensions need to be signed on OS X, we should add the signing entity as a field in the kernel_extensions table.

**Comment by marpaia** [comment]
relevant link from @mag00: https://www.virusbtn.com/virusbulletin/archive/2014/10/vb201410-malware-persistence-MacOSX#id5040662

**Comment by theopolis** [comment]
Kernel extensions should also enumerate the search paths for .kext bundles. I'm thinking:

1. Use APIs to query information about extensions.
2. Do some directory traversal to find all bundles in well-known search paths, then parse the Info plist for metadata (including signatures) and hash the corresponding executable.
3. For each label included in the API return, pair with the label from the Info map from 2.
4. Then you can emit a "on_disk" column, hashes, signatures!

**Comment by theopolis** [comment]
The mach-o signatures for the extension binaries are not easily query-able. It looks like kexd does keep information about the signatures so a notification center call can check revocations. But I can't see how we can access this info from another process. This means we'll have to parse the extension executable (using the Security/static code/signature APIs). Very spendy! 

I propose including a new table macho_signature, and you can join kernel_extensions.path against that table to get various signature data.

**Comment by marpaia** [comment]
I think that, if we can't use kextd to get the signatures without parsing binaries into memory, then we should definitely do this as a joinable `macho_signature` table.

**Comment by wxsBSD** [comment]
I've got some experience with pulling signature blocks out of binaries. I believe they are never loaded into the processes memory space so the only approach would be the time consuming and error prone parsing route. You also have the complication when multiple sub-arches are signed in a single universal binary. None of these are insurmountable but will make for an interesting set of challenges.

**Comment by theopolis** [comment]
To echo @wxsBSD a bit, there's also bundle and bundle resource signatures we *could* support. Looking through the kextd code a bit more, there's also multiple revisions to code signing (like we should expect), and there will be more to come! It'd be best to isolate this parsing/support to it's own joinable table.

Let's close this and add a macho_signatures table to the tables master task.
