### ISSUE TITLE
Cannot open IOKit HID Manager

### ISSUE THREAD

**Issue by grimnight** [facebook/osquery#806]
Using `1.4.2` I keep getting `Cannot open IOKit HID Manager`, I had the same problem with `1.2.2`, I did not get it with `1.3.1`.
Also see [homebrew/35343].

```
~ ❯❯❯ echo "SELECT major FROM osx_version;" | /usr/local/Cellar/osquery/1.3.1/bin/osqueryi

+-------+
| major |
+-------+
| 10    |
+-------+
~ ❯❯❯ echo "SELECT major FROM osx_version;" | /usr/local/Cellar/osquery/1.4.2/bin/osqueryi
W0227 10:31:22.982457 77893632 iokit_hid.cpp:59] [Reference #617] Cannot open IOKit HID Manager

+-------+
| major |
+-------+
| 10    |
+-------+
```

[homebrew/35343]: https://github.com/Homebrew/homebrew/issues/35343

**Comment by theopolis** [comment]
I'm working through https://github.com/Homebrew/homebrew/issues/35343, to be clear there are two issues, both introduced by a combo of osquery + building in homebrew: (1) the pre-built bottle throws a SIGILL on your hardware (2) IOKit HID doesn't start? These might be the same root issue. 

I'm trying to figure out how to best debug homebrew builds. Most likely they are including CXX/C flags that osquery's CMake is ignoring.

**Comment by theopolis** [comment]
The illegal instruction could also be clang + a wrong reporting of CPU type. @grimnight, mind if I ask if you're installing in a VM or a hackintosh?

**Comment by grimnight** [comment]
No VM or hackintosh just OS X Yosemite. Do you need more detailed hardware information?

**Comment by theopolis** [comment]
Thanks, I'll assume it's a CXX/C flags propagation issue and run some tests.
