### ISSUE TITLE
Package payload targets incomplete path on darwin (/var instead of /private/var)

### ISSUE THREAD

**Issue by arubdesu** [facebook/osquery#808]
I was [singing the praises](https://twitter.com/Sacrilicious/status/571684030669828096) of how simple the pkgs y'all make available [here](http://osquery.io/downloads/) are, no postinstall tomfoolery and pretty intuitive, standard locations, but just one quibble: the log folder and example launchd job and conf targets in the package payload use a symlinked path, ```/var``` instead of ```/private/var```, which could potentially fail in certain installation scenarios (e.g. against an un-booted volume with [AutoDMG](https://github.com/MagerValp/AutoDMG)).

**Comment by theopolis** [comment]
Thanks! :D

I was always under the impression that using the symlinked etc, var, tmp was preferred? I know there are gotchas with things like fseventsd always reporting `realpath` even if you ask for alerts on the soft link. I'm happy to change the installer paths in [make_osx_package.sh](https://github.com/facebook/osquery/blob/master/tools/deployment/make_osx_package.sh) to use `/private` if there are no side effects. Let me know, or throw up a PR! ;)

**Comment by arubdesu** [comment]
LGTM 👍
(Wish I had beat you to the PR, but them's the breaks. Thanks!)

**Comment by theopolis** [comment]
Haha, I hate to say "PR welcome" so often, so I try to jump in an patch simple issues/recommendations ASAP. But... there are a ton more needed if you'd like to join the cause! :D
