### ISSUE TITLE
Embedded YARA

### ISSUE THREAD

**Issue by wxsBSD** [facebook/osquery#816]
I decided to embed YARA in osquery, and want to open it up for a bit of discussion before I go any further. Just to get something up and running I decided to modify the file_changes table to have a YARA column. Anytime a file is put in one of the watched places it is scanned with YARA and the matches are presented in the table. Currently only the last match is stored, but I will be fixing that. Here's an example config file:

```
{
  "scheduledQueries": [
  ],
  "additional_monitoring" : {
    "file_paths": {
      "system_binaries": [
        "/Users/wxs/tmp/foo/%"
      ]
    }
  }
}
```

And then I can spin up osquery and copy a file into ~/tmp/foo which is triggered by my YARA rules, and the output shows up in the file_changes table.

```
osquery> select * from file_changes;

+------------------------------+-----------------+-------+---------+----------------+----------------------------------+------------------------------------------+------------------------------------------------------------------+---------------+
| target_path                  | category        | time  | action  | transaction_id | md5                              | sha1                                     | sha256                                                           | yara          |
+------------------------------+-----------------+-------+---------+----------------+----------------------------------+------------------------------------------+------------------------------------------------------------------+---------------+
| /Users/wxs/tmp/foo/njrat.exe | system_binaries | 32767 | CREATED | 28909740       | 92ee1fb5df21d8cfafa2b02b6a25bd3b | 09a886f172418ec5d9fa86c5891f50b4869e2751 | 266d1e9c348b6ac17f421c0462e191faab2942d6d0504aa013d886fb9b04e648 | win_exe_njRAT |
+------------------------------+-----------------+-------+---------+----------------+----------------------------------+------------------------------------------+------------------------------------------------------------------+---------------+
osquery> 
```

I still have a lot to clean up but I wanted to put this out there for further discussion so I can refactor as necessary. My current TODO list on this includes:

1. Make YARA rule file configurable. It is currently hardcoded just to get something going.
2. Make matching rules a CSV string in the table. If there is a better way to present a list of things I'd love to know about it.
3. Further testing.

Other things I'd like input on:

1. Move this to its own subscriber and table so I can have a different way to configure it? I didn't put a ton of thought into the configuration side of things right now as my initial goal was just to get comfortable with how to embed YARA.
2. Is this even a good idea? My personal opinion is that it is a good idea to combine osquery and YARA. I'm rather excited about the possibilities this brings to enterprises using osquery.

**Comment by theopolis** [comment]
For 1. an EventSubscriber plugin is the best way for sure! You can almost 100% duplicate the [`file_changes`](https://github.com/facebook/osquery/blob/master/osquery/tables/events/linux/file_changes.cpp) subscriber's `init` method. It's perfectly fine to add a whole slew of duplicate subscriptions. The event publisher dedups these and then fires matching callbacks. So if you verbatim duplicate the set of subscriptions your yara event subscriber will be able to act within it's `Callback` by applying a set of signature files.

That `file_changes` subscriber also passes around the "category" key from subscription to the callback method. Since you'll need to hold the set of signature files separately from the subscription, you can use some sort of category (or the same!) to later identify which set of signatures to apply. 
For 2. hell yeah!

**Comment by theopolis** [comment]
With regards to moving yara into a new type of osquery compartmentalization "modules": YARA is pretty useful, I think we can benefit from yara-integrations in a few other areas in the future. Moving it into some optional or side-by-side component would be a bit of work and wont benefit us much. I say we keep the code where it is for now. In the future we might want to move yara-functions into a more available ./osquery/tables/utils/yara_utils.cpp or the like. Thoughts?

**Comment by wxsBSD** [comment]
I'm fine with keeping it where it is. I'm also in agreement that any future additions should abstract common code (ie: yara callback) into a common location.

Now I'm thinking about checking out how "where" clauses work so we can specify either files or pids on demand.

**Comment by theopolis** [comment]
Here's a good example of checking if a "constraint" or "where predicate" was set: https://github.com/facebook/osquery/blob/master/osquery/tables/system/darwin/preferences.cpp#L245. Constraints are implemented in [core/tables.cpp](https://github.com/facebook/osquery/blob/master/osquery/core/tables.cpp) using public API for [tables.h](https://github.com/facebook/osquery/blob/master/include/osquery/tables.h).

There's not much we can get from the SQLite virtual table (module) API, but we try our best. The easiest thing to act on when you're expecting discrete expressions like paths or pids is `EQUALS`, but the only way to access them is by asking for ALL constraints and selecting on the operator used. 

So to find all the equalities:
```cpp
# select * from yara_search where pid = 9001;
std::vector<std::string> pids = context.constraints["path"].getAll(EQUALS);
# {"9001"}

# Or if you want them as ints
std::vector<int> int_pids = context.constraints["path"].getAll<int>(EQUALS);
# {9001}
```

If someone where to request multiple pids: 
```sql
select * from yara_search where pid = 9001 OR pid = 9002
# or something cooler
select * from yara_search where pid in (9001, 9002)
```
You would expect this to return `{"9001", "9002"}`.

Right now our SQLite needs some hacking, by default the common SQL infix operators throw a fit, so no "in", "like", "or".

**Comment by wxsBSD** [comment]
Awesome! Thanks for the pointers! I think this will be bumped closer to the top of my list. ;)
