### ISSUE TITLE
file table, check directory query predicate

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#817]
Hey @jedi22, I think there's a regression in the file table, when listFilesInDirectory was moved into two functions. Now there `where directory =` only lists file inodes. Mind taking a look?

**Comment by jedi22** [comment]
Looking in the file.cpp table, it barely accesses the public filesystem.h interface, in fact it only does for `lsperms`. So if this is a regression, I don't think it was caused by that. Should 
`select * from file where directory = '/'` return /usr, /bin etc?

**Comment by theopolis** [comment]
Yeah, looks like we need to change that logic to emit the directories too!

**Comment by jedi22** [comment]
#822

**Comment by jedi22** [comment]
Merged
![blog_120906_08](https://cloud.githubusercontent.com/assets/2386877/6491725/1981a6a2-c264-11e4-9ca7-e3f2448d851e.png)
