### ISSUE TITLE
make deps failed on Ubuntu 12.04 LTS (i386) due to cannot compile this atomic library

### ISSUE THREAD

**Issue by LilyQin** [facebook/osquery#821]
Error log as below:

```
~/osquery/.sources/rocksdb-rocksdb-3.5 ~/osquery/.sources
make[1]: Entering directory `/root/osquery/.sources/rocksdb-rocksdb-3.5'
clang++ -g -Wall -Werror -Wsign-compare -I. -I./include -std=c++11  -DROCKSDB_PLATFORM_POSIX  -DOS_LINUX -fno-builtin-memcmp -DROCKSDB_ATOMIC_PRESENT -DROCKSDB_FALLOCATE_PRESENT -DSNAPPY -DGFLAGS=google -DZLIB -DBZIP2   -DHAVE_JEMALLOC -O2 -fno-omit-frame-pointer -momit-leaf-frame-pointer -DNDEBUG -Woverloaded-virtual -c db/column_family.cc -o db/column_family.o
In file included from db/column_family.cc:10:
In file included from ./db/column_family.h:15:
In file included from /usr/include//c++/4.8/atomic:41:
/usr/include//c++/4.8/bits/atomic_base.h:404:16: error: cannot compile this atomic library call yet
      { return __atomic_add_fetch(&_M_i, 1, memory_order_seq_cst); }
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [db/column_family.o] Error 1
make[1]: Leaving directory `/root/osquery/.sources/rocksdb-rocksdb-3.5'
make: *** [deps] Error 2
```

**Comment by theopolis** [comment]
Thanks @LilyQin! I'm having trouble reproducing the build error. Is this in the osquery [vagrant ubuntu12](https://github.com/facebook/osquery/wiki/install-linux#building-from-source) image? And I'm assuming this is the first time running `make deps` on the system?

**Comment by LilyQin** [comment]
Yes running make deps on the system at first time, but I don't know which osquery image was i used. My build steps as below:

$ git clone http://github.com/facebook/osquery.git
$ cd osquery
$ make deps

BTW: Where can download osquery deb package with Ubuntu 12.04 LTS (i386)?

**Comment by theopolis** [comment]
Ok, sorry about that, it could be an untested version of glibc/clang (or anything llvm). It's hard to debug compiler errors in our dependencies if you're not using our vagrant templates. :P

deb packages and our apt repo details: http://osquery.io/downloads/

**Comment by LilyQin** [comment]
I try to use as below steps to install osquery, but still failed:

$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C9D8B80B
$ sudo add-apt-repository "deb https://osquery-packages.s3.amazonaws.com/precise precise main"
$ sudo apt-get update

Error message as below:
Hit http://ppa.launchpad.net precise/main Translation-en
Fetched 2386 B in 1s (2051 B/s)
W: Failed to fetch https://osquery-packages.s3.amazonaws.com/precise/dists/precise/InRelease  Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)

E: Some index files failed to download. They have been ignored, or old ones used instead.

root@usx-21045:~# cat /etc/apt/sources.list
deb http://archive.ubuntu.com/ubuntu precise main
deb https://osquery-packages.s3.amazonaws.com/precise precise main
deb-src https://osquery-packages.s3.amazonaws.com/precise precise main
root@usx-21045:~# ^C

BTW:  I try to download precise/osquery.deb to install, but is only support adm64 :(.

**Comment by theopolis** [comment]
Right, we don't build or host a 32bit deb or include one in our apt repo.

**Comment by LilyQin** [comment]
Thanks a lot.

**Comment by theopolis** [comment]
Hey @javuto, what do you think it would take to generate x86 packages? I've never thought about what impact it would have on our testing, provisioning, or build. I'd bet it's "a lot of work", and I don't know how much impact it would have (aka, I don't think many people would benefit from x86 binaries). But I'm curious about your thoughts!

**Comment by theopolis** [comment]
Hey @LilyQin, unfortunately we can't support non-64bit builds at this time. Sorry for the wait, but I've been slowly testing our dependencies and what it would take to generate both builds. It will take a considerable effort to build some development dependencies non-64bit and maintain the additional vagrant environments + Jenkins CI.

**Comment by BAjayKrishna** [comment]
Hey Guys, I have encountered a similar issue while installing it on Ubuntu 12.04 (64bit) following [this](https://osquery.readthedocs.org/en/stable/installation/install-linux/) doc.
`$ sudo  apt-get update` failed with following error . .

W: Failed to fetch https://osquery-packages.s3.amazonaws.com/precise/dists/precise/Release  Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)

Looking at my /etc/apt/sources.list file, it has the following lines

```deb https://osquery-packages.s3.amazonaws.com/precise precise main```
```deb-src https://osquery-packages.s3.amazonaws.com/precise precise main```

But the the [Release file](https://osquery-packages.s3.amazonaws.com/precise/dists/precise/Release) on s3 don't have any pointers to the ```deb-src``` that apt seems to look for, so it failed. .

To work around this problem i have deleted following line from my `sources.list` file
```deb-src https://osquery-packages.s3.amazonaws.com/precise precise main```

Just though of writing this here if someone stumbles up on this thread looking for a solution. Thanks.

**Comment by javuto** [comment]
Hey @BAjayKrishna, this seems to be a known problem in Ubuntu 12 (precise). By default, it adds the source repository and we do not have any source package in the repo. You could edit manually the sources.list and comment/remove the line ```deb-src [arch=amd64] https://osquery-packages.s3.amazonaws.com/precise precise main``` or execute ```sudo add-apt-repository -r "deb-src [arch=amd64] https://osquery-packages.s3.amazonaws.com/precise precise main"```

**Comment by javuto** [comment]
Oops, I should have refreshed before answering. We agreed on the solution thought :)
