### ISSUE TITLE
Use a list for config["additional_monitoring"]["file_changes"]

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#830]
I would be nice to represent each "file_changes" list of paths as a dict with "paths" as a key, along with "name" and "features". The added `features` would also be a list and allow us to extend input from Yara OR join from multiple locations easier. // @wxsBSD, @jedi22

**Comment by jedi22** [comment]
This would break any existing config files using the old mechanism. (obviously)

So one of the proposed features of this would be to easily merge things like

```JSON
{"name" : "binaries", "paths" : ["/bin/", "/usr/bin"], "features":["yara"]}
```
with
```JSON
{"name" : "binaries", "paths" : ["/bin/", "/sbin/"], "features":["VT"]}
```

into

```JSON
{"name" : "binaries", "paths" : ["/bin/", "/usr/bin", "/sbin/"], "features":["yara", "VT"]}
```

**Comment by wxsBSD** [comment]
This is the syntax I was thinking of:

```
{
  "name": "binaries",
  "paths" ["/bin/%", "/usr/bin/%"],
  "features": [ { "yara": { "rules": ["/tmp/foo.sig", "/tmp/bar.sig"] } } ]
}
```

Features would be a list of dictionaries, where the key would be the name of the feature and the value would be any feature-specific options as dictionaries. For this example it would be the paths of which YARA rules to use. 

I'm going to base my YARA work off this branch, it's going to make my life easier. :smile:

**Comment by theopolis** [comment]
@jedi22  and I whiteboarded this a bit yesterday. What about keeping the existing:
```
"additional_monitoring" : {
  "file_paths": {
    "downloads": [],
    "system_binaries": ["/bin/%sh", "/tmp/"]
  }
}
```

And then adding another key to "additional_monitoring":
```
"additional_monitoring" : {
  "file_paths": {
    "downloads": [],
    "system_binaries": ["/bin/%sh", "/tmp/"]
  },
  "yara": {
    "downloads": ["@all"],
    "system_binaries": ["/path/to/binary_sigs.yara", "/other/path/to/osx_binary_sigs.yara"]
  }
}
```

You'll have to repeat each key in "yara" that exists in "file_paths", iff you want to apply some set of rule files with `@all` keywords for meta-groups of sig files.

**Comment by wxsBSD** [comment]
That works for me. To support ```@all``` we would need a way to say what that means, but I like the idea of being able to provide groupings of signature files and specify them this way.

**Comment by theopolis** [comment]
Me thinks for @all, we could define a key called "@all" with a set of paths and say all keys that start with @ are considered meta keys, and may be used as values, and we sub in their values. 

Paths can also be a file or dir, if dir we enumerate and include all files.

**Comment by wxsBSD** [comment]
I think that's reasonable. This would all be handled by the configuration handling code, so I'm not going to implement that in my current work in the interest of keeping my changes limited to just YARA.

**Comment by theopolis** [comment]
Awesome! Let's close this out since we're solving the problem without needing the change.
