### ISSUE TITLE
Vertical Display in osqueryi

### ISSUE THREAD

**Issue by mag00** [facebook/osquery#847]
MySQL has a sweet option "\G" after queries:

http://dev.mysql.com/doc/refman//5.5/en/mysql-commands.html

This displays results vertically in a console, useful when output is wider than window.

Example:
http://pento.net/2009/02/27/the-g-modifier-in-the-mysql-command-line-client/ 

So something like `select * from alf\G` won't be a stack of visual crap.

**Comment by mag00** [comment]
found --line and other options, so this feature request is probably worse.

**Comment by marpaia** [comment]
JFYI, you can also do `.mode line` while you're in osquery to turn on line mode. You can then type `.mode pretty` to go back to the default.
