### ISSUE TITLE
select * from file;      not output

### ISSUE THREAD

**Issue by swuecho** [facebook/osquery#859]
osquery> select * from osx_version;

+-------+-------+-------+
| major | minor | patch |
+-------+-------+-------+
| 10    | 10    | 2     |
+-------+-------+-------+
osquery> select * from osquery_info;

+---------+------------+---------------------------+------+------------+
| version | config_md5 | config_path               | pid  | extensions |
+---------+------------+---------------------------+------+------------+
| 1.4.2   |            | /var/osquery/osquery.conf | 2703 | active     |
+---------+------------+---------------------------+------+------------+
osquery> select * from file;
osquery>

**Comment by theopolis** [comment]
file needs a path or directory. :)

Try:
`select * from file where path = '/path/to/some/file';`
`select * from file where directory = '/etc/';`

**Comment by swuecho** [comment]
great! Thanks.
