### ISSUE TITLE
filesystem API is not catching exceptions

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#863]
```
» ./build/darwin/osquery/osqueryi "select * from chrome_extensions"
libc++abi.dylib: terminating with uncaught exception of type boost::filesystem::filesystem_error: boost::filesystem::status: Permission denied: "/Users/admin/Library/Application Support/Google/Chrome/Default/Extensions/"
[1]    6498 abort      ./build/darwin/osquery/osqueryi "select * from chrome_extensions"
```

**Comment by theopolis** [comment]
Line: https://github.com/facebook/osquery/blame/master/osquery/filesystem/filesystem.cpp#L132
Diff: https://github.com/facebook/osquery/commit/637336f8c9ac282bda3dc5dd55d26eae206af09d

**Comment by jedi22** [comment]
Fixing in lastest pull, will close when merge build succeeds

**Comment by jedi22** [comment]
This should be fixed now

**Comment by theopolis** [comment]
Line: https://github.com/facebook/osquery/blame/master/osquery/filesystem/filesystem.cpp#L143
