### ISSUE TITLE
python module API

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#876]
Please comment on ways that we can extend/improve the API for the upcoming python module. We're still working through it, but we want the API itself to be intuitive, so we're designing the API first. 

Consider the following "extension" that registers a logger plugin, a config plugin and a new table:

```py
import json
import pyosquery

class RandomLoggerPlugin(pyosquery.LoggerPlugin):
    def log_string(self, string):
        print("[+] {value}".format(value=string))

class RandomTablePlugin(pyosquery.TablePlugin):
    def columns(self):
        return {
            {"foo": pyosquery.INTEGER},
            {"bar": pyosquery.TEXT},
        }

    def generate(self, context):
        results = []
        for i in range(10):
            row = {}
            row["foo"] = i
            row["bar"] = "my number is {i}".format(i=i)
            results.append(row)
        return results

class RandomConfigPlugin(pyosquery.ConfigPlugin):
    def generate_config(self):
        return json.dumps({
            "scheduledQueries": [
                {
                    "name": "example_1",
                    "query": "select * from osquery_info;",
                    "interval": 10,
                },
                {
                    "name": "example_2",
                    "query": "select * from osquery_flags;",
                    "interval": 20,
                },
            ]
        })

if __name__ == "__main__":
    pyosquery.register_logger(RandomLoggerPlugin, "foolog")
    pyosquery.register_config(RandomConfigPlugin, "barconf")
    pyosquery.register_table(RandomTablePlugin, "randtab")

    pyosquery.start_extension()
```

In the above example, you could start osqueryd with the following flags:

```
osqueryd --config_plugin=foolog --config_plugin=barconf
```

You could also schedule a query: 
```sql
SELECT foo, bar FROM randtab;
```

Additionally, you can execute queries:

```py
import pyosquery

if __name__ == "__main__":
    conn = pyosquery.connect(path="/var/osquery/osquery.em")
    q = conn.query("select * from randtab")
    for result in q.results:
        print "foo: {foo}, bar: {bar}".format(foo=result["foo"], bar=result["bar"])
```

**Comment by theopolis** [comment]
If you run the python shell as a non-root user a `pyosquery.connect` will fail. Do you think it makes sense to have a `create` method that spawns an instance of the shell as a subprocess and connects to it's transient socket?

**Comment by wxsBSD** [comment]
I assume part of this plan is to also expose the event system so you can write event publishers or event subscribers in python?

Also, one of the things I've had in the back of my mind is the ability to remotely query the state of an osqueryd. The idea would be to have an equivalent of an Apache status page for osqueryd, either directly exposed in osqueryd or via a completely separate web application that can connect to a running osqueryd and collect information. In particular seeing things like number of events fired, number of failed subscribers, and also possibly restarting subscribers or osqueryd entirely. Totally pie in the sky thoughts but it would be nice to be able to do.

**Comment by theopolis** [comment]
@wxsBSD although it's possible to register an event publisher and subscriber, you can't publish and subscribe to either through the extensions API. If you were writing a C++ extension like [example_extension.cpp](https://github.com/facebook/osquery/blob/master/osquery/examples/example_extension.cpp) you could `REGISTER_EXTERNAL` your publisher and subscriber and publishing to that subscriber would work just fine. You wouldn't be able to subscribe to inotify though. I'd like to support subscribing over extensions in the future. As soon as there's a thrift API for adding a subscription, we'd be able to write publishers or subscribers in any language. 

You can run SQL queries using the existing thrift API, check out: [test_extensions.py#140](https://github.com/facebook/osquery/blob/master/tools/tests/test_extensions.py#L140), this is limited to UNIX domain socket connections so remote = still local to the machine running osqueryd. Communication beyond would be up to you.

**Comment by blackfist** [comment]
In the example above, where did `pyosquery` come from?

**Comment by marpaia** [comment]
@blackfist ah, this isn't written yet, we were just tossing around what the API would look like

**Comment by marpaia** [comment]
Here's an example of the API in it's current version. Let me know if anyone doesn't like the names of types, functions, classes, etc.

```python
#  LICENSE file in the root directory of this source tree. An additional grant
#  of patent rights can be found in the PATENTS file in the same directory.

import sys
import osquery

@osquery.register_plugin
class MyLoggerPlugin(osquery.LoggerPlugin):
    def name(self):
        return "my_logger"

    def log(self, value):
        print("[+] %s" % value)

@osquery.register_plugin
class MyConfigPlugin(osquery.ConfigPlugin):
    def name(self):
        return "my_config"

    def content(self):
        return {
            "schedule": {
                "foo": {
                    "query": "select * from foobar",
                    "interval": 5,
                },
            },
        }

@osquery.register_plugin
class MyTablePlugin(osquery.TablePlugin):
    def name(self):
        return "foobar"

    def columns(self):
        return [
            osquery.TableColumn(name="foo", type=osquery.STRING),
            osquery.TableColumn(name="baz", type=osquery.INTEGER),
        ]

    def generate(self, context):
        query_data = []

        for i in range(5):
            row = {}
            row["foo"] = "bar"
            row["baz"] = "baz"
            query_data.append(row)

        return query_data

if __name__ == "__main__":
    osquery.start_extension()
```

**Comment by arirubinstein** [comment]
:+1: Looking forward to this @marpaia

**Comment by marpaia** [comment]
i'm going to close this, let's track this in #1020

**Comment by theopolis** [comment]
Looks great!

A couple of default assumptions: 
- We should be able to call `register_plugin`, and a similar `deregister_plugin` at anytime during the extension's execution. 
- `start_extension` blocks until the process ends.
- There's quite a bit of python code required to manage the call API in the extension interface.

**Comment by marpaia** [comment]
@theopolis, i copied your comments over to #1020 and kept the conversation going over there.

**Comment by marpaia** [comment]
re-opening as per #1013

**Comment by theopolis** [comment]
Moving development to https://github.com/osquery/osquery-python

**Comment by marpaia** [comment]
This is ready for some more eyes on it: https://github.com/osquery/osquery-python/pull/2
