### ISSUE TITLE
add configuration profiles

### ISSUE THREAD

**Issue by keeleysam** [facebook/osquery#879]
It would be good to have configuration profiles tracked, getting the same information from this output:

```
system_profiler SPConfigurationProfileDataType
```

**Comment by theopolis** [comment]
Agreed! Any interest in implementing it? ;)

**Comment by theopolis** [comment]
system_profiler uses the private framework SPSupport that takes an optional `Type`DataType parameter and calls an async `.reporter` bundle from `/System/Library/SystemProfiler/<Type>Reporter.spreporter`. 

List of reporters (this is a work in progress):

| Reporter | Exists | Methods/Issue |
|-------------|------------|---------------------|
`SPAirPort` |
`SPApplications` | apps |
`SPAudio` |
`SPBluetooth` |
`SPCamera` |
`SPCardReader` |
`SPComponent` |
`SPConfigurationProfile` |
`SPDeveloperTools` |
`SPDiagnostics` |
`SPDisabledApplications` | ??? | 
`SPDiscBurning` | ???
`SPDisplays` |
`SPEthernet` | network_interfaces | 
`SPExtensions` | kernel_extensions | includes more details
`SPFibreChannel` | 
`SPFireWire` |
`SPFirewall` | alf
`SPFont` |
`SPFrameworks` |
`SPHardwareRAID` |
`SPInstallHistory` | package_receipts |
`SPLogs` |
`SPManagedClient` |
`SPMemory` |
`SPNetworkLocation` |
`SPNetwork` |  |
`SPNetworkVolume` |
`SPOS` |
`SPPCI` | pci_devices |
`SPParallelATA` |
`SPParallelSCSI` |
`SPPlatform` |
`SPPower` |
`SPPrefPane` |
`SPPrinters` |
`SPPrintersSoftware` |
`SPSAS` |
`SP`SPI` |
`SPSerialATA` |
`SPStartupItem` | startup_items |
`SPStorage` | block_devices |
`SPSync` |
`SPThunderbolt` | pci_devices | not sure if TB devices are listed
`SPUSB` | usb_devices |
`SPUniversalAccess` |
`SPWWAN` |

Where "exists" means we are already capturing the needed information in another table.

**Comment by theopolis** [comment]
For `SPConfigurationProfile`, the output of `profiles -P -v` lists the aggregate managed configuration. This is cached from LDAP/AD/MDM-MCX services in `/Library/Managed Preferences`, a conflicting name with `~/Library/Preferences` and others parsed in our `preferences` table. :/

It looks like managed profiles imported using the profile tool are also stored here. I'm curious about the CoreData/NSPersistentStore data in `/var/db/ConfigurationProfiles/` but that seems very volatile so parsing the cached/aggregate plists might be a first cut solution.

**Comment by theopolis** [comment]
This now exists as `managed_policies` on OS X. I'm going to close this but backup the list of reporters in another issue.
