### ISSUE TITLE
Error compiling on OSX

### ISSUE THREAD

**Issue by umareddy** [facebook/osquery#888]
I am following the instructions to build after git clone. I get the following error, the directory /Library/PostgreSQL/9.4/lib does exist. Any idea why I am getting  clang: error: no such file or directory: ':/Library/PostgreSQL/9.4/lib'

Building CXX object osquery/CMakeFiles/example_extension.dir/examples/example_extension.cpp.o
[ 82%] Built target osquery_tables_darwin
[ 82%] Built target libosquery_additional
Scanning dependencies of target run
Scanning dependencies of target shell
Linking CXX executable osqueryd
clang: error: no such file or directory: ':/Library/PostgreSQL/9.4/lib'
make[3]: *** [osquery/osqueryd] Error 1
make[2]: *** [osquery/CMakeFiles/daemon.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 83%] [ 83%] Building CXX object osquery/CMakeFiles/shell.dir/devtools/shell.cpp.o
Building CXX object osquery/CMakeFiles/shell.dir/main/shell.cpp.o
[ 84%] Building CXX object osquery/CMakeFiles/run.dir/main/run.cpp.o
Linking CXX executable run
clang: error: no such file or directory: ':/Library/PostgreSQL/9.4/lib'
make[3]: *** [osquery/run] Error 1
make[2]: *** [osquery/CMakeFiles/run.dir/all] Error 2
Linking CXX executable osqueryi
clang: error: no such file or directory: ':/Library/PostgreSQL/9.4/lib'
make[3]: *** [osquery/osqueryi] Error 1
make[2]: *** [osquery/CMakeFiles/shell.dir/all] Error 2
Linking CXX shared library libmodexample.dylib
clang: error: no such file or directory: ':/Library/PostgreSQL/9.4/lib'
make[3]: *** [osquery/libmodexample.dylib] Error 1
make[2]: *** [osquery/CMakeFiles/modexample.dir/all] Error 2
Linking CXX executable example_extension.ext
clang: error: no such file or directory: ':/Library/PostgreSQL/9.4/lib'
make[3]: *** [osquery/example_extension.ext] Error 1
make[2]: *** [osquery/CMakeFiles/example_extension.dir/all] Error 2
Linking CXX static library libosquery_testing.a
[ 84%] Built target libosquery_testing
make[1]: *** [all] Error 2
make: *** [all] Error 2

**Comment by theopolis** [comment]
Interesting, there's no PostgreSQL deps at all! Sounds like CMake's set of find packages are pulling in unintended paths.

Can you post the complete output of `make deps` and `make VERBOSE=1`?

The `./build/darwin/CMakeCache.txt` could be helpful too, search that and see if the PostgreSQL path was detected for any variable.

**Comment by umareddy** [comment]
Your response made me look at my environment variables. As I am using PostgreSQL for other projects I had the following set:
LDFLAGS=:/Library/PostgreSQL/9.4/lib

I searched for references to PostgreSQL in all the files under osquery folder. build/darwin/CMakeFiles/CMakeError.log had a reference, this is obvious. I also noticed a reference in CMakeCache.txt, this was strange, here is what I found in CMakeCache.txt file. Looks like the LDFLAGS environment variable was causing this to be set.
//Flags used by the linker.
CMAKE_EXE_LINKER_FLAGS:STRING= :/Library/PostgreSQL/9.4/lib

//Flags used by the linker during the creation of modules.
CMAKE_MODULE_LINKER_FLAGS:STRING= :/Library/PostgreSQL/9.4/lib

//Flags used by the linker during the creation of dll's.
CMAKE_SHARED_LINKER_FLAGS:STRING= :/Library/PostgreSQL/9.4/lib

I went ahead and removed the LDFLAGS environment variable and rebuilt, success - built clean. This allows me to make progress for now.

If I remove the LDFLAGS setting I am sure I will have have a problem when I build a program which pulls in PostgreSQL libraries.

Is this a problem that can be fixed in the osquery make process? I do not have enough knowledge to figure out how to fix the make process.

Thanks for your help.

Let me know if you still need the make and make VERBOSE output.

**Comment by theopolis** [comment]
Cool! No verbose output needed, but it may be helpful!

Allowing the builder/build environment to override variables is a good idea IMO. It would let you build with a different version of boost or thrift if you wanted to use non-system default search paths. Homebrew may need to set LDFLAGS when using our CMake too!

clang and osquery should work fine if you add more LDFLAGS, but it seems like CMake is having trouble parsing the value.

Should it be "-L /Library/..."? The preceding colon may also be the error. Making with verbose should give the exact clang call.

**Comment by umareddy** [comment]
After further testing, as you pointed out the problem was my LDFLAGS setting. I changed it to LDFLAGS=-L/Library/PostgreSQL/9.4/lib, my mistake.
the build works fine now.
Thanks for your time. I am closing the issue.
