### ISSUE TITLE
add OS X package receipts

### ISSUE THREAD

**Issue by keeleysam** [facebook/osquery#890]
Currently .apps are monitored but packages installed by installer are not.  It should be relatively easy to monitor all plists in /var/db/receipts, but bonus points for getting info from the BOMs too.

**Comment by theopolis** [comment]
`pkgutil` enumerates receipts/BOMs using the BOM PrivateFramework: `/System/Library/PrivateFrameworks/Bom.framework`. I can't find a reliable source of receipt directories given a Volume, which is what the private symbol:

```objc
+ (NSArray *)receiptsOnVolumeAtPath:(NSString*)path;
```

provides. The path could be "/" in this case. We have externed a private symbol before and linked the non-private framework library. This however requires both an extern + private link, very scary. 

We can include a few well-known paths to receipts: `/private/var/db/receipts/` and `~/Library/Receipts`. We'll parse the receipt plists normally and pull out some well-known dictionary keys. The BOMs will take a little more work, perhaps some side-by-side BOM parsing utilities.

Any other ideas?

**Comment by theopolis** [comment]
Always go for bonus points: https://github.com/facebook/osquery/pull/899

**Comment by theopolis** [comment]
Note: the BOM parsing requires a path=/path/to/bom. Discovering and parsing all boms took a crazy amount of CPU. If one wanted an inventory of all packages you could join against file and provide a directory to search.

**Comment by theopolis** [comment]
Merged!
