### ISSUE TITLE
add Active Directory configuration information

### ISSUE THREAD

**Issue by keeleysam** [facebook/osquery#892]
basically the output of
```
/usr/sbin/dsconfigad -show -xml
```

**Comment by theopolis** [comment]
I couldn't find source code or an obvious framework for this tool so I reversed the binary (it's not too big). The -show trigger parses `/Library/Preferences/OpenDirectory/Configurations/Active Directory/*.plist` files, looks for the "module options" dictionary key and pretty-formats each of the "ActiveDirectory/*" first level subkeys. There's some more pretty-formatting applied to their values to turn CFBooleanRef=CFBoolean(true) into "Enabled" and such.

We can get this information with the `preferences` table right now (as root), but this is a case for separate/dedicated table. Normal permissions would apply, only root osqueryi/osqueryd users would be able to list/read those plists.

**Comment by theopolis** [comment]
This is also a problem: [GH-895](https://github.com/facebook/osquery/issues/895), once that's fixed you can:

```sql
SELECT p.domain, p.key, p.subkey, p.value
FROM (
  SELECT path
  FROM file
  WHERE directory = '/Library/Preferences/OpenDirectory/Configurations/Active Directory/'
) f, preferences p
WHERE p.path = f.path;
```

**Comment by marpaia** [comment]
> I couldn't find source code or an obvious framework for this tool so I reversed the binary

![image](https://cloud.githubusercontent.com/assets/927168/6785887/d97c3478-d145-11e4-84d3-97196f6eccfd.png)

**Comment by theopolis** [comment]
Implemented in: https://github.com/facebook/osquery/pull/897
