### ISSUE TITLE
fix www.osquery.io

### ISSUE THREAD

**Issue by keeleysam** [facebook/osquery#893]
www.osquery.io is a CNAME for facebook.github.io, which itself is a CNAME to github.map.fastly.net, it looks like this used to be used for GitHub pages.

It should probably be configured the same as osquery.io so the page actually works instead of landing on a GitHub 404 page.

**Comment by theopolis** [comment]
@marpaia, there was an internal task to update 'www' for osquery.io, I don't think you control the domain anymore, but would you mind pinging the new domain owners again?

**Comment by marpaia** [comment]
@theopolis, the DNS is owned by FB now, but we still control the DNS via Route53. I'll change it now.

**Comment by marpaia** [comment]
www.osquery.io is now an A record to 54.193.126.242
