### ISSUE TITLE
enable HSTS for osquery.io

### ISSUE THREAD

**Issue by keeleysam** [facebook/osquery#894]
Now that osquery.io is properly setup for SSL, please add this header to enable HSTS.  This is the same config facebook.com uses.
```
Strict-Transport-Security: max-age=15552000; preload
```

**Comment by marpaia** [comment]
Thanks for keeping us honest, @keeleysam :)

**Comment by theopolis** [comment]
pushed

**Comment by keeleysam** [comment]
thank you!

it will be preloaded to Chrome in about 10 weeks.

On Tue, Mar 31, 2015 at 6:54 PM, Teddy Reed <notifications@github.com>
wrote:

> Closed #894 <https://github.com/facebook/osquery/issues/894>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/osquery/issues/894#event-270195060>.
>



-- 
Samuel Keeley
