### ISSUE TITLE
mixed content on osquery.io

### ISSUE THREAD

**Issue by keeleysam** [facebook/osquery#898]
These buttons are loaded over HTTP not HTTPS so modern browsers will refuse to load them or show a mixed content warning: https://www.dropbox.com/s/cdpkzgrlt0kvikt/Screenshot%202015-03-23%2012.18.41.png?dl=0

ghbtns.com is available over SSL so just change it to https from http https://ghbtns.com/github-btn.html?user=facebook&repo=osquery&type=watch&count=true&size=large

**Comment by marpaia** [comment]
<noob> What page are these buttons hosted on? </noob>

**Comment by keeleysam** [comment]
the home page

On Mon, Mar 23, 2015 at 12:23 PM, Mike Arpaia <notifications@github.com>
wrote:

> What page are these buttons hosted on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/osquery/issues/898#issuecomment-85111484>.
>



-- 
Samuel Keeley

**Comment by marpaia** [comment]
@theopolis, I tested in inspector and pushed an update to `osquery-site`. Can you re-push whenever you get a chance?

**Comment by theopolis** [comment]
pushed
