### ISSUE TITLE
--clean or --reinitialize option for osquery package

### ISSUE THREAD

**Issue by eastebry** [facebook/osquery#902]
When deploying a new version of the daemon to a host, sometimes it is nice to have the daemon start fresh, with an empty query results database.

I propose adding a `--clean` option the package building script, or to osqueryctl that would cause the daemon to start fresh. 

This could be implemented by simply rm-ing /var/osquery/osquery.db. Or perhaps there is a better solution?

**Comment by theopolis** [comment]
Good point. I like `--clean` as a part of osqueryctl, then we can choose to clean in a cookbook.

**Comment by eastebry** [comment]
Is removing the database suitable? Would be a pretty easy change, I could jump on it this evening.

**Comment by theopolis** [comment]
Yeah, it's fine. But you'll generate logs for the results of every query the next/first time they run.

**Comment by theopolis** [comment]
Merged: https://github.com/facebook/osquery/commit/afe76d4f6e0420450f0cc654033ae439f4e78062
