### ISSUE TITLE
Filesystem status logging (glog) should use YYYYMMDD for logfile separations

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#907]
We're seeing instances where glog is creating a whole ton of log files. This needs to stop.

Internal task reference: t6595858

**Comment by theopolis** [comment]
Might be better to handle this outside of the daemon, and rather in logrotate or newsyslog: https://github.com/facebook/osquery/issues/829

Then the sysadmin can determine how many iterations of log files they want to keep around.

Alternatively, we could emit status logs to filenames with the format: `osqueryd.WARNING.YYYYMMDD` without the timestamp, then you'll get at max 1 per day. Easier to describe rotate rules this way too!

**Comment by marpaia** [comment]
I think we definitely need to do something. I like changing the log format, does glog allow that?
