### ISSUE TITLE
Add FileVault full disk encryption status

### ISSUE THREAD

**Issue by sharvilshah** [facebook/osquery#911]
Hello osquery team,

According to #619, FDE status is up for grabs. 
I would like to work on this, at least on the OS X FileVault side of things, since I am not super familiar with LUKS/dm-crypt and state of FDE tooling on Linux.

##### Minimum info that is exposed:
* Encryption status
* UUID of the logical volume

##### Wishlist:
* Whether a personal recovery key has been set
* Whether an institutional recovery key has been set

Implementing wishlist would most likely require disassembling/poking in the private frameworks.

**Comment by theopolis** [comment]
The minimum info sounds perfect.

Think it's possible to have a singe table cover both information from FV and LUKS? A 1-row table should be ok. The status field is definitely applicable to both. UUID of logical volume would be the Linux device mapper volume.

Beyond that I'm not sure, maybe a liberally-used mode column when FV settings are investigated and added. Then in FV institution mode there's a path to public x509 cert. If there's additional FV specific details maybe a file_vault table is best.

**Comment by theopolis** [comment]
I'm not on OS X right now, but the DiskArbitration service might provide some details about the Logical Volume path and it's UUID: https://github.com/facebook/osquery/blob/master/osquery/tables/system/darwin/block_devices.cpp

Maybe there's a "FV-encrypted/protected" flag somewhere for each volume? The protected key is in a keychain. If there's no FV setting for what keychain the key is in we can leave those details out and rely on the keychain_items table for details. 

Also, including both the UUID and logical volume path of the encrypted device would be nice. A lot of table use "path" as a primary or foreign key.

**Comment by sharvilshah** [comment]
Actually logical volume management is exposed via `CoreStorage`. 
I have been dissecting respective PrivateFrameworks and libCoreStorage.dylib for a while now, and  `kCoreStorageIsEncryptedKey`, `kCoreStorageLogicalClassName`, `kCoreStorageLVFUUIDKey` fields are exposed. 

The value for `kCoreStorageLogicalClassName` is just `CoreStorageLogical`, and we can query properties via `ioreg`.

```bash
❯ ioreg -c CoreStorageLogical | grep -i corestorage
    | | | |                     | +-o CoreStoragePhysical  <class CoreStoragePhysical, id 0xsomeaddr, !registered, !matched, active, busy 0 (71 ms), retain 7>
    | | | |                     |   +-o Macintosh HD  <class CoreStorageGroup, id 0xsomeaddr, registered, matched, active, busy 0 (71 ms), retain 9>
    | | | |                     |     +-o Macintosh HD  <class CoreStorageLogical, id 0xsomeaddr, registered, matched, active, busy 0 (1 ms), retain 12>
    | | | |                     |       |   "CoreStorage" = Yes
    | | | |                     |       |   "CoreStorage LVF UUID" = "<uuid>"
    | | | |                     |       |   "CoreStorage CPDK" = No
    | | | |                     |       |   "CoreStorage Encrypted" = Yes
    | | | |                     |       |   "CoreStorage LVG UUID" = "<my uuid>"
    | | | |                     |       +-o CoreStorageLogicalBSDClient  <class CoreStorageLogicalBSDClient, id 0x1000002e4, registered, matched, active, busy 0 (0 ms), retain 7>
      +-o CoreStorage  <class CoreStorage, id 0xasdfasd, registered, matched, active, busy 0 (378 ms), retain 6>
```
So I think I can get a DADisk reference, and pass it to IOKit/IORegistry, and query those keys. I am new to both C++ and OS X low level APIs, so I am going by iokit_utils and iokit_registry in the source.

Does that approach sound good?

**Recovery Keys**:

Dissecting libcsfde.dylib (CoreStorage FDE) has been harder, I don't think encryption type is exposed, and AFAIK FV only supports AES with XTS as the mode of operation. No progress on figuring out if personal recovery key has been set.

Also with institutional key, can we just rely on a hard-coded path to FileVaultMaster.keychain? And can we assume having FileVaultMaster.keychain means an institutional key has been set?

**LUKS:**

I don't want to experiment on my only desktop, so will have to spin up VMs and configure dm-crypt/LUKS, and play around it with. This might take a little bit longer.

**Comment by theopolis** [comment]
That approach sounds great!

My only caution is `extern`ing the CoreStorage constants: `kCoreStorageIsEncryptedKey`, `kCoreStorageLogicalClassName`, etc. In osquery we have been [redefining](https://github.com/facebook/osquery/blob/master/osquery/tables/system/darwin/pci_devices.cpp#L26) the IOKit-related class and key names to avoid linking against the undocumented/unsupported private frameworks. There is one [instance](https://github.com/facebook/osquery/blob/master/osquery/tables/system/darwin/preferences.cpp#L175) where we depend on an undocumented symbol, but that symbol is in a public framework slated for deprecation, which we'll address in the near future.

So feel free to `#define` or `const std::string kCoreStorageClassname_ = "CoreStorageLogical"` within the FDE table. If we need additional logical volume control or `CoreStorage` information we can pull out the registry class names later.

I'm assuming you'll query IOKit/CoreStore/or DiskArbirtration, which ever is easiest, for every mounted device, then use the IOKit queries to determine if that device includes the CoreStorage FV details/keys. If "CoreStorage LVF UUID" is the same as `IOMedia`'s "UUID" then we can easily join `block_devices` and `mounts`.

For the key types and mode, feel free to punt for now. But reversing the fde library is excellent, I'm very excited to see what you find!

**Comment by sharvilshah** [comment]
Yeah, that makes complete sense.


`CoreStorage LVF UUID`  is not the same as the one reported in `block_devices` table, which reports the LV UUID. But I agree, it would be cleaner to just have an encryption column in `block_devices`. 

From what I gather ([diskutil manpage](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/diskutil.8.html) and [this blog post](http://blog.fosketts.net/2011/08/04/mac-osx-lion-corestorage-volume-manager/)): encryption happens at the LVF (Logical Volume Family) level which consists of one or more LVs. And `block_devices` is reporting PVs and LVs (not LVF).

Maybe I can just use the BSD name, if that works, we can't report on the LVF UUID (just the PV/LV UUIDs), does that matter? I will give it a shot, if it doesn't work, or we absolutely want LVF UUID then I will create a new table.

I will get started on an "in progress" pull request for implementing the minimal information. Once that is reviewed (ie tests and performance look good), I can take a stab at Linux FDE status and if we want to display encryption type.
