### ISSUE TITLE
The --check_config osqueryd option does daemon init-y things

### ISSUE THREAD

**Issue by eastebry** [facebook/osquery#915]
Right now, the logic for `--check_config` happens after the daemon is initialized. If you just want to check the config file for syntax errors, osqueryd will attempt to create a pidfile, and do a bunch of other stuff that isn't really needed.

We should short-circuit this logic, or move the `--check_config` option to osqueryi.

**Comment by theopolis** [comment]
I vote to short circuit some unneeded initialization steps, at least.

On our CentOS fleet we use an extension to deliver the config so we need to do a few initialization steps before we have a chance to consume config data. The shell can load extensions, so theoretically we could replicate in osqueryi too.

**Comment by marpaia** [comment]
fixed in 6dd92bd051af9f734c3bb19951a4f5ccbdc16777
