### ISSUE TITLE
Merge quarantine and xattr_where_from tables

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#932]
Both parse xattrs and I *think* quarantine implies where_from?

**Comment by jedi22** [comment]
The plan for this, after talking with @theopolis, is to parse each each field out into it's own set of rows, meaning that each extended attribute could create multiple rows per file.

Also to making it cross platform

**Comment by theopolis** [comment]
Considerations: 

- extended attributes for filesystems is cross-OS and cross-FS; Linux supports multiple filesystem types, are you going to support extended attributes for ext3/4/rfs/etc?
- xattrs are mostly application-defined, parsers/keys are also mostly known way before compile time.
- some xattrs are structures of several attributes (like where_from)
- some attribute values may be non-string & non-ASCII
- resistance to attribute key/value/structure is paramount

**Comment by jedi22** [comment]
These tables are now merged, we will handle any other filesystem implementations in their own task
