### ISSUE TITLE
Add LUKS/dm-crypt FDE on Linux.

### ISSUE THREAD

**Issue by sharvilshah** [facebook/osquery#933]
Since we now have `disk_encryption` table which tracks OS X filevault, we can add LUKS/Linux support to it.

Migrated TODO from #913 
- [ ] Linux implementation
- [ ] Test `disk_encryption` table
- [ ] Documentation.

**Comment by theopolis** [comment]
FYI: I missed this in the PR code review before, but wanted to let you know I [moved](https://github.com/facebook/osquery/commit/d8d1ee70724bb3ae3cad689a4752922717758101) the table spec into "darwin" from "x". You might have to rebase then move it back to "x" for your next PR when you add the table to Linux. 

If the .table file is in "x" then Linux-based builds will look for the specified symbol, in this case `genFDEStatus`.

**Comment by sharvilshah** [comment]
Thanks, yeah I should have caught that. Was relying on the Jenkins/CI bot for linux builds but maybe it doesn't automatically test the pull request.

**Comment by theopolis** [comment]
Jenkins should have caught misplaced .table file, 100% not your fault, haha! It definitely started catching after the PR was merged.

For libcryptsetup-dev:
- Instead, are there details we can pull from /proc or /sys about device mapper? libdm should add LUKS notes to encrypted devices.
- Can we compile/link a static libcryptsetup?

**Comment by sharvilshah** [comment]
* Found nothing relating to FDE in procfs or sysfs except the cipher suites the kernel supports (/proc/crypto). AFAIK (judging by manpage of `dmsetup`) libdm only manages low level LVM. 

And the `dm-crypt` target (cryptsetup is a frontend to dm-crypt like dmsetup is to libdm) AFAIK only does encryption of block devices, `libcryptsetup` is what does key management and writes LUKS headers to the LVM. At least according to [this outdated wiki](http://www.saout.de/misc/dm-crypt/):

> The latest version of the native userspace setup tool is cryptsetup 0.1.
Clemens Fruhwirth is maintaining an enhanced version of cryptsetup with the LUKS extension that allows you to have an on-disk block of metadata which is superior to the current mechanism and was my long term plan anyway but I didn't find the time to implement that yet...

Will probably need to get and use the sources.

* Linking a static libcryptsetup:

I am not sure about this, need to experiment. Here are the dependencies on ubuntu14:
```bash
vagrant@vagrant-ubuntu-trusty-64:/lib$ objdump -p libcryptsetup.so.4.5.0  | awk '/ NEEDED / { print $2 }'
libuuid.so.1
libdevmapper.so.1.02.1
libgcrypt.so.11
libc.so.6
```

I am not sure whether libuuid and libdevmapper are already part of the distro, I am assuming so. Also reasonable to assume libgrcypt (which I think cryptsetup uses for key derivation and stretching) is present since apt and yum probably depend on it to verify signatures. Again just my assumptions, need to verify it, unless you already have the answers to them.

**Comment by theopolis** [comment]
Perfect, looks like the cryptosetup APIs are the most appropriate. From what I have installed (VMs for osquery dedicated development), those dependent dynamic libs exist on CentOS, RHEL 6.5, and Ubuntu 14.04.

**Comment by sharvilshah** [comment]
Cool. Okay to pull down that library via `provision.sh` or do you still want me to try and statically link `libcryptsetup-dev.a`?

Also where is the RHEL image, it's not defined in the Vagrantfile. It doesn't really matter since CentOS and RHEL probably have the exact same libraries, but I want to test things out more thoroughly (and try and not break builds).

**Comment by theopolis** [comment]
If you create a PR, our Jenkins webhooks *should* pull the code and build on each OS. Feel free to pull in packages in the `provision.sh` script (which is now a wrapper for distro-specific shell scripts). If the `-devel` package installs a `.a`, perfect, otherwise link to the shared library. I can tweak the build/provision to build statically later.

RHEL build hosts are coming soon, we're working through the subscription fee details now. Confirming that our Jenkins builds/tests correctly for CentOS 6.5/7 is good enough for RHEL now. We've only seen discrepancies in RPM package names and their version dependency lists.

**Comment by sharvilshah** [comment]
@theopolis:

Spent way too much time debugging why FDE status reporting was flaky on my linux VM.
Turns out `libcryptsetup` calls into `libdevmapper` (part of libcryptsetup), which checks if it's being called as root, and only initializes the device context if it's called as root. Otherwise it returns an error: "No such mapped device".

When it is being called as root, it returns status as expected. 
This isn't ideal, what do you suggest I do?

Implement it as is and document that, or try to override devicemapper calls? It seems that it checks if root ,for all devicemapper functions. But since we are only calling for status and not doing any creation/deletion/modification we *might* be able to override it and get by (haven't tried it yet).

**Comment by theopolis** [comment]
Wow, nice work! We can add a euid/uid check in the table implementation code to make sure the invoker is 0. If you're not root then we return nothing. Unless there's a more appropriate privilege check that mimics the dev mapper check?

**Comment by sharvilshah** [comment]
I like checking for euid/uid, simple and works.

**Comment by theopolis** [comment]
Hey @sharvilshah are we all wrapped up with disk_encryption? Is there anything else you wanted to commit as part of this issue? I'm cutting a debug build and running on a few CentOS machines. Looks great!

**Comment by sharvilshah** [comment]
@theopolis Yup, disk_encryption is all wrapped up.
