### ISSUE TITLE
Question: How to populate file_changes

### ISSUE THREAD

**Issue by blackfist** [facebook/osquery#939]
I'm experimenting with `osquery` on OSX and I can't seem to get anything to show up in the file_changes table. My configuration file in `/var/osquery/osquery.conf` looks like this:

```
{
  "options": {
    "host_identifier": "hostname",
    "schedule_splay_percent": 10
  },
  "scheduledQueries": [
    {
      "name": "time",
      "query": "select * from time;",
      "interval": 1
    }
  ],
  "additional_monitoring" : {
    "file_paths": {
      "system_files": [
    "/etc"
      ],
      "core_binaries": [
        "/bin/"
      ],
      "other_binaries":[
        "/sbin/",
    "/usr/sbin"
      ]
    }
  }
}
```

Which I totally stole from one of the closed issues here on github. Then I run `osqueryd` and manually make a change to a file in `/etc`. But when I open `osqueryi` I don't see anything in the file_changes table.

`select * from file_changes;`

Can you suggest where I might look to figure out why this isn't working?

**Comment by jedi22** [comment]
If this is on OS X, try listening to /private/etc/ because that is the true location of /etc/.

Let me know if that fixes the problem or if it's not OS X.

**Comment by theopolis** [comment]
Hey! osqueryd and osqueryi are completely different tools, they don't communicate. To test the file changes monitoring features load osqueryi using that config, modifiy a file, then select and see the changes.

To see changes with osqueryd, you'll need to schedule a query to select from file_changes, then monitor the results log. Hope that helps!

**Comment by blackfist** [comment]
ooooh! Thanks. I'll give that a try.

**Comment by blackfist** [comment]
Alright I'm having trouble getting `osqueryd` to work for me but I'll put that in a different issue.
