### ISSUE TITLE
file_changes paths not being added

### ISSUE THREAD

**Issue by DoomCode** [facebook/osquery#948]
I have been testing osquery on Ubuntu 12.04 and CentOS 7. I cannot get the paths to be added correctly for file_changes monitoring. They seem to be added correctly if a wildcard character is included in the path but not if I have an absolute path. Am I configuring this incorrectly, or is there a bug here?

Here is my config followed by the debug output that pertains to the paths.

{
   "options":{
      "config_plugin":"filesystem",
      "logger_plugin":"filesystem",
      "osquery_log_dir":"/var/log/osquery",
      "disable_logging":"false",
      "log_result_events":"true",
      "schedule_splay_percent":"10",
      "host_identifier":"hostname",
      "pidfile":"/var/osquery/osquery.pidfile",
      "event_pubsub": "true",
      "event_pubsub_expiry":"86000",
      "db_path":"/var/osquery/osquery.db",
      "debug":"false",
      "verbose_debug":"false",
      "worker_threads":"4"
   },
   "scheduledQueries":[
      {
         "name":"proccess_on_disk",
         "query":"SELECT * FROM processes WHERE on_disk = 0;",
         "interval":3600
      },
      {
         "name":"file_changes",
         "query":"SELECT * FROM file_changes;",
         "interval":60
      }
   ],
   "additional_monitoring":{
      "file_paths":{
         "system_binaries":[
            "/bin/bash",
            "/bin/zsh"
         ],
         "configuration":[
            "/etc/osquery/osquery.conf",
            "/etc/hosts"
         ],
         "cron":[
            "/etc/cron.%%"
         ],
         "user_credentials":[
            "/etc/passwd",
            "/etc/shadow",
            "/etc/group",
            "/etc/gshadow",
            "/etc/security/opasswd"
         ]
      }
   }
}

I0406 18:22:44.537039 30784 interface.cpp:249] Extension manager service starting: /var/osquery/osquery.em
I0406 18:22:44.617050 30777 file_changes.cpp:61] Added listener to: /etc/cron.weekly
I0406 18:22:44.617213 30777 file_changes.cpp:61] Added listener to: /etc/cron.monthly
I0406 18:22:44.617357 30777 file_changes.cpp:61] Added listener to: /etc/cron.hourly
I0406 18:22:44.617535 30777 file_changes.cpp:61] Added listener to: /etc/cron.d
I0406 18:22:44.617760 30777 file_changes.cpp:61] Added listener to: /etc/cron.daily

**Comment by theopolis** [comment]
I spoke with @jedi22 a bit. He thinks this is a bug in the globbing code: https://github.com/facebook/osquery/blob/master/osquery/filesystem/filesystem.cpp#L284
