### ISSUE TITLE
YARA table

### ISSUE THREAD

**Issue by wxsBSD** [facebook/osquery#952]
Now that the YARA subscriber has landed in master I'm taking the chance to implement a YARA table, which uses constraints to determine what to scan. The difference between this table and ```yara_matches``` is that this table would be used for on-demand or scheduled queries, as opposed to event-based changes in ```yara_matches```. The usage would look something like this:

```
select * from yara where path='/bin/sh';
select * from yara where path like '/bin/%sh';
```

The first one would scan an individual file while the second one would expand out to multiple files for scanning.

The question now becomes how do I specify which signature files to use. For that I was thinking of changing the config block to look like this:

```
{
  // Description of the YARA feature.
  "yara": {
    "signatures": {
      // Each key is an arbitrary group name to give the signatures listed
      "sig_group_1": [ "foo.sig", "bar.sig" ],
      "sig_group_2": [ "baz.sig" ]
    },
    "file_paths": {
      // Each key is a key from file_paths in additional_monitoring
      // The value is a list of signature groups to run when an event fires
      // These will be watched for and scanned when the event framework fire off an event
      // to yara_matches table
      "system_binaries": [ "sig_group_1" ],
      "tmp": [ "sig_group_1", "sig_group_2" ]
    }
  },
  
  // Scheduled queries to be run on a periodic basis. Nothing new here...
  "scheduled_queries": ["select * from yara where path=\"/bin/sh\""],
  
  // Event based things that will be monitored
  "additional_monitoring": {
    // Paths to watch for filesystem events
    "file_paths": {
      "system_binaries": [ "/usr/bin/%", "/usr/sbin/%" ],
      "tmp": [ "/tmp/%%" ]
    }
  }
}
```

Essentially I would be putting the description of the YARA configuration in the ```yara``` top level key. It would contain a way to describe the signatures to use and how to group them, and also what signatures to apply to the files being monitored (if any). The list of files being monitored would be handled in the ```additional_monitoring.file_paths``` section as before. The nice thing about this is that the core can handle what to monitor, as it currently does, and leave it up to the individual event subscribers to parse out their configuration during ```init()``` and determine _HOW_ to monitor. This means additional subscribers won't ever have to alter config handling code. 

If a user wants to scan a file with a given signature grouping they can do:

```
select * from yara where path="/bin/sh" and signature_group="sig_group_1";
```

On a related note, I'm thinking I should change ```yara_matches``` to ```yara_file_events``` or something similar. This is for two reasons:

1. It is more descriptive and makes sense if there is also a ```yara``` table.
2. It leaves things open to write a ```yara_process_events``` implementation which would be able to attach to new PIDs and scan them.

**Comment by theopolis** [comment]
Everything looks sound!

I'm trying to pitch removing "additional_monitoring", and we're adopting a "schedule" dictionary:
```
{
  // Description of the YARA feature.
  "yara": {
    "signatures": {
      // Each key is an arbitrary group name to give the signatures listed
      "sig_group_1": [ "foo.sig", "bar.sig" ],
      "sig_group_2": [ "baz.sig" ]
    },
    "file_paths": {
      // Each key is a key from file_paths in additional_monitoring
      // The value is a list of signature groups to run when an event fires
      // These will be watched for and scanned when the event framework fire off an event
      // to yara_matches table
      "system_binaries": [ "sig_group_1" ],
      "tmp": [ "sig_group_1", "sig_group_2" ]
    }
  },

  // Scheduled queries to be run on a periodic basis. Nothing new here...
  "schedule": {
    "yara_example": {"query: "select * from yara where path=\"/bin/sh\"", "interval": 10}
  }

  // Paths to watch for filesystem events
  "file_paths": {
    "system_binaries": [ "/usr/bin/%", "/usr/sbin/%" ],
    "tmp": [ "/tmp/%%" ]
  }
}
```

**Comment by theopolis** [comment]
This is the next iteration/step from: #816

**Comment by marpaia** [comment]
`foo.sig` and `bar.sig` are signature files, right? Is there a default search path for them, since they're not full paths?

**Comment by wxsBSD** [comment]
Sorry, wasn't clear. My intention is to require a full path.

**Comment by wxsBSD** [comment]
Also, sorry for the delay. Been at a conference all week. I'm back on this starting this weekend.

**Comment by marpaia** [comment]
No worries at all :) We could probably make a default home for them something like `$OSQUERY_ROOT/yara`, so `/var/osquery/yara` on OS X and `/etc/osquery/yara` on linux?

**Comment by marpaia** [comment]
Also, will we support being able to do something like:

```sql
select * from yara where signature_file="/path/to/my/one-off/signature/file";
```

**Comment by wxsBSD** [comment]
Yeah. I'll make it check a default directory of an absolute at his not given. Also, the signature_file is on my list too. :)

**Comment by marpaia** [comment]
Like a boss.

**Comment by theopolis** [comment]
Let's consider this resolved and track additional yara capabilities, performance, etc in discrete issues!

**Comment by arpita-chakraborty** [comment]
How I will pass a windows file path like c:\user\program\foo to be monitor in this yara configuration, it is throwing an error when I m passing this path

**Comment by theopolis** [comment]
Hi @arpita-chakraborty, can you open a new issue for your question? This one is outdated and closed.
