### ISSUE TITLE
Move osquery.io links to RTD, replace GH wiki pages with redirects

### ISSUE THREAD

**Issue by theopolis** [facebook/osquery#954]
The osquery.io site repository pages should be updated to point to our now-current RTD urls. We should replace the github wiki pages with textual redirects to the RTD pages for external non-osquery linking.

**Comment by marpaia** [comment]
should we nuke the wiki? are we going to add the same "see http://osquery.readthedocs.org/" text to every page?

**Comment by theopolis** [comment]
We can do one better and replace the existing pages with their RTFD equivalent. Then remove the sidebar and point the wiki entry point to the RTFD introduction with a textual redirect.

**Comment by marpaia** [comment]
oOo, you're out of control, that would be epic. i'll add it to #972
