### ISSUE TITLE
add default flag values to help output

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#959]
Action item off of #944

**Comment by theopolis** [comment]
Actually, we used to have this but the help output looked horrible. We can definitely add it back to `--help`, the values are in the same structure that's iterated to output the `--<KEY_NAME_HERE>` option keys. Either way, we should add a guide for each of these to readthedocs/wiki.

**Comment by marpaia** [comment]
True, that's a good point. What if we had a way to do something like `osqueryd --help config_path` which would then should defaults and extended information?

**Comment by theopolis** [comment]
Definitely doable, do you think that makes sense? We can include in the default `--help` output to run `--help variable_name` for more details. Or write a man page?

**Comment by marpaia** [comment]
Man pages, that's not a bad idea. It would be really neat if we could generate man pages from https://github.com/facebook/osquery/tree/master/docs. Then, we could just maintain the docs and both the wiki and the command line help would be consistent.

**Comment by theopolis** [comment]
All of the document generation methods we support are very powerful, we can script in Python and they will provide a build phase to codegen some additional markdown. It's technical debt right now, we can up for grabs this or spend an upcoming week improving our documentation generation workflows.

**Comment by marpaia** [comment]
I created a master task to talk about the specific things we need to do to improve the state of our docs. I'll close this, let's move conversation there.
