### ISSUE TITLE
os_version table doesn't return expected results on OS X

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#962]
```
osquery> select * from os_version;
major = 14
minor = 1
patch = 0
```

I'm running 10.10.2

**Comment by jedi22** [comment]
This table is populated from the system_controls table. Which is returning this:
```
| kern.version                                             | 1.4               | kern      | Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 |              | string |
| kern.osrelease                                           | 1.2               | kern      | 14.1.0                                                                                           |              | string |
```

**Comment by theopolis** [comment]
Depends on what you expect from "os_version"? 14.1.0 is correct, but is a bit esoteric. We can switch back to the common 10.x.x format. It would be nice to add a "revision" column, and we can emit something like "14.1.0-199506" and in Linux this could be the kernel version or 0?

**Comment by theopolis** [comment]
We can do this with a much needed "software_variables" table and select "productVersion". Should be a quick, non-iterating/non-searching API call.

**Comment by theopolis** [comment]
Can you give master a build and let me know what you think of the os_version table now?

**Comment by marpaia** [comment]
A wise man once told me "everything in osx is a plist".
