### ISSUE TITLE
Repository error on ubuntu 14.04 64bit

### ISSUE THREAD

**Issue by bussiere** [facebook/osquery#964]
Impossible de récupérer https://osquery-packages.s3.amazonaws.com/trusty/dists/trusty/InRelease  Impossible de trouver l'entrée « main/binary-i386/Packages » attendue dans le fichier « Release » :  ligne non valable dans sources.list ou fichier corrompu

It says it's unable ton find main/binary-i386/Packages in the release package

**Comment by bussiere** [comment]
I had to edit my sources.lst and replace the line by : deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/trusty trusty main
regards

**Comment by theopolis** [comment]
Thanks @bussiere, I'll update the docs on the website/wiki ASAP!
