### ISSUE TITLE
snapshot scheduled queries

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#966]
Right now, given the following config, we'll emit a differential of the query results to the results log.

```json
{
  "schedule": {
    "etc_hosts": {
      "query": "select address, hostnames from etc_hosts",
      "interval": 60
    }
  }
}
```

We need to support the following key in the config:

```json
{
  "schedule": {
    "etc_hosts": {
      "query": "select address, hostnames from etc_hosts",
      "interval": 60,
      "snapshot": true
    }
  }
}
```

Note the addition of the *snapshot* key. Instead of emitting differentials whenever this data changes (and nothing if the data doesn't change), this should emit a full snapshot of the query every time the query is ran. 

Such a log should look like the following, expanded on to multiple lines for readability:

```json
{
    "name": "etc_hosts",
    "hostIdentifier": "marpaia-mbp.dhcp.thefacebook.com",
    "calendarTime": "Tue Apr  7 15:09:57 2015",
    "unixTime": "1428444597",
    "snapshot": [
        {
            "address": "127.0.0.1",
            "hostname": "localhost"
        },
        {
            "address": "255.255.255.255",
            "hostname": "broadcasthost"
        },
        {
            "address": "::1",
            "hostname": "localhost"
        }
    ],
    "action": "snapshot"
}
```

Note that *action* is now *snapshot* and the results are emitted in a top-level *snapshot* key.

**Comment by theopolis** [comment]
Merged: https://github.com/facebook/osquery/commit/13c4e27629e1cd04f89f27129647b4a3b5919a7d
