### ISSUE TITLE
[master task] documentation overhaul

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#972]
Our lack of significantly robust documentation generation, publication, etc need to be solved by dedicating the appropriate amount of engineering effort to the problem. Let's use this issue to organize the tasks required to up our documentation skills.
- [ ] generate man pages from the wiki documentation markdown
- [x] replicate /docs to the GitHub Wiki for this project
- [x] automate the publishing of table API documentation
- [ ] publish public API docs alongside table docs
- [ ] publish documentation for event publishers and subscribers
- [x] add "make docs" to the jenkins CI runlist

**Comment by marpaia** [comment]
The genesis of this issue was the conversation that took place in #959

**Comment by theopolis** [comment]
I just deprecated the github wiki pages and updated links to redirect to RTD.

**Comment by marpaia** [comment]
are there many places that reference the old wiki that we should care about updating?

**Comment by marpaia** [comment]
So it https://github.com/facebook/osquery/wiki/using-osqueryd supposed to redirect to http://osquery.readthedocs.org/introduction/using-osqueryd/ ?

**Comment by marpaia** [comment]
Also, I love the checkboxes: 
![screen shot 2015-04-09 at 11 11 37 pm](https://cloud.githubusercontent.com/assets/927168/7082760/dbee4a86-df0d-11e4-9cc3-67a3de89aba4.png)

**Comment by marpaia** [comment]
Ah never mind about my last question, I see your commit to master updating the readme. Do you think there are any other places (blog articles, etc) that we should worry about updating with old wiki links?

**Comment by theopolis** [comment]
The links are still valid but each "old" page is a simple shell saying: Page moved <URL to new RTD page>. ;)

**Comment by theopolis** [comment]
Page moved: (URL to new RTD page link)

**Comment by marpaia** [comment]
When I go to https://github.com/facebook/osquery/wiki/using-osqueryd, I get 302'd to the homepage:

```
[marpaia-mbp] ~ curl https://github.com/facebook/osquery/wiki/using-osqueryd --verbose
* Hostname was NOT found in DNS cache
*   Trying 192.30.252.129...
* Connected to github.com (192.30.252.129) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
* Server certificate: github.com
* Server certificate: DigiCert SHA2 Extended Validation Server CA
* Server certificate: DigiCert High Assurance EV Root CA
> GET /facebook/osquery/wiki/using-osqueryd HTTP/1.1
> User-Agent: curl/7.37.1
> Host: github.com
> Accept: */*
>
< HTTP/1.1 302 Found
* Server GitHub.com is not blacklisted
< Server: GitHub.com
< Date: Fri, 10 Apr 2015 07:43:56 GMT
< Content-Type: text/html; charset=utf-8
< Transfer-Encoding: chunked
< Status: 302 Found
< Content-Security-Policy: default-src *; script-src assets-cdn.github.com collector-cdn.github.com; object-src assets-cdn.github.com; style-src 'self' 'unsafe-inline' 'unsafe-eval' assets-cdn.github.com; img-src 'self' data: assets-cdn.github.com identicons.github.com www.google-analytics.com collector.githubapp.com *.githubusercontent.com *.gravatar.com *.wp.com; media-src 'none'; frame-src 'self' render.githubusercontent.com gist.github.com www.youtube.com player.vimeo.com checkout.paypal.com; font-src assets-cdn.github.com; connect-src 'self' live.github.com wss://live.github.com uploads.github.com status.github.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com
< Cache-Control: no-cache
< Vary: X-PJAX
< Location: https://github.com/facebook/osquery
< X-UA-Compatible: IE=Edge,chrome=1
< Set-Cookie: _gh_sess=eyJzZXNzaW9uX2lkIjoiZTM0YWE3YWQ5ODMzYzNiNTg4NDJmN2FjOGY2MDRhYTkiLCJzcHlfcmVwbyI6ImZhY2Vib29rL29zcXVlcnkiLCJzcHlfcmVwb19hdCI6MTQyODY1MTgzNn0%3D--c576e74cb466bbbe85d83b4563f10763883e40a1; path=/; secure; HttpOnly
< X-Request-Id: 3fbaffb3c5f229226e7678e093909aa8
< X-Runtime: 0.007111
< X-GitHub-Request-Id: C7C94002:6CB5:95187D:55277F3C
< Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Frame-Options: deny
< Vary: Accept-Encoding
< X-Served-By: a568c03544f42dddf712bab3bfd562fd
<
* Connection #0 to host github.com left intact
<html><body>You are being <a href="https://github.com/facebook/osquery">redirected</a>.</body></html>
```

**Comment by theopolis** [comment]
Oh no! I wonder if your turn off the wiki Github will 302 to the project main page. We can fix this by turning the wiki back on

**Comment by marpaia** [comment]
Do you think it's worth it? I don't mind not having a GitHub Wiki.

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by thedrow** [comment]
We can use the wiki for community resources such as additional bundles and extensions.
