### ISSUE TITLE
[master task] osqueryi overhaul

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#973]
osqueryi is an extended version of the SQLite shell, which means it has inherited a lot of functionality (and technical debt) that we don't need / which is hard to maintain. Let's use this issue to organize and brainstorm ways that we can make using `osqueryi` a better user experience.

- [ ] tab completion for columns and tables
- [ ] way to natively browse table documentation
- [ ] organize `.tables` with categories
- [ ] move modes into a `--mode` (support existing, silently)
- [ ] skip publisher, thrift server and thread pool creation when CLI/stdin query set (see thread backtrace in #1237)

**Comment by facebook-github-bot-5** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
