### ISSUE TITLE
Add platform and distro value to the table osquery_info

### ISSUE THREAD

**Issue by javuto** [facebook/osquery#989]
During compilation, we do get the value of PLATFORM and DISTRO to compile for the exact target. This information can be used for loading queries and could be added to the osquery_info table. Let's do it.

**Comment by theopolis** [comment]
Hey @javuto to avoid confusion what do you think about naming the columns: `build_distro` and `build_version`? That way if you somehow execute a CentOS-build osqueryi on a RHEL or Oracle/SL machine you aren't confused when osquery_info still reports centos/6.5.

**Comment by javuto** [comment]
Sounds good, I'll use those names for the columns.It achieves perfectly what I am looking for.

**Comment by marpaia** [comment]
tracking in #997
