### ISSUE TITLE
installed clang downgraded from 3.5 to 3.4 after make deps on ubuntu14

### ISSUE THREAD

**Issue by marpaia** [facebook/osquery#995]
I noticed that my clang got downgraded from 3.5 to 3.4 after a run of `make deps`. This makes sense, as we're pinning to 3.4 in provision: https://github.com/facebook/osquery/blob/master/tools/provision/ubuntu.sh#L35-L36

Thoughts on updating our clang to 3.5?

**Comment by theopolis** [comment]
I had a lot of success with 3.7 from the LLVM-maintain apt repos. I'd prefer we keep our compiler relatively similar across all platforms. We can choose to upgrade, but we should upgrade unilaterally. 

CentOS7: 3.4.2, gcc: 4.8.3-9
Apple: 3.5(appl6.0), gcc: 4.2?
RHEL 6.5: 3.4.2, gcc: 4.9.1-1
Ubuntu14: 3.4.1, gcc: 4.8.2

**Comment by marpaia** [comment]
we could publish our own clang-3.7 packages on pkg.osquery.io?

**Comment by theopolis** [comment]
Built for our supported vagrant boxes? We can build and pull them down using provision from S3 like our other provision-installed from-source tarballs. The difference here being we've pre-built LLVM/clang. But I'd hesitate to advertise them via a web UI for general consumption.

**Comment by marpaia** [comment]
no, for sure, i don't think we should become advertised publishers of popular linux packages, but we have all of the infrastructure to build and distribute packages for a variety of operating systems. why are we building ANYTHING from source other than osquery?

**Comment by theopolis** [comment]
Same question: why are we building osquery from source?

Advantages we get today:
- compile-time linking against the building machine's libraries. If you're building osquery from source with the intent of distribution, this matters.
- architecture independence. Although x86_64 is the osquery-arch to rule them all, one could experiment with arm rather easily. We haven't been explicit or anything close to including an architecture call out in our supported distribution list.
- Compiler flexibility. I test/analyze/lint with bleeding edge compilers at home, building all of our dependencies from source catches neat things. (We've patched a few in our third-party-based sources too!)
- Debug + optimized flexibility. Stepping with non-optimized targets is less frustrating. We'd have to include a -debuginfo for each built-package. NBD, but just saying.

A provision of a more-recent compiler than that shipped by the target platform/distribution benefits the enterprising builder and (slightly) our build hosts. Might be a bit of an over optimization now that I think about it. What's the advantage of having 3.4+ over 3.4? And how much infra/work/testing is required to add that to the provision responsibilities?

**Comment by marpaia** [comment]
> compile-time linking against the building machine's libraries. If you're building osquery from source with the intent of distribution, this matters.

Totally, but if we offered packages for libglog.a, and you happened to have your own libglog.a, you could presumably just use your own. you probably know enough about libraries and linking to figure out what we're doing to manage dependencies and insert your own in there. 

If you were concerned about distribution (like what we've seen with OS X and homebrew libs before), then I would imagine our packages would be even better for people to build osquery with, because we've used the more sane flags.

> architecture independence. Although x86_64 is the osquery-arch to rule them all, one could experiment with arm rather easily. We haven't been explicit or anything close to including an architecture call out in our supported distribution list.

This is true, but if we built all dependencies from source on our build hosts to publish packages, maybe then we could add an arm build host and, as long as it had a c compiler, we could build our deps and publish packages. This is a bit of a stretch.

> Compiler flexibility. I test/analyze/lint with bleeding edge compilers at home, building all of our dependencies from source catches neat things. (We've patched a few in our third-party-based sources too!)

This is fair. The naive argument is definitely "well, you only care about bugs in YOUR code, not third-parties", but clearly, we often have to. I think it's a trade off. Developer velocity in the form of build time vs static analysis flexibility.

> Debug + optimized flexibility. Stepping with non-optimized targets is less frustrating. We'd have to include a -debuginfo for each built-package. NBD, but just saying.

Yeah, I'm sure the road to actually doing this is paved with sharp objects, just like this one.

> What's the advantage of having 3.4+ over 3.4? And how much infra/work/testing is required to add that to the provision responsibilities?

This is a great point. There's also value in using a more ubiquitously supported compiler. The same debate can be made for any update, as it should. 

I think that upgrading something that doesn't have good packages, across all of our build OS's is something that often stops us from upgrading dependencies if/when we want to. Of course, this is because of technical complexity, value proposition, etc. I don't think that it should. Or rather, I think that we would at least use more new software if we knew that it was easy and Responsible Of Us to distribute new build dependencies.

**Comment by theopolis** [comment]
Alternatively we can include a make clang

**Comment by theopolis** [comment]
I think the solution for trusty is an extra conditional in the provision script to install 3.4 on precise, 3.5 on trusty and call it a day for now.
