### ISSUE TITLE
additional_monitoring ignore option

### ISSUE THREAD

**Issue by isafe** [facebook/osquery#996]
Hi,I used osquery  monitor the system files(monitor /etc/ all files).
when i use vim/vi editor some file (/etc/reslov.conf),it generation xxx.swp,how ignore it?

**Comment by theopolis** [comment]
Good idea @isafe. You'd like to define something similar to:

```json
"file_paths": {
  "all_etc": [
    "/etc/%%",
    "!/etc/%.swp",
  ]
}
```

Where an included `!` in the beginning of a path is an ignore. @jedi22 an ignore option for each category of monitored files might be nice. Thoughts?

**Comment by isafe** [comment]
Thangk you! It's work fine.

**Comment by isafe** [comment]
I test on centos 6.6 64bits ,osquery-1.4.4-1.el6_6.5.x86_64.rpm,it's don't work~

**Comment by theopolis** [comment]
What about the RPM doesn't work?

**Comment by isafe** [comment]
{"name":"Critical Files modified","hostIdentifier":"localhost","calendarTime":"Thu Apr 16 11:26:54 2015","unixTime":"1429154814","columns":{"action":"DELETED","category":"config_files","md5":"","sha1":"","sha256":"","target_path":"\/etc\/.resolv.conf.swp","time":"1429154791","transaction_id":"0"},"action":"added"}

**Comment by theopolis** [comment]
Oh, there's no way to ignore files just yet, we'll need to write it :)

**Comment by isafe** [comment]
Thank for your quickly reply.

**Comment by theopolis** [comment]
This is going to take a bit of work. I'm removing this from a 1.4.5 blocker and we'll get back to work on it after the next release.

**Comment by theopolis** [comment]
I'm going to label this "wont-fix" since it'll be an extreme amount of complexity to add to the publisher/subscribe logic. To ignore events it is better to add a `WHERE path NOT LIKE '%.swp'` in the query schedule. This will cause those spurious events to be buffered/written into RocksDB but there should be an acceptable amount of optimization such that they are negligible.
